### YamlMime:Yaml
ms.openlocfilehash: 282571a1bae6394b9bcd2c235c5d3a2e9fa26a43
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139899206"
Slug: a-sample-application-for-pulling-data-from-the-web-into-an-azure-event-hub
Title: 웹에서 Azure Event Hub로 데이터를 끌어 오는 샘플 애플리케이션
Summary: 제어하지 않는 공개 웹 사이트에서 데이터를 끌어온 다음 해당 데이터를 Azure Event Hub로 푸시하는 방법을 알아봅니다.
Content: >-
  <p>제어하는 디바이스에서 Azure로 데이터를 푸시하고 다른 스트리밍 또는 정적 데이터와 함께 분석하는 방법에 대한 <a href="https://azure.microsoft.com/en-us/documentation/articles/?suite=iot-suite">문서 문서</a> 및 <a href="https://azure.microsoft.com/en-us/documentation/samples/?service=iot-hub">코드 샘플</a> 이 많이 있습니다.</p>


  <p>문서화되지 않은 내용은&rsquo; 제어하지 않는&rsquo; 공개 웹 사이트에서 데이터를 끌어온 다음 해당 데이터를 Azure Event Hub로 푸시하는 방법입니다. Dinar Gainitdinov로 만든 최근 문서 및 코드 샘플은 몇 줄의 C#으로 간단한 애플리케이션을 빌드하는 방법을 보여줍니다. 이 코드의 강화된 버전을 사용하여 실시간 자동차 데이터를 Microsoft Dynamics의 유지 관리 레코드와 결합하고 다른 버전을 사용하여 시애틀 지역의 트래픽이 날씨에 의해 어떻게 영향을 받는지 분석했습니다. 물론 웹 사이트에서 저작권이 있는 데이터를 수집하지 않고 모든 사용 약관을 준수해야 합니다.</p>


  <p><a href="https://azure.microsoft.com/en-us/documentation/articles/event-hubs-pulling-public-data/">기술 설명서</a> 및 GenericWebToEH 솔루션 코드를 확인하여 즐겨 찾는 데이터 피드 중 일부를 사용해 보세요.</p>
