### YamlMime:Yaml
ms.openlocfilehash: 4ea45a3f8e91b3d2d2c228e80e79f1668e53ba04
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139899188"
Slug: accelerate-application-modernization-with-azure-migrate-app-containerization
Title: 'Azure Migrate를 사용하여 애플리케이션 현대화 가속화: 앱 컨테이너화'
Summary: '조직이 더 민첩하고 운영적으로 효율적으로 되기 위해 클라우드 중심 비즈니스 변환에 착수함에 따라 애플리케이션 현대화는 이러한 목표를 실현하기 위한 초석이 되고 있습니다. 이 블로그에서는 Azure Migrate: 앱 컨테이너화 도구를 사용하여 애플리케이션을 Azure로 마이그레이션할 때 애플리케이션 현대화를 가속화하는 방법을 알아봅니다.'
Content: >-
  <p>조직이 더 민첩하고 운영적으로 효율적으로 되기 위해 클라우드 중심 비즈니스 변환에 착수함에 따라 애플리케이션 현대화는 이러한 목표를 실현하기 위한 초석이 되고 있습니다. 이 블로그에서는 <a href="https://aka.ms/AzureMigrate/Containerize" target="_blank">Azure Migrate:&nbsp;App Containerization</a> 도구를 사용하여 애플리케이션을 Azure로 마이그레이션할 때 애플리케이션 현대화를 가속화하는 방법을 알아봅니다.</p>


  <p>Azure를 사용하면 IaaS(Infrastructure-as-a-Service), PaaS(Platform-as-a-Service), CaaS(Containers-as-a-Service) 및 서버리스의 스펙트럼에 걸쳐 있는 애플리케이션에 대한 다양한 호스팅 옵션 중에서 유연하게 선택할 수 있습니다. Azure App Service 및 AKS(Azure Kubernetes Service)와 같은 Azure 제품은 애플리케이션 개발자가 가장 중요한 비즈니스 문제를 해결하는 데 집중할 수 있도록 지원합니다. 기본 제공 인프라 유지 관리, 보안 패치 및 크기 조정을 통해 Azure App Service는 웹 기반 애플리케이션을 실행하기 위한 용도로 빌드된 플랫폼입니다. Azure App Service는 가장 인기 있는 애플리케이션 프레임워크를 기본적으로 지원하며, 또한 사용자 지정 Windows 또는 Linux 컨테이너를 사용하여 컨테이너화된 애플리케이션을 실행할 수도 있습니다. AKS는 인프라를 보다 잘 제어하려는 경우 컨테이너화된 애플리케이션을 실행하는 데 적합합니다.</p>


  <p>컨테이너는 최신 애플리케이션을 빌드하고 관리하는 데 매우 널리 사용되고 있습니다. 애플리케이션을 컨테이너로 배포하면 애플리케이션 소유자와 IT 의사 결정자가 환경 전체에서 일관되고 안정적이며 반복 가능한 배포를 실현할 수 있습니다. 또한 인프라 사용률 향상 및 문제 분리를 통한 관리 관행 표준화가 이점에 포함됩니다. 고객은 마이크로 서비스 아키텍처를 사용하도록 설계된 분산 애플리케이션뿐만 아니라 상당한 변경 없이 다시 플랫폼화되는 다른 애플리케이션에 대해서도 애플리케이션 배포 단위로 컨테이너를 점점 더 많이 사용하고 있습니다. 다시 플랫폼화는 애플리케이션의 추가 현대화에 착수하기 전의 첫 번째 단계인 경우가 많습니다. 고객은 애플리케이션을 완전히 다시 조정하거나 리팩터링할 필요가 없거나 신중하지 않을 수 있는 많은 경우에 컨테이너로 다시 플랫폼화하는 것을 선호합니다.</p>


  <p>올해 초 Microsoft Ignite에서는 AKS로 앱을 쉽게 컨테이너화하고 마이그레이션하는 데 도움이 되는 Azure Migrate: 앱 컨테이너화 도구의 미리 보기를 발표했습니다. 받은 피드백&rsquo;에 따라 오늘 미리 보기에 대한 여러 개선 사항을 발표합니다.</p>


  <h2>Azure Migrate를 사용하여 애플리케이션 다시 패키지: 앱 컨테이너화</h2>


  <p>앱 컨테이너화 도구는 애플리케이션의 실행 상태를 사용하여 최소한의 코드 변경 없이 애플리케이션을 컨테이너로 다시 패키징하는 지점 및 컨테이너화 접근 방식을 제공합니다. 이 도구는 현재 Apache Tomcat에서 실행되는 ASP.NET 애플리케이션 및 Java 웹 애플리케이션의 컨테이너화를 지원합니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/f55ca690-0a99-48ce-a3aa-902a037280f8.jpg"><img alt="Modernization capabilities of Azure Migrate: App Containerization" border="0" height="570" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/d42a92ec-759a-42fc-9849-1eb8e681b2c0.jpg" style="border: 0px currentcolor; border-image: none; display: inline; background-image: none;" title="Azure Migrate의 현대화 기능: 앱 컨테이너화" width="1085"></a></p>


  <p><em><strong>그림 1:</strong> Azure Migrate의 현대화 기능: 앱 컨테이너화</em></p>


  <p>이 도구를 사용하면 다음을 수행할 수 있습니다.</p>


  <ul style="margin-left: 40px;">
      <li>독립 실행형 앱 컨테이너화 유틸리티를 사용하여 애플리케이션 및 해당 구성을 검색하기 위해 애플리케이션 서버에 원격으로 연결합니다.</li>
      <li>일관성 있고 반복 가능한 배포를 용이하게 하려면 애플리케이션 구성 및 데이터베이스 연결 문자열과 같은 종속성을 매개 변수화합니다.</li>
      <li>영구 스토리지로 이동하여 파일 시스템에 저장된 정적 콘텐츠 및 애플리케이션 상태를 외부화합니다.</li>
      <li>Azure Container Registry 작업을 사용하여 컨테이너 이미지를 빌드하고 게시합니다.</li>
      <li>Dockerfiles, 컨테이너 이미지 및 Kubernetes 리소스 정의 파일과 같은 도구 생성 아티팩트(예: 2일차 작업)를 사용자 지정하고 다시 사용하고 CI/CD(지속적인 통합 및 지속적인 업데이트) 파이프라인에 직접 통합합니다.</li>
  </ul>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/48df2ab2-59a5-4704-a342-44a17a98ac18.jpg"><img alt="Downloadable and reusable artifacts for Day 2 operations" border="0" height="683" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/5119ffd3-a1ef-491b-aa33-6f6634e64aec.jpg" style="border: 0px currentcolor; border-image: none; display: inline; background-image: none;" title="2일차 작업에 대해 다운로드 가능하고 재사용 가능한 아티팩트" width="1024"></a></p>


  <p><em><strong>그림 2:</strong> 2일차 작업에 대해 다운로드 가능하고 재사용 가능한 아티팩트</em></p>


  <h2>애플리케이션 배포 및 관리를 위한 새로운 향상된 기능</h2>


  <p>이제 도구의 최신 릴리스를 사용하여 다음을 수행할 수 있습니다.</p>


  <ul style="margin-left: 40px;">
      <li>컨테이너화된 애플리케이션을 Azure App Service 컨테이너 또는 AKS에 배포합니다.</li>
      <li>Azure Key Vault를 사용하여 인증서 및 매개 변수가 있는 구성과 같은 애플리케이션 비밀을 관리합니다. Kubernetes 비밀 또는 Azure App Service 애플리케이션 설정을 사용하여 비밀을 관리할 수도 있습니다.</li>
      <li>Java 앱에 대한 애플리케이션 모니터링을 Azure Application Insights 자동으로 통합합니다.</li>
  </ul>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/bb50f974-fd06-42cb-aa2b-e4dec0cb5fb8.jpg"><img alt="Automatically enable application monitoring with Azure Application Insights" border="0" height="683" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/c9af1309-2cfa-49d7-8739-7e87a5fce2ce.jpg" style="border: 0px currentcolor; border-image: none; display: inline; background-image: none;" title="Azure Application Insights 애플리케이션 모니터링을 자동으로 사용하도록 설정" width="1024"></a></p>


  <p><em><strong>그림 3:</strong> Azure Application Insights 애플리케이션 모니터링을 자동으로 사용하도록 설정</em></p>


  <h2>시작</h2>


  <p>이러한 향상된 기능을 통해 이제 컨테이너화되지 않은 애플리케이션을 더 쉽게 컨테이너화하고 Azure로 마이그레이션할 수 있는&#39;. Azure Migrate: 앱 컨테이너화 도구는 애플리케이션을 다시 플랫폼화하는 템플릿화된 프로세스를 제공하고 Azure를 사용하여 현대화 과정을 가속화합니다. 오늘 사용해 보세요.</p>


  <ul style="margin-left: 40px;">
      <li><a href="https://aka.ms/migrate/containerization/aspnet" target="_blank">ASP.NET 애플리케이션을 컨테이너화하여 AKS로 마이그레이션</a></li>
      <li><a href="https://aka.ms/migrate/containerization/java" target="_blank">Java 웹 애플리케이션을 AKS로 컨테이너화 및 마이그레이션</a></li>
      <li><a href="https://aka.ms/migrate/containerization/aspnet/appservice" target="_blank">ASP.NET 애플리케이션을 컨테이너화하여 Azure App Service로 마이그레이션</a></li>
      <li><a href="https://aka.ms/migrate/containerization/java/appservice" target="_blank">Java 웹 애플리케이션 컨테이너화 및 Azure App Service로 마이그레이션</a></li>
  </ul>


  <p>Wed&rsquo;는 피드백을 듣는 것을 좋아합니다. <a href="https://aka.ms/appcontainerization/survey" target="_blank">이 양식을 사용하여</a> 어떻게 생각하는지 알려주세요.</p>
