### YamlMime:Yaml
ms.openlocfilehash: cd44a78c8598080aa8ceb924715e53c688897d78
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139899547"
Slug: advancing-indatacenter-critical-environment-infrastructure-availability
Title: 데이터 센터 내 중요 환경 인프라 가용성 발전
Summary: 중요한 환경 인프라 가용성에 영향을 줄 수 있는 여러 가지 요인이 있습니다. 인프라 구성 요소의 안정성, 데이터 센터 생성 단계 동안의 제어, 효과적인 상태 모니터링 및 이벤트 감지 체계, 강력한 유지 관리 프로그램 및 운영 우수성은 모든 작업이 관련 위험 영향을 신중하게 고려하여 수행되도록 합니다.
Content: >-
  <p><em>&ldquo;Azure 클라우드 컴퓨팅 플랫폼의 기반 중 하나는 전 세계 데이터 센터의 IT 인프라에 전원 및 냉각을 제공하는 중요 환경(CE) 인프라의 가용성입니다. <a href="https://www.aka.ms/AdvancingReliability" target="_blank">Ive는 고급 안정성</a>&nbsp;&rsquo;에 대한 오늘의&rsquo; 게시물을 위해 클라우드 운영 및 InnovationEngineering&nbsp; 팀의 안정성 엔지니어링 디렉터 <strong>Randy Kong</strong>에게 이러한 필수 시스템과 관련된 다양한 위험을 식별하고 완화하는 방법을 설명해 달라고 요청했습니다. 다음은 Microsoft와 파트너가 Azure 플랫폼에서 실행하는 중요한 애플리케이션에 대한 세계적 수준의 안정성을 보장하기 위해 Microsoft와 파트너가 이동하는 길이의 개요 및 볼트 하이라이트&nbsp;입니다.&rdquo;&mdash;</em> Mark Russinovich, CTO, Azure</p>


  <hr>

  <p>중요한 환경(CE) 인프라 가용성&mdash;에 영향을 줄 수 있는 여러 가지 요인이 있습니다. 인프라 구성 요소의 안정성, 데이터 센터 생성 단계 동안의 제어, 효과적인 상태 모니터링 및 이벤트 감지 체계, 강력한 유지 관리 프로그램 및 운영 우수성을 통해 모든 작업이 관련 위험 영향을 신중하게 고려하여 수행되도록 합니다.</p>


  <p>Microsoft는 고가용성 CE 인프라 설계, 생성, 시운전 및 운영 분야에서 업계를 선도하는 것 외에도 CE 인프라 가용성을 높이고 유지하기 위해 안정성 엔지니어링 분야에서&mdash; 모범 사례를 개발하고 구현하는 데 투자합니다. 일반적으로 안정성 엔지니어링&quot;&nbsp;은 다양한 오류 모드, &quot;효과 및 메커니즘을 통해 예상되는 수명&mdash; 동안 시스템 기능에 영향을 미칠 수 있는 시간 지연 위험을 사전에 식별하고 평가하는 데 중점을 둔 엔지니어링 분야를 참조합니다. 한 가지 간단한 예로, 에너지 효율이 높은 무료 공기 냉각을 사용하여&nbsp; 데이터 센터를 냉각할 때 제어된 온도, 습도 및 공기 품질 환경을 제공하는 CE 인프라를 확인&rsquo;합니다. 인쇄 회로 기판 어셈블리와 같은 부적절한 조건에서 전기 쇼츠 또는 열기가 발생할 수 있으므로 부식 관련 오류를 방지하는 것이 목적 중 하나입니다.</p>


  <p>하이퍼스케일 클라우드 데이터 센터용 CE는 일반적으로 UPS(무정전 전원 공급 장치), PDU(전력 배전 장치), ATS(자동 전송 스위치), AHU(공기 처리 장치) 및 발전기와 같은 다양한 공급업체 기반&mdash; 구성 요소의 혼합으로 구성됩니다. 이 다중 공급 업체, 다중 기술 환경은 본질적으로 복잡성뿐만 아니라 견고성의 변화를 도입, 주로 공급 업체 역량과 경험에 따라 달라집니다. CE 인프라 상태의 모니터링도 제한됩니다. 예를 들어 이러한 기성품 구성 요소에 대한 정보가 부족하기 때문입니다. 따라서 모니터링은 주로 EPMS(전력 관리 시스템) 또는 BAS(건물 자동화 시스템)와 같은 높은 수준의 &ldquo;오류 효과&rdquo; 감지에 의존합니다.</p>


  <p>그러나 오류 효과 기반 검색 체계는 일반적으로 위반 요소를 신속하게 감지하고 정확히 파악하기 어렵기 때문에 오류가 발생할 때 서비스의 신속한 복구가 지연될 수 있습니다. 글로벌 운영의 규모는 더 많은&mdash; 과제를 추가하지만, 지역 조건의 변화는 일반적으로 시간 기반 예방 유지 관리 접근 방식의 효과에 대한 문제를 제기하는 장비&mdash;에 다른 스트레스를 초래할 수 있습니다. 일부 지리적 영역은 온도, 습도 또는 대기 품질에 더 주목할 만한 변화를 경험하기 때문에 시간 기반 유지 관리 접근 방식이 낭비되거나 해당 환경 스트레스 조건에서 저하 속도를 고려하지 않으면 시스템 안정성을 새로 고칠&rdquo; 기회를 &ldquo;놓칠 수 있습니다.</p>


  <h2>CE 안정성 엔지니어링에 투자</h2>


  <p>이러한 종류의 문제를 해결하기 위해 Microsoft는 CE 안정성 엔지니어링 기능을 구축하는 데 투자했습니다. 지난 수십 년 동안 전자 산업에서 많은 관련 안정성 엔지니어링 및 기술이&nbsp; 등장했으며, 데이터 센터 CE 인프라에 대한 안정성 모범 사례 및 솔루션을 조정, 확장 및 혁신할 수 있는 충분한 기회가 있습니다. 예를 들어, 기성 CE 구성 요소의 경우 장비 선택 및 자격 단계에서 애플리케이션별 안정성 위험 평가에서 CE 공급업체와 긴밀한 파트너십을 모색해 왔습니다. 또한 운영 단계에서는 공급업체 기반과 긴밀하게 협력하여 개별 사례에 대한 근본 원인 분석&mdash;부터 플릿 전체 상태 동작 데이터 분석에 이르는 심층적인 물리적 및 데이터 분석을 통해 지속적인 개선을 추진합니다. 이러한 파트너 관계를 통해 Microsoft와 공급업체는 관련 안정성 추세, 잠재적 위험 영역 및 기본 기여 요인에 대한 명확한 데이터 기반 가시성을 확보하여 효과적인 해결 방법을 도입할 수 있으며, 더 많은 결과적 영향이 발생하기 전에 사전에 사전에 해결할 수 있습니다. 잠재적인 CE 인프라 위험에 대한 이해를 향상하는 동시에 안정성 엔지니어링은 오류 모드 및 중요도 영역에 대한 메커니즘과 상관 관계가 있는 매개 변수를 캡처하는 등 보다 사전 예방적이고 효과적인 인프라 상태 감지를 초래할 수 있는 RD&amp;(연구 개발) 노력에 중점을 둡니다. 내부 및 외부 파트너십은 데이터 마이닝 및 기계 학습에서 PoF(Physics-of-Failure) 방법론에 이르기까지 관련 접근 방식의 RD&amp;에 설립되었습니다.</p>


  <p>Microsoft가 CE 공간에 혁신을 계속 도입함에 따라 안정성 엔지니어링은 초기 단계 위험 분석 및 완화를 통해 설계 및 기본 제공 안정성을 모두 구동하여 이러한 솔루션의 견고성을 보장하는 데 핵심적인 역할을 하고 있습니다. 예를 들어 <a href="https://www.microsoft.com/security/blog/2020/11/23/iot-security-how-microsoft-protects-azure-datacenters/" target="_blank">Microsoft Sphere 기반 IoT 솔루션</a> 은 기계 및 전력 CE 시스템에서 데이터를 안전하게 획득하기 위해 개발되었습니다. 안정성 엔지니어링은 내부 및 외부 제품 설계 및 제조 파트너와 긴밀하게 협력하여 솔루션 개념, 프로토타입, 디자인, 프로세스 개발 및 제품 배포 단계에서 분석 및 PoF 기반 테스트 접근 방식을 모두 적용합니다. 한 가지 경우는 전자 포장&rsquo; 관련 결함, 제조 또는 조립 중 또는 사용 수명 주기에 대한 우려입니다. FEA(유한 요소 분석)를 기반으로 하는 시뮬레이션 도구는 설계가 여전히 종이에 그리기일 때에도 열 기계적 스트레스 지점을 식별하기 위해 사용되었습니다. 이러한 스트레스 포인트는 예상된 수명 내에서 오류를 초래할 수 있기 때문에. 이러한 지점은 환경 스트레스 테스트 중 또는 제조 공정 단계에서 관련 열 기계적 스트레스를 도입할 수 있는 밀접하게 추적되고 특징지어집니다(예: 스트레인 게이지 포함). 이러한 스트레스를 경험한 후에도 시스템이 여전히 작동할 수 있더라도 샘플은 결함의 초기 개시를 식별하기 위해 중요한 접합부에서 물리적으로 단면화됩니다. 이러한 심층 분석을 통해 동시 제품 또는 프로세스 디자인 변경을 통해 오류 가능성을 제거하여 최종 시스템 가용성을 높일 수 있습니다.</p>


  <p>인프라의 물리적 배포 전에 사전 위험 식별 및 예방 기회를&mdash; 가능하게 하기 위해 복잡한 CE 인프라 자체에 대해서도 유사한 DFX(설계-우수성) 전략을 모색하고 있습니다. 안정성 엔지니어링 분야의 이러한 CE 관련 투자 및 기술 발전은 Microsoft&rsquo; CE 인프라가 세계적 수준의 클라우드 컴퓨팅 서비스에 대한 고객의&rsquo; 가용성 기대치를 충족하기 위해 추가적인 견고성 메커니즘을 구축하는 데 도움이 될 것입니다.</p>
