### YamlMime:Yaml
ms.openlocfilehash: 749e67758f765f82e2652f1696beda4b0eecc004
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139902796"
Slug: advancing-safe-deployment-with-aiops-introducing-gandalf
Title: AIOps를 사용하여 안전한 배포 진행 - Gandalf 소개
Summary: 상태 메트릭의 지속적인 모니터링은 이 프로세스의 기본적인 부분이며 AIOps가 중요한 역할을 하는 부분입니다. 다음 게시물에서는 AI 및 기계 학습을 사용하여 DevOps 엔지니어에게 권한을 부여하고, 대규모로 Azure 배포 프로세스를 모니터링하고, 문제를 조기에 감지하고, 영향 범위 및 심각도에 따라 롤아웃 또는 롤백 결정을 내리는 방법을 소개합니다.
Content: >-
  <p><em>&ldquo;Azure 서비스 및 Azure 플랫폼 자체에 대한 변경은 업데이트, 새로운 기능 및 보안 향상을 지속적으로 제공하는 데 불가피하고 유용합니다. 그러나 변경은 하이퍼스케일 클라우드 공급자, 실제로 모든 IT 서비스 공급자의 안정성 문제에&mdash; 영향을 줄 수 있는 서비스 회귀의 주요 원인이기도 합니다. 따라서 개발 및 배포 출시 중에 가능한 한 빨리 이러한 문제를 파악하여 고객 환경에 미치는 영향을 최소화하는 것이 중요합니다. 지속적인 <a href="https://www.aka.ms/AdvancingReliability" target="_blank">안정성 향상</a> 블로그 시리즈의 일환으로, 오늘 Ive&rsquo;는 AIOps 팀의 수석 프로그램 관리자 <strong>Jian Zhang</strong> 에게 기계 학습을 활용하여 이러한 변경의 위험을 제거하여 궁극적으로 Azure의 안정성을 개선하는 방법을&rsquo; 소개해 달라고 요청했습니다.&rdquo;</em>&mdash; Mark Russinovich, CTO, Azure</p>


  <hr>

  <p><em>이 게시물에는 주요 데이터 과학자 켄 Hsieh와 Ze Li, 수석 데이터 과학자 관리자 인 Yingnong Dang 및 파트너 그룹 소프트웨어 엔지니어링 관리자 무랄리 친탈라파티의 기부금이 포함됩니다.</em></p>


  <p>&nbsp;</p>


  <p>이전 블로그 게시물 &ldquo;<a href="https://azure.microsoft.com/blog/advancing-safe-deployment-practices/" target="_blank">의 고급 안전 배포 사례</a>&rdquo; 에서 Cristina del Amo Casado는 <a href="https://azure.microsoft.com/en-us/" target="_blank">Azure</a> 플랫폼에서 코드 및 구성 변경 모두에 대한 프로덕션 변경 내용을 릴리스하는 방법을 설명했습니다. 프로세스는 변경 내용을 점진적으로 전달하는 것으로 구성되며, 테스트 중에 누락된 대부분의 회귀에 대해 작은 규모로 검색할 수 있도록 충분한 베이킹 시간을 통합하는 단계가 있습니다.</p>


  <p>상태 메트릭의 지속적인 모니터링은 이 프로세스의 기본적인 부분이며, 여기서 AIOps는 중요한 역할을&mdash; 수행하므로 변칙을 검색하여 경고를 트리거하고 배포 중지 또는 롤백 시작과 같은 작업 수정을 자동화할 수 있습니다.</p>


  <p>다음 게시물에서는 AI 및 기계 학습을 사용하여 DevOps 엔지니어에게 권한을 부여하고, 대규모로 Azure 배포 프로세스를 모니터링하고, 문제를 조기에 감지하고, 영향 범위 및 심각도에 따라 롤아웃 또는 롤백 결정을 내리는 방법을 소개합니다.</p>


  <h2>안전한 배포를 위한 AIOps 이유</h2>


  <p><a href="https://www.gartner.com/en/documents/3892967/market-guide-for-aiops-platforms" target="_blank">Gartner</a>에서 정의한 대로 AIOps는 빅 데이터, 기계 학습 및 시각화를 결합하여 이벤트 상관 관계, 변칙 검색 및 인과 관계 결정을 포함한 IT 작업 프로세스를 자동화하는 인사이트를 통해 IT 작업을 향상시킵니다. AIOps&quot;를 사용하여 <a href="https://azure.microsoft.com/en-us/blog/advancing-azure-service-quality-with-artificial-intelligence-aiops/" target="_blank">Azure 서비스 품질을 향상하는</a> 이전 게시물 &quot; 에서는 안전한 배포를 포함하여 AIOps를 실제로 이미 사용하고 있는 몇 가지 비전과 몇 가지 방법을 공유했습니다. AIOps는 특히 서비스 간 종속성의 복잡성, 하이퍼스케일 클라우드 서비스의 규모 및 지원되는 다양한 고객 시나리오로 인해 배포 롤아웃 중에 오류를 catch하는 데 적합합니다.</p>


  <p>단계적 롤아웃 및 보강된 상태 신호는 배포 프로세스에서 모니터링 및 의사 결정을 용이하게 하는 데 사용되지만, 배포 의사 결정에 관련된 신호의 양과 복잡성 수준은 60개 이상의 지역에서 200개 이상의 데이터 센터에 걸쳐 끊임없이 진화하는 수천 개의 서비스 구성 요소에서 인간이 합리적으로 추론할 수 있는 수준을 초과합니다. 일부 잠재적인 문제는&rsquo; 배포 후 며칠 동안 매니페스트되지 않으며, 여러 클러스터에 걸쳐 있지만 개별 클러스터에서 분 단위로만 매니페스트하는 글로벌 문제는 로컬 Watchdog만으로는 검색하기 어렵습니다. 느슨한 결합을 사용하면 대부분의 서비스 구성 요소를 독립적으로 배포할 수 있지만 배포는 서로 복잡한 영향을 미칠 수 있습니다. 예를 들어 업스트림 서비스의 간단한 변경은 두 서비스 간의 API 호출 계약을 중단하는 경우 다운스트림 서비스에 잠재적으로 영향을 줄 수 있습니다.</p>


  <p>이러한 과제는 자동화된 모니터링, 변칙 검색 및 롤아웃 영향 평가 솔루션을 요구하여 배포 결정을 빠른 속도로 용이하게 합니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/ea272394-b78c-496a-a993-bc1c8733c6d0.png"><img alt="Gandalf safe deployment – including pre-qualification test, safe deployment policy, local watchdog, and “Gandalf” the global and intelligent watchdog." border="0" height="209" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/47cf1def-15ef-41dd-b9bb-69eb6ed10a44.png" style="border: 0px currentcolor; border-image: none; display: inline; background-image: none;" title="gandalf img1" width="240"></a></p>


  <p><em>그림 1: Gandalf 안전 배포</em></p>


  <h2>Gandalf 안전한 배포 서비스: AIOps 솔루션</h2>


  <p>위에서 설명한 과제에 따라 Azure Compute Insights 팀은 안전한 배포를 위해 Gandalf&rdquo; 안전 배포 서비스&mdash; 엔드 투 엔드 연속 모니터링 시스템을 개발&ldquo;했습니다. 몇 가지 다른 지능형 모니터링 서비스를 포함하는 Gandalf AIOps 솔루션 제품군의 이 부분을 고려합니다. Gandalf라는 코드 이름은 그림 1에 표시된 것처럼 반지의 제왕의 주인공에서 영감을 받아 수집된 신호에 따라 지능형 배포 결정을 내리는 글로벌 워치독 역할을 합니다. 로컬 감시, 안전한 배포 정책 및 사전 검증 테스트와 함께 작동하여 배포 안전 및 속도를 보장합니다.</p>


  <p>그림 2에 설명된 것처럼 Gandalf 시스템은 Azure에서 풍부하고 대표적인 신호를 모니터링하고, 변칙 검색 및 상관 관계를 수행한 다음, 배포 의사 결정 및 작업을 지원하는 인사이트를 파생합니다.</p>


  <p><strong><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/6dcc2c12-e23a-44d1-905f-2a4a01da7ff2.png"><img alt="Gandalf system overview – showing data sources, the detection/correlation/decision engine, result orchestration, consumers, and the deployment engine." border="0" height="262" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/7c1aa8d8-2f29-4752-bc86-b2eeecdd0a59.png" style="border: 0px currentcolor; border-image: none; display: inline; background-image: none;" title="그림 2" width="1024"></a></strong></p>


  <p><em>그림 2: Gandalf 시스템 개요</em></p>


  <h3>데이터 원본</h3>


  <p>Gandalf는 아래에 설명된 대로 성능, 오류 및 이벤트에 대한 신호를 모니터링합니다. 데이터를 미리 처리하여 통합 데이터 스키마를 중심으로 구성하여 다운스트림 데이터 분석을 지원합니다. 또한 Virtual Machine 오류 분류 서비스 및 거의 실시간 오류 특성 처리 서비스를 포함하여 상태 신호를 위해 Azure 내에서 몇 가지 다른 분석 서비스를 활용합니다. 모든 새 서비스 구성 요소가 온보딩될 때 Gandalf를 사용한 신호 등록이 필요합니다.</p>


  <ul>
      <li><strong>성능 데이터: </strong> Gandalf는 성능 카운터, CPU 사용량, 메모리 사용량 등을 &ndash; 모니터링하여 호스트된 서비스의 성능 및 리소스 소비 패턴에 대한 개략적인 보기를 제공합니다.</li>
      <li><strong>오류 신호:</strong> Gandalf는 고객&rsquo; 가상 머신(데이터 평면) 및 테넌트 수준 서비스(제어 평면)의 호스팅 환경을 모두 모니터링합니다. 데이터 평면의 경우 OS 크래시, 노드 오류 및 다시 부팅과 같은 실패 신호를 모니터링하여 VM&rsquo; 호스팅 환경의 상태를 평가합니다.&nbsp; 동시에 API 호출 실패와 같은 제어 평면의 오류 신호를 모니터링하여 테넌트 수준 서비스의 상태를 평가합니다.</li>
      <li><strong>이벤트 업데이트:</strong> Gandalf는 수집된 원격 분석 데이터 외에도 배포 진행 상황 및 문제를 보고하는 배포 이벤트의 펄스를 손가락으로 유지합니다.</li>
  </ul>


  <h3>검색, 상관 관계 및 결정</h3>


  <p>Gandalf는 배포&mdash;의 영향 범위(예: 영향을 받은 노드, 클러스터 및 고객&mdash; 수)를 평가하여 동적으로 학습된 의사 결정 조건을 사용하여 이동/이동 없이 의사 결정을 내립니다. 속도와 검사의 균형을 맞추기 위해 Gandalf는 스트리밍 및 일괄 처리 분석 엔진을 모두 사용하는 아키텍처를 활용합니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/040317ab-ee8f-4043-96f4-138476f62040.png"><img alt="Gandalf correlation process (identifying which rollouts are suspicious) and decision process (assessing the customer impacts of the blamed components/failures)." border="0" height="431" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/bac9753f-e782-4ece-987b-214cb2b012c9.png" style="border: 0px currentcolor; border-image: none; display: inline; background-image: none;" title="간달프 img3" width="841"></a></p>


  <p><em>그림 3: Gandalf 변칙 검색 및 상관 관계 모드</em></p>


  <p>그림 3에서는 Gandalf Machine Learning(ML) 모델의 개요를 보여 줍니다. 의심스러운 배포를 식별하기 위한 두 가지 부분&mdash;별 검색 및 상관 관계 프로세스와 의사 결정 프로세스(고객의 영향을 평가)로 구성됩니다.</p>


  <h3>변칙 검색 및 상관 관계 프로세스</h3>


  <p>정확한 감지를 위해 Gandalf는 오류를 고유하게 식별하는 데 사용할 수 있는 입력 신호에서 오류 서명을 파생합니다. 그런 다음 오류 서명의 발생에 따라 검색합니다.</p>


  <p>Azure와 같은 대규모 클라우드 시스템에서는 호스트되는 시스템 및 워크로드의 동적 특성과 엄청난 양의 오류 서명으로 인해 간단한 임계값 기반 검색이 실용적이지 않습니다. Gandalf는 기계 학습 기술을 적용하여 기록 데이터를 기반으로 기준 설정을 자동으로 예측하고 필요에 따라 학습을 통해 설정을 조정할 수 있습니다.</p>


  <p>Gandalf는 변칙을 검색할 때 관찰된 실패와 배포 이벤트의 상관 관계를 지정하고 영향 범위를 평가합니다. 이렇게 하면 임의 펌웨어 문제와 같은 배포가 아닌 이유로 인한 오류를 필터링할 수 있습니다.</p>


  <p>여러 시스템 구성 요소가 동시에 배포되는 경우가 많으므로 투표 거부 메커니즘을 사용하여 오류와 롤아웃 구성 요소 간의 관계를 설정합니다. 또한 임시 및 공간 상관 관계를 사용하여 오류의 구성 요소를 식별합니다. 오류 서명의 롤아웃과 감지 사이의 시간을 측정하는 오류 기간은 새로 관찰된 오류가 이전 롤아웃에 의해 트리거될 가능성이 적기 때문에 이전 롤아웃보다 새 롤아웃에 더 많은 초점을 맞출 수 있는 것으로 간주됩니다.</p>


  <p>이러한 방식으로 Gandalf는 프로세스&mdash; 초기에 고객 환경의 잠재적 회귀로 이어질 수 있는 변칙을 감지하여 광범위한 고객 영향을 생성할 수 있습니다. 자세한 내용은 <a href="https://www.usenix.org/conference/nsdi20/presentation/li" target="_blank">대규모 클라우드 인프라에서 안전한 배포를 위해 게시된 Gandalf: 지능형 엔드 투 엔드 분석 서비스를</a> 참조하세요.&ldquo;&rdquo;</p>


  <h3>의사 결정 프로세스</h3>


  <p>마지막으로 Gandalf는 영향을 받은 클러스터/노드/고객 수와 같은 배포의 영향 범위를 평가하고 궁극적으로 &quot;이동/이동 안&quot; 됨 결정을 내린다. &rsquo;Gandalf는 개발자가 자신의 경험에 따라 신호&rsquo; 가중치 할당을 사용자 지정할 수 있도록 설계되었습니다. 이러한 방식으로 인간 전문가의 도메인 지식을 통합하여 기계 학습 솔루션을 보완할 수 있습니다.</p>


  <h3>결과 오케스트레이션</h3>


  <p>Gandalf는 속도와 검사의 균형을 맞추기 위해 들어오는 신호의 스트리밍 및 일괄 처리를 모두 활용합니다. 스트리밍 처리는 빠른 속도로 분석을 지원하는 클라우드 스토리지 솔루션인 Azure Data Explorer의 데이터를 사용합니다. 스트리밍 처리는 각 노드에서 각 배포 전후 1시간 동안 발생하는 오류 신호를 처리하는 데 사용되며 빠른 응답을 위해 간단한 분석 알고리즘을 실행합니다.</p>


  <p>일괄 처리는 매우 많은 양의 데이터를 지원하는 Hadoop과 유사한 파일 시스템인 Cosmos 데이터를 사용합니다. &rsquo;고급 알고리즘을 사용하여 더 큰 기간(일반적으로 30일 기간)에 걸쳐 오류를 분석하는 데 사용됩니다.</p>


  <p>스트림 및 일괄 처리는 5분 간격으로 증분 방식으로 수행됩니다. 일반적으로 Gandalf의 들어오는 원격 분석 신호는 모두 Kusto로 스트리밍되고 매시간/매일 Cosmos 저장됩니다. 동일한 데이터 원본을 사용하면 처리 파이프라인의 결과가 일치하지 않을 수 있습니다. 일괄 처리는 보다 합리적인 의사 결정을 내리고 빠른/스트리밍 프로세스에서 검색할 수 없는 대기 문제를 처리하기 때문에 의도적으로 수행됩니다.</p>


  <h2>배포 환경 변환</h2>


  <p>Gandalf 시스템은 이제 Azure 내에서 DevOps 워크플로에 잘 통합되었으며 전체 차량에서 배포 상태 모니터링을 위해 널리 채택되었습니다. 나쁜 롤아웃을 최대한 빨리 방지하는 데 도움이 될 뿐만 아니라, 분산된&rsquo; 증거를 찾는 것에서부터 임시 진단부터 대화형 문제 해결&mdash; 사용에 이르기까지, 간달프와 상호 작용하는 많은 엔지니어들이 이에 대한 의견을 가지고 있는, 분산된 증거를 찾는 소프트웨어 변경 사항을&mdash; 배포하는 데 있어 엔지니어 및 릴리스 관리자&rsquo; 환경을 변화시켰습니다.  회의론자에서 옹호자로 진화.</p>


  <p>많은 Azure 서비스에서 Gandalf는 모든 릴리스 유효성 검사의 기본 기준이 되었으며, 온-콜 엔지니어가 Gandalf를 얼마나 신뢰하는지 듣는 것은&rsquo; 매우 흥미롭습니다.</p>


  <h2>요약</h2>


  <p>이 게시물에서는 Azure 서비스의 안전한 배포를 위한 지능형 엔드 투 엔드 분석 서비스인 <a href="https://www.usenix.org/conference/nsdi20/presentation/li" target="_blank">Gandalf</a> 안전 배포 서비스를 도입했습니다. Gandalf 안전 배포 서비스는 최신 변칙 검색, 특수 및 임시 상관 관계 및 결과 오케스트레이션을 통해 DevOps 엔지니어가 Azure와 같은 하이퍼스케일 클라우드 플랫폼에 필요한 속도로 정확한 의사 결정을 내릴 수 있도록 합니다.</p>


  <p>우리는 클라우드 서비스 관리를 개선하기 위해 AI 및 기계 학습 기반 기술을 적용하는 데 계속 투자하여 궁극적으로 고객 환경을 지속적으로 개선할 것입니다. 품질을 왼쪽으로 푸시하는 데 도움이 되는 사전 프로덕션 분석을 포함하여 AIOps 솔루션에 대해 더 많이 공유할 수 있습니다.</p>
