### YamlMime:Yaml
ms.openlocfilehash: 136445667dc10c85b679a1271159b0fda6657f7e
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139912209"
Slug: announcing-application-consistent-backup-for-linux-vms-using-azure-backup
Title: Azure Backup을 사용하여 Linux VM에 대한 애플리케이션 일치 백업 발표
Summary: Azure Backup은 온-프레미스와 클라우드 모두에서 엔터프라이즈 데이터를 보호하기 위한 클라우드 우선 백업 솔루션입니다. Azure에서 실행되는 Linux Virtual Machines의 백업은 다음을 수행할 필요 없이 이미 제공합니다.
Content: >-
  <p>Azure Backup은 <a href="https://docs.microsoft.com/en-us/azure/backup/backup-azure-vms-first-look-arm">Azure에서 실행되는 Linux Virtual Machines의</a> 파일 시스템 일치 백업을 제공합니다. 현재는 인기 있는 Linux 배포판(예: Ubuntu, Red Hat Enterprise Linux 등)에서 실행되는 MySQL, InterSystems Cach&eacute; 및 SAP HANA와 같은 엔터프라이즈 중요 애플리케이션에 대해 <b>애플리케이션 일치 백업</b>을 수행하도록 이 기능을 확장하고 있습니다. 이 프레임워크를 사용하면 VM 백업 프로세스의 일부로 사용자 지정 사전 및 사후 스크립트를 유연하게 실행할 수 있습니다. 이러한 스크립트는 애플리케이션 일관성을 보장하는 백업을 수행하는 동안 애플리케이션 IO를 정지하는 데 사용할 수 있습니다.</p>


  <h2>가치 제안</h2>


  <ul>
   <li><b>백업 워크플로 사용자 지정: </b> 이제 VM 스냅샷을 만드는 동안 사용자 지정 스크립트를 실행하여 백업 중에 애플리케이션 및 프로덕션 환경을 완전히 유연하게 제어할 수 있습니다. 아래에는 프레임워크를 활용하는 방법에 대한 몇 가지 예가 나와 있습니다.

   <ul>
    <li>사전 스크립트를 사용하여 애플리케이션 네이티브 API를 사용하여 일시적으로 애플리케이션 IO를 정지 또는 리디렉션하고 메모리 콘텐츠를 디스크로 플러시한 후 VM 스냅샷을 만들 수 있습니다. 그런 다음 사후 스크립트를 사용하여 스냅샷 완료 후 IO를 해동하고 정상적인 애플리케이션 작업을 다시 시작할 수 있습니다. 이렇게 하면 실행 중인 모든 애플리케이션에 대한 애플리케이션 일치 VM 백업이 보장됩니다. 일부 애플리케이션은 정지 논리를 방해하지 않도록 fsfreeze를 사용하지 않도록 설정해야 하므로 Azure Backup을 사용하여 Linux VM 백업을 수행하는 동안 기본적으로 실행되는 Linux <em>fsfreeze</em> 를 사용하지 않도록 설정하는 기능도 제공합니다.</li>
    <li>네이티브 애플리케이션 API를 호출하여 애플리케이션 백업 및 데이터베이스 로그 백업을 수행할 수도 있으며, VM 백업의 일부로 데이터가 Recovery Services 자격 증명 모음으로 이동되어 VM 손상 시나리오(예: VM 삭제 또는 손상)로부터 데이터를 보호합니다.</li>
   </ul>
   </li>
  </ul>


  <blockquote>

  <ul>

  </ul>

  </blockquote>


  <ul>
   <li><b>애플리케이션 및 배포판에 구애받지 않습니다. </b> 프레임워크는 Linux 배포판 및 버전에 구애받지 않으며 게스트 애플리케이션에 애플리케이션 IO를 일시 중지하고 다시 시작할 수 있는 API가 있는 한 <a href="https://docs.microsoft.com/en-us/azure/backup/backup-azure-backup-faq#what-can-i-back-up">지원되는 모든 Linux 배포판</a> 에서 원활하게 작동합니다.</li>
   <li><b>Github의 샘플 스크립트: </b> Microsoft는 인기 있는 Linux 애플리케이션용 <a href="https://github.com/MicrosoftAzureBackup">github</a> 에 오픈 소스 스크립트를 제공하기 위해 파트너 및 ISV와 협력하고 있습니다. 이 릴리스를 기준으로 MySQL, Cach&eacute;에 대한 이러한 항목이 준비되었으며 SAP HANA와 긴밀히 협력하고 있습니다.<strong>&nbsp;</strong></li>
  </ul>


  <h2>기본적인 이해</h2>


  <p>Azure Backup은 아래 이미지에 설명된 대로 빠르고 효율적인 Azure Linux VM 백업을 수행하는 일련의 단계를 완료합니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/f2dca00d-728c-4ce9-ad56-e6fd06bf993a.png"><img alt="workflow" border="0" height="595" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/b64fe2c1-6168-4ea8-b54a-9dd15748affe.png" style="border-left-width: 0px; border-right-width: 0px; border-bottom-width: 0px; float: none; margin-left: auto; display: block; border-top-width: 0px; margin-right: auto" title="워크플로" width="418"></a></p>


  <h2>시작</h2>


  <p>아래 비디오에서는 사전 스크립트 및 사후 스크립트를 실행하기 위해 프레임워크를 구성하는 방법에 대한 다양한 단계를 안내합니다. 자세한 내용은 <a href="https://docs.microsoft.com/azure/backup/backup-azure-linux-app-consistent#steps-to-configure-pre-script-and-post-script">애플리케이션 일치 Linux VM 백업을 구성하는 단계를</a> 참조하세요.</p>


  <p><iframe allowfullscreen="" frameborder="0" height="540" src="https://channel9.msdn.com/Series/Azure-Backup/Application-consistent-backup-for-Linux-VMs-using-Azure-Backup/player" width="960"></iframe></p>


  <h2>MySQL &amp; 캐싱에 대한 샘플 스크립트&eacute;</h2>


  <p>프레임워크를 부트스트랩하기 위해 클러스터형 배포를 비롯한 데모 스크립트를 사용하여 <a href="https://www.intersystems.com/our-products/cache/cache-overview/">InterSystems Cach&eacute;</a> DB 및 <a href="https://www.mysql.com/">MySQL</a> DB 예제를 사용했습니다. 이를 참조로 사용하여 고유한 스크립트를 만들고 이 프레임워크의 기능을 활용할 수 있습니다.</p>


  <p>Capside에서 Azure Backup을 사용하여 MySQL 애플리케이션 일치 백업</p>


  <p><a href="https://community.intersystems.com/post/caché-application-consistent-backups-azure-backup">Intersystems에서 Azure Backup을 사용하여 애플리케이션 일치 백업 캐시&eacute;</a></p>


  <h2>오픈 소스 커뮤니티 기여 찾기</h2>


  <p>개발자, ISV, 기술 애호가 및 파트너가 오픈 소스 <a href="https://github.com/MicrosoftAzureBackup">github</a> 리포지토리에 스크립트를 기여할 것을 요구합니다. 스크립트는 모든 사용자가 직접 사용하거나 요구 사항에 따라 사용자 지정할 수 있습니다. 기여에 관심이 있는 경우 메일을 <a href="https://azure.microsoft.com/en-us/blog/key-updates-to-azure-backup-for-azure-linux-vms/preview/linuxazurebackupteam@service.microsoft.com">linuxazurebackupteam@service.microsoft.com</a> 보내주시면 Github에 게시하고, 사용 지침을 설명하고, 기여에 대한 승인을 받을 수 있도록 하겠습니다.</p>


  <h2>관련 링크 및 추가 콘텐츠</h2>


  <ul>
   <li>이 기능에 대한 자세한 내용을 원하십니까? <a href="https://docs.microsoft.com/azure/backup/backup-azure-linux-app-consistent">Azure 애플리케이션 일치 Linux VM 백업 설명서</a> 확인</li>
   <li>도움이 필요하신가요? <a href="https://social.msdn.microsoft.com/forums/azure/en-US/home?forum=windowsazureonlinebackup">지원을 위해 Azure Backup 포럼</a>에 문의</li>
   <li>새 아이디어를 기여하고 기존 아이디어를 투표하여 <a href="https://feedback.azure.com/forums/258995-azure-backup">Azure Backup을 개선할</a> 수 있는 방법을 알려주세요.</li>
   <li>최신 뉴스 및 업데이트에 대한 트위터에 <a href="https://twitter.com/azurebackup">@AzureBackup</a> 우리를 따르라</li>
   <li><a href="https://azure.microsoft.com/en-us/services/backup/">Azure Backup</a>을 새로 사용, <a href="https://azure.microsoft.com/en-us/pricing/free-trial/">무료 Azure 평가판 구독</a> 등록</li>
  </ul>
