### YamlMime:Yaml
ms.openlocfilehash: ba6bf2e01308b5b37304fd4e86363ddb540df5b3
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139906297"
Slug: annotations-detail-blade-now-available-in-application-insights
Title: 이제 애플리케이션 Insights 주석 세부 정보 블레이드를 사용할 수 있습니다.
Summary: 이제 애플리케이션 Insights 주석 기능에 대한 세부 정보 블레이드를 사용할 수 있습니다.
Content: >-
  <p><a href="https://azure.microsoft.com/en-us/blog/application-insights-announces-availability-of-release-annotations/" target="_blank" title="릴리스 주석 블로그 사후"> 블로그 게시물</a>에서 주석이라는 애플리케이션 Insights 새로운 기능의 가용성을 발표<em>했습니다.</em> 나는 또한이 기능에 대한 세부 블레이드가 스프린트의 다음 몇 가지를 통해 사용할 수 있게 될 것이라고 언급했다. 글쎄, 좋은 소식, 모두 : 그것은&rsquo; <em>지금</em> 사용할 수 있습니다.</p>


  <p>기능은 가능한 한 간단합니다. 사용자가 세부 정보를 보려는 주석&rsquo;을 클릭하면 새 블레이드가 오른쪽으로 열립니다. 이 블레이드는 릴리스 ID, 요청자, 소스 제어 분기, 릴리스 정의 및 환경을 포함하여 릴리스에 대한 다양한 정보를 제공합니다. 다음은&rsquo; 작동 중인 빠른 샷입니다.</p>


  <p><img alt="image" border="0" height="368" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/fc9e824e-85eb-4fe9-a920-4ab56d4fd8c0.png" style="background-image: none; padding-top: 0px; padding-left: 0px; display: inline; padding-right: 0px; border-image: none" title="이미지" width="610"></p>


  <p>이 기능이 추가되면서 릴리스 주석에 훨씬 더 많은 가치가 있다고 생각합니다. &rsquo;이제 애플리케이션 Insights 원격 분석과 릴리스의 상관 관계를 지정할 때 더 많은 식별 정보를 얻을 수 있습니다.</p>


  <p>앱 Insights ALM 팀은 이 추가가 주석을 웹앱 및 서비스의 일상적인 모니터링 및 분석에 더 유용하게 만들기를 희망합니다. 보고 싶은 세부 정보 블레이드에 없는 추가 관련 릴리스 데이터가&rsquo; 있는 경우 알려주세요.&rsquo; 데이터의 가용성을 조사해 주세요.</p>


  <p>우리는 곧 당신을 위해 더 오고있다, 그래서 새로운 발표에 대한 Azure 블로그에 여기에 내 게시물에 눈을 유지하시기 바랍니다!</p>


  <p>언제나처럼 애플리케이션 Insights 사용자 의견 페이지에서 새로운 기능 또는 향상된 기능에 대한 아이디어를 공유하세요. 질문이 있으면 <a href="https://social.msdn.microsoft.com/Forums/vstudio/en-US/home?forum=ApplicationInsights"><u>애플리케이션 Insights 포럼</u></a>을 방문하세요.</p>

  <script>
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

    ga('create', 'UA-68318793-1', 'auto'); ga('send', 'pageview');

  </script>
