### YamlMime:Yaml
ms.openlocfilehash: 3e04dbe549191e344efe761d4ddbf3bce976eb5d
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139903389"
Slug: announcing-the-general-availability-of-azure-application-insights-sdk-for-node-js-1-0
Title: Node.js 1.0용 Azure Application Insights SDK의 일반 공급 발표
Summary: Microsoft는 개발자가 Azure에서 Node.js 앱을 빌드하고 실행하는 데 유용한 환경을 제공하기 위해 최선을 다하고 있습니다. 오늘 Azure 애플리케이션의 일반 공급은 다음과 같습니다.
Content: >-
  <p>Microsoft는 개발자가 Azure에서 Node.js 앱을 빌드하고 실행하는 데 유용한 환경을 제공하기 위해 최선을 다하고 있습니다. 오늘, Node.js <a href="https://docs.microsoft.com/en-us/azure/application-insights/" target="_blank">1.0용 Azure Application Insights SDK</a>의 일반 공급은 많은 성공적인 반복의 절정이며 고객 피드백 수신을 기반으로 합니다.</p>


  <p>애플리케이션 Insights 배포 후 <strong>프로덕션의 앱, 서비스 및 구성 요소를 모니터링</strong>하여 <strong>성능 병목 상태 및 기타 문제를 검색하고 신속하게 진단</strong>하는 데 도움이 되는 애플리케이션 성능 관리 도구입니다. <a href="https://github.com/Microsoft/ApplicationInsights-node.js/releases" target="_blank">1.0 릴리스</a>는 주로 Node.js 애플리케이션 Insights SDK에 성능, 안정성 및 안정성 향상을 제공합니다.</p>


  <p>Node.js 애플리케이션 Insights SDK는 <a href="https://github.com/Microsoft/ApplicationInsights-node.js/" target="_blank">GitHub 호스트되는</a> 오픈 소스 프로젝트입니다.</p>


  <h2>시작</h2>


  <p>Azure 애플리케이션 Insights 새로운 경우 Node.js 애플리케이션 또는 서비스에 대한 모니터링을 설정하는 단계별 프로세스를 안내하는 자세한 <a href="https://docs.microsoft.com/en-us/azure/application-insights/app-insights-nodejs" target="_blank">시작 가이드</a>를 확인하세요. Node.js 앱이 실행되는 위치에 관계없이 애플리케이션 Insights 사용할 수 있습니다. Azure 또는 온-프레미스의 Virtual Machines, 컨테이너, <a href="https://docs.microsoft.com/en-us/azure/app-service-web/app-service-web-get-started-nodejs" target="_blank">Linux의 Web Apps</a>, 심지어 <a href="https://azure.github.io/azure-iot-sdk-node/" target="_blank">사물 인터넷</a> 디바이스 및 전자 데스크톱 앱에서도 사용할 수 있습니다. 애플리케이션에 몇 줄의 코드를 삽입하여 프로덕션의 문제를 진단하는 데 도움이 되는 사용량 원격 분석 및 데이터를 가져오기만 하면 됩니다.</p>


  <h2>애플리케이션 맵</h2>


  <p><a href="https://docs.microsoft.com/en-us/azure/application-insights/app-insights-app-map" target="_blank">애플리케이션 맵은 애플리케이션</a> 구성 요소의 종속성 관계의 시각적 레이아웃입니다. 각 구성 요소는 부하, 성능, 오류 및 경고와 같은 KPI를 보여 주어 성능 문제 또는 실패를 유발하는 모든 구성 요소를 발견할 수 있도록 합니다. 모든 구성 요소에서 애플리케이션 Insights 이벤트와 같은 보다 자세한 진단으로 이동할 수 있습니다. 앱에서 Azure 서비스를 사용하는 경우 SQL Database Advisor에서 제공하는 것과 같은 Azure 진단 및 권장 사항을 클릭할 수도 있습니다. Node.js 애플리케이션 Insights SDK의 1.0 릴리스는 이 공간에서 몇 가지 향상된 기능을 제공하므로 Redis, MongoDB, PostgreSQL 등을 비롯한 타사 제품 및 서비스에 대한 아이콘을 표시하여 종속성을 쉽게 식별할 수 있습니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/e90f4bd4-906f-4103-9685-5c5be7a358e7.png"><img alt="1101" border="0" height="484" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/487d816c-3b79-41ec-a7ba-412348e0200f.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="1101" width="1024"></a> 이 기능을 시도해 보고 애플리케이션 맵에서 요구 사항을 더 잘 충족할 수 있는 다른 기능을 <a href="https://github.com/Microsoft/ApplicationInsights-node.js/issues" target="_blank">알려주세요</a> .</p>


  <h2>향상된 NPM 모듈 지원</h2>


  <p>Node.js 인기는 NPM에 수십만 개의 패키지가 있는 타사 모듈 에코시스템에서 비롯됩니다. 현재 Node.js 애플리케이션은 NPM 패키지를 그 어느 때보다 많이 사용하고 있으며 복잡한 문제를 진정으로 진단하기 위해 이러한 모듈에서 인사이트를 얻어야 하는 경우가 많습니다. 애플리케이션 Insights 종속성을 포함하여 전체 애플리케이션에서 심층적이고 실행 가능한 진단 정보를 제공하는 훌륭한 진단 환경을 제공하는 것을 목표로 합니다. Node.js 애플리케이션 Insights SDK의 1.0 릴리스에서는 두 개의 추가 모듈에 자동 계측을 추가했습니다. <a href="https://www.npmjs.com/package/pg" target="_blank">PostgreSQL</a> 및 <a href="https://www.npmjs.com/package/winston" target="_blank">윈스턴</a> 로깅 프레임워크는 <em>bunyan</em>, <em>콘솔, mongodb, mongodb-core, mysql, redis</em> 및 <em>pg-pool</em>과 함께 기본 제공 패키지를 지원하는 NPM 패키지의 증가하는 목록에 합류했습니다.</p>


  <h2>이 릴리스의 주요 변경 내용</h2>


  <p>변화를 깨는 것은 항상 어려운 결정이며, 우리는 그것을 가볍게 여기지 않습니다&rsquo;. 그러나 다른 애플리케이션 Insights SDK와의 일관성을 제공하고 향후 확장성을 허용하기 위해 이 릴리스에는 API 전반의 몇 가지 주요 변경 내용도 포함되어 있습니다. GitHub 프로젝트 페이지에서 새 메서드 및 속성 이름 및 마이그레이션 지침에 대한 <a href="https://github.com/Microsoft/ApplicationInsights-node.js/blob/develop/README.md" target="_blank">추가 정보(README</a>)를 검토하세요. 또한 이 SDK의 기본 구성은 앱이 오프라인일 때 기본적으로 디스크에 원격 분석 스토리지를 설정하여 변경되었습니다.</p>


  <h2>사용해 보기</h2>


  <p>Node.js<a href="https://docs.microsoft.com/en-us/azure/application-insights/app-insights-nodejs" target="_blank">애플리케이션 Insights </a> 사용해 보시고 오늘 Node.js 앱 및 서비스 모니터링을 시작해 보시기 위해 여러분 모두를 초대합니다.</p>


  <p>더 많은 타사 모듈을 자동으로 계측하고 고객&rsquo; 피드백에 따라 애플리케이션 맵 통합 및 컨텍스트 추적을 개선하여 고객 환경을 지속적으로 개선할 것입니다.</p>


  <p>궁금한 사항이 있거나 Node.js 애플리케이션 Insights SDK에 문제가 있는 경우 GitHub <a href="https://github.com/Microsoft/ApplicationInsights-node.js/issues/" target="_blank">프로젝트 페이지에서</a> 문제를 여세요.</p>
