### YamlMime:Yaml
ms.openlocfilehash: b759e771a49d1105d6e698b37deb5b03db3872a4
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139906655"
Slug: announcing-full-powershell-cmdlet-support-for-azure-automation
Title: Azure Automation에 대한 전체 PowerShell Cmdlet 지원 발표
Summary: 당신은 물었고, 우리는 대답했다! 이번 주에는 최신 버전의 Azure PowerShell 모듈이 릴리스되었습니다. 이 업데이트에는 계정, 자산 및 예약된 Runbook에 대한 새 cmdlet이 포함됩니다.
Content: >-
  당신은 물었고, 우리는 대답했다! 이번 주에는 최신 버전의 Azure PowerShell 모듈이 릴리스되었으며, PowerShell ISE/콘솔 또는 Azure Automation Runbook 내에서 로컬로 <a href="https://azure.microsoft.com/blog/2014/08/20/azure-automation-capabilities-in-depth-the-azure-automation-powershell-cmdlets/">Azure Automation을 관리하기</a> 위한 <strong>23개의 새로운</strong> <strong>PowerShell</strong> <strong>cmdlet</strong>이 함께 출시되었습니다. 이 업데이트에는 계정, 자산 및 예약된 Runbook에 대한 새 cmdlet이 포함됩니다.


  &nbsp;

  <h2>새 cmdlet:</h2>

  <ul>
      <li>New-AzureAutomationAccount</li>
      <li>Remove-AzureAutomationAccount</li>
      <li>Get-AzureAutomationScheduledRunbook</li>
      <li>New-AzureAutomationVariable</li>
      <li>Set-AzureAutomationVariable</li>
      <li>Remove-AzureAutomationVariable</li>
      <li>Get-AzureAutomationVariable</li>
      <li>Get-AzureAutomationCredential</li>
      <li>New-AzureAutomationCredential</li>
      <li>Remove-AzureAutomationCredential</li>
      <li>Set-AzureAutomationCredential</li>
      <li>Get-AzureAutomationCertificate</li>
      <li>New-AzureAutomationCertificate</li>
      <li>Set-AzureAutomationCertificate</li>
      <li>Remove-AzureAutomationCertificate</li>
      <li>Get-AzureAutomationConnection</li>
      <li>New-AzureAutomationConnection</li>
      <li>Remove-AzureAutomationConnection</li>
      <li>Set-AzureAutomationConnectionFieldValue</li>
      <li>Get-AzureAutomationModule</li>
      <li>New-AzureAutomationModule</li>
      <li>Set-AzureAutomationModule</li>
      <li>Remove-AzureAutomationModule</li>
  </ul>

  &nbsp;

  <h2>주목할 만한 업데이트:</h2>

  <ul>
      <li>Get-AzureAutomationJob 이제 작업 상태에 대한 서버 쪽 필터링을 지원합니다.</li>
  </ul>

  &nbsp;


  <a href="https://msdn.microsoft.com/en-us/library/dn690262.aspx">MSDN</a>의 Azure Automation cmdlet에 대해 자세히 알아보거나 여기에서 최신 Azure PowerShell 모듈을 설치할 수 <a href="https://azure.microsoft.com/en-us/documentation/articles/install-configure-powershell/">있습니다</a>.


  &nbsp;


  Azure Automation을 시작하기만 하면 되었나요?<a href="https://aka.ms/Q2p1ap" target="_blank">여기서</a> 서비스에 대해 알아보고 <a href="https://twitter.com/AzureAutomation" target="_blank">Twitter</a>에서 Azure Automation을 따르세요.


  개인적으로 저와 연락하고 싶으신가요? <a href="https://jodoglevy.com" target="_blank">내 블로그</a>를 통해 연락하거나 <a href="https://twitter.com/jodoglevy" target="_blank">트위터에서</a> 나를 따르세요.


  예정된 기능에 대해 Azure Automation 엔지니어링 팀과 소통하고 싶나요? <a href="https://microsoft.qualtrics.com/SE/?SID=SV_0VAgcjc4xF2CDvn">짧은 설문 조사를</a> 작성하면 연락을 드리겠습니다.
