### YamlMime:Yaml
ms.openlocfilehash: 3a499ecaee97f0901037c3353562a189393956d5
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139912208"
Slug: announcing-application-insights-public-preview-2
Title: 애플리케이션 Insights 공개 미리 보기 발표
Summary: 여기서는 애플리케이션 성능 관리 및 사용 현황 분석을 통합하는 모든 앱에 대한 분석 솔루션인 Visual Studio Application Insights 공개 미리 보기를 발표합니다.
Content: >-
  오늘 <a href="https://www.buildwindows.com/">Microsoft BUILD</a> 컨퍼런스에서 발표되는 모든 발표를 매우 기쁘게 생각합니다! <a href="https://aka.ms/soma-build-2015">Soma의 blogandBrian</a>   <a href="https://blogs.msdn.com/b/bharry/archive/2015/04/29/visual-studio-and-team-foundation-server-at-build-2015.aspx">Harry 블로그</a>에서 읽은 것처럼 애플리케이션 <a href="https://azure.microsoft.com/en-us/documentation/articles/app-insights-detect-triage-diagnose">성능 관리</a> 및 <a href="https://azure.microsoft.com/en-us/documentation/articles/app-insights-overview-usage">사용 현황 분석을</a> 통합하는 모든 앱에 대한 분석 솔루션인 <a href="https://azure.microsoft.com/en-us/services/application-insights/">Visual Studio Application Insights</a> <em>공개 미리 보기를</em> 발표합니다.


  애플리케이션 Insights 개발 팀은 라이브 애플리케이션의 성능, 가용성 및 사용량에 대해 포괄적인 360° 보기를 제공합니다. 빠른 문제 해결 및 진단을 위한 직관적인 보기와 강력한 도구를 사용하면 사용자 활동 및 채택을 분석하여 향후 작업에 따라 우선 순위를 지정할 수 있습니다.


  Application Insights 공개 미리 보기의 일환으로 앱당 원격 분석 볼륨을 기반으로 하며 모든 개발 팀에게 무료로 훌륭한 가치를 제공하도록 설계된 새로운 <a href="https://azure.microsoft.com/pricing/details/application-insights/">클라우드 친화적인 가격 책정 모델을</a> 시작합니다. 가격은 2015년 6월부터 적용되며 공개 미리 보기에서 50% 할인됩니다.


  <img class="alignnone wp-image-288621 size-large" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/360-Overview-636x329.png" alt="360 Overview" width="636" height="329" />

  <h2>실제로 모든 앱에 사용할 수 있나요?</h2>

  예. 우리가 지원하는 플랫폼의 범위가 넓고 증가하고 있습니다.


  <a href="https://azure.microsoft.com/documentation/articles/app-insights-ios/">iOS</a> 및 <a href="https://azure.microsoft.com/documentation/articles/app-insights-android/">Android</a> SDK는 <a href="https://blogs.msdn.com/b/somasegar/archive/2014/12/11/microsoft-acquires-hockeyapp-leading-mobile-crash-analytics-and-beta-distribution-service-for-ios-android-and-windows-phone.aspx">HockeyApp</a>에서 통합하는 강력한 기능 덕분에 사용 인사이트 및 크래시 진단을 지원합니다. 물론 <a href="https://azure.microsoft.com/documentation/articles/app-insights-windows-get-started">Windows 전화</a>, 스토어 및 UAP 앱을 지원합니다.


  <a href="https://azure.microsoft.com/documentation/articles/app-insights-java-get-started">J2EE</a> 앱은 모든 개발 플랫폼의 기본 원격 분석과 Eclipse를 사용하는 경우 통합된 도구로 지원됩니다.


  <a href="https://azure.microsoft.com/documentation/articles/app-insights-start-monitoring-app-health-usage/">ASP.NET</a> 개발자는 Visual Studio 한 번의 클릭으로 애플리케이션 Insights 옵트인할 수 있습니다. <a href="https://azure.microsoft.com/documentation/articles/insights-perf-analytics">Azure 웹앱이거나 Azure VM에서 실행되는</a> 경우 애플리케이션 Insights 긴밀하게 결합되어 있습니다.


  <a href="https://azure.microsoft.com/documentation/articles/app-insights-javascript/">JavaScript SDK</a>를 사용하여 모든 웹 페이지에서 원격 분석을 보낼 수 있습니다.


  또한 PHP, Python, Ruby, Node.js, WordPress 및 SharePoint 같은 다양한 <a href="https://azure.microsoft.com/documentation/articles/app-insights-platforms">언어 및 플랫폼</a>에 대한 애플리케이션 Insights SDK가 있습니다.


  원하는 경우 직접 작성할 수 있습니다. 각 앱 유형에 대해 애플리케이션 Insights SDK는 분석하고 포털에서 사용자에게 표시할 원격 분석을 서비스에 보냅니다. 따라서 플랫폼에 대한 SDK가 있는 경우 모든 앱을 모니터링할 수 있습니다. 애플리케이션 Insights Azure에서 호스트되는 서비스이지만 플랫폼 또는 호스팅 위치에 관계없이 모든 앱에서 실제로 사용할 수 있습니다.

  <h2>Who 사용 중입니까?</h2>

  애플리케이션 Insights 사용하는 애플리케이션은 이미 450,000개에 가깝습니다. 점점 더 많은 개발자가 앱에 애플리케이션 Insights 추가하고 있습니다.


  몇 명의 고객이 다음과 같이 말하고 있습니다.

  <blockquote>"나는 완전한 DevOps 이야기에 대한 비전을 가지고 있으며, AI는 우리가 거기에 도착하는 데 도움이 될 수 있습니다. AI는 이미 우리가 식별하지 못한 문제를 해결하는 데 도움을 주었습니다."

  - 주나 코콜라, 마에스트로 기술 감독(핀란드)


  "애플리케이션 Insights 성능 또는 사용자 동작을 결정하는 작업 도구가 아닙니다. 그것은 개발 프로세스의 진정한 부분입니다!"

  - Ray Escamilla, QA 및 Release Manager, Dominion Enterprises(미국)


  "애플리케이션 Insights 조직에서 500억 달러 이상의 Microsoft 수익을 모니터링하기 위한 초석이 되었으며 앞으로도 기대됩니다."

  - Eric Mattingly, 서비스 엔지니어, Microsoft Enterprise Commerce</blockquote>

  애플리케이션 Insights 다음을 제공하므로 만족합니다.

  <ul>
   <li>가용성, 성능 및 사용량에 대한 360° 뷰</li>
   <li>빠르고 강력한 문제 해결, 진단 및 사용 현황 인사이트</li>
   <li>모든 앱에 대한 기본 제공 분석</li>
   <li>클라우드 친화적인 가격 책정 모델을 사용하여 무료로 유용한 가치</li>
  </ul>

  이러한 각 사항을 차례로 살펴보겠습니다.

  <h2>가용성, 성능 및 사용량에 대한 360° 뷰</h2>

  <a href="https://www.gartner.com/newsroom/id/2669915">Gartner에 따르면</a> 가용성, 성능 및 사용량에 대한 전체 보기의 필요성은 조직이 2015-2016년에 마스터해야 하는 상위 10개 모바일 기술 및 기능 중 하나로 평가됩니다. 애플리케이션 Insights 사용하면 전체 애플리케이션 스택의 모든 각도에서 한 곳에서 여러 플랫폼에서 통합 보기를 얻을 수 있습니다.


  <a href="https://azure.microsoft.com/documentation/articles/app-insights-custom-events-metrics-api/">사용자 지정 계측</a>을 사용하여 시나리오를 통해 사용자 경로를 추적할 수 있으며 강력한 드릴다운 기능, 데이터 조각화 및 받아쓰기, <a href="https://azure.microsoft.com/documentation/articles/app-insights-metrics-explorer/">필터링 및 분할</a> 및 <a href="https://azure.microsoft.com/documentation/articles/app-insights-diagnostic-search/">특정 인스턴스 검색</a>을 활용하여 다음과 같은 질문에 대답할 수 있습니다.

  <ul>
   <li>성능 병목 현상이 있나요?</li>
   <li>지난 달보다 더 빠르거나 느리게 신규 사용자를 유치하고 있나요?</li>
   <li>서비스 성능 문제의 영향을 받은 사용자는 어떻게 되었나요?</li>
   <li>가장 큰 영향을 받은 사용자 세그먼트는 무엇인가요?</li>
  </ul>

  <h2>빠르고 강력한 문제 해결 및 진단</h2>

  애플리케이션 또는 서비스에서 가동 중지 시간을 감당할 수 없습니다. 개발자 또는 서비스 엔지니어는 비즈니스에 영향을 주기 전에 문제를 식별해야 합니다. Application Insights 도구를 사용하면 문제가 발생하는 즉시 문제를 식별하고 진단할 수 있습니다.


  실시간 모바일 크래시 분석을 사용하면 디바이스에서 크래시 세부 정보를 얻고, 크래시로 이어지는 원인을 파악하고, 고객 영향에 따라 수정 사항의 우선 순위를 지정할 수 있습니다. 웹 애플리케이션의 경우 실패한 요청, 예외 &amp; 종속성 오류를 진단하고 더 깊은 컨텍스트를 위해 <a href="https://azure.microsoft.com/documentation/articles/app-insights-search-diagnostic-logs/">추적 로그</a> &amp; <a href="https://azure.microsoft.com/documentation/articles/app-insights-custom-events-metrics-api/">사용자 지정 이벤트</a> 와 상관 관계를 지정할 수 있습니다.


  <a href="https://acom.azurecomcdn.net/80C57D/blogmedia/blogmedia/2015/04/29/AI-Mobile-Crash-Diagnostics1.png"><img class="alignnone wp-image-288791 size-large" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/AI-Mobile-Crash-Diagnostics1-636x307.png" alt="AI Mobile Crash Diagnostics" width="636" height="307" /></a>


  웹앱의 경우 <a href="https://azure.microsoft.com/documentation/articles/app-insights-monitor-web-app-availability/">웹 테스트 또는 URL ping</a>을 기반으로 <a href="https://azure.microsoft.com/documentation/articles/app-insights-set-alerts/">경고를 설정하고</a> 고객에게 영향을 주기 전에 비정상적인 서비스 동작에 대해 알 수 있도록 고유한 메트릭 기반 임계값을 정의할 수 있습니다.


  <a href="https://acom.azurecomcdn.net/80C57D/blogmedia/blogmedia/2015/04/29/Alerts1.png"><img class="alignnone wp-image-289251 size-large" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/Alerts1-636x296.png" alt="Alerts" width="636" height="296" /></a>

  <h2>모든 앱에 대한 기본 제공 분석</h2>

  개발 프로세스의 필수적인 부분으로 애플리케이션 Insights 설계했으며, <a href="https://azure.microsoft.com/documentation/articles/app-insights-monitor-performance-live-website-now/">이미 프로덕션 환경에 있는</a> 경우에도 새 애플리케이션과 기존 애플리케이션 모두에 <a href="https://azure.microsoft.com/documentation/services/application-insights/">쉽게</a>  추가할 수 있도록 했습니다. 실제로 아무런 노력도 없이 중요한 애플리케이션 데이터를 자동으로 수집하며, Visual Studio 사용하는 경우 이미 개발 워크플로의 일부입니다.


  <a href="https://acom.azurecomcdn.net/80C57D/blogmedia/blogmedia/2015/04/29/AI-NewProject2.png"><img class="alignnone wp-image-288821 size-large" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/AI-NewProject2-636x282.png" alt="AI-NewProject" width="636" height="282" /></a>


  우리는 많은 IDE에서 동일한 접근 방식을 취합니다. Xcode에 해당하는 도구는 다음과 같습니다.


  <a href="https://acom.azurecomcdn.net/80C57D/blogmedia/blogmedia/2015/04/29/Xcode-Integration.png"><img class="alignnone wp-image-289281 size-large" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/Xcode-Integration-636x345.png" alt="Xcode Integration" width="636" height="345" /></a>


  앞에서 본 것처럼 애플리케이션 Insights 포털은 앱의 원격 분석 데이터 스트림에 적용할 수 있는 다양한 강력한 분석 및 검색 도구를 제공합니다. 또한 <a href="https://azure.microsoft.com/documentation/articles/app-insights-export-telemetry/">외부 시스템으로 데이터를 내보내</a> 서 다른 데이터 원본으로 원격 분석을 매시업하고 추가 분석을 수행할 수 있습니다.

  <h2>클라우드 친화적인 가격 책정 모델을 사용하여 무료로 유용한 가치</h2>

  새로운 클라우드 친화적 <a href="https://azure.microsoft.com/pricing/details/application-insights/">인 가격 책정 모델</a> (2015년 6월부터)은 애플리케이션당 데이터 볼륨을 기반으로 합니다. 무료 계층에서는 데이터 볼륨 및 보존 기간에 대한 몇 가지 제한 사항이 있는 대부분의 기능을 얻을 수 있습니다. 애플리케이션이 증가하고 더 많은 기록이 필요하면 표준 및 Premium 계층을 활용할 수 있습니다. 데이터 볼륨에 대한 요금을 지불합니다. 배포되는 서버 수는 중요하지 않습니다. 사용하지 않은 리소스에 대한 페널티 없이 동적으로 크기를 조정할 수 있습니다. 공개 미리 보기에 있는 동안에는 50% 할인이 있습니다.


  <a href="https://acom.azurecomcdn.net/80C57D/blogmedia/blogmedia/2015/04/29/Pricing1.png"><img class="alignnone wp-image-289361 size-large" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/Pricing1-596x369.png" alt="Pricing" width="596" height="369" /></a>

  <h2>요약</h2>

  아직 수행하지 않은 경우 지금 <a href="https://azure.microsoft.com/services/application-insights/">애플리케이션 Insights</a> 사용해 보세요! 기본 제공 분석, 빠른 &amp; 강력한 진단 및 360° 보기를 사용하면 맹인 비행을 중지하고, 조명을 켜고, 앱에 대해 더 똑똑해질 수 있습니다.


  <iframe style="line-height: 1.5;" src="//channel9.msdn.com/Series/ConnectOn-Demand/218/player" width="587" height="330" frameborder="0" allowfullscreen="allowfullscreen"></iframe>


  마지막 한 가지. 애플리케이션 Insights 사용 중이며 서비스에 대한 의견을 알려 주시려면 이 설문 조사를 통해 피드백을 공유하세요. 질문 및/또는 피드백은 <a href="https://social.msdn.microsoft.com/Forums/en-US/ApplicationInsights/">Application Insights 포럼</a>을 방문하세요.
