### YamlMime:Yaml
ms.openlocfilehash: ae318de27788681eb52c4f7b8465bb64091d724f
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139899081"
Slug: announcing-the-1-0-0-release-of-application-insights-windows-sdks
Title: 애플리케이션 Insights Windows SDK의 1.0.0 릴리스 발표
Summary: 애플리케이션 Insights Windows SDK가 1.0.0 마일스톤에 도달했다고 발표하게 되어 기쁩니다. 1.0.0 마일스톤에 도달하면 SDK 변경과 더 긴 지원 수명에 대한 안정성을 강화할 것입니다.
Content: >-
  애플리케이션 Insights Windows SDK가 1.0.0 마일스톤에 도달했다고 발표하게 되어 기쁩니다. 1.0.0 마일스톤에 도달하면 SDK 변경과 더 긴 지원 수명에 대한 안정성을 강화할 것입니다. SDK에 개선 사항과 새로운 기능을 계속 도입할 예정이지만, 이 SDK 버전이 향후 호환성이 손상되는 변경을 피할 수 있다는 점을 편안하게 느낄 수 있습니다. 1.0.0 SDK에는 환경을 개선하기 위한 몇 가지 API 변경 내용과 다양한 안정성 및 성능 향상 픽스가 포함되어 있습니다. <a href="https://go.microsoft.com/fwlink/?LinkID=616551">릴리스 정보를</a> 보면 변경 내용의 전체 목록을 볼 수 있습니다.

  <h2>지원되는 플랫폼은 무엇인가요?</h2>

  애플리케이션 Insights 현재 사용 중인 많은 애플리케이션 유형을 지원하며 추가 플랫폼에 대한 지원을 빠르게 추가하고 있습니다. 애플리케이션 Insights 모든 환경에서 애플리케이션을 지원하기 위해 노력합니다.

  <ul>
      <li>ASP.Net 웹 애플리케이션</li>
      <li>Windows 애플리케이션</li>
      <li>Java 웹 애플리케이션</li>
  </ul>

  기타 지원되는 플랫폼(1.0.0 출시 예정)

  <ul>
      <li>Javascript 기반 웹 페이지</li>
      <li>iOS</li>
      <li>Mac OS X</li>
      <li>Android</li>
      <li>PHP</li>
      <li>Python</li>
      <li>Ruby</li>
      <li>node.js</li>
  </ul>

  지원되는 플랫폼의 전체 집합 및 시작에 대한 정보는 <a href="https://azure.microsoft.com/documentation/articles/app-insights-platforms/">설명서를</a> 참조하세요. SDK가 애플리케이션으로 컴파일되므로 실행되는 모든 코드를 완전히 이해하는 것이 중요하다고 생각합니다. 모든 SDK가 오픈 소스이거나 오픈 소스가 되는 과정에서 이러한 이해를 지원하려면 <a href="https://github.com/Microsoft/ApplicationInsights-Home">GitHub 홈</a>을 방문하여 자세한 내용을 확인하거나 기여하십시오.

  <h2>SDK는 무엇을 합니까?</h2>

  SDK는 다양한 자동 원격 분석 캡처를 기본적으로 제공합니다. <a href="https://azure.microsoft.com/documentation/articles/app-insights-get-started/">애플리케이션 Insights 시작하는</a> 것은 SDK를 애플리케이션에 통합하고 다시 빌드하는 것만큼 쉽습니다. 각 플랫폼별 SDK는 해당 플랫폼에 대해 가장 높은 값인 원격 분석을 자동으로 수집합니다.

  <h3></h3>

  <h3>Context 속성</h3>

  각 SDK는 모든 원격 분석 항목을 공통 컨텍스트 속성 집합으로 자동으로 채웁니다. 모든 원격 분석 항목에 대해 수집하면 Application Insights 포털에서 원격 분석 유형의 <a href="https://azure.microsoft.com/documentation/articles/app-insights-metrics-explorer/#segment-your-data">다차원 조각화</a> 작업을 수행할 수 있습니다. 또한 SDK는 userID 및 sessionID와 같은 상관 관계 값을 수집하여 서로 다른 원격 분석 형식 간에 상관 관계를 사용하도록 설정합니다. 아래 목록은 SDK에서 자동으로 제공하는 컨텍스트 속성 중 일부를 나타냅니다. 수집되는 값에 대해 보다 세분화된 제어를 원하는 경우 이러한 모든 값을 코드에 지정할 수 있습니다.

  <ul>
      <li>애플리케이션 버전</li>
      <li>언어</li>
      <li>Locale</li>
      <li>모델 이름</li>
      <li>OEM 이름</li>
      <li>네트워크 종류</li>
      <li>OS 버전</li>
      <li>브라우저 버전</li>
      <li>UserId</li>
      <li>SessionId</li>
      <li>OperationId</li>
      <li>국가 또는 지역</li>
  </ul>

  <h3></h3>

  <h3>사용량 원격 분석</h3>

  모든 클라이언트 SDK는 기본 <a href="https://go.microsoft.com/fwlink/?LinkID=616552">사용량 원격 분석을</a> 자동으로 수집합니다. 여기에는 익명 방식으로 사용자 및 세션 추적이 포함됩니다. 이 기본 원격 분석은 애플리케이션이 성공하고 고객이 사용하는지 이해하는 데 중요합니다. 또한 기본 사용량 원격 분석은 <a href="https://azure.microsoft.com/pricing/details/application-insights/">무료이며 무제한</a> 이며 월별 할당량에 대한 요금이 부과되지 않는다는 것을 편안하게 느낍니다.


  최근에(SDK 0.17 및 현재 1.0에서) 사용자 및 세션 수를 계산하는 방법에 중요한 변경 사항이 도입되었습니다. 지금까지 "세션"에 대한 정의는 광범위한 것이었습니다. 세션은 사용자 또는 다른 컴퓨팅 엔터티(예: RESTful 엔드포인트를 호출하는 다른 앱)에 의해 시작될 수 있습니다.이로 인해 많은 사용자에게 혼란이 있었고 메트릭 값이 부풀려질 수 있습니다. SDK 1.0부터 Application Insight의 세션은 "사용자 세션"을 의미합니다. 이러한 변경의 의미는 다음과 같습니다.

  <ul>
      <li>ASP.NET 및 Java 웹 SDK는 더 이상 사용자 및 세션 쿠키를 생성하지 않고 JavaScript SDK를 사용하여 이러한 쿠키를 제공합니다.웹앱에 대한 사용자 및 세션 추적을 구현하려면 이제 JS SDK를 사용한 계측이 필요합니다.</li>
      <li>SDK 1.0으로 계측된 앱은 특히 사용자가 아닌 호출의 사소한 볼륨을 가진 앱에 대해 더 적은 수의 사용자 및 세션을 보고할 수 있습니다.</li>
  </ul>

  자세한 내용은 <a href="https://azure.microsoft.com/documentation/articles/app-insights-release-notes-dotnet/">릴리스 정보</a> 및 <a href="https://azure.microsoft.com/documentation/articles/app-insights-web-track-usage/#sessions">설명서 페이지를</a> 참조하세요.

  <h3>페이지 보기</h3>

  SDK는 페이지 보기 원격 분석도 자동으로 수집합니다. 웹 애플리케이션의 경우 페이지 보기 및 페이지 보기 성능의 인기도에 대한 기존 보기를 가져옵니다. 모바일 디바이스 앱의 경우 SDK는 각 플랫폼에서 UI 보기의 리딩을 나타내는 페이지 보기를 수집합니다. 이를 통해 사용자가 애플리케이션에 참여하는 경우뿐만 아니라 애플리케이션의 어떤 부분이 가장 자주 사용되는지 파악할 수 있습니다.

  <h3>충돌 및 예외</h3>

  애플리케이션 내에서 오류를 진단할 수 있는 것은 제품의 성공에 매우 중요합니다. 어려운 오류 사례의 진단을 지원하기 위해 AppInsights SDK는 <a href="https://azure.microsoft.com/documentation/articles/app-insights-windows-crashes/">클라이언트 앱 충돌</a> 및 <a href="https://azure.microsoft.com/documentation/articles/app-insights-asp-net-exceptions/">서버 오류 및 예외와</a> 관련된 원격 분석을 수집합니다. SDK는 이 진단 정보를 수집하는 데 상당한 양의 값을 제공할 수 있으며 앱의 실패 모드에 대한 심층적인 인사이트를 제공합니다. iOS 크래시에는 기계 코드 크래시 보고서를 읽을 수 있는 스택 추적으로 변환하는 기호화 지원이 포함됩니다. 서버 앱의 경우 요청 실패와 예외 및 종속성 오류의 상관 관계를 허용합니다.

  <h3>요청 및 종속성 원격 분석</h3>

  서버 및 서비스 애플리케이션의 경우 웹 및 Java SDK는 들어오는 모든 프로세스 요청의 자동 원격 분석 컬렉션과 나가는 모든 종속성 호출에 대한 세부 정보를 제공합니다. 이 정보는 서버 앱의 <a href="https://azure.microsoft.com/documentation/articles/app-insights-web-monitor-performance/">성능</a> 및 운영 특성을 이해하는 데 중요합니다. SDK는 기간 및 성능, 상태 코드 및 다른 원격 분석 데이터와 상관 관계에 대한 정보를 포함하여 심층적인 수준의 데이터 수집을 제공합니다.

  <h3>성능 카운터</h3>

  애플리케이션 Insights SDK는 애플리케이션이 실행되는 위치에서 컴퓨터 성능 카운터를 수집하는 기능을 지원합니다. SDK는 프로세서 CPU 및 사용 가능한 메모리와 같은 기본 성능 카운터를 수집하는 것 외에도 Windows 머신에서 <a href="https://blogs.msdn.com/b/visualstudioalm/archive/2015/04/01/application-insights-choose-your-own-performance-counters.aspx">사용자 지정 성능 카운터</a> 의 컬렉션을 지원합니다. 성능 카운터의 컬렉션은 애플리케이션 호스트 환경이 애플리케이션에 미치는 영향을 모니터링하고 진단하는 데 중요한 인사이트를 제공할 수 있습니다.

  <h3>원격 분석 추적</h3>

  애플리케이션 Insights SDK는 <a href="https://go.microsoft.com/fwlink/?LinkID=616916">추적(또는 로그) 원격 분석</a>의 수집을 허용합니다. Log4Net, NLog, System.Diagnostics, LogBack 또는 Log4J와 같이 잠재적으로 사용 중인 기존의 많은 추적 로깅 프레임워크에서 원격 분석을 자동으로 캡처하도록 SDK를 구성할 수 있습니다. 자동 수집 외에도 항상 SDK API를 통해 직접 추적 원격 분석을 기록할 수 있습니다.

  <h3>사용자 지정 원격 분석</h3>

  SDK는 간단하고 강력한 API를 제공합니다. 이 API를 사용하면 사용자 지정 원격 분석 데이터를 로깅할 수 있습니다. 모든 자동 원격 분석은 API를 통해 제어, 보강 또는 교체할 수 있습니다. 또한 2개의 전용 사용자 지정 원격 분석 유형, 이벤트 및 메트릭을 노출합니다. 사용자 지정 이벤트 및 메트릭은 원격 분석 데이터를 수집하기 위한 강력한 도구입니다. 사용자 지정 이벤트는 애플리케이션 내에서 추적된 작업의 단일 개별 인스턴스를 나타냅니다. 사용자 지정 메트릭은 데이터 값의 간단한 로깅을 통해 시계열 기반 데이터의 로깅을 지원하며, 시간이 지남에 따라 평균 및 합계 메트릭을 추출할 수 있습니다. 또한 모든 원격 분석 사용자 지정 원격 분석을 속성으로 채울 수 있는 것처럼 나중에 다차원 분석을 수행할 수 있습니다.

  <h2>시작하려면 어떻게 해야 하나요?</h2>

  애플리케이션 Insights 값과 SDK에서 제공하는 기능을 이해하는 가장 좋은 방법은 애플리케이션 Insights 기존 애플리케이션에 추가하거나 새 프로토타입 애플리케이션으로 사용해보는 것입니다. <a href="https://azure.microsoft.com/documentation/articles/app-insights-platforms/">시작</a> 프로세스는 5분 이상 걸리지 않습니다. 또한 새 애플리케이션이 <a href="https://azure.microsoft.com/pricing/details/application-insights/">무료 계층</a>의 일부로 생성되므로 애플리케이션 Insights 빠르고 위험 평가가 가능합니다.


  기존 애플리케이션 Insights 고객 <a href="https://go.microsoft.com/fwlink/?LinkID=616915">업그레이드</a>는 간단합니다. NuGet 패키지 관리자를 활용하여 참조를 안정적인 최신 버전으로 업그레이드합니다.
