### YamlMime:Yaml
ms.openlocfilehash: 78904634ab9a94b2a56c8d5d2673974b6b507684
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139902842"
Slug: announcing-new-azure-functions-capabilities-to-accelerate-development-of-serverless-applications
Title: 서버리스 애플리케이션 개발을 가속화하는 새로운 Azure Functions 기능 발표
Summary: 오늘 Azure Functions를 사용하여 서버리스 애플리케이션 개발을 가속화하는 몇 가지 새로운 기능에 대한 미리 보기 지원을 발표하게 되어 기쁩니다.
Content: >-
  <p><a href="https://azure.microsoft.com/en-us/services/functions/">Azure Functions</a>가 도입된 이래로 고객이 이를 사용하여 흥미롭고 영향력 있는 <a href="https://customers.microsoft.com/en-us/search?sq=%22Azure%20Functions%22&amp;ff=&amp;p=0">솔루션을 빌드하는</a> 것을 보았습니다.&nbsp; 서버리스 아키텍처, 다른 솔루션과 쉽게 통합할 수 있는 기능, 간소화된 개발 환경 및 Azure Functions에서 사용하도록 설정된 주문형 크기 조정은 여러 시나리오에서 계속해서 큰 용도를 찾고 있습니다.</p>


  <p>오늘 Azure Functions를 사용하여 서버리스 애플리케이션 개발을 가속화하는 몇 가지 새로운 기능에 대한 미리 보기 지원을 발표하게 되어 기쁩니다.</p>


  <h2>서버리스 프레임워크와 통합</h2>


  <p>오늘 <a href="https://serverless.com/">the</a>&rsquo; 서버리스 프레임워크<a href="https://serverless.com/">와 Azure</a> Functions 통합에 대한 미리 보기 지원을 발표했습니다. 서버리스 프레임워크는 모든 클라우드에서 서버리스 애플리케이션의 배포 및 모니터링을 간소화하는 인기 있는 오픈 소스 도구입니다. 서버리스 리소스의 세부 정보를 추상화하고 개발자가 애플리케이션의 중요한 부분에 &ndash; 집중할 수 있도록 합니다. 이 통합은 <a href="https://aka.ms/serverlessfx">공급자 플러그 인</a>을 통해 제공되므로 이제 Azure Functions는 서버리스 프레임워크 환경에서 일류 참가자가 됩니다.&nbsp; Azure Functions의 출처가 오픈 소스 <a href="https://github.com/Azure/azure-webjobs-sdk">Azure WebJobs SDK</a>에 있었다는 점을 감안할 때 이 커뮤니티 노력에 기여하는 것은 매우 자연스러운 선택이었습니다.</p>


  <p><a href="https://www.serverless.com/framework/docs/providers/azure/">Azure Functions 서버리스 프레임워크 설명서 및 Azure Functions 서버리스 프레임워크</a> 블로그 게시물에서 플러그 인 <a href="https://aka.ms/msdnserverlessfx"></a> 에 대해 자세히 알아볼 수 있습니다.&nbsp;</p>


  <h2>Azure Functions 프록시</h2>


  <p>함수는 일부 트리거(이벤트)에 대한 응답으로 수행해야 하는 작업을 빠르게 표현하는 환상적인 방법을 제공합니다.&nbsp; 이는 여러 고객이 이미 Functions를 사용하고 있는 API처럼 매우 많이 들립니다.&nbsp; &rsquo;또한 고객이 개별 구성 요소 간의 배포 격리가 필요한 마이크로 서비스 아키텍처에 Functions를 사용하기 시작했습니다.</p>


  <p>오늘 Azure Functions 프록시의 미리 보기를 발표하게 되어 기쁘게 생각합니다. Azure Functions를 사용하여 API를 더 쉽게 개발할 수 있는 새로운 기능입니다. 프록시를 사용하면 여러 함수 앱에 대한 단일 API 표면을 정의할 수 있습니다. 이제 모든 함수 앱은 다른 함수 앱, API 앱 또는 다른 API에 대한 역방향 프록시 역할을 하는 엔드포인트를 정의할 수 있습니다.</p>


  <p><a href="https://docs.microsoft.com/azure/azure-functions/functions-proxies">설명서</a> 페이지 및 Azure Functions 프록시 공개 미리 보기 블로그 게시물로 이동하여 <a href="https://blogs.msdn.microsoft.com/appserviceteam/2017/02/22/azure-functions-proxies-public-preview/">Azure Functions 프록시</a>에 대해 자세히 알아볼 수 있습니다. 이 기능은 미리 보기 상태에서는 무료이지만 표준 Functions 청구는 프록시 실행에 적용됩니다. 자세한 내용은 <a href="https://azure.microsoft.com/pricing/details/functions/">Azure Functions 가격 책정 페이지를</a> 참조하세요.</p>


  <h2>PowerApps 및 Flow 통합</h2>


  <p><a href="https://powerapps.com/">PowerApps</a> 및 <a href="https://flow.microsoft.com/">Flow</a> 조직 내의 비즈니스 사용자가 비즈니스 프로세스에 대한 지식을 솔루션으로 전환할 수 있도록 하는 서비스입니다. 코드를 작성하지 않고도 사용자는 다양한 엔터프라이즈 데이터 및 서비스와 상호 작용하는 앱 및 사용자 지정 자동화된 워크플로를 쉽게 만들 수 있습니다. 사용자는 다양한 기본 제공 SaaS 통합을 활용할 수 있지만 회사별 비즈니스 프로세스를 통합해야 하는 경우가 많습니다. 이러한 사용자 지정 논리는 일반적으로 전문 개발자에 의해 빌드되었지만 이제는 앱을 빌드하는 비즈니스 사용자가 워크플로에서 이러한 논리를 사용할 수 있습니다.</p>


  <p><a href="https://azure.microsoft.com/en-us/services/app-service/">Azure App Service</a>와 Azure Functions는 모두 많은 앱 및 활동에 필요한 중요한 비즈니스 논리를 표현하는 조직 API를 빌드하는 데 적합합니다.&nbsp; 이제 PowerApps로 내보내기 및 Microsoft Flow 제스처를 포함&quot;하도록 App Service 및 Azure Functions의 API 정의 기능을 확장한&#39;&quot;. 그러면 App Service 또는 Azure Functions의 API를 PowerApps 및 Flow 사용자가 사용할 수 있도록 하는 데 필요한 모든 단계를 안내합니다. 자세한 내용은 <a href="https://docs.microsoft.com/azure/app-service/app-service-export-api-to-powerapps-and-flow">설명서를</a> 참조하고 <a href="https://aka.ms/msdnpowerappsflow">PowerApps용 API 및 Flow</a> 블로그 게시물을 참조하세요.</p>


  <p>이러한 새로운 기능을 여러분의 손에 맡기게 되어 기쁘게 생각하고 <a href="https://social.msdn.microsoft.com/Forums/en-US/home?forum=AzureFunctions">포럼</a>, <a href="https://stackoverflow.com/questions/tagged/azure-functions">StackOverFlow</a> 또는 <a href="https://feedback.azure.com/forums/355860-azure-functions/filters/top">Uservoice</a>를 통해 여러분의 의견을 기다리고 있습니다.</p>
