### YamlMime:Yaml
ms.openlocfilehash: de1af79f86f343e4417a4611e03ad175c01aa987
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139902783"
Slug: application-aware-availability-solutions-with-azure-site-recovery
Title: Azure Site Recovery를 사용하여 가용성 솔루션 Application-Aware
Summary: 지난 몇 개월 동안 Microsoft에서 이러한 애플리케이션 그룹과 긴밀한 파트너십을 맺고 ASR을 사용하여 동급 최고의 재해 복구 및 가용성 솔루션을 배포할 수 있도록 했습니다.
Content: >-
  Azure Site Recovery를 사용하면 고객이 <a href="https://aka.ms/asr_workload_aod">주문형 솔루션에 애플리케이션 인식 가용성을 배포할 </a>수 있습니다. 서버 또는 Linux 기반 애플리케이션, Microsoft 자사 엔터프라이즈 애플리케이션 또는 다른 공급업체의 제품을 Windows Azure Site Recovery를 사용하여 재해 복구를 사용하도록 설정하거나 주문형 DevTest 환경을 배포하거나 Azure로 마이그레이션할 수 있습니다. ASR 복제 기술은 모든 디스크 및 데이터로 전체 가상 머신을 보호할 수 있습니다. 이렇게 하면 컴퓨터에서 실행되는 <strong><em>모든 애플리케이션</em></strong> 과 호환될 수 있습니다.


  Microsoft는 SharePoint, Exchange, Dynamics, SQL Server 같은 동급 엔터프라이즈 애플리케이션에서 최고의 개발을 위한 전문 지식과 경험을 보유하고 있습니다. 지난 몇 개월 동안 Microsoft에서 이러한 애플리케이션 그룹과 긴밀하게 협력하여 ASR을 사용하여 사용자 지정된 재해 복구 및 가용성 솔루션을 배포할 수 있도록 했습니다. <strong> Azure Site Recovery 솔루션은 테스트되었으며 이제 SharePoint, Dynamics AX, Exchange 2013, 원격 데스크톱 서비스, SQL Server, IIS 애플리케이션 및 Operations Manager와 같은 System Center 제품군에 대해 지원됩니다</strong>.Microsoft 애플리케이션 외에도 다양한 Linux 배포판에서 실행되는 SAP 및 애플리케이션과 같은 타사 애플리케이션에 대한 광범위한 테스트를 수행하고 지원합니다.


  Azure Site Recovery 기능은 애플리케이션 수준 보호/복구를 염두에 두고 설계되었습니다.

  <ul>
      <li>가장 중요한 애플리케이션의 필요를 충족하는 30초 이하의 RPO와 <b><i>거의 동기화된 복제</i></b>입니다.</li>
      <li>단일 또는 N 계층 애플리케이션<strong><em>에 대한 앱 일치 스냅샷</em></strong></li>
      <li><b><i>앱 수준 복제와 통합을 선택할 &amp;</i></b>수 있는 유연성. 해당하는 경우 AD 복제, SQL Always On, Exchange 데이터베이스 가용성 그룹과 같은 클래스 애플리케이션 수준 제품에서 가장 잘 활용합니다. 다른 계층에 ASR의 기본 제공 복제를 사용합니다.</li>
      <li>확장 <b><i>가능한 복구 계획은 </i></b>전체 애플리케이션을 모델링하고 애플리케이션 인식 복구/마이그레이션 워크플로를 구성합니다. 필요한 경우 단일 클릭 엔드-엔드 애플리케이션 복구를 트리거합니다.</li>
      <li>ASR 및 Azure의 <b><i>고급 네트워크 관리</i></b>. 애플리케이션과 관련된 모든 네트워킹 구성을 자동화합니다. 즉, IP 주소를 예약하거나, 부하 분산 장치를 구성하거나, 낮은 RTO 전환에 트래픽 관리자를 사용합니다.</li>
      <li>프로덕션 지원 애플리케이션별 스크립트를 제공하는 <b><i>리치 자동화 라이브러리</i></b>입니다. 이를 다운로드하고 ASR 기반 솔루션에 통합합니다.</li>
  </ul>

  &nbsp;


  SharePoint 또는 Dynamics AX 배포를 관리하는 경우 ASR을 사용하여 DR 또는 DevTest에 대한 대기 배포 유지 관리 비용 및 오버헤드를 제거할 수 있습니다. ASR은 전체 팜을 복제하고 재해 복구 또는 프로덕션과 유사한 테스트 복사본을 만들기 위해 주문형으로 가져올 수 있습니다. 주 팜에 배포된 새 애플리케이션 또는 구성 변경 내용은 몇 분 내에 자동으로 복제되므로 보조 팜을 최신 상태로 유지하기 위해 복잡한 프로세스에 투자할 필요가 없습니다.


  SQL 서버는 많은 중요한 엔터프라이즈 애플리케이션의 기초입니다. ASR을 사용하면 다른 사이트 또는 Azure에 <a href="https://aka.ms/asr_workload_sql">SQL Server 쉽게 복제하고 복구할 수 있습니다</a>. 또한 ASR은 SQL Always On 가용성 그룹과 같은 클래스 네이티브 재해 복구 솔루션과 통합하고 ASR 복구 계획의 일부로 장애 조치(failover) 작업을 관리할 수 있습니다.


  Exchange 서버의 경우 DAG는 클래스 재해 복구 솔루션에서 가장 적합하며 권장되는 배포 옵션입니다. ASR 복구 계획을 DAG와 통합하여 스크립트된 작업을 통해 사이트 간 DAG 장애 조치(failover)를 오케스트레이션할 수 있습니다. 단일 서버 또는 비클러스터형 서버와 같은 소규모 Exchange 2013 배포의 경우 고객은 Azure Site Recovery를 사용하여 보조 온-프레미스 사이트로 서버를 보호할 수 있습니다.


  Windows 서버의 원격 데스크톱 서비스는 사용자가 세션 기반 데스크톱, 가상 머신 기반 데스크톱 또는 애플리케이션에 액세스할 수 있도록 하는 기술을 제공합니다. ASR을 사용하면 RDS 배포를 위한 재해 복구 또는 클라우드 버스팅 솔루션을 배포하고 고객이 항상 고화질 데스크톱 환경을 사용할 수 있도록 할 수 있습니다.


  IGNITE 컨퍼런스에서 이러한 애플리케이션 관련 솔루션 및 지원되는 구성에 대해 자세히 살펴보겠습니다. <a href="https://aka.ms/asr_at_ignite">이번 주 IGNITE에서 ASR 관련 세션을</a> 체크 아웃하는 것이 좋습니다. 또한 이러한 솔루션을 환경에 쉽게 배포할 수 있도록 몇 주 안에 설명서 사이트를 통해 자세한 기술 지침을 공유할 예정입니다.이는 진행 중인 여정이며, Azure Site Recovery를 사용하여 더 많은 애플리케이션을 커버하고 더 풍부한 애플리케이션 인식 환경을 조명하는 데 계속 투자할 것입니다.


  <a href="https://aka.ms/asr_ignite_app_aware">ASR을 사용하여 재해 복구를 배포하기 위한 모범 사례에 대한 Ignite 세션의</a> 기록을 확인합니다.
