### YamlMime:Yaml
ms.openlocfilehash: d5072ec44b4062c4dc64d558eb937399b4e0f3f5
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139907933"
Slug: application-insights-integrates-alooma
Title: 'Visual Studio 애플리케이션 Insights 확장성: Alooma를 사용하여 원격 분석 데이터를 Amazon Redshift로 내보내기'
Summary: 애플리케이션 Insights 다른 도구와의 통합을 위해 빌드되었으며, 더 쉽게 만들 수 있도록 계획에 대해 알려드립니다. 하지만 먼저 통합 파트너 중 하나인 Alooma를 소개하려고 합니다.
Content: >-
  <p><a href="https://azure.microsoft.com/services/application-insights/">Visual Studio 애플리케이션 Insights</a> 다른 도구와의 통합을 위해 빌드되었으며, 오늘 결혼&rsquo;은 더 쉽게 하기 위한 계획에 대해 알려드립니다. 하지만 먼저 통합 파트너 &ndash; 인 <a href="https://www.alooma.com/">Alooma</a>를 소개하고 싶습니다. Aloomas&rsquo; SaaS 서비스를 사용하면 Application Insights 수집한 원시 원격 분석 이벤트를 Amazon Redshift와 같은 데이터 웨어하우스로 쉽게 변환할 수 있습니다. 데이터가 있으면 다양한 분석 및 BI 도구에서 쉽게 액세스할 수 있습니다.</p>


  <p><img alt="Export Application Insights data to Amazon Redshift with Alooma" border="0" height="279" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/b4b98fe2-45a8-4c53-ba1b-6169add7d854.png" style="border-left-width: 0px; border-right-width: 0px; background-image: none; border-bottom-width: 0px; float: none; padding-top: 0px; padding-left: 0px; display: inline; padding-right: 0px; border-top-width: 0px" title="Alooma를 사용하여 애플리케이션 Insights 데이터를 Amazon Redshift로 내보내기" width="800"></p>


  <p>간단히 말해서 Alooma는 다음을 사용하도록 설정합니다.</p>


  <ul>
   <li>데이터 원본을 쉽게 통합: 수십 개의 기본 제공 커넥터를 사용하거나 Aloomas&rsquo; 웹 및 모바일 API를 사용하여 사용자 고유의 커넥터를 빌드합니다.</li>
   <li>즉석에서 데이터 변환: 스트림 내 변환을 사용하면 실시간으로 데이터를 필터링, 정리, 수정 및 보강할 수 있습니다.</li>
   <li>데이터가 저장되는 방식을 제어합니다. 데이터를 테이블에 자동 매핑하거나 데이터 탐색 도구를 사용하여 최적의 매핑을 안내합니다.</li>
   <li>변경된 스키마를 지능적으로 처리합니다. 데이터에 새 필드가 나타나거나 기존 필드가 다른 형식으로 표시될 때 알림을 받습니다. 새 스키마의 이벤트는 로드할 방법을 결정할 때까지 유지되며 데이터가 손실되지 않습니다.</li>
   <li>투명한 모니터링: 기본 제공 대시보드를 사용하여 파이프라인의 성능을 모니터링하거나 Aloomas&rsquo; 메트릭 API를 통해 직접 빌드합니다.</li>
  </ul>


  <p>Alooma를 애플리케이션 Insights 통합하면 &ndash; <a href="https://www.alooma.com/blog/application-insights-amazon-redshift">Alooma와 함께 Amazon Redshift로 애플리케이션 Insights 내보내</a>기에서 자세한 지침을 쉽게 확인할 수 있습니다.</p>


  <h2>Application Insights와의 통합</h2>


  <p>Alooma는 애플리케이션 Insights 첫 번째 파트너 통합 중 하나입니다. &rsquo;엔지니어링 팀으로서 개발/DevOps 주기를 지원하기 위해 다양한 도구를 사용하려고 합니다. Microsoft와 마찬가지로 특정 사용자 지정 워크플로에 맞게 이러한 도구를 함께 짜는 동시에 특정 작업에 적합한 동급 최고의 도구를 사용하려고 합니다.</p>


  <p>이러한 요구를 해결하기 위해 애플리케이션 Insights REST API, 오픈 소스 SDK 등과 같은 업계 표준 확장성 메커니즘을 통해 쉽게 통합할 수 있는 확장 가능한 개방형 플랫폼으로 설계했습니다. 이러한 확장성 지점 중 일부는 현재 사용할 수 있으며 곧 추가 사항을 발표하기 위해 노력하고 있습니다.</p>


  <h2>확장성 메커니즘</h2>


  <p>애플리케이션 Insights 데이터 중심 솔루션이므로 초기 초점은 데이터 계층에서 통합을 사용하도록 설정하는 것입니다. 이러한 범주는 다음과 같은 두 가지 광범위한 범주로 분류됩니다.</p>


  <ol>
   <li>애플리케이션 Insights 데이터 보내기: 애플리케이션 구성 요소, 환경 및 인프라 또는 애플리케이션 수명 주기에서 원격 분석 데이터를 애플리케이션 Insights SDK를 사용하거나 REST API를 통해 보낼 수 있습니다. 이 데이터는 애플리케이션 Insights 풍부한 정보 모델을 사용하여 저장되며 애플리케이션 Insights&rsquo; <a href="https://azure.microsoft.com/documentation/articles/app-insights-portal/">포털</a>에서 메트릭 탐색기 및 검색 탐색기를 사용하여 추가 분석 및 시각화에 사용할 수 있습니다.</li>
   <li>다른 도구에서 애플리케이션 Insights 데이터 사용: Application Insights 수집 및 저장한 원격 분석 데이터에서 중요한 값을 잠금 해제할 수 있습니다. 현재는 <a href="https://azure.microsoft.com/documentation/articles/app-insights-export-telemetry/">연속 내보내</a>기를 통해<a href="https://azure.microsoft.com/documentation/articles/app-insights-export-power-bi/">, Power BI 통합</a>을 통해, 그리고 이제 Alooma 통합을 통해 이를 사용하도록 설정합니다. 추가 API 기반 데이터 솔루션이 작동합니다. 이 작업을 수행하고 Application Insights User Voice에서 이 항목을 통해 피드백을 제공할 수 있습니다(추가 항목에는 웹후크 콜백 및 경고 시스템 통합 포함).</li>
  </ol>


  <p>고객은 이미 이러한 메커니즘을 사용하여 사용자 지정 통합을 사용하도록 설정합니다. 또한 파트너와 협력하여 보다 간소화된 통합 환경을 구현하고 있습니다. SDK 및 통합의 전체 목록은 <a href="https://azure.microsoft.com/en-us/documentation/articles/app-insights-platforms/">언어, 플랫폼 및 통합 인덱스를</a> 참조하세요.</p>


  <p>Application Insights User Voice에서 새로운 기능 또는 향상된 기능에 대한 아이디어를 공유하세요. 궁금한 사항은 <a href="https://social.msdn.microsoft.com/Forums/vstudio/en-US/home?forum=ApplicationInsights">애플리케이션 Insights 포럼</a>을 방문하세요.</p>


  <p>잠재적인 파트너 관계 기회를 위해 다음을 통해 <a href="mailto:aipartners@microsoft.com">aipartners@microsoft.com</a> 문의하세요.</p>
