### YamlMime:Yaml
ms.openlocfilehash: 1a088622db6aec2a0f43b60e85dac0dc50b95155
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139913200"
Slug: application-insights-work-item-integration-with-visual-studio-team-services
Title: '애플리케이션 Insights: Visual Studio Team Services 작업 항목 통합'
Summary: 오늘은 Visual Studio Team Services(즉, VSTS)와 작업 항목 통합에 대해 논의하겠습니다.
Content: >-
  <p>&rsquo;내 마지막 블로그 게시물 이후 잠시 동안, 하지만 애플리케이션 Insights ALM 팀은 새로운 기능에 열심히 노력 하고있다. 오늘 Im&rsquo;은 Visual Studio Team Services(즉, VSTS)와 작업 항목 통합에 대해 설명합니다.</p>


  <p>작업 항목 통합 기능을 사용하면 관련 애플리케이션 Insights 데이터가 포함된 VSTS에서 작업 항목을 쉽게 만들 수 있습니다. 이 연결을 구성하고 작업 항목 만들기를 시작하는 것은 매우 간단합니다(이 프로세스는 1~2분만 소요됨).</p>


  <h3>작업 항목 통합 구성</h3>


  <p>애플리케이션 Insights 리소스에 대한 작업 항목 통합을 구성하려면 해당 리소스에 대한 설정 블레이드로 이동하면 됩니다. &rsquo;이제 설정 블레이드의 구성&rdquo; 섹션에 &ldquo;작업 항목이 표시된 새 항목이 있습니다&ldquo;.&rdquo;</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/9434e196-ddd0-4402-981e-81b56a3969ed.png"><img alt="" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/3496395a-1e72-4415-a9b1-717829500c89.png" style="border-left-width: 0px; height: 334px; border-right-width: 0px; width: 281px; background-image: none; border-bottom-width: 0px; padding-top: 0px; padding-left: 0px; display: inline; padding-right: 0px; border-top-width: 0px" title=""></a></p>


  <p>이 옵션을 클릭하면 작업 항목에 대한 구성 블레이드가 열립니다. 작업 항목을 작성하려는 프로젝트와 함께 연결하려는 VSTS 시스템에 대한 정보를 입력하기만 하면 됩니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/09553076-32e2-4fcb-9cea-f8bc92c8f34f.png"><img alt="" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/5f7ad1d9-8928-49f7-b37d-30e75c750e40.png" style="border-left-width: 0px; height: 727px; border-right-width: 0px; width: 408px; background-image: none; border-bottom-width: 0px; padding-top: 0px; padding-left: 0px; display: inline; padding-right: 0px; border-top-width: 0px" title=""></a></p>


  <p>해당 정보가 있으면 권한 부여 단추를 클릭하면 선택한 VSTS 시스템에서 액세스 권한을 부여하도록 리디렉션되어 작업 항목을 여기에 쓸 수 있습니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/8431dd0c-d6e2-4f3c-b867-7ce2a5ec822b.png"><img alt="" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/561dc8ff-5ffb-43f8-9393-f19b5bd420c8.png" style="border-left-width: 0px; height: 376px; border-right-width: 0px; width: 649px; background-image: none; border-bottom-width: 0px; padding-top: 0px; padding-left: 0px; display: inline; padding-right: 0px; border-top-width: 0px" title=""></a></p>


  <p>&rsquo;권한 부여 프로세스를 완료한 후에는 영역 경로&rdquo;에 대한 &ldquo;기본값을 &ldquo;설정하고 할당할 수 있습니다.&quot; 영역 경로만 필요합니다(프로젝트에서&rsquo; 특정 영역 경로를 설정하지 않은&rsquo; 경우 괜찮습니다. 최상위 영역 경로이므로 프로젝트의 이름을 사용합니다. 확인을 클릭하고 모든 항목을 올바르게 입력했다고 가정&rsquo;하면&rsquo;&ldquo; 유효성 검사가 성공&rdquo;하고 블레이드가 닫힙니다. &rsquo;이제 작업 항목 만들기를 시작할 준비가 되었습니다.</p>


  <h3>작업 항목 만들기</h3>


  <p>애플리케이션 Insights 작업 항목을 만드는 것은 매우 쉽습니다. 현재 작업 항목을 만들 수 있는 위치는 자동 관리 검색 및 작업의 개별 인스턴스(예: 예외, 오류, 요청 등)의 두 가지 위치입니다. 후자의 간단한 예제를 보여 주지만 두 경우 모두 기능이 동일합니다.</p>


  <p>이 예제에서는 Ive&rsquo;&rsquo;가 Azure에 게시한 테스트 웹앱을 확인합니다. Ive&rsquo;는 실패 블레이드를 확인하여 이 앱에 대한 작업을 자세히 살펴보기 시작했습니다(그러나 검색 단추 또는 메트릭 탐색기를 통해 이 동일한 정보를 얻을 수도 있음).</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/0211eb81-2ed6-405c-bcab-596e593a47dd.png"><img alt="" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/6cf284c3-dec5-4458-a8f3-701c02226ace.png" style="border-left-width: 0px; height: 532px; border-right-width: 0px; width: 721px; background-image: none; border-bottom-width: 0px; padding-top: 0px; padding-left: 0px; display: inline; padding-right: 0px; border-top-width: 0px" title=""></a></p>


  <p>사용자가 이 웹앱의 홈/정보 탭을 클릭할 때 발생한 여러 가지 예외가 있음을 알 수 있습니다. 이 예외 그룹을 드릴인하면 목록을 보고 개별 예외를 선택할 수 있습니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/37776ad4-53b1-413f-9778-9c0579d73f10.png"><img alt="" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/736561ea-f22b-4add-9d28-f85803a2bd6e.png" style="border-left-width: 0px; height: 628px; border-right-width: 0px; width: 972px; background-image: none; border-bottom-width: 0px; padding-top: 0px; padding-left: 0px; display: inline; padding-right: 0px; border-top-width: 0px" title=""></a></p>


  <p>이 예외에 대한 세부 정보 블레이드를 살펴보면 이제 블레이드 맨 위에 새 작업 항목 및 &ldquo;작업 항목&rdquo; 보기를 읽&ldquo;는 두 개의 단추를 사용할 수 있습니다.&rdquo; 작업 항목을 만들려면 다음 단추 중 첫 번째 단추를 클릭하면 새 작업 항목 블레이드가 열립니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/d43ee541-1e00-49df-aa1b-5c058adee96a.png"><img alt="" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/8fb0d5e6-531d-4bc8-af21-9a9cfc0a8916.png" style="border-left-width: 0px; height: 834px; border-right-width: 0px; width: 715px; background-image: none; border-bottom-width: 0px; padding-top: 0px; padding-left: 0px; display: inline; padding-right: 0px; border-top-width: 0px" title=""></a></p>


  <p>여기서 볼 수 있듯이, 평균 시나리오에 필요한 거의 모든 것이 채워져 있습니다. 초기 구성에서 지정한 영역 경로 및 &quot;할당&quot;된 영역 경로&quot;의 기본값&quot;이 설정되고 이 예외에 사용할 수 있는 모든 세부 정보가 세부 정보 필드에 추가되었습니다. 원하는 경우 제목, 영역 경로를 재정의하고 이 블레이드의 필드에 할당하거나 캡처된 세부 정보에 추가할 수 있습니다. &rsquo;작업 항목을 만들 준비가 되면 확인&rdquo; 단추를 클릭하면 &ldquo;작업 항목이 VSTS에 기록됩니다.</p>


  <h3>작업 항목 보기</h3>


  <p>&rsquo;애플리케이션 Insights 하나 이상의 작업 항목을 만든 후에는 VSTS에서 쉽게 볼 수 있습니다. Azure Portal에 있는 경우 작업 항목에 연결된 이벤트에 대한 세부 정보 블레이드에 작업 항목&rdquo; 보기 단추가 &ldquo;활성화됩니다. 목록을 보려면 단추를 클릭하기만 하면 됩니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/291129dd-5c78-46bd-904a-96a5b6e957f8.png"><img alt="" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/3827eac5-4fb1-4655-a2c7-eff2e796e3bd.png" style="border-left-width: 0px; height: 478px; border-right-width: 0px; width: 869px; background-image: none; border-bottom-width: 0px; padding-top: 0px; padding-left: 0px; display: inline; padding-right: 0px; border-top-width: 0px" title=""></a></p>


  <p>보려는 작업 항목의 링크를 클릭하면 VSTS에서 열립니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/22c94c87-7365-49fa-bc98-a332e06dcf27.png"><img alt="" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/c604c3dd-6fa7-4518-8936-b7d062e67434.png" style="border-left-width: 0px; height: 493px; border-right-width: 0px; width: 909px; background-image: none; border-bottom-width: 0px; padding-top: 0px; padding-left: 0px; display: inline; padding-right: 0px; border-top-width: 0px" title=""></a></p>


  <p>&nbsp;</p>


  <h3>고급 구성</h3>


  <p>일부 사용자는 고급 구성이라는 레이블 &ldquo;이 지정된 구성 블레이드에 스위치가 있음을 알 수 있습니다.&rdquo; 이 기능은&rsquo; 기본 설정 중 일부를 변경하거나 확장한 시나리오&rsquo;에서 VSTS에 쓰는 기능을 구성하는 데 도움이 되도록 제공되는 추가 기능입니다. 이 예제의 좋은 예는 추가 필수 필드를 지정하는 것입니다. 현재 표준 구성에서 이 추가 필수 매핑을 처리할 수 있는 방법은 없지만 고급 모드에서 처리할 수 있습니다.</p>


  <p>스위치를 클릭하면 블레이드 아래쪽에 있는 컨트롤이 다음과 같이 변경됩니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/56b5ed31-f075-4c76-b8aa-fbba9f1b68cd.png"><img alt="" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/c516eb89-5991-439d-9072-a66fe391f1fd.png" style="border-left-width: 0px; height: 304px; border-right-width: 0px; width: 574px; background-image: none; border-bottom-width: 0px; padding-top: 0px; padding-left: 0px; display: inline; padding-right: 0px; border-top-width: 0px" title=""></a></p>


  <p>이제 VSTS 프로젝트 수정을 처리하는 데 필요할 수 있는 모든 특정 설정/매핑을 지정할 수 있는 JSON 기반 편집 상자가 제공됩니다. 일부 샘플 텍스트가 채워집니다. 가까운 장래에 Intellisense를 사용하여 이 컨트롤을 강화하고 고급 구성 모드를 더 잘 이해하기 위한 몇 가지 기본 지침을 게시할 계획입니다.</p>


  <h3>다음 단계</h3>


  <p>작업 항목 기능을 애플리케이션 Insights 통합하는 것이 좋은 시작이라고 생각합니다. 그러나 이 기능은 기본적으로 이 기능 집합의 1.0 버전이라는  사실에 유의하세요. 우리는 많은 작업을 계획하고, 당신은 앞으로 몇 달 동안이 공간에서 상당한 진화를 볼 수 있습니다. 우선, 이미 계획에 있거나 조사 중인 몇 가지 사항을 간략하게 살펴보겠습니다.</p>


  <ul>
   <li><em><strong>모든 작업 항목 유형</strong></em> &ndash; 에 대한 지원 현재 기능 집합이 작업 항목 유형을 버그로 &ldquo;잠근다는 것을 알 수 있습니다.&rdquo; 로깅 버그가 이 공간에 대한 기본 요청이었기 때문에&rsquo; 시작했지만, 상황이 끝나야 하는&rsquo; 위치는 확실히 생각하지 않습니다&rsquo;. 더 단기적인 변경 내용 중 하나는 VSTS에서 지원되는 모든 프로세스에 대해 모든 작업 항목 유형을 처리하는 것입니다.</li>
   <li><em><strong>애플리케이션 Insights</strong></em> &ndash; 다시 연결 &rsquo;앱 Insights 데이터를 사용하여 작업 항목을 만들 수 있는 것이 좋지만 ALM 시스템에서 해당 항목을 보고 App Insights 작업 항목의 원본으로 빠르게 돌아가려면 어떻게&rsquo; 되나요? 이를 최대한 빠르고 쉽게 만들 수 있도록 가까운 장래에 작업 항목에 대한 링크를 추가할 계획입니다.</li>
   <li><em><strong>보다 유연한 구성</strong></em> &ndash; 현재 표준 구성은 사용자가 VSTS에서 프로젝트를 크게 수정/확장하지 않은 시나리오만 처리합니다. 현재 이러한 종류의 변경을&rsquo; 수행한 경우&rsquo; 고급 구성 모드로 전환해야 합니다. 앞으로는 가능한 경우 표준 구성에서 사용자가 변경할 수 있는 일반적인 사항(예: 추가 필드 필요 만들기, 새 필드 추가)을 처리하려고 합니다. 이를 위해서는 VSTS 팀의 친구로부터 일부 업데이트가 필요하지만, 이미 이러한 업데이트 중 일부를 작업 중입니다. &rsquo;사용할 수 있게 되면 표준 구성을 보다 유연하게 만들기 시작합니다. 그 동안(그리고 향후) 언제든지 고급 구성을 사용하여 제한 사항을 극복할 수 있습니다.</li>
   <li><em><strong>여러 프로필</strong></em> &ndash; 단일 구성을 설정한다는 것은 사용자가 일반적으로 작업 항목을 만드는 여러 가지 방법이 있는 상점에서 애플리케이션 Insights 작업 항목을 만드는 사람들이 값을 자주 재정의해야 한다는 것을 의미합니다. 특정 프로필을 사용하여 작업 항목을 만들 때 드롭다운 목록에서 간단히 선택할 수 있도록 각각에 대해 지정된 표준 값을 사용하여 사용자에게 1:n 프로필을 설정할 수 있는 기능을 제공할 계획입니다.</li>
   <li>작업 항목 &ndash; <em><strong>에 대한 추가 만들기 원본</strong></em> 작업 항목을 만드는 것이 적합한 애플리케이션 Insights 다른 위치를 계속 조사하고 피드백을 받을 것입니다.</li>
   <li><em><strong>작업 항목</strong></em> &ndash; 자동 만들기 조건에 따라 작업 항목을 만들려는 시나리오를 상상할 수 있습니다(그리고&rsquo; 여러분도 할 수 있습니다). 이것은 확실히 레이더에, 하지만 우리는 슈퍼 시끄러운 또는 가출 작업 항목 생성의 가능성을 제한 하기 위해이 몇 가지 디자인 시간을 보내고 있다. 이 기능은 강력하고 편리한 기능이라고 생각하지만 ALM 시스템을 최대한 스팸 처리할 수 있는 가능성을 줄이려고 합니다.</li>
   <li><em><strong>다른 ALM 시스템</strong></em> &ndash; 지원 이봐, 우리는 VSTS는 멋진 제품이라고 생각하지만, 우리는 많은 사용자가 자신의 ALM에 대한 다른 제품을 사용할 수 있음을 인식하고, 우리는 그들이있는 사람들을 만나고 싶습니다. 따라서 인기 있는 ALM 제품의 추가 1계층 통합을 위해 노력하고 있습니다. 또한 최종 사용자가 애플리케이션 Insights 거의 모든 ALM 시스템에 연결할 수 있도록 순수 사용자 지정 구성 선택(VSTS에 대한 고급 구성과 유사)을 제공할 계획입니다.</li>
  </ul>


  <p>파이프에도 다른 것들이 있지만, 당신이 볼 수 있듯이, 이것은 단기적으로 작업 할 것들의 꽤 중요한 목록입니다. 이러한 기능이 진화함에 따라 Well&rsquo;을 계속 업데이트하고 현재 기능이 어떻게 작동하는지, 그리고 이 기능 집합을 개선해야 할 수 있는 다른 제안 사항을 알려주세요. 애플리케이션 Insights 원격 분석을 일상적인 워크플로에 통합하는 데 도움이 되는 좋은 시작이 되기를 바라며, 계속해서 환경을 개선하기 위해 노력할 것입니다.</p>


  <p>건배</p>


  <p>Mike</p>


  <p>_____________________________________</p>


  <p>우리는 곧 당신을 위해 더 오고있다, 그래서 새로운 발표에 대한 Azure 블로그에 여기에 내 게시물에 눈을 유지하시기 바랍니다!</p>


  <p>언제나처럼 <a href="https://visualstudio.uservoice.com/forums/357324-application-insights">애플리케이션 Insights 사용자 의견 페이지에서</a> 새로운 기능 또는 향상된 기능에 대한 아이디어를 공유하고, 질문이 있으면 <a href="https://social.msdn.microsoft.com/Forums/vstudio/en-US/home?forum=ApplicationInsights"><u>애플리케이션 Insights 포럼</u></a>을 방문하세요.</p>
