### YamlMime:Yaml
ms.openlocfilehash: 9382462b553d9e634691cc08a89d60955c326c71
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139907926"
Slug: application-insights-performance-improvements-and-service-updates
Title: 애플리케이션 Insights 대한 성능 향상 및 서비스 업데이트
Summary: Visual Studio 애플리케이션 Insights 성능 및 안정성을 개선하기 위해 개발자가 서비스를 사용하는 방법을 기반으로 몇 가지 변경 작업을 수행하고 있습니다.
Content: >-
  <p>Visual Studio <a href="https://azure.microsoft.com/en-us/services/application-insights/">애플리케이션 Insights</a> 성능 및 안정성을 개선하기 위해 몇 가지 변경을 할 예정입니다. 메트릭 탐색기에서 차트를 분할하는 데 사용할 수 있는 차원 집합을 다시 통합하고, 거의 사용되지 않는 메트릭과 속성을 제거하고, 집계된 메트릭의 보존 기간을 줄일&#39;있습니다.</p>


  <p>지난 몇 달 동안 개발자가 애플리케이션 Insights 사용하는 방법을 검토했으며, Application Insights 자체적으로 수집한 성능, 진단 및 사용량 현황 데이터를 기반으로 <a href="https://azure.microsoft.com/en-us/blog/application-insights-temporary-limitations-and-performance-improvements/">서비스를 지속적으로 개선하고</a> 있습니다. Weve&rsquo;는 이미 UI 성능, 데이터 새로 고침 및 서비스 가용성을 크게 개선했으며 환경을 더 빠르고 원활하게 만들기 위해 최선을 다하고 있습니다.</p>


  <p>2016년 3월 16일 수요일, 애플리케이션 Insights 기대할 수 있는 강력한 진단 환경을 지속적으로 제공하면서 서비스 성능 및 안정성을 더욱 개선하기 위해 변경합니다. Were&rsquo;는 또한 몇 가지 멋진 새로운 것 들에 작업, 브라이언 해리 그의 <a href="https://blogs.msdn.microsoft.com/bharry/2016/02/06/a-bit-more-on-the-feb-3-and-4-incidents/">최근 블로그 게시물에</a> 언급 하는 일부, 그래서 뿐만 아니라 이러한 발표에 대 한 조정 유지!</p>


  <h2>그룹화 메트릭에 대한 통합 차원</h2>


  <p>애플리케이션 Insights 처음 설계했을 때 메트릭에 대한 비전은 매우 광범위한 차원으로 조각화하고 주사위를 만들 수 있어야 한다는 것이었습니다. 그러나 우리 모두가 경험을 얻었을 때, 이러한 조합의 꽤 많은 자주 사용되지 않는 것으로 나타났습니다. 이렇게 많은 집계 메트릭 조합을 사용하면 거의 모든 데이터가 사용되지 않고 전체 성능에 영향을 주는 엄청난 양의 데이터를 저장하는 것이 문제가 발생합니다.</p>


  <p>애플리케이션 Insights 애플리케이션에서 원격 분석을 탐색하는 두 가지 방법을 제공합니다.</p>


  <ul>
   <li><a href="https://azure.microsoft.com/documentation/articles/app-insights-diagnostic-search/">진단 검색</a>: 관련된 특정 이벤트, 예외 및 원격 분석을 탐색할 수 있는 강력한 진단 도구입니다.</li>
   <li><a href="https://azure.microsoft.com/documentation/articles/app-insights-metrics-explorer/">메트릭 탐색기</a>: 필터링하고 분할할 수 있는 집계된 데이터의 시간 차트를 생성합니다.</li>
  </ul>


  <p>처리 성능을 개선하고 그룹화할 차원을 선택하는 사용자 환경을 간소화하기 위해 기본적으로 사용 가능한 차원 목록을 통합합니다. 앱에서 서비스로 전송되는 데이터는 변경되지 않습니다. 추가&rsquo; 처리를 위해 <a href="https://powerbi.microsoft.com/documentation/powerbi-content-pack-application-insights/">Azure Storage 또는 Power BI</a> 모든 원격 분석을 <a href="https://azure.microsoft.com/documentation/articles/app-insights-export-telemetry/">지속적으로 내보내</a>는 것 외에도 현재 수행하는 모든 진단 검색을 수행할 수 있습니다.</p>


  <p>실제로 메트릭 탐색기&rsquo;에서 <a href="https://azure.microsoft.com/documentation/articles/app-insights-metrics-explorer/#editing-charts-and-grids">차트를 만들거나 사용자 지정</a>하려는 경우 선택할 메트릭 목록이 훨씬 더 간단합니다. 차트&rsquo;를 분할하려는 경우 <a href="https://azure.microsoft.com/documentation/articles/app-insights-metrics-explorer/#segment-your-data">그룹화</a> 메뉴에도 더 클리너 목록이 표시됩니다.</p>


  <p>즐겨 찾는 메트릭 또는 차원을 잘라내면 어떻게 될까요? 글쎄, 해결 방법이 있습니다. 사용자 지정 계측을 활용하고 메트릭을 매개 변수로 사용하여 고유한 <a href="https://azure.microsoft.com/documentation/articles/app-insights-api-custom-events-metrics/#track-metric">TrackMetric()</a> 호출 또는 <a href="https://azure.microsoft.com/documentation/articles/app-insights-api-custom-events-metrics/#properties">TrackEvent()</a> 를 보낼 수 있습니다. SDK 웹 모듈에서 기본적으로 전송되는 모든 메트릭에 대해 필요한 경우 <a href="https://azure.microsoft.com/documentation/articles/app-insights-api-filtering-sampling/#filtering">원격 분석 프로세서를 작성</a> 하여 생성되는 메트릭을 가로채고 메트릭 값을 사용자 지정 호출에 복사할 수 있습니다.</p>


  <p>우리가 말했듯이, 이것은 원시 원격 분석 또는 내보낸 원격 분석에 영향을 미치지 않습니다&rsquo;. 예를 들어 Power BI 또는 다른 도구를 사용하여 데이터를 표시하는 경우&rsquo; 변경 내용이 영향을 미치지 않습니다&rsquo;. 앞으로&rsquo; 원시 원격 분석을 통해 집계를 수행할 수 있는 기능을 갖춘 보다 강력한 검색 솔루션을 계획해야 합니다. 기대해 주세요.</p>


  <h2>통합 사용 메트릭</h2>


  <p>많은 고객이 애플리케이션 Insights 사용하여 실제 사용자 영향에 따라 사용자 및 세션 메트릭 및 심사 문제를 사용하여 애플리케이션의 사용을 모니터링해 왔습니다. 우리는이 경험을 더 나은 만들기 위해 강력한 기능 세트에 노력하고 있습니다! 지금은 핵심 진단 환경을 최적화하고 성능을 향상시키기 위해 세션당 이벤트, 세션당 예외, 세션당 페이지 수, 세션 간 시간, 세션 간 시간(인증된 사용자) 및 세션 기간 등 거의 사용되지 않는 메트릭 및 속성 중 일부를 제거합니다.</p>


  <p>이러한 메트릭 또는 속성을 사용하는 경우&rsquo; 즐겨찾는 도구를 사용하여 <a href="https://azure.microsoft.com/documentation/articles/app-insights-export-telemetry/">내보낸 데이터</a> 에서 해당 메트릭을 계산할 수 있습니다.</p>


  <h2>집계된 메트릭에 대한 데이터 보존 감소</h2>


  <p>현재 애플리케이션 Insights <a href="https://azure.microsoft.com/pricing/details/application-insights/">가격 책정 계획에</a> 따라 13개월 이상 시간당 수준에서 집계된 메트릭을 유지합니다. 사용량 원격 분석을 진행하는 동안 대부분의 사용자 지정 쿼리가 30일 미만이며 절반 이상이 24시간 미만이라는 것을 발견했습니다. 서비스 안정성을 크게 향상시키고 최적화된 데이터 성능을&rsquo; 제공하기 위해 집계된 메트릭의 보존 기간을 현재 수준에서 90일(모든 가격 책정 계획의 경우)으로 변경해야 합니다.</p>


  <p>애플리케이션 Insights 주로 웹앱 및 서비스에서 문제를 검색, 심사 및 진단하는 데 사용됩니다(디바이스 앱을 HockeyApp으로 전환하는 최근 <a href="https://azure.microsoft.com/en-us/blog/transitioning-mobile-apps-from-application-insights-to-hockeyapp/">공지</a> 참조). &rsquo;몇 달 전의 CPU 사용률 또는 예외 비율이 현재 배포 및 문제에 큰 의미가 있는 경우는 드뭅니다. 새 시간 범위는 모든 쿼리&nbsp; 의 99.9% 이상을 나타내므로 이러한 시간 간격으로 쿼리를 최적화하는 것이 장기 보존 동작을 개선하는 것보다 더 유용할 것이라고 생각합니다. 다시 말하지만, 몇 가지 메트릭 데이터를 장기간 유지하는 것이 주요 시나리오인 경우 <a href="https://azure.microsoft.com/documentation/articles/app-insights-metrics-explorer/">Excel 메트릭 탐색기에서 데이터를</a> 계속 가져오거나 <a href="https://azure.microsoft.com/documentation/articles/app-insights-export-telemetry/">연속 데이터 내보내기를</a> 사용할 수 있습니다.</p>


  <h2>검색 쿼리 기간 단축</h2>


  <p>마지막으로 <a href="https://azure.microsoft.com/en-us/blog/application-insights-temporary-limitations-and-performance-improvements-update/">지난 12월</a>&rsquo; 블로그 게시물에서 설명한 대로 쿼리 성능 및 전반적인 시스템 안정성을 개선하기 위해 서비스에서 데이터를 관리하는 방법을 변경했습니다. 이 변경을 사용하도록 설정하기 위해 <a href="https://azure.microsoft.com/documentation/articles/app-insights-diagnostic-search/">검색 쿼리</a>를 수행할 수 있는 기간을 7일로 <a href="https://azure.microsoft.com/en-us/blog/application-insights-temporary-limitations-and-performance-improvements/">제한</a>했습니다. 위에서&rsquo; 설명한 것처럼 더 긴 기간 동안 원시 데이터를 검색하는 데 도움이 되는 보다 강력한 검색 솔루션을 계획합니다.</p>


  <p>그 동안 표준 및 Premium 고객은 <a href="https://azure.microsoft.com/documentation/articles/app-insights-export-telemetry/">연속 내보내</a>기를 사용하여 7일이 지난 데이터에 계속 액세스할 수 있습니다. <a href="https://azure.microsoft.com/documentation/articles/app-insights-metrics-explorer/">메트릭 탐색기는</a> 7일 이상 표준 및 사용자 지정 속성을 기준으로 필터링하고 그룹화할 수 있는 기능을 포함하여 자세한 메트릭 데이터를 계속 제공합니다.</p>


  <h2>피드백</h2>


  <p>Microsoft는 사용자와 같은 개발자가 애플리케이션 Insights 사용하는 방법에 대해 많이 배우고 있습니다. Microsoft는 여러분의 피드백을 소중히 여기며, 문제를 그 어느 때보다 빠르게 해결할 수 있도록 계속 개선하고자 합니다. UserVoice 및 <a href="https://social.msdn.microsoft.com/Forums/en-US/home?forum=ApplicationInsights">MSDN</a> 포럼에서 제공되는 피드백을 유지하고 <a href="https://build.microsoft.com/">빌드 2016</a>에서 발표될 이러한 새로운 기능을 확인하세요.</p>
