### YamlMime:Yaml
ms.openlocfilehash: deddc8d3071957ff8d4ec41e53e34cdb7ebd4258
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139897484"
Slug: application-consistent-backup-for-linux-vms-using-azure-backup-is-generally-available
Title: Azure Backup을 사용하는 Linux VM에 대한 애플리케이션 일치 백업은 일반적으로 사용할 수 있습니다.
Summary: Azure Backup을 사용하여 Azure에서 실행되는 Linux VM의 애플리케이션 일치 백업의 GA(일반 공급)를 발표하게 되어 기쁩니다. 작년에 이 기능과 고객에 대한 미리 보기를 진행했습니다...
Content: >-
  <p>Azure Backup을 사용하여 Azure에서 실행되는 Linux VM에 대한 애플리케이션 일치 백업의 GA(일반 공급)를 발표하게 되어 기쁩니다. 작년에 이 기능의 <a href="https://azure.microsoft.com/en-in/blog/announcing-application-consistent-backup-for-linux-vms-using-azure-backup/">미리 보기를</a> 수행했으며, 고객은 이미 Oracle, MySQL, Mongo DB, SAP HANA 및 PostGreSQL과 같은 다양한 애플리케이션에 이 프레임워크를 사용하고 있습니다.</p>


  <h2>애플리케이션 일치 백업이란?</h2>


  <p>애플리케이션 일치 백업은 백업된 데이터가 트랜잭션적으로 일관되고 애플리케이션이 VM 복원 후 부팅되도록 합니다. 트랜잭션 일관성을 보장하려면 애플리케이션을 정지해야 하며 VM 스냅샷을 만들 때 완료되지 않은 트랜잭션이 없어야 합니다.</p>


  <p>Windows 애플리케이션 일치 VM 백업을 보장하기 위해 VSS(볼륨 스냅샷 서비스) 프레임워크를 가지고 있지만 Linux에 대한 일반 프레임워크는 없습니다. Azure Linux VM을 더 많이 채택하면서 Azure VM 내에서 실행되는 중요한 엔터프라이즈 애플리케이션을 백업해야 하는 수요가 증가하고 있습니다. Linux 배포판에서 실행되는 Linux 애플리케이션에 대한 애플리케이션 일치 VM 백업을 보장하기 위한 VSS와 유사한 일반 프레임워크를 도입했습니다. 이 프레임워크를 사용하면 VM 백업 프로세스의 일부로 사용자 지정 사전 및 사후 스크립트를 유연하게 실행할 수 있습니다. 이러한 스크립트는 애플리케이션 일관성을 보장하는 VM 스냅샷을 만드는 동안 애플리케이션 IO를 정지하는 데 사용할 수 있습니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/4c54e4aa-8e4f-4d31-8ca0-48adaa2e71cd.png"><img alt="f4bad234-e373-48e9-812a-46e9f90aa79e" border="0" height="490" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/6503c117-2250-47b1-b078-aa3c8862c35a.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="f4bad234-e373-48e9-812a-46e9f90aa79e" width="886"></a></p>


  <p>실제로 프레임워크는 VM 스냅샷의 일부로 네이티브 백업 API를 호출하여 애플리케이션 네이티브 백업을 수행하는 데 사용할 수 있으므로 더 강력합니다. Azure Backup은 VM 손상, VM 삭제 또는 재해 복구 시나리오로부터 안전하게 보호되도록 이 데이터를 오프사이트 복구 서비스 자격 증명 모음으로 이동합니다. 이 모든 작업은 VM을 종료할 필요 없이 수행합니다.</p>


  <h2>주요 특징</h2>


  <ul>
   <li><strong>애플리케이션 데이터를 쉽게 테스트하고 복원합니다 </strong>. 이제 iSCSI를 사용하여 복구 지점에서 직접 <a href="https://azure.microsoft.com/en-in/blog/instant-file-recovery-from-azure-vm-backups-is-now-generally-available/">애플리케이션을 탑재</a> 할 수 있습니다. 이렇게 하면 백업 데이터를 복사하지 않고 복구 지점의 유효성을 신속하게 검사할 수 있습니다. 그런 다음 전체 VM을 복원할 필요 없이 특정 애플리케이션 파일을 복구할 수 있습니다. 예를 들어 MySQL을 실행하는 Azure Linux VM의 백업이 있는 경우 클라우드 복구 지점에서 .sql 데이터 덤프를 탑재하고, MySQL 데이터베이스를 이 파일에 직접 연결하고, 전체 데이터 덤프를 다운로드하지 않고도 백업의 유효성을 신속하게 검사하거나 테이블과 같은 개별 항목을 검색할 수 있습니다.</li>
   <li><strong>향상된 모니터링:</strong> 이 릴리스에서는 문제를 식별하고 쉽게 해결할 수 있도록 모든 프레임워크 관련 오류가 백업 작업에 표시됩니다. 예를 들어 스크립트 실패&rdquo; 시 계속을 구성&ldquo;한 경우 백업은 파일 시스템 또는 크래시 일관성으로 진행됩니다. 그러나 이제 백업 작업에 경고&rdquo;와 함께 완료됨이 표시&ldquo;되고 스크립트 오류를 해결하기 위한 자세한 오류 메시지 및 권장 작업을 제공합니다.</li>
   <li><strong>애플리케이션 및 배포에 구애받지 않습니다. </strong> 프레임워크는 Linux 배포판 및 버전에 구애받지 않으며 게스트 애플리케이션에 애플리케이션 IO를 일시 중지하고 다시 시작하는 API가 있는 한 <a href="https://docs.microsoft.com/en-us/azure/backup/backup-azure-arm-vms-prepare#supported-operating-systems-for-backup">지원되는 모든 Linux 배포판</a> 에서 원활하게 작동합니다.</li>
   <li><strong>GitHub 샘플 스크립트:</strong> 인기 있는 Linux 애플리케이션에 대한 <a href="https://github.com/MicrosoftAzureBackup">GitHub</a> 오픈 소스 스크립트를 제공하기 위해 파트너 및 ISV와 협력하고 있습니다. 이 릴리스를 기준으로 MySQL, Oracle 및 Cach&eacute;에 대한 이러한 항목이 준비되었습니다.</li>
   <li><strong>Azure CL을 사용하여 대규모 자동화: </strong> 이제 <a href="https://azure.microsoft.com/en-in/blog/manage-your-azure-vm-backups-with-azure-cli-2-0-preview/">Azure CLI를 사용하여 대규모로 Azure Backup 작업을 구성, 관리 및 자동화할</a> 수 있습니다. 대부분의 일반적인 작업에 대한 스마트 기본값, 탭 완성 및 파이프 가능 출력과 같은 CLI 기능을 활용하여 VM 백업 및 복구 작업을 관리하기만 하면 됩니다. 백업 및 복원 구성 외에도 명령 출력을 쿼리하여 다른 관리 작업을 자동화할 수도 있습니다. 예를 들어 백업 상태 정보를 프로그래밍 방식으로 검색할 수 있으며 상태에 따라 후속 작업을 시작할 수 있습니다.</li>
  </ul>


  <h2>시작</h2>


  <p>아래 비디오에서는 사전 스크립트 및 사후 스크립트를 실행하기 위해 프레임워크를 구성하는 방법에 대한 다양한 단계를 안내합니다. 자세한 내용은 <a href="https://docs.microsoft.com/azure/backup/backup-azure-linux-app-consistent">애플리케이션 일치 Linux VM 백업을 구성하는 단계를</a> 참조하세요.</p>


  <p align="center"><iframe allowfullscreen="" frameborder="0" height="540" src="https://channel9.msdn.com/Series/Azure-Backup/Configure-application-consistent-backup-for-Linux-VMs-using-Azure-Backup/player" width="960"></iframe></p>


  <p align="left">이제 데이터를 복사하고 백업할 필요 없이 VM 백업에서 직접 애플리케이션을 탑재하여 데이터의 유효성을 검사할 수 있습니다. 자세한 내용은 아래 비디오를 시청하세요.</p>


  <p style="text-align: center;"><iframe allowfullscreen="" frameborder="0" height="540" scrolling="no" src="https://channel9.msdn.com/posts/Restore-application-files-from-application-consistent-Linux-VM-backup/player" width="960"></iframe></p>


  <h2>고객 성공 사례</h2>


  <p>OU(<a href="https://www.open.ac.uk/">Open University)는</a> Azure Linux 일관성 백업 솔루션을 활용하여 Azure에서 곧 라이브로 전환되는 Azure 기반 가상 학습 환경 집합에 대해 Linux 데이터베이스 서버의 일관된 이미지 기반 백업을 허용했습니다.</p>


  <p>OU는 가상화를 활용하는 밀턴 케인즈 영국의 온-프레미스 데이터 센터와 같은 여러 가상 학습 환경을 운영하고 있으며, 이제 Azure에 새로운 가상 학습 환경을 배포하기 시작했습니다. Azure Backup 및 Azure Linux 일치 백업 솔루션을 활용하여 Linux 데이터베이스 백업에 대한 일관된 접근 방식을 통해 Azure에서 호스팅되는 새 학습 환경의 배포, 백업 및 복구를 간소화할 수 있습니다.</p>


  <blockquote>

  <p><em>&ldquo;사전 동결 및 사후 동결 프로세스는 온-프레미스 가상 머신 이미지 수준 백업 솔루션을 사용하여 Linux 데이터베이스 서버에서 사용하는 프로세스와 거의 동일합니다. 이렇게 하면 수정 없이 기존 패키지된 사전 동결 및 동결 후 스크립트를 활용할 수 있습니다. 이렇게 하면 Azure 가상 학습 환경의 배포가 훨씬 간단해졌으며 데이터베이스 백업 일관성을 유지하면서 Azure 머신 백업을 사용할 수 있습니다&rdquo;.</em></p>

  </blockquote>


  <p align="right">- Gareth Robins, Systems 프로그래머, IT 서비스 &amp; 지원, 오픈 유니버시티</p>


  <p>Microsoft 파트너 인 <a href="https://intercept.nl/">Intercept</a>는 Azure Linux VM에서 실행되는 Oracle 데이터베이스에 대한 애플리케이션 일치 백업을 구현했습니다. 다음은 기능에 대한 인터셉트&rsquo; 피드백입니다.</p>


  <blockquote>

  <p><i>&ldquo;고객 중 한 명이 Azure VM&rsquo; 내의 Oracle 데이터베이스를 일관되게 백업할 수 있도록 Linux 기능에 대한 애플리케이션 일치 백업을 구현했습니다. 고객은 백업 도구를 간단하고 관리 용이성을 위해 Azure 네이티브 솔루션을 선호하며 모든 Azure 리소스에 대해 균일한 백업 환경을 갖기를 원합니다. Linux에 대한 Azure 애플리케이션 일치 백업을 통해 이를 가능하게 합니다.&rdquo;</i></p>

  </blockquote>


  <p align="right">- Remco Vrielink, Intercept</p>


  <p><a href="https://www.impactinggroup.com/" target="_blank">SA에 영향을 미치는</a> 경우 MySQL 및 MongoDB에 대해 이 솔루션을 시도했으며 전체 VM이 아닌 특정 애플리케이션 파일만 복원해야 하므로 복원 시간이 크게 향상되었습니다(최대 70%). 다음은 SA에 영향을 미치는 피드백입니다.</p>


  <blockquote>

  <p><em>&ldquo;사용 가능한 설명서 및 지침만 따라야 하므로 이 기능을 활성화하기가 쉬웠습니다. 그들은 간단하고 명시적이며 이해하기 쉬웠습니다. </em><em>이 기능의 긍정적인 점은 복원할 수 있을 때까지 시작하는 순간부터 백업 시간을 줄였다는 점입니다. 백업 복구는 이전 프로세스에 비해 약 70% 더 빠르게 복구되었으며 4시간에서 약 20분으로 늘어났습니다.&rdquo;</em></p>

  </blockquote>


  <h2>Oracle DB에 대한 샘플 스크립트</h2>


  <p>많은 고객이 MySQL 및 Oracle에 대한 솔루션을 사용하는 것을 보았고, MySQL 오픈 소스 스크립트는 이미 GitHub 업로드되었지만 이제 <a href="https://github.com/MicrosoftAzureBackup/Oracle">샘플 Oracle 스크립트를 추가했습니다</a>. 이를 참조로 사용하여 고유한 스크립트를 만들고 이 프레임워크의 기능을 활용할 수 있습니다.</p>


  <h2>오픈 소스 커뮤니티 기여 추구</h2>


  <p>이 프레임워크를 일반화하고 Windows VSS와 같은 다양한 애플리케이션을 지원하기 위해 개발자, ISV, 기술 애호가 및 파트너를 호출하여 <a href="https://github.com/MicrosoftAzureBackup">GitHub 리포지토리</a>에 오픈 소스 스크립트에 기여합니다. 스크립트는 모든 사용자가 직접 사용하거나 요구 사항에 따라 사용자 지정할 수 있습니다. 기여에 관심이 있는 경우 전자 메일을 <a href="mailto:linuxazurebackupteam@service.microsoft.com">linuxazurebackupteam@service.microsoft.com</a> 보내주시기 바랍니다. 당사는 귀하와 협력하여 GitHub 게시하고, 사용 지침을 설명하고, 귀하의 기여에 대한 승인을 받을 수 있도록 할 것입니다.</p>


  <h2>관련 링크 및 추가 콘텐츠</h2>


  <ul>
   <li>이 기능에 대한 자세한 내용을 원하십니까? <a href="https://docs.microsoft.com/azure/backup/backup-azure-linux-app-consistent">Azure 애플리케이션 일치 Linux VM 백업 설명서를 확인하세요</a>.</li>
   <li>도움이 필요하신가요? <a href="https://social.msdn.microsoft.com/forums/azure/en-US/home?forum=windowsazureonlinebackup">지원을 위해 Azure Backup 포럼</a>에 문의하거나 <a href="https://docs.microsoft.com/azure/backup/">Azure Backup 설명서를</a> 찾아보세요.</li>
   <li>새 아이디어를 제공하고 기존 아이디어를 투표하여 <a href="https://feedback.azure.com/forums/258995-azure-backup">Azure Backup을 개선하는</a> 방법을 알려주세요.</li>
   <li>최신 뉴스 및 업데이트에 대한 트위터에 <a href="https://twitter.com/azurebackup">@AzureBackup</a> 우리를 따르십시오.</li>
   <li><a href="https://azure.microsoft.com/en-us/services/backup/">Azure Backup</a>을 새로 사용하려면 <a href="https://azure.microsoft.com/en-us/pricing/free-trial/">무료 Azure 평가판 구독</a>에 등록하세요.</li>
  </ul>
