### YamlMime:Yaml
ms.openlocfilehash: 7219c1e6bb386a8e27ae819e698b3a79be011dfa
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139907934"
Slug: application-insights-improvements-for-java-and-nodejs
Title: Java 및 Node.js 대한 애플리케이션 Insights 개선 사항
Summary: 애플리케이션 Insights Java 및 Node.js 사용하는 팀을 위한 일류 모니터링 환경이 있습니다.
Content: >-
  <p>애플리케이션 Insights Java 및 Node.js 지원한다는 사실을 알고 계셨나요? Microsoft의 <a href="https://www.microsoft.com/en-us/about" target="_blank">사명은 전 세계의 모든 사람과 조직이 더 많은 성과를 거둘 수 있도록 하는 것이기</a> 때문에&#39;. <a href="https://azure.microsoft.com/services/application-insights/" target="_blank">Azure Application Insights</a> 팀의 모든 사용자는 사용하는 기술 스택에 관계없이 모든 개발자, DevOps 실무자 및 사이트 안정성 엔지니어를 의미합니다.</p>


  <p>이러한&#39;Java 및 Node.js 팀이 Azure 및 온-프레미스 환경 모두에서 일류 모니터링 환경을 제공할 수 있도록 1년 넘게 작업한&#39;이유입니다. 그래서 오늘&#39;저는 우리 팀이 이미 달성한 몇 가지 성과를 여러분과 공유하게 되어 자랑스럽고,&#39;앞으로 몇 달 동안 계속 출시될 기능과 개선 사항에 대해 매우 기쁘게 생각합니다. 하지만 먼저&#39;Java에 대해 이야기해 보겠습니다.</p>


  <h2>Java용 Application Insights</h2>


  <div><img alt="I Code Java" border="0" height="480" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/0dc8fd7c-9a57-4536-a3c3-444a9fe2268a.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="I Code Java" width="392"></div>


  <p>Java SDK용 애플리케이션 Insights 두 번째 버전은 올해 초 <a href="https://mvnrepository.com/artifact/com.microsoft.azure/applicationinsights-web" target="_blank">Maven</a>/Gradle 및 <a href="https://github.com/Microsoft/ApplicationInsights-Java/releases" target="_blank">GitHub</a> 릴리스되었으며, 팀은 그 이후로 개선 사항을 계속 개선해 왔으며, 가장 최근에는 <a href="https://github.com/Microsoft/ApplicationInsights-Java/releases/tag/2.1.2" target="_blank">버전 2.1.2</a>를 사용했습니다. 수많은 버그 수정 외에도 팀은 고정 속도 샘플링, Log4J에 대한 향상된 지원 및 구성 요소 간 원격 분석 상관 관계에 대한 지원을 추가했습니다. 또한 개발자가 특별한 방식으로 애플리케이션을 계측할 필요가 없도록 <a href="https://docs.microsoft.com/en-us/azure/application-insights/auto-collect-dependencies#java" target="_blank">가장 인기 있는 앱 프레임워크, 스토리지 클라이언트 및 통신 라이브러리</a> 의 사용을 자동으로 검색합니다.</p>


  <div><img alt="Spring by Pivotal logo" border="0" height="156" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/1d42bca1-90a4-470e-a247-3a0607945308.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="Spring by Pivotal 로고" width="480"></div>


  <p>Java 개발자는 Spring 프레임워크를 좋아하며 우리도 마찬가지입니다. 이 때문에 일반적으로 Spring의 전반적인 지원을 개선하는 데 시간을 할애하고 Spring 개발자가 애플리케이션&#39;Insights <a href="https://docs.microsoft.com/java/azure/spring-framework/configure-spring-boot-java-applicationinsights" target="_blank">빠르고 쉽게 구성할</a> 수 있도록 <a href="https://start.spring.io/" target="_blank">Spring Initializr 애플리케이션 부트스트랩 도구</a>와 호환되는 Spring Boot Starter를 게시했습니다. 우리의 사랑이 계속 성장함에 따라, 우리는 미래에 봄 팀에 대한 모니터링 경험을 개선하기 위해 계속 볼 것으로 기대합니다.</p>


  <p>마지막으로 Java<a href="https://docs.microsoft.com/en-us/azure/application-insights/app-insights-java-get-started" target="_blank">용 Application Insights 빠른 시작을</a> 확인하여 자세히 알아보세요.</p>


  <h2>Node.js용 Application Insights</h2>


  <div><br>

  <img alt="Node.js logo" border="0" height="295" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/1b566587-d6c1-4a1b-be8a-ec2e71d702f1.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="Node.js 로고" width="480"></div>


  <p>이제 Node.js. Node.js SDK용 애플리케이션 Insights 안정적인 버전은 현재 거의 1년 동안 <a href="https://www.npmjs.com/package/applicationinsights" target="_blank">npm</a> 및 <a href="https://github.com/Microsoft/ApplicationInsights-node.js/releases" target="_blank">GitHub</a> 사용할 수 있으며 계속 개선되고 있습니다. 가장 최근에는 개발자가 실수로 손상된 버전의 TLS 프로토콜을 사용하지 못하도록 보안을 강화하고, HTTP(S) 프록시에 대한 지원을 추가했으며, Java와 마찬가지로 수동 애플리케이션 계측의 필요성을 줄이기 위한 <a href="https://docs.microsoft.com/azure/application-insights/auto-collect-dependencies#nodejs" target="_blank">훌륭한 자동 수집기 컬렉션을</a> 제공합니다. 언제나처럼, <a href="https://docs.microsoft.com/en-us/azure/application-insights/app-insights-java-get-started" target="_blank">Node.js애플리케이션 Insights 대한 빠른 시작 </a> 은 더 많은 것을 찾을 수있는 좋은 장소입니다.</p>


  <h2>미래를 내다보며</h2>


  <p>언급했듯이, 최근에 우리가 성취한&#39;자랑스러워할 뿐만 아니라 미래가 어떻게 될지에 대해서도 흥분할&#39;있습니다. 메트릭에 대한 라이브러리의 단일 배포 및 최소한의 오버헤드로 분산 추적을 달성하는 &quot;것을 목표로 하는 오픈 소스 <a href="https://open.microsoft.com/2018/06/13/microsoft-joins-the-opencensus-project/">프로젝트인 OpenCensus 프로젝트에 참여할&#39;발표</a>했을 때 이미 힌트를 삭제했습니다.&quot; 더 많은 기여를 하고 추가 스택 및 기술에 대한 지원을 확장할 수 있습니다.</p>


  <p>기여에 대해 말하자면, 모든 애플리케이션 Insights SDK는 Java 및 Node.js 포함한 오픈 소스입니다. 팀은 <a href="https://github.com/Microsoft/ApplicationInsights-Java/issues/" target="_blank">문제</a> 및 끌어오기 요청을 통해 피드백을 듣는 것을 좋아하므로 자유롭게 우리와 함께 개발할 수 있습니다!</p>


  <p>마지막으로, 질문이나 의견이 있는 경우 아래의 의견에 그대로 두세요.</p>
