### YamlMime:Yaml
ms.openlocfilehash: 0c52196e7ebf8f5396509dca274921d27e4b7a61
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139903348"
Slug: application-insights-temporary-limitations-and-performance-improvements
Title: 애플리케이션 Insights - 일시적인 제한 사항 및 성능 향상
Summary: 지난 몇 개월 동안 Application Insights 성능 및 안정성을 향상하여 경험을 빠르고 안정적으로 만드는 것을 목표로 했습니다.
Content: >-
  <p>Weve&rsquo;는 지난 몇 개월 동안 <a href="https://azure.microsoft.com/services/application-insights/"><u>애플리케이션 Insights</u></a> 성능 및 안정성을 향상하여 경험을 빠르고 매우 안정적으로 만드는 것을 목표로 했습니다. &rsquo;Application Insights 아직 미리 보기 상태인 동안 거의 매일 개선됩니다. 리팩터링&rsquo;의 일환으로 일부 데이터를 이동하므로 약간의 제한을 적용해야 합니다.</p>


  <h1>검색 쿼리 기간의 임시 감소</h1>


  <h3>무슨 일이 일어날거야?</h3>


  <ul>
   <li>
   <p>2015년 10월 28일(태평양 표준시 수요일 오후)에 <a href="https://azure.microsoft.com/documentation/articles/app-insights-diagnostic-search/"><u>검색 쿼리</u></a>를 수행할 수 있는 기간을 일시적으로 줄입니다. 표준 또는 Premium 가격 책정 계층&rsquo;을 사용하는 경우에도&rsquo; 7일 이상 거슬러 올라가는 검색 쿼리를 수행할 수 없다는 것을 알 수 있습니다&rsquo;.</p>
   </li>
   <li>
   <p><a href="https://azure.microsoft.com/documentation/articles/app-insights-metrics-explorer/"><u>메트릭 탐색기는</u></a> <a href="https://azure.microsoft.com/pricing/details/application-insights/"><u>가격 책정 계획에</u></a> 따라 1분 단위까지 집계된 모든 데이터를 계속 제공합니다.</p>
   </li>
  </ul>


  <h3>그 이유는 무엇일까요?</h3>


  <ul>
   <li>
   <p>우리는 개선 프로그램의 계획 된 부분으로이 작업을 수행하고있다. 데이터 스토리지 접근 방식을 리팩터링하여 다양한 인덱스의 검색 및 메트릭 쿼리를 처리하여 성능을 크게 향상시키고 있습니다.</p>
   </li>
  </ul>


  <h3>일시적입니까?</h3>


  <ul>
   <li>
   <p><strong>예</strong>. 표준 데이터 보존 시간은 향후 몇 주 동안 복원될 예정입니다. &rsquo;쿼리 성능이 향상되는 것을 즉시 확인할 수 있습니다.</p>
   </li>
  </ul>


  <h1>지속적인 개선 사항</h1>


  <p>&rsquo;이 임시 조치로 인해 불편을 드려 죄송합니다. 이 변경은 지속적인 개선 프로그램의 일부입니다. 다음은 지난 몇 개월 동안의 성과 중 일부입니다.</p>


  <ul>
   <li>
   <p><strong>UI 성능: </strong> 페이지 및 쿼리 로드 속도가 두 배 빨라집니다. &rsquo;향상된 캐싱, 사전 인출, 데이터 볼륨의 직렬화/직렬화 제거, 코드 리팩터링, 쿼리 성능, 비동기 호출, UI 지역 배포 등이 향상되었습니다.</p>
   </li>
   <li>
   <p><strong>UI 안정성</strong>: 애플리케이션 Insights 구성 요소의 일부 부하로 인해 더욱 자신 있게 서비스에 의존할 수 있다고 믿는 중요한 안정성 개선이 이루어졌습니다.</p>
   </li>
   <li>
   <p><strong>데이터 확장성:</strong> 트래픽 증가는 최근 몇 달 동안 두 배로 증가하여 더 많은 용량이 필요했습니다. 추가 데이터 수집 끝점은 전 세계의 다양한 데이터 센터에 배포되었으며 미국 중남부에 추가 처리 데이터 센터가 추가되었습니다.</p>
   </li>
  </ul>


  <p>물론 Application&rsquo; Insights 사용하여 모든 문제를 감지, 심사 및 진단하고 지속적인 개선을 제공했습니다. 이러한 변경으로 애플리케이션 Insights 사용 환경이 훨씬 더 즐겁지만 여러분의 의견을 직접 듣고 싶습니다. 사용자 의견 및 <a href="https://social.msdn.microsoft.com/Forums/en-US/home?forum=ApplicationInsights"><u>포럼</u></a>에 대한 피드백, 제안 또는 질문을 제공하세요.</p>
