### YamlMime:Yaml
ms.openlocfilehash: a5a5f65243d412e7531c94ed6752219b304b1ecf
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139907922"
Slug: application-insights-pricing-effective-june-1
Title: 애플리케이션 Insights 가격 책정 6월 1일부터(업데이트됨)
Summary: Application Insights 공개 미리 보기의 일환으로 애플리케이션당 데이터 볼륨을 기반으로 하며 모든 개발 팀에 큰 가치를 제공하도록 설계된 새로운 클라우드 친화적인 가격 책정 모델을 출시합니다. 가격은 2015년 6월 1일부터 적용되며 공개 미리 보기에서 50% 할인됩니다.
Content: >-
  <p><a href="https://www.buildwindows.com/">Microsoft BUILD</a> 컨퍼런스와 <a href="https://azure.microsoft.com/blog/2015/04/29/announcing-application-insights-public-preview-2/">Merav Davidsons&rsquo;의 최근 블로그 게시물</a>에서 <a href="https://azure.microsoft.com/services/application-insights/">Visual Studio 애플리케이션 Insights</a> 공개 미리 보기에 대한 준비가 되었다고 발표했습니다. 애플리케이션 Insights&rsquo; 공개 미리 보기의 일환으로 애플리케이션당 데이터 볼륨을 기반으로 하며 모든 개발 팀에 큰 가치를 제공하도록 설계된 새로운 <a href="https://azure.microsoft.com/pricing/details/application-insights/">클라우드 친화적인 가격 책정 모델을</a> 시작합니다. 가격은 2015년 6월 1일부터 적용되며 공개 미리 보기에서&nbsp; 50% 할인됩니다. <strong>무료 계층</strong>에서는 데이터 볼륨 및 보존 기간에 대한 몇 가지 제한 사항이 있는 대부분의 기능을 얻을 수 있습니다. 애플리케이션이 더 많은 데이터 볼륨을 증가 및&nbsp; 생성&nbsp;하거나 더 풍부한 분석을 위해 더 오랜 기간 동안 데이터에 액세스하려는 경우 각 계층에 포함된 데이터 요소의 월별 할당량을 늘리고, 더 긴 기간 동안 데이터를 유지하고, <a href="https://azure.microsoft.com/documentation/articles/app-insights-export-telemetry/">연속 내보내기</a> 기능을 사용하도록 설정하는 <strong>표준</strong> 및 <strong>Premium</strong> 계층을 활용할 수 있습니다. 데이터 볼륨에 대한 요금을 지불합니다. 웹앱인 경우 배포된 서버&rsquo;의 개수는 중요하지 않습니다&rsquo;. 사용하지 않은&rsquo; 리소스에 대한 페널티 없이 동적으로 크기를 조정할 수 있습니다. 무료, 표준 및 Premium 계층 외에도 각 애플리케이션 Insights 리소스는<strong> 무료 30일 Premium 평가판</strong>에 사용할 수 있습니다. 여기에는 Premium 계층의 모든 기능이 있지만 월별 비용은 없으므로 전체 애플리케이션 Insights 환경을 얻고 특정 애플리케이션에 적합한 계층을 결정할 수 있습니다.</p>


  <p><a href="https://acom.azurecomcdn.net/80C57D/blogmedia/blogmedia/2015/05/21/Pricing-Blog-0-Pricing-Tiers.png"><img alt="Pricing Blog 0 - Pricing Tiers" class="alignnone size-medium wp-image-297371" height="369" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/Pricing-Blog-0-Pricing-Tiers-596x369.png" width="596"></a></p>


  <h2>애플리케이션 Insights 가격 관리</h2>


  <p>애플리케이션 Insights 리소스에 대한 가격 책정 계층을 선택하려면 리소스를 열고 설정 명령을 클릭한 다음 <strong>할당량 + 가격 책정</strong>&rdquo; 옵션을 선택합니다&ldquo;.</p>


  <p><a href="https://acom.azurecomcdn.net/80C57D/blogmedia/blogmedia/2015/05/21/Pricing-Blog-1-Settings-with-arrow.jpg"><img alt="Pricing Blog 1 - Settings (with arrow)" class="alignnone size-medium wp-image-297392" height="369" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/Pricing-Blog-1-Settings-with-arrow-593x369.jpg" width="593"></a></p>


  <p>그러면 <strong>할당량 + 가격 책정 구성</strong>&rdquo; 블레이드가 &ldquo; 열립니다.</p>


  <p><a href="https://acom.azurecomcdn.net/80C57D/blogmedia/blogmedia/2015/05/21/Pricing-Blog-2-Quota-and-pricing-config-blade.jpg"><img alt="Pricing Blog 2 - Quota and pricing config blade" class="alignnone size-medium wp-image-297421" height="369" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/Pricing-Blog-2-Quota-and-pricing-config-blade-357x369.jpg" width="357"></a></p>


  <p>블레이드를 시계 방향으로 작업하는 첫 번째 타일은 <strong>이번 달</strong>&rdquo; Data입니다&ldquo;. 이 값은 이번 달에 지금까지 사용된 현재 계층&rsquo; 할당량의 백분율을 보여 줍니다. 매월 첫째 날에 누적된 원격 분석 재설정 횟수입니다. (이 리소스&rsquo; 구독에 대한 청구 주기와 반드시 동일하지는 않습니다.) 이 개수에는 할당량이 없는 세션 원격 분석(예: 세션, 지리, 환경 및 디바이스 유형 데이터 수)을 제외한 애플리케이션 Insights 수집된 모든 데이터가 포함됩니다. 할당량에 계산되는 데이터 요소 유형은 다음과 같습니다.</p>


  <ol>
   <li><strong>요청</strong>: 관리되는 애플리케이션에서 수신하거나 TrackRequest API를 통해 전송된 모든 요청</li>
   <li><strong>예외</strong>: 처리되지 않은 예외/크래시가 수집되거나 TrackException API를 통해 전송된 각 예외</li>
   <li><strong>종속성</strong>: 관리되는 애플리케이션에서 원격 종속성에 대한 각 호출</li>
   <li><strong>페이지 보기</strong>: 웹 사이트, 모바일 애플리케이션에서 로드되거나 TrackPage API를 통해 전송된 각 페이지</li>
   <li><strong>성능 카운터</strong>: 수집된 성능 데이터의 각 인스턴스(기본 카운터 또는 <a href="https://blogs.msdn.com/b/visualstudioalm/archive/2015/04/01/application-insights-choose-your-own-performance-counters.aspx">사용자 지정 카운터</a>)</li>
   <li><strong>사용자 지정 이벤트</strong>: TrackEvent API를 통해 전송된 각 이벤트</li>
   <li><strong>사용자 지정</strong> 메트릭: TrackMetric API를 통해 전송된 각 메트릭</li>
   <li><strong>추적 로그</strong>: <a href="https://azure.microsoft.com/documentation/articles/app-insights-asp-net-trace-logs/">로깅 어댑터</a> 또는 TrackTrace API의 각 추적 항목</li>
   <li><strong>웹 테스트 데이터:</strong> 테스트의 성공/실패에 대한 웹 테스트에서 생성된 데이터</li>
  </ol>


  <p>웹 테스트에서 제출된 데이터는 곧 할당량에 대해서도 계산됩니다. 다음 타일에서는 선택한 가격 책정 계층에 포함된 할당량보다 높은 원격 분석 데이터 수집을 사용하도록 설정할지 여부를 구성할 수 있습니다. 이 옵션은 무료 계층에서 사용할 수 없습니다. 기본적으로 애플리케이션 Insights 리소스는 이 추가 원격 분석을 수집할 수 없으며 이는 명시적으로 옵트인 모델입니다. &ldquo; 다음은 <strong>가격 책정 계층</strong>&rdquo; 타일입니다. 이 옵션을 클릭하면 가격 책정 계층&rdquo; 선택 블레이드가 &ldquo;열립니다. 사용할 가격 책정 계층을 선택할 수 있습니다. 6월 1일 이후에 만든 애플리케이션 Insights 리소스는 모두 무료 계층에서 만들어지고 언제든지 표준, Premium 또는 30일 Premium 평가판 계층으로 이동하도록 선택할 수 있습니다. 언제든지 30일 Premium 평가판을 시작할 수 있지만, 시작되면 리소스는 30일 동안 이 계층에 유지됩니다. 평가판이 끝나면 리소스가 평가판을 시작하기 전에 있던 가격 책정 계층으로 되돌아갑니다. 평가판이 끝날 때 다른 가격 책정 계층으로 변경하려는 경우 이 블레이드를 사용하여 평가판 기간 동안 언제든지 해당 계층을 선택할 수 있습니다.</p>


  <p><a href="https://acom.azurecomcdn.net/80C57D/blogmedia/blogmedia/2015/05/27/Pricing-Blog-3-Pricing-tier-blade.jpg"><img alt="" class="alignnone wp-image-302581 size-medium" height="369" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/Pricing-Blog-3-Pricing-tier-blade-594x369.jpg" width="594"></a></p>


  <p>마지막으로 이 블레이드의 맨 아래 타일인 &ldquo;<strong>데이터 요소 볼륨</strong>&rdquo; 은 지난 30일 동안 이 애플리케이션에 대해 처리된 데이터 요소 수를 표시하므로 추세를 감시하고 데이터 볼륨에 가장 많이 기여하는 데이터 형식을 이해할 수 있습니다.</p>


  <p><a href="https://acom.azurecomcdn.net/80C57D/blogmedia/blogmedia/2015/05/21/Pricing-Blog-4-Data-volume.jpg"><img alt="Pricing Blog 4 - Data volume" class="alignnone size-medium wp-image-297481" height="369" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/Pricing-Blog-4-Data-volume-533x369.jpg" width="533"></a></p>


  <h2>6월 1일에 발생하는 작업</h2>


  <p>2015년 6월 1일에 애플리케이션 Insights 가격 책정을 켜면 모든 활성 애플리케이션 Insights 리소스를 <strong>30일 Premium 평가판</strong> 가격 책정 계층으로 이동합니다. 즉, 향후 30일 동안 가장 높은 수준의 애플리케이션 Insights&rsquo; 기능 및 데이터 볼륨 할당량을 얻게 되며 이 전환 중에 연속 내보내기를 사용하는 사용자의 영향을 받지 않도록 합니다. (위에서 설명한 대로 이 변경 후 생성된 애플리케이션 Insights 리소스는 모두 무료 가격 책정 계층에서 시작되며 30일 Premium 평가판을 사용하려는 경우 사용자에게 달려 있습니다.) 30일 평가판이 끝나면 모든 리소스가 기본적으로 무료 가격 책정 계층으로 되돌아갑니다. 연속 내보내기를 사용하는 경우 30일 평가판이 끝나기 전에 표준 또는 Premium 가격 책정 계층을 선택하여 중단 없는 내보내기 기능을 확인해야 합니다. 물론 우리는&rsquo;뿐만 아니라 이메일로 당신을 생각 나게합니다.</p>


  <h2>요약</h2>


  <p>애플리케이션 Insights&rsquo; <a href="https://azure.microsoft.com/pricing/details/application-insights/">클라우드 친화적인 가격 책정 모델의</a> 구현은 2015년 6월 1일부터 시작됩니다. 이 모델은 애플리케이션당 데이터 볼륨을 기반으로 하며 모든 개발 팀에게 무료로 큰 가치를 제공하도록 설계되었습니다. 애플리케이션 Insights 사용하여 모니터링되는 모든 애플리케이션이 현재 애플리케이션 Insights 동일한 환경을 제공하는 이 시점에서 30일 Premium 평가판에 배치되므로 즉각적인 조치가 필요하지 않습니다. 그러나 30일 평가판 중에는 원격 분석 볼륨 및 필요한 기능(데이터 보존 및 연속 내보내기 길이)에 따라 애플리케이션에 적합한 가격 책정 계층을 고려하고 평가판이 끝난 후 애플리케이션에 사용할 계층으로 선택해야 합니다.</p>


  <h2>업데이트(6월 27일)</h2>


  <p>Premium 제품을 평가하는 데 더 많은 시간을 할애하기 위해 <strong>프리미엄 평가판을 연장하고</strong> 있습니다. 6월 17일 이전에 Premium 평가판을 사용하도록 설정한 모든 리소스의 경우 평가판이 7월 17일까지 자동으로 연장됩니다. 모든 애플리케이션 Insights 리소스에 &ndash; 자동으로 적용되는 작업이 필요하지 않습니다. 적절한 <a href="https://azure.microsoft.com/pricing/details/application-insights/">애플리케이션 Insights 가격 책정 계층</a>을 선택하는 데 도움이 되도록 현재 데이터 볼륨을 모니터링하는 것이 좋습니다. 또한 표준 및 Premium 계층에서만 사용할 수 있는 <a href="https://azure.microsoft.com/documentation/articles/app-insights-export-telemetry/">연속 내보내</a>기와 같은 기능을 사용해 보세요. &ldquo;가격 책정 계획에 대한 자세한 내용은 각 Applications Insight 개요 블레이드의 설정 옵션에서 평가할 수 있는 할당량 및 가격 책정 구성&rdquo; 블레이드를 참조하세요.</p>


  <h2>업데이트(9월 4일)</h2>


  <p>이번 주에는 리소스&#39;할당량에 대해 계산되는 데이터 요소 볼륨에 웹 테스트 데이터를 포함할 수 있습니다.</p>
