### YamlMime:Yaml
ms.openlocfilehash: af0b5fb8909712f2176af6927707c1a8cab1171a
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139911427"
Slug: application-insights-temporary-limitations-and-performance-improvements-update
Title: 애플리케이션 Insights - 일시적인 제한 사항 및 성능 향상(업데이트)
Summary: '애플리케이션 Insights 성능, 안정성 및 규모를 지속적으로 개선하고 있습니다. 샘플링 및 필터링을 지원하는 새 버전의 Application Insights SDK와 동적 샘플링을 지원하는 미리 보기 버전이 있습니다. '
Content: >-
  <p><a href="https://azure.microsoft.com/services/application-insights/">애플리케이션 Insights</a> 성능, 안정성 및 규모를 지속적으로 개선하고 있습니다.&nbsp; <a href="https://azure.microsoft.com/en-us/blog/announcing-azure-portal-general-availability/">Azure Portal</a>은 최근에 일반 공급이 발표되었으며 Azure의 기본 포털 환경입니다. <a href="https://azure.microsoft.com/en-us/documentation/articles/app-insights-api-filtering-sampling/">샘플링 및 필터링</a>을 지원하는 새 버전의 Application Insights SDK와 <a href="https://www.nuget.org/packages/Microsoft.ApplicationInsights.Web/2.0.0-beta3">동적 샘플링</a>을 지원하는 미리 보기 버전이 있습니다.&nbsp;</p>


  <p>10월 하순에 쿼리 성능 및 전반적인 시스템 안정성을 개선하기 위해 서비스에서 데이터를 관리하는 방법을 변경하기 시작했습니다.&nbsp; 이 변경을 사용하도록 설정하기 위해 검색 쿼리를 수행할 수 있는 <a href="https://azure.microsoft.com/en-us/blog/application-insights-temporary-limitations-and-performance-improvements/">기간을 줄</a><a href="https://azure.microsoft.com/documentation/articles/app-insights-diagnostic-search/">여 줍니다</a>. 표준 또는 Premium 가격 책정 플랜&rsquo;을 사용하는 경우에도&rsquo; 7일 이상 거슬러 올라가는 검색 쿼리를 수행할 수 없습니다.&nbsp; 이제 데이터 리팩터링을 완료했지만 안타깝게도 이 변경 사항을 롤아웃하는 데 예상보다 시간이 오래 걸립니다. 1월에는 검색 쿼리를 복원하는 데 필요한 최종 변경 내용을 7일 이상 롤아웃하기 시작합니다. 2월 중순까지 가격 책정 플랜에서 제공하는 원시 데이터 보존 제한까지 7일을 초과하여 다시 한 번 검색할 수 있습니다. 그 동안 표준 및 Premium 고객은 <a href="https://azure.microsoft.com/en-us/documentation/articles/app-insights-export-telemetry/">연속 내보내</a>기를 사용하여 7일이 지난 데이터에 계속 액세스할 수 있습니다.&nbsp;</p>


  <p><a href="https://azure.microsoft.com/documentation/articles/app-insights-metrics-explorer/">메트릭 탐색기는</a> 7일을 초과하여 표준 및 사용자 지정 속성을 기준으로 필터링하고 그룹화할 수 있는 기능을 포함하여 자세한 메트릭 데이터를 계속 제공합니다.</p>


  <p>적절한 시기에 올바른 정보에 액세스하는 것은 애플리케이션 문제를 모니터링, 진단 및 해결하는 데 매우 중요하다는 것을 알고 있습니다. 따라서 애플리케이션 Insights 환경을 보다 유용하고 가치 있게 만들기 위해 환경 및 지원 인프라를 지속적으로 변경하고 개선하고 있습니다.</p>


  <p>언제나 그처럼 피드백을 듣고 싶으므로 사용자 의견 및 <a href="https://social.msdn.microsoft.com/Forums/en-US/home?forum=ApplicationInsights">MSDN 포럼</a>에 대한 피드백, 제안 또는 질문을 제공해 주세요.</p>
