### YamlMime:Yaml
ms.openlocfilehash: 98f2e881340ab225c96d25617cbb723fd343bcf0
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139907924"
Slug: application-insights-powershell-script-available-for-creating-release-annotations
Title: '애플리케이션 Insights: 릴리스 주석을 만드는 데 사용할 수 있는 Powershell 스크립트'
Summary: 현재 VSTS를 사용하지 않는 사용자 기반을 지원하기 위해 어디서나 릴리스 주석을 만드는 데 사용할 수 있는 Powershell 스크립트를 제공합니다.
Content: >-
  <h2>어디서나 주석 해제</h2>


  <p>이제 많은 사용자가 <a href="https://azure.microsoft.com/en-us/blog/application-insights-announces-availability-of-release-annotations/" target="_blank">릴리스 주석</a>에 익숙해지고 애플리케이션 Insights 리소스에 추가하기 시작했습니다. 이 시점까지 이러한 릴리스 주석을 볼 수 있는 유일한 방법은 Visual Studio Team Services 릴리스에 추가하는 것입니다. 이 통합은 VSTS 사용자에게 유용합니다.</p>


  <p>이 기능을 발표 한 후, 우리는 즉시 기본적으로 헤이에 &ldquo;달하는 많은 사용자로부터 피드백을 받았다, 이러한 주석은 중대하고 wed&rsquo; 정말 그들을 사용하는 것을 좋아하지만, 우리는 지금 우리의 응용 프로그램 릴리스에 대한 다른 무언가를 사용합니다.&rdquo; 글쎄, 우리는 당신이 크고 분명하게 듣습니다! 따라서 현재 VSTS를 사용하지 않는 사용자 기반을 지원하기 위해 어디에서&rsquo;나 릴리스 주석을 만드는 데 사용할 수 있는 Powershell 스크립트를 가져오려고 합니다.</p>


  <p><a href="https://github.com/Microsoft/ApplicationInsights-Home/blob/master/API/CreateReleaseAnnotation.ps1">GitHub</a> Powershell 스크립트를 찾을 수 있습니다.</p>


  <p>일반적인 사용법은 다음과 같습니다.</p>


  <pre class="prettyprint">

  .\CreateReleaseAnnotation.ps1 -applicationId &quot;&lt;appId&gt;&quot; -apiKey &quot;&lt;apiKey&gt;&quot; -releaseName &quot;&lt;releaseName&gt;&quot; -releaseProperties @{&quot;ReleaseDescription&quot;=&quot;Release with annotation&quot;;&quot;TriggerBy&quot;=&quot;John Doe&quot;}</pre>


  <p>즉, API 키를 생성한 다음 Azure Portal에서 이 키와 appId를 복사하기만 하면 됩니다. 이러한 항목이 있으면 Powershell 스크립트를 사용하여 특성을 적절하게 채울 준비가 된 것입니다.</p>


  <p><strong><em>업데이트</em></strong>: <a href="https://github.com/roryprimrose" target="_blank">Rory Primrose</a> 덕분에 이제 문어 배포 워크플로에서 애플리케이션 Insights 릴리스 주석을 만들 수 있습니다. 템플릿 및 해당 설명서는 여기에서 GitHub 찾을 수 <a href="https://library.octopusdeploy.com/#!/step-template/actiontemplate-application-insights-annotate-release" target="_blank">있습니다</a>.</p>


  <h2>앞으로 이동</h2>


  <p>주석의 기능을 확장하여 사용자에게 여러 종류를 가져오고 사용자 지정 주석을 허용하는 경우 이러한 추가 옵션을 지원하도록 이 Powershell 스크립트를 수정할 계획입니다. 물론 언제든지 이 스크립트를 직접 복사하고 조정하여 특정 또는 사용자 지정 종류의 주석을 사용할 수 있게 됩니다.</p>


  <p>API가 완성됨에 따라 API를 통해 더 많은 직접 액세스 권한을 부여하고 포털&rsquo; UI를 통해 주석을 더 쉽게 삽입할 수 있는 방법을 찾고 있습니다. 당신은 계속 지켜보고, 우리는&rsquo; 계속 진화합니다.</p>


  <p>언제나처럼 애플리케이션 Insights 사용자 의견 페이지에서 새로운 기능 또는 향상된 기능에 대한 아이디어를 공유하고 <a href="https://social.msdn.microsoft.com/Forums/vstudio/en-US/home?forum=ApplicationInsights"><u>애플리케이션 Insights 포럼</u></a>에서 질문하세요.</p>
