### YamlMime:Yaml
ms.openlocfilehash: 52a0a9cb8c0319b3a59fc4146f17d1fe6db87af0
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139907944"
Slug: application-insights-analytics-grid
Title: 서비스의 새 그리드 컨트롤
Summary: Visual Studio 애플리케이션 Insights 분석에서 강력한 새 그리드 표시를 확인했나요? 필터링, 정렬, 그룹화 및 페이징된 디스플레이가 있어 큰 쿼리 결과를 탐색하는 데 모두 적합합니다.
Content: >-
  <p>Visual Studio 애플리케이션 Insights <a href="https://blogs.msdn.microsoft.com/bharry/2016/03/28/introducing-application-analytics/">분석</a>에서 강력한 새 그리드 표시를 확인했나요? <strong>필터링, 정렬, 그룹화</strong> 및 <strong>페이징된 디스플레이</strong> &ndash; 는 큰 쿼리 결과를 탐색하는 데 적합합니다. 또한 예외 스택 및 사용자 지정 속성과 같은 <strong>중첩된 데이터를 확장</strong> 할 수 있습니다. 이 모든 작업은 다시 실행하지 않고도 마지막 쿼리에서 반환된 데이터에 대해 작동합니다.</p>


  <h2>정렬 및 그룹화</h2>


  <p>열 헤드를 클릭하여 결과를 정렬합니다. 다른 방법으로 정렬하려면 다시 클릭하고 세 번째로 원래 순서로 되돌려 갑니다. 분명히 하기 위해 이 기능은 포털에서 받은 결과를 정렬하고 쿼리를 다시 실행하지 않습니다. 쿼리에 &quot;테이크, &quot;&quot; 제한&quot; 또는 &quot;최상위&quot; 연산자가&rsquo; 포함된 경우 반환된 결과 집합만 표시됩니다.</p>


  <p>&rsquo;둘 이상의 열을 기준으로 정렬된 항목을 보려면 그룹화하세요. 테이블 설정에서 그룹화 사용이 선택되어 있는지 확인합니다. 열 헤드를 테이블 위의 공간으로 끌어다 놓습니다.</p>


  <p><img alt="New grid control - Application Insights Analytics" border="0" height="289" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/acfb022b-abc6-4b70-8732-29afd1442557.png" style="border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="여러 열로 그룹화" width="480"></p>


  <h2>필터링</h2>


  <p>&rsquo;각 열 헤드에 필터 아이콘이 있습니다. 문자열 및 숫자에 대해 다양한 조건을 사용할 수 있습니다.</p>


  <p><img alt="New grid control - Application Insights Analytics" border="0" height="294" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/0f9a12a7-eebb-4754-a9c7-8d5c3c809ac5.png" style="border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="열에 필터 적용" width="250"></p>


  <h2>중첩된 데이터 구조</h2>


  <p>행을 확장하여 모든 속성을 볼 때 예외 스택 추적 및 사용자 지정 차원(그렇지 않으면 JSON의 긴 줄로 표시되는 항목)과 같은 항목을 확장할 수 있습니다.</p>


  <p><img alt="New grid control - Application Insights Analytics" border="0" height="290" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/d15aec61-804b-48a7-8a9a-9d38f729706e.png" style="border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="중첩된 데이터 구조" width="480"></p>


  <h2>&hellip;그리고 모든 일반적인 물건</h2>


  <p>눈치 채지 못한&rsquo; 경우 원하는 모든 일반적인 작업을&rsquo; 수행할 수 있습니다. 오른쪽 위에 열 선택기 단추가 있는 열을 선택하고, 머리글을 끌어 열을 다시 정렬하고, 경계를 끌어 열 크기를 조정할 수 있습니다. 긴 데이터는 페이지로 구분됩니다. 페이지 간에 이동하고 페이지당 최대 레코드 수를 설정하기 위해 각 페이지의&nbsp; 맨 아래에 있는 컨트롤을 참조하세요.</p>


  <p>언제나처럼 다음 채널 중 하나를 사용하거나 아래의 댓글 스레드에서 질문이나 피드백을 자유롭게 보내주세요.</p>


  <ul>
   <li><a href="https://analytics.applicationinsights.io/demo">애플리케이션 Insights 분석 사용해 보기</a></li>
   <li><a href="https://visualstudio.uservoice.com/forums/357324-application-insights/category/161991-analytics">애플리케이션 Insights 아이디어에서 아이디어 제안 및 투표</a></li>
   <li><a href="https://social.msdn.microsoft.com/Forums/vstudio/home?forum=ApplicationInsights">애플리케이션 Insights Community 대화에 참여</a></li>
  </ul>
