### YamlMime:Yaml
ms.openlocfilehash: ec8b07a45ff7d25d724245eea5f1cf88a70561e9
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139907943"
Slug: application-insights-analytics-time-picker
Title: '소개: Application Insights Analytics의 시간 선택기'
Summary: '쿼리에 대한 시간 범위를 쉽게 설정할 수 있도록 시간 선택기가 Azure Application Insights Analytics에 추가되었습니다. '
Content: >-
  <p>쿼리의 시간 범위를 쉽게 설정할 수 있도록 시간 선택기가 <a href="https://azure.microsoft.com/services/application-insights/" target="_blank">Azure 애플리케이션 Insights</a> <a href="https://docs.microsoft.com/azure/application-insights/app-insights-analytics-tour" target="_blank">Analytics</a>에 추가되었습니다. 기본 범위는 지난 24시간이지만 쉽게 변경할 수 있습니다. 다른 사전 설정 범위를 선택하거나 쿼리에 타임스탬프&rdquo;&hellip; 절을 직접 추가&ldquo;하면 됩니다(따라서 쿼리에 이미 시간 필터가 포함되어 있는 경우 이전과 정확히 일치합니다&rsquo;).<br>

  &nbsp;<img alt="Time Picker in Application Insights Analytics" border="0" height="161" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/e4f1f7b9-e653-4a2f-94b6-412c06f667eb.png" style="border-width: 0px; margin: 0px auto; padding-top: 0px; padding-right: 0px; padding-left: 0px; float: none; display: block; background-image: none;" title="애플리케이션 Insights 분석의 시간 선택기" width="610"></p>


  <h3>시간 선택기가 필요한 이유는 무엇인가요?</h3>


  <p>데이터의 산을 사용하여 분석 사용자는 종종 특정 시간 프레임에 집중하려고 합니다. 새 시간 선택기를 사용하면 쿼리를 수동으로 편집하지 않고도 흥미로운 이벤트를 확대 및 탐색할 수 있습니다. 데이터 보존 기간을 전체 90일로 업그레이드할 예정이면 반환되는 레코드 수를 좁히기 위해 시간 필터를 적용하면 이벤트&rsquo; 근본 원인을 파악하고 결과를 조사하는 데 도움이 됩니다. 시간 필터는 쿼리를 보다 효율적으로 만들고 더 빠른 결과를 얻을 수 있는 좋은 방법입니다. 이 때문에 Weve&rsquo;는 새로운 시간 선택기를 도입하여 시간 필터링을 전면에 도입하고 가능한 한 쉽게 만들기로 결정했습니다.</p>


  <h3>시간 선택기는 무엇을 합니까?</h3>


  <p>익숙한 이동 단추 옆에 있는 시간 선택기를 사용하면 수동으로 반복해서 입력하는 대신 쿼리에 적용할 시간 범위를 선택할 수 있습니다. 선택한 시간 범위는 현재 탭의 모든 쿼리에 적용됩니다. 기본 범위는 지난 24시간이지만 다른 범위를 &ndash;&nbsp; 사용하면 10분, 지난 1시간, 2일 또는 7일 동안의 다른 사전 설정을 &ndash; 선택하기만 하면 됩니다. 쿼리를 실행한 후 결과 표시줄에서 적용된 시간 범위를 볼 수 있습니다.</p>


  <p><img alt="Time Picker in Application Insights Analytics" border="0" height="135" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/e2143f41-740a-4bd3-8b16-f4ff05df63dc.png" style="border-width: 0px; margin: 0px auto; padding-top: 0px; padding-right: 0px; padding-left: 0px; float: none; display: block; background-image: none;" title="애플리케이션 Insights 분석의 시간 선택기" width="610"><br>

  &nbsp;<br>

  요구 사항과 일치하는 사전 설정이 없는 경우 사용자 지정 시간 범위를 선택하여 쿼리에 고유한 시간 필터를 추가하는 방법을 알아봅니다.</p>


  <h3>하지만 대기, 이미 시간 필터를 포함 하는 쿼리에 대 한?</h3>


  <p>염려하지 마세요. 쿼리에서 명시적 시간 필터를 지정하는 것은 매우 강력한 기능입니다. 이러한 경우 시간 필터를 포함하는 쿼리에 대해 자동으로 선택된 쿼리 모드에서 집합을 추가했습니다.</p>


  <p><img alt="Time Picker in Application Insights Analytics" border="0" height="164" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/0ed5aad7-78e1-45ac-ab9b-3c245838721e.png" style="border-width: 0px; margin: 0px auto; padding-top: 0px; padding-right: 0px; padding-left: 0px; float: none; display: block; background-image: none;" title="애플리케이션 Insights 분석의 시간 선택기" width="610"></p>


  <p>&nbsp;</p>


  <h2>다음 단계는 무엇입니까&rsquo;?</h2>


  <p><br>

  이것은 물론 시작에 불과합니다. 더 많은 사용자가 시간 선택기를 알게 되면 이전 달(현재 월 이전의 전체 달력 월) 및 특정 시작 및 종료 날짜 및 시간 선택과 같은 더 많은 사용 사례를 지원하도록 발전할 것입니다.</p>


  <p>언제나처럼 다음 채널 중 하나를 사용하여 질문이나 피드백을 자유롭게 보내주세요.<br>

  &bull;&nbsp;<a href="https://visualstudio.uservoice.com/forums/357324-application-insights/category/161991-analytics" target="_blank">UserVoice 페이지에서 아이디어 제안 및 투표</a><br>

  &bull;&nbsp;<a href="https://social.msdn.microsoft.com/Forums/vstudio/home?forum=ApplicationInsights" target="_blank">애플리케이션 Insights Community 포럼에서 대화 참가</a><br>

  &bull;&nbsp;<a href="https://analytics.applicationinsights.io/demo" target="_blank">Application Insights Analytics 사용해 보기</a></p>
