### YamlMime:Yaml
ms.openlocfilehash: e7f783ab848c0be9be89ba30c4acade8d06a42f9
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139903340"
Slug: applicationsecuritygroups
Title: 이제 모든 Azure 지역에서 애플리케이션 보안 그룹을 일반 공급
Summary: >+
  모든 Azure 지역에서 ASG(애플리케이션 보안 그룹)의 일반 공급이 발표되어 기쁘게 생각합니다. 이 기능은 Azure의 가상 네트워크에 대한 보안 마이크로 세분화를 제공합니다.

Content: >-
  <p>모든 Azure 지역에서 ASG(애플리케이션 보안 그룹)의 일반 공급이 발표되어 기쁘게 생각합니다. 이 기능은 Azure의 가상 네트워크에 대한 보안 마이크로 세분화를 제공합니다.</p>


  <p><img alt="" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/Intro.PNG" style="width: 800px; height: 412px; margin-right: auto; margin-left: auto; float: none; display: block;"></p>


  <h2>네트워크 보안 마이크로 세분화</h2>


  <p>ASG를 사용하면 명시적 IP 주소 대신 애플리케이션에 중앙 집중화된 워크로드에 따라 세분화된 네트워크 보안 정책을 정의할 수 있습니다. 네트워크의 신뢰할 수 있는 세그먼트에서 트래픽을 필터링하여 모니커 및 보안 애플리케이션을 사용하여 VM을 그룹화할 수 있는 기능을 제공합니다.</p>


  <p>세분화된 보안 트래픽 제어를 구현하면 워크로드의 격리가 향상되고 개별적으로 보호됩니다. 위반이 발생하는 경우 이 기술은 해커로부터 네트워크를 횡적 탐색할 때 발생할 수 있는 잠재적 영향을 제한합니다.</p>


  <h2>보안 정의 간소화</h2>


  <p>ASG를 사용하면 다음 단계를 사용하여 애플리케이션 패턴에 따라 트래픽을 필터링하는 것이 간소화됩니다.</p>


  <ul>
   <li>애플리케이션 그룹을 정의하고 아키텍처에 맞는 모니커 설명 이름을 제공합니다. 애플리케이션, 워크로드 유형, 시스템, 계층, 환경 또는 모든 역할에 사용할 수 있습니다.</li>
   <li>ASG 및 NSG(네트워크 보안 그룹)를 사용하여 단일 규칙 컬렉션을 정의하면 모든 서브넷의 전체 가상 네트워크에 단일 NSG를 적용할 수 있습니다. 단일 NSG는 트래픽 정책에 대한 완전한 가시성과 관리를 위한 단일 위치를 제공합니다.</li>
   <li>사용자 고유의 속도로 크기를 조정합니다. VM을 배포할 때 적절한 ASG의 멤버로 만듭니다. VM이 여러 워크로드를 실행하는 경우 여러 ASG를 할당하기만 하면 됩니다. 워크로드에 따라 액세스 권한이 부여됩니다. 보안 정의에 대해 다시 걱정할 필요가 없습니다. 더 중요한 것은 제로 트러스트 모델을 구현하여 명시적으로 허용되는 애플리케이션 흐름에 대한 액세스를 제한할 수 있다는 것입니다.</li>
  </ul>


  <h2>단일 네트워크 보안 정책</h2>


  <p>ASG는 동일한 서브넷 내에 여러 애플리케이션을 배포하고 ASG를 기반으로 트래픽을 격리하는 기능을 도입합니다. ASG를 사용하면 구독의 NSG 수를 줄일 수 있습니다. 경우에 따라 가상 네트워크의 여러 서브넷에 단일 NSG를 사용할 수 있습니다. ASG를 사용하면 동적 환경에서 다음과 같은 이점을 제공하여 구성을 중앙 집중화할 수 있습니다.</p>


  <ul>
   <li><strong>중앙 집중식 NSG 보기</strong>: 단일 위치의 모든 트래픽 정책입니다. &rsquo;변경 내용을 쉽게 작동하고 관리할 수 있습니다. VM 그룹에 대한 새 포트를 허용해야 하는 경우 단일 규칙을 변경할 수 있습니다.</li>
   <li><strong>중앙 집중식 로깅</strong>: <a href="https://docs.microsoft.com/en-us/azure/network-watcher/network-watcher-nsg-flow-logging-overview" target="_blank">NSG 흐름 로그</a>와 함께 로그에 대한 단일 구성은 트래픽 분석에 여러 가지 이점이 있습니다.</li>
   <li><strong>정책 적용</strong>: 특정 트래픽을 거부해야 하는 경우 우선 순위가 높은 보안 규칙을 추가하고 관리 규칙을 적용할 수 있습니다.</li>
  </ul>


  <h2>동서 트래픽 필터링</h2>


  <p>ASG를 사용하면 여러 워크로드를 격리하고 가상 네트워크에 대한 추가 보호 수준을 제공할 수 있습니다.</p>


  <p>다음 그림에서는 여러 애플리케이션이 동일한 가상 네트워크에 배포됩니다. 설명된 보안 규칙에 따라 워크로드는 서로 격리됩니다. 애플리케이션 중 하나의 VM이 손상되면 횡적 탐색이 제한되어 공격자의 잠재적 영향을 최소화합니다.</p>


  <p>이 예제에서는 application1의 웹 서버 VM 중 하나가 손상되었다고 가정하고&rsquo; 나머지 애플리케이션은 계속 보호되며 데이터베이스 서버와 같은 중요한 워크로드에 대한 액세스는 여전히 연결할 수 없습니다. 이 구현은 네트워크에 여러 추가 보안 계층을 제공하여 이러한 침입을 덜 해롭고 이러한 이벤트에 쉽게 대응할 수 있도록 합니다.</p>


  <p><img alt="" height="346" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/EastWest.PNG" style="width: 1000px; height: 432px; margin-right: auto; margin-left: auto; float: none; display: block;" width="800"></p>


  <h2>남북 트래픽 필터링</h2>


  <p>NSG의 추가 기능과 함께 다양한 시나리오에서 온-프레미스 및 Azure 서비스에서 워크로드를 격리할 수도 있습니다.</p>


  <p>다음 그림에서는 가상 네트워크 내의 여러 워크로드 유형에 대해 비교적 복잡한 환경을 구성합니다. 애플리케이션은 보안 규칙을 설명하여 각 VM에 올바른 정책 집합을 적용합니다. 이전 예제와 마찬가지로 분기 중 하나가 손상된 경우 가상 네트워크 내에서 탐색이 제한되므로 침입자의 잠재적 영향을 최소화합니다.</p>


  <p>이 예제&rsquo;에서는 VPN을 사용하여 연결된 분기 중 하나에 있는 누군가가 워크스테이션을 손상시키고 네트워크에 액세스할 수 있다고 가정합니다. 일반적으로 네트워크의 나머지 부분을 격리하여 이 분기에는 네트워크의 하위 집합만 필요합니다. 다른 모든 애플리케이션은 계속 보호되고 연결할 수 없습니다. 전체 네트워크에 대한 다른 보안 계층을 ASG합니다.</p>


  <p>웹 서버 중 하나에서 위반을 감지했다고 가정하는 또 다른 흥미로운 시나리오는 조사를 위해 VM을 격리하는 것이 좋습니다. ASG를 사용하면 첫 번째 보안 정책에서 격리 VM에 대해 미리 정의된 특수 그룹을 쉽게 할당할 수 있습니다. 이러한 VM은 이러한 처리에 대응하고 완화하는 데 도움이 되는 추가 혜택을 제공하는 액세스 권한을 잃게 됩니다.</p>


  <p><img alt="" height="442" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/NorthSouth.PNG" style="width: 1000px; height: 552px; margin-right: auto; margin-left: auto; float: none; display: block;" width="800"></p>


  <h2>요약</h2>


  <p>NSG의 최신 개선 사항과 함께 애플리케이션 보안 그룹은 단일 관리 환경, 여러 차원에 대한 제한 증가, 훌륭한 수준의 간소화 및 아키텍처와의 자연스러운 통합과 같은 네트워크 보안 영역에서 여러 가지 이점을 가져왔으며, 오늘부터 시작하여 가상 네트워크에서 이러한 기능을 경험합니다.</p>


  <p>자세한 내용은 <a href="https://docs.microsoft.com/en-us/azure/virtual-network/security-overview#application-security-groupshttps://docs.microsoft.com/azure/virtual-network/security-overview" target="_blank">ASG를 설명하는 NSG 개요 문서를</a> 참조하세요. 다음 <a href="https://docs.microsoft.com/en-us/azure/virtual-network/create-network-security-group-preview" target="_blank">자습서</a>에서 NSG 및 ASG를 구현하는 방법을 알아봅니다.</p>


  <p>언제나 그처럼 여러분의 피드백은 우리가 올바른 방향으로 계속 발전하고 나아가는 데 도움이 됩니다. <a href="https://feedback.azure.com/forums/217313-networking?category_id=77468https://feedback.azure.com/forums/217313-networking?category_id=77466" target="_blank">사용자 음성 채널을</a> 통해 ASG에 대한 제안 및 피드백과 향후 시나리오를 듣고 싶습니다. Azure의 네트워크 보안 공간에서 더 흥미로운 업데이트를 확인하세요!</p>
