### YamlMime:Yaml
ms.openlocfilehash: 9cf442a0ca647e20da0d2515d74219381d3a6ec7
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139907950"
Slug: application-gateway-analytics-via-goaccess
Title: GoAccess를 통한 Application Gateway Analytics
Summary: Azure Application Gateway는 트래픽 패턴 및 호출자의 IP, 요청된 URL, 반환 코드 등과 같은 유용한 정보를 기록하는 고객에 대한 액세스 로그를 제공합니다.
Content: >-
  <p>Azure Application Gateway는 트래픽 패턴 및 호출자&rsquo; IP, 요청된 URL, 반환 코드 등과 같은 유용한 정보를 기록하는 고객에 대한 액세스 로그를 제공합니다. 이러한 로그는 Azure Storage 푸시하고 Azure Log Analytics, Excel 및 Power BI 같은 다양한 도구를 사용하여 분석할 수 있습니다. 이러한 메커니즘을 설정하고 사용하는 데 어려움의 수준은 주로 고객의&rsquo; 친숙함과 선호도에 따라 달라집니다.</p>


  <p>고객은 다양한 시나리오에 대한 트래픽 분석이 필요하며, 그 중 일부는 다음과 같습니다.</p>


  <ul>
   <li>프로모션 캠페인과 같은 예상되는 트래픽이 많은 이벤트 중 라이브 모니터링.</li>
   <li>보안 인시던트 등 운영 문제를 디버깅하고 해결합니다.</li>
   <li>관찰된 트래픽(클라이언트 통계)을 기준으로 고객이 누구인지 이해합니다.</li>
   <li>요청이 많은 애플리케이션의 부분 또는 URL(상위 요청 URL)을 이해합니다.</li>
   <li>애플리케이션의 성능(오류 및 대기 시간)을 이해합니다.</li>
  </ul>


  <p>게시된 <a href="https://aka.ms/appgwgoaccessreadme" target="_blank">Azure 빠른 시작 템플릿</a>을 통해 인기 있는 오픈 소스 <a href="https://goaccess.io/" target="_blank">GoAccess</a> 실시간 로그 분석기 프레임워크와 Application Gateway 액세스 로그의 통합을 기존 Application Gateway 트래픽 분석 도구 키트에 추가하게 되어 기쁘게 생각합니다. 이 통합을 통해 고객은 AppGW 트래픽 흐름에 대한 인사이트를 얻을 수 있습니다. GoAccess는 터미널 또는 HTML과 같은 여러 출력 형식에 대한 풍부한 대시보드에 데이터를 제공합니다.</p>


  <p>이 도구는 다음을 포함하여 애플리케이션 게이트웨이에 대한 중요한 HTTP 트래픽 통계를 제공합니다.</p>


  <ul>
   <li>총 요청, 성공적인 요청, 실패한 요청 및 고유한 방문자 수와 같은 전체 트래픽 통계입니다.</li>
   <li>일일 최고 고유 방문자.</li>
   <li>HTTP 상태 코드 배포</li>
   <li>상위 요청된 파일/URL, 404개 URL</li>
   <li>클라이언트 통계: 방문자 호스트 이름/IP, 클라이언트 운영 체제, 브라우저.</li>
   <li>트래픽 볼륨의 시간 분포입니다.</li>
  </ul>


  <p>일부 스크린샷은 다음과 같습니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/97cbafe6-deb5-4e8c-9c76-6a24bcca10af.png"><img alt="goaccessgraphs" border="0" height="854" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/7ea7e1a7-3c77-4392-813b-72067056bb69.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="goaccessgraphs" width="2458"></a></p>


  <p>또한 GoAccess는 실행하는 데 필요한 리소스 측면에서 효율적이고 가볍습니다.</p>


  <p>&rsquo;이제 백그라운드에서 어떤 일이 일어나는지 살펴보겠습니다. GoAccess 통합을 위한 Azure 빠른 시작 템플릿은 배포 시 다음을 수행합니다.</p>


  <ul>
   <li>구독에서 Linux VM을 만들고 실행합니다.</li>
   <li>GoAccess 및 웹 서버를 설치하고 실행합니다.</li>
   <li>구성된 스토리지 계정에서 액세스 로그를 증분 방식으로 가져오는 Azure 커넥터를 설치하고 실행합니다.</li>
  </ul>


  <p>템플릿을 배포할 때 고객의 입력으로 필요한 값은 거의 없으며 템플릿 아래의 추가 정보 파일에 설명되어 있습니다. 배포가 완료되면 고객으로서 해야 할 일은 브라우저에서 URL https://&lt; Public-DnsNameOfVM&gt;/report.html 가리키기만 하면 됩니다. 여기서 &lt;Public-DnsNameOfVM&gt; 은 템플릿에서 설치한 VM에 대한 입력 중 하나로 제공한 DNS 이름입니다.</p>


  <p>설치 프로그램은 다음과 같습니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/7377271d-c6f7-4917-8de1-a3053193c437.png"><img alt="image" border="0" height="302" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/8fe33773-e54a-44ec-b464-0a98d722e3da.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="이미지" width="624"></a></p>


  <p>캐치는 무엇입니까&rsquo;? 몇 가지 노트를 제외하고는 그다지 많지 않습니다.</p>


  <ul>
   <li>표시된 통계의 새로 고침이 스토리지 계정으로 스트리밍되는 로그에 대한 일반적인 대기 시간을 초과하여 최대 5분 지연될 수 있습니다. 로그가 스토리지 계정에 도달하면 GoAccess에서 데이터를 새로 고치는 데 최대 5분이 걸릴 수 있습니다.</li>
   <li>솔루션은 고객 구독에서 VM을 실행합니다. 따라서 고객은 생성될 수 있는 VM 및 대역폭 비용을 담당합니다.</li>
  </ul>


  <p>고객이 Application Gateway Analytics에 대한 이 빠른 시작 템플릿을 활용하기를 바랍니다. 템플릿 및 지원 옵션에 대한 자세한 내용은 <a href="https://aka.ms/appgwgoaccessreadme" target="_blank">추가</a> 정보를 참조하세요.</p>


  <p>언제나처럼 <a href="https://feedback.azure.com/forums/217313-networking" target="_blank">Azure 피드백</a> 채널을 통해 고객 피드백을 환영합니다. 백로그에서 우선 순위를 확인하려는 기능에 대해 계속 투표하세요.</p>
