### YamlMime:Yaml
ms.openlocfilehash: ad8a290df513f900a83c8044d365dcaedf660777
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139913202"
Slug: application-insights-work-item-integration-with-github
Title: '애플리케이션 Insights: GitHub 작업 항목 통합'
Summary: 애플리케이션 Insights 팀은 애플리케이션 Insights 직접 GitHub 작업 항목(문제)을 만드는 지원을 추가했습니다.
Content: >-
  <p>불과 한 달 전, 애플리케이션 Insights 대한 새로운 기능 집합인 <a href="https://azure.microsoft.com/en-us/blog/application-insights-work-item-integration-with-visual-studio-team-services/" target="_blank">Visual Studio Team Services 작업 항목 통합</a>을 발표했습니다. 오늘 저는 분석을 워크플로에 통합하려는 사람들에게 더 좋은 소식을 전합니다. 우리는 GitHub 대한 유사한 경험에 대한 작업을 마쳤습니다. 몇 분 만에 중요한 애플리케이션 Insights 데이터가 포함된 문제를 GitHub 프로젝트에 직접 쓰도록 애플리케이션 Insights 리소스를 구성할 수 있습니다.</p>


  <h3>작업 항목 통합 구성</h3>


  <p>GitHub 애플리케이션 Insights 리소스에 대한 통합 구성은 VSTS에 사용되는 절차와 매우 유사하게 작동합니다. 해당 리소스에 대한 설정 블레이드로 이동하기만 하면 됩니다. 설정&rsquo; 블레이드의 &ldquo;구성&rdquo; 섹션에 작업 항목이 표시된 &ldquo;항목을 적어둡니다.&rdquo;</p>


  <p><img height="360" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/9434e196-ddd0-4402-981e-81b56a3969ed.png" width="303"></p>


  <p>이 옵션을 클릭하면 작업 항목에 대한 구성 블레이드가 열립니다. &ldquo;이제 구성 블레이드의 맨 위에 있는 추적 시스템&rdquo; 드롭다운이 활성화되어 있으며 두 가지 선택 항목 중 하나가 GitHub.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/aadb0523-b41d-484d-9c9a-6320b88e261e.png"><img alt="image" border="0" height="44" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/10993b9c-c058-4011-82a1-0c1accff4c6f.png" style="border-width: 0px; padding-top: 0px; padding-right: 0px; padding-left: 0px; display: inline; background-image: none;" title="이미지" width="360"></a></p>


  <p>GitHub 선택합니다. 그런 다음 연결하려는 GitHub 프로젝트에 매핑되는 URL만 입력하면 됩니다.</p>


  <p><img alt="image" border="0" height="407" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/d8e672a4-4af9-4d1f-8248-38929b8ca3d2.png" style="border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; display: inline; background-image: none;" title="이미지" width="480"></p>


  <p>해당 정보가 있으면 권한 부여 단추를 클릭하면 선택한 GitHub 프로젝트에서 액세스 권한을 부여하도록 리디렉션되므로 작업 항목(문제)을 작성할 수 있습니다.</p>


  <p><img alt="image" border="0" height="244" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/535a0139-2201-4e8e-8d4d-9e67c93d6bfd.png" style="border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; display: inline; background-image: none;" title="이미지" width="480"></p>


  <p>참고: 아직 GitHub 로그인하지 않은 경우 이때 로그인하라는 메시지가 표시됩니다.</p>


  <p>권한 부여 프로세스를 완료한 후&rsquo; 확인을 클릭합니다. &rsquo;&ldquo;유효성 검사가 성공&rdquo;하고 블레이드가 닫힙니다. &rsquo;이제 GitHub 문제를 만들 준비가 되었습니다!</p>


  <h3>작업 항목 만들기</h3>


  <p>애플리케이션 Insights 작업 항목을 만드는 것은 매우 쉽습니다. 현재 작업 항목을 만들 수 있는 위치는 자동 관리 검색 및 작업의 개별 인스턴스(예: 예외, 오류, 요청 등)의 두 가지 위치입니다. 후자의 간단한 예를 보여 주겠지만 두 경우 모두 기능이 동일합니다.</p>


  <p>이 예제&rsquo;에서는 Azure에 게시한 테스트 웹앱을 확인합니다. 오류 블레이드를 확인하여 이 앱에 대한 작업을 자세히 살펴보기 시작했습니다(그러나 검색 단추 또는 메트릭 탐색기를 통해 동일한 정보를 얻을 수도 있음).</p>


  <p><img alt="image" border="0" height="321" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/aed665c7-5978-4b62-84fd-c46e508ba361.png" style="border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; display: inline; background-image: none;" title="이미지" width="610"></p>


  <p>이 웹앱에서 발생한 여러 예외가 있음을 알 수 있습니다. 이 예외 그룹을 자세히 살펴보면 목록을 보고 개별 예외를 선택할 수 있습니다.</p>


  <p><img alt="image" border="0" height="445" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/f8652452-769d-49eb-b8d4-9fc9c3a97a4b.png" style="border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; display: inline; background-image: none;" title="이미지" width="610"></p>


  <p>이 예외에 대한 세부 정보 블레이드를 보면 이제 블레이드 맨 위에 새 작업 항목 및 &ldquo;작업 항목&rdquo; 보기를 읽&ldquo;는 두 개의 단추를 사용할 수 있습니다.&rdquo; 작업 항목을 만들려면 이 단추 중 첫 번째 단추를 클릭하면 새 작업 항목 블레이드가 열립니다.</p>


  <p><img alt="image" border="0" height="358" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/a1535dd4-643b-4e5b-89c9-3ff6dc17191a.png" style="border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; display: inline; background-image: none;" title="이미지" width="610"></p>


  <p>여기서 볼 수 있듯이, 평균 시나리오에 필요한 거의 모든 것이 채워져 있습니다. 이 예외에 사용할 수 있는 모든 세부 정보가 세부 정보 필드에 추가되었습니다. 원하는 경우 제목을 재정의하거나 캡처된 세부 정보에 추가할 수 있습니다. &rsquo;작업 항목을 만들 준비가 되면 확인&rdquo; 단추를 클릭하면 &ldquo;문제가 GitHub 기록됩니다.</p>


  <h3>작업 항목 보기</h3>


  <p>&rsquo;Application Insights 하나 이상의 작업 항목을 만든 후에는 GitHub 쉽게 볼 수 있습니다. Azure Portal에 있는 경우 작업 항목에 연결된 이벤트에 대한 세부 정보 블레이드에 작업 항목&rdquo; 보기 단추가 &ldquo;활성화됩니다. 목록을 보려면 단추를 클릭하기만 하면 됩니다.</p>


  <p><img alt="image" border="0" height="130" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/83395f11-3203-48d3-b1de-56daac2a94d0.png" style="border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; display: inline; background-image: none;" title="이미지" width="610"></p>


  <p>보려는 작업 항목에 대한 링크를 클릭하면 GitHub 열립니다.</p>


  <p><img alt="image" border="0" height="409" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/d0c1e470-0c75-4868-b8c8-161be9fd9324.png" style="border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; display: inline; background-image: none;" title="이미지" width="610"></p>


  <p>이 문제에는 GitHub 문제를 보는 사용자가 Azure Portal 및 애플리케이션 Insights 다시 탐색할 수 있는 링크가 아래쪽에 있습니다.</p>


  <p>그게&rsquo; 전부입니다! 보듯이 이 기능은 매우 쉽게 설정할 수 있으며 애플리케이션 Insights 문제를 만드는 것이 바로 스냅입니다.</p>


  <p><a href="https://azure.microsoft.com/en-us/blog/application-insights-work-item-integration-with-visual-studio-team-services/" target="_blank">이전 게시물</a>에서 VSTS 작업 항목 통합에 대해 자세히 설명했듯이 이 기능을 개선하기 위한 향후 계획이 많이 있습니다. GitHub 통합을 완료하는 것은 다른 ALM 시스템&rdquo; 목표에 대한 지원의 &ldquo;일부였으며&rsquo;, Application Insights 대한 링크의 &ldquo;목표를 달성했습니다(이 기능은 Application Insights&rdquo; 만든 VSTS 작업 항목에도 추가되었습니다).</p>


  <p>이 기능 집합의 또 다른 중요한 이정표이지만, 여러 프로필을 설정하고, 이벤트를 기반으로 작업 항목을 자동으로 만들고, 작업 항목을 만들기 위한 다른 원본 지점(예: 경고)을 추가하는 기능과 같은 많은 목표가 있습니다. 일상적인 워크플로에 보다 유연하고 원활하게 통합할 수 있도록 작업 항목 통합을 지속적으로 개선하고 발전시킬 것입니다.</p>


  <p>언제나처럼 <a href="https://visualstudio.uservoice.com/forums/357324-application-insights">애플리케이션 Insights UserVoice 페이지에서</a> 새로운 기능 또는 향상된 기능에 대한 아이디어를 공유하세요. 질문이 있으면 <a href="https://social.msdn.microsoft.com/Forums/vstudio/en-US/home?forum=ApplicationInsights"><u>애플리케이션 Insights 포럼</u></a>을 방문하세요.</p>
