### YamlMime:Yaml
ms.openlocfilehash: 58d7dba1fa5d886ddb75d4cc641c189753b2e140
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139903346"
Slug: application-insights-tools-in-visual-studio-2015-rtm-2
Title: Visual Studio 2015 RTM의 애플리케이션 Insights 도구
Summary: 오늘 아침 Visual Studio 2015는 개발 주기의 모든 단계를 지원하는 많은 훌륭한 기능으로 출시되었습니다.
Content: >-
  오늘 아침 Visual Studio 2015는 개발 주기의 모든 단계를 지원하는 많은 훌륭한 기능으로 출시되었습니다. 아직 없는 경우 <a href="https://blogs.msdn.com/b/visualstudio/archive/2015/07/20/visual-studio-2015-and-visual-studio-2013-update-5-released.aspx">Visual Studio 2015 </a>릴리스 페이지를 확인하세요.이러한 기능 중에는 Visual Studio Visual Studio Application Insights Tools가 있습니다.

  <h2>Application Insights란?</h2>

  <a href="https://www.visualstudio.com/products/application-insights-vs.aspx">애플리케이션 Insights</a> 라이브 애플리케이션의 성능 및 사용을 모니터링하는 확장 가능한 분석 솔루션입니다. Windows 디바이스 및 ASP.NET 웹앱뿐만 아니라 iOS, Android 및 J2EE 등 다양한 플랫폼에서 웹 및 독립 실행형 애플리케이션에서 작동합니다. (여기서는 Visual Studio 개발로 사용하는 방법에 초점을 맞출 것이지만 전반적으로 균일하게 작동한다는 점을 언급할 가치가 있습니다.)


  애플리케이션 Insights 개발 팀을 대상으로 합니다. 이를 사용하여 성능 <a href="https://azure.microsoft.com/documentation/articles/app-insights-detect-triage-diagnose/">및</a> 가용성 문제 및 충돌을 감지하고 진단합니다.   <a href="https://azure.microsoft.com/documentation/articles/app-insights-overview-usage/">사용 패턴을 분석</a> 하고 각 새 기능의 성공을 측정합니다. 다음을 계획할 수 있도록 각 새 릴리스에 대한 데이터를 수집하여 devOps 주기에 기본 제공되도록 설계했습니다.


  <a href="https://acom.azurecomcdn.net/80C57D/blogmedia/blogmedia/2015/07/19/AI.png"><img class="alignnone size-medium wp-image-320561" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/AI-636x300.png" alt="Application Insights" width="636" height="300" /></a>

  <h2>Visual Studio 사용하여 애플리케이션 Insights 시작</h2>

  Visual Studio 애플리케이션 Insights 시작하는 것은 매우 간단합니다.


  쓰기 권한이 있는 <a href="https://azure.com/">Microsoft Azure</a> 구독이 필요합니다.무료로 등록할 수 있으며, 무료  <a href="https://azure.microsoft.com/pricing/details/application-insights/">계층 </a>화 애플리케이션 Insights 선택할 수 있습니다.


  새 프로젝트를 만드는 경우 애플리케이션 Insights 확인란이 선택되어 있는지 확인합니다.


  <img class="alignnone size-medium wp-image-320641" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/AIVS-636x319.jpg" alt="Application Insights checkbox in File New Dialog" width="636" height="319" />


  또는 기존 프로젝트가 있는 경우 프로젝트 상황에 맞는 메뉴 또는 연결된 서비스 대화 상자에서 애플리케이션 Insights 추가를 선택합니다.


  이러한 명령은 프로젝트에 SDK를 추가하고 데이터가 저장, 분석 및 표시되는 애플리케이션 Insights 리소스를 만듭니다.


  디버그, 테스트 및 프로덕션에서 애플리케이션 Insights 사용할 수 있습니다.

  <h2>2015 Visual Studio Application Insights Tools의 새로운 기능</h2>

  <h3>새 프로젝트 형식 지원:</h3>

  <ul>
   <li><a href="https://azure.microsoft.com/documentation/articles/app-insights-asp-net-five/">ASP.NET 5</a></li>
   <li>Windows 앱(출시 예정)</li>
   <li>Windows 8.1 유니버설</li>
  </ul>

  <h3>Visual Studio 연결된 서비스의 애플리케이션 Insights</h3>

  이제 Visual Studio(Project-Add-Connected&gt;&gt; Services)의 연결된 서비스 대화 상자에서 애플리케이션 Insights 찾을 수 있습니다.

  <a href="https://acom.azurecomcdn.net/80C57D/blogmedia/blogmedia/2015/07/19/Connected.png"><img class="alignnone size-medium wp-image-320581" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/Connected-539x369.png" alt="Connected" width="539" height="369" /></a>

  <h3>내 프로젝트에 AI 추가를 완료했습니다. 이제 어떻게 해야 할까요?</h3>

  애플리케이션 Insights 새 프로젝트 또는 기존 프로젝트에 추가한 후 시작 도움말에 대한 링크가 Project 서비스 참조 폴더 아래에 표시됩니다.


  <a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/link.png"><img class="alignnone size-full wp-image-320582" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/link.png" alt="link" width="345" height="130" /></a>

  <h2>내 프로젝트에 애플리케이션 Insights 옵션이 표시되지 않음</h2>

  일부 유형의 프로젝트의 경우 애플리케이션 Insights 구성이 완전히 자동화되지 않습니다. 하지만 애플리케이션 Insights 수동으로 추가할 수 있습니다. <a href="https://azure.microsoft.com/documentation/articles/app-insights-platforms/">지원되는 플랫폼의 전체 범위를 참조하세요</a>.

  <h2>애플리케이션 Insights 서비스 업데이트</h2>

  <a href="https://azure.microsoft.com/updates/?service=application-insights">서비스 업데이트</a> 페이지에서는 애플리케이션 Insights 항상 발생하는 새로운 기능 및 개선 사항을 알려줍니다.

  <h2>의견/피드백</h2>

  우리는 우리가 어떻게하고 있는지에 대해 듣고 매우 관심이 있습니다, 그래서 질문과 문제를 제출하시기 바랍니다 <a href="https://social.msdn.microsoft.com/Forums/vstudio/home?forum=ApplicationInsights">Forums</a>, 버그 <a href="https://connect.microsoft.com/VisualStudio">커넥트</a>  (애플리케이션 Insights 선택), 사용자 음성에 제안.
