### YamlMime:Yaml
ms.openlocfilehash: 9c451684a4cfcb036eafd6677e21925081de518d
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139907936"
Slug: application-insights-content-pack-for-power-bi
Title: Power BI 애플리케이션 Insights 콘텐츠 팩
Summary: Power BI 위한 새 애플리케이션 Insights 콘텐츠 팩에 대해 알아봅니다.
Content: >-
  <p><a href="https://powerbi.com">Power BI</a> 새 <a href="https://azure.microsoft.com/en-us/services/application-insights/">애플리케이션 Insights</a> 콘텐츠 팩을 사용하면 사용자 지정 가능한 대시보드 및 보고서 컬렉션에서 사용자에 대한 새로운 인사이트를 얻을 수 있습니다.&nbsp; 시각화에는 국가/지역별 사용자 위치와 요약 통계 및 활동 시계열을 모두 보여 주는 지도가 포함됩니다.</p>


  <p>애플리케이션을 모니터링하기 <a href="https://azure.microsoft.com/en-us/documentation/articles/app-insights-overview/">위해 Visual Studio 애플리케이션 Insights 이미 설정한</a> 경우 이 콘텐츠 팩은 지난 30일 동안 애플리케이션&rsquo; 사용량의 추세를 시각화할 수 있는 기능의 훌륭한 확장을 제공합니다. Power BI 사용하면 동일한 대시보드에 있는 여러 원본의 데이터를 결합할 수 있으므로 판매 데이터 및 웹 사이트 사용량을 동일한 실시간 프레젠테이션으로 끌어올 수 있습니다.</p>


  <p>설정하는 데 2분이 걸립니다. 여기서는 바로 사용할 수 있는 대시보드의 예제를&#39;.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/5aee0a97-3e6c-486b-bcba-4f3ecb809988.png"><img alt="AIPBIDashboard" border="0" height="331" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/f96a2791-3e9a-4427-a44f-dce851d2e9f9.png" style="border-top: 0px; border-right: 0px; background-image: none; border-bottom: 0px; padding-top: 0px; padding-left: 0px; border-left: 0px; display: inline; padding-right: 0px" title="AIPBIDashboard" width="684"></a></p>


  <p>맵은 이 애플리케이션&rsquo; 사용자가 있는 위치를 보여 줍니다. 차트는 지난 30일 동안의 사용자 수를 보여 줍니다.<br>

  대시보드는 쉽게 수정할 수 있으므로 원하는 위치에 표시할&#39;가장 관련성이 있는 데이터를 신속하게 가져올 수 있습니다.&nbsp; 더 나은, 이것은 설정하기 매우 쉽습니다! 살펴 보겠습니다&rsquo;.&hellip;</p>


  <h2>대시보드에 2분</h2>


  <p>Power BI 사용하여 애플리케이션 Insights 대시보드를 시작하고 실행하는 데 몇 분 정도 걸립니다. &#39;이 과정을 살펴보겠습니다.</p>


  <ol>
   <li><a href="https://portal.azure.com/">Azure Preview 포털</a>에서 앱&rsquo; 애플리케이션 Insights 개요 블레이드로 이동합니다.&nbsp; &rsquo;곧 여기에서 몇 가지 정보가 필요합니다. (<a href="https://azure.microsoft.com/en-us/documentation/articles/app-insights-overview/">앱에 대한 애플리케이션 Insights 아직 설정</a>하지 않은&rsquo; 경우 지금 설정하는 데 몇 분 정도 걸립니다.)</li>
   <br>
   <li><a href="https://powerbi.com/groups/me/getdata/services/application-insights">Power BI 애플리케이션 Insights 콘텐츠 팩으로</a> 이동하여 데이터 가져오기, 서비스, 애플리케이션 Insights 선택한 다음, 커넥트.<br>
   <a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/7ab87190-7dda-438c-a218-91d178bb8e40.png"><img alt="ConnectFlow" border="0" height="258" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/8117efba-8722-4f27-aeaf-ca94f742fd43.png" style="border-top: 0px; border-right: 0px; background-image: none; border-bottom: 0px; padding-top: 0px; padding-left: 0px; border-left: 0px; display: inline; padding-right: 0px" title="ConnectFlow" width="589"></a></li>
   <br>
   <li>&ldquo;애플리케이션&rdquo; Insights 커넥트 페이지에서 Azure Preview Portal에서 필요한 3가지 값을 복사하여 붙여넣어 Power BI.<br>
   <a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/26c5169c-e422-40cf-8f37-4bfeed4dd6d8.png"><img alt="AppInsightPowerBIConfigure" border="0" height="344" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/45a1179c-0957-4a4b-a018-bec574fa148b.png" style="border-top: 0px; border-right: 0px; background-image: none; border-bottom: 0px; padding-top: 0px; padding-left: 0px; border-left: 0px; display: inline; padding-right: 0px" title="AppInsightPowerBIConfigure" width="809"></a></li>
   <br>
   <li>다음 페이지에서 로그인&rdquo;을 간단히 누르&ldquo;고(인증 방법을 OAUTH2로 유지) 자격 증명을 묻는 메시지가 표시되면 Azure Preview 포털에서 애플리케이션에 액세스하는 데 필요한 자격 증명을 제공합니다.</li>
   <br>
   <li>이제 Power BI 데이터를 가져오며, 약 1분&rsquo; 후에는 사용자 고유의 애플리케이션에 대해 위와 같은 대시보드가 표시됩니다.</li>
  </ol>


  <h1>요약</h1>


  <p>&rsquo;이제 애플리케이션&rsquo;의 중요한 사용 통계(사용자 수, 세션, 지리 등)를 표시하는 대시보드가 생겼습니다. 데이터를 표시하거나, 다시 정렬하거나, 다른 원본의 데이터와 결합하는 다른 방법을 선택할 수 있습니다.</p>


  <p>이는 애플리케이션 Insights 콘텐츠 팩의 첫 번째 반복이며, Power BI&rsquo; 모든 뛰어난 기능을 통해 더 많은 작업을 수행할 수 있습니다.&nbsp; 애플리케이션 Insights User Voice 페이지에서 새로운 기능 또는 향상된 기능에 대한 아이디어를 공유하세요. 질문이 있으면 <a href="https://social.msdn.microsoft.com/Forums/en-US/ApplicationInsights/">애플리케이션 Insights 포럼</a>을 방문하세요.</p>
