### YamlMime:Yaml
ms.openlocfilehash: 863830b2d8db2a5bc2e6e7962d944659bbdb587a
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139911425"
Slug: application-insights-profiler
Title: 이제 Azure App Service용 애플리케이션 Insights Profiler를 일반 공급
Summary: Azure App Service용 Application Insights Profiler의 일반적인 가용성을 발표하게 되어 기쁩니다.
Content: >-
  <p>Azure App Service용 Application Insights Profiler의 일반적인 가용성을 발표하게 되어 기쁩니다. 동시에 컴퓨팅 리소스에 대한 Profiler의 공개 미리 보기 버전(예: Virtual Machines, 확장 집합, Cloud Services 및 Service Fabric)을 도입하게 되어 기쁘게 생각합니다. Profiler를 사용하면 프로덕션 애플리케이션에서 느린 요청에 대한 코드 수준 추적을 자동으로 수집하고 볼 수 있습니다.</p>


  <h2>개요</h2>


  <p>특히 앱이 클라우드의 프로덕션 환경에서 실행되는 경우 성능 문제를 진단하기가 어렵습니다. 고객이 앱을 사용할 때 응답 속도가 느린 경우 요청을 처리하기 위해 파이프라인에 있는 인프라, 프레임워크 또는 애플리케이션 코드로 인해 발생할 수 있습니다. 클라우드는 머신이 오고 가고, 사용자 입력 및 기타 조건이 지속적으로 변경되고, 확장성이 높아질 수 있는 매우 동적 &ndash; 입니다.</p>


  <p>애플리케이션 Insights Profiler는 위의 정확한 문제를 해결합니다. 이렇게 하면 이러한 모든 동적 상황에서 애플리케이션에 대한 성능 추적을 캡처하고 볼 수 있으며 최종 사용자에게 부정적인 영향을 주지 않고 대규모로 자동으로 발생합니다. 애플리케이션 Insights Profiler는 Azure에서 앱을 실행할 때 성능 문제를 쉽게 식별할 수 있도록 다음 정보를 캡처합니다.</p>


  <ul>
   <li>고객이 수행한 각 웹 요청에 대한 중앙값, 가장 빠르고 느린 응답 시간</li>
   <li>&ldquo;특정 웹 요청을 처리할 때 가장 오래 걸리는 핫&rdquo; 코드 경로</li>
  </ul>


  <p>Profiler는 익숙한 성능 문제를 진단하기 위한 PerfView 도구를 기반으로 합니다. PerfView 알고리즘을 대규모로 실행하도록 최적화되어 각 시간의 짧은 기간 동안 낮은 오버헤드 예제를 사용합니다. 가능한 한 빨리 성능 문제를 식별하기 위해 모든 Azure 애플리케이션에서 사용하는 것이 좋습니다. 실제로 Azure 애플리케이션&rsquo;에 성능 문제가 &ndash; 없도록 하여 Profiler가 문제를 조기에 파악하고 고객에게 광범위한 영향을 주지 않도록 하는 것이 목표입니다.</p>


  <h2>Profiler 사용</h2>


  <p>App Services에서 애플리케이션 Insights Profiler를 사용하도록 설정하려면 다음을 수행합니다.</p>


  <p><a href="https://go.microsoft.com/fwlink/?linkid=848303">Application Insights를 사용하여 라이브 Azure Web Apps 프로파일링</a></p>


  <p>컴퓨팅 리소스에서 Application Insights Profiler(미리 보기)를 사용하도록 설정하려면 다음을 수행합니다.</p>


  <p><a href="https://go.microsoft.com/fwlink/?linkid=848155&amp;clcid=0x409">다른 Azure 컴퓨팅 서비스에 프로파일러 사용</a></p>


  <h2>결과 보기</h2>


  <p>다음은 애플리케이션에서 성능 문제를 쉽게 식별하는 방법을 보여 주는 빠른 둘러보기입니다. 고객이 온라인으로 음악 앨범을 구매할 수 있는 음악 스토어 웹 애플리케이션이 있다고 가정해 보겠습니다. Azure에 앱을 배포하고 애플리케이션 Insights Profiler를 사용하도록 설정했습니다. 프로파일러를 사용하면 애플리케이션이 항상 성능이 좋은지 확인할 수 있습니다.</p>


  <h3>성능 문제 검색</h3>


  <p>먼저 웹앱에서 사용하는 애플리케이션 Insights 리소스 음악 스토어로 이동하세요. 성능 블레이드를 열어 성능 통계 개요를 확인합니다.</p>


  <p>성능 블레이드의 왼쪽에 있는 새 작업 섹션에는 각 웹 요청이 소요되는 기간에 대한 요약이 표시됩니다. 특정 행을 클릭하여 오른쪽의 콘텐츠를 필터링할 수 있습니다. 기본적으로 모든 요청이 선택됩니다.</p>


  <p>오른쪽의 전체 섹션에서는 평소보다 오래 걸리는 요청 수 또는 백분위수별로 그룹화된 평균 범위 내의 요청 수에 대한 분포를 보여 줍니다. 슬라이더 막대를 사용하여 기간 범위를 필터링하여 이러한 요청의 세부 정보를 드릴할 수 있습니다.</p>


  <p>오른쪽 아래 모서리에는 수행할 수 있는 몇 가지 작업이 있습니다. 이 경우 특정 요청이 느린 이유를 조사하려고 하므로 <strong>프로파일러 추적 </strong>단추를 클릭합니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/Performance-blade.png"><img alt="image" border="0" height="500" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/Performance-blade.png" style="border: 0px currentColor; border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="이미지" width="750"></a></p>


  <p>&nbsp;</p>


  <p>응답 시간이 가장 느린 호출을 알아보기 위해 95번째 백분위수 시간을 정렬했습니다. 최악의 경우 ShoppingCart 관련 요청이 실제로 느려질 수 있음을 발견했습니다. ShoppingCart는 고객이 체크 아웃하고 지불을 진행하는 곳입니다. 이 중요한 기능이 항상 응답적이고 안정적으로 작동하는지 확인해야 합니다. 그래서 당신은 무슨 일이 있었는지에 대해 자세히 알아보고 싶습니다.</p>


  <h3>성능 문제의 근본 원인 식별</h3>


  <p>POST ShoppingCart/RemoveFromCart 메서드의 행에 있는 <b>예제</b> 열 아이콘을 클릭하여 자세한 프로필 추적을 확인할 수 있으며, 가장 느린 최악의 응답 시간이 있습니다. 그러면 아래 그림과 같이 자세한 추적 보기 블레이드가 열립니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/c3cb48ea-6cfc-48fa-9f86-6cd45d4d1fe4.png"><img alt="LockContention" border="0" height="464" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/60d4bc21-48cc-4ffc-88b5-3f979d54860d.png" style="border: 0px currentColor; border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; display: inline; background-image: none;" title="LockContention" width="906"></a></p>


  <p>95번째 백분위수 예제 버킷에서 샘플을 선택합니다. 추적 보기에서 핫 경로&rdquo; 표시를 &ldquo;클릭하면 트리가 자동으로 확장되어 대부분의 시간이 소요된 호출 스택이 표시됩니다. 성능 향상을 위해 개입이 필요한 호출로 바로 이동되는 경우가 많습니다.</p>


  <p>이 예제에서는 음악 Store의 카트에서 제거 작업에 대한 핫 경로가 잠금 경합에 너무 많이 소비됩니다. Profiler는 이를 즉시 식별하고 잠금 경합 해결에 대한 지침을 안내합니다. 이는 프로파일러가 도움이 될 수 있는 많은 예제 중 하나입니다. 그 외에는 느린 알고리즘/함수, 외부 호출에 대한 차단된 시간, 캐싱이 필요한 데이터 호출, 잠금 경합 등이 있습니다.</p>


  <h2>가격 책정 및 제한 사항</h2>


  <p>&rsquo;추가 <b>비용 없이</b> 5일간의 보존 기간으로 애플리케이션 Insights 프로파일링 데이터가 포함되어 있음을 알려드리게 되어 기쁘게 생각합니다.</p>


  <ul>
   <li>하루에 수집된 최대 데이터는 10GB입니다.</li>
   <li>웹앱은 적어도 App Services의 기본 계층에 호스트되어야 합니다.</li>
  </ul>


  <h2>요약</h2>


  <p>&rsquo;프로덕션 애플리케이션에서&nbsp; 성능 문제를 더 잘 진단하고 해결하는 데 도움이 되도록 Application Insights Profiler의 생성 가용성&nbsp;에 대해 기쁘게 생각하고 있습니다.</p>


  <p>오늘 사용해 보세요! 이 게시물에 전자 메일을 <a href="mailto:serviceprofilerhelp@microsoft.com">serviceprofilerhelp@microsoft.com</a>보내거나 여기에 의견을 남기면 어떻게 생각하는지 알려주세요!</p>
