### YamlMime:Yaml
ms.openlocfilehash: 505ebc3078418cd4d81516962c42e9896b6473c0
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139898501"
Slug: article-tips-for-migrating-your-applications-to-the-cloud
Title: '문서: 애플리케이션을 클라우드로 마이그레이션하기 위한 팁'
Summary: '[이 문서는 SQL Azure 팀에서 제공했습니다.] 많은 기업 고객들이 Windows Azure에 관심을 가지고 있기 때문에 조지 휴이와 웨이드 웨그너는 Windows 개최하기로 결정했습니다...'
Content: <p>[이 문서는 SQL Azure 팀에서 제공했습니다.]</p><p>Windows Azure에서 표현된 많은 기업 고객의 관심 때문에 George Huey와 Wade Wegner는 Microsoft 기술 센터에서 Windows Azure Migration Labs 세트를 개최하기로 결정했습니다. 고객이 애플리케이션을 랩으로 가져와서 실제로 SQL Azure 마이그레이션하기 위한 것이었습니다. 이 프로세스를 통해 모든 고객은 웹 애플리케이션 및 SQL 데이터베이스를 Windows Azure 플랫폼으로 성공적으로 마이그레이션할 수 있었습니다. SQL Azure 마이그레이션 마법사를 사용했습니다. 이제 조지와 웨이드는 MSDN 잡지에서이 <a href="https://msdn.microsoft.com/en-us/magazine/ff872379.aspx">문서에서</a> 어떻게 되었는지 알려줄 것입니다.</p>  <p>여기에서 문서를 읽어 <a href="https://msdn.microsoft.com/en-us/magazine/ff872379.aspx">보세요</a>.</p>
