### YamlMime:Yaml
ms.openlocfilehash: 6cb6dbcc67a8e5dac553eed9270767f27509ea13
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139902775"
Slug: automating-vm-configuration-using-powershell-dsc-extension
Title: PowerShell DSC 확장을 사용하여 VM 구성 자동화
Summary: 이제 Azure SDK에서 PowerShell DSC 확장 및 관련 Azure PowerShell DSC cmdlet을 사용할 수 있습니다. 이제 Azure PowerShell DSC cmdlet을 사용하여 VM 에이전트 및 PowerShell DSC 확장을 사용하도록 설정하여 PowerShell DSC 구성을 업로드하고 Azure VM에 적용할 수 있습니다.
Content: >-
  4월<a href="https://www.buildwindows.com/">/ 빌드/</a>컨퍼런스에서 Jeffrey Snover는 Azure VM을 프로비전하고 <a href="https://blogs.msdn.com/b/powershell/archive/2014/04/03/configuring-an-azure-vm-using-powershell-dsc.aspx">PowerShell DSC(Desired State Configuration) 및 사용자 지정 스크립트 확장을</a> 사용하여 구성하는 방법을 설명했습니다. Azure VM 에이전트 및 확장은 Microsoft Azure 인프라 서비스의 일부이며 개요를 보려면 이전 블로그 <a href="https://azure.microsoft.com/blog/2014/04/11/vm-agent-and-extensions-part-1/">VM 에이전트 및 확장 1부</a>, <a href="https://azure.microsoft.com/blog/2014/04/15/vm-agent-and-extensions-part-2/">2부</a>를 확인하고 <a href="https://azure.microsoft.com/blog/2014/04/24/automating-vm-customization-tasks-using-custom-script-extension/">사용자 지정 스크립트 확장을 사용하여 VM 사용자 지정 작업을 자동화하는</a> 것이 좋습니다.


  PowerShell DSC에 익숙하지 않은 사용자를 위해 PowerShell DSC는 Cmdlet 및 PowerShell 환경을 활용하여 Windows 리소스의 자율적이고 멱등하고 투명한 배포, 구성 및 규정 준수를 가능하게 하는 선언적 모델입니다. DSC 사용에 대한 자세한 내용은 <a href="https://blogs.technet.com/b/privatecloud/archive/2014/04/25/desired-state-configuration-blog-series-part-1-learning-about-dsc.aspx">이 블로그 문서에서</a> 확인할 수 있습니다. PowerShell MVP <a href="https://onedrive.live.com/?cid=7F868AA697B937FE&amp;id=7F868AA697B937FE%21110">가 작성한 DSC Book</a> 을 읽을 수도 있습니다.


  오늘 PowerShell DSC 확장 및 <a href="https://azure.microsoft.com/en-us/downloads/">Azure SDK</a>의 일부인 관련 Azure PowerShell DSC cmdlet을 발표합니다. Azure PowerShell DSC cmdlet을 사용하여 VM 에이전트 및 PowerShell DSC 확장을 사용하도록 설정하여 PowerShell DSC 구성을 업로드하고 Azure VM에 적용할 수 있습니다. PowerShell DSC 확장은 VM에서 PowerShell DSC를 업데이트합니다. 필요한 버전이 아직 설치되지 않은 경우 PowerShell DSC를 호출하여 수신된 DSC 구성을 적용합니다.


  새 확장에 대한 자세한 개요는 이 항목 <a href="https://blogs.msdn.com/b/powershell/archive/2014/08/07/introducing-the-azure-powershell-dsc-desired-state-configuration-extension.aspx">에 대한 PowerShell 블로그</a> 를 참조하세요.


  귀하의 의견을 듣고 싶으므로 Twitter <a href="https://twitter.com/Azure">@Azure</a> 또는 <a href="https://feedback.azure.com/forums/34192--general-feedback">피드백 포럼</a>에서 의견을 알려주세요!
