### YamlMime:Yaml
ms.openlocfilehash: 2d5405c4f281e3e044dee2f06e5c03373f2d2bed
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139913192"
Slug: automation-and-configuration-of-your-azure-on-premises-and-hybrid-cloud-resources-at-scale
Title: 대규모 Azure, 온-프레미스 및 하이브리드 클라우드 리소스의 자동화 및 구성
Summary: 오늘날 고객이 하이브리드 클라우드에서 인프라 및 애플리케이션을 자동화하고 구성하는 것은 어려운 일입니다. 대규모로 잘 관리되는 환경을 유지 관리하려면 Windows 및 Linux 시스템 모두에 다음 기능이 필요합니다.
Content: >-
  <p>오늘날 고객이 하이브리드 클라우드에서 인프라 및 애플리케이션을 자동화하고 구성하는 것은 어려운 일입니다. 잘 관리되는 환경을 대규모로 유지 관리하려면 Windows 및 Linux 시스템 모두에 다음 기능이 필요합니다.</p>


  <ul>
   <li>인프라 및 애플리케이션의 구성을 적용하고 모니터링합니다.</li>
   <li>계획되지 않은 가동 중지 시간 없이 운영 체제 업데이트를 적용하는 시기와 방법을 제어합니다.</li>
   <li>경고를 해결하고, 백업 및 재해 복구를 오케스트레이션하고, 보안 문제를 자동으로 수정합니다.</li>
   <li>인벤토리를 수집하고 보고, 진단 및 포렌식에 대한 변경 내용을 추적합니다.</li>
   <li>Azure 및 온-프레미스 데이터 센터 모두에 대한 시스템 간 프로세스를 자동화합니다.</li>
   <li>안전한 중앙 집중식 리포지토리에서 모든 자동화 및 구성 자산을 관리합니다.</li>
  </ul>


  <p>이러한 요구 사항을 해결하기 위해 Azure Portal 내에서 새로운 자동화 및 구성 기능의 릴리스를 발표하게 되어 기쁩니다.</p>


  <h2>Azure 가상 머신 통합</h2>


  <p>이제 가상 머신과 통합하면 VM 블레이드에서 직접 Windows 및 Linux 컴퓨터에 대한 업데이트 관리, 인벤토리 및 변경 내용 추적이 가능합니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/556eb62e-2c57-41de-bc65-63697fee7b09.png"><img alt="UpdateManagementVMBlade" border="0" height="467" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/f19f0e07-a524-4d44-97b3-d04d276fcb25.png" style="border-left-width: 0px; border-right-width: 0px; background-image: none; border-bottom-width: 0px; float: none; padding-top: 0px; padding-left: 0px; margin-left: auto; display: block; padding-right: 0px; border-top-width: 0px; margin-right: auto" title="UpdateManagementVMBlade" width="983"></a></p>


  <p>업데이트 관리를 사용하면 항상 Windows 및 Linux에 대한 준수 상태를 알 수 있으며, 정의된 유지 관리 기간 내에 업데이트 설치를 오케스트레이션하는 예약된 배포를 만들 수 있습니다. 배포 중에 문제를 식별하는 자세한 문제 해결 로그와 함께 특정 업데이트를 제외하는 기능도 사용할 수 있습니다.</p>


  <p>VM 게스트 내 리소스의 인벤토리는 설치된 애플리케이션과 추적하려는 다른 구성 항목에 대한 가시성을 제공합니다. 풍부한 보고 및 검색을 통해 VM 내에서 구성된 모든 항목을 이해하는 데 도움이 되는 자세한 정보를 빠르게 찾을 수 있습니다.</p>


  <p>변경 내용 추적은 서비스, 디먼, 소프트웨어, 레지스트리 및 파일에서 변경 내용의 자동 수집을 제공하여 문제의 원인을 신속하게 식별하고 원치 않는 변경이 발생할 때 진단 및 경고를 사용하도록 설정합니다.</p>


  <h2>Azure 및 하이브리드 환경에서 대규모 관리</h2>


  <p>Azure 및 온-프레미스 리소스를 대규모로 관리할 수 있도록 이러한 기능이 Azure의 Automation &amp; 구성 서비스에도 추가되었습니다. 전체 환경에서 통합 보기를 얻을 수 있으며 Azure Portal에서 올바르게 구성, 업데이트 및 관리되도록 조치를 취할 수 있습니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/0ef71e94-8dd8-4595-ac55-3c4be976e09a.png"><img alt="ChangeTrackingAutomationAccount" border="0" height="588" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/78b4134b-6813-4b9d-a66f-560c1625eeec.png" style="border-left-width: 0px; border-right-width: 0px; background-image: none; border-bottom-width: 0px; float: none; padding-top: 0px; padding-left: 0px; margin-left: auto; display: block; padding-right: 0px; border-top-width: 0px; margin-right: auto" title="ChangeTrackingAutomationAccount" width="960"></a></p>


  <p>Azure Portal의 Automation &amp; 구성에는 PowerShell 원하는 상태 구성 서비스를 사용하는 구성 관리가 이미 있습니다. 이제 업데이트 관리를 수행하고, 인벤토리를 수집하고, 하이브리드 데이터 센터에서 실행되는 Azure VM 및 컴퓨터 모두에서 변경 내용을 추적하는 기능도 포함됩니다.</p>


  <p>또한 Linux 컴퓨터에 대한 하이브리드 작업자 지원을 추가하여 Linux 작업을 자동화하는 기능을 추가했다는 사실을 발표하게 되어 기쁘게 생각합니다. 즉, 현재 Windows 위해 수행할 수 있는 것처럼 일관된 방식으로 로컬 데이터 센터 및 Azure Linux VM의 작업을 오케스트레이션할 수 있습니다.</p>


  <p>또한 Python을 사용하여 Runbook을 작성하고 자동화 서비스 또는 Linux 또는 Windows Hybrid Worker에서 이러한 Python Runbook을 실행하도록 하는 기능도 발표합니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/54b7e7fe-06a0-4829-8cdb-0cbc2b05550d.png"><img alt="Python" border="0" height="543" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/9e6fb35b-9deb-494d-9fce-5852d56bbd03.png" style="border-left-width: 0px; border-right-width: 0px; background-image: none; border-bottom-width: 0px; float: none; padding-top: 0px; padding-left: 0px; margin-left: auto; display: block; padding-right: 0px; border-top-width: 0px; margin-right: auto" title="Python" width="974"></a></p>


  <p>이렇게 하면 가장 익숙한 자동화 언어를 사용할 수 있으며, 서비스 내의 PowerShell 및 그래픽 Runbook에 대한 기존 지원을 추가할 수 있습니다.</p>


  <h2>Automation &amp; 구성 기능에 대한 가격 책정</h2>


  <p>목표는 Azure 리소스 및 하이브리드 환경의 통합 관리를 사용하도록 설정하는 것입니다. Azure에서 이러한 새로운 기능이 추가되면서 이러한 기능을 사용하는 비용이 변경되어 필요한 만큼만 비용을 지불하게 됩니다.</p>


  <p>Azure 및 비 Azure 컴퓨터 모두에 대한 업데이트 관리 기능의 경우 Azure Log Analytics에 저장된 로그에 대해서만 비용을 지불합니다. 프로세스 자동화에는 매월 500분 무료가 포함되며, 그 후 각 Runbook 작업 분에 대한 요금이 부과됩니다. 구성 관리에는 매월 5개의 하이브리드 노드가 무료로 포함되며 각 비 Azure 컴퓨터에 대해 시간당 요금이 부과됩니다. Azure Log Analytics에 저장된 로그에 대한 비용을 지불합니다. 이러한 기능에 대한 비용에 대해 자세히 알아보려면 <a href="https://azure.microsoft.com/en-us/pricing/details/automation/" target="_blank">Automation 가격 책정 페이지를</a> 검토하세요.</p>


  <p>Automation &amp; 구성에서 새 기능을 시작하려면 대규모 작업을 수행할 때 가상 머신 블레이드 또는 Automation 계정을 사용합니다.</p>


  <p><a href="https://docs.microsoft.com/en-us/azure/automation/" target="_blank">Azure Automation &amp; 구성 설명서</a> 페이지의 기존 기능과 새로운 기능에 대해 알아보고 <a href="https://twitter.com/AzureAutomation" target="_blank">Twitter</a>에서 Azure Automation을 따릅니다.</p>
