### YamlMime:Yaml
ms.openlocfilehash: 098795fe99aebb368b4c1b5be7da62c5ec29437e
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139911411"
Slug: automating-industrial-iot-security
Title: 산업용 IoT 보안 자동화
Summary: 산업용 IoT는 가장 큰 IoT 기회입니다. Microsoft에서는 연결된 팩터리라는 오픈 소스 Azure IoT Suite 솔루션에 편리하게 번들로 제공되고 1년 전 HMI 2017에서 출시한 산업용 IoT 클라우드 플랫폼 참조 아키텍처를 제공하여 이 수직을 제공합니다.
Content: >-
  <p>산업용 IoT는 <a href="https://www.mckinsey.com/business-functions/digital-mckinsey/our-insights/the-internet-of-things-the-value-of-digitizing-the-physical-world" target="_blank">가장 큰 IoT 기회입니다</a>. Microsoft에서는 연결된 <strong>팩터</strong>리라는 오픈 소스 <a href="https://www.azureiotsuite.com/" target="_blank">Azure IoT Suite</a> 솔루션에 편리하게 번들로 제공되어 1년 전 HMI 2017에서 출시한<strong> 산업용 IoT 클라우드 플랫폼 참조 아키텍처</strong>를 제공하여 이 수직을 제공합니다.</p>


  <p>그 이후, 우리는 OPC UA 산업 상호 운용성 표준을 개발하는 비영리 단체인 OPC Foundation과의 협력을 계속하고 <a href="https://github.com/opcfoundation" target="_blank">Github 페이지에</a> 많은 새로운 오픈 소스 기여를 추가하여 오픈 소스 소프트웨어의 가장 큰 기여자로서 OPC Foundation에 10 배의 요인으로 리드를 확장했습니다. 또한 규정 준수를 위해 오픈 소스 플랫폼 간 <a href="https://github.com/OPCFoundation/UA-.NETStandard" target="_blank">.Net Standard OPC UA 참조 스택</a>을 성공적으로 <a href="https://opcfoundation.org/certification/how-to-certify/" target="_blank">인증</a>했습니다. 연결된 팩터리는 내부적으로 이 스택을 사용하므로 오픈 소스 OPC UA 여정에서 중요한 단계였습니다. 또한 최근 발표된 <a href="https://azure.microsoft.com/en-us/blog/azure-iot-hub-is-driving-down-the-cost-of-iot/" target="_blank">Azure IoT Hub의 새로운 가격 책정 구조</a>로 인해 연결된 팩터리의 월별 Azure 사용 비용을 줄일 수 있었습니다.</p>


  <p>Connected Factory는 머신 빌더와 제조업체 모두에서 매우 인기가 있지만, 실제 머신을 연결하는 것은 여전히 어렵고 동시에 이러한 컴퓨터를 IoT 애플리케이션에 안전하게 보호할 수 있다는 소식을 수시로 듣습니다. 따라서 연결 및 보안을 완전히 자동으로 만드는 연결된 팩터리에 몇 가지 새로운 모듈과 서비스를 추가했습니다. 우리는 우리가 올해 HMI에서 이러한 새로운 모듈과 서비스를 출시하는 것을 발표하게 된 것을 기쁘게 생각합니다.</p>


  <p>자세한 내용은 다음을 추가했습니다.</p>


  <ul>
   <li><strong>자동 머신/자산 검색</strong> Azure IoT Edge 모듈인 <strong>OPC Twin</strong>은 OT 네트워크에서 OPC UA 서버를 검색하고 <strong>Azure IoT Hub에 자동으로 등록합니다</strong>. 또한 AZURE에서 실행되는 도우미 OPC 쌍 마이크로 서비스를 사용하여 클라우드에서 OPC 쌍을 제어하고 관리할 수 있습니다.</li>
   <li>또한 OPC 쌍은 OPC UA 메타데이터가 포함된 각 OPC UA 서버에 대한 디바이스 쌍을 만듭니다. 이렇게 하면 <strong>네이티브 IoT Hub API를 사용하여 클라우드의 각 개별 OPC UA 서버와 상호 작용</strong>할 수 있습니다.</li>
   <li>또한 OPC 쌍은 각 개별 OPC UA 서버에 대해 <strong>자동 보안 평가를</strong> 수행하고 사용자에게 보안 약점을 강조 표시합니다.</li>
   <li>또한 IoT Edge 모듈로 다시 패키지된 클라우드 지원 OPC UA <strong>글로벌 검색 서버를</strong> 추가했습니다. <strong>OPC 서버의 자동 보안 구성</strong>을 처리하고 OPC 쌍과 마찬가지로 클라우드에서 제어 및 관리하기 위한 Azure 기반 마이크로 서비스가 함께 있습니다. 마이크로 서비스는 Azure Key Vault와 상호 작용하며 <strong>GDS 자격</strong> 증명 모음이라고도 합니다. GDS 자격 증명 모음은 OPC UA에서 사용하는 X.509 인증서 및 프라이빗 키를 안전하게 저장하고 관리하기 위해 Key Vault를 사용합니다. 운영자는 클라우드 기반 인터페이스를 통해 처음으로 전역 규모로 OPC UA 서버의 보안 설정을 관리할 수 있으며, 더 이상 각 작업 현장의 각 OPC UA 클라이언트 및 서버에 대해 OPC UA 인증서를 수동으로 교환할 필요가 없습니다. 따라서 GDS는 세계&rsquo; 최초의 진정한 글로벌 GDS를 나타냅니다.</li>
  </ul>


  <p>말할 필요도 없이, 우리는 곧 GitHub 연결된 팩터리에서 위의 모든 오픈 소스 통합<a href="https://github.com/Azure/azure-iot-connected-factory" target="_blank">을</a> 제공 할 것입니다.</p>


  <p>OPC Foundation과 Platform Industry 4.0 모두 OPC UA 서버의 보안 관리를 위해 글로벌 검색 서버를 사용하는 것이 좋습니다. 두 조직 모두 세부 정보를 설명하는 백서(<a href="https://opcfoundation.org/security/" target="_blank">1</a>)(<a href="https://www.plattform-i40.de/I40/Redaktion/DE/Downloads/Publikation/hm-2018-opc.html" target="_blank">2</a>)를 발표했습니다.</p>


  <p>다음은 새로운 연결된 팩터리 아키텍처의 다이어그램입니다.<br>

  &nbsp; <a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/24a5a418-5d3c-4426-b044-c225537ed93b.png"><img alt="clip_image002[8]" border="0" height="457" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/80e503f0-7646-4428-bddf-8e5a575b8af1.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="clip_image002[8]" width="756"></a></p>


  <p>나는 또한 우리가 OPC 재단에 오픈 소스 글로벌 검색 서버를 기여했다<a href="https://azure.microsoft.com/en-us/blog/simplifying-opc-ua-security-for-everyone/" target="_blank">는 우리의 발표</a>에 대한 응답으로 작성 실시간 자동화에서 존 리날디에 의해 <a href="https://www.automation.com/automation-news/article/how-microsoft-is-leveraging-opc-ua-to-get-an-irreplaceable-position-in-your-factory" target="_blank">기사에서</a> 인용하고 싶습니다 :</p>


  <p><em>글로벌 검색 서버는 채택의 모든 차이를 만듭니다. GDS 구현은 OPC UA에 부족했으며 아키텍처의 약점 중 하나입니다. Microsoft 제품은 OPC UA 기술을 크게 개선하고 공장 현장의 Microsofts&rsquo; 위치를 공고히 합니다. 전부는 아니지만 대부분의 공장 현장 구현은 인증서 관리를 처리하기 위해 GDS가 필요하며 이는 거의 모든 OPC UA 설치에 Microsoft가 있음을 의미합니다.</em></p>


  <p>하지만 기다려, 더 있다&rsquo;!</p>


  <p>또한 OPC UA의 기능으로 <a href="https://www.microsoft.com/en-us/iot-central/" target="_blank">Azure IoT Central</a>을 확장하여 IoT Central 고객에게도 온-프레미스 머신에 대한 비관입 연결을 가능하게 했다는 사실을 자랑스럽게 생각합니다.</p>


  <p>여기서 볼 수 있듯이, Microsoft는 제조에서 디지털 변환 과정의 모든 단계에서 적합한 산업용 IoT Cloud Platform을 지원하기 위해 <a href="https://blogs.microsoft.com/iot/2018/04/04/microsoft-will-invest-5-billion-in-iot-heres-why/" target="_blank">계속 투자</a> 하고 있습니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/adafb35a-fd0f-4d55-b06b-bd3767d715d7.png"><img alt="yes" border="0" height="779" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/6dd1e60e-efeb-4047-a284-7070fc4f8ffa.png" style="margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="예" width="1349"></a></p>


  <p>우리는 당신이 그것을 사용하여 구축 할 새로운 제품을보고 기다릴 수 없어&rsquo;!</p>
