### YamlMime:Yaml
ms.openlocfilehash: 20ea0fd45c76d63eff73f4250fce6c9c1ffef0f8
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139913185"
Slug: availability-monitoring-with-application-insights
Title: 엔드포인트 모니터링에서 애플리케이션 Insights 가용성 테스트로 이동
Summary: 새 Azure Portal에서 애플리케이션 Insights 사용한 가용성 모니터링은 클래식 포털의 엔드포인트 모니터링을 대체합니다. 클래식 포털로 가지 않고 관리할 수 있도록 새 포털에서 동등한 테스트를 만들었습니다.
Content: >-
  <p>Azure 웹앱에 <a href="https://blogs.msdn.microsoft.com/mast/2013/03/03/windows-azure-portal-update-configure-web-endpoint-status-monitoring-preview/">엔드포인트 모니터링을</a> 사용합니까? <b>2016년 4월 4</b>일,&rsquo; 새롭고 더 강력한 <a href="https://azure.microsoft.com/documentation/articles/app-insights-monitor-web-app-availability/">가용성 테스트</a>로 대체했습니다. 새 테스트를 이미 만들었습니다. 그러나 2016년 4월 4일에 전환할 때까지 비활성화됩니다.</p>


  <p>새 테스트를 편집하고 원하는 경우 스위치를 직접 수행할 수 있습니다. 특히 웹에서 구독 소유자로 설정했으므로&rsquo; 알림 전자 메일 주소를 확인해야 합니다. Azure Portal의 <i>Default-ApplicationInsights-CentralUS</i> 리소스 그룹에서 테스트를 찾을&#39;있습니다.<a href="https://portal.azure.com/"></a></p>


  <p>이 스위치&nbsp;에 대한 자세한 내용은<a href="https://azure.microsoft.com/documentation/articles/app-insights-migrate-azure-endpoint-tests/">Azure 설명서를 참조하세요</a>.</p>
