### YamlMime:Yaml
ms.openlocfilehash: 23ad707eaad06a887fb1bc0850b6d5403043d542
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139902211"
Slug: azure-stream-analytics-and-documentdb-for-your-iot-application
Title: IoT 애플리케이션용 Azure Stream Analytics 및 DocumentDB
Summary: 사물 인터넷이 기업에서 변경 에이전트로 부상함에 따라 올바른 도구를 사용하는 것이 그 어느 때보다 중요합니다. Microsoft는 Azure IoT Suite의 최근 출시 외에도 더 빠른 구성을 위해 Azure Stream Analytics와 Azure DocumentDB 간의 통합을 향상시키고 출시 시간을 늘렸습니다.
Content: >-
  <p>Microsoft&rsquo;의 신뢰할 수 있는 Azure 클라우드 플랫폼은 전 세계 기업에서 데이터의 기능을 활용하고 실행 가능한 인텔리전스를 만드는 데 사용됩니다. 사물 인터넷이 엔터프라이즈의 변경 에이전트로 부상함에 따라 IoT 솔루션을 쉽게 개발하고 배포할 수 있는 적절한 도구를 보유하는 것이 그 어느 때보다 중요합니다.</p>


  <p>Microsoft는 Azure IoT <a href="https://blogs.microsoft.com/iot/2015/09/29/azure-iot-suite-now-available/">Suite</a>의 최근 출시 외에도 더 빠른 구성&mdash;을 위해 <a href="https://azure.microsoft.com/en-us/services/stream-analytics/">Azure Stream Analytics</a>와 <a href="https://azure.microsoft.com/en-us/services/documentdb/">Azure DocumentDB</a> 간의 통합을 향상하고 출시 시간을 단축했습니다. Stream Analytics 작업은 이제 처리된 데이터를 DocumentDB에 쓸 수 있으므로 비정형 JSON 데이터에 대한 보관 및 짧은 대기 시간 쿼리를 사용할 수 있습니다. Stream Analytics 데이터를 DocumentDB에 출력하는 기능은 매우 요청되었으며 Azure 피드백 포럼에서 <a href="https://feedback.azure.com/forums/270577-azure-stream-analytics/suggestions/7114244-can-we-add-an-output-to-documentdb">가장 많은 투표를 받은 아이디어</a> 였습니다.</p>


  <p>이 블로그 게시물에서는 스트리밍 데이터 위에 이러한 두 서비스를 사용할 경우의 이점을 강조하고 함께 구성하는 방법을 살펴봅니다.</p>


  <h2>규모 및 성능을 위해 빌드</h2>


  <p>스트림 처리 솔루션을 사용하는 많은 고객은 처리된 데이터에 대해 유연하고 짧은 대기 시간 쿼리를 실행할 수 있어야 합니다. 예를 들어 유료 부스 시나리오에서는 수백만 대의 자동차가 매분마다 유료 스테이션을 가로지릅니다.&nbsp; 이러한 애플리케이션에는 여러 유료 부스의 이벤트를 병렬로 처리하고 유지할 수 있는 고도로 확장된 시나리오가 필요합니다.</p>


  <p>DocumentDB는 데이터가 스키마 또는 변환 없이 JSON에 고유하게 저장되므로 Azure Stream Analytics와 자연스럽고 원활하게 통합됩니다. DocumentDBs&rsquo; <a href="https://azure.microsoft.com/documentation/articles/documentdb-indexing/">자동 인덱싱</a> 을 대규모로 사용하면 스키마 및 보조 인덱스 없이 빠르게 진화하는 IoT 데이터에 대한 관계형, 계층적 및 공간 쿼리를 수행할 수 있습니다. 여기에서 DocumentDBs&rsquo; 쿼리 기능에 대해 자세히 알아볼 수 <a href="https://azure.microsoft.com/en-us/documentation/articles/documentdb-sql-query/">있습니다</a>.</p>


  <p>Stream Analytics를 사용하면 DocumentDB 컬렉션 목록을 지정할 수 있으며, 선택한 PartitionKey 값을 기반으로 들어오는 데이터를 지정된 컬렉션으로 자동으로 <a href="https://azure.microsoft.com/documentation/articles/documentdb-sharding/#hash-partition-resolver">분할</a> 합니다. 이를 통해 수평적으로 확장하여 대량의 데이터를 수집하고 인덱싱할 수 있습니다. 또한 개별 DocumentDB 컬렉션의 <a href="https://azure.microsoft.com/en-us/documentation/articles/documentdb-performance-levels/">성능 수준을</a> 구성하고 DocumentDB <a href="https://azure.microsoft.com/documentation/articles/documentdb-consistency-levels/">일관성 수준</a> 및 <a href="https://azure.microsoft.com/documentation/articles/documentdb-indexing-policies">인덱싱 정책을 수정하여</a> 세분화된 성능 절충을 수행할 수 있습니다.</p>


  <h2>여러 쓰기 모드</h2>


  <p>Stream Analytics는 DocumentDB에 쓰는 두 가지 모드인 upsert 및 추가를 지원합니다.</p>


  <p>데이터에 ID&rdquo; 속성이 &ldquo;포함되어 있으면 DocumentDB에 쓸 때 Stream Analytics에서 문서를 <a href="https://azure.microsoft.com/blog/documentdb-adds-upsert/">upsert</a>(삽입 또는 바꾸기)합니다. 예를 들어 이는 두 시나리오 모두에서 차량의 최신 활동 데이터를 업데이트할 때 유용합니다.</p>


  <p>&ldquo;ID&rdquo; 속성을 사용할 수 없거나 고유 식별자로 설정하면 Stream Analytics에서 새 문서를 만듭니다. 이는 차량&rsquo; 활동 데이터의 전체 기록을 보관하는 데 유용합니다.</p>


  <h2>DocumentDB 출력을 설정하는 방법</h2>


  <ol>
   <li><a href="https://portal.azure.com/">Azure Preview 포털</a> 또는 <a href="https://msft.sts.microsoft.com/adfs/ls/?wauth=http%3a%2f%2fschemas.microsoft.com%2fclaims%2fmultipleauthn&amp;username=v-madfre%40microsoft.com&amp;wa=wsignin1.0&amp;wtrealm=urn%3afederation%3aMicrosoftOnline&amp;wctx=estsredirect%3d2%26estsrequest%3drQIIAYWQz0rDQBCH3awU66UiWPAiFQJCYZM02TZJT_65edE3KJvsxAbZ3bDZWuhj9Ogb2KMn6SP01LMnKR48-wQ2lgriwd_hm2HmMB_Txh2n07e973QCUpUN0m23zXWt63lRGN8ifbh_8H56Nt5rW1dPb82Fc3liP6KdGWoNjSnKvusKJtkdOONccjUu2WSkwUmVcF8QWiL0gdDMsn0IfRYmlEQJzQgNWUySHosIZdzLepEfxEn8ajVuLkZm6FdQOp_A6s_k06pnSotBoUozxQ3Fqq1TMVUcpvhIFSBzniopITVOzo26BznD9m9ZAdKsHfWPtSPBuM-4tvYWSs6xHdIoAwgY6VK61vTDgEScU5LFLPV6WcI4BAt8PCpBD3JRgC6VZCZXsrUxWOHmAxGMZxrORZ5qVaqsOimWu2he__d3Xw2">Azure 관리 포털</a>에서 Stream Analytics 작업의 출력으로 이동하고 추가를 클릭합니다.<br>
   <br>
   <a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/210a5624-8e6d-4e1a-a3af-f2c950a89ba2.jpg"><img alt="Outputs_Stream Analytics" border="0" height="480" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/8ab19791-12d3-462e-b07e-18918e6488d3.jpg" style="border: 0px currentColor; border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; display: inline; background-image: none;" title="Outputs_Stream 분석" width="610"></a><br>
  &nbsp;</li>
   <li>원본 유형으로 DocumentDB를 선택하고 필요한 연결 및 구성 정보를 제공합니다. 이러한 각 필드에 대한 세부 정보는 <a href="https://azure.microsoft.com/en-us/documentation/articles/stream-analytics-define-outputs/">Stream Analytics 출력 이해</a>에서 찾을 수 있습니다.<br>
   <br>
   <a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/52ef566b-b015-4900-ab05-f949d31c931d.jpg"><img alt="DocumentDB_Source Type" border="0" height="480" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/3610c5be-602c-41e1-9fbf-f4f3b1a6e4b7.jpg" style="border: 0px currentColor; border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; display: inline; background-image: none;" title="DocumentDB_Source 형식" width="164"></a><br>
  &nbsp;</li>
   <li>만들기 단추를 클릭하여 입력 설정을 완료합니다.</li>
  </ol>


  <p>IoT Suite에서 더 많은 기능 및 업데이트를 계속 확인하세요. <a href="https://social.msdn.microsoft.com/Forums/en-US/home?forum=AzureStreamAnalytics">Stream Analytics 포럼</a>과 <a href="https://feedback.azure.com/forums/270577-azure-stream-analytics">Azure 피드백 포럼</a>에서 Stream Analytics와 DocumentDB 간의 통합에 대한 피드백을 기다리고 있습니다.</p>
