### YamlMime:Yaml
ms.openlocfilehash: 0918a9e854177d0c1da9875e05b7fd4113f8d363
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139905605"
Slug: azure-security-center-now-generally-available-proven-to-improve-security
Title: 이제 일반 공급된 Azure Security Center는 보안을 개선하는 것으로 입증되었습니다.
Summary: 최신 도구인 Azure Security Center를 일반 공급한다는 사실을 알려드릴 수 있게 되어 기쁘게 생각합니다.
Content: >-
  <p>사이버 보안의 가시성과 제어를 유지하는 것은 끊임없는 과제입니다. 그리고 공격자가 혁신함에 따라 이를 따라잡는 것은 압도적인 작업이 될 수 있습니다. 조직에서 위반을 감지하는 데 평균적으로 200일 이상이 걸립니다. 위반의 평균 비용은 수백만 달러에 도달, 지분은 더 높은 적이있다.</p>


  <p>Microsoft에서는 클라우드 서비스를 대규모로 운영함으로써 얻은 위협 인텔리전스에 대한 Microsoft&rsquo;의 고유한 관점을 활용하는 새로운 접근 방식이 필요하다고&mdash; 생각합니다. 새로운 접근 방식은 보안을 플랫폼에 통합하고 파트너의 솔루션을 통합합니다. 우리는 이러한 모든 분야에서 우리의 <a href="https://aka.ms/I1stiu">역량을</a> 발전시키기 위해 매년 10억 달러 이상을 연구 개발에 투자합니다.</p>


  <p>Azure에서 이러한 투자는 물리적, 네트워크 및 운영 보안의 견고한 기반을 구축하는 데 도움이 됩니다. Microsoft는 업계 모범 사례에 기반을 두며 광범위한 규정 준수 인증을 통해 역량을 입증합니다.</p>


  <p>또한 Azure에 배포하는 리소스에 대한 보안 목표를 달성하는 데 도움이 되는 도구에도 투자합니다. 오늘 최신 도구인 Azure Security Center를 일반 공급한다고 발표하게 되어 기쁘게 생각합니다.</p>


  <p>미리 보기 기간 동안 Azure Security Center는 Chronodrive, Jet.com 및 Metro Bank와 같은 고객이 Azure 리소스의 보안 상태를 파악하고, 클라우드 보안 정책을 제어하고, 보안 구성을 모니터링하면서 활성 공격을 감지하고 대응하도록 지원했습니다.</p>


  <p>Azure Security Center는 리소스의 보안 상태를 개선하기 위해 고객에게 500,000개 이상의 권장 사항을 제공했습니다. 기계 학습 및 Microsofts&rsquo;의 방대한 글로벌 위협 인텔리전스를 포함한 고급 분석을 사용하여 실행 가능한 경고를 제공하고 검색 및 응답 시간을 크게 줄인 매월 &ndash; 140,000개 이상의 위협을 감지했습니다.</p>


  <p>추가 보안 제어를 권장&nbsp;하는 시나리오에서 Azure Security Center를 사용하면 파트너의 솔루션뿐만 아니라 Azure에 기본 제공되는 컨트롤을 간단하게 찾고, 배포하고, 구성할 수 있습니다. Barracuda, Check Point, F5, Fortinet, Imperva 및 추세 Micro의 솔루션은 이미 제공됩니다. Cisco 및&nbsp;Qualys의 솔루션은 앞으로 몇 주 안에 제공될 예정입니다. 또한 고객이 인프라를 보호하기 위해 다양한 보안 도구를 사용하고 있다는 것을 알고 있기 때문에 에코시스템은 계속 성장할 것입니다.</p>


  <h3>새로운 기능&rsquo;</h3>


  <p>또한 다음과 같은 여러 가지 새로운 기능이 추가되었습니다.</p>


  <ul>
      <li><strong>로그 통합.</strong> Azure용 새 <a href="https://azure.microsoft.com/en-us/documentation/articles/security-center-integrating-alerts-with-log-integration/">커넥터</a> 는 Azure Security Center 경고를 비롯한 보안 데이터를 HP ArcSight, IBMQradar&nbsp;, Splunk 등의 보안 정보 및 이벤트 관리 솔루션으로 가져오는 프로세스를 간소화합니다.</li>
      <li><strong>더 많은 Azure 리소스 종류에 대한 지원.</strong> Security Center는 이제 시스템 업데이트 상태, OS 구성 및 디스크 암호화를 포함하여 RedHat 및 더 많은 Linux <a href="https://azure.microsoft.com/en-us/documentation/articles/security-center-faq/#virtual-machines">배포판</a>의 보안을 보다 광범위하게 모니터링할 수 있습니다. Cloud Services(웹 및 작업자 역할)의 보안 상태를 모니터링하고 오래된 OS 인스턴스를 <a href="https://azure.microsoft.com/en-us/documentation/articles/security-center-update-os-version/">업데이트</a>할 것을 권장할 수도 있습니다.</li>
      <li><strong>전자 메일 알림.</strong> 새로운 높은 심각도 보안 경고가 감지되면 이메일 알림을 사용하여 위협에 더 빠르게 대응합니다.</li>
      <li><strong>새 검색.</strong> Security Center는 이제 횡적 이동, 나가는 공격 및 악성 스크립트를 감지하는 기능을 개선했으며, 연구원들은 지속적으로 새로운 <a href="https://azure.microsoft.com/en-us/documentation/articles/security-center-detection-capabilities/">기능을 추가하고 있습니다</a>.</li>
      <li><strong>보안 인시던트.</strong> 분석을 사용하여 고유한 보안 경고 간에 점을 연결함으로써 Security Center는 이제 공격 캠페인과 모든 관련 경고에 대한 <a href="https://azure.microsoft.com/en-us/documentation/articles/security-center-incident/">단일 보기를</a> 제공하여 공격자가 수행한 작업과 영향을 받은 리소스를 빠르게 이해할 수 있습니다.</li>
      <li><strong>REST API.</strong> 기존 변경 관리 또는 보안 운영 시스템과 통합하려는 고객을 위해 <a href="https://msdn.microsoft.com/en-US/library/mt704034(Azure.100).aspx">REST API 설명서를</a> 게시했습니다.</li>
      <li><strong>통합 취약성 평가.</strong> 앞으로 몇 주 안에 고객은 몇 번의 클릭만으로 Qualys와 같은 파트너의 취약성 평가 솔루션을 배포할 수 있습니다.</li>
  </ul>


  <p>다른 퍼블릭 클라우드는 Azure Security Center에서 제공하는 지속적인 모니터링을 제공하지 않습니다. 또한 Microsoft가 광범위한 엔터프라이즈 및 소비자 제품 및 서비스에서 수집할 수 있는 위협 인텔리전스의 폭과 다양성을 일치시킬 수 있는 공급업체는 없습니다. 해당 인텔리전스가 작동하도록 하려면 오늘 Azure Security Center를 시작하세요.</p>


  <h3>자세한 정보</h3>


  <ul>
      <li><a href="https://azure.microsoft.com/services/security-center/">Azure Security Center</a></li>
      <li><a href="https://azure.microsoft.com/pricing/details/security-center/">가격 정보</a></li>
      <li><a href="https://azure.microsoft.com/en-us/documentation/articles/security-center-data-security/">개인 정보</a></li>
  </ul>
