### YamlMime:Yaml
ms.openlocfilehash: f7f346fad72717efe5aeb91b63ce3d4911cb159d
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139901796"
Slug: azure-managed-application-in-azure-marketplace-under-the-hood
Title: 'Azure Marketplace의 Azure Managed Application: 내부적으로'
Summary: Azure Managed Applications를 사용하면 MSP(관리 서비스 공급자) 및 ISV(독립 소프트웨어 공급업체) 파트너 및 엔터프라이즈 IT 팀이 Azure Marketplace를 통해 또는 특정 최종 고객의 엔터프라이즈 서비스 카탈로그를 통해 사용할 수 있는 완전 관리형 턴키 클라우드 솔루션을 제공할 수 있습니다. 이 블로그에서는 Azure Marketplace 시나리오에 초점을 맞추고 있습니다.
Content: >-
  <p>Azure Managed Applications를 사용하면 MSP(Managed Service Provider) 및 ISV(Independent Software Vendor) 파트너 및 엔터프라이즈 IT 팀이 Azure Marketplace를 통해 또는 특정 최종 고객의 엔터프라이즈 서비스 카탈로그를 통해 사용할 수 있는 완전 관리형 턴키 클라우드 솔루션을 제공할 수 있습니다. 이 블로그에서는&rsquo; Azure Marketplace 시나리오에 중점을 두고 있습니다. 관리되는 애플리케이션 서비스 카탈로그에 대한 자세한 내용은 여기를 참조하세요. 고객은 자신의 구독에서 관리되는 애플리케이션을 신속하게 배포하고 수명 주기 동안 유지 관리 작업 및 지원을 위해 파트너에 의존할 수 있습니다. </p>


  <p>Azure Managed Applications는 서비스 및 운영 지원을 Azure 솔루션에 연결하여 인프라 및 소프트웨어 이상으로 확장할 수 있는 추가 파트너 기회입니다. 관리되는 애플리케이션을 사용하는 파트너는 Azure Marketplace에서 게시할 때 Azure&rsquo; 청구 시스템을 사용하여 고객에게 직접 송장을 작성하고 Azure Resource Manager 템플릿을 사용하여 배포된 애플리케이션의 수명 주기를 지원할 수 있습니다. 이 모든 것을 통해 고객에게 더욱 풍부한 클라우드 에코시스템을 제공하고 파트너에게 새로운 기회를 제공할 수 있습니다.</p>


  <h2>배포 채널로서의 Azure Marketplace</h2>


  <p>이제 관리되는 애플리케이션을 게시하고 Azure Portal의 Azure Marketplace에서 사용할 수 있습니다. 파트너가 게시한 후에는 Azure 구독을 사용하는 모든 상용 고객에게 사용할 수 있습니다. 이를 통해 MSP 및 ISV 파트너는 더 넓은 시장에 솔루션을 마케팅할 수 있습니다. 파트너는 고객이 배포한 후에 애플리케이션을 유지 관리, 서비스 및 업그레이드할 책임이 있습니다. 고객은 심층적인 시간과 리소스 투자 없이 복잡한 솔루션을 실행할 수 있으므로 이점을 누릴 수 있습니다.</p>


  <h3>게시</h3>


  <p>파트너는 Cloud 파트너 포털을 사용하여 관리되는 애플리케이션을 Azure Marketplace에 게시합니다. 필요한 주요 구성 요소는 a) 프로비전될 리소스를 설명하는 템플릿 파일과 b) 이러한 리소스를 프로비전하는 데 필요한 입력이 포털에 표시되는 방법을 설명하는 UI 정의 파일입니다. 필요한 파일은 .zip 파일로 패키지화되고 게시 포털을 통해 업로드됩니다. 다음은 게시 포털의 스크린샷이며 <a href="https://docs.microsoft.com/en-us/azure/managed-applications/publish-marketplace-app">, 자세한 지침은 여기에서 확인할 수 있습니다</a>.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/2c63f92f-70eb-43fb-94f3-9ed2d23a5219.png"><img alt="publishingPortal" border="0" height="472" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/c7f67490-71c3-4e6d-b2d9-eaa0858f0869.png" style="border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; display: inline; background-image: none;" title="publishingPortal" width="940"></a></p>


  <h3>가격 책정</h3>


  <p>관리되는 애플리케이션을 Azure Marketplace 또는 고객 서비스 카탈로그에 게시하는 파트너는 추가 요금이 부과되지 않습니다. 파트너는 게시하기 전에 <a href="https://docs.microsoft.com/en-us/azure/managed-applications/publish-marketplace-app#set-up-your-account-for-publishing-portal">Microsoft 개발자 센터 계정이</a> 필요합니다. 관리되는 애플리케이션의 게시자는 마켓플레이스에서 제공하는 솔루션&rsquo;과 고정 월별 비용을 연결할 수 있습니다. 이는 추가 비용이 고객&rsquo; Azure 청구서에 별도의 품목으로 표시됩니다. 기존 Azure Marketplace 파트너 수익 모델이 적용됩니다.</p>


  <p>고객은 일반 청구 구문을 사용하여 관리되는 애플리케이션의 일부인 Azure 리소스 사용에 대한 요금이 청구됩니다. 예를 들어 관리되는 애플리케이션의 일부로 가상 머신이 고객 구독에 프로비전되면 고객에게 가상 머신 사용량에 대한 요금이 청구됩니다. 마찬가지로, 수명 주기 작업에 대해 고객에게 요금을 부과하는 수수료 파트너는 고객&rsquo; Azure 청구서에 새 품목으로 표시됩니다.</p>


  <h3>권한 부여</h3>


  <p>관리되는 애플리케이션의 일부인 리소스가 포함된 리소스 그룹이 고객에 대해 잠겨&rdquo; 있습니다&ldquo;. 고객은 이 리소스 그룹의 리소스에 대한 읽기 전용 액세스 권한이 있습니다. 따라서 고객은 관리되는 애플리케이션의 일부인 리소스를 실수로 삭제하거나 업데이트할 수 없습니다. 그러나 관리되는 애플리케이션의 게시자는 고객&rsquo; 테넌트에서 애플리케이션을 유지 관리, 서비스 및 업그레이드할 수 있는 필요한 권한을 얻습니다. 이러한 권한은 일반적인 <a href="https://docs.microsoft.com/en-us/azure/active-directory/role-based-access-built-in-roles">Azure RBAC 역할에</a> 의해 정의됩니다.&nbsp; 이에 대한 자세한 내용은 추가 리소스 섹션에서 확인할 수 있습니다.</p>


  <h3>지원되는 지역</h3>


  <p>관리되는 애플리케이션 서비스는 전역적으로 사용 가능한 모든 Azure 지역에서 사용할 수 있습니다.</p>


  <h2>주요 시작 파트너</h2>


  <p>관리되는 애플리케이션에서 Cisco, OpsLogix 및 Xcalar와 매우 긴밀하게 협력한 것을 공유하게 되어 기쁩니다. 이러한 파트너의 제품은 이미 라이브 상태이며 마켓플레이스에 게시되어 있으며 사용할 수 있습니다. 다음은 이러한 파트너의 제품 세부 정보입니다.</p>


  <h2>OpsLogix</h2>


  <p>Azure Marketplace에서 &ldquo;OpsLogix OMS Oracle 솔루션&rdquo; 관리형 애플리케이션을 제공하고 있습니다. 이를 통해 OpsLogix OMS Oracle 솔루션 관리형 애플리케이션을 사용하여 Oracle 모니터링 및 감사 데이터를 OMS에 삽입하여 Oracle 환경을 전체적으로 볼 수 있습니다. OpsLogix OMS Oracle 솔루션은 성능 및 가용성 메트릭을 제공할 뿐만 아니라 Oracle 환경을 감사하여 몇 시간 내에 규정을 준수할 수 있도록 합니다.</p>


  <h2>Xcalar&nbsp;</h2>


  <p>Xcalar Data Platform은 단순성, 속도 및 규모로 실행 가능한 인사이트를 제공하는 개방적이고 확장 가능한 분석 플랫폼입니다. 특허 받은 기술은 데이터 준비, 데이터 과학, 데이터 웨어하우징 및 임시 분석을 비롯한 완전한 분석 파이프라인을 위한 클라우드 규모의 플랫폼을 제공합니다. Xcalars&rsquo; 엔터프라이즈급 소프트웨어는 클라우드 및 온-프레미스 배포 모두에 대해 수백 개의 노드, 수천 명의 사용자 및 페타바이트 데이터로 확장됩니다.</p>


  <h2>시스코</h2>


  <p>Cisco Meraki는 네트워크에서 일상적인 작업을 수행하는 데 필요한 노력을 줄여 IT 관리자의 수명을 간소화합니다. 자동 VPN 및 SD-WAN을 사용하면 관리자가 몇 번의 클릭만으로 사이트간 VPN을 만들고 최적화할 수 있으며, 이제 이 기능을 Azure 클라우드로 직접 확장할 수 있으므로 IT 리소스가 몇 초 만에 강력하고 최적화된 네트워크를 통해 원격으로 액세스할 수 있습니다. Cisco Meraki 고객은 Azure에서 가상 어플라이언스를 만들 수 있으며, IT 리소스에 쉽게 원격으로 액세스할 수 있도록 일반 Meraki 대시보드를 통해 관리할 수 있습니다.</p>


  <h2>Customers&rsquo; Service 카탈로그 및 Marketplace에서 게시</h2>


  <p>다음은 서비스 카탈로그 또는 Markeplace에 게시할 때의 차이점과 주요 기능을 이해하는 데 도움이 되는 간단한 요약입니다.</p>


  <table border="0" cellpadding="2" cellspacing="0" width="1860">
   <tbody>
    <tr>
     <td valign="top" width="232">
     <p>&nbsp;</p>
     </td>
     <td valign="top" width="714">
     <p><strong>서비스 카탈로그 관리형 애플리케이션</strong></p>
     </td>
     <td valign="top" width="912">
     <p><strong>Marketplace 관리형 애플리케이션</strong></p>
     </td>
    </tr>
    <tr>
     <td valign="top" width="232">
     <p><strong>게시 도구</strong></p>
     </td>
     <td valign="top" width="714">
     <ul>
     </ul>

     <p align="left">Azure CLI</p>

     <p align="left">Azure PowerShell</p>

     <p align="left">Azure Portal</p>
     </td>
     <td valign="top" width="912">
     <p><a href="https://cloudpartner.azure.com/"><em>Cloud 파트너 게시 포털</em></a></p>
     </td>
    </tr>
    <tr>
     <td valign="top" width="232">
     <p><em style="font-size: 13px;"><strong>&nbsp;</strong></em><strong>소비 도구</strong></p>
     </td>
     <td valign="top" width="714">Azure Portal(더 많은 서비스&gt; 관리형 애플리케이션으로 이동)</td>
     <td valign="top" width="912">Azure Portal(Azure Marketplace로 이동)</td>
    </tr>
    <tr>
     <td valign="top" width="232">
     <p><strong></strong><b>Pricing</b></p>
     </td>
     <td valign="top" width="714">
     <ul>
     </ul>

     <p>파트너를 위해 게시할 수수료가 없습니다.</p>

     <p>관리되는 애플리케이션의 일부로 프로비전되는 Azure 리소스에 대한 요금이 청구된 고객입니다.</p>
     </td>
     <td valign="top" width="912">
     <ul>
     </ul>

     <p>파트너를 위해 게시할 수수료가 없습니다. <a href="https://docs.microsoft.com/en-us/azure/managed-applications/publish-marketplace-app#set-up-your-account-for-publishing-portal">Microsoft 개발자 센터 계정이</a> 필요합니다.</p>

     <p>관리되는 애플리케이션의 일부로 프로비전되는 Azure 리소스에 대한 요금이 청구된 고객입니다.</p>

     <p>고객에게 정액 월 요금이 부과될 수 있습니다.</p>

     <p>&nbsp;</p>
     </td>
    </tr>
    <tr>
     <td valign="top" width="232">
     <p><strong>패키지에 필요한 Artifacts</strong></p>
     </td>
     <td valign="top" width="714">
     <ul>
     </ul>

     <p>mainTemplate.json</p>

     <p>createUIDefinition.json</p>
     </td>
     <td valign="top" width="912">
     <ul>
     </ul>

     <p>mainTemplate.json</p>

     <p>createUIDefinition.json</p>
     </td>
    </tr>
    <tr>
     <td valign="top" width="232">
     <p><strong>사용 사례</strong></p>

     <p>(고객)</p>
     </td>
     <td valign="top" width="714">
     <ul>
     </ul>

     <p>관리형 애플리케이션을 사용하고 팀에서 특정 인재를 채용/구축하여 비용/출시 시간 혜택을 얻을 수 있습니다.</p>

     <p>서비스 카탈로그 정의 애플리케이션을 사용하여 회사 표준으로 거버넌스를 보장합니다.</p>

     <p>Azure 리소스의 기본 복잡성에서 최종 사용자를 추상화합니다.</p>
     </td>
     <td valign="top" width="912">
     <ul>
     </ul>

     <p>관리형 애플리케이션을 사용하고 팀에서 특정 인재를 채용/구축하여 비용/출시 시간 혜택을 얻을 수 있습니다.</p>

     <p>Azure 리소스의 기본 복잡성에서 최종 사용자를 추상화합니다.</p>

     <p>Azure Marketplace의 수천 파트너로부터 혁신에 쉽게 액세스할 수 있습니다.</p>

     <p>&nbsp;</p>
     </td>
    </tr>
    <tr>
     <td valign="top" width="232">
     <p><strong>사용 사례</strong>&nbsp;</p>
  (파트너)</td>
     <td valign="top" width="714">
     <p>최종 고객 조직 내의 개발자 및 사업부에 승인된 앱/서비스를 제공합니다.</p>

     <p>Azure 리소스의 기본 복잡성에서 최종 사용자를 추상화합니다.</p>

     <p>고객 테넌트에 배포된 관리되는 앱에 변조 및 의도하지 않은 변경이 없는지 확인합니다.</p>

     <p>수명 주기 관리 서비스로 수익을 창출합니다. 제공된 사용자 지정 솔루션 및 지원 서비스에 수익을 창출합니다.</p>
     </td>
     <td valign="top" width="912">
     <p>Azure Marketplace를 통해 모든 Azure 고객에게 애플리케이션을 제공합니다.</p>

     <p>수명 주기 관리 서비스로 수익을 창출합니다. 제공된 사용자 지정 솔루션 및 지원 서비스에 수익을 창출합니다.</p>

     <p>제품 혁신을 주도할 수 있는 기능을 갖춘 사용 패턴에 대한 고객 직접 연락 및 이해</p>

     <p>Azure 청구 시스템을 사용하여 최종 고객에게 청구하고 운영 작업을 오프로드합니다.</p>
     </td>
    </tr>
   </tbody>
  </table>


  <p>이 새로운 서비스를 사용해 보고 <a href="https://feedback.azure.com/forums/281804-azure-resource-manager">사용자 음성 채널</a> 또는 아래 의견을 통해 피드백을 알려주세요.</p>


  <h2>추가 리소스</h2>


  <ul>
   <li><a href="https://docs.microsoft.com/en-us/azure/azure-resource-manager/managed-application-author-marketplace">Marketplace 관리형 애플리케이션 게시</a></li>
   <li><a href="https://docs.microsoft.com/en-us/azure/azure-resource-manager/managed-application-publishing">서비스 카탈로그 관리되는 애플리케이션 게시</a></li>
   <li><a href="https://docs.microsoft.com/en-us/azure/azure-resource-manager/managed-application-createuidefinition-overview">관리되는 애플리케이션에 대한 UIDefinition을 만드는 방법</a></li>
   <li><a href="https://github.com/Azure/azure-managedapp-samples">관리되는 애플리케이션 샘플 GitHub 리포지토리</a></li>
  </ul>
