### YamlMime:Yaml
ms.openlocfilehash: 1ffaadafb52c761aae0ca2d27749dfc65b414ae0
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139897764"
Slug: azure-security-center-can-identify-attacks-targeting-azure-app-service-applications
Title: Azure Security Center는 Azure App Service 애플리케이션을 대상으로 하는 공격을 식별할 수 있습니다.
Summary: Azure에서 가장 인기 있는 서비스 중 하나는 고객이 인프라를 관리하지 않고 선택한 프로그래밍 언어로 웹 애플리케이션을 빌드하고 호스트할 수 있게 해주는 App Service입니다.
Content: >-
  <p>Azure&rsquo;에서 가장 인기 있는 서비스 중 하나는 고객이 인프라를 관리하지 않고 선택한 프로그래밍 언어로 웹 애플리케이션을 빌드하고 호스트할 수 있게 해주는 <a href="https://azure.microsoft.com/en-us/services/app-service/" target="_blank">App Service</a> 입니다. App Service는 자동 크기 조정 및 고가용성을 제공하며 Windows 및 Linux를 모두 지원합니다. 또한 GitHub, Visual Studio Team Services 또는 Git 리포지토리의 자동화된 배포도 지원합니다. <a href="https://azure.microsoft.com/en-us/blog/announcing-new-azure-security-center-capabilities-at-rsa-2018/" target="_blank">RSA에서</a> Azure Security Center는 클라우드의 규모를 활용하여 App Service 애플리케이션을 대상으로 하는 공격을 식별한다고 발표했습니다.</p>


  <p>웹 애플리케이션의 취약성은 인터넷의 거의 모든 조직에 공통적이고 동적인 인터페이스이므로 공격자가 자주 악용합니다. App Service를 기반으로 실행되는 애플리케이션에 대한 요청은 전 세계 Azure 데이터 센터에 배포된 여러 게이트웨이를 통해 진행되며, 각 요청을 해당 애플리케이션으로 라우팅합니다. 최근 Security Center 및 App Service는 App Service 고객을 지원하기 위한 보안 제공을 구축하기 위한 여정을 시작했습니다.</p>


  <p>Security Center는 Azure가 클라우드 공급자로서 가지고 있는 가시성을 활용하여 App Service 내부 로그를 분석하여 여러 대상에 대한 공격 방법론을 식별합니다. 예를 들어 다양한 웹 사이트에서 동일한 URI(Uniform Resource Identifiers)에 액세스하려고 시도합니다. 이러한 유형의 공격자는 일반적으로 여러 웹 사이트의 동일한 웹 페이지로 크롤링하여 특히 취약한 페이지 또는 플러그 인을 검색하는 패턴을 나타냅니다. Security Center는 WAF(웹 애플리케이션 방화벽) 계측을 통과할 수 있는 동작을 감지하고 경고할 수 있습니다.</p>


  <p>WAF는 웹 애플리케이션을 보호하기 위해 사용되는 광범위한 보호 메커니즘입니다. WAF는 일반적으로 요청된 URI에 대한 규칙 기반 문자열 분석을 수행하고 일반적인 공격을 성공적으로 식별합니다. 예를 들어 SQL 삽입, 사이트 간 스크립팅 및 기타 HTTP 위반이 있습니다. 알려진 공격을 성공적으로 완화하는 동안 규칙 기반 접근 방식은 새로운 취약성의 속도를 따라잡지 못합니다.</p>


  <p>Security Center는 클라우드의 규모를 활용하여 새로운 공격에 초점을 맞추면서 App Service 애플리케이션에 대한 공격을 식별합니다. 공격자가 정찰 단계에 있으므로 Azure에서 호스트되는 여러 웹 사이트에서 취약성을 식별하기 위해 검사합니다. Security Center&rsquo;의 새로운 기능에는 고객이 HTTP를 통해 또는 관리 방법 중 하나를 통해 애플리케이션&rsquo;과 상호 작용할 수 있는 모든 인터페이스를 포함하는 분석 및 기계 학습 모델이 포함됩니다. 또한 Azure의 자사 서비스인 Security Center는 이 PaaS의 기본 컴퓨팅 노드를 다루는 호스트 기반 보안 분석을 제공할 수 있는 고유한 위치에 있습니다. 따라서 Security Center는 이미 악용된 웹 애플리케이션에 대한 공격을 감지할 수 있습니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/8af5852b-1cd3-4eec-ba0f-30392943ed89.png"><img alt="image" border="0" height="502" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/168a8058-bbdb-4e81-b30e-b2fd9fca0f29.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="이미지" width="347"></a></p>


  <p>웹 애플리케이션을 관리하면 워크로드가 보안 취약성에 노출될 수 있으며, 이를 고려하고 해결해야 합니다. 이러한 취약성으로 인해 웹 애플리케이션이 악용되고 공격자가 워크로드에서 공간을 확보할 수 있습니다. Security Center는 웹 애플리케이션을 올바르게 구성하는 프로세스를 안내하는 데 도움이 되는 보안 모범 사례를 통해 Windows 및 Linux 웹 애플리케이션에 대한 권장 사항 집합을 제공합니다.</p>


  <p>이 기능의 공개 미리 보기는 이제 추가 비용 없이 Security Center의 표준 및 평가판 계층에서 사용할 수 있습니다.</p>


  <p>Security Center 위협 탐지에 대한 자세한 내용은 Security Center가 <a href="https://azure.microsoft.com/en-us/blog/how-azure-security-center-helps-reveal-a-cyberattack/" target="_blank">SQL 무차별 암호 대입 공격</a>, <a href="https://azure.microsoft.com/en-us/blog/how-azure-security-center-detects-a-bitcoin-mining-attack/" target="_blank">비트코인 마이닝</a>, <a href="https://azure.microsoft.com/en-us/blog/how-azure-security-center-detects-ddos-attack-using-cyber-threat-intelligence/" target="_blank">사이버 위협 인텔리전스를 사용한 DDoS</a> 공격 및 <a href="https://azure.microsoft.com/en-us/blog/how-azure-security-center-aids-in-detecting-good-applications-being-used-maliciously/" target="_blank">악의적으로 사용되는 좋은 애플리케이션</a>을 검색하는 방법에 대한 보안 연구원의 <a href="https://docs.microsoft.com/en-us/azure/security-center/security-center-detection-capabilities" target="_blank">설명서</a> 또는 사례 연구를 검토하세요.</p>
