### YamlMime:Yaml
ms.openlocfilehash: 861cc3ee8e7e7608d621d3411f535162125127a4
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139907317"
Slug: azure-monitor-for-containers-with-prometheus-now-in-preview
Title: Prometheus를 사용하는 컨테이너용 Azure Monitor가 미리 보기로 제공됩니다.
Summary: Prometheus는 인기 있는 오픈 소스 메트릭 모니터링 솔루션이며 클라우드 네이티브 컴퓨팅 재단의 일부입니다. 많은 고객은 Prometheus가 Kubernetes에서 제공하는 광범위한 메트릭을 좋아합니다.
Content: >-
  <p><a href="https://prometheus.io/" target="_blank">Prometheus</a> 는 인기 있는 오픈 소스 메트릭 모니터링 솔루션이며 <a href="https://www.cncf.io/" target="_blank">클라우드 네이티브 컴퓨팅 재단</a>의 일부입니다. 우리는 Prometheus가 Kubernetes에서 제공하는 광범위한 메트릭을 좋아하는 많은 고객이 있습니다. 그러나 AKS(Azure Kubernetes Service) 클러스터<a href="https://docs.microsoft.com/en-us/azure/monitoring/monitoring-container-health" target="_blank">에 대해</a> 완벽하게 <a href="https://docs.microsoft.com/en-us/azure/azure-monitor/insights/container-insights-overview">관리되는 기본</a> 모니터링을 제공하는 컨테이너용 Azure Monitor를 사용하는 것이 얼마나 쉬운지도 좋아합니다. Prometheus 데이터를 Azure Monitor로 유입하라는 요청을 받고 있으며, 현재 컨테이너용 Azure Monitor와 Prometheus 통합을 공유하게 되어 기쁘게 생각합니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/2e90a2c0-7b52-45a7-b101-1c4815e2273c.png"><img alt="Flowchart illistrating how Promethues endpoints integrate with Azure Monitor for containers" border="0" height="307" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/adc3360f-3bfb-439c-90e8-7f2d6f28098b.png" style="border: 0px currentcolor; margin-right: auto; margin-left: auto; display: block; background-image: none;" title="Promethues 엔드포인트가 컨테이너용 Azure Monitor와 통합되는 방법을 지정하는 순서도" width="880"></a></p>


  <p>일반적으로 Prometheus를 사용하려면 데이터베이스를 사용하여 Prometheus 서버를 설정 및 관리해야 합니다. Azure Monitor 통합을 사용하면 Prometheus 서버가 필요하지 않습니다. 내보내기 또는 Pod(애플리케이션)를 통해 Prometheus 엔드포인트를 노출하기만 하면 컨테이너용 Azure Monitor용 컨테이너화된 에이전트가 메트릭을 스크래핑할 수 있습니다. Azure Monitor를 사용하여 Prometheus 메트릭을 수집하는 원활한 온보딩 환경을 제공했습니다. 아래 예제에서는 kube-dns-metric의 일부인 coredns 메트릭이 로그를 위해 Azure Monitor로 수집되는 방법을 보여 줍니다.&nbsp;</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/401e4e7e-d3e5-4bcb-b3b9-3399ab2a0434.png"><img alt="Screenshot example of how the coredns metrics is collected into Azure Monitor for logs" border="0" height="183" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/699f0f61-6b0b-47de-af1d-c3b90021bc43.png" style="border: 0px currentcolor; margin-right: auto; margin-left: auto; display: block; background-image: none;" title="로그를 위해 Coredns 메트릭을 Azure Monitor에 수집하는 방법의 스크린샷 예제" width="1355"></a></p>


  <p>Prometheus SDK를 애플리케이션에 계측하여 컨테이너에서 워크로드 메트릭을 수집할 수도 있습니다. 아래 예제에서는 <strong>prommetrics_demo_requests_counter</strong> 컬렉션을 보여 주세요. URL, 엔드포인트 또는 Pod 주석을 통해 워크로드 메트릭을 수집할 수도 있습니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/57d50ef9-c134-4732-b742-9d9540af0985.png"><img alt="Screenshot example showing the collection of the prommetrics_demo_requests_counter" border="0" height="157" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/0c191334-07c7-4d64-9c5c-7141302c2f4b.png" style="border: 0px currentcolor; margin-right: auto; margin-left: auto; display: block; background-image: none;" title="prommetrics_demo_requests_counter 컬렉션을 보여 주는 스크린샷 예제" width="1390"></a></p>


  <h2>컨테이너용 Azure Monitor를 사용하여 전체 스택 모니터링</h2>


  <p>따라서 Prometheus 메트릭은 컨테이너용 Azure Monitor에서 이미 제공하는 최근에 추가된 스토리지 및 네트워크 성능 메트릭을 포함하여 나머지 메트릭과 어떻게 일치하나요? 메트릭이 모두 아래에 어떻게 적합한지 확인할 수 있습니다. 컨테이너용 Azure Monitor는 플랫폼, 컨테이너, 오케스트레이터 수준 및 워크로드 수준에서 기본 원격 분석을 제공합니다. Prometheus의 추가 워크로드 메트릭을 사용하면 이제 컨테이너용 Azure Monitor에서 AKS(Azure Kubernetes Services)에 대한 전체 스택, 엔드투엔드 모니터링 보기를 얻을 수 있습니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/cbbc0570-e10c-425f-ab4c-d46ac1e31d49.png"><img alt="Image of table showing how Prometheus telemetry fits in with other metrics" border="0" height="339" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/cfec160a-b003-45b0-87d3-bf54ac26bc5f.png" style="border: 0px currentcolor; margin-right: auto; margin-left: auto; display: block; background-image: none;" title="Prometheus 원격 분석이 다른 메트릭과 어떻게 일치하는지 보여 주는 테이블 이미지" width="1180"></a></p>


  <h2>Azure 대시보드에서 Prometheus 메트릭 시각화 및 경고</h2>


  <p>메트릭이 Azure Monitor 로그에 저장되면 KQL(Kusto Query Language)과 함께 Log Analytics를 사용하여 메트릭에 대해 쿼리할 수 있습니다. Prometheus SDK를 계측하는 샘플 쿼리를 여기에&rsquo; 추가합니다.&nbsp; Azure Portal에서 쿼리를 사용하여 결과를 신속하게 그릴 수 있습니다.</p>


  <pre>

  &lt;Queries&gt;

  InsightsMetrics

  | where Name == &quot;prommetrics_demo_requests_counter_total&quot;

  | extend dimensions=parse_json(Tags)

  | extend request_status = tostring(dimensions.request_status)

  | where request_status == &quot;bad&quot;

  | where TimeGenerated &gt; todatetime(&#39;2019-07-02T09:40:00.000&#39;)

  | where TimeGenerated &lt; todatetime(&#39;2019-07-02T09:54:00.000&#39;)

  | project request_status, Val, TimeGenerated | render timechart</pre>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/7f0c2588-8637-4d11-9fcc-78d580bed27d.png"><img alt="Screenshot example of plotting results in Azure portal for a query that uses the embedded Prometheus library" border="0" height="651" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/e6965b89-7451-42c1-abd9-e00b916a543a.png" style="border: 0px currentcolor; margin-right: auto; margin-left: auto; display: block; background-image: none;" title="포함된 Prometheus 라이브러리를 사용하는 쿼리에 대한 Azure Portal의 결과 그리기 예제 스크린샷" width="1307"></a></p>


  <p>차트를 Azure 대시보드에 고정하고 사용자 지정 대시보드를 만들 수 있습니다. <a href="https://docs.microsoft.com/en-us/azure/azure-monitor/insights/container-insights-analyze#view-performance-directly-from-an-aks-cluster" target="_blank">컨테이너 클러스터 보기용 Azure Monitor</a>에서 현재 Pod 및 노드 차트를 대시보드에 고정할 수도 있습니다.</p>


  <p><img alt="Screenshot example of pinning query result charts to the Azure or customized dashboards" border="0" height="781" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/e63bd58f-b746-463b-a9ef-0b58ba53b84a.png" style="border: 0px currentcolor; margin-right: auto; margin-left: auto; display: block; background-image: none;" title="쿼리 결과 차트를 Azure 또는 사용자 지정된 대시보드에 고정하는 스크린샷 예제" width="1140"></p>


  <p>Prometheus 메트릭에 대해 경고하려는 경우 <a href="https://docs.microsoft.com/en-us/azure/azure-monitor/insights/container-insights-alerts" target="_blank">Azure에서 경고를</a> 사용하여 경고할 수 있습니다.&nbsp;</p>


  <p>이것은 우리에게 흥미로운 통합이었으며, 우리는 고객이 Kubernetes를 모니터링할 수 있도록 계속 노력할 것입니다. 에이전트를 구성하여 Prometheus 데이터를 수집하고, 쿼리하고, 컨테이너용 Azure Monitor의 데이터를 사용하는 방법에 대한 자세한 내용은 <a href="https://aka.ms/ci-prom" target="_blank">설명서를 참조하세요</a>. Prometheus는 Prometheus에서 Azure Monitor 로그로 수집된 데이터를 보여 주는 <a href="https://aka.ms/ci-prom-usage" target="_blank">쿼리</a>에서 비용 영향을&rsquo; 이해해야 하는 경우 풍부하고 광범위한 원격 분석을 제공합니다.</p>


  <p>Prometheus에서 사용 가능한 메트릭은 <a href="https://prometheus.io/" target="_blank">Prometheus 웹 사이트</a>로 이동하세요.</p>


  <p>피드백 또는 제안 사항은 <a href="https://azure.microsoft.com/en-us/support/community/?product=monitor" target="_blank">techforum</a> 또는 <a href="https://aka.ms/ci-forums" target="_blank">stackoverflow</a>를 통해 문의하세요.</p>
