### YamlMime:Yaml
ms.openlocfilehash: 0e511cc996582c1ff85661220dc28ef0e1401d22
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139899950"
Slug: azure-monitor-multiple-diagnostic-settings
Title: 'Azure Monitor: 로그 및 메트릭 라우팅에 대한 향상된 기능'
Summary: 오늘 Azure 리소스 진단 로그 및 메트릭을 스토리지 계정, Event Hubs 또는 Log Analytics로 라우팅하기 위한 Azure Monitor 내의 새로운 기능 집합을 발표하게 되어 기쁘게 생각합니다...
Content: >-
  <p>오늘 Azure 리소스 진단 로그 및 메트릭을 <a href="https://docs.microsoft.com/azure/storage/storage-introduction">스토리지 계정</a>, <a href="https://azure.microsoft.com/services/event-hubs/">Event Hubs</a> 네임스페이스 또는 <a href="https://azure.microsoft.com/services/log-analytics/">Log Analytics</a> 작업 영역으로 라우팅하기 위한 Azure Monitor 내의 새로운 기능 집합을 발표하게 되어 기쁘게 생각합니다. 이제 리소스당 여러 리소스 진단 설정을 만들어 로그 범주 및 메트릭의 다양한 순열을 다른 대상(공개 미리 보기)으로 라우팅하고 메트릭과 로그를 다른 구독의 대상으로 라우팅할 수 있습니다. 이 게시물&rsquo;에서는 이러한 새로운 기능과 현재 사용 방법을 안내합니다.</p>


  <h2>여러 진단 설정 만들기</h2>


  <p><a href="https://docs.microsoft.com/azure/monitoring-and-diagnostics/monitoring-overview-of-diagnostic-logs#resource-diagnostic-settings">리소스 진단 설정</a>은 해당 리소스 종류에 사용할 수 있는 로그 및 메트릭 중 수집할 로그 및 해당 데이터를 보낼 위치를 결정하는 개별 Azure 리소스에 대한 규칙입니다. 리소스 진단 설정에는 데이터를 모니터링하기 위한 세 가지 대상 또는 &lsquo;데이터 싱크가 있습니다&rsquo; .</p>


  <ul>
   <li><a href="https://docs.microsoft.com/azure/monitoring-and-diagnostics/monitoring-archive-diagnostic-logs">보관을 위한 Storage 계정</a></li>
   <li><a href="https://docs.microsoft.com/azure/log-analytics/log-analytics-azure-storage">검색 및 분석을 위한 Log Analytics 작업 영역</a></li>
   <li><a href="https://docs.microsoft.com/azure/monitoring-and-diagnostics/monitoring-stream-diagnostic-logs-to-event-hubs">타사 도구 또는 사용자 지정 솔루션과의 통합을 위한 Event Hubs 네임스페이스</a></li>
  </ul>


  <p>이전에는 리소스당 하나의 진단 설정만 설정할 수 있습니다. 두 가지 방법으로 너무 제한적이라는 피드백을 들었습니다.</p>


  <ol>
   <li>모니터링 데이터를 각 대상의 한 인스턴스로만 보내는 것으로 제한되었습니다. 예를 들어 특정 Application Gateway에 대한 로그 및 메트릭만 하나의 스토리지 계정으로 보낼 수 있습니다. 각각 이 데이터를 사용하려는 보안 및 모니터링을 위한 두 개의 독립 팀이 있는 경우 이 데이터를 두 팀 모두에 별도로 제공할 수 있는 기능이 제한되었습니다.</li>
   <li>로그 범주 및 메트릭의 동일한 순열을 모든 대상으로 라우팅해야 했습니다. 예를 들어 동일한 계정 메트릭을 스토리지 계정&rsquo;으로 보내는 동안 특정 Batch 계정&rsquo; 서비스 로그를 Log Analytics로 라우팅하는 것은 불가능했습니다.</li>
  </ol>


  <p>현재는 단일 리소스에서 여러 진단 설정을 만드는 기능의 공개 미리 보기를 도입하여 위의 두 가지 제한을 모두 제거했습니다. &rsquo;Azure Portal에서 이를 설정하는 방법을 간단히 살펴보겠습니다. 모니터 블레이드로 이동하고 진단 설정 클릭합니다&ldquo;.&rdquo;</p>


  <p><img alt="Azure diagnostic settings blade" border="0" height="620" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/d5a494bb-dd74-4029-9de5-d49ba5da39d9.png" style="background-image: none; float: none; margin-left: auto; display: block; margin-right: auto; border-image: none" title="Azure 진단 설정 블레이드" width="1103"></p>


  <p>&rsquo;&rsquo;리소스에서 로그 및 메트릭 데이터를 둘 다 라우팅하는 기능을 더 잘 반영하기 위해 진단 로그&rdquo;에서 &ldquo;이 섹션 &ldquo;진단 설정&rdquo; 이름이 바뀌었습니다. 이 블레이드&rsquo;에는 진단 설정을 지원하는 리소스 목록이 표시됩니다. 하나를 클릭하면 해당 리소스의 모든 설정 목록이 표시됩니다.</p>


  <p><img alt="Azure multiple diagnostic settings" border="0" height="443" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/e3ea1378-52c3-47fc-ad3f-bdee256cf1ec.png" style="background-image: none; float: none; margin: 0px auto; display: block; border-image: none" title="Azure 다중 진단 설정" width="1030"></p>


  <p>존재하지 않는 경우 만들라는 메시지가 표시됩니다.</p>


  <p><img alt="Azure no diagnostic settings" border="0" height="294" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/fede6a1e-d717-4890-9621-77d3880d7111.png" style="background-image: none; float: none; margin: 0px auto; display: block; border-image: none" title="Azure 진단 설정 없음" width="517"></p>


  <p>진단 턴을 &ldquo;클릭하면 진단&rdquo; 설정을 위한 친숙한 블레이드가 표시되지만 이제 이름&rdquo; 필드&ldquo;가 추가된 것을 볼 수 있습니다. 동일한 리소스의 여러 설정을 구분하는 이름을 설정에 지정합니다.</p>


  <p><img alt="Azure named diagnostic setting blade" border="0" height="593" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/229ba2d9-8260-41a7-8f64-883a91838214.png" style="background-image: none; float: none; margin: 0px auto; display: block; border-image: none" title="Azure 명명된 진단 설정 블레이드" width="583"></p>


  <p>저장&rdquo;을 클릭하고 &ldquo;이제 이전 블레이드로 돌아가면 만든 설정이 표시되고 추가 설정이 추가됩니다.</p>


  <p><img alt="Azure multiple diagnostic settings" border="0" height="510" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/ed74f072-3956-4978-870f-5a139898f402.png" style="background-image: none; float: none; margin: 0px auto; display: block; border-image: none" title="Azure 다중 진단 설정" width="1027"></p>


  <p>진단 설정을 더 추가하면 이 목록에 추가됩니다. 리소스당 최대 3개의 진단 설정을 사용할 수 있습니다.</p>


  <p>REST API 또는 ARM 템플릿을 사용하여 이 작업을 수행할 수도 있습니다. PowerShell 지원이 곧 제공될 예정입니다. 동일한 유형의 추가 대상으로 데이터를 라우팅하면 청구 정보에 따라 서비스 요금이 부과됩니다.</p>


  <h2>구독 간에 모니터링 데이터 작성</h2>


  <p>이전에는 리소스에 대한 메트릭 및 로그 범주를 데이터를 내보내는 리소스와 동일한 구독 내의 스토리지 계정, Event Hubs 네임스페이스 또는 Log Analytics 작업 영역으로만 라우팅할 수 있었습니다. 많은 구독을 추적하는 중앙 집중식 모니터링 팀이 있는 회사의 경우 구독당 대상 리소스를 유지하는 것이 지루하여 각 구독에 대한 고유한 스토리지 계정(또는 Event Hubs 네임스페이스 또는 작업 영역)에 대한 지식이 필요합니다. 이제 사용자 계정에 해당 대상 리소스에 대한 적절한 쓰기 액세스 권한이 있는 경우 모니터링 데이터를 다른 구독의 대상으로 보내도록 진단 설정을 구성할 수 있습니다.</p>


  <p><img alt="Azure cross subscription diagnostic setting" border="0" height="581" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/ac7f0e3b-ad5c-495a-b808-0c367df32d97.png" style="background-image: none; float: none; margin: 0px auto; display: block; border-image: none" title="Azure 구독 간 진단 설정" width="1164"></p>


  <p>인증은 특정 Azure Active Directory 테넌트 내에서 수행되므로 모니터링 데이터는 데이터를 내보내는 리소스와 동일한 테넌트 내의 대상으로만 라우팅할 수 있습니다.</p>


  <p>이러한 새로운 기능은 오늘부터 모든 공용 <a href="https://azure.microsoft.com/en-us/regions/">Azure 지역에 배포됩니다</a> . 이를 사용해 보고 <a href="https://feedback.azure.com/forums/231545-diagnostics-and-monitoring">UserVoice 채널</a> 또는 아래의 의견을 통해 피드백을 알려주세요.</p>
