### YamlMime:Yaml
ms.openlocfilehash: 082c0cbcaf15a67c355b37a7383187d333eeb5ca
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139898195"
Slug: azure-active-directory-news-application-proxy-general-availability-and-many-more-new-additions
Title: 'Azure Active Directory 뉴스: 애플리케이션 프록시 일반 공급 및 더 많은 새로운 추가'
Summary: 올해는 Azure Active Directory 팀에서 하루 만에 출시 된 가장 큰 기능 세트로 마감됩니다. 많은 기능이 처음으로 공개 미리 보기로 제공되며 다른 기능은 12월 11일에 일반 공급됩니다.
Content: >-
  올해는 Azure Active Directory 팀에서 하루 만에 출시 된 가장 큰 기능 세트로 마감됩니다. 많은 기능이 처음으로 공개 미리 보기로 제공되며 다른 기능은 12월 11일에 일반 공급됩니다.


  <a href="https://msdn.microsoft.com/en-us/library/azure/dn768219.aspx">Azure Active Directory 애플리케이션 프록시</a>의 일반 공급 공지부터 Azure Active Directory 이제 Single Sign-On을 제공하고 온-프레미스에서 호스트되는 모든 종류의 웹 애플리케이션에 대한 보안 원격 액세스를 제공할 수 있습니다. 애플리케이션 프록시를 사용하면 웹 애플리케이션을 게시할 수 있으며 <a href="https://msdn.microsoft.com/library/azure/dn532272.aspx">Premium 및 Basic 버전</a> 모두에서 사용할 수 있습니다. 이제 온-프레미스 웹앱을 SaaS 애플리케이션과 동일한 방식으로 제공하여 최종 사용자에게 응집력 있고 원활한 환경을 제공할 수 있습니다.


  애플리케이션 프록시 및 릴리스된 다른 모든 기능에 대한 자세한 내용은 <a href="https://blogs.technet.com/b/ad/">Active Directory 팀 블로그</a>를 참조하세요.

  <h2>향상된 기능:</h2>

  Azure Active Directory 온-프레미스 디렉터리로의 <b>비밀번호 쓰기 저장</b>은 일반적으로 사용할 수 있습니다. 클라우드의 암호 변경 내용은 Azure Active Directory 동기화를 통해 온-프레미스 디렉터리에 다시 쓸 수 있습니다.


  <a href="https://go.microsoft.com/fwlink/?LinkID=519058"><b>관리 단위</b></a>  대기업이 디렉터리를 하위 분할하고 복잡한 조직에서 관리 권한을 위임할 수 있도록 공개 미리 보기로 제공됩니다.


  <b>암호 SSO를 지원하는 SaaS 애플리케이션은 이제 관리자가</b> Azure Active Directory 테넌트에 수동으로 추가할 수 있습니다. 이 기능은 공개 미리 보기에 도입되었습니다. Azure Active Directory 테넌트에 대한 이러한 사용자 지정 애플리케이션 추가는 Single Sign-On 방법과 Azure Active Directory 애플리케이션 <a href="https://azure.microsoft.com/en-us/marketplace/active-directory/">갤러리</a>에 있는지 여부에 관계없이 애플리케이션에 대한 거의 모든 링크를 추가하고 최종 사용자의 액세스 패널에 할당할 수 있는 지점까지 확장됩니다.


  위의 추가 기능을 통해 Azure Active Directory 액세스 패널은 애플리케이션 갤러리 또는 사용자 지정, 온-프레미스에서 게시된 웹 애플리케이션(애플리케이션 프록시를 통해) 및 공개적으로 액세스할 수 있는 링크가 있는 모든 애플리케이션에서 SaaS 애플리케이션을 시작하는 지점이 될 수 있습니다.


  보안 셀프 서비스 암호 재설정을 위한 옵션인 <b>보안 질문</b>도 공개 미리 보기로 제공됩니다. 휴대폰 또는 전자 메일 계정에 액세스할 수 없는 사용자는 미리 정의된 여러 보안 질문에 답변하여 ID를 증명하고 myapps.microsoft.com 웹 페이지(액세스 패널)에서 암호를 재설정할 수 있는 권한을 얻을 수 있습니다.


  이 블로그에서 Azure Active Directory, Azure Multi-Factor Authentication 및 하이브리드 ID 뉴스를 계속 공유할 것입니다.
