### YamlMime:Yaml
ms.openlocfilehash: 46033c0cb21f5e528b39e4aa04b79418c6bb8f57
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139898432"
Slug: azure-layered-approach-to-physical-security
Title: 물리적 보안에 대한 Azure의 계층화된 접근 방식
Summary: Azure는 인프라, 애플리케이션 및 데이터를 호스트하기 위해 처음부터 빌드된 매우 안전한 기반을 제공합니다.
Content: >-
  <p><em>이 블로그는 Microsoft Azure 안전한 기반을 제공하는 방법에 대한 4부로 구성된<a href="https://azure.microsoft.com/en-us/blog/tag/azure-security/"> 블로그 게시물 시리즈의</a> 첫 번째 블로그입니다.</em></p>


  <p>많은 고객으로부터 클라우드 보안이 가장 중요한 문제 중 하나라는 소식을 들었습니다. 고객으로부터 들었던 또 다른 점은&rsquo; Azure에서 보안을 담당하는 내용과 Azure에서 수행할 작업에 대한 명확성을 원한다는 것입니다. Azure는 인프라, 애플리케이션 및 데이터를 호스트하기 위해 처음부터 빌드된 매우 안전한 기반을 제공합니다. Microsoft는 고객 데이터 보호의 중요성을 이해하므로 데이터를 포함하는 데이터 센터를 보호하기 위해 최선을 다하고 있습니다. Microsoft는 Azure 플랫폼의 물리적 보안을 포함하여 보안에 10억 달러 이상을 투자하여 다른 비즈니스 이니셔티브에 시간과 리소스를 투자할 수 있습니다. 향후 몇 개월 동안 보안 기반 블로그 시리즈의&rsquo; 일부로 Azures&rsquo; 플랫폼을 구성하는 데 도움이 되는 물리적, 인프라(논리적) 및 운영 보안의 구성 요소에 대해 설명합니다. 오늘날 우리는 물리적 보안에 초점을 맞추고 있습니다.</p>


  <p>물리적 보안은 Microsoft가 고객 데이터가 저장된 영역에 대한 물리적 액세스를 엄격하게 제어하는 방식으로 데이터 센터를 설계, 빌드 및 운영하는 방법을 나타냅니다. 당사의 데이터 센터는 모든 클라우드 서비스 공급자의 국제적으로 인정받는 표준 및 인증의 가장 포괄적인 포트폴리오를 준수하도록 <a href="https://azure.microsoft.com/en-us/overview/trusted-cloud/" target="_blank">인증</a> 되었습니다. Microsoft에는 Azure를 지원하는 물리적 시설을 설계, 구축 및 운영하는 데 전념하는 전체 부서가 있습니다. 이 팀은 최첨단의 물리적 보안을 유지 관리하는 데 투입되었습니다.</p>


  <p>우리는 물리적 보안에 계층화된 접근 방식을 취합니다. Microsoft에서 관리하는 데이터 센터에는 액세스 승인, 시설&rsquo; 경계, 건물 경계, 건물&rsquo; 내부 및 데이터 센터 층에 대한 광범위한 보호 계층이 있습니다. 이 계층화된 접근 방식은 권한이 없는 사용자가 데이터 및 데이터 센터 리소스에 물리적으로 액세스할 수 있는 위험을 줄입니다.</p>


  <p>물리적 보안의 첫 번째 계층은 데이터 센터에 도착하기 전에 액세스 요청으로 시작합니다. 방문에 대한 유효한 비즈니스 근거(예: 규정 준수 또는 감사 목적)를 제공해야 합니다. 모든 요청은 Microsoft 직원의 액세스 필요성에 따라 승인됩니다. 이는 데이터 센터에서 작업을 완료하는 데 필요한 개인 수를 최소한으로 유지하는 데 도움이 됩니다. 권한이 부여되면 개인은 승인된 비즈니스 근거에 따라 데이터 센터의 개별 영역에만 액세스할 수 있습니다. 권한은 특정 기간으로 제한되며, 허용된 기간 후에는 만료됩니다.</p>


  <p>다음 보안 계층은 건물&rsquo; 경계입니다. 데이터 센터에 도착하면 잘 정의된 액세스 지점을 통과해야 합니다. 일반적으로 강철과 콘크리트로 만들어진 높은 울타리가 경계를 1인치 간격으로 둘러싸고 있습니다. 데이터 센터 주변에는 카메라가 있어서 연중무휴로 촬영되며, 보안 팀에서 모니터링합니다.</p>


  <p>데이터 센터 경계에 액세스할 수 있게 되면 데이터 센터를&rsquo; 입력하려면 추가 보안 조치를 전달해야 합니다. 데이터 센터 입구에는 엄격한 훈련 및 신원 조사를 거친 전문 보안 책임자가 배치됩니다. 또한 이러한 보안 책임자는 데이터 센터를 정기적으로 순찰하는 동시에 1년 24/7 및 365일 동안 데이터 센터 내부의 카메라 비디오를 모니터링합니다. 건물에 들어간 후에 데이터 센터로 계속 이동하려면 생체 인식 방법을 통한 2단계 인증을 통과해야 합니다. ID의 유효성이 검사된 경우 액세스를 승인한 데이터 센터의 일부를 입력할 수 있으며 승인된 기간 동안만 해당 곳에 머물 수 있습니다.</p>


  <p>데이터 센터 바닥의 요청된 부분 입구에 도착하면 전신 금속 감지 검사를 통과해야 합니다. Microsoft에서 알지 못하게 데이터 센터에서 무단으로 데이터를 입출력할 위험을 줄이기 위해 승인된 디바이스만 데이터 센터 층에 유입되도록 할 수 있습니다. 또한 비디오 카메라는 모든 가상 머신 랙의 전면과 뒷면을 모니터링합니다. 가상 머신으로 수행할 모든 작업은 추적&mdash;됩니다. 하드 디스크가 정리되고 지워질 때까지 가상 머신에 처음 들어갈 때입니다. 데이터 센터 층을 나갈 때도 전신 금속 탐지기가 작동합니다. 데이터 센터를 나가려면 추가 보안 검사를 통과해야 합니다.&nbsp;&nbsp;</p>


  <p>클라우드 플랫폼의 보안을 유지하기 위해 전 세계의 데이터 센터를 보호하는 것이 최우선 과제입니다. 우리는 고객 데이터 보안의 중요성과 보안 위반의 위험을 이해하므로 세계적 수준의 보안에 10 억 달러 이상을 투자했으며 이러한 투자를 초과 근무로 계속 늘릴 것입니다. 데이터 및 데이터 센터 리소스의 보안이 매우 보호된다는 것을 알고 비즈니스 우선 순위에 집중할 수 있습니다.</p>


  <p>데이터 센터 보안이 작동하는 것을 직접 확인하려면 다음 비디오를 시청하세요.</p>


  <p align="center"><iframe allow="autoplay; encrypted-media" allowfullscreen="" frameborder="0" height="315" src="https://www.youtube.com/embed/r1cyTL8JqRg" width="560"></iframe></p>
