### YamlMime:Yaml
ms.openlocfilehash: c8f8cf205df0762f4a42a3969d25917dc9bae5a3
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139911116"
Slug: azure-web-application-firewall-waf-generally-available
Title: Azure WAF(웹 애플리케이션 방화벽) 일반 공급
Summary: 지난 9월 Ignite에서 계층 7 Azure Application Gateway 서비스에 웹 애플리케이션 방화벽을 추가하여 웹 애플리케이션 보안을 향상하기 위한 계획을 발표했습니다. 우리는 지금 일반을 발표하고있다 ...
Content: >-
  <p>지난 9월 Ignite에서 계층 7 <a href="https://azure.microsoft.com/en-us/services/application-gateway/">Azure Application Gateway</a> 서비스에 웹 애플리케이션 방화벽을 추가하여 웹 애플리케이션 보안을 향상하기 위한 계획을 발표했습니다. 이제 모든 Azure 공용 지역에서 웹 애플리케이션 방화벽의 일반 공급이 발표되었습니다.</p>


  <p>웹 애플리케이션은 SQL 삽입 및 사이트 간 스크립팅 공격과 같은 일반적인 알려진 취약성을 악용하는 악의적인 공격의 대상이 되고 있습니다. 애플리케이션에서 이러한 악용을 방지하려면 애플리케이션 토폴로지의 여러 계층에서 엄격한 유지 관리, 패치 적용 및 모니터링이 필요할 수 있습니다. 중앙 집중식 WAF(웹 애플리케이션 방화벽)는 웹 공격으로부터 보호하고 애플리케이션을 변경하지 않고도 보안 관리를 간소화합니다. 애플리케이션 및 규정 준수 관리자는 위협 및 침입에 대해 더 나은 보증을 받습니다.</p>


  <p>Azure Application Gateway는 SSL 종료, 진정한 라운드 로빈 부하 분산, 쿠키 기반 세션 선호도, 다중 사이트 호스팅 및 URL 경로 기반 라우팅을 비롯한 기능을 제공하는 ADC(애플리케이션 배달 컨트롤러) 계층 7 네트워크 서비스입니다. Application Gateway는 더 나은 애플리케이션 보안 강화를 제공하기 위해 SSL 정책 제어 및 종단 간 SSL 암호화를 제공합니다. 이러한 기능을 통해 백 엔드 애플리케이션은 비용이 많이 드는 암호화/암호 해독, SSL 정책 및 부하 분산을 Application Gateway에 유지하면서 핵심 비즈니스 논리에 집중할 수 있습니다. Application Gateways&rsquo; 핵심 제품과 통합된 웹 애플리케이션 방화벽은 OWASP(Open Web Application Security Project) <a href="https://www.owasp.org/index.php/Category:OWASP_Top_Ten_Project">상위 10개 취약성</a>으로 식별되는 가장 일반적인 웹 취약성으로부터 보호하는 애플리케이션의 보안 포트폴리오와 태세를 더욱 강화합니다. Application Gateway WAF는 이러한 많은 취약성에 대한 기준 보안을 제공하는 OWASP ModSecurity Core 규칙 집합(3.0 또는 2.2.9)으로 미리 구성됩니다. 간단한 구성 및 관리를 통해 Application Gateway WAF는 풍부한 로깅 기능과 선택적 규칙 사용 기능을 제공합니다.</p>


  <h2>이점</h2>


  <p>다음은 웹 애플리케이션 방화벽에서 제공하는 핵심 이점입니다.</p>


  <h3>보호</h3>


  <ul>
   <li>백 엔드 코드를 수정하지 않고 웹 취약성 및 공격으로부터 애플리케이션을 보호합니다. WAF는 다음을 비롯한 다양한 공격 범주를 해결합니다. <ul>
    <li>SQL 삽입</li>
    <li>사이트 간 스크립팅</li>
    <li>명령 삽입, HTTP 요청 밀수, HTTP 응답 분할 및 원격 파일 포함 공격과 같은 일반적인 공격</li>
    <li>HTTP 프로토콜 위반</li>
    <li>HTTP 프로토콜 변칙</li>
    <li>봇, 크롤러 및 스캐너</li>
    <li>일반적인 애플리케이션 구성 오류(예: Apache, IIS 등)</li>
    <li>HTTP 서비스 거부</li>
   </ul>
   </li>
   <li>여러 웹 애플리케이션을 동시에 보호합니다. Application Gateway는 웹 공격으로부터 모두 보호할 수 있는 단일 게이트웨이 뒤에 최대 20개의 웹 사이트를 호스팅하도록 지원합니다.</li>
  </ul>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/fb10e181-7a4d-4ceb-98ab-45ac18906291.png"><img alt="WAF - App Gateway" border="0" height="300" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/5e08781c-806a-4b83-b75c-3e59b508ff4f.png" style="border-top: 0px; border-right: 0px; background-image: none; border-bottom: 0px; float: none; padding-top: 0px; padding-left: 0px; margin-left: auto; border-left: 0px; display: block; padding-right: 0px; margin-right: auto" title="WAF - App Gateway" width="490"></a></p>


  <h3>사용 편의성</h3>


  <ul>
   <li>Application Gateway WAF는 Azure Portal 및 REST API를 통해 간단하게 구성, 배포 및 관리할 수 있습니다. PowerShell 및 CLI는 곧 사용할 수 있습니다.</li>
   <li>관리자는 WAF 규칙을 중앙에서 관리할 수 있습니다.</li>
   <li>기존 Application Gateway는 WAF를 포함하도록 업그레이드할 수 있습니다. WAF는 웹 애플리케이션 방화벽 외에도 모든 표준 Application Gateway 기능을 유지합니다.</li>
  </ul>


  <h3>모니터링</h3>


  <ul>
   <li>Application Gateway WAF는 <a href="https://docs.microsoft.com/en-us/azure/monitoring-and-diagnostics/monitoring-overview">AZURE Monitor</a> 와 통합된 실시간 WAF 로그를 사용하여 공격에 대한 웹 애플리케이션을 모니터링하여 WAF 경고를 추적하고 추세를 쉽게 모니터링하는 기능을 제공합니다. JSON 형식 로그는 고객&rsquo; 스토리지 계정으로 직접 이동합니다. 고객은 이러한 로그를 완전히 제어할 수 있으며 자체 보존 정책을 적용할 수 있습니다. 고객은 이러한 로그를 자체 분석 시스템에 수집할 수도 있습니다. WAF 로그도 <a href="https://www.microsoft.com/en-us/cloud-platform/operations-management-suite">OMS(Operations Management Suite)</a> 와 통합되므로 고객은 OMS 로그 분석을 사용하여 정교한 세분화된 쿼리를 실행할 수 있습니다.</li>
  </ul>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/aad23373-ed3a-46a1-a36c-982e250e17ee.png"><img alt="WAF - Access Log" border="0" height="310" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/1701f816-3793-4ac2-8fbd-0fe84783cd89.png" style="border-top: 0px; border-right: 0px; background-image: none; border-bottom: 0px; float: none; padding-top: 0px; padding-left: 0px; margin-left: auto; border-left: 0px; display: block; padding-right: 0px; margin-right: auto" title="WAF - 액세스 로그" width="440"></a></p>


  <ul>
   <li>Application Gateway WAF는 곧 <a href="https://azure.microsoft.com/en-us/services/security-center/">Azure Security Center</a> 와 통합되어 모든 Azure 리소스에 대한 중앙 집중식 보안 보기를 제공합니다. Azure Security Center는 구독에서 취약성을 검사하고 검색된 문제에 대한 완화 단계를 권장합니다. 이러한 취약성 중 하나는 WAF로 보호되지 않는 웹 애플리케이션의 존재입니다.</li>
  </ul>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/5d9e369f-c560-4230-95c3-f5913aa53793.png"><img alt="WAF - 1" border="0" height="240" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/3a6e5777-1895-4250-905e-16ddf1a365a8.png" style="border-top: 0px; border-right: 0px; background-image: none; border-bottom: 0px; float: none; padding-top: 0px; padding-left: 0px; margin-left: auto; border-left: 0px; display: block; padding-right: 0px; margin-right: auto" title="WAF - 1" width="569"></a></p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/6c262667-d63b-48c3-b52e-e451c485af1e.png"><img alt="WAF - 2" border="0" height="268" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/2f16c1e8-0163-4be5-a834-a1186c2f5dc0.png" style="border-top: 0px; border-right: 0px; background-image: none; border-bottom: 0px; float: none; padding-top: 0px; padding-left: 0px; margin-left: auto; border-left: 0px; display: block; padding-right: 0px; margin-right: auto" title="WAF - 2" width="569"></a></p>


  <h3>사용자 지정</h3>


  <ul>
   <li>Application Gateway WAF는 탐지 또는 방지 모드에서 실행할 수 있습니다. 일반적인 사용 사례는 관리자가 트래픽에서 악의적인 패턴을 관찰하기 위해 탐지 모드에서 실행하는 경우입니다. 악용 가능성이 감지되면 방지 모드로 전환되어 의심스러운 수신 트래픽을 차단합니다.</li>
   <li>고객은 WAF RuleGroups를 사용자 지정하여 광범위한 범주 또는 하위 범주의 공격을 사용하거나 사용하지 않도록 설정할 수 있습니다. 따라서 관리자는 SQL 삽입 또는 XSS(교차 사이트 스크립팅)에 대해 RuleGroups를 사용하거나 사용하지 않도록 설정할 수 있습니다. 고객은 RuleGroup 내에서 특정 규칙을 사용하거나 사용하지 않도록 설정할 수도 있습니다. 예를 들어 프로토콜 변칙 규칙 그룹은 선택적으로 사용/사용하지 않도록 설정할 수 있는 많은 규칙의 컬렉션입니다.</li>
  </ul>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/7a7795ab-1e4e-41f3-89fb-a59a62f3eee0.png"><img alt="WAF - 3" border="0" height="389" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/1db5fa79-b6ea-430c-b4ea-23e3d049090d.png" style="border-top: 0px; border-right: 0px; background-image: none; border-bottom: 0px; float: none; padding-top: 0px; padding-left: 0px; margin-left: auto; border-left: 0px; display: block; padding-right: 0px; margin-right: auto" title="WAF - 3" width="549"></a></p>


  <h2>오픈 소스 수용</h2>


  <p>Application Gateway WAF는 가장 일반적인 웹 취약성으로부터 보호하기 위해 가장 인기 있는 WAF 배포 &ndash;&nbsp; <a href="https://www.modsecurity.org/crs/">OWASP ModSecurity Core 규칙 집합</a> 중 하나를 사용합니다. 엄격한 표준을 준수하는 이러한 규칙은 오픈 소스 커뮤니티에서 관리하고 유지 관리합니다. 고객은 규칙 집합 CRS 2.2.9와 CRS 3.0 중에서 선택할 수 있습니다. CRS 3.0은 가양성 감소를 크게 제공하므로 CRS 3.0을 사용하는 것이 좋습니다.</p>


  <h2>요약 및 다음 단계</h2>


  <p>웹 애플리케이션 방화벽의 일반 공급은 Application Gateway ADC 보안 제품에서 중요한 중요 시점입니다. 사용자 의견에 따라 WAF 기능 집합을 계속 개선할 것입니다. 현재 포털 또는 ARM 템플릿을 사용하여 Application Gateway 웹 애플리케이션 방화벽을 사용해 볼 수 있습니다. 자세한 정보 및 자세한 설명서 링크는 아래에 제공됩니다.</p>


  <ul>
   <li><a href="https://azure.microsoft.com/en-us/pricing/details/application-gateway/">Application Gateway WAF 가격 책정</a></li>
   <li>Application Gateway WAF에 대한 <a href="https://docs.microsoft.com/en-us/azure/application-gateway/application-gateway-web-application-firewall-overview">자세한 기술 세부 정보</a></li>
   <li><a href="https://docs.microsoft.com/en-us/azure/application-gateway/application-gateway-crs-rulegroups-rules">WAF 규칙 스키마 및 RuleGroup/규칙의 포괄적인 목록</a></li>
   <li>단계별 가이드를 <a href="https://docs.microsoft.com/en-us/azure/application-gateway/application-gateway-web-application-firewall-portal">만들어</a> <a href="https://docs.microsoft.com/en-us/azure/application-gateway/application-gateway-customize-waf-rules-portal">사용자 지정</a></li>
   <li><a href="https://github.com/Azure/azure-quickstart-templates/tree/master/101-application-gateway-waf/">ARM 템플릿으로 배포</a></li>
   <li><a href="https://docs.microsoft.com/en-us/rest/api/applicationgateway/">ARM API</a></li>
   <li>PowerShell 및 CLI 지원은 곧 제공될 예정입니다.</li>
  </ul>
