### YamlMime:Yaml
ms.openlocfilehash: 8531a097545035ddc6a9541862219e209d32064e
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139901795"
Slug: azure-managed-applications
Title: Azure 관리되는 애플리케이션
Summary: Azure Marketplace에서 Azure Managed Applications의 공개 미리 보기를 발표하게 되어 기쁩니다. Azure Managed Applications는 MSP(Managed Service Providers) ,... 지원하는 에코시스템을 제공합니다.
Content: >-
  <p>Azure Marketplace에서 Azure Managed Applications의 공개 미리 보기를 발표하게 되어 기쁩니다.</p>


  <p>Azure Managed Applications는 MSP(Managed Service Providers), ISV(Independent Software Vendor) 및 회사 중앙 IT 팀이 Azure Marketplace 또는 서비스 카탈로그를 통해 턴키 솔루션을 제공할 수 있는 에코시스템을 제공합니다. 고객은 이러한 관리되는 애플리케이션을 구독에 배포하지만 이 서비스의 주요 이점으로 유지 관리, 업데이트 또는 서비스를 제공할 필요가 없습니다&rsquo;. 공급업체는 이러한 애플리케이션을 관리하고 지원합니다. 즉, 고객은&rsquo; 이러한 애플리케이션을 서비스하는 데 필요한 애플리케이션별 도메인 지식 빌드에 투자할 필요가 없습니다. 그러므로 고객은 애플리케이션 관련 문제 해결 및 문제 진단을 염려하지 않고 애플리케이션 업데이트를 자동으로 얻을 수 있습니다.</p>


  <p>다른 쪽에서는 마켓플레이스를 통해 인프라 및 소프트웨어를 판매할 뿐만 아니라 Azure 고객에게 서비스 및 운영 지원을 연결하는 방법을 만드는 채널을 만듭니다. 이를 통해 공급업체는 Azure&#39;청구 시스템을 사용하여 고객에게 요금을 청구하고 템플릿을 사용하여 배포된 애플리케이션의 수명 주기를 관리할 수 있습니다. 이는 자체 포함되고 고객에게 봉인되어 공급업체가 더 높은 서비스 품질을 제공할 수 있도록 합니다. Azure의 이러한 에코시스템은 PaaS 및 SaaS 공급업체뿐만 아니라 솔루션을 패키지하고 재판매하려는 회사 중앙 플랫폼 팀과 시스템 통합자에게도 혜택을 줍니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/d1df38a9-c94d-4c11-8b7c-86422371e1a4.png"><img alt="ApplianceOverview" border="0" height="186" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/2f8292d7-05cf-4578-b56f-33afb94eb3b9.png" style="background-image: none; float: none; margin-left: auto; display: block; margin-right: auto; border-image: none" title="ApplianceOverview" width="610"></a></p>


  <p>Azure Managed Applications는 두 가지 버전으로 제공됩니다. 하나는 서비스 카탈로그 관리되는 애플리케이션이라고 하고 다른 하나는 Azure Marketplace 관리되는 애플리케이션이라고 합니다.</p>


  <h2>서비스 카탈로그</h2>


  <p>서비스 카탈로그를 사용하면 조직에서 Azure에 대해 승인된 솔루션의 카탈로그를 만들 수 있습니다. 이러한 솔루션 카탈로그를 유지 관리하는 것은 특정 조직 표준을 준수하면서 조직에 훌륭한 솔루션을 제공할 수 있으므로 엔터프라이즈의 중앙 IT 팀에 특히 유용합니다. 이러한 애플리케이션을 제어, 업데이트 및 유지 관리할 수 있습니다. 조직의 직원은 IT 부서에서 권장 및 승인한 풍부한 애플리케이션 집합을 손쉽게 검색할 수 있습니다. 고객은 자체 또는 조직의 다른 사용자가 공유한 서비스 카탈로그 관리형 애플리케이션만 볼 수 있습니다. 게시자는 <a href="https://docs.microsoft.com/en-us/azure/azure-resource-manager/managed-application-publishing" target="_blank">Azure CLI를 사용하여 이러한 서비스 카탈로그 관리형 애플리케이션을 만들 수 있습니다</a>. 고객은 현재 Azure Portal에서 게시된 관리되는 애플리케이션을 사용/만들 수 있습니다. 그러나 서비스 카탈로그 관리되는 애플리케이션 게시에 대한 지원은 곧 Azure Portal로 제공됩니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/43da6756-b27b-49f0-833e-16fb5bd30cae.png"><img alt="ServiceCatalog_Create" border="0" height="332" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/03fc8b5d-9266-44b4-9e75-256bbfe4d6a8.png" style="background-image: none; float: none; margin-left: auto; display: block; margin-right: auto; border-image: none" title="ServiceCatalog_Create" width="610"></a></p>


  <p><a href="https://docs.microsoft.com/en-us/azure/azure-resource-manager/managed-application-overview" target="_blank">서비스 카탈로그 관리형 애플리케이션을 게시하고 사용하는 방법에</a> 대해 자세히 알아봅니다.</p>


  <h2>Marketplace</h2>


  <p>다른 옵션은 Azure Marketplace 관리형 애플리케이션입니다. 이러한 애플리케이션은 Azure Portal의 마켓플레이스에서 사용할 수 있습니다. 공급업체에서 게시한 후에는 조직 내부 또는 외부의 모든 사용자가 사용할 수 있습니다. 이를 통해 MSP, ISV 및 SIS&rsquo;(시스템 통합자)는 모든 Azure 고객에게 솔루션을 제공할 수 있습니다. 고객은 심층적인 이해를 얻고 이러한 유지 관리에 투자하지 않고도 이러한 복잡한 솔루션을 활용하는 이점을 얻을 수 있습니다. 게시 시 게시자는 관리되는 애플리케이션 또는 관리되지 않는 솔루션 템플릿으로 제품을 사용할 수 있도록 하는 옵션을 가져옵니다.</p>


  <p>공급업체는 <a href="https://cloudpartner.azure.com/">Cloud 파트너 포털</a>을 사용하여 관리되는 애플리케이션을 Azure Marketplace에 게시할 수 있습니다. 관리되는 애플리케이션을 게시하는 주요 구성 요소에는 프로비전될 리소스를 설명하는 템플릿 파일과 이러한 리소스를 프로비전하는 데 필요한 입력이 포털에 표시되는 방법을 설명하는 UI 정의 파일이 포함됩니다. 필요한 파일은 .zip 파일로 패키지화되고 게시 포털을 통해 업로드됩니다. Pleas는 SKU Type&rdquo; 속성이 &ldquo;관리되는 애플리케이션과 솔루션 템플릿을 구분합니다. 다음은 게시 포털의 이미지입니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/1d9b3cb1-630d-4b37-adbf-fa378b62cac8.png"><img alt="newOffer_newSku" border="0" height="273" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/4d53ac4e-f5a5-4884-852f-5fcb2b3c4d4f.png" style="background-image: none; float: none; margin-left: auto; display: block; margin-right: auto; border-image: none" title="newOffer_newSku" width="610"></a></p>


  <p>제품이 게시되면 몇 가지 필수 구성 요소 검사, 유효성 검사 및 기타 검토를 진행합니다. 모든 검사가 통과되면 제품이 라이브 상태가 되며 공용 소비에 사용할 수 있게 됩니다. <a href="https://docs.microsoft.com/en-us/azure/azure-resource-manager/managed-application-overview">마켓플레이스 관리형 애플리케이션을 게시하는 방법에 대해</a> 자세히 알아보고 자세한 지침을 확인하세요.</p>


  <p>제품이 라이브 상태가 되면 Azure Marketplace에 표시되며 고객은 제품의 인스턴스를 만들 수 있습니다.</p>


  <h2>권한 부여</h2>


  <p>위에서 설명한 대로 공급업체는 고객이 프로비전하는 애플리케이션을 관리합니다. 공급업체가 애플리케이션을 성공적으로 관리할 수 있도록 하려면 공급업체에 이러한 리소스가 프로비전될 고객 구독의 리소스 그룹에 대한 특정 권한이 필요합니다. 관리되는 애플리케이션을 게시할 때 공급업체는 리소스 그룹에 대한 특정 권한이 있는 Azure AD 사용자, 사용자 그룹 또는 애플리케이션을 나타냅니다. 관리되는 애플리케이션에 필요한 리소스가 배포되는 위치입니다. 부여된 권한은 일반적으로 <a href="https://docs.microsoft.com/en-us/azure/active-directory/role-based-access-built-in-roles">Azure RBAC 기본 제공 역할</a> 중 하나입니다.</p>


  <p>또한 관리되는 애플리케이션은 고객을 위해 자체 포함 및 봉인되었다고 위에서 설명했습니다. 즉, 리소스를 프로비전 &ldquo;할 리소스 그룹이 고객에 대해 잠깁니다&rdquo; . 따라서 고객은 이 리소스 그룹의 리소스를 삭제하거나 변경할 수 없습니다.</p>


  <h2>요약</h2>


  <p>요약하자면, 다음은 관리되는 애플리케이션의 두 가지 특징 간의 주요 차이점을 설명하는 빠른 요약입니다.</p>


  <table border="0" cellpadding="2" cellspacing="0" width="3128">
   <tbody>
    <tr>
     <td valign="top">
     <table border="0" cellpadding="2" cellspacing="0">
      <tbody>
       <tr>
        <td valign="top">
        <blockquote dir="ltr" style="margin-right: 0px">
        <p>&nbsp;</p>
        </blockquote>
        </td>
        <td valign="top">
        <p align="left" dir="ltr" style="margin-right: 0px"><strong>서비스 카탈로그 관리형 애플리케이션</strong></p>
        </td>
        <td valign="top">
        <p align="left" dir="ltr" style="margin-right: 0px"><strong>Marketplace 관리형 애플리케이션</strong></p>
        </td>
       </tr>
       <tr>
        <td valign="top">
        <p align="left" dir="ltr" style="margin-right: 0px">게시 도구</p>
        </td>
        <td valign="top">
        <ul>
         <li>Azure CLI</li>
         <li>Azure Portal(출시 예정)</li>
         <li>Azure PowerShell(출시 예정)</li>
        </ul>
        </td>
        <td valign="top">
        <ul>
         <li>게시 포털</li>
        </ul>
        </td>
       </tr>
       <tr>
        <td valign="top">
        <p dir="ltr">Artifacts 필요</p>

        <blockquote dir="ltr" style="margin-right: 0px">
        <p>&nbsp;</p>
        </blockquote>
        </td>
        <td valign="top">
        <ul>
         <li>mainTemplate.json</li>
         <li>applianceMainTemplate.json</li>
         <li>applianceCreateUIDefinition.json</li>
        </ul>
        </td>
        <td valign="top">
        <ul>
         <li>mainTemplate.json</li>
         <li>applianceMainTemplate.json</li>
         <li>applianceCreateUIDefinition.json</li>
        </ul>
        </td>
       </tr>
       <tr>
        <td valign="top">
        <p dir="ltr" style="margin-right: 0px">사용 사례/이점</p>
        </td>
        <td valign="top">
        <ul>
         <li>
         <div align="left">조직 내의 개발자 및 사업부에 승인된 앱/서비스를 제공합니다.</div>
         </li>
         <li>
         <div align="left">중앙 IT에서 관리를 제공합니다.</div>
         </li>
         <li>
         <div align="left">거버넌스를 보장하면서 Azure에서 관리되는 애플리케이션을 가져옵니다.</div>
         </li>
         <li>
         <div align="left">Azure 리소스의 기본 복잡성에서 최종 사용자를 추상화합니다.</div>
         </li>
        </ul>
        </td>
        <td valign="top">
        <ul>
         <li>솔루션에 대한 전문 지식 및 회사별 IP로 수익을 창출할 수 있습니다.</li>
         <li>관리형 애플리케이션을 사용하고 팀에서 특정 인재를 채용/구축하여 비용/시장 출시 시간 혜택을 얻습니다.</li>
         <li>고유한 제품에서 혁신을 주도할 수 있는 기능을 갖춘 사용 패턴에 대한 직접적인 고객 접촉 및 이해.</li>
         <li>공급업체는 Azure 청구 시스템을 사용하여 고객에게 요금을 청구할 수 있습니다.</li>
        </ul>
        </td>
       </tr>
      </tbody>
     </table>
     </td>
    </tr>
   </tbody>
  </table>


  <h2>추가 리소스</h2>


  <ul>
   <li><a href="https://docs.microsoft.com/en-us/azure/azure-resource-manager/managed-application-author-marketplace">Marketplace 관리형 애플리케이션 게시</a></li>
   <li><a href="https://docs.microsoft.com/en-us/azure/azure-resource-manager/managed-application-publishing">서비스 카탈로그 관리되는 애플리케이션 게시</a></li>
   <li><a href="https://docs.microsoft.com/en-us/azure/azure-resource-manager/managed-application-createuidefinition-overview">관리되는 애플리케이션에 대한 UIDefinition을 만드는 방법</a></li>
   <li><a href="https://github.com/Azure/azure-managedapp-samples">관리되는 애플리케이션 샘플 GitHub 리포지토리</a></li>
  </ul>
