### YamlMime:Yaml
ms.openlocfilehash: dad778e25da837aef837a63f07df48eee7d90d29
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139911173"
Slug: azure-network-security
Title: Azure 네트워크 보안
Summary: Azure에서 보안은 디자인, 코드 개발, 모니터링, 작업, 위협 인텔리전스 및 대응과 같은 모든 단계에서 기본 제공됩니다. 클라우드의 폭과 규모에는 깊은 요구가 있다는 것을 이해합니다.
Content: >-
  <p>Azure에서 보안은 모든 Stepdesign&mdash;, 코드 개발, 모니터링, 작업, 위협 인텔리전스 및 응답에 기본 제공됩니다. 클라우드의 폭과 규모에는 소수의 개별 조직이 제공할 수 있는 보안 기술 및 프로세스에 대한 깊은 헌신이 필요합니다. 수십 년 동안 엔터프라이즈 소프트웨어를 구축하고 Microsoft Azure, Bing, Dynamics 365, Office 365, OneDrive 및 Xbox Live 같은 세계&rsquo; 최대의 온라인 서비스를 운영하면서 Microsofts&rsquo;의 고유한 보안 관점이 형성되었습니다. Microsoft는 수조 개의 신호와 수십억 개의 원본에서 개발된 위협 인텔리전스를 사용하여 매년 보안 기능에 10억 달러 이상을 투자하여 <a href="https://www.microsoft.com/en-us/security/default.aspx">Microsoft Secure</a>라는 포괄적인 접근 방식을 제공합니다. 자세한 내용은 <a href="https://blogs.microsoft.com/microsoftsecure/2016/07/25/introducing-the-microsoft-secure-blog/#oPsVUTrbHAFGKfJu.99">Microsoft Secure 블로그</a>를 참조하세요. <em> </em></p>


  <p>Weve&rsquo;는 보안 플랫폼을 만들고 보안 애플리케이션을 빌드하는 데 도움이 되는 서비스를 제공하기 위해 방대한 운영 환경을 적용했습니다. Microsoft의 약속은 Azure를 사용하여 애플리케이션, 데이터 및 ID를 보호할 수 있다는 것입니다. 광범위한 <a href="https://azure.microsoft.com/en-us/support/trust-center/">Azure 규정 준수 인증</a>을 통해 이 약속을 철회하여 클라우드 서비스 공급자 중 리더가 되었습니다. <a href="https://www.microsoft.com/en-us/trustcenter">Microsoft 보안 센터에서</a> 규정 준수 및 개인 정보에 대해 자세히 알아볼 수 있습니다.</p>


  <p>이 블로그에서는 네트워크 관점에서 보안에 초점을 맞추고 Azure 네트워크 기능을 사용하여 매우 안전한 클라우드 서비스를 빌드하는 방법을 설명합니다. 고객에게 보안 네트워크를 제공하는 방법을 강조 표시하는 네 가지 영역은 다음과 같습니다.</p>


  <ul>
   <li>기본은 고객 네트워크에 대한 격리 경계를 제공하는 보안 네트워크 패브릭을 제공하는 <a href="https://azure.microsoft.com/en-us/services/virtual-network/">Azure Virtual Network</a> 입니다.</li>
   <li>Virtual Network 구성 및 정책은 클라우드 애플리케이션을 보호합니다.</li>
   <li>활성 모니터링 시스템 및 도구는 보안 유효성 검사를 제공합니다.</li>
   <li>기본 제공 고급 보안 강화를 사용하는 기본 물리적 네트워크 인프라는 전체 글로벌 네트워크를 보호합니다.&nbsp;</li>
  </ul>


  <h2>단일 공유 실제 네트워크에서 고객 네트워크 격리</h2>


  <p>클라우드 서비스의 엄청난 성장을 지원하고 훌륭한 네트워킹 환경을 유지하기 위해 Microsoft는 데이터 센터와 고객을 연결하는 세계에서&mdash; <a href="https://azure.microsoft.com/en-us/blog/how-microsoft-builds-its-fast-and-reliable-global-network/">가장 큰 다크 파이버 백본 중 하나를 소유하고 운영</a>합니다. Azure에서는 공유 물리적 네트워크를 기반으로 논리 오버레이 네트워크를 실행하여 고객에게 격리된 프라이빗 네트워크를 제공합니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/44af250d-c902-4b2e-908d-829037151dae.jpg"><img alt="ANS2" border="0" height="296" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/5fa83b95-e4bd-4bcd-927d-02a669eb416f.jpg" style="border-top: 0px; border-right: 0px; background-image: none; border-bottom: 0px; float: none; padding-top: 0px; padding-left: 0px; margin-left: auto; border-left: 0px; display: block; padding-right: 0px; margin-right: auto" title="ANS2" width="551"></a></p>


  <p align="center"><em>그림 2. 격리된 고객 가상 네트워크는 동일한 실제 네트워크에서 실행됩니다. </em></p>


  <p>오버레이 네트워크는 Azures&rsquo; SDN(소프트웨어 정의 네트워킹) 스택에 의해 구현됩니다. 각 오버레이 네트워크는 API 호출을 통해 고객을 위해 요청 시 특별히 생성됩니다. 이러한 네트워크를 빌드하기 위한 모든 구성은 softwarethis&mdash;에서 수행되므로 Azure는 몇 초 만에 수천 대의 오버레이 네트워크를 만들도록 확장할 수 있습니다. 각 오버레이 네트워크는 고객&rsquo; VNet(Virtual Network)으로 구성된 자체 계층 3 라우팅 도메인입니다.</p>


  <h2>Azure Virtual Network</h2>


  <p>Azure Virtual Network는 온-프레미스 네트워크처럼 처리하는 네트워크 격리 및 보안 제어를 제공하는 안전한 논리 네트워크입니다. 각 고객은 자체&mdash; 개인 IP 주소 범위를 사용하고, 경로 테이블, 네트워크 보안 그룹, ACL(액세스 제어 목록), 게이트웨이 및 가상 어플라이언스를 구성하여 클라우드에서 워크로드를 실행하는 방식으로 자체 구조를 만듭니다.&nbsp;</p>


  <p>그림 3은 두 고객 가상 네트워크의 예를 보여줍니다. 고객 1s&rsquo; VNet은 온-프레미스 회사 네트워크에 연결되어 있지만 고객 2s&rsquo; VNet은 RDP(원격 데스크톱 프로토콜)를 통해서만 액세스할 수 있습니다. 인터넷에서 VM(가상 머신)으로의 네트워크 트래픽은 Azure 부하 분산 장치를 통과한 다음, VM을 실행하는 Windows Server 호스트&rsquo;로 이동합니다. 호스트 및 게스트 방화벽은 네트워크 포트 차단 및 ACL 규칙을 구현합니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/7d6f4fc5-cb44-413d-95b4-1f949c3ff7cd.png"><img alt="ANS3" border="0" height="356" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/1bd8c715-5657-4598-87e6-09272ca1ff48.png" style="border-top: 0px; border-right: 0px; background-image: none; border-bottom: 0px; float: none; padding-top: 0px; padding-left: 0px; margin-left: auto; border-left: 0px; display: block; padding-right: 0px; margin-right: auto" title="ANS3" width="585"></a></p>


  <p align="center"><em>그림 3. Azure Virtual Network에서 제공하는 고객 격리</em></p>


  <p>VNet에 배포된 VM은 개인 IP 주소를 사용하여 서로 통신할 수 있습니다. IP 주소 블록, DNS 설정, 보안 정책 및 라우팅 테이블을 제어합니다. 이점은 다음과 같습니다.</p>


  <ul>
   <li><strong>격리:</strong> VNet을 서로 격리할 수 있으므로 개발, 테스트 및 프로덕션을 위한 별도의 네트워크를 만들 수 있습니다. VNet이 서로 통신하도록 허용할 수도 있습니다.</li>
   <li><strong>보안:</strong> 네트워크 보안 그룹을 사용하여 서브넷 및 VM을 들어오고 나가는 트래픽을 제어할 수 있습니다.</li>
   <li><strong>연결:</strong> VNet 내의 모든 리소스가 연결됩니다. VNet 피어링을 사용하여 동일한 지역의 다른 Virtual Network와 연결할 수 있습니다. VPN(가상 사설망) 게이트웨이를 사용하여 온-프레미스 사이트와 다른 지역의 VNet에서 인터넷을 통해 VNet에 대한 IPsec 연결을 사용하도록 설정할 수 있습니다. ExpressRoute는 인터넷을 우회하는 VNet에 대한 프라이빗 네트워크 연결을 제공합니다.</li>
   <li><strong>고가용성:</strong> 부하 분산은 고객 애플리케이션에 고가용성 및 네트워크 성능을 제공하는 핵심 부분입니다. VM에 대한 모든 트래픽은 Azure Load Balancer 통과합니다.</li>
  </ul>


  <h2>애플리케이션 보안 유지</h2>


  <p><a href="https://www.csoonline.com/article/3146995/leadership-management/security-pros-most-worried-about-clouds-mobile.html">2016년 12월 보안 전문가를 대상으로 실시한 설문조사에 따르면</a> 전년 대비 가장 큰 신뢰도 하락은 웹 애플리케이션의 보안에 &ldquo;있는 것으로 나타났으며, 이는 80%에서 62%로 18포인트 하락한 수치입니다.&rdquo; Microsoft는 애플리케이션에 보안을 구축하고 고객이 개발 단계에서 서비스에 대한 액세스를 제어하는 방법까지 클라우드 호스팅 애플리케이션의 보안을 강화하는 데 도움이 되는 기능 및 서비스를 제공하여 잠재적인 취약성을 해결합니다.</p>


  <p>Azure에는 고객이 애플리케이션을 보호하는 데 사용할 수 있는 다양한 네트워킹 메커니즘 집합이 있습니다. 다음은 몇 가지 예제입니다.</p>


  <p>공용 엔드포인트 IP 주소에 대한 액세스를 제한하도록 네트워크 ACL을 구성할 수 있습니다. 엔드포인트의 ACL은 트래픽을 특정 원본 IP 주소로만 제한합니다.</p>


  <p>NSG(<a href="https://azure.microsoft.com/en-us/blog/network-security-groups/">네트워크 보안 그룹</a>)는 VNet의 VM에 대한 네트워크 액세스를 제어합니다. 이 네트워크 ACL 컬렉션을 사용하면 서브넷 또는 VM&rsquo; 네트워크 인터페이스를 입력하거나 종료하는 모든 트래픽에 전체 5개 튜플(원본 IP 주소, 원본 포트, 대상 IP 주소, 대상 포트, 프로토콜) 일련의 규칙을 적용할 수 있습니다. 서브넷 또는 VM에 연결된 NSG는 SDN 스택에 의해 적용됩니다.</p>


  <p>NVA(네트워크 가상 어플라이언스)는 VNet 보안 및 네트워크 기능을 강화하며&rsquo; <a href="https://azuremarketplace.microsoft.com/en-us">Azure Marketplace</a>를 통해 수많은 공급업체에서 사용할 수 있습니다. 고가용성 방화벽, 침입 방지, 침입 감지, WAF(웹 애플리케이션 방화벽), WAN 최적화, 라우팅, 부하 분산, VPN, 인증서 관리, Active Directory 및 다단계 인증을 위해 NVA를 배포할 수 있습니다.</p>


  <p>대부분의 기업에서는 특정 정책 적용을 위해 모든 네트워크 패킷에 대한 온-프레미스 검사를 요구하는 엄격한 보안 및 준수 요구 사항을 유지합니다. Azure는 ExpressRoute 또는 VPN을 통해 사용자 지정 경로 또는 BGP(Border Gateway Protocol) 광고를 만들어 VM에서 온-프레미스로 트래픽을 라우팅하는 강제 터널링이라는 메커니즘을 제공합니다.</p>


  <p>그림 4에서는 분리된 서브넷에서 NSG 규칙을 사용하고 프런트 엔드 서브넷을 보호하는 NVA를 사용하는 예제를 보여 줍니다.&nbsp;</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/27ca08da-42f8-4c4d-bbdc-aeba73b6d9b9.png"><img alt="ANS4" border="0" height="504" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/fdcff073-850e-4c5b-bd71-041fbe4d9ef3.png" style="border-top: 0px; border-right: 0px; background-image: none; border-bottom: 0px; float: none; padding-top: 0px; padding-left: 0px; margin-left: auto; border-left: 0px; display: block; padding-right: 0px; margin-right: auto" title="ANS4" width="441"></a></p>


  <p align="center"><em>그림 4. 네트워크 보안 그룹을 사용하여 빌드된 경계 네트워크 아키텍처</em></p>


  <p>계층 7 부하 분산 장치인 Azure <a href="https://docs.microsoft.com/en-us/azure/application-gateway/application-gateway-introduction">Application Gateway</a>는 가장 일반적인 웹 취약성으로부터 보호하기 위해 <a href="https://go.microsoft.com/fwlink/?linkid=845983">WAF(웹 애플리케이션 방화벽)</a> 기능도 제공합니다.</p>


  <p>IPsec을 사용하여 인터넷을 통해 온-프레미스에서 Azure로 안전하게 연결하거나 <a href="https://azure.microsoft.com/en-us/services/expressroute/">ExpressRoute</a>를 사용하여 개인 네트워크 연결을 통해 <a href="https://azure.microsoft.com/en-us/services/vpn-gateway/">VPN Gateway</a> 서비스에 액세스할 수 있습니다. 그림 4에서는 프런트 엔드(인터넷 연결) 웹 서버 및 백 엔드 애플리케이션 서버에 대해 서로 다른 규칙이 있는 NSG를 사용하여 Virtual Network 액세스를 제한할 수 있는 경계 네트워크&ndash; 스타일 강화 보안 디자인을 보여 줍니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/69b85027-cef3-4780-b7ab-cc2793d0fc8b.png"><img alt="ANS5" border="0" height="384" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/dad065a9-132d-400b-9696-ac4296d1dc45.png" style="border-top: 0px; border-right: 0px; background-image: none; border-bottom: 0px; float: none; padding-top: 0px; padding-left: 0px; margin-left: auto; border-left: 0px; display: block; padding-right: 0px; margin-right: auto" title="ANS5" width="559"></a></p>


  <p align="center"><em>그림 5. 온-프레미스에 연결된 인터넷 프런트 엔드 및 백 엔드에 연결된 보안 VNet</em></p>


  <p>더 많은 예제와 모범 사례는 <a href="https://docs.microsoft.com/en-us/azure/best-practices-network-security">Microsoft 클라우드 서비스 및 네트워크 보안을</a> 참조하세요.</p>


  <h2>보안 유효성 검사</h2>


  <p>Azure는 보안 이벤트를 모니터링, 방지, 감지 및 응답하는 다양한 도구를 제공합니다. 고객은 <a href="https://docs.microsoft.com/en-us/azure/security-center/security-center-intro">Azure Security Center</a>에 액세스할 수 있으므로 Azure 리소스의 보안을 파악하고 제어할 수 있습니다. 통합 보안 모니터링 및 정책 관리를 제공하고, 위협을 감지하고, 광범위한 보안 솔루션 에코시스템에서 작동합니다.</p>


  <p>또한 Azure 네트워크에 대한 모니터링, 진단 및 인사이트를 얻을 수 있는 <a href="https://azure.microsoft.com/en-us/services/network-watcher/">Network Watcher</a> 를 제공합니다. 네트워크 보안 및 성능을 모니터링하는 진단 및 시각화 도구를 사용하면 네트워크&rsquo; 문제를 식별하고 해결할 수 있습니다. 예를 들어 NSG로 들어오고 나가는 트래픽에 대한 정보를 보기 위해 Network Watcher는 <a href="https://docs.microsoft.com/en-us/azure/network-watcher/network-watcher-nsg-flow-logging-overview">NSG 흐름 로그를</a> 제공합니다. NSG가 제대로 배포되었는지 확인하고 리소스에 액세스하려는 권한이 없는 IP를 확인할 수 있습니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/204c0542-316e-4f28-97ec-58616d9f20a4.png"><img alt="ANS6" border="0" height="366" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/f92fb10a-2f53-477f-8cdc-46d186dd508c.png" style="border-top: 0px; border-right: 0px; background-image: none; border-bottom: 0px; float: none; padding-top: 0px; padding-left: 0px; margin-left: auto; border-left: 0px; display: block; padding-right: 0px; margin-right: auto" title="ANS6" width="546"></a></p>


  <p align="center"><em>그림 6. Network Watcher를 사용하여 NSG Flow 로그 캡처</em></p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/d9f7a42b-4b7f-4d24-acdb-96758f40d2ad.png"><img alt="ANS7" border="0" height="415" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/c8661550-0729-40ce-87a8-955b970f6fd7.png" style="border-top: 0px; border-right: 0px; background-image: none; border-bottom: 0px; float: none; padding-top: 0px; padding-left: 0px; margin-left: auto; border-left: 0px; display: block; padding-right: 0px; margin-right: auto" title="ANS7" width="550"></a></p>


  <p align="center"><em>그림 7. Power BI 사용하여 NSG Flow 로그 분석</em></p>


  <h2>네트워크 인프라 보안 강화</h2>


  <p><a href="https://www.ponemon.org/library/2015-cost-of-cyber-crime-united-states?s=+cost+of+cyber">2015년 Ponemon 연구에</a> 따르면 기업의 경우 보안 위반당 평균 비용은 1,500만 달러입니다. 조직&rsquo; 자산을 보호하기 위해 Microsoft 클라우드 데이터 센터는 경계 펜싱, 비디오 카메라, 보안 담당자, 보안 입구, 실시간 통신 네트워크 및 모든 물리적 서버를 비롯한 심층 방어 보안 계층으로 보호됩니다. 이러한 정기적으로 감사되는 보안 조치는 Azure가 강력한 규정 준수 인증 포트폴리오를 달성하는 데 도움이 됩니다.&nbsp;</p>


  <p>수년 동안 Weve&rsquo;는 온라인 범죄자 및 해커로부터 고객을 보호하기 위해 <a href="https://blogs.microsoft.com/blog/2013/12/04/protecting-customer-data-from-government-snooping/#01svD48xbI8t3Cjs.99">제품 및 서비스에서 암호화</a> 를 사용했습니다. 우리는 고객 데이터가 침해되는 기회를 원하지 않으며&rsquo;이 문제를 정면으로 해결하고 있습니다. Microsoft는 네트워크 및 서비스 전반에 걸쳐 고객 데이터의 암호화를 강화하기 위한 포괄적인 엔지니어링 노력을 기울이고 있습니다. 이러한 노력은 고객이 만든 콘텐츠의 전체 수명 주기에 걸쳐 보호를 제공합니다.</p>


  <p><a href="https://azure.microsoft.com/en-us/blog/how-microsoft-builds-its-fast-and-reliable-global-network/">데이터 센터 간의 Azure 트래픽</a> 은 글로벌 네트워크에 유지되며 인터넷을 통해 흐르지 않습니다. 여기에는 전 세계 어디서나 Microsoft Azure 퍼블릭 클라우드 서비스 간의 모든 트래픽이 포함됩니다. 예를 들어 Azure 내에서 VM, 스토리지 및 SQL 간의 트래픽은 원본 및 대상 지역에 관계없이 Microsoft 네트워크에 유지됩니다. 지역 내 VNet 간 트래픽과 지역 간 VNet 간 트래픽은 Microsoft 네트워크에 유지됩니다.</p>


  <p>DDoS(분산 서비스 거부) 공격은 지속적으로 증가하는 위협입니다. 이러한 공격의 증가하는 규모와 복잡성으로부터 보호하려면 글로벌 규모로 배포된 중요한 인프라가 필요합니다. Azure에는 모든 Microsoft 클라우드 서비스를 보호하는 기본 제공 DDoS 보호 시스템이 있습니다. 따라서 모든 Azure 공용 IP는 모든 Azure 데이터 센터에 배포된 이 보호에 속합니다. DDoS 시스템은 동적 위협 탐지 알고리즘을 사용하여 일반적인 DDoS 대량 공격(예: UDP 홍수, SYN-ACK 공격 또는 리플렉션 공격)을 방지합니다. 매일 수백 번의 완화된 공격 시도를 모니터링하고 보호를 지속적으로 확장합니다.</p>


  <p>또한 Azure 자체는 인터넷을 통해 활성 모니터링 및 인텔리전스 수집을 통해 보호됩니다. Microsoft는 어두운 웹에 대한 위협 인텔리전스 연구를 지속적으로 수행하여 잠재적인 위험과 공격을 식별하고 완화합니다. 이 지식은 보호 기술 및 완화에 적용됩니다. <a href="https://blogs.microsoft.com/microsoftsecure/2017/01/17/microsofts-cyber-defense-operations-center-shares-best-practices/">Microsoft 사이버 방어 운영 센터는</a> 당사의 약속을 강조하면서 보안 인시던트에 대응합니다.</p>


  <p>이러한 투자를 종합하면 Azure에서 실행되는 서비스를 보호하기 위해 그림 8에 표시된 것처럼 계층화된 보안 모델을 제공합니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/4f83d04e-0df1-4fc2-920c-f4df2a38f195.png"><img alt="ANS8" border="0" height="262" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/b4288b7a-ffe9-48ce-a74f-92b6696cc11e.png" style="border-top: 0px; border-right: 0px; background-image: none; border-bottom: 0px; float: none; padding-top: 0px; padding-left: 0px; margin-left: auto; border-left: 0px; display: block; padding-right: 0px; margin-right: auto" title="ANS8" width="533"></a></p>


  <p align="center"><em>그림 8. Azure 보안에 대한 계층화된 접근 방식</em></p>


  <h2>보안 Azure 네트워킹</h2>


  <p>Azure는 보안에 상당한 투자를 했습니다. 고객은 Virtual Network 및 기타 보안 기능 및 서비스를 사용하여 클라우드 애플리케이션을 디자인, 구성 및 모니터링할 수 있습니다. 우리는 끊임없이 변화하는 새로운 사이버 위협에 대처하기 위해 글로벌 인프라를 적극적으로 모니터링하고 지속적으로 강화합니다.</p>


  <p>Microsoft는 네트워크 보안 공격 방지를 선도하고 있습니다. 가장 인기 있는 클라우드 서비스를 실행하는 글로벌 공간과 경험을 통해 네트워크를 보호하고 서비스를 보호하는 데 도움이 되는 규모와 다양한 입력을 제공합니다. Azure에서 서비스를 안전하게 준수하고&mdash;, 배포, 모니터링 및 실행할 수&mdash; 있도록 네트워크 보안 기술에 계속 투자할 것입니다. Microsoft는 비즈니스를 안전하게 운영하기 위한 파트너입니다.</p>


  <p><iframe allowfullscreen="" frameborder="0" height="540" src="https://channel9.msdn.com/Blogs/Azure/Azure-Network-Security/player" width="960"></iframe></p>


  <h2>자세히 알아보기</h2>


  <p>이 시리즈에서 더 많은 게시물을 읽으려면 다음을 방문하세요.</p>


  <ul>
   <li><a href="https://azure.microsoft.com/en-us/blog/networking-innovations-that-drive-the-cloud-disruption/">클라우드 중단을 유도하는 네트워킹 혁신</a></li>
   <li><a href="https://azure.microsoft.com/en-us/blog/sonic-the-networking-switch-software-that-powers-the-microsoft-global-cloud/">SONiC: Microsoft 글로벌 클라우드를 지원하는 네트워킹 전환 소프트웨어</a></li>
   <li><a href="https://azure.microsoft.com/en-us/blog/how-microsoft-builds-its-fast-and-reliable-global-network/">Microsoft에서 빠르고 신뢰할 수 있는 글로벌 네트워크를 구축하는 방법</a></li>
   <li><a href="https://azure.microsoft.com/en-us/blog/lighting-up-network-innovation/">네트워크 혁신 조명</a></li>
  </ul>
