### YamlMime:Yaml
ms.openlocfilehash: c558eb214d9cd40ac29af7fdbc17844ee587a919
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139908603"
Slug: azure-sql-data-warehouse-releases-new-capabilities-for-performance-and-security
Title: Azure SQL Data Warehouse는 성능 및 보안을 위한 새로운 기능을 릴리스합니다.
Summary: 저장되고 쿼리되는 데이터 양이 계속 늘고 있어서 가격 대비 성능이 가장 좋은 데이터 웨어하우스를 갖추는 일이 점점 더 중요해지고 있습니다. Gigaom의 TPC-H 및 TPC-DS 벤치마크 보고서 모두에서 업계 리더가 된 것에 대해 기쁘게 생각하지만 고객을 대신하여 혁신을 중단할 계획은 없습니다.
Content: >-
  <p>저장되고 쿼리되는 데이터 양이 계속 늘고 있어서 가격 대비 성능이 가장 좋은 데이터 웨어하우스를 갖추는 일이 점점 더 중요해지고 있습니다. &rsquo;Gigaoms&rsquo; <a href="https://azurecomcdn.azureedge.net/cvt-cf58e036f3a90892f94ad7c7e3793eca0f3c6a6f55e2745bb083941a1d34ed8a/mediahandler/files/resourcefiles/data-warehouse-in-the-cloud-benchmark/FINAL%20data-warehouse-cloud-benchmark.pdf">TPC-H</a> 및 <a href="https://azurecomcdn.azureedge.net/cvt-cf58e036f3a90892f94ad7c7e3793eca0f3c6a6f55e2745bb083941a1d34ed8a/mediahandler/files/resourcefiles/cloud-data-warehouse-performance-testing/FINAL%20GigaOm%20Report_cloud-data-warehouse-performance-testing.pdf">TPC-DS</a> 벤치마크 보고서 모두에서 업계 리더가 되는 것에 대해 기쁘게 생각하지만 고객을&rsquo; 대신하여 혁신을 중단할 계획은 없습니다.</p>


  <p>Rohan Kumar가 월요일에 자신의 <a href="https://azure.microsoft.com/en-us/blog/analytics-in-azure-remains-unmatched-with-new-innovations/">블로그</a>에서 언급했듯이 Azure SQL Data Warehouse를 <b>가격 성능,</b>&rsquo; 유연성 및 <b>보안</b> 분야의 타의 추종을 불허하는 업계 선두 업체로 만들 수 있는 몇 가지 새로운 기능을 도입하게 되어 기쁩니다.</p>


  <p>고객이 추가 비용을 추가하지 않고 애플리케이션의 성능을 계속 개선할 수 있도록 <strong>결과 집합 캐싱</strong>,&rsquo; <strong>구체화된 뷰</strong> 및 <strong>순서가 지정된 클러스터형 columnstore 인덱스의</strong> 미리 보기 가용성을 발표합니다.</p>


  <p>가격 대비 성능 향상&rsquo; 외에도 고객이 더 민첩하고 유연하게 사용할 수 있는 새로운 기능을 추가했습니다. 첫 번째는 <strong>워크로드 중요도</strong>입니다. 이 기능은 충돌하는 요구 사항이 있는 워크로드의 우선 순위를 지정하는 방법을 사용자가 결정할 수 있는 새로운 기능입니다. 둘째, 자동 통계 유지 관리(<strong>자동 업데이트 통계</strong>)에 대한 새로운 지원은 Azure SQL Data Warehouse의 관리 효율성과 유지 관리가 더 쉽고 효과적임을 의미합니다. 마지막으로 JSON&rsquo; 데이터 관리 및 쿼리에 대한 지원도 추가했습니다.<strong> </strong> 이제 사용자는 <strong>JSON 데이터를</strong> 데이터 웨어하우스에 직접 로드하고 다른 관계형 데이터와 혼합하여 더 빠르고 쉬운 인사이트를 얻을 수 있습니다.</p>


  <p>마지막 발표는 보안 및 개인 정보 보호에 중점을 둡니다. 아시다시피 클라우드에 데이터 웨어하우징 솔루션을 배포하려면 정교하고 강력한 보안이 필요합니다. Azure SQL Data Warehouse는 이미 고급 보안 모델을 배포할 수 있게 해 주지만, 오늘은&rsquo; DDM(<strong>동적 데이터 마스킹</strong>)에 대한 지원을 발표했습니다. DDM을 사용하면 사용자 정의 정책을 통해 개인 데이터를 보호할 수 있으므로&rsquo; 볼 수 있는 권한이 있는 사용자에게만 표시되도록 할 수 있습니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/e247a71c-bd6d-4381-9e2a-8904fadb447d.png"><img alt="Azure SQL Data Warehouse is a critical piece of the big data pipeline." border="0" height="204" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/8d723883-2ad6-4b61-b5f6-3f08b8790ea8.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="" width="499"></a></p>


  <p>아래&rsquo; 섹션에서는 이러한 새로운 기능과 각 기능이 제공하는 이점에 대해 자세히 설명합니다.</p>


  <h2>가격-성능</h2>


  <p>가격 성능은 놀라운 가치로 가장 빠른 분석 서비스 중 하나를 제공하기 때문에 릴리스에서 재귀 테마입니다. 오늘 발표 된 새로운 기능을 통해 우리는 선도적 인 가격 성능 플랫폼을 제공하기 위한 우리의 노력을 계속 보여줍니다.</p>


  <h3>결과 집합 캐싱을 사용한 대화형 대시보드(미리 보기)</h3>


  <p>대화형 대시보드에는 예측 가능하고 반복적인 쿼리 패턴이 제공됩니다. 현재 미리 보기로 제공되는 결과 집합 캐싱은 비즈니스 분석가 및 보고 사용자에 대한 인사이트 시간을 줄이면서 즉각적인 쿼리 응답 시간을 가능하게 하므로 이 시나리오에 도움이 됩니다.</p>


  <p>결과 집합 캐싱을 사용하도록 설정하면 Azure SQL Data Warehouse는 반복 쿼리의 결과를 자동으로 캐시하므로 후속 쿼리 실행은 전체 쿼리 실행을 생략하는 지속형 캐시의 결과를 반환합니다. 컴퓨팅 주기를 줄일 뿐 아니라 결과 집합 캐시에 의해 충족되는 쿼리는 동시성 슬롯을 사용하지 않으므로 기존 동시성 한도에 포함되지 않습니다. 보안을 위해 적절한 보안 자격 증명이 있는 사용자만 캐시의 결과 집합에 액세스할 수 있습니다.</p>


  <h3>성능 향상을 위한 구체화된 뷰(미리 보기)</h3>


  <p>광범위한 쿼리 집합에 대한 쿼리 성능을 크게 향상시키는 또 다른 새로운 기능은 구체화된 뷰 지원이며, 이제 미리 보기에서 사용할 수 있습니다. 구체화된 뷰는 간단한 유지 관리 작업을 제공하면서 복잡한 쿼리(일반적으로 조인 및 집계를 사용하는 쿼리)의 성능을 향상시킵니다.</p>


  <p>구체화된 뷰를 만들면 Azure SQL Data Warehouse 쿼리 최적화 프로그램이 사용자 쿼리를 투명하게 자동으로 다시 작성하여 배포된 구체화된 뷰를 활용하므로 쿼리 성능이 향상됩니다. 무엇보다도 데이터가 기본 테이블에 로드되면 Azure SQL Data Warehouse는 구체화된 뷰를 자동으로 유지 관리하고 새로 고쳐 유지 관리 및 관리에 대한 간소화된 보기를 제공합니다. 사용자 쿼리가 구체화된 뷰를 활용함에 따라 쿼리는 훨씬 더 빠르게 실행되고 시스템 리소스를 적게 사용합니다. 보기 내에서 쿼리가 더 복잡하고 비용이 많이 들수록 실행 시간 절약에 더 큰 가능성이 있습니다.</p>


  <h3>정렬된 클러스터형 columnstore 인덱스를 사용하여 빠른 검색(미리 보기)</h3>


  <p>columnstore는 대량의 데이터를 저장하고 효율적으로 쿼리하기 위한 핵심 기능입니다. 각 테이블에 대해 들어오는 데이터를 행 그룹으로 나누고 행 그룹의 각 열은 디스크에서 세그먼트를 형성합니다. columnstore 인덱스를 쿼리할 때 사용자 쿼리와 관련된 열 세그먼트만 디스크에서 읽습니다. 순서가 지정된 클러스터형 columnstore 인덱스는 효율적인 세그먼트 제거를 지원하여 쿼리 실행을 좀 더 최적화합니다.</p>


  <p>미리 정렬된 데이터로 인해 디스크에서 읽는 세그먼트 수를 크게 줄여 쿼리 처리 속도가 빨라질 수 있습니다. 이제 정렬된 클러스터형 columnstore 인덱스를 미리 보기로 사용할 수 있으며 필터 및 조건자가 포함된 쿼리는 이 기능의 이점을 크게 활용할 수 있습니다.</p>


  <h2>유연성</h2>


  <p>비즈니스 요구 사항이 발전함에 따라 솔루션 동작을 변경하고 조정하는 기능은 최신 데이터 웨어하우징 제품의 주요 이점 중 하나입니다. 사용 편의성과 관리를 제공하면서 기업이 가지고 있는 다른 유형의 데이터를 처리하고 관리하는 기능은 매우 중요합니다. 이러한 요구를 지원하기 위해 Azure SQL Data Warehouse는 끊임없이 진화하는 요구 사항을 처리하는 데 도움이 되는 다음과 같은 새로운 기능을 도입하고 있습니다.</p>


  <h3>워크로드 중요도를 사용하여 워크로드 우선 순위 지정(일반 공급)</h3>


  <p>분석 솔루션에서 혼합 워크로드를 실행하는 것은 비즈니스 프로세스를 효과적이고 신속하게 실행해야 하는 경우가 많습니다. 리소스가 제한된 상황에서는 전체 솔루션 비용 관리에 도움이 되므로 먼저 실행해야 하는 워크로드를 결정하는 기능이 중요합니다. 예를 들어 임원 대시보드 보고서는 임시 쿼리보다 더 중요할 수 있습니다. 이제 워크로드 중요도를 통해 이 시나리오를 사용할 수 있습니다. 중요도가 높은 요청은 미리 정의된 SLA를 충족하고 중요한 요청의 우선 순위를 지정하는 데 도움이 되는 리소스에 대한 더 빠른 액세스를 보장합니다.</p>


  <h3>워크로드 분류 개념</h3>


  <p>워크로드 우선 순위를 정의하려면 다양한 요청을 분류해야 합니다. Azure SQL Data Warehouse는 SQL 쿼리, 데이터베이스 사용자, 데이터베이스 역할, Azure Active Directory 로그인 또는 Azure Active Directory 그룹에 대해 설정할 수 있는 유연한 분류 정책을 지원합니다. 워크로드 분류는 새 <a href="https://docs.microsoft.com/sql/t-sql/statements/create-workload-classifier-transact-sql?view=azure-sqldw-latest">CREATE WORKLOAD CLASSIFIER</a> 구문을 사용하여 수행됩니다.</p>


  <p>아래 다이어그램은 워크로드 분류 및 중요도 함수를 보여 줍니다.</p>


  <p><i><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/b95ed62e-c6fc-467e-843f-19894ecc9fda.gif"><img alt="The classifier assigns incoming requests to a workload group and assigns importance based on the parameters specified in the classifier statement definition." height="264" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/c23b1701-df11-4116-84b9-929e98ec5d02.gif" style="margin-right: auto; margin-left: auto; float: none; display: block;" title="" width="320"></a></i></p>


  <h3>워크로드 중요도 개념</h3>


  <p><a href="https://docs.microsoft.com/azure/sql-data-warehouse/sql-data-warehouse-workload-importance">워크로드 중요</a> 도는 분류를 통해 설정됩니다. <em>중요도</em> 는 요청자가 메모리, CPU, IO 및 잠금을&nbsp; 포함한 시스템 리소스에 대한 액세스를&#39;영향을 줍니다. 요청은 낮음, below_normal, 정상, above_normal 및 높음의 5가지 중요도 수준 중 하나를 할당할 수 있습니다. 중요도가 above_normal 요청이 예약된 경우 기본 <i>정상</i> 중요도의 요청 전에 리소스에 액세스합니다.</p>


  <p><i><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/c80605c9-3e27-4a14-9403-e7c6b5ead006.gif"><img alt="With workload importance, you can easily ensure that important queries immediately get access to resources." height="252" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/b5413815-8030-4259-996f-4956fe4f2c58.gif" style="margin-right: auto; margin-left: auto; float: none; display: block;" title="" width="360"></a></i></p>


  <h3>JSON 데이터 관리 및 쿼리(미리 보기)</h3>


  <p>조직은 점점 더 여러 데이터 원본과 다른 유형의 파일 형식을 처리하는 것에 직면하고 있으며, JSON은 CSV 파일을 제외하고 상위 데이터 원본 중 하나입니다. 인사이트 시간을 단축하고 불필요한 데이터 변환 프로세스를 최소화하기 위해 Azure SQL Data Warehouse를 통해 JSON 데이터 쿼리를 지원할 수 있습니다. 이 기능은 이제 미리 보기에서 사용할 수 있습니다.</p>


  <p>비즈니스 분석가는 이제 친숙한 T-SQL 언어를 사용하여 JSON 데이터로 형식이 지정된 문서를 쿼리하고 조작할 수 있습니다. 이제 Azure SQL Data Warehouse에서 JSON_VALUE, JSON_QUERY, JSON_MODIFY 및 OPENJSON과 같은 JSON 함수가 지원됩니다. 이제 Azure SQL Data Warehouse는 두 데이터 간의 조인을 포함하여 관계형 데이터와 비관계형 데이터를 효과적으로 지원할 수 있으며, 사용자는 Power BI 같은 기존 BI 도구를 사용할 수 있습니다.</p>


  <h3>자동 통계 유지 관리 및 업데이트(미리 보기)</h3>


  <p>Azure SQL Data Warehouse는 최적의 실행 계획이 생성되고 사용되도록 비용 기반 최적화 관리자를 구현합니다. 비용 기반 최적화 프로그램이 효과적이려면 열 수준 통계가 필요합니다. 이러한 통계가 부실하면 최적이 아닌 계획을 선택할 수 있으므로 쿼리 성능이 저하될 수 있습니다.</p>


  <p>현재 통계&rsquo;를 자동으로 새로 고치고 유지 관리하는 기능을 추가하여 자동 통계 생성에 대한 지원을 확장합니다. 데이터 웨어하우스 테이블이 로드되고 업데이트되면 시스템은 이제 오래된 통계를 자동으로 검색하고 업데이트할 수 있습니다. 이제 미리 보기에서 자동 업데이트 통계 기능을 사용할 수 있으므로 Azure SQL Data Warehouse는 통계 유지 관리 프로세스를 간소화하면서 전체 통계 관리 기능을 제공합니다. 더 이상 통계를 수동으로 유지 관리할 필요가 없으므로 간소화되고 비용 효율적인 데이터 웨어하우스 배포가 발생합니다.</p>


  <h2>보안</h2>


  <p>Azure SQL Data Warehouse는 시장에서 가장 고급 보안 및 개인 정보 보호 기능 중 하나를 제공합니다. 이는 입증된 SQL Server 기술을 사용하여 달성됩니다. SQL Server Azure SQL Data Warehouse의 핵심 기술 및 구성 요소로서 <a href="https://nvd.nist.gov/">NIST 국가 취약성 데이터베이스</a>에 따르면 지난 8년 동안 가장 취약한 데이터베이스였습니다. 기존 Azure SQL Data Warehouse&#39;보안 및 개인 정보 보호 기능을&rsquo; 확장하기 위해 이제 미리 보기에서 DDM(동적 데이터 마스킹) 지원을 사용할 수 있습니다.</p>


  <h3>동적 데이터 마스킹을 사용하여 중요한 데이터 보호(미리 보기)</h3>


  <p>DDM(<a href="https://docs.microsoft.com/en-us/sql/relational-databases/security/dynamic-data-masking?toc=%2Fazure%2Fsql-data-warehouse%2Ftoc.json&amp;view=sql-server-2017">동적 데이터 마스킹)을</a> 사용하면 관리자와 데이터 개발자가 회사&rsquo; 데이터에 대한 액세스를 제어하여 중요한 데이터를 안전하고 제한할 수 있습니다. 즉석에서 데이터를 가리면 프라이빗 데이터에 대한 무단 액세스를 방지합니다. 사용자 정의 데이터 마스킹 정책에 따라 Azure SQL Data Warehouse는 쿼리가 실행되고 결과가 사용자에게 표시되기 전에 데이터를 동적으로 난독 처리할 수 있습니다.</p>


  <p><i><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/283fe5f4-a7d6-4860-9e20-c4f219bfec48.gif"><img alt="Dynamic Data Masking with Azure SQL Data Warehouse prevents unauthorized access to private data by obscuring the data on-the-fly." height="238" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/d6c01a8b-f527-4674-b497-3bd1568854b0.gif" style="margin-right: auto; margin-left: auto; float: none; display: block;" title="" width="402"></a></i></p>


  <p>Azure SQL Data Warehouse는 엔진 내에서 직접 DDM 기능을 구현합니다. DDM을 사용하여 테이블을 만들 때 정책은 시스템&#39;메타데이터에 저장되고 쿼리가 실행될 때 엔진에 의해 적용됩니다. 이 중앙 집중식 정책 적용 프로세스는 애플리케이션 계층에서 액세스 제어가 구현되고 반복되지 않으므로 데이터 마스킹 규칙 관리를 간소화합니다. 다양한 사용자가 쿼리 테이블에 액세스하면 중요한 데이터를 보호하면서 정책이 자동으로 적용되고 적용됩니다. DDM에는 유연한 정책이 제공되며 선택한 열의 일부 데이터를 노출하는 부분 마스크 또는 데이터를 완전히 난독 처리하는 전체 마스크를 정의하도록 선택할 수 있습니다. Azure SQL Data Warehouse는 사용자가 선택할 수 있는 기본 제공 마스킹 기능도 제공합니다.</p>


  <h2>다음 단계</h2>


  <ul>
   <li>무료 <a href="https://azure.microsoft.com/en-us/free/sql-data-warehouse/">Azure SQL Data Warehouse 계정을 시작합니다</a>.</li>
   <li><a href="https://www.youtube.com/watch?v=QcCRBAhoXpM&amp;index=8&amp;list=PLLasX02E8BPClOvjNV9bXk3LUuf3nQiS2">워크로드 관리 개념 및 워크로드</a> <a href="https://www.youtube.com/watch?v=_2rLMljOjw8&amp;index=7&amp;list=PLLasX02E8BPClOvjNV9bXk3LUuf3nQiS2">관리 시나리오</a>에 대해 자세히 알아봅니다.</li>
   <li> <a href="https://aka.ms/simply-unmatched">Azure의 whyanalytics가 단순히 일치하지 않는</a> 이유에 대해 자세히 알아봅니다.</li>
  </ul>


  <p>이 블로그에 언급된 미리 보기 기능은 모든 지역에 배포됩니다. <a href="https://docs.microsoft.com/en-us/azure/sql-data-warehouse/release-notes#checking-the-code-version-that-has-been-applied-to-your-data-warehouse">인스턴스에 배포된 버전을 확인하고</a> 최신 <a href="https://docs.microsoft.com/en-us/azure/sql-data-warehouse/release-notes">Azure SQL Data Warehouse 릴리스 정보를</a> 검토하여 자세히 알아보세요. 미리 보기 질문은 문의 <a>AskADWPreview@microsoft.com</a>하세요.</p>
