### YamlMime:Yaml
ms.openlocfilehash: 1f6f67a5cf1ccf87e667d5d400729437817c5693
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139906877"
Slug: azure-application-insights-javascript-sdk-reliability-and-performance-improvements
Title: 'Azure Application Insights JavaScript SDK: 안정성 및 성능 향상'
Summary: >
  최근에 Application Insights 웹 페이지 모니터링의 견고성이 향상되었으며 쿠키를 사용하지 않는 기능이 도입되었습니다. 이제 제한 및 네트워크 문제와 페이지가 언로드될 때 전송의 안정성이 향상되었습니다. Azure Application Insights 사용하여 앱의 성능 및 사용량을 모니터링할 수 있습니다. JavaScript의 작은 코드 조각을 사용하면 페이지 로드 및 AJAX 호출의 타이밍, 브라우저 예외 및 AJAX 실패의 개수 및 세부 정보뿐만 아니라 사용자 및 세션 수를 얻을 수 있습니다.
Content: >-
  <p>최근에 <a href="https://azure.microsoft.com/services/application-insights/">Application Insights</a> 웹 페이지 모니터링의 견고성이 향상되었으며 쿠키를 사용하지 않는 기능이 도입되었습니다. 이제 제한 및 네트워크 문제와 페이지가 언로드될 때 전송의 안정성이 향상되었습니다.</p>


  <p>Azure Application Insights 사용하여 앱의 성능 및 사용량을 모니터링할 수 있습니다. JavaScript의 작은 코드 조각을 사용하면 페이지 로드 및 AJAX 호출의 타이밍, 브라우저 예외 및 AJAX 실패의 개수 및 세부 정보뿐만 아니라 사용자 및 세션 수를 얻을 수 있습니다. 시작하는 방법에 대한 자세한 내용은 <a href="https://docs.microsoft.com/azure/application-insights/app-insights-javascript">설명서를</a> 참조하세요.</p>


  <h2>새로운 JavaScript SDK 기능</h2>


  <p>내부 개선 사항 외에도 몇 가지 버그를 수정하고, SDK를 정리하고, 몇 가지 추가 기능을 추가했습니다.</p>


  <h3>NPM 패키지에 snippet.js 추가합니다.</h3>


  <p><a href="https://github.com/Microsoft/ApplicationInsights-JS/commit/3c110ae3815b7133a45366c5a6c1a93adaeca585">Snippet.js</a> Gulp 파이프라인을 사용하여 인라인 JavaScript를 사용하는 대신 별도의 파일에서 Application Insights를 사용하려는 사용자에게 사용되는 파일입니다. <a href="https://github.com/RehanSaeed">레한사에드</a>. 감사 무하마드 레한!</p>


  <h3>쿠키를 사용하지 않도록 설정하는 옵션</h3>


  <p>이는 일부 사용자의 질문이었습니다. 이제 쿠키를 사용하지 않도록 설정할 수 있지만 일부 기능이 손실됩니다. 쿠키가 없으면 모든 페이지 보기가 새 사용자 및 세션으로 계산됩니다. 자세한 구성 옵션은 <a href="https://github.com/Microsoft/ApplicationInsights-JS/blob/master/API-reference.md#config">애플리케이션 Insights SDK JavaScript API</a>를 참조하세요.</p>


  <h3>종속성 상관 관계 헤더 사용</h3>


  <p>이제 기본적으로 해제되어 있지만 수동으로 사용하도록 설정할 수 있습니다. 종속성을 서버 요청과 상호 연결하려면 구성 파일의 disableCorrelationHeaders를 <i>false</i>로 설정합니다. 이 기능을 옵트인하면 클라이언트 쪽 AJAX 호출과 상관 관계가 있는 서버 요청을 볼 수 있습니다.</p>


  <h2>JavaScript SDK 개선 사항</h2>


  <p>온보딩 시 추가 작업 없이 JavaScript SDK를 상승시키는 다음과 같은 개선 사항이 있습니다.</p>


  <h3>보안</h3>


  <p>JS SDK가 https로 완전히 전환되었습니다. 이제 https를 사용하여 모든 원격 분석을 보내고 라이브러리를 다운로드합니다. 또한 모든 보안 사이트에 대해 SDK는 보안 플래그가 있는 쿠키를 만듭니다. <a href="https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie">집합 쿠키 설명서</a>에 대한 자세한 정보입니다.&nbsp;</p>


  <h3>전송</h3>


  <p>Application Insights JavaScript SDK의 가장 큰 목표 중 하나는 계측된 페이지를 어떤 방식으로든 저하시키지 않으면서 최대한 많은 기능을 제공하는 것입니다. 여기에는 성능 및 사용자 환경이 포함됩니다. 전송 안정성은 SDK&rsquo;의 중요한 부분이기 때문에 최근에 이 영역에서 몇 가지 개선이 이루어졌습니다.</p>


  <p>원격 분석은 다음과 같은 경우에 보다 안정적으로 전송됩니다.</p>


  <p>1.애플리케이션 Insights 포털에서 제한을 부과하거나 일시적으로 데이터를 수락할 수 없습니다.</p>


  <p>재시도 및 오류 처리 기능은 전송 안정성을 개선하는 데 도움이 됩니다. 네트워크 문제의 경우 SDK는 <a href="https://en.wikipedia.org/wiki/Exponential_backoff">지수 백오프</a>를 사용하여 원격 분석 데이터 전송을 다시 시도합니다.</p>


  <p>2. 사용자는 코드가 원격 분석 이벤트를 보낸 직후 동일한 사이트 내의 새 페이지로 이동합니다. 이전에는 페이지가 언로드되었을 때 아직 전송되지 않은 이벤트가 손실되었습니다. 이제 이벤트는 동일한 사이트의 페이지 간에 유지되는 세션 버퍼에 유지됩니다.</p>


  <h3>비콘 API</h3>


  <p>JavaScript SDK는 <a href="https://www.w3.org/TR/beacon/">비콘 API</a>에 대한 실험적 지원도 제공합니다. 비콘 API는 브라우저가 시간이 중요한 작업으로 사용량이 없을 때 원격 분석을 전송하도록 설계되었습니다. 사용자가 브라우저 탭을 탐색하거나 닫는 경우에도 모든 데이터가 배달됩니다.</p>


  <p>비콘 API는 전송을 위해 데이터를 큐에 대기시킬 수만 있으며 실제 전송은 제어 범위를 벗어난 브라우저에서 처리됩니다. 따라서 JavaScript SDK는 애플리케이션 Insights 백 엔드에서 모든 원격 분석이 수신되고 올바르게 처리되었다는 확인을 받을 수 없습니다.</p>


  <p>기본 JavaScript SDK 구성이 완벽하게 작동하지 않고&rsquo; 모든 이벤트가 추적되지 않거나 전송이 페이지의 성능에 영향을 주는 것으로 의심되는 경우 비콘 API를 사용해 볼 수 있습니다.&nbsp; 이 기능은 현재 사용하지 않도록 설정되어 있지만 isBeaconApiDisabled&rsquo;를 false로 설정&lsquo;하여 사용하도록 설정할 수 있습니다. 구성을 참조<a href="https://github.com/Microsoft/ApplicationInsights-JS/blob/master/API-reference.md#config">하세요</a>. 비콘 API를 사용하여 데이터를 보내려는 경우 SDK는 세션 Storage 버퍼 및 다시 시도 기능을 자동으로 해제합니다.</p>


  <h3>Session 클래스의 Performance.now</h3>


  <p>PowerBI 및 Edge 팀과 함께 작업한 후 세션 호출에서 performance.now를 사용하도록 이동했습니다. 이렇게 하면 라이브러리&rsquo; 날짜/시간 처리의 성능이 향상됩니다.</p>


  <h2>피드백</h2>


  <p>JavaScript SDK에 대한 질문이 있거나 문제가 발생하는 경우 <a href="https://github.com/Microsoft/ApplicationInsights-JS">GitHub</a> 문제를 자유롭게 여세요.</p>


  <h2>특별 감사</h2>


  <p>이 게시물을 준비하는 데 도움이 <a href="https://github.com/kamilszostak">카밀 Szostak</a> 특별한 감사.</p>
