### YamlMime:Yaml
ms.openlocfilehash: 837569fb6c10502ebb7a416d98905f712141cfe7
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139898750"
Slug: azure-hdinsight-application-platform-install-solutions-built-for-the-apache-hadoop-ecosystem
Title: 'Azure HDInsight 애플리케이션 플랫폼: Apache Hadoop 에코시스템용으로 빌드된 솔루션 설치'
Summary: Apache Hadoop 에코시스템을 위해 빌드한 솔루션 또는 애플리케이션을 쉽게 배포, 검색 및 설치할 수 있는 방법을 발표하게 되어 기쁩니다.
Content: >-
  <p>Azure HDInsight는 클라우드에서 제공되는 Apache Hadoop 배포입니다. 즉, 요청 시 테라바이트에서 페타바이트로 크기가 조정되는 모든 양의 데이터를 처리합니다. 사용하는 컴퓨팅 및 스토리지에 대해서만 요금을 청구할 때마다 &ndash; 노드 수를 스핀업합니다.</p>


  <p>Apache Hadoop 에코시스템을 위해 빌드한 솔루션 또는 애플리케이션을 쉽게 배포, 검색 및 설치할 수 있는 방법을 발표하게 되어 기쁩니다. 이러한 솔루션은 데이터 수집, 데이터 랭글링, 모니터링, 시각화, 성능 최적화, 보안, 분석, 시각화, 보고 등 다양한 시나리오에 걸쳐 있을 수 있습니다.</p>


  <p><u>다음은 이 환경의 몇 가지 주요 주요 사항입니다.</u></p>


  <p><b>작성, 배포 및 관리의 용이성</b></p>


  <ul>
   <li>새 클러스터를 만드는 동안뿐만 아니라 기존 HDInsight 클러스터에 이러한 앱을 설치할 수 있습니다.&nbsp;</li>
  </ul>


  <p><b>클러스터에 대한 네이티브 액세스</b></p>


  <ul>
   <li>앱은 Edge 노드에 설치되며 전체 클러스터에 액세스할 수 있습니다.</li>
  </ul>


  <p><b>클러스터에서 앱 구성의 용이성</b></p>


  <ul>
   <li>이러한 애플리케이션의 최종 사용자는 각 노드에 패키지를 설치하거나 관리하고 애플리케이션을 구성할 필요가 없습니다.</li>
  </ul>


  <p><b>기존 HDInsight 클러스터에 솔루션을 설치합니다.</b></p>


  <ul>
   <li>솔루션 공급자는 HDInsight 클러스터가 이미 실행 중인 사용자가 솔루션을 사용할 수 있도록 할 수 있습니다. 이를 통해 사용자는 이러한 솔루션을 쉽게 사용하고 생산성을 높일 수 있습니다.</li>
  </ul>


  <p>사용자는 <b>애플리케이션 </b>블레이드를 선택하여 클러스터에 앱을 검색하고 설치할 수 있습니다.</p>


  <p>다음 스크린샷에서 기존 클러스터가 있었고 Datameer 애플리케이션을 검색할 수 있습니다. 그런 다음 기존 클러스터에서 빠르고 쉽게 설치할 수 있는 Datameer 애플리케이션을 클릭할 수 있습니다.</p>


  <p><img alt="" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/fe29ccc1-715c-4d5b-ba94-cf62638dffad.png" style="border-width: 0px; width: 610px; height: 302px; padding-top: 0px; padding-right: 0px; padding-left: 0px; display: inline; background-image: none;" title=""></p>


  <p>Ive&rsquo;가 내 클러스터에 Datameer를 설치하면 이제 설치된 앱 목록에서 해당 데이터를 볼 수 있습니다.</p>


  <p><img alt="" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/cd5dbb08-7e86-4524-9112-a02258907ea4.png" style="border-width: 0px; width: 610px; height: 295px; padding-top: 0px; padding-right: 0px; padding-left: 0px; display: inline; background-image: none;" title=""></p>


  <p>Datameer를 설치하면 설치된 앱 블레이드에서 Datameer Studio에 액세스하여 HDInsight에서 실행되는 Datameers&rsquo; 엔드 투 엔드 셀프 서비스 빅 데이터 분석 플랫폼을 사용하여 새 프로젝트를 시작할 수 있습니다. 다음 스크린샷은 Datameer Studio를 보여줍니다.</p>


  <p><img alt="" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/ddda0f50-62ee-4e40-8a15-81592bc6611f.png" style="border-width: 0px; width: 610px; height: 218px; padding-top: 0px; padding-right: 0px; padding-left: 0px; display: inline; background-image: none;" title=""></p>


  <p>설치된 애플리케이션을 삭제할 수도 있습니다. 이 스크린샷에서 애플리케이션을 마우스 오른쪽 단추로 클릭하여 쉽게 삭제할 수 있는 Hue 애플리케이션을 설치했습니다. <a href="https://azure.microsoft.com/en-us/documentation/articles/hdinsight-apps-install-custom-applications/">여기서</a> Hue를 설치하는 방법에 대해 자세히 알아보세요.</p>


  <p>다음 스크린샷은 애플리케이션을 삭제하는 방법을 보여줍니다.</p>


  <p><img alt="" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/954ea67a-aaab-4d6f-9348-695402a580db.png" style="border-width: 0px; width: 610px; height: 523px; padding-top: 0px; padding-right: 0px; padding-left: 0px; display: inline; background-image: none;" title=""></p>


  <p>이는 최종 사용자가 Hadoop에서 생산성을 높이는 데 도움이 되는 솔루션을 검색하고 설치하는 매우 쉬운 방법입니다. <b>동일한 방법을 사용하여 사용자 지정 애플리케이션을 만들고 팀과 공유할 수 있습니다.</b></p>


  <p>Datameer는 솔루션을 쉽게 사용할 수 있도록 이 환경을 개발해 왔습니다. 클라우드 솔루션의 Datameers&rsquo; <b>Sr 제품 관리자에 따르면 알레한드로 말벳:</b></p>


  <p><b><i>&quot;Azure HDInsight 애플리케이션 플랫폼은 클라우드에서 Datameer 배포를 신속하게 구성하고 테스트하기 위해&#39;가장 강력하고 안정적인 프레임워크입니다. 동일한 포털 내의 마케팅 담보뿐만 아니라 솔루션에 대한 다양한 배포 옵션을 반복적으로 테스트할 수 있는 모든 유연성이 있었습니다. 지금까지 클라우드 기반 솔루션을 Market으로 사용하는 가장 쉽고 빠른 방법입니다.&quot;</i></b></p>


  <p>Datameer에 대해 자세히 알아보려면 <a href="https://azure.microsoft.com/en-us/marketplace/partners/datameer/datameerdatameer/">Azure Marketplace의 Datameer 목록을</a> 방문하세요.</p>


  <p>Apache Hadoop 에코시스템을 위해 빌드한 솔루션이 있고 HDInsight에서 사용할 수 있도록 하려면 다음 설명서를 참조하세요.</p>


  <p><b>설명서 &amp; 방법&rsquo;</b></p>


  <p><a href="https://azure.microsoft.com/en-us/documentation/articles/hdinsight-apps-install-custom-applications/">사용자 지정 HDInsight 애플리케이션 설치</a></p>


  <p><a href="https://msdn.microsoft.com/en-us/library/mt706515.aspx">앱에 대한 MSDN 설명서</a></p>


  <p><a href="https://azure.microsoft.com/en-us/documentation/articles/hdinsight-hadoop-customize-cluster-linux/">스크립트 작업을 사용하여 Linux 기반 HDInsight 클러스터 사용자 지정</a></p>


  <p><a href="https://azure.microsoft.com/en-us/documentation/articles/hdinsight-apps-publish-applications/">Azure Marketplace에 HDInsight 애플리케이션 게시</a></p>


  <p><b>요약</b></p>


  <p>이 경험을 통해 빅 데이터를 사용하는 고객의 생산성을 높일 수 있는 배포하기 쉬운 솔루션이 되기를 바랍니다. 이 기능을 활용하여 고객이 솔루션을 더 쉽게 검색하고 사용할 수 있도록 ISV(독립 소프트웨어 공급업체)를 초대합니다. 참여하려는 경우 연락 <a href="mailto:hdipartners@microsoft.com">hdipartners@microsoft.com</a> 해 주세요.</p>
