### YamlMime:Yaml
ms.openlocfilehash: cd9112e6e816f085715aa8807a6cd6686ccdafce
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139897771"
Slug: azure-security-center-and-microsoft-web-application-firewall-integration
Title: Azure Security Center 및 Microsoft 웹 애플리케이션 방화벽 통합
Summary: 웹 애플리케이션은 사이트 간 스크립팅, SQL 삽입 및 애플리케이션 DDoS와 같은 공격의 대상이 되고 있습니다. MICROSOFT WAF(웹 애플리케이션 방화벽) 및 ASC(Azure Security Center)는 이러한 취약성에 대한 웹 애플리케이션을 보호하는 데 도움이 될 수 있습니다.
Content: >-
  <p>웹 애플리케이션은 사이트 간 스크립팅, SQL 삽입 및 애플리케이션 DDoS와 같은 공격의 대상이 되고 있습니다. OWASP는 이러한 공격에 더 저항할 수 있는 애플리케이션 작성에 대한 지침을 제공하지만, 애플리케이션 토폴로지의 여러 계층에서 엄격한 유지 관리 및 패치가 필요합니다. MICROSOFT <a href="https://docs.microsoft.com/azure/application-gateway/application-gateway-web-application-firewall-overview" target="_blank">WAF(웹 애플리케이션 방화벽)</a> 및 <a href="https://azure.microsoft.com/en-us/services/security-center/" target="_blank">ASC(Azure Security Center)</a> 는 이러한 취약성에 대한 웹 애플리케이션을 보호하는 데 도움이 될 수 있습니다.</p>


  <p>Microsoft WAF는 <a href="https://www.owasp.org/index.php/Category:OWASP_ModSecurity_Core_Rule_Set_Project" target="_blank">OWASP 핵심 규칙 집합</a>을 사용하는 일반적인 웹 악용으로부터 웹 애플리케이션을 보호하는 <a href="https://docs.microsoft.com/azure/application-gateway/application-gateway-introduction" target="_blank">Azure Application Gateway</a>(계층 7 부하 분산 장치)의 기능입니다. Azure Security Center는 Azure 리소스에서 취약성을 검사하고 이러한 문제에 대한 완화 단계를 권장합니다. 이러한 취약성 중 하나는 WAF로 보호되지 않는 웹 애플리케이션이 있다는 것입니다. 현재 Azure Security Center는 개방형 인바운드 웹 포트(80 및 443)가 있는 연결된 네트워크 보안 그룹이 있는 공용 IP에 WAF 배포를 권장합니다. Azure Security Center는 기존 Azure 리소스에 <a href="https://docs.microsoft.com/en-us/azure/application-gateway/application-gateway-integration-security-center" target="_blank">애플리케이션 게이트웨이 WAF 프로비저닝</a> 을 제공하고 기존 웹 애플리케이션 방화벽에 새 리소스를 추가합니다. AZURE Security Center는 WAF와 통합하여 로그를 분석하고 중요한 보안 경고를 표시할 수 있습니다.</p>


  <p>경우에 따라 보안 관리자는 Azure Security Center에서 WAF를 프로비전할 리소스 권한이 없거나 애플리케이션 소유자가 앱 배포의 일부로 WAF를 이미 구성했습니다. 이러한 시나리오를 수용하기 위해 Security Center가 Security Center를 사용하여 프로비전되지 않은 구독에서 WAF 인스턴스를 곧 자동으로 검색할 것이라고 발표하게 되어 기쁩니다. 이전에 프로비전된 WAF 인스턴스는 보안 관리자가 Azure Security Center와 통합할 수 있는 검색된 솔루션 아래 Security Center 보안 솔루션 창에 표시됩니다. 기존 Microsoft WAF 배포를 연결하면 고객은 WAF 프로비전 방법에 관계없이 Security Center 검색을 활용할 수 있습니다. 사용자 지정 방화벽 규칙 집합과 같은 추가 구성 설정은 Security Center에서 직접 연결되는 WAF 콘솔에서 사용할 수 있습니다. <a href="https://docs.microsoft.com/en-us/azure/application-gateway/application-gateway-web-application-firewall-portal">Microsoft WAF 구성</a>에 관한 이 문서에서는 프로비저닝 프로세스에 대한 추가 지침을 제공할 수 있습니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/8a165976-3bc4-452d-886d-2b33a3e6624e.png"><img alt="ASC_WAF_Blog_picture" border="0" height="493" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/72d8b75f-b9af-4809-ad51-99aa93267843.png" style="border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="ASC_WAF_Blog_picture" width="925"></a></p>


  <p>여러분의 의견을 듣고 싶습니다! 제안이나 질문이 있는 경우 게시물 맨 아래에 의견을 남기거나 연락 <a href="mailto:ascpartnerssupport@microsoft.com">ascpartnerssupport@microsoft.com</a>해 주세요.</p>


  <p>Azure Security Center에 대해 자세히 알아보고 싶으세요?</p>


  <p style="margin-left: 40px;"><a href="https://docs.microsoft.com/en-us/azure/security-center/security-center-intro" target="_blank">Azure Security Center 소개</a></p>


  <p style="margin-left: 40px;"><a href="https://docs.microsoft.com/en-us/azure/security-center/security-center-faq" target="_blank">Azure Security Center FAQ</a></p>
