### YamlMime:Yaml
ms.openlocfilehash: 46181649080e41f4125a022abf507f8e6e3bbb6e
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139903065"
Slug: azure-data-lake-introduces-java-sdks-in-public-preview-for-big-data-processing-in-java-applications
Title: Azure Data Lake는 공개 미리 보기에서 Java SDK를 도입했습니다.
Summary: 오늘 공개 미리 보기에서 Azure Data Lake Analytics 및 Azure Data Lake Store용 Java SDK를 발표합니다.
Content: >-
  <p>오늘 공개 미리 보기에서 <a href="https://azure.microsoft.com/en-us/services/data-lake-analytics/">Azure Data Lake Analytics</a> 및 <a href="https://azure.microsoft.com/en-us/services/data-lake-store/">Azure Data Lake Store</a>용 Java SDK를 발표합니다. 이를 통해 Java로 작성된 애플리케이션 내에서 빅 데이터 처리 및 분석을 통합할 수 있습니다(C# 및 Node.js 이미 통합되어 있는 동안).</p>


  <h2>Java SDK로 무엇을 얻을 수 있나요?</h2>


  <p>이러한 Java SDK를 사용하면 새 Java 또는 기존 Java 애플리케이션을 Azure Data Lake와 통합하여 빅 데이터를 저장하고 처리할 수 있습니다.</p>


  <ul>
      <li><a href="https://azure.microsoft.com/en-us/services/data-lake-analytics/">Azure Data Lake Analytics</a> 리소스를 즉시 동적으로 프로비전하여 빅 데이터를 더 쉽게 처리할 수 있도록 분산 코드 및 인프라를 관리하는 복잡한 작업을 수행하는 빅 데이터 서비스입니다. Java SDK를 사용하면 빅 데이터(U-SQL) 작업을 제출 및 모니터링하고, U-SQL 메타데이터 카탈로그를 찾아보고, 사용자 계정 만들기/관리 및 Azure Portal 내에서 이미 수행할 수 있는 다른 작업을 수행할 수 있는 코드를 포함할 수 있습니다.</li>
      <li><a href="https://azure.microsoft.com/en-us/services/data-lake-store/">Azure Data Lake Store</a> 는 데이터 크기 조정으로 애플리케이션을 강제로 변경하지 않고도 크기, 유형 및 속도의 데이터를 쉽게 캡처할 수 있는 단일 리포지토리입니다. Java SDK를 사용하면 파일 시스템에 저장된 항목을 읽고, 쓰고, 관리하고, 데이터에 대한 액세스를 관리하고, 계정 및 Azure Portal 내에서 이미 수행할 수 있는 모든 작업을 만들거나 관리할 수 있습니다.</li>
  </ul>


  <h2>어떻게 시작하나요?</h2>


  <p>시작하려면 여기에서 시작 가이드에 액세스할 수 있습니다.</p>


  <ul>
      <li><a href="https://azure.microsoft.com/en-us/documentation/articles/data-lake-analytics-get-started-java-sdk/">Data Lake Analytics</a> Java SDK에 대한 시작 가이드</li>
      <li><a href="https://azure.microsoft.com/en-us/documentation/articles/data-lake-store-get-started-java-sdk/">Data Lake Store</a> Java SDK 시작 가이드</li>
  </ul>


  <p>시작하려면 고객은 Azure Data Lake Analytics/Store의 <a href="https://azure.microsoft.com/en-us/documentation/articles/data-lake-analytics-get-started-portal/#create-data-lake-analytics-account">공개 미리 보기</a>에 등록된 <a href="https://azure.microsoft.com/en-us/pricing/free-trial/">Azure 구독</a>이 있어야 합니다. 이를 통해 Azure Data Lake Analytics 및 스토어용 Java SDK를 시작할 준비가&#39;있습니다.</p>


  <p>처음에는 Java SDK를 <a href="https://adxsnapshots.azurewebsites.net/?dir=com/microsoft/azure/azure-mgmt-datalake-analytics/1.0.0-SNAPSHOT">Azure 스냅샷 리포지토리</a>에서 사용할 수 있지만 곧 중앙 Maven 리포지토리에서 사용할 수 있습니다. 이 변경이 발생할 때 이를 반영하도록 설명서가 업데이트됩니다.</p>


  <h2>소스 코드는 어디에 있나요?</h2>


  <p>Java SDK의 소스 코드는 GitHub(<a href="https://ttps://github.com/Azure/azure-sdk-for-java/tree/1.0.0-beta1/azure-mgmt-datalake-analytics">Data Lake Analytics</a> 및 <a href="https://github.com/Azure/azure-sdk-for-java/tree/1.0.0-beta1/azure-mgmt-datalake-store">Data Lake Store</a>)에서 사용할 수 있습니다. 누구나 참여할 수 있습니다. 자세한 내용은 아래 링크를 확인하세요.</p>


  <ul>
      <li>&nbsp;<a href="https://azure.microsoft.com/en-us/pricing/free-trial/">평가판 구독 가져오기</a></li>
      <li>&nbsp;<a href="https://azure.microsoft.com/en-us/documentation/articles/data-lake-analytics-get-started-portal/#create-data-lake-analytics-account">Azure Data Lake Analytics/스토어 공개 미리 보기에 대한 액세스 요청</a></li>
      <li>&nbsp;<a href="https://azure.microsoft.com/en-us/documentation/articles/data-lake-analytics-get-started-java-sdk/">Java SDK를 사용하여 Azure Data Lake Analytics 시작</a></li>
      <li>&nbsp;<a href="https://azure.microsoft.com/en-us/documentation/articles/data-lake-store-get-started-java-sdk/">Java SDK를 사용하여 Azure Data Lake Store 시작</a></li>
      <li>&nbsp;<a href="https://github.com/Azure/azure-sdk-for-java/tree/autorest/azure-mgmt-datalake-analytics">Data Lake Analytics Java SDK 소스 코드</a></li>
      <li>&nbsp;<a href="https://github.com/Azure/azure-sdk-for-java/tree/autorest/azure-mgmt-datalake-store">Data Lake Store Java SDK 소스 코드</a></li>
  </ul>


  <h4>Azure Data Lake Analytics 정보</h4>


  <ul>
      <li>&nbsp;<a href="https://azure.microsoft.com/en-us/documentation/articles/data-lake-analytics-overview/">Azure Data Lake Analytics 개요</a></li>
      <li>&nbsp;<a href="https://azure.microsoft.com/en-us/documentation/articles/data-lake-analytics-get-started-portal/">포털에서 Azure Data Lake Analytics 시작</a></li>
      <li>&nbsp;<a href="https://azure.microsoft.com/en-us/documentation/articles/data-lake-analytics-data-lake-tools-get-started/">Azure Data Lake Analytics 및 도구 시작</a></li>
      <li>&nbsp;<a href="https://azure.microsoft.com/en-us/documentation/articles/data-lake-analytics-use-interactive-tutorials/">Azure Data Lake Analytics 대한 대화형 자습서</a></li>
      <li>&nbsp;<a href="https://azure.microsoft.com/en-us/documentation/articles/data-lake-analytics-analyze-weblogs/">Azure Data Lake Analytics 사용하여 웹 로그 분석</a></li>
      <li>&nbsp;<a href="https://azure.microsoft.com/en-us/documentation/articles/data-lake-analytics-u-sql-get-started/">U-SQL 시작</a></li>
  </ul>


  <h4>Azure Data Lake Store</h4>


  <ul>
      <li>&nbsp;<a href="https://azure.microsoft.com/en-us/documentation/articles/data-lake-store-overview">Azure Data Lake Store 개요</a></li>
      <li>&nbsp;<a href="https://azure.microsoft.com/en-us/documentation/articles/data-lake-store-get-started-portal">포털에서 Azure Data Lake Store 시작</a></li>
      <li>&nbsp;<a href="https://azure.microsoft.com/en-us/documentation/articles/data-lake-store-secure-data">Azure Data Lake Store를 사용하여 데이터 보호</a></li>
      <li>&nbsp;<a href="https://azure.microsoft.com/en-us/documentation/articles/data-lake-store-hdinsight-hadoop-use-portal">Azure Data Lake Store와 Azure HDInsight 연결</a></li>
  </ul>
