### YamlMime:Yaml
ms.openlocfilehash: 70f9e4f7b3374248750c29a16a1c43fe0ed03e8a
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139901767"
Slug: azure-search-how-to-add-suggestions-auto-complete-to-your-search-applications
Title: Azure Search – 검색 애플리케이션에 제안(자동 완성)을 추가하는 방법
Summary: 이 게시물에서는 이 환경을 향상시키는 제안 사항 및 기타 새로운 기능을 활용하는 방법을 보여 줍니다.
Content: >-
  <h2>검색 제안이란?</h2>

  많은 모바일 애플리케이션 및 웹 사이트의 경우 검색은 사용자가 원하는 항목을 찾는 기본 수단입니다.따라서 검색 상자는 사용자가 콘텐츠를 빠르게 찾을 수 있도록 돕는 데 효과적이어야 합니다.이를 수행하는 한 가지 방법은 제안 또는 자동 완성이라고 합니다.검색 상자에서 사용자가 입력하는 항목에 대한 응답으로 잠재적 용어 일치를 제안하는 프로세스입니다.이 예제는 'sur' 문자를 입력할 때 Microsoft Store 아래에 나와 있습니다.


  <a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/type-ahead.png"><img class="alignnone size-full wp-image-243401" style="width: 245px; height: 216px;" alt="type-ahead" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/type-ahead.png" width="332" height="334" /></a>

  <h2>제안 시작</h2>

  이 게시물에서는 이미지 및 유사 항목 검색과 같이 이 환경을 향상시키는 제안 및 기타 새로운 기능을 활용하는 방법을 보여 줍니다.


  제가 안내하는 자습서는 사용자가 채소 목록을 검색할 수 있는 MVC4 기반 웹 사이트입니다.내 인덱스 만들기에 사용한 데이터는 <a href="https://en.wikipedia.org/wiki/List_of_vegetables">WikiPedia</a> 에서 제공되었으며 <a href="https://github.com/twitter/typeahead.js">Twitter Type-Ahead</a> java 스크립트 라이브러리를 사용하여 멋진 검색 상자를 만들고 있습니다.Azure Search와 함께 이러한 구성 요소를 사용하면 다음과 같이 미리 입력할 수 있을 뿐만 아니라 이미지로 제안을 확장할 수 있는 웹 사이트가 있습니다.


  <a href="https://acom.azurecomcdn.net/80C57D/blogmedia/blogmedia/2015/01/19/azure-search-suggestions.png"><img class="alignnone size-medium wp-image-243412" alt="azure-search-suggestions" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/azure-search-suggestions-452x369.png" width="452" height="369" /></a>

  <h2>요구 사항</h2>

  이 자습서에서는 다음에 대한 액세스 권한이 있다고 가정합니다.

  <ul>
   <li>Azure Search 서비스( <a href="https://azure.microsoft.com/en-us/documentation/articles/search-get-started/">자세한 내용은 여기</a>)를 참조하세요.</li>
   <li>Visual Studio 2012 이상</li>
   <li>샘플에 대한 <a href="https://azsearchsuggestions.codeplex.com/SourceControl/latest">소스 코드</a> 다운로드</li>
   <li>먼저 자습서를 완료한 것이 좋습니다. <a href="https://azure.microsoft.com/en-us/documentation/articles/search-create-first-solution/">Azure Search를 사용하여 첫 번째 검색 솔루션 만들기</a></li>
  </ul>

  <h2></h2>

  <h2>Azure Search 제안 샘플 구성</h2>

  이 시점에서 <a href="https://azsearchsuggestions.codeplex.com/SourceControl/latest">샘플 프로젝트를</a> 다운로드하고 Visual Studio 열어야 합니다.샘플 Visual Studio 프로젝트에서 Azure Search 서비스에 대한 연결 정보를 추가해야 합니다.

  <ul>
   <li>CreateIndex 프로젝트 내에서 app.config 열고 Azure Portal에서 찾을 수 있는 Azure Search 서비스 및 Azure Search Service API 키를 반영하도록 SearchServiceName 및 SearchServiceApiKey 값을 변경<a href="https://portal.azure.com/">합니다.</a></li>
   <li>AzureSearchSuggestionsDemo 프로젝트 내에서 web.config 열고 SearchServiceName 및 SearchServiceApiKey 값도 변경합니다.</li>
  </ul>

  <h2></h2>

  <h2>야채 인덱스 만들기</h2>

  이제 애플리케이션을 구성했으므로 CreateIndex 애플리케이션을 시작할 수 있습니다.

  <ul>
   <li>F5 키를 눌러 애플리케이션 시작</li>
  </ul>

  이 애플리케이션은 다음 단계를 수행합니다.

  <ul>
   <li>이전에 Azure Search 서비스에 존재했던 경우 채소 인덱스를 삭제합니다.</li>
   <li>프로젝트에 포함된 schema.json 파일을 사용하여 Vegetables라는 새 검색 인덱스 만들기</li>
   <li>프로젝트 파일 documents.json에 저장된 문서를 이 인덱스로 로드합니다.</li>
  </ul>

  성공하면 다음과 같이 콘솔 창에 출력이 표시됩니다.


  인덱스 만들기...


  인덱스로 문서 로드 중...


  완료.Enter&gt; 키를 눌러 &lt;계속합니다.


  이 자습서에서는 검색 인덱스 만들기에 대한 세부 정보를 거치지 않습니다.이에 대해 자세히 알아보려면 다음 자습서를 참조하세요. <a href="https://azure.microsoft.com/en-us/documentation/articles/search-create-first-solution/">Azure Search를 사용하여 첫 번째 검색 솔루션 만들기</a>

  <h2>Azure Search 제안 샘플 실행</h2>

  이제 Azure Search 인덱스 "vegetables"를 만들었으므로 다음을 수행하는 ASP.NET MVC 애플리케이션(F5) AzureSearchSuggestionsDemo를 시작할 수 있습니다.


  1) 채소를 검색할 수 있는 검색 상자가 있는 페이지를 로드합니다.


  2) 몇 글자를 입력하여 Azure Search에서 다시 제공되는 제안 결과를 확인합니다.참고: 처음 검색하는 데 몇 초가 걸립니다.


  <a href="https://acom.azurecomcdn.net/80C57D/blogmedia/blogmedia/2015/01/19/azure-search-suggestions.png"><img class="alignnone size-medium wp-image-243412" alt="azure-search-suggestions" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/azure-search-suggestions-452x369.png" width="452" height="369" /></a>

  <h2>코드를 통해 제안의 작동 방식</h2>

  샘플을 확인했으므로 작동 방식의 주요 구성 요소를 살펴보겠습니다.

  <ul>
   <li>애플리케이션을 중지하고 \Views\Home 폴더 아래에 있는 Index.cshtml 파일을 엽니다.</li>
  </ul>

  이 페이지의 코드 대부분은 <a href="twitter.github.io/typeahead.js">Twitter typeahead.js 라이브러리를 활용합니다</a>.이 라이브러리는 멋진 검색 상자를 제공하는 데 많은 작업을 수행하고 Azure Search에 대한 비동기 ajax 호출을 매우 쉽게 수행할 수 있도록 하는 라이브러리입니다.또한 typeahead.js 라이브러리는 제안 출력의 형식을 지정하는 방법을 간소화하는 handlebars.js 사용합니다.예를 들어 애플리케이션에서는 다음 서식을 사용합니다.

  <p style="padding-left: 30px;">&lt;pimg&gt;&lt; src="{{thumbnail}}} style="height:40px;width:60px;"&gt;&amp; nbsp;&lt; strong&gt;{{name}}&lt;/strongnbsp&gt;&amp;;-&amp;nbsp;{ {species}}&lt; /p&gt;</p>

  이렇게 하면 검색 제안에서 텍스트와 함께 이미지를 표시할 수 있습니다.다음 섹션에서 자세히 살펴보겠습니다.


  마지막으로 유의해야 할 것은 HomeController.cs 파일 내에서 MVC 컨트롤러 함수 Suggest를 호출할 수 있는 다음 참조입니다.또한 사용자가 입력한 텍스트 상자에 매개 변수 'q'를 전달하고 매개 변수 유사 항목을 false로 설정합니다.

  <p style="padding-left: 30px;">remote: '/home/suggest?q=%QUERYtype&amp;=namefuzzy&amp;=false'</p>


  <h2>유사 항목 일치를 지원하도록 샘플 확장</h2>

  유사 항목 검색은 최근에 Azure Search 제안에 추가된 기능으로, 사용자가 검색 상자에서 단어의 철자를 잘못 입력하더라도 근접 일치 항목을 기반으로 결과를 가져올 수 있습니다.

  <p style="padding-left: 30px;">이 작업을 수행하려면 다음 줄을 이 줄에서 변경합니다.</p>

  <p style="padding-left: 60px;">remote: '/home/suggest?q=%QUERYtype&amp;=namefuzzy&amp;=false'</p>

  <p style="padding-left: 30px;">아래와 같이 변환합니다.</p>

  <p style="padding-left: 60px;">remote: '/home/suggest?q=%QUERYtype&amp;=namefuzzy&amp;=true'</p>

   변경 내용을 저장하고 애플리케이션(F5)을 시작합니다.

  <ul>
   <li>'arta'와 같은 항목을 입력하고 입력한 문자와 정확히 일치하지 않더라도 결과가 어떻게 돌아오는지 확인합니다.</li>
  </ul>

  <h2>홈 컨트롤러</h2>

  이제 샘플에 대한 JavaScript 코드를 검토했으므로 검색 제안 요청을 실행하는 C# 컨트롤러 코드를 살펴보겠습니다.

  <ul>
   <li>컨트롤러 디렉터리에서 HomeController.cs 파일을 엽니다.<b></b></li>
  </ul>

  가장 먼저 알 수 있는 것은 이 컨트롤러가 다음을 호출한다는 것입니다.


  SuggestionSearch _suggestSearch = new SuggestionSearch();


  이렇게 하면 Azure Search 서비스에 인증된 HTTP 클라이언트를 만드는 등의 여러 가지 작업을 수행합니다.작동 방식에 대해 자세히 알아보려면 다음 자습서를 참조하세요. <a href="https://azure.microsoft.com/en-us/documentation/articles/search-create-first-solution/">Azure Search를 사용하여 첫 번째 검색 솔루션 만들기</a>

  <ul>
   <li>Suggest 함수로 이동</li>
  </ul>

  이 함수는 매우 간단하며 실제로 사용자가 검색 상자에 입력한 문자인 매개 변수 q와 유사 항목 검색에 대한 부울 값을 가져와서 _suggestSearch.Suggest에 전달합니다.

  <ul>
   <li>프로젝트 루트에서 SuggestionsSearch.cs 파일을 열고 Suggest 함수로 이동합니다.</li>
  </ul>

  수신된 매개 변수를 사용하여 Azure Search REST API 호출이 실행됩니다.그런 다음 제안 결과가 목록 개체인 ListSuggestion&lt;&gt; suggestionList에 로드됩니다.


  Suggestion 클래스에는 미리 보기라는 문자열이 있습니다.Azure Search 야채 인덱스에서 PNG 이미지에 대한 URL 참조입니다.Azure Search에 이진 이미지를 저장하는 것은 의미가 없으므로(이미지는 전체 텍스트를 검색할 수 없음) 프로젝트에 썸네일을 저장하거나(\Images 디렉터리에서 볼 수 있음) Azure Blob Storage 같은 항목에 더 잘 저장합니다.


  이 목록이 만들어지면 홈 컨트롤러 제안 함수로 다시 전달되며, 이 함수는 JSON 형식으로 Index.cshtml로 반환되고, 그런 다음 구문 분석되어 검색 상자에 제안으로 로드됩니다.

  <ul>
   <li>(선택 사항) SuggestionsSearch.cs 파일에서 Suggest 함수의 시작 부분에 중단점을 추가하고 애플리케이션을 다시 실행(F5)할 수 있습니다.검색 상자에 문자를 입력하면 어떻게 되는지 확인합니다.</li>
  </ul>

  <h2></h2>

  <h2>최종 생각 – 검색 결과 페이지에 연결</h2>

  검색 상자에서 항목을 선택할 때 검색 결과가 반환되지 않음을 알 수 있습니다. 샘플은 검색 용어 공식 기능을 표시하기만 하면 됩니다.


  이 샘플을 추가로 수행하려면 검색을 실행하고 결과를 반환하는 코드를 추가해야 합니다. 이를 처리하는 방법은 여러 가지가 있지만 가장 일반적인 방법은 사용자가 검색 상자에서 "Enter"를 클릭할 때 검색을 실행하는 것입니다.현재 index.cshtml 파일에 다음 코드에 대한 참조가 표시됩니다.

  <p style="padding-left: 30px;">.on('typeahead:selected', function(obj, datum) {</p>

  <p style="padding-left: 60px;">console.log(obj);</p>

  <p style="padding-left: 60px;">console.log(datum);</p>

  <p style="padding-left: 30px;">})</p>

  제안된 검색어 중 하나를 선택할 때마다 이 코드가 호출됩니다.검색을 실행하고 결과를 다시 얻으려면 console.log 코드를 이 작업을 수행하는 ajax 호출로 바꿉니다.


  검색 결과 페이지를 만드는 방법에 대한 자세한 내용은 다음 자습서를 참조하세요. <a href="https://azure.microsoft.com/en-us/documentation/articles/search-create-first-solution/">Azure Search를 사용하여 첫 번째 검색 솔루션을 만듭니</a>다.


  여기에 typeahead.js 라이브러리를 확장하는 방법에 대한 자세한 정보도 <a href="https://github.com/twitter/typeahead.js/blob/master/doc/jquery_typeahead.md">있습니다</a>.


  Azure Search에 대한 자세한 내용은 <a href="https://azure.microsoft.com/en-us/documentation/services/search/">Azure Search 설명서를</a> 참조하세요.


  <a href="https://feedback.azure.com/forums/263029-azure-search/suggestions/6328649-localization">피드백을</a> 계속 보내주세요.


  Liam Cavanagh는 자신의 블로그 또는 <a href="https://twitter.com/liamca" target="_blank">트위터를</a> 통해 연락할 수 있습니다.
