### YamlMime:Yaml
ms.openlocfilehash: 49a73752bbd8c20b54fc90b1032352500521398a
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139907903"
Slug: azure-diagnostics-integration-with-application-insights
Title: Application Insights Azure Diagnostics 통합
Summary: Azure SDK 2.8에서는 Azure Cloud Services 프로젝트 및 Azure Windows VM에 대한 Azure Diagnostics 원격 분석을 애플리케이션 Insights 도입했습니다.
Content: >-
  <p>Azure 클라우드 서비스가 느리게&rsquo; 응답하는 경우 CPU 또는 메모리 병목 현상이&rsquo; 있는지 또는 예기치 않게 실패하거나 시작&rsquo;되지 않는&rsquo; 경우 시스템 로그를 보고 싶어할 것입니다. <a href="https://azure.microsoft.com/en-us/blog/announcing-the-azure-sdk-2-8-for-net/" target="_blank">Azure SDK 2.8</a>&rsquo;을 사용하여 <a href="https://azure.microsoft.com/en-us/documentation/articles/cloud-services-dotnet-diagnostics/" target="_blank">Azure Cloud Services</a> 프로젝트 및 Azure Windows VM을 위해 Azure Diagnostics 원격 분석을 <a href="https://azure.microsoft.com/en-us/services/application-insights" target="_blank">애플리케이션</a> Insights 가져왔습니다. 성능 카운터, Windows 이벤트 로그 및 앱 추적은 모두 애플리케이션 Insights SDK에서 앱 내에서 전송된 <a href="https://azure.microsoft.com/documentation/articles/app-insights-start-monitoring-app-health-usage/" target="_blank">응답 시간</a>, <a href="https://azure.microsoft.com/documentation/articles/app-insights-dependencies/" target="_blank">종속성</a> 및 <a href="https://azure.microsoft.com/documentation/articles/app-insights-api-custom-events-metrics/" target="_blank">기타 이벤트</a>와 함께 표시됩니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/2fd47aac-298d-4aea-9867-f47097ad8852.png"><img alt="Overview Blade" border="0" height="610" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/0b6c1f85-7599-4886-ac3c-614032e0b86a.png" style="border-width: 0px; padding-top: 0px; padding-right: 0px; padding-left: 0px; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="개요 블레이드" width="561"></a></p>


  <h2>Application Insights 리소스 설정</h2>


  <p><a href="https://azure.microsoft.com/documentation/articles/app-insights-cloudservices/" target="_blank">Cloud Services 앱에 Application Insights SDK를 아직 추가</a>하지 않은&rsquo; 경우 지금 추가합니다. 또는 Azure Diagnostics 데이터를 자체적으로 보려면 표시할 <a href="https://azure.microsoft.com/documentation/articles/app-insights-create-new-resource/" target="_blank">새 애플리케이션 Insights 리소스를 만듭니</a>다.</p>


  <h2>Application Insights에 Azure Diagnostics 보내기</h2>


  <ul>
   <li>Visual Studio를 엽니다. 또는 <a href="https://github.com/FrictionFree/WAD2AI" target="_blank">PowerShell을 사용할</a> 수 있습니다.</li>
  </ul>


  <p>클라우드 서비스 프로젝트를 아직 게시하지 않은&rsquo; 경우:</p>


  <ul>
   <li>솔루션 탐색기에서 각 웹 또는 작업자 역할의 속성(프로젝트가 아닌 역할)을 엽니다.</li>
   <li><strong>애플리케이션 Insights 진단 데이터 보내기를 확인합니다</strong>.</li>
   <li>앱에 대한 애플리케이션 Insights 리소스를 선택합니다.</li>
   <li>서비스를 게시합니다.</li>
  </ul>


  <p>클라우드 서비스 또는 Virtual Machine이 이미 실행 중인 경우:</p>


  <ul>
   <li>서버 탐색기 또는 클라우드 탐색기에서 클라우드 서비스 또는 가상 머신을 마우스 오른쪽 단추로 클릭하고 <strong>진단 사용/업데이트를</strong> 선택합니다.</li>
   <li><strong>애플리케이션 Insights 진단 데이터 보내기를 확인합니다</strong>.</li>
   <li>앱에 대한 애플리케이션 Insights 리소스를 선택합니다.</li>
   <li>업데이트를 적용합니다.</li>
  </ul>


  <p><img alt="Send Azure Diagnostics to Application Insights" border="0" height="458" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/d4b3e0f3-cee3-4a0a-a8c9-1bdcd127ba0d.png" style="border-width: 0px; padding-top: 0px; padding-right: 0px; padding-left: 0px; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="Visual Studio 애플리케이션 Insights Azure Diagnostics 보내기" width="610"></p>


  <h3>&nbsp;</h3>


  <h2>애플리케이션 Insights 포털에서 Azure Diagnostics 데이터 보기</h2>


  <p>진단 원격 분석은 애플리케이션 Insights 포털에 표시됩니다.</p>


  <ul>
   <li><strong>Windows 이벤트 로그</strong>

   <ul>
    <li><a href="https://azure.microsoft.com/documentation/articles/app-insights-diagnostic-search/" target="_blank"><em>검색</em></a>을 사용하여 개별 이벤트를 조사합니다.</li>
    <li><a href="https://azure.microsoft.com/documentation/articles/app-insights-metrics-explorer/" target="_blank"><em>메트릭 탐색기를</em></a> 사용하여 다양한 유형의 이벤트 수를 확인합니다. <em>사용자 지정</em> 범주 아래에 표시되는 <em>Azure Diagnostics 이벤트</em> 메트릭을 선택합니다.</li>
   </ul>
   </li>
   <li><strong>애플리케이션 추적 및 <a href="https://msdn.microsoft.com/library/ms751538(v=vs.110).aspx" target="_blank">ETW</a> 추적</strong>: <a href="https://azure.microsoft.com/documentation/articles/app-insights-diagnostic-search/" target="_blank"><em>검색</em></a> 을 사용하여 로그 추적을 찾고 검사합니다.</li>
   <li><strong>성능 카운터</strong>: 개요 블레이드에서 서버 타일을 열거나 <a href="https://azure.microsoft.com/documentation/articles/app-insights-metrics-explorer/" target="_blank"><em>메트릭 탐색기</em></a>&nbsp; <em><a href="https://azure.microsoft.com/en-us/documentation/articles/app-insights-analytics/" target="_blank">애플리케이션 Insights 분석을</a></em> 사용하여 자체 차트를 만듭니다. <em>사용 가능한 메모리 </em>및 <em>% 프로세서 시간 </em>성능 카운터는 <em>성능 카운터</em> 범주에서 찾을 수 있지만 다른 카운터는 <em>사용자 지정 메트릭</em>에서 찾을 수 있습니다.</li>
  </ul>


  <p><img alt="View Azure Diagnostics telemetry in Application Insights" border="0" height="410" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/30ab484f-b7f0-43c2-b84e-0f1a35e46b93.png" style="border-width: 0px; padding-top: 0px; padding-right: 0px; padding-left: 0px; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="Application Insights Azure Diagnostics 원격 분석 보기" width="610"></p>


  <h2>결합된 진단 사용</h2>


  <p>Azure Diagnostics 및 애플리케이션 Insights SDK는 라이브 애플리케이션에 대한 상호 보완적인 보기를 제공합니다. Azure 진단은 시스템 관점, 성능 카운터, 역할 수명 주기 데이터 및 기타 Windows 이벤트를 제공하며, SDK는 앱 내부에서 요청, 예외, 종속성 및 추가하는 <a href="https://azure.microsoft.com/documentation/articles/app-insights-api-custom-events-metrics/" target="_blank">모든 사용자 지정 원격 분석에</a> 대한 데이터를 보냅니다.</p>


  <p>여기서&rsquo; 볼 수 있듯이 각각은 단일 옵션으로 켜지고 Azure Portal에서 동일한 리소스로 데이터 스트림을 보낼 수 있습니다. &rsquo;쉽게 설정할 수 있으며 두 스트림의 조합은 훌륭한 진단 값을 제공합니다.</p>


  <p>이 조합을 특히 중시하는&rsquo; 몇 가지 시나리오가 있습니다.</p>


  <ul>
   <li>성능 저하:&rsquo; 문제를 진단하는 데 도움이 되는 시스템 이벤트 및 성능 데이터를 볼 수 있습니다.</li>
   <li>역할 충돌, 재활용 또는 역할 수명 주기 데이터 시작 &ndash; 실패는 이러한 유형의 문제를 식별하는 데 매우 중요합니다.</li>
  </ul>


  <p>한 곳에서&rsquo; 모든 데이터를 확인하면 VM에 로그인하거나 다른 곳으로 이동하여 앱과 시스템 원격 분석의 상관 관계를 지정할 수 있는 이벤트 로그&ndash;&rsquo;를 찾을 필요가 없습니다.</p>


  <p>애플리케이션 Insights 사용자 의견 페이지에서 새로운 기능 또는 향상된 기능에 대한 아이디어를 공유하세요. 질문이 있으면 <a href="https://social.msdn.microsoft.com/Forums/en-US/ApplicationInsights/" target="_blank">애플리케이션 Insights 포럼</a>을 방문하세요.</p>
