### YamlMime:Yaml
ms.openlocfilehash: 3802a42896430337978891f360a54fca766356be
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139907288"
Slug: azure-web-application-gallery-on-azure-microsoft-com
Title: azure.microsoft.com Azure 웹 애플리케이션 갤러리
Summary: >
  Azure 웹 애플리케이션 갤러리를 사용하면 Azure Websites에서 인기 있는 커뮤니티 ASP.NET, PHP, Python, Java 및 Node.JS 애플리케이션을 쉽게 탐색, 검색 및 설치할 수 있습니다. 이제 사용자는 몇 분 만에 애플리케이션을 찾아보고 보고 개인 블로그에서 전자 상거래 웹 사이트, 회사 웹 사이트에 이르는 동적 웹 사이트를 빌드할 수 있습니다.
Content: >-
  이제 <a href="https://azure.microsoft.com/en-us/gallery/">Azure 갤러리</a>는 Microsoft Azure Websites에서 인기 있는 오픈 소스 커뮤니티 웹 애플리케이션을 탐색하고 설치하는 쉬운 방법을 제공합니다.


  <a href="https://acom.azurecomcdn.net/80C57D/blogmedia/blogmedia/2014/09/21/galleryindex.png"><img style="margin: 0px; border: 0px;" title="galleryindex" alt="galleryindex" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/galleryindex_thumb.png" width="1026" height="662" border="0" /></a>


  &nbsp;


  Azure 웹 사이트에 대해 제공되는 애플리케이션 목록을 보려면 <a href="https://azure.microsoft.com/en-us/gallery/web/">여기</a>를 클릭하십시오.


  <a href="https://acom.azurecomcdn.net/80C57D/blogmedia/blogmedia/2014/09/21/index1.png"><img style="margin: 0px; border: 0px;" title="index1" alt="index1" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/index1_thumb.png" width="996" height="770" border="0" /></a>


  &nbsp;


  이러한 애플리케이션을 클릭하여 해당 애플리케이션에 대해 자세히 알아보고 <strong>웹앱 만들기 </strong> 를 클릭하여 애플리케이션을 만듭니다.


  <a href="https://acom.azurecomcdn.net/80C57D/blogmedia/blogmedia/2014/09/21/detailspage.png"><img style="margin: 0px; border: 0px;" title="detailspage" alt="detailspage" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/detailspage_thumb.png" width="1026" height="694" border="0" /></a>


  &nbsp;


  찾고 있는 애플리케이션을 찾을 수 없는 경우  <a href="https://feedback.azure.com/forums/169385-websites">피드백 포럼</a>에서 제안 사항을 공유하세요.
