### YamlMime:Yaml
ms.openlocfilehash: ac3706d2be66b8946ff99aaa86838b6e8588c762
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139902705"
Slug: azure-monitor-aad-activity-logs-using-diagnostic-settings
Title: 'Azure Monitor: 진단 설정을 사용하여 AAD 활동 로그 라우팅'
Summary: 오늘 Azure Active Directory(AAD) 팀과 협력하여 Azure Monitor 진단 설정을 사용하여 AAD 활동 로그의 공개 미리 보기를 발표하게 되어 기쁩니다. Azure Monitor 진단...
Content: >-
  <p>오늘 Azure Active Directory(AAD) 팀과 협력하여 Azure Monitor 진단 설정을 사용하여 AAD 활동 로그의 공개 미리 보기를 발표하게 되어 기쁩니다. Azure Monitor 진단 설정을 사용하면 Azure 서비스에서 Azure Storage 계정, Event Hubs 네임스페이스 및/또는 Log Analytics 작업 영역의 세 가지 대상으로 로그 데이터를 스트리밍할 수 있습니다. 이렇게 하면 모든 Azure 서비스에서 데이터 보관, <a href="https://azure.microsoft.com/en-us/blog/use-azure-monitor-to-integrate-with-siem-tools/">SIEM 도구</a> 또는 사용자 지정 로그 처리 도구로 로그를 쉽게 라우팅할 수 있습니다. 오늘&rsquo; 발표를 통해 이제 AAD 감사를 라우팅하고 로그를 동일한 대상으로 로그인하여 하나의 파이프라인에서 모든 Azure 서비스 로그를 중앙 집중화할 수 있습니다.</p>


  <p>지금까지 Azure Monitor에서 처리하는 모든 로그 데이터는 Azure 구독 내에 배포된 Azure 리소스에서 제공되었습니다. 이러한 유형의 데이터를 리소스 수준 로그 데이터로 &ldquo;설명하는 경우가 많으며 리소스&rdquo; 진단 설정을 사용하여 구성됩니다. AAD 로그 데이터는 Azure Monitor를 통해 제공되는 <strong>테넌트 수준 서비스의</strong> 첫 번째 로그 데이터 형식입니다. 테넌트 수준 서비스는 Azure 구독 내에서 리소스로 배포되지 않고&rsquo; 전체 AAD 테넌트에서 작동합니다. 이 새로운 유형의 &ldquo;테넌트 수준 로그 데이터를&rdquo; 처리하기 위해 Azure Monitor는 새로운 유형의 진단 설정인 테넌트 진단 설정을 도입했습니다. AAD 로그의 경우 포털의 AAD 영역에서 감사 로그로 이동하고 데이터 설정 내보내기를 클릭하여 &ldquo;테넌트 진단 설정을 설정할 수 있습니다.&rdquo;</p>


  <p><img alt="image" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/00a242b3-2593-4248-b143-5f2993e82aa1.png" style="margin-right: auto; margin-left: auto; float: none; display: block;"></p>


  <p>그러면 진단 설정을 만들거나 수정하거나 삭제할 수 있는 친숙한 Azure Monitor 진단 설정 환경이 표시됩니다.</p>


  <p><img alt="image" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/300855ae-7574-4202-a834-9e2a10672db1.png" style="margin-right: auto; margin-left: auto; float: none; display: block;"></p>


  <p>이미지 기능에 대해 자세히 알아보고 시작하려면 <a href="https://cloudblogs.microsoft.com/enterprisemobility/2018/07/26/azure-ad-activity-logs-in-azure-monitor-diagnostics-now-in-public-preview/">Enterprise 모바일 및 보안 블로그에서 Alex Simonss&rsquo; 게시물을</a> 확인하세요. 또한 공개 미리 보기 동안 AAD 활동 로그는 아직 Log Analytics로 라우팅할 수 없지만 2018년 10월까지 이를 사용하도록 설정하기 위해 노력하고 있습니다. Azure Monitor를 통해 로그를 노출하는 서비스의 전체 목록은 <a href="https://docs.microsoft.com/en-us/azure/monitoring-and-diagnostics/monitoring-diagnostic-logs-schema#service-specific-schemas-for-resource-diagnostic-logs">설명서를 참조하세요</a>.</p>
