### YamlMime:Yaml
ms.openlocfilehash: a8bfe9b60dec494dbe73c73549adcbb55aa3f452
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139906179"
Slug: azure-iot-hub-device-provisioning-service-preview-automates-device-connection-configuration
Title: Azure IoT Hub Device Provisioning Service 미리 보기는 디바이스 연결 및 구성을 자동화합니다.
Summary: '오늘 Azure IoT Hub Device Provisioning Service의 공개 미리 보기를 발표합니다! Device Provisioning Service는 고객이 IoT Hub에 대한 제로 터치 디바이스 프로비저닝을 구성할 수 있도록 Azure IoT Hub와 작동하는 새로운 서비스입니다. '
Content: >-
  <p>오늘 Azure IoT Hub Device Provisioning Service의 공개 미리 보기를 발표하는&#39;있습니다. Device Provisioning Service는&nbsp; 고객이 IoT Hub에 대한 제로 터치 디바이스 프로비저닝을 구성할 수 있도록 Azure IoT Hub와 작동하는 새로운 서비스입니다. Device Provisioning Service를 사용하면 안전하고 확장 가능한 방식으로 수백만 개의 디바이스를 프로비전할 수 있으며, 프로세스&nbsp; 작업을 자동화하는 것은 역사적으로 연결된 디바이스 볼륨을 관리하는 제조업체와 회사에 시간과 리소스 집약적이었습니다. Device Provisioning Service는 디바이스를 클라우드에 등록하고 디바이스를 구성하는 것을 포함하여 완전한 자동화된 프로비저닝을 제공하는 유일한 클라우드 서비스입니다. Device Provisioning Service는 오늘부터 미국 동부, 서유럽 및 동남 아시아에서 사용할 수 있으며 결국 전 세계적으로 사용할 수 있습니다.</p>


  <p>프로비전 서비스가 없으면 디바이스를 Azure IoT Hub에 연결하려면 수동 작업이 필요합니다. 디바이스가 손상된 경우 디바이스별 액세스 해지를 사용하도록 설정하려면 각 디바이스에 고유한 ID가 필요합니다. 이 작업은 극소수의 디바이스에서 수동으로 작동하지만 IoT 규모에서는 수백만 개의 디바이스 각각에 연결 자격 증명을 개별적으로 배치해야 합니다.</p>


  <p>&iuml;연결 문제를 해결하는 방법은 제조 시 디바이스에서 IoT Hub 연결 정보를 하드 코딩하는 것이지만 일부 시나리오에서만 작동합니다. 대부분의 경우 전체 프로비전에는 디바이스를 제조할 때 사용할 수 없는 정보(예: 디바이스를 구매한 사람 또는 디바이스를 사용할 대상)가 필요합니다.</p>


  <p>디바이스가 연결되더라도 <a href="https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-device-twins">원하는 쌍 상태</a> 및 소프트웨어 및/또는 펌웨어 업데이트로 구성해야 합니다. 이는 디바이스 배포를 계획할 때 고려해야 할 더 많은 작업입니다.</p>


  <p>Device Provisioning Service는 고객에게 많은 시간을 절약하여 IoT Hub에 등록하는 동안 디바이스를 자동으로 구성하는 데 도움을 줍니다. Device Provisioning Service에는 디바이스를 프로비전하는 데 필요한 모든 정보가 포함되어 있으며, 디바이스의 수신을 취소하고 다시 플래시하지 않고도 나중에 공급망에서 정보를 쉽게 업데이트할 수 있습니다.</p>


  <p>Device Provisioning Service에서 사용하도록 설정하는 몇 가지 프로비저닝 시나리오는 다음과 같습니다.</p>


  <ul>
   <li>팩터리(초기 설정)에서 하드 코딩된 IoT Hub 연결 정보를 요구하지 않고 단일 IoT 솔루션에 제로 터치 프로비저닝</li>
   <li>솔루션별 요구 사항에 따라 디바이스를 자동으로 구성합니다.</li>
   <li>여러 허브에서 디바이스 부하를 분산합니다.</li>
   <li>판매 트랜잭션 데이터(다중 테넌트)를 기반으로 디바이스를 소유자&rsquo; IoT 솔루션에 연결합니다.</li>
   <li>사용 사례에 따라 특정 IoT 솔루션에 디바이스 연결(솔루션 격리)</li>
   <li>가장 가까운 지리적 위치를 사용하여 디바이스를 IoT Hub에 연결합니다.</li>
   <li>소유권 또는 위치 변경과 같은 디바이스의 변경 내용에 따라 다시 프로비전합니다.</li>
  </ul>


  <p>이러한 모든 시나리오는 동일한 기본 흐름을 사용하여 Device Provisioning Service를 통해 오늘 달성할 수 있습니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/00868aff-fb7b-42ec-99ff-a212b0644bc9.png"><img alt="image" border="0" height="229" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/c64c2a4c-885b-49ae-b047-1b144a2e3d59.png" style="border: 0px currentColor; border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="이미지" width="480"></a></p>


  <p>&nbsp;</p>


  <p>Device Provisioning Service는 HSM(하드웨어 보안 모듈)을 사용하여 키를 안전하게 저장하는 디바이스에서 가장 잘 작동합니다. HSM은 키 스토리지에 대한 최대 보안 용량을 제공하며, 업데이트된 디바이스 SDK를 사용하면 HSM을 사용하여 디바이스와 클라우드 간에 신뢰의 루트를 매우 쉽게 설정할 수 있습니다. Microsoft는 여러 HSM 제조업체와 파트너십을 맺고 있으며 <a href="https://azure.microsoft.com/en-us/blog/azure-iot-supports-new-security-hardware-to-strengthen-iot-security/">, Azure 블로그</a>에서 파트너 관계 및 HSM 옵션에 대해 읽을 수 있습니다. 디바이스가 HSM을 사용할 수 없는 경우에도 Device Provisioning Service에 연결할 수 있습니다. <a href="https://aka.ms/simulatedhsm">여기에서 시뮬레이션된 TPM 또는 소프트웨어 기반 x509 인증서를</a> 사용하는 방법을 알아볼 수 있습니다.</p>


  <p><a href="https://aka.ms/provisioningconcepts">디바이스 프로비저닝과 관련된 모든 기술 개념에 대해 자세히 알아봅니다</a>.</p>


  <p>Azure IoT 안전하고 신뢰할 수 있는 방식으로 IoT 솔루션을 배포하고 관리하지 않는 서비스를 제공하기 위해 최선을 다하고 있습니다. <a href="https://portal.azure.com/">Azure</a> Portal에서 고유한 Device Provisioning Service를 만들 수 있으며 <a href="https://aka.ms/dpssdk">GitHub</a> 디바이스 SDK를 체크 아웃할 수 있습니다. Device Provisioning Service에 대해 자세히 알아보고 <a href="https://docs.microsoft.com/en-us/azure/iot-dps/">설명서 센터에서</a> 사용하는 방법을 알아봅니다. 보안 디바이스 등록(미리 보기의&#39;)에 대한 피드백을 받으시기 바랍니다. 따라서 <a href="https://feedback.azure.com/forums/321918-azure-iot/">Azure IoT User Voice 포럼</a>을 통해 계속해서 제안 사항을 제출하세요.</p>
