### YamlMime:Yaml
ms.openlocfilehash: 180d2e686d23f0ea262da967aa705556243d9617
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139907324"
Slug: azure-lighthouse-managing-cloud-hybrid-and-edge-environments-atscale-through-a-single-control-plane
Title: Azure Lighthouse - 단일 제어 평면을 통해 대규모 클라우드, 하이브리드 및 에지 환경 관리
Summary: 수천 개의 파트너와 기업이 Azure Lighthouse를 사용하여 Azure 테넌트 전체에서 서비스를 관리하며, 이는 Azure Resource Manager에서 수만 개의 구독과 100만 개 이상의 Azure 리소스(단일 제어 평면)를 나타냅니다.
Content: >-
  <p>수천 개의 파트너와 기업이 <a href="https://azure.microsoft.com/en-us/services/azure-lighthouse/" target="_blank">Azure Lighthouse</a> 를 사용하여 Azure 테넌트 전체에서 서비스를 관리하며, 이는 Azure Resource Managera&mdash; 통합 제어 평면에서 수만 개의 구독과 100만 개 이상의 Azure 리소스를 나타냅니다. Azure Lighthouse를 사용하면 서비스 공급자와 자체 관리 기업이 Azure&rsquo;의 포괄적이고 강력한 관리 도구를 사용하여 더 높은 운영 효율성을 달성할 수 있습니다. 이제 하이브리드 자산 및 온-프레미스에서 더 높은 자동화, 규모 및 향상된 거버넌스를 사용하여 리소스를 보고 관리할 수 있습니다.</p>


  <p>MSP(관리 서비스 공급자)는 하이브리드 자산 및 온-프레미스 환경에서 고객 리소스를 서비스하는 것이 일반적입니다. 많은 MSP 파트너는 이러한 고급 시나리오에서 통합 관리 솔루션을 달성하기 위해 Azure Lighthouse 및 현재 Azure Arc를 사용합니다. MSP는 Azure Resource Manager를 통해 고객&rsquo; 온-프레미스 환경을 관리하고, 대규모로 리소스를 관리하고, Azure 정책을 사용하여 규정 준수를 제어하기 위해 서비스 제품을 확장할 수 있습니다.</p>


  <h2>의료 고객을 위한 하이브리드 환경 전반의 강력한 거버넌스를 ClearDATAdelivering&mdash;</h2>


  <p>Azure Lighthouse, Azure Policy 및 Azure Arc를 사용하여 ClearDATAan&mdash; Azure Expert MSP 및 ISVprovides&mdash; 규정 준수 인사이트를 의료와 같은 규제 산업의 엔터프라이즈 고객에게 제공합니다. Azure Arc를 사용하면 ClearDATA가 하이브리드 환경에서 가상 머신 인벤토리를 쉽게 수행할 수 있으며, Azure Lighthouse와 함께 사용되는 Azure Policy를 사용하면 고객이 사용하는 모든 클라우드 및 프라이빗 데이터 센터 또는 지점의 모든 고객에서 일관성, 보안 및 규정 준수를 달성할 수 있습니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/aa4dbacd-a2e0-4898-a8ee-5fd463a9c388.png"><img alt="ClearDATA - pic1 - NEW" border="0" height="444" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/924a92a0-d09a-4513-8769-300ecc1efa2f.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="ClearDATA - pic1 - NEW" width="1024"></a></p>


  <p align="center"><em>ClearDATA는 하이브리드 환경에서 엔터프라이즈 고객에게 규정 준수 상태 인사이트를 제공합니다.</em></p>


  <p style="margin-left: 40px;">&ldquo;<i>Azure의 ClearDATAs&rsquo; HIPAA 규격 및 HITRUST 9.1 인증 솔루션은 엔터프라이즈 조직이 더 큰 신뢰도로 클라우드로의 이동을 쉽게 전환하고 가속화할 수 있도록 지원합니다. 고유한 자동화된 세이프가드 및 수정 기술과 함께 Azure 서비스에 대한 규정 준수 참조 아키텍처의 풍부한 라이브러리는 Azure Lighthouse 및 Azure 클라우드의 진정한 잠재력을 실현합니다. 시각적이고 사용하기 쉬운 규정 준수 대시보드 및 유연한 보고서는 규정 준수를 입증하는 데 필요한 투명성과 가시성을 제공합니다.</i>&rdquo;&mdash; 수하스 켈카르, 클리어데이타 최고 제품 책임자.</p>


  <h2>고객 에지 디바이스 요크텔&mdash;모니터링</h2>


  <p>Yorktel은 최종 고객을 대신하여 디스플레이, 마이크, 카메라, 스피커 및 Microsoft Teams 실시간 기능을 포함하여 Microsoft 협업 디바이스(Surface Hubs 1, 2 및 Microsoft Teams 룸&rsquo;)의 상태를 관리합니다. Azure Monitor를 기본 모니터링 도구로, Azure Lighthouse를 보안 액세스 메커니즘으로 피벗함으로써 Yorktel은 에지 디바이스 관리를 흔들고 있습니다. 모든 고객에 대한 통합 보기는 요크텔에 포괄적인 감독을 제공하여 신속한 문제 해결을 위해 응답 워크플로를 트리거하는 시기 적절한 경고를 가능하게 합니다. Azure Lighthouse는 더 원활한 사용자 환경과 더 높은 고객 만족도를 만들었습니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/759ad59d-ac7c-4f7c-a0af-8a3eba7b5bf1.png"><img alt="Yorktel uses Azure Lighthouse and Azure monitor to provide comprehensive oversight across Microsoft collaboration devices. " border="0" height="498" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/3b495e49-33a0-4d37-853b-ba1c9499381a.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="Yorktel은 Azure Lighthouse 및 Azure 모니터를 사용하여 Microsoft 협업 디바이스에서 포괄적인 감독을 제공합니다. " width="1024"></a></p>


  <p align="center"><em>에지 디바이스에 대한 Yorktels&rsquo; Azure 기반 모니터링 워크플로입니다.</em></p>


  <p style="margin-left: 40px;"><em>&ldquo;Yorktels&rsquo; Azure Lighthouse 지원 모니터링 및 관리 솔루션은 더 나은 시기에 제공되지 못했습니다&rsquo;. 사후 COVID-19 세계가 직장으로 복귀할 준비를 하면서 이러한 사전 예방적 문제 및 해결 기술은 관리형 서비스 공급자와 고객 모두에게 극적인 영향을 미칠 수 있습니다. 더 빠르고 대규모 문제 해결을 통해 창출된 효율성을 통해 기업은 전술적, 일상적인 &lsquo;조명 유지보다는 COVID-19 이후 세계에 성장하고 적응하는 데 도움이 되는 전략적이고 혁신적인 이니셔티브에&rsquo; 집중할 수 있습니다.&rdquo; </em>&mdash; Jeremy Short, SVP of Microsoft Solutions, Yorktel</p>


  <h2>관리형 네트워크 서비스 반디스&mdash;델리버링</h2>


  <p>또한 Azure Lighthouse는 <a href="https://docs.microsoft.com/en-us/azure/networking/networking-partners-msp" target="_blank">Azure 네트워킹 MSP</a>와 같은 여러 서비스 공급자가 고객 프레미스에서 Azure의 고객 구독으로 최적화된 하이브리드 연결을 빌드하고 운영할 수 있도록 했습니다. 예를 들어 Vandis는 Azure Lighthouse를 사용하여 Azure Virtual WAN 및 Azure Express Route를 기반으로 고객을 위한 하이브리드 네트워크를 계획, 빌드 및 운영합니다.</p>


  <p style="margin-left: 40px;"><i>&ldquo;Azure Lighthouse를 사용하면 고객에게 Network-as-a-Service 플랫폼을 확장하고 Azure의 Windows Virtual Desktop과 같은 가정용 솔루션을 구동할 수 있었습니다.&rdquo; </i><i>&mdash;</i> Ryan Young, CTO, Vandis</p>


  <h2>Azure에서 대규모 관리 시나리오를 위한 혁신을 위한 Azure Lighthousecontinuing&mdash;</h2>


  <p>Azure 및 하이브리드 자산을 관리하기 위한 향상된 서비스를 통해 공동 고객에게 계속해서 가치를 더해 주신 모든 파트너에게 축하드립니다. 우리 팀은 파트너 에코시스템을 위해 그 어느 때보다도 혁신할 의욕을 가지고 있으며&rsquo;, 그 결과 지속적으로 새로운 Azure Lighthouse 기능을 추가해 왔습니다.</p>


  <p>다음은 몇 가지 주요 사항입니다.</p>


  <ul>
      <li>이제 서비스 공급자는 <a href="https://docs.microsoft.com/en-us/azure/lighthouse/how-to/monitor-at-scale" target="_blank">고객&rsquo; 리소스 위임 작업을 모니터링</a>하는 활동 로그를 통해 자신의 Azure 컨트롤 플레인에서 팀에 대한 알림 및 온보딩 워크플로를 트리거할 수 있습니다.</li>
      <li>이제 고객은 다른 포털 또는 마켓플레이스를 방문하지 않고 서비스 공급자 보기에서 자체 Azure Portal 환경 내에서 <a href="https://docs.microsoft.com/en-us/azure/lighthouse/how-to/view-manage-service-providers" target="_blank">관리 서비스 제품을 업그레이드</a> 할 수 있습니다.</li>
      <li>CLI(명령줄 인터페이스), API(<a href="https://docs.microsoft.com/en-us/rest/api/resources/subscriptions/get" target="_blank">구독</a> 함수) 및 PowerShell에서 선택한 자동화 도구는 이제 Azure 구독의 관리 및 관리 테넌트 컨텍스트를 표시할 수 있습니다.</li>
      <li>서비스 공급자는 규정 준수 및 오프보딩 요구를 가속화하기 위해 <a href="https://docs.microsoft.com/en-us/azure/role-based-access-control/built-in-roles#managed-services-registration-assignment-delete-role" target="_blank">고객이 위임한 Azure 범위를</a> 자체 관리하지 않고 옵트아웃할 수 있습니다.</li>
      <li>Azure <a href="https://azure.microsoft.com/en-us/blog/backup-explorer-now-available-in-preview/" target="_blank">Backup Explorer</a> 및 <a href="https://docs.microsoft.com/en-us/azure/backup/configure-reports" target="_blank">Backup 보고서는</a> 이제 서비스 공급자를 위한 고객 간 통합 보기를 제공하여 운영자 효율성을 높입니다.</li>
      <li>Azure Lighthouse는 이제 Microsoft Azure Government에서 사용할 수 있는 <a href="https://docs.microsoft.com/en-us/azure/azure-government/compliance/azure-services-in-fedramp-auditscope#azure-government-services-by-audit-scope" target="_blank">FEDRAMP High 인증 서비스</a>입니다.</li>
      <li>이제 파트너는 파트너 센터에서 직접 <a href="https://docs.microsoft.com/en-us/azure/lighthouse/how-to/publish-managed-services-offers" target="_blank">관리 서비스 제품을 작성하고</a> Azure Marketplace에 게시하여 제품 및 잠재 고객 관리를 단일 포털로 간소화할 수 있습니다.</li>
      <li>일반적인 문제에 대한 권장 솔루션을 포함하여 Azure Lighthouse 도움말 및 지원 환경이 향상되어 문제를 직접 해결하기 위해 더 많은 인사이트를 통해 테넌트를 관리할 수 있습니다.</li>
  </ul>


  <p>Azure&rsquo; Lighthouse를 사용하여 빌드 2020을 래핑합니다. 나는 7 월에 인스파이어 2020에서 당신과 더 많은 것을 공유하기를 기다릴 수 없다. 그 동안 새 <a href="https://docs.microsoft.com/en-us/learn/modules/intro-to-azure-lighthouse/" target="_blank">Azure Lighthouse 학습 콘텐츠를</a> 확인합니다.</p>
