### YamlMime:Yaml
ms.openlocfilehash: de2d6c1aa023790510b3e75666cae1e42f58e72b
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139902210"
Slug: best-practices-for-building-reliable-sql-azure-database-client-applications
Title: 신뢰할 수 있는 SQL Azure 데이터베이스 클라이언트 애플리케이션을 빌드하기 위한 모범 사례
Summary: '[이 문서는 SQL Azure 팀에서 제공했습니다.] Valery Mizonov는 SQLCAT에 "신뢰할 수 있는 SQL Azure 데이터베이스 클라이언트 애플리케이션을 빌드하기 위한 모범 사례"라는 논문을 발표했습니다. 종이...'
Content: <p>[이 문서는 SQL Azure 팀에서 제공했습니다.]</p><p>Valery Mizonov는 SQLCAT에 "신뢰할 수 있는 SQL Azure 데이터베이스 클라이언트 애플리케이션을 빌드하기 위한 모범 사례"라는 논문을 발표했습니다. 이 문서에서는 SQL Azure 관련된 재시도 시나리오를 처리하기 위해 SqlConnection과 같은 ADO.NET 클래스의 서브클래싱에 대해 설명합니다. 코드는 훌륭한 디딤돌입니다. 표준 ADO.NET 호출을 사용자 지정 클래스로 대체합니다. 문서를 읽고 여기에 코드를 다운로드합니다.</p>
