### YamlMime:Yaml
ms.openlocfilehash: e942c7a9d5c492a01b1b6451fb94b2ebbbc9de24
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139898706"
Slug: best-practices-for-process-server-deployment-when-protecting-vmware-and-physical-workloads-with-azure-site-recovery
Title: Azure Site Recovery를 사용하여 VMware 및 물리적 워크로드를 보호할 때 프로세스 서버 배포에 대한 모범 사례
Summary: 이 게시물은 InMage 복제 채널 또는 마이그레이션 가속기를 사용하여 ASR을 구현할 때 프로세스 서버 구성 요소의 크기 조정 및 배치에 대한 지침을 제공합니다.
Content: >-
  2014년 여름, Microsoft는 광범위한 플랫폼 및 운영 체제를 지원하는 엔터프라이즈급 DR(재해 복구) 제품을 구축하는 데 전문화된 <a href="https://aka.ms/microsoft_acquires_inmage">InMage Systems라는 회사를 인수</a> 했습니다. 인수 직후 <a href="https://aka.ms/asr_for_vmw_phy_site_to_site">InMage의 사이트 간 및 사이트 간 호스팅자 DR용 주력 제품은 ASR(Microsoft Azure Site Recovery)의 일부가 되었습니다</a>. 이를 위해 고객이 가동 중지 시간을 최소화하면서 워크로드를 <a href="https://aka.ms/what_is_microsoft_azure">Microsoft Azure</a> 빠르고 쉽게 마이그레이션할 수 있는 InMage 기술을 기반으로 하는 서비스인 <a href="https://aka.ms/ma_preview">Microsoft Migration Accelerator의 미리 보기</a>로 이 작업을 수행했습니다.


  &nbsp;


  기본적으로 InMage 복제 채널을 활용하는 모든 현재 제품은 동일한 기본 아키텍처를 기반으로 합니다. 관련된 핵심 구성 요소는 다음과 같습니다.

  <ul>
   <li><b>구성 서버</b> – 복제 정책, 복제 상태 및 상태 보고서를 유지 관리하는 보조 사이트에서 실행되는 VM입니다.</li>
   <li><b>마스터 대상</b> – 복제된 모든 데이터 및 변경 저널의 리포지토리 역할을 하는 보조 사이트에서 실행되는 VM입니다.</li>
   <li><b>Mobility Service </b>– 복제를 위해 보호된 워크로드에서 생성되는 데이터 변경 내용을 실시간으로 메모리에서 직접 캡처하는 경량 소프트웨어 구성 요소입니다.</li>
   <li><b>프로세스 서버</b> – 복제의 모든 컴퓨팅 및 IO 집약적 측면을 처리하는 기본 사이트에 상주하는 게이트웨이입니다.<b></b></li>
  </ul>

  이 블로그 게시물에서는 InMage 복제 채널 또는 Migration Accelerator를 처음 사용하여 ASR을 구현하는 사용자를 위한 프로세스 서버 구성 요소의 크기 조정 및 배치에 대한 지침을 제공합니다.


  &nbsp;

  <h3>프로세스 서버란?</h3>

  프로세스 서버는 보호되는 기본 워크로드와 동일한 위치에 있는 게이트웨이 어플라이언스입니다. R2를 실행하는 물리적 또는 가상 머신에 배포할 수 Windows Server 2012. DR 목적으로 보조 위치에 복제하기 전에 기본 워크로드에서 데이터 변경 내용을 수신하고 압축, 암호화, 캐싱 및 대역폭 관리를 수행합니다. 이 방법은 프로세스 서버에 대한 연속 복제와 관련된 모든 컴퓨팅 및 IO 집약적 작업을 오프로드하여 보호된 워크로드의 거의 모든 오버헤드를 제거합니다.


  &nbsp;


  <a href="https://acom.azurecomcdn.net/80C57D/blogmedia/blogmedia/2015/01/21/image.png"><img style="padding-top: 0px; padding-left: 0px; padding-right: 0px; border-width: 0px;" title="이미지" alt="image" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/image_thumb.png" width="614" height="223" border="0" /></a>


  &nbsp;

  <h3>프로세스 서버 배치</h3>

  InMage의 호스트 오프로드 아키텍처의 최대 이점을 얻으려면 항상 보호되는 <b>기본 워크로드와 동일한 위치에 프로세스 서버를 프로비전합니다</b> . 이렇게 하면 주 워크로드의 컴퓨팅 및 IO 오버헤드가 거의 존재하지 않습니다.


  &nbsp;

  <h3>프로세스 서버 크기 조정</h3>

  일반적으로 프로세스 서버 크기 조정은 보호된 모든 워크로드의 일일 변경률에 따라 달라집니다. 인라인 압축 및 암호화와 같은 작업을 수행하려면 충분한 컴퓨팅이 필요합니다. 또한 기본 사이트와 보조 사이트 간에 네트워크 병목 상태 또는 중단이 발생할 경우 충분한 캐시 스토리지를 프로비전해야 합니다. 아래 표에서는 특히 InMage 복제 채널 또는 마이그레이션 가속기를 사용하여 ASR을 처음 구현할 때 따라야 할 좋은 지침을 제공합니다.

  <table border="1" cellspacing="0" cellpadding="0">

  <tbody>

  <tr>

  <td valign="top" width="96"><i>데이터 변경률</i><i></i></td>

  <td valign="top" width="90"><i>CPU</i><i></i></td>

  <td valign="top" width="68"><i>메모리</i><i></i></td>

  <td valign="top" width="98"><i>부팅 볼륨 용량</i><i></i></td>

  <td valign="top" width="150"><i>캐시 디스크 크기</i><i></i></td>

  <td valign="top" width="150"><i>필요한 총 디스크 처리량</i><i></i></td>

  <td valign="top" width="128"><i>NIC 세부 정보</i><i></i></td>

  </tr>

  <tr>

  <td valign="top" width="96">최대 300GB/일</td>

  <td valign="top" width="90">4개 코어</td>

  <td valign="top" width="68">8GB</td>

  <td valign="top" width="98">40GB</td>

  <td valign="top" width="150">최소 400GB</td>

  <td valign="top" width="150">15 - 20MB/s</td>

  <td valign="top" width="128">고정 IP를 사용하는 2 x 1 GigE</td>

  </tr>

  <tr>

  <td valign="top" width="96">최대 700GB/일</td>

  <td valign="top" width="90">8개 코어</td>

  <td valign="top" width="68">16GB</td>

  <td valign="top" width="98">40GB</td>

  <td valign="top" width="150">최소 790GB</td>

  <td valign="top" width="150">34.9 - 46.6MB/s</td>

  <td valign="top" width="128">고정 IP를 사용하는 2 x 1 GigE</td>

  </tr>

  <tr>

  <td valign="top" width="96">최대 1TB/일</td>

  <td valign="top" width="90">8개 코어</td>

  <td valign="top" width="68">32GB</td>

  <td valign="top" width="98">40GB</td>

  <td valign="top" width="150">최소 790GB</td>

  <td valign="top" width="150">51.2 - 68.27MB/s</td>

  <td valign="top" width="128">고정 IP를 사용하는 2 x 1 GigE</td>

  </tr>

  </tbody>

  </table>

  캐시 디스크의 IO는 일반적으로 크고 순차적입니다. 필요한 처리량을 달성하기 위해 캐시 디스크 뒤의 스핀들 수는 용량보다 더 중요한 경향이 있습니다. 프로세스 서버가 물리적 컴퓨터에서 프로비전되는 경우 충분한 스핀들을 얻기 위해 넓은 스트라이프를 사용하여 FC 또는 iSCSI 스토리지 배열에서 캐시 디스크/LUN을 프로비전하는 것이 좋습니다. 프로세스 서버가 VM으로 프로비전되는 경우 캐시용 가상 디스크가 SAN에서 시작된 블록 또는 파일 기반 데이터 저장소에 상주하는지 확인하는 것 외에 특별한 작업을 수행할 필요가 없습니다. 1TB/일 이상의 변경률의 경우 필요에 따라 추가 프로세스 서버를 배포하여 스케일 아웃하는 것이 좋습니다. 이 내용은 프로파일링 및 용량 계획에 대한 향후 블로그 문서에서 자세히 설명될 예정입니다.


  &nbsp;

  <h3>기타 고려 사항</h3>

  IP 네트워크를 통해 복제가 발생하므로 프로세스 서버에는 몇 가지 인바운드 및 아웃바운드 포트가 열려 있어야 합니다. 인바운드 포트에는 원본 및 대상 엔터티에서 데이터 전송을 위한 9080 또는 9443이 포함됩니다. 및 아웃바운드 포트에는 복제 상태 및 상태에 대한 실시간 업데이트를 제공하기 위해 구성 서버에 대한 80 또는 443이 포함됩니다. 기본 사이트와 보조 사이트의 구성 요소 간에 연결하려면 프로세스 서버의 인터페이스 중 하나에 대해 보안 사이트 간 VPN 터널 또는 NAT IP가 있는 공용 인터넷을 사용할 수 있습니다. <a href="https://aka.ms/ma_ports">마이그레이션 가속기를 배포하는 데 필요한 포트의 전체 보기는 여기에서 확인할 수 있습니다</a>.

  <h4></h4>

  <h4>요약</h4>

  요약하자면, InMage 복제 채널을 사용하여 ASR용 프로세스 서버를 프로비전하는 경우의 크기 조정 및 배치 측면은 보호된 워크로드 수 및 일일 변경률과 같은 몇 가지 요인에 따라 달라집니다. 최상의 결과를 위해 이 블로그 게시물에 제공된 지침을 따르는 것이 좋습니다. 추가 질문 또는 의견을 보려면 <a href="https://aka.ms/asr_msdn_forums">MSDN의 Azure Site Recovery 포럼을 확인</a>하세요. <a href="https://aka.ms/asr_for_vmw_phy_site_to_site">Azure Site Recovery 및 VMware 및 물리적 워크로드를 보호하는 기능에 대해 자세히 알아보</a>려면 단계별 설명서를 확인하세요. <a href="https://aka.ms/asr_landing">Azure Site Recovery를 시작하기 위해 무료 Azure 평가판에 등록할 수도 있습니다</a>.
