### YamlMime:Yaml
ms.openlocfilehash: fd1196526998ed60cf05de1a406640cddb4909f4
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139898683"
Slug: bring-the-power-of-serverless-to-your-iot-application-and-compete-for-cash-prizes
Title: IoT 애플리케이션에 서버리스 기능을 제공하고 상금을 놓고 경쟁하세요.
Summary: 요즘은 어떤 식으로든 인터넷에 연결된 것을 지나가지 않는 것이 어렵습니다. 책상, 주머니, 손목, 벽, 주방, 차량, 공장, 교통 ...
Content: >-
  <p>요즘은 어떤 식으로든 인터넷에 연결된 것을 지나가지 않는 것이 어렵습니다. 책상, 주머니, 손목, 벽, 주방, 차량, 공장, 교통 정류장, 식료품점&hellip; 등 모든 곳에 있습니다. 이러한 작업은 유용한 작업을 수행하고, 데이터를 수집하며, 가장 중요한 것은 기본 제공 연결을 갖습니다. 클라우드의 처리 능력, 가용성 및 인텔리전스를 사용하여 이러한 항목의 데이터를 안전하게 캡처, 처리 및 분석할 때 달성할 수 있는 작업은 무궁무진합니다. 우리는 당신과 함께 이러한 가능성을 탐구하고 싶습니다!</p>


  <p>그래서 우리는 당신의 기회를 위해 <a href="https://azurehacks.devpost.com/" target="_blank">서버리스 해커톤에서 Azure IoT</a> 참여하도록 초대합니다 *<strong> $ 20,000 상금 풀</strong>의 조각.</p>


  <p><a href="https://azurehacks.devpost.com/" target="_blank"><img alt="Azure IoT on Serverless Hackathon" border="0" height="264" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/ed5e4043-a7a2-4331-a0fb-712075544ac6.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="서버리스 해커톤에서 Azure IoT" width="1582"></a></p>


  <p>이 온라인 대회는 앞으로 몇 개월 동안 진행되며 참여하고자하는 모든 사람에게 열려 있습니다. 이 대회는 상금을 획득하는 것 외에도 Azure 블로그에 추천할 수 있는 기회를 제공합니다.</p>


  <p>연기한 센서 기반 스마트 홈 프로젝트에서 작업하거나, 의료 시설에 대한 원격 모니터링 솔루션을 구축하거나, 생산 공장의 제조 프로세스를 간소화하는 지능형 시스템을 만들거나, 멋진 선글라스를 착용한 자가 치유 로봇을 만들든 모든 아이디어를 환영합니다. 이 도전은 당신을위한 것입니다!</p>


  <h2>이 서버리스 항목은 어떨까요?</h2>


  <p><a href="https://azure.com/serverless" target="_blank">서버리스</a> 아키텍처를 사용하는 것은 일반적으로 IoT 백 엔드에 대한 인프라 관리와 함께 제공되는 미분화되지 않은 무거운 리프팅 대신 트래픽 &ndash; 의 변수에 관계없이 데이터를 &ndash; 처리하고 데이터를 생성하는 데 집중할 수 있기 때문에 <a href="https://azure.microsoft.com/en-us/product-categories/iot/" target="_blank">사물 인터넷</a> 프로젝트에 매우 적합합니다. 여기에 Azure Functions 또는 Logic Apps가 다른 클라우드 서비스와 함께 제공하는 통합을 추가하면 클라우드 기반 IoT 애플리케이션을 빌드하는 가장 빠르고 저렴한 방법이 있습니다.</p>


  <p><strong>솔루션을 삭제하는 턱</strong>으로 우리를 놀라게하고 그것을 구축하는 동안 IoT 프로젝트에 서버리스가 될 가능성을 탐구!</p>


  <h2>&ldquo;좋아, Im&rsquo; 어떻게&hellip; 가입합니까?&rdquo;</h2>


  <p>계속 진행하여 온라인 해커톤에 등록할 수 있습니다 <a href="https://azurehacks.devpost.com" target="_blank">https://azurehacks.devpost.com</a>. 구독이 아직 없는&rsquo; 경우 <a href="https://aka.ms/iotfunchackfree" target="_blank">무료 Azure 계정에</a> 등록하고 <strong>IoT Hub 및 Azure Functions</strong>뿐만 아니라 포함할 수 있는 다른 서비스, 디바이스 또는 기술을 사용하여 솔루션 빌드를 시작합니다.</p>


  <p>Azure를 처음 사용하세요? 서버리스를 새로 사용하시겠습니까? 걱정하지 마세요! 디바이스 또는 센서에서 데이터를 캡처하고, 집계, 필터링 또는 이 데이터에 대한 다른 사용자 지정 처리를 수행하고, 데이터베이스에 저장하는 방법에 대한 이 <a href="https://aka.ms/funciotsample" target="_blank">빠른 샘플을</a> 확인하세요. 이 샘플에서는 <strong>IoT Hub와 Azure Functions 간의 통합을 설정하고, Azure Functions</strong>에 대한 트리거 및 바인딩에 대해 자세히 알아보고, <strong>Cosmos DB</strong>에서 처리된 데이터를 삭제하는 방법을 이해합니다.</p>


  <h2>나에게 돈을 보여!</h2>


  <p>이 해커톤은 이러한 서비스를 함께 사용할 수 <strong>있는 훌륭한 실습 학습 기회를</strong> 제공하는 것 외에도 최고의 프로젝트에 <strong>큰 상을</strong> 제공합니다.</p>


  <ul>
   <li>1위를 차지한 솔루션의 <strong>상금 $10,000</strong></li>
   <li>2위를 차지한 솔루션에 대한 <strong>$6,000의 상금</strong></li>
   <li>3위를 차지한 솔루션의 <strong>상금 $3,000</strong></li>
   <li>대중 투표를 통해 선택된 인기 있는 선택 솔루션에 대한 <strong>$1,000의 상금</strong></li>
  </ul>


  <p><strong> 심사위원단</strong>은 모든 제출을 검토하고 평가하며, 수상 솔루션을 선택합니다. 이 패널은 IoT, 클라우드 컴퓨팅 및 서버리스 분야의 Microsoft 전문가로 구성됩니다. 조건은 <strong>아이디어의 품질, 구현 및 프로덕션 사용에 대한 잠재적 값으로</strong> 구성됩니다. <a href="https://azurehacks.devpost.com/" target="_blank">Hackathon 웹 사이트에서</a> 모든 관련 세부 정보를 찾을 수 있습니다.</p>


  <p>위의 동기 부여가 충분하지 않은 경우 Azure 블로그에서 성공적인 프로젝트와 개발자를 강조 표시하므로 빌드 중인 멋진 내용을 전 세계에 알릴 수 있습니다.</p>


  <h2>다음 단계</h2>


  <ul>
   <li><a href="https://azurehacks.devpost.com/" target="_blank">해커톤 웹사이트</a>에서 대회에 등록하세요.</li>
   <li><a href="https://aka.ms/funciotsample" target="_blank">Azure Functions를 통해 IoT Hub 데이터를 처리하는</a> 방법을 알아봅니다.</li>
   <li><a href="https://azure.microsoft.com/en-us/blog/go-serverless-for-your-iot-needs/" target="_blank">IoT 요구 사항에 맞게 서버리스로 이동하는 방법에 대한</a> 몇 가지 예제를 확인하세요.</li>
  </ul>


  <p>다음 주에 <a href="https://www.microsoft.com/en-us/build" target="_blank">Microsoft Build</a> 컨퍼런스에서 발표될 공지 사항을 주시하고 솔루션 작업을 즉시 시작하세요!</p>


  <p>해킹 게임을 시작하자!</p>


  <p>&nbsp;</p>


  <p>*구매가 필요하지 않습니다. 해당 국가의 대다수 연령인 신규 및 기존 Devpost 사용자에게만 개방됩니다. 경기는 2018년 8월 2일 오후 5:00 동부 시간으로 종료됩니다. 자세한 내용은 <a href="https://azurehacks.devpost.com/rules" target="_blank">공식 규칙을 참조하세요</a>.</p>
