### YamlMime:Yaml
ms.openlocfilehash: 72b74c89a8323e8967fd604681631773d96f11aa
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139898087"
Slug: bringing-commercial-innovations-in-chip-design-to-national-security
Title: 국가 안보에 칩 디자인의 상업적 혁신 가져오기
Summary: 반도체 및 마이크로 일렉트론스는 위성과 레이더에서 차량 및 통신 장비에 이르기까지 국가 안보 및 방위 기술에 대한 최첨단 기능을 구축하는 데 가장 중요한 구성 요소 중 하나입니다.
Content: >-
  <p>반도체와 마이크로 일렉트론스는 위성과 레이더에서 차량 및 통신 장비에 이르기까지 국가 안보 및 방위 기술에 대한 최첨단 기능을 구축하는 데 가장 중요한 구성 요소 중 일부입니다. 보안과 관련하여 이러한 구성 요소가 개발되도록 하는 것은 중요하면서도 어려운 작업입니다. 지금까지 마이크로 일렉트론 개발과 관련된 보안 요구 사항은 미국 국방부&rsquo;(DoD)가 최신 혁신을 활용하는 능력을 제한했습니다.</p>


  <p>고급 상용 기능을 사용하는 최근&nbsp;DoD 후원 프로젝트인 RAPID Assured Microelectronics 프로토타입(RAMP)을 통해 목표는 상업적 모범 사례를 활용하여 개발 프로세스를 가속화하고 안정적이고 안전한 최첨단 마이크로 일렉트론 설계 및 제조를 국가 안보 및 방위 애플리케이션에 제공하는 것입니다. DoDrecently&nbsp;는 <a href="https://nstxl.org/opportunity/ramp-phase-ii/" target="_blank">이 프로젝트의 두 번째 단계를 지원하기 위해 Microsoft를</a> 선택했다고 발표했습니다.</p>


  <p>이 프로젝트는 Microsoft와 미국 국방부 간의 40년 간의 협력 역사를 바탕으로 국가 안보 커뮤니티에 상업적 혁신을 가져다 줍니다. Microsoft는 이전에 이 이니셔티브의 <a href="https://azure.microsoft.com/en-us/blog/innovations-for-a-more-secure-us-microelectronics-supply-chain/" target="_blank">첫 번째 단계에서</a> DoD와 협력하는 파트너 연합을 이끌고 부서&rsquo; 임무 우선 순위를 달성하는 디자인 기능을 개발했습니다. 이 두 번째 단계에서 Microsoft와 파트너는 이러한 성공적인 디자인을 기반으로 하여 고급 제조 프로세스에 대한 액세스를 제공하는 안전하고 협력적인 디자인 흐름을 사용하여 사용자 지정 SoC(통합 칩 및 시스템) 설계 개발을 시작합니다. 이러한 새로운 디자인은 전력 소비를 줄이고, 성능을 향상시키고, 물리적 크기를 줄이며, DoD 시스템의 애플리케이션에 대한 안정성을 향상합니다.</p>


  <p>Microsoft는 DIB(상용 및 방위 산업 기지)에서 마이크로 일렉트론학 업계 리더&nbsp;들과 협력하여 RAMP 프로젝트의 이 단계를 개발했습니다. collaboratorsinclude Ansys&nbsp;, Applied Materials, Inc., BAE Systems, Battelle Memorial Institute, Cadence Design Systems, Cliosoft, Inc., Flex Logix, GlobalFoundries, Intel Federal, Raytheon Intelligence andSpace&nbsp;, Siemens EDA, Synopsys, Inc., Tortuga Logic 및 Zero ASIC Corporation.</p>


  <p>RAMP 솔루션은 클라우드, AI 및 기계 학습 지원 자동화, 보안 및 정량화 가능한 보증을 통해 중요 업무용 애플리케이션을 위한 고급 마이크로 일렉트로닉스 개발 플랫폼을 제공합니다. 이 솔루션은 <a href="https://azure.microsoft.com/en-us/global-infrastructure/government/" target="_blank">Azure Government</a>에서 호스트되며, 미국 전역에서 사용할 수 있는 서비스를 통해 정부를 위한 가장 광범위한 상업적 혁신을 제공합니다.&nbsp; 데이터 분류.</p>


  <p>RAMP는 DoDto&nbsp;가 안전하고 확장 가능한 마이크로 일렉트론 공급망을 활용하는 동시에 설계 및 제조가 엄격한 보안 및 규정 준수 요구 사항을 충족하도록 보장하는 중요한 이니셔티브입니다. RAMP는 클라우드 기반 보안 설계 기능을 활용하여 DoD에 사용할 수 있는 주조소 수를 확장하고 복원력을 향상시키며 국내 반도체 공급망의 성장을 촉진할 것입니다. RAMP의 성공으로 부서가 기술 개발에 더 민첩하고, 진화하는 요구에 신속하게 적응하고, 최신 기술 기능을 채택할 수 있습니다. 우리는 마이크로 일렉트론 공급망을 보호하기 위해 획기적인 혁신적인 솔루션을 제공하기 위해 DoD 및 업계 파트너와 지속적으로 협력하기를 기대합니다.</p>
