### YamlMime:Yaml
ms.openlocfilehash: 30d9de67f21a509cf0154353222db593dcabd0ff
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139913073"
Slug: build-cloudnative-applications-that-run-anywhere
Title: 어디서나 실행되는 클라우드 네이티브 애플리케이션 빌드
Summary: 차세대 개발자가 미래의 애플리케이션을 빌드할 수 있도록 하는 세계적 수준의 도구와 클라우드 서비스를 제공하는 것은 Microsoft의 사명입니다. 이러한 미래의 애플리케이션은 지능적이고 AI가 주입되어 고급 인사이트를 제공합니다. 전 세계의 오픈 소스 기술과 라이브러리를 통합할 예정입니다.로드 시 안정적이고 설계상 안전합니다. 또한 개발자가 아이디어에서 코드로 원활하게 이동할 수 있는 도구를 사용하여 빌드됩니다.
Content: >-
  <p>개발자의 전 세계 인구는 2030년에 7,150만 명에 이를 것으로 추정되며, 이는 현재 <sup>1</sup>명에서 4,450만 명의 개발자가 증가한 것입니다. 각각의 새로운 개발자는 자신이&rsquo; 전 세계와 공유하고자 하는 아이디어와 혁신을 제공합니다. 차세대 개발자가 미래의 애플리케이션을 빌드할 수 있도록 하는 세계적 수준의 도구와 클라우드 서비스를 제공하는 것이 우리의 임무입니다.</p>


  <p>이러한 미래의 애플리케이션은 지능적이고 AI가 주입되어 고급 인사이트를 제공합니다. 전 세계의 오픈 소스 기술과 라이브러리를 통합할 것입니다. 로드 시 안정적이고 설계상 안전합니다. 또한 개발자가 아이디어에서 코드로 원활하게 이동할 수 있는 도구를 사용하여 빌드됩니다.</p>


  <p>컨테이너, Kubernetes, 마이크로 서비스, 서버리스 함수 및 API 중심 설계와 같은 <a href="https://azure.microsoft.com/en-us/overview/cloudnative/" target="_blank">클라우드 네이티브 기술을</a> 활용하여 미래의 애플리케이션을 빌드하는 Microsoft Azure 고객을 확인합니다.</p>


  <ul>
      <li><a href="https://customers.microsoft.com/en-us/story/784791-mercedes-benz-r-and-d-creates-container-driven-cars-powered-by-microsoft-azure" target="_blank">메르세데스 벤츠</a> 는 직접 유지 보수 방문을 요구하는 대신 무선으로 동적으로 애플리케이션을 제공함으로써 고객의 차량 내 환경을 개선하고 있습니다.</li>
      <li><a href="https://customers.microsoft.com/en-us/story/811347-pwc-partner-professional-services-azure" target="_blank">PwC</a> 는 고객이 몇 주가 아닌 몇 초 안에 문서를 마인 및 분석할 수 있는 AI 기반 시스템을 사용하여 규정을 준수하도록 지원하고 있습니다.</li>
      <li><a href="https://customers.microsoft.com/en-us/story/765209-bosch-increases-vehicle-safety-using-map-matching-algorithms-and-azure-kubernetes-service" target="_blank">보쉬는</a> 자동차가 밀리초 이내에 고속도로에서 잘못된 길을 갈 때 인근 운전자에게 경고하는 시스템으로 생명을 구하는 데 도움을 주고 있습니다.</li>
  </ul>


  <p>고객이 Azure에서 클라우드 네이티브 기술을 사용하여 경험한 성공으로 많은 사람들이 이제 다른 환경에서 이러한 성공을 복제하려고 합니다. Azure 및 온-프레미스 환경, 에지 위치 및 AWS 및 Google Cloud와 같은 다른 클라우드에서 클라우드 네이티브 워크로드에 대한 동급 최고의 개발 및 관리 환경을 원합니다.</p>


  <h2>Azure 애플리케이션 서비스: 어디서나 앱&nbsp; 실행</h2>


  <p>오늘 <strong>Kubernetes 및 Azure</strong> , 온-프레미스, AWS 및 Google Cloud에서 실행할 Azure 애플리케이션 서비스의 미리 보기 기능을 발표합니다. Azure Arc를 통해 연결된 CNCF(클라우드 네이티브 컴퓨팅 파운데이션) 준수 Kubernetes 클러스터는 이제 Azure 애플리케이션 서비스에 지원되는 배포 대상입니다.</p>


  <p>Azures&rsquo; 애플리케이션 서비스는 함께 작동하도록 설계되었으며 개발자 생산성을 위해 고도로 최적화되어 있습니다. 여기에는 다음이 해당합니다.</p>


  <ul>
      <li><a href="https://azure.microsoft.com/en-us/services/app-service/" target="_blank">Azure App Service</a> 를 사용하면 자동 크기 조정, 배포 슬롯 및 통합 웹 인증과 같은 완전히 관리되는 플랫폼과 기능을 사용하여 웹 애플리케이션 및 API를 쉽게 빌드하고 관리할 수 있습니다.</li>
      <li><a href="https://azure.microsoft.com/en-us/services/functions/" target="_blank">Azure Functions</a> 는 최신 자동 크기 조정을 통해 이벤트 기반 프로그래밍을 간단하게 만들고 트리거 및 바인딩을 사용하여 다른 Azure 서비스와 통합합니다.</li>
      <li><a href="https://azure.microsoft.com/en-us/services/logic-apps/" target="_blank">Azure Logic Apps</a> 400개 이상의 커넥터 라이브러리와 앱, 데이터, 서비스 및 백 엔드 시스템을 통합하기 위한 자동화된 워크플로를 생성합니다.</li>
      <li><a href="https://azure.microsoft.com/en-us/services/event-grid/" target="_blank">Azure Event Grid</a> 는 모든 원본에서 대상으로 이벤트 라우팅을 관리하기 위한 단일 서비스로 이벤트 기반 애플리케이션을 간소화합니다.</li>
      <li><a href="https://azure.microsoft.com/en-us/services/api-management/" target="_blank">Azure API Management</a> 는 모든 내부 및 외부 API에서 통합 관리 환경 및 완전한 가시성을 제공합니다.</li>
  </ul>


  <p>GitHub <a href="https://aka.ms/build21-devvelocityblog" target="_blank">및 Visual Studio Code</a> 긴밀하게 통합된 이러한 클라우드 네이티브 애플리케이션 서비스를 통해 개발자는 빠른 속도로 오늘날 Azure에서 미래의 애플리케이션을 빌드할 수 있습니다.</p>


  <h2>Kubernetes를 제어하는 애플리케이션 서비스의 생산성</h2>


  <p>고객으로부터 계속 듣고 있는 과제 중 하나는 Kubernetes의 향상된 제어 및 에코시스템 혜택에도 불구하고 개발자가 직접 사용하기가 어렵다는 것입니다. 개발자는 많은 고급 개념과 API를 학습해야 하므로 생산성이 저하될 수 있습니다.</p>


  <p>오늘&rsquo; 발표를 통해 개발자는 더 이상 <strong>Azure 애플리케이션 서비스의 생산성과 Kubernetes 제어</strong> 중에서 선택할 필요가 없습니다.</p>


  <p>작동 원리 일반 개발자 워크플로를 사용하여 새 Azure Function을 만들고, 스토리지 큐 트리거와 같은 통합 기능을 사용하고, Azure 지역 대신 Kubernetes 클러스터를 대상으로 지정한 다음, 다른 워크로드와 함께 Kubernetes 모니터링 대시보드에 Azure Functions Pod가 표시되는지 확인합니다. <strong>이제 Azure에서 동일한 생산적인 개발자 환경이 Azure Arc를 통해 연결된 모든 Kubernetes 클러스터에서 작동</strong> 합니다. Kubernetes에서 <a href="https://aka.ms/ArcEnabledAppServices-Build2021-Blog" target="_blank">애플리케이션 서비스</a>&nbsp; 실행에 대해 자세히 알아봅니다.&nbsp;</p>


  <h2>Azure Arc를 사용하여 어디서나 앱 실행</h2>


  <p>개발자는 온-프레미스, 에지 또는 다중 클라우드에서 더 많은 환경을 대상으로 하기 시작하면 애플리케이션 호스팅, 데이터 호스팅, 모니터링, 보안 및 DevOps 자동화를 위한 사용자 지정 솔루션을 빌드해야 하는 경우가 많습니다. 호스팅 환경 변경으로 인해 존재하는 사용자 지정 솔루션을 생성하는 것은 비생산적이며 신뢰할 수 없습니다.</p>


  <p>오늘&rsquo; 발표를 통해 개발자는 <a href="https://azure.microsoft.com/en-us/services/azure-arc/" target="_blank">Azure Arc</a>에서 사용하도록 설정된 <strong>이식 가능한 애플리케이션 서비스를 사용하여 하이브리드 애플리케이션을 빌드하는 시간을 절약할 수 있습니다</strong>. Azure PostgreSQL 및 Azure SQL 같은 Arc 지원 데이터 서비스의 사용과 결합된 경우 애플리케이션 및 해당 데이터는 이제 완전 관리형 클라우드 서비스&mdash; 업계를 먼저 사용하여 어디서나 실행할 수 있습니다.</p>


  <p>Azure 또는 Azure Arc를 통해 애플리케이션 서비스를 사용해 보시겠습니까? <a href="https://aka.ms/apptemplate" target="_blank">GitHub 새로운 시나리오 기반 가속기를</a> 빠르게 시작합니다.</p>


  <h2>온-프레미스 및 클라우드에서 일관되게 앱 관리</h2>


  <p>고객이 환경 전체에서 워크로드를 관리하고 관리하는 데 도움이 되도록 최근에 <a href="https://techcommunity.microsoft.com/t5/azure-arc/azure-arc-enabled-kubernetes-is-now-generally-available/ba-p/2174859" target="_blank">Azure Arc 지원 Kubernetes의 일반 공급</a>이 발표되었습니다. <a href="https://customers.microsoft.com/en-us/story/844606-siemens-healthineers-health-providers-azure-arc" target="_blank">Siemens Healthineers</a>는 Azure Arc의 GitOps 기능을 사용하여 수만 개의 위치에서 Kubernetes 클러스터를 배포하고 관리하여 전 세계 70개국의 병원에서 MRI 스캐너, CT 스캐너, X선 기계 및 초음파 머신을 유지 관리할 수 있습니다. Azure Arc는 CNCF에 부합하는 Kubernetes 클러스터와 함께 작동하며 Azure Portal을 통해 중앙 가시성과 Azure Policy를 통한 거버넌스 및 규정 준수를 <strong>제공하는 단일 창을 제공합니다</strong> .</p>


  <p>관리되는 Kubernetes 컨트롤 플레인을 찾는 고객을 위해 오늘<strong> <a href="https://aka.ms/AKSonHCI" target="_blank">Azure Stack HCI</a>에서 AKS(Azure Kubernetes Service)의 일반 공급이</strong> 발표됩니다. Azure Stack HCI의 AKS를 사용하면 고객은 AKS와 일치하고 Microsoft에서 완전히 지원되며 오픈소스 에코시스템을 100% 준수하는 Kubernetes 클러스터를 쉽게 배포할 수 있습니다. Azure Stack HCI에 AKS를 배포하는 경우 몇 번의 클릭만으로도 됩니다. Azure Stack HCI 클러스터는 기본 제공 보안, 친숙한 관리 도구 및 Azure와의 긴밀한 통합을 제공하는 Azure Arc 지원 기본 제공 클러스터입니다. <a href="https://aka.ms/AKSonHCI" target="_blank">Azure Stack HCI의 AKS에</a> 대해 자세히 알아봅니다.</p>


  <p>&rsquo;클라우드 네이티브 기술을 연구하는 개발자가 되는 것은 흥미로운 시간입니다. 어디서나 실행되는 Microsoft Build 2021 Technical Session <a href="https://mybuild.microsoft.com/sessions/2debfc2e-f0b3-4adf-bcec-d126930f806f" target="_blank">Build 클라우드 네이티브 애플리케이션</a> 을 시청하여 이러한 공지 사항과 클라우드 네이티브 공간의 혁신에 대해 자세히 알아보세요. &nbsp;빌드한 내용을 확인하려면 앞으로 나아보세요.</p>


  <hr>

  <p><sup>1</sup> 데이터 원본: Arnal Dayaratna 박사, IDC 분석가</p>


  <p><em>Azure. 목적에 따라 발명. </em></p>
