### YamlMime:Yaml
ms.openlocfilehash: 282dedaea5efa0528d1ebbd54180078be1228e16
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139907269"
Slug: built-in-security-and-operations-management-for-azure-and-hybrid-environments
Title: Azure 및 하이브리드 환경에 대한 기본 제공 보안 및 운영 관리
Summary: 지난 몇 년 동안 클라우드 인프라 사용량의 증가는 엄청났습니다. 고객과의 대화에서 많은 사람들이 클라우드 보안 및 클라우드에 도움이 되는 기술을 찾고 있습니다.
Content: >-
  <p>지난 몇 년 동안 클라우드 인프라 사용량의 증가는 엄청났습니다. 고객과의 대화에서 많은 사람들이 클라우드 보안 및 클라우드 관리에 도움이 되는 기술을 찾고 있습니다. 더 많은 고객이 클라우드에 뿌리를 두고 실제로 새로운 클라우드 패러다임을 위해 설계된 관리를 요구하고 있습니다. Microsoft는 현재와 미래의 엔터프라이즈를 위한 신뢰할 수 있는 파트너이며, 클라우드 플랫폼을 빌드하고 관리 및 보안 서비스를 제공하는 오랜 역사를 가진 고유한 위치에 있습니다.</p>


  <p>Azure를 사용하면 기본 제공 보안 및 운영 관리가 있고 여전히 가장 큰 엔터프라이즈 고객의 요구를 충족할 수 있는 개방형 클라우드 플랫폼을 제공함에 따라 기존의 플랫폼 범주와 관리 &ndash; 범주 간의 경계가 모호해지고 있습니다. 고객은 전체 보안 및 운영 관리 수명 주기에서 더 간단한 환경을 통해 이 접근 방식을 활용할 수 있습니다. 또한 Azure뿐만 아니라 기존 워크로드를 관리하고 보호하는 도구 빌드의 중요성과&rsquo; 하이브리드 기능 제공에 중점을 두는 이유도 알고 있습니다.</p>


  <p>오늘 Im&rsquo;은 이러한 영역에 걸쳐 몇 가지 새로운 서비스와 기능을 발표하게 되어 기쁩니다.</p>


  <ul>
      <li><strong>Azure Cost Management by Cloudyn은 무료로 사용할 수 있습니다.</strong> Azure Cost Management를 통해 조직은 Azure, AWS 및 Google Cloud Platform에서 클라우드 지출을 관리하고 최적화할 수 있습니다. 비용 관리는 고객의 가장 인기 있는 요청 중 하나였으며&rsquo;, Im은 이제 Azure 고객 및 파트너가 Azure 지출을 관리할 수 있도록 무료로 사용할 수 있음을 발표하게 되어 기쁩니다. <a href="https://azure.com/costmanagement" target="_blank">Cloudyn의 Azure Cost Management에</a> 대해 자세히 알아봅니다.</li>
      <li><strong>하이브리드 워크로드에 대한 Azure Security Center 보호.</strong> Azure Security Center를 사용하면 사이버 위협으로부터 Azure에서 실행되는 워크로드를 보호할 수 있으며, 이제 온-프레미스 및 다른 클라우드에서 실행되는 워크로드를 보호하는 데도 사용할 수 있습니다. 현재는 고급 위협을 더 잘 감지 및 방어하고, 보안 워크플로를 자동화 및 오케스트레이션하고, 위협 조사를 간소화하는 새로운 기능을 릴리스하고 있습니다. <a href="https://aka.ms/hybrid-asc" target="_blank">Azure Security Center 업데이트</a>에 대해 자세히 알아봅니다.</li>
      <li><strong>관리가 Azure Portal의 가상 머신 환경에 통합됩니다.</strong> 이 새로운 환경은 기존 가상 머신에 백업, 사이트 복구, 모니터링, 업데이트 관리 등을 추가하는 프로세스를 간소화합니다.</li>
      <li><strong>업데이트 관리, 구성 관리 &amp; 변경 내용 추적은 Azure 고객이</strong> 누락된 업데이트를 관리하고 Azure의 Windows 및 Linux 가상 머신 및 하이브리드 환경에서 구성 변경 내용을 효율적으로 추적하는 데 도움이 되도록 무료로 포함됩니다. Python 지원은 기존 PowerShell &amp; 그래픽 작성 기능 외에도 Automation 서비스에 추가되어 Windows 및 Linux 환경을 더 쉽게 자동화할 수 있습니다. <a href="https://aka.ms/Vs878t" target="_blank">Azure Automation 및 구성 업데이트</a>에 대해 자세히 알아봅니다.</li>
      <li><strong>애플리케이션에서 인프라로 종단 간 모니터링</strong> 새로운 Azure 모니터 사용자 환경은 인프라 및 애플리케이션 전반에서 가시성을 얻을 수 있도록 모니터링 서비스를 함께 중앙 집중화합니다. 또한 Azure Log Analytics에 대한 환경뿐만 아니라 애플리케이션 Insights 메트릭 탐색, 애플리케이션 성능 모니터링 및 실패 진단도 크게 최적화했습니다. 또한 Azure 경고를 IT 서비스 관리 도구와 통합하고 컨테이너 모니터링을 위한 새로운 솔루션을 출시했습니다. <a href="https://aka.ms/AzMonIgnite17" target="_blank">Azure 모니터링 업데이트</a>에 대해 자세히 알아봅니다.</li>
      <li><strong>거버넌스 및 규정 준수를 제공하는 데 도움이 되는 Azure Policy입니다.</strong> 이제 제한된 미리 보기로 제공되는 새로운 Azure Policy 서비스는 표준을 설정하고, 난간을 보호하며, 규정 준수를 지속적으로 모니터링하여 엔터프라이즈 차원의 거버넌스를 제공하는 데 도움이 됩니다. Azure 정책은 단일 구독에서 전체 조직에서 제어할 수 있는 관리 그룹에 이르기까지 Azure 리소스에 적용할 수 있습니다. <a href="https://azure.com/policy" target="_blank">Azure Policy 제한된 미리 보기</a>에 등록합니다.</li>
      <li><strong>Azure Cloud Shell의 PowerShell 지원</strong> 은 Bash를 또 다른 인증된 브라우저 기반 셸 도구로 보완하여 Azure 관리 환경을 간소화합니다. <a href="https://aka.ms/cloudshell/welcomePS" target="_blank">Azure Cloud Shell의 PowerShell에</a> 대해 자세히 알아봅니다.</li>
  </ul>


  <h2>클라우드 워크로드 보안 및 관리의 중요성</h2>


  <p>고객이 24x7로 비즈니스를 수행할 것으로 예상하고 위협이 점점 더 정교해지는 이 세상에서는 최소한 가상 머신에 대한 보안, 백업 및 모니터링을 설정하는 것이 좋습니다. Azure 플랫폼은 데이터 센터 구축, 유지 관리 및 보안에 대한 보안 및 운영 관리 부담을 줄이도록 설계되었지만, 고객은 Microsoft와 협력하여 Azure 리소스가 올바른 보안 및 규정 준수 제어를 통해 안전하고 잘 관리되도록 할 수 있습니다.&nbsp;</p>


  <p>Microsoft <a href="https://myignite.microsoft.com/sessions/54789?source=sessions" target="_blank">Ignite에서</a> 직접 또는 가상으로 이러한 새로운 기능과 업데이트가 작동하는 것을 볼 수 있기를 바랍니다. &rsquo;클라우드에서 리소스를 보호 및 관리하는 방법에 대해 여러분의 의견을 듣고 피드백을 계속 보내주시기 부탁드립니다. <a href="https://azure.microsoft.com/free/security-management/" target="_blank">무료 계정을 만들어</a> 현재 Azure 보안 및 운영 관리를 탐색할 수 있습니다.</p>
