### YamlMime:Yaml
ms.openlocfilehash: ca0d139caac33fb8e62fd2062738d817f12256b0
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139906092"
Slug: build-a-windows-azure-application-using-twilio-and-win-a-netbook
Title: Twilio를 사용하여 Windows Azure 애플리케이션을 빌드하고 Netbook을 획득하세요!
Summary: '업데이트 [2009년 9월 3일 @ 오전 10:14]: Twilio는 미국에서 노동절 주말을 수용하기 위해 마감일을 일주일 더 연장했습니다.  Windows Azure는 Twilio와 힘을 합쳐 다음 주 #16을 제공합니다.'
Content: '<p><strong>업데이트 </strong>[9/3/2009 @ 10:14AM]: Twilio has  미국에서 노동절 주말을 수용하기 위해 <a href="https://blog.twilio.com/2009/09/back-to-school-back-to-coding-with-windows-azure-extended-contest-category.html">마감일을 일주일 더 연장</a>했습니다.</p>  <p>Windows Azure는 <a href="https://blog.twilio.com/2009/08/announcing-this-weeks-netbook-contest-category-windows-azure-platform.html">Twilio 개발자 콘테스트의 16주차</a>를 가져오기 위해 <a href="https://twilio.com">Twilio</a>와 힘을 합치고 있습니다.&#160; 모르는 분들을 위해 Twilio는 간단한 HTTP 요청을 사용하여 전화를 걸고 받기 위한 웹 서비스 API입니다.&#160; azure Windows를 사용하는 많은 동일한 개발자에게 어필할 수 있다고 생각했습니다.  그래서 이번 주에 우리는 두 가지를 결합하는 애플리케이션을 빌드하기 위해 도전하고 있습니다.</p>  <p>콘테스트 참가자는 9월 6일 일요일 자정까지 신청서를 제출하여 Windows 7, Windows Azure 크레딧으로 500달러(상업적 출시에 도달하면 11월에 시작됨) 및 Twilio.&#160; Netbook을 획득할 수 있는 기회를 얻으려면 Twilio 콘테스트 페이지를 방문하세요.</p>'
