### YamlMime:Yaml
ms.openlocfilehash: f6562a3bac1dcb78329c5f7f3f392b755ce03868
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139906070"
Slug: build-your-application-development-agenda-at-ignite
Title: Ignite에서 애플리케이션 개발 어젠다를 빌드하세요!
Summary: 새로운 개발 기술, 새로운 연결된 디바이스 및 새로운 클라우드 지향 비즈니스 모델은 애플리케이션 개발자가 더 큰 혁신을 추진할 수 있는 특별한 기회를 창출합니다. 여부...
Content: >-
  새로운 개발 기술, 새로운 연결된 디바이스 및 새로운 클라우드 지향 비즈니스 모델은 애플리케이션 개발자가 더 큰 혁신을 추진할 수 있는 특별한 기회를 창출합니다. 온-프레미스 또는 클라우드에서 실행되는 비즈니스 애플리케이션, 고급 웹 포털 또는 클라이언트 사용자 인터페이스를 빌드하든 관계없이 올해 Ignite에 참석할 때 최대한 많은 애플리케이션 개발 지혜를 만끽할 수 있습니다. (만들 수 없는 경우 이 게시물의 맨 아래에 있는 온라인 보기 옵션을 확인하세요.) 직접 참석하든 온라인이든 Ignite에 참석하는 것은 진정한 커리어 향상이 될 수 있습니다.


  다음 샘플 안건에는 애플리케이션 개발자를 위한 가장 관련성이 있고 중요한 세션이 포함되어 있습니다.


  <b>월요일, 5월 4</b>


  9:00AM - Satya Nadella 및 기타 Microsoft 경영진과 함께하는 Microsoft Ignite 키노트


  오후 1:30- <a href="https://ignite.microsoft.com/session/sessionmoreinfo/?topicid=2dfca4c9-00c1-e411-b87f-00155d5066d7#fbid=fQk9eWdVz_x?WT.mc_id=IG15XCSOSC">개발자를 위한 Microsoft 애플리케이션 플랫폼 개요</a>


  3:15PM - <a href="https://ignite.microsoft.com/session/sessionmoreinfo/?topicid=2d5ee1b2-91a1-e411-b87f-00155d5066d7#fbid=NmAyvuzAU-7?WT.mc_id=IG15XCSOSC">연습의 민첩한 개발: 현대화된 개발 주기를 위한 팁 및 요령</a>


  <b>화요일, 5월 5</b>


  오후 1시 30분 - <a href="https://ignite.microsoft.com/session/sessionmoreinfo/?topicid=e3bb0a18-91a1-e411-b87f-00155d5066d7#fbid=NmAyvuzAU-7?WT.mc_id=IG15XCSOSC">새 Premium Azure CDN 소개</a>


  오후 3시 15분 - <a href="https://ignite.microsoft.com/session/sessionmoreinfo/?topicid=4bdc904a-93a1-e411-b87f-00155d5066d7#fbid=fQk9eWdVz_x?WT.mc_id=IG15XCSOSC">모바일로 이동! Azure App Service를 사용하여 Enterprise API에 로그인, 데이터 동기화 및 커넥트</a>


  5:00PM - <a href="https://ignite.microsoft.com/session/sessionmoreinfo/?topicid=87223433-6f85-e411-b87f-00155d5066d7#fbid=NmAyvuzAU-7?WT.mc_id=IG15XCSOSC">Office 365 API를 사용하여 Mobile Apps 켜기</a>


  <b>5월 6일 수요일</b>


  오전 9:00 - <a href="https://ignite.microsoft.com/session/sessionmoreinfo/?topicid=af9f0784-2fa1-e411-b87f-00155d5066d7#fbid=NmAyvuzAU-7?WT.mc_id=IG15XCSOSC">DevOps 사고방식에 대한 Release Management 실용적 보기</a>


  오후 1시 30분 - <a href="https://ignite.microsoft.com/session/sessionmoreinfo/?topicid=d34c3f49-eaaf-e411-b87f-00155d5066d7#fbid=NmAyvuzAU-7?WT.mc_id=IG15XCSOSC">Microsoft Azure Media Services 있는 엔드 투 엔드 미디어 워크플로</a>


  <b>5월 7일 목요일</b>


  오전 9:00 - <a href="https://ignite.microsoft.com/session/sessionmoreinfo/?topicid=03629459-b39a-e411-b87f-00155d5066d7#fbid=NmAyvuzAU-7?WT.mc_id=IG15XCSOSC">Office 365 API를 사용하여 클라우드에서 Microsoft OneNote 사용하여 개발</a>


  오전 10:45 - <a href="https://ignite.microsoft.com/session/sessionmoreinfo/?topicid=f574e3c8-2fa1-e411-b87f-00155d5066d7#fbid=NmAyvuzAU-7?WT.mc_id=IG15XCSOSC">ASP.NET 5 소개</a>


  5:00PM - <a href="https://ignite.microsoft.com/session/sessionmoreinfo/?topicid=99ed2f92-92a1-e411-b87f-00155d5066d7#fbid=fQk9eWdVz_x?WT.mc_id=IG15XCSOSC">Azure App Service Logic Apps 및 BizTalk: 내일의 통합이 오늘 시작됩니다.</a>


  <b>5월 8일 금요일</b>


  오전 9:00 - <a href="https://ignite.microsoft.com/session/sessionmoreinfo/?topicid=dca77d19-92a1-e411-b87f-00155d5066d7#fbid=NmAyvuzAU-7?WT.mc_id=IG15XCSOSC">좋은 앱에 나쁜 일이 발생하는 경우: Azure App Service에서 애플리케이션 문제 해결</a>


  오후 12시 30분 - <a href="https://ignite.microsoft.com/session/sessionmoreinfo/?topicid=5a60d65c-91a1-e411-b87f-00155d5066d7#fbid=NmAyvuzAU-7?WT.mc_id=IG15XCSOSC">Azure App Service에서 Enterprise Web 및 Mobile Apps 실행</a>


  그것은 종류의 당신의 입 물을 만든다, 그렇지 않아? 이러한 세션은 Ignite의 일부일 뿐입니다. 필요한 항목에 맞게 미세 조정된 <a href="https://myignite.microsoft.com/#/sessions?WT.mc_id=IG15XCSOSC">이벤트 명단을 만들</a> 수 있습니다. 또한 근무 시간 후 네트워킹 활동에서 같은 생각을 가진 많은 사람들을 만날 수 있습니다!


  Ignite에 등록하지 않았고 직접 참석할 수 없는 경우 <a href="https://ignite.microsoft.com/#fbid=MVRDJfn0SnH?WT.mc_id=IG15XCSOSC">5월 4일에 기조 연설을 시청</a> 하고 라이브 상태인 후 24시간 후에 주문형 세션에 액세스할 수 있습니다.


  Ignite에 대한 뉴스 및 업데이트를 계속 진행하려면 <a href="https://microsoft.eventcore.com/MicrosoftIgniteMailingList?WT.mc_id=IG15XCSOSC">여기를 구독하세요</a>.
