### YamlMime:Yaml
ms.openlocfilehash: a3ee96e47a0265d7d13bd3460f1221547219f8dc
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139899875"
Slug: build-distribute-and-deploy-application-updates-to-azure-virtual-machine-scale-sets
Title: Azure 가상 머신 확장 집합에 애플리케이션 업데이트 빌드, 배포 및 배포
Summary: 'Azure는 분산 클라우드 환경에서 애플리케이션 업데이트를 더 쉽게 빌드하고 배포할 수 있는 새로운 기능에 계속 투자하고 있습니다. '
Content: >-
  <p>비즈니스 요구 사항이 증가하고 클라우드 규모에서 중요 비즈니스용 애플리케이션을 배포하면 해당 애플리케이션을 관리하는 복잡성 및 관리 오버헤드가 크게 증가할 수 있습니다. 이러한 관리 오버헤드를 줄이기 위해 Azure는 분산 클라우드 환경에서 애플리케이션 업데이트를 더 쉽게 빌드하고 배포할 수 있는 새로운 기능에 계속 투자하고 있습니다.</p>


  <p>최근 사용자 지정 이미지에 대한 자동 이미지 기반 업그레이드의 <a href="https://azure.microsoft.com/updates/automatic-image-upgrade-for-custom-images-now-available-for-azure-vmss" target="_blank">일반 공급</a> 이 발표되어 새 버전의 VM(가상 머신) 이미지를 가상 머신 확장 집합에 자동으로 배포할 수 있습니다. <a href="https://docs.microsoft.com/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-automatic-upgrade" target="_blank">자동 이미지 업그레이드</a> 는 기본적으로 <a href="https://docs.microsoft.com/azure/virtual-machine-scale-sets/shared-image-galleries" target="_blank">공유 이미지 갤러리</a>와 통합되어 VM 이미지의 확장 가능한 배포와 오케스트레이션된 인프라 업데이트의 용이성 및 안전성을 결합하여 이미지 게시에서 워크로드 배포에 이르는 엔드투엔드 솔루션을 제공합니다.</p>


  <p>이 블로그에서는 통합 Azure 서비스를 사용하여 애플리케이션 업데이트로 사용자 지정 이미지를 빌드하고, 조직 전체에 해당 이미지를 배포하고, 새 이미지를 가상 머신 확장 집합에 자동으로 배포하는 방법을 설명합니다.</p>


  <p><img alt="Building and deploying application updates with custom images." border="0" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/806e3cf2-c447-44e8-99b6-ab0cfee38544.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="사용자 지정 이미지를 사용하여 애플리케이션 업데이트 빌드 및 배포"></p>


  <h2>애플리케이션 업데이트를 사용하여 이미지 빌드</h2>


  <p>조직 전체에서 애플리케이션 및 보안 업데이트를 배포하는 것은 종종 복잡한 프로세스일 수 있으며, 연결되지 않은 시스템 간에 여러 단계의 배포가 포함됩니다. 표준화된 VM 이미지를 통해 조직은 배포 전반에서 일관성을 유지할 수 있으며, 이러한 이미지에는 일반적으로 미리 정의된 보안 및 구성 설정과 소프트웨어 워크로드가 포함됩니다.</p>


  <p>사용자 고유의 이미징 파이프라인을 통해 표준화된 이미지를 빌드하거나 <a href="https://docs.microsoft.com/azure/virtual-machines/linux/image-builder-overview" target="_blank">Azure VM Image Builder 서비스를</a> 사용할 수 있습니다. Azure VM Image Builder(현재 미리 보기 상태)를 사용하면 자체 이미징 파이프라인을 설정하지 않고도 표준화된 이미지 빌드를 빠르게 시작할 수 있습니다. 이미지를 설명하는 간단한 구성을 제공하고 Image Builder 서비스에 제출하면 이미지가 빌드되고 배포됩니다.</p>


  <p>Azure VM Image Builder를 사용하면 기존 사용자 지정 이미지뿐만 아니라 <a href="https://docs.microsoft.com/azure/virtual-machines/windows/image-builder-gallery" target="_blank">Windows</a> 또는 <a href="https://docs.microsoft.com/azure/virtual-machines/linux/image-builder-gallery" target="_blank">Linux 기반</a> Azure Marketplace 이미지로 시작하고 사용자 지정을 추가할 수 있습니다.</p>


  <h2>이미지 배포</h2>


  <p><a href="https://docs.microsoft.com/azure/virtual-machine-scale-sets/shared-image-galleries" target="_blank">공유 이미지 갤러리</a> 를 사용하면 중앙 집중식 이미지 관리 플랫폼을 통해 여러 구독 및 지역에서 이미지 배포를 수행할 수 있습니다. 공유 이미지 갤러리를 사용하면 다양한 이미지 정의 및 이미지 버전을 지정하여 논리 그룹에서 이미지를 구성할 수 있으므로 다양한 애플리케이션에 대한 새 이미지 빌드를 반복할 수 있습니다.</p>


  <p>Image Builder를 사용하여 새 이미지 버전을 빌드할 때 조직의&rsquo; 요구 사항에 따라 여러 Azure 지역에 이미지를 복제하여 이러한 이미지를 전역적으로 배포할 수도 있습니다. 대상 지역만 지정하면 되며, 공유 이미지 갤러리는 선택한 지역에 이미지 버전을 <a href="https://docs.microsoft.com/azure/virtual-machine-scale-sets/shared-image-galleries#replication" target="_blank">복제</a> 합니다.</p>


  <p><img alt="Global replication of virtual machine images." border="0" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/53139aa6-f1a8-4955-976f-ca4f66743ed0.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="가상 머신 이미지의 전역 복제입니다."></p>


  <p>또한 공유 이미지 갤러리를 사용하면 Azure AD(구독 및 Azure Active Directory) 테넌트 간에 이미지를 공유할 수 있으므로 전체 조직에서 이미지 관리를 중앙 집중화할 수 있습니다.</p>


  <h2>이미지 배포</h2>


  <p>프로세스의 마지막 단계는 새로 만든 이미지를 가상 머신 확장 집합에 배포하는 것입니다. 확장 집합에 <a href="https://docs.microsoft.com/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-automatic-upgrade" target="_blank">대해 자동 OS 이미지 업그레이드</a> 를 사용하도록 설정하면 이미지를 배포하기 위해 추가 작업을 수행할 필요가 없습니다. 자동 OS 이미지 업그레이드는 이미지 갤러리를 모니터링하고 새 이미지 버전이 배포될 때 자동으로 확장 집합 업그레이드를 시작하여 수동 오버헤드 없이 더 빠른 이미지 배포를 지원합니다.</p>


  <p>업그레이드는 최신 이미지 버전을 사용하여 만든 새 디스크로 VM OS 디스크를 바꾸는 방식으로 작동합니다. 구성된 모든 확장 및 사용자 지정 스크립트는 OS 디스크에서 실행되고 데이터 디스크는 유지됩니다. 애플리케이션 가동 중지 시간을 최소화하기 위해 업그레이드는 언제든지 업그레이드되는 확장 집합의 20%를 초과하지 않고 일괄 처리로 수행됩니다. 업데이트 오케스트레이터는 업그레이드 프로세스 중에 업그레이드 중인 VM의 상태와 확장 집합의 상태를 모니터링합니다. 확장 집합 가상 머신의 20% 이상이 비정상 상태가 되면 확장 집합 업그레이드가 현재 일괄 처리의 끝에서 중지됩니다. 업그레이드 프로세스는 업그레이드 실패에 대한 자동 롤백도 지원합니다. 이렇게 하면 롤아웃이 점진적이고 안전한 방식으로 오케스트레이션되어 이미지의 사용자 지정으로 인한 확장 집합 전체 중단을 방지할 수 있습니다.</p>


  <p>확장 집합의 업그레이드는 새 이미지 버전이 확장 집합의 지역에 복제되는 경우에만 시작됩니다. 다른 시간에 다른 지역에 대한 이미징 복제를 스테이징하여 글로벌 배포를 엇갈릴 수 있으며, 글로벌 애플리케이션 작동 시간이 더욱 늘어날 수 있습니다.</p>


  <h2>시작</h2>


  <p>Azure Portal을 통해 공유 이미지 갤러리의 이미지 정의에서 시작하고 <strong>VMSS 만들기 옵션을 사용하여+</strong> 이미지에서 새 확장 집합을 만들 수 있습니다.</p>


  <p><img alt="Creating virtual machine scale set from Shared Image Gallery." border="0" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/a34701a5-7e11-46d3-b708-0ceeb0a2d1c8.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="공유 이미지 갤러리에서 가상 머신 확장 집합 만들기"></p>


  <p>가상 머신 확장 집합에 대한 만들기 환경의 <strong>관리</strong> 탭에서 <strong>자동 OS 업그레이드</strong>에 대한 <strong>켜기</strong> 옵션을 선택하기만 하면 됩니다.</p>


  <p><img alt="Enabling automatic OS upgrades on a virtual machine scale set." border="0" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/6747ea54-2c15-49a9-a7bd-aa64c9924178.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="가상 머신 확장 집합에서 자동 OS 업그레이드를 사용하도록 설정합니다."></p>


  <p>또한 프로세스를 추가로 사용자 지정하고 기존 이미지 빌드 파이프라인을 공유 이미지 갤러리와 통합하여 자동 OS 이미지 업그레이드의 이점을 누릴 수 있습니다.</p>


  <p>위에서 설명한 강력한 기능에 대해 자세히 알아보려면 Azure 설명서를 참조하세요.</p>


  <ul>
      <li><a href="https://docs.microsoft.com/azure/virtual-machine-scale-sets/virtual-machine-scale-sets-automatic-upgrade" target="_blank">자동 OS 이미지 업그레이드</a></li>
      <li><a href="https://docs.microsoft.com/azure/virtual-machine-scale-sets/shared-image-galleries" target="_blank">공유 이미지 갤러리</a></li>
      <li><a href="https://docs.microsoft.com/azure/virtual-machines/linux/image-builder-overview" target="_blank">Azure VM Image Builder</a></li>
  </ul>
