### YamlMime:Yaml
ms.openlocfilehash: 13ea72e4c609d57f33b88720332db657e9ba9ef0
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139908535"
Slug: build-resilient-applications-with-kubernetes-on-azure
Title: Azure에서 Kubernetes를 사용하여 복원력 있는 애플리케이션 빌드
Summary: 현재 Azure에서 Kubernetes로의 클라우드 네이티브 여정에 도움이 될 수 있는 더 많은 기능에 대해 알려드릴 수 있게 되어 기쁩니다.
Content: >-
  <p>가상 버전인 KubeCon EU 2020에 오신 것을 환영합니다. &rsquo;우리는 올해 KubeCon EU에서 직접 서로를 볼 수 없지만,&#39;우리는 KubeCon의 새로운 가상 형식이 놀라운 Kubernetes 커뮤니티의 더 많은 사람들이 집을 떠나지 않고 전 세계에서 참여하고 참여할 수있게되어 그 어느 때보 다 컨퍼런스에 더 쉽게 접근 할 수 있게되어 기쁩니다.</p>


  <p>모든 일이 일어나고 있는 가운데, 지난 해는 위아래로 진행된 경험이었지만, 이를 통해 모든 Im&rsquo;은 Azure Kubernetes 팀의 초점과 헌신을 매우 자랑스럽게 생각합니다. 고객들에게 엔터프라이즈급 환경을 제공하는 Azure의 Kubernetes를 계속 반복하고 개선하고 있습니다.</p>


  <p>Azure의 Kubernetes(그리고 실제로 어디서나)는 클라우드 네이티브 개발을 위한 개방적이고 이식 가능한 에코시스템을 제공합니다. 이 핵심 약속 외에도 워크로드가 요구하는 안정성과 보안을 보장하는 고유한 엔터프라이즈급 환경을 제공하는 동시에 오늘날 비즈니스에서 원하는 민첩성과 효율성을 지원합니다. 모든 워크로드를 AKS(Azure Kubernetes Service)에 안전하게 배포하여 비즈니스 전반에서 비용 절감을 촉진할 수 있습니다. 현재 Azure에서 Kubernetes로의 클라우드 네이티브 여정에 도움이 될 수 있는 더 많은 기능에 대해 알려줄&#39;있습니다.</p>


  <h2>대기 시간 및 운영 효율성 향상</h2>


  <p>클라우드 채택의 주요 동인 중 하나는 대기 시간을 줄이는 것입니다. 예전에는 물리적 컴퓨터를 가져와 클러스터에서 설정하는 데 며칠이 걸렸습니다. 현재는 5분 이내에 Azure에 Kubernetes 클러스터를 배포할 수 있습니다. 이러한 개선은 고객의 민첩성에 도움이 됩니다. 더 빠르게 크기를 조정하고 프로비전하려는 고객을 위해 클러스터의 새로운 컴퓨팅 요구에 더 빠르게 대응할 수 있는 임시 OS 디스크 지원 미리 보기를 발표합니다.</p>


  <p>대기 시간은&rsquo; 클러스터를 만드는 데 걸리는 시간에 불과합니다. &rsquo;또한 운영 문제를 감지하고 대응할 수 있는 속도에 대해서도 설명합니다. 기업이 운영 효율성을&rsquo; 개선할 수 있도록 어떤 이유로든 클러스터가 비정상 상태인 경우 경고할 수 있는 Azure Resource Health와의 미리 보기 통합을 발표합니다. &rsquo;또한 안정성을 위해 동일한 Kubernetes 버전을 유지하면서 클러스터의 버그 또는 취약성에 응답하도록 기본 운영 체제를 업그레이드할 수 있는 노드 이미지 업데이트의 일반 공급도 발표했습니다.</p>


  <p>마지막으로, Kubernetes는 항상 기업이 컨테이너화를 통해 비용 절감을 추진할 수 있도록 해 왔지만, 전염병 기간 동안 세계의 새로운 경제 현실은 비즈니스에 대한 비용 효율성을 달성하는 것이 그 어느 때보다 중요하다는 것을 의미합니다. Weve&rsquo;는 <a href="https://docs.microsoft.com/learn/modules/aks-optimize-compute-costs/" target="_blank">컨테이너 및 Azure Kubernetes Service를 사용하여 비용을 최적화</a>하는 방법을 배우는 데 도움이 되는 훌륭한 연습을 받았습니다.</p>


  <h2>Azure에서 Kubernetes를 사용하여 설계에 따라 보호</h2>


  <p>엔터프라이즈 컴퓨팅 플랫폼의 핵심 핵심 요소 중 하나는 보안입니다. Pod 및 클라우드 네이티브 보안에 대한 정책 통합 및 Azure Active Directory ID와&nbsp; 같은 시장을 선도하는 기능은 항상 Azure Kubernetes Service의 중요한 부분이었습니다. Kubernetes&rsquo;에서 실행되는 워크로드의 보안을 더욱 강화하기 위해 최근에 추가된 몇 가지 새로운 기능에&rsquo; 대해 기대합니다.</p>


  <p>Kubernetes는 비밀에 대한 기본 제공 지원을 제공하지만 대부분의 엔터프라이즈 환경에서는 보다 안전하고 규정을 준수하는 구현이 필요합니다. Azure Kubernetes Service에서 엔터프라이즈급이 된다는 것은 Azure Key Vault와 Azure Kubernetes 서비스 간의 통합을 제공하는 것을 의미합니다. Kubernetes와 함께 Key Vault를 사용하면 자격 증명, 인증서 및 기타 비밀을 최신 상태의 호환 비밀 저장소에 안전하게 저장하고 Azure Kubernetes 클러스터의 애플리케이션에서 쉽게 사용할 수 있습니다.</p>


  <p>&rsquo;이 통합은 Azure 팀이 전체 Kubernetes 커뮤니티에 대해 빌드하고 오픈 소스로 만든 openContainer&nbsp; Storage Interface&nbsp;(CSI) 드라이버의 뒷면에 구축되었다는 사실이 더욱 흥미로워집니다. 오픈 소스에 돌려주는 것은 커뮤니티 관리자가 된다는 것이 무엇을 의미하는지에 대한 중요한 부분이며, HashiCorp Vault 팀이 비밀 통합을 위해 선택하고 사용함에 따라 우리의 접근 방식이 검증되는 것을 보는 것은 흥미로웠습니다. 오픈 소스 팀은 보안 에코시스템의 다른 많은 부분을 개선하기 위해 열심히 노력해 왔습니다.&nbsp; Weve&rsquo;는 Windows&nbsp; 대한 CSI 드라이버를 향상시키고 cgroups v2 및 컨테이너화에서 작업했습니다. 클라우드 네이티브 워크로드를 보호하고 엔터프라이즈가 Microsofts&rsquo; 모범 사례를 따르고 있는지 확인하는 방법에 대해 자세히 알아보려면 <a href="https://docs.microsoft.com/en-us/azure/aks/best-practices" target="_blank">Kubernetes 모범 사례에 대한 가이드를 확인하세요</a>. 클라우드 네이티브 개발에서 보안과 민첩성을 모두 갖도록 방화벽, 정책 등을 통합하는 방법을 설명합니다.</p>


  <h2>다음 단계 및 KubeCon EU</h2>


  <p>나는 당신이 멋진 KubeCon EU를 가지고 있기를 바랍니다. 컨퍼런스를 진행하면서 Kubernetes에 대해 자세히 알아보면 온라인 및 가상 부스에서 모든 훌륭한 정보를 통해 Azure의 <a href="https://azure.microsoft.com/en-us/overview/kubernetes-on-azure/" target="_blank">Kubernetes에 대해 자세히 알아볼</a> 수 있습니다. &rsquo;KubeCon 및 Kubernetes를 처음으로 접하고 취미에서 엔터프라이즈&rsquo;에 이르는 워크로드를 위해 Kubernetes를 어떻게 채택할 수 있을지 궁금하다면 <a href="https://aka.ms/adopt/kubernetes" target="_blank">Kubernetes 채택 가이드</a>가 제공됩니다.</p>
