### YamlMime:Yaml
ms.openlocfilehash: ac4fed8fe4ecace71a6b57369799eaf51c9e2c1b
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139913066"
Slug: building-cloud-native-applications-with-azure-and-hashicorp
Title: Azure 및 HashiCorp를 사용하여 클라우드 네이티브 애플리케이션 빌드
Summary: >
  해가 지날수록 점점 더 많은 개발자가 클라우드 네이티브 애플리케이션을 빌드하고 있습니다. 개발자가 점점 더 복잡한 애플리케이션을 빌드함에 따라 이러한 애플리케이션을 빌드하고 운영하는 복잡성을 줄이기 위해 Azure 및 HashiCorp와 같은 혁신가를 찾고 있습니다. HashiCorp와 Azure는 수많은 혁신에 협력해 왔다.
Content: >-
  <p>해가 지날수록 점점 더 많은 개발자가 클라우드 네이티브 애플리케이션을 빌드하고 있습니다. 개발자는 더 복잡한 애플리케이션을 빌드함에 따라 이러한 애플리케이션을 빌드하고 운영하는 복잡성을 줄이기 위해 Microsoft Azure 및 HashiCorp와 같은 혁신가를 찾고 있습니다. HashiCorp와 Azure는 수많은 혁신에 협력해 왔다. 이러한 혁신의 예로는 클라우드 네이티브 애플리케이션을 레거시 인프라에 연결하는 도구와 고객 애플리케이션 및 인프라의 지속적인 배포를 보호하고 자동화하는 도구가 있습니다. Azure는 HashiCorp와 같은 오픈 소스 소프트웨어 개발자가 사용하기 쉽고 통합된 방식으로 고객에게 도구를 제공할 수 있는 최고의 플랫폼이 되기 위해 최선을 다하고 있습니다. Azure에서 HashiCorps&rsquo; Consul Service를 구동하는 관리되는 애플리케이션 플랫폼과 같은 Azure 혁신은 협업 및 활기찬 오픈 소스 시작 에코시스템에 대한 이러한 노력의 좋은 예입니다. Were&rsquo;는 또한 이러한 에코시스템이 발전하는 데 도움이 되는 개방형 표준 개발에 전념하고 있으며 CNAB(클라우드 네이티브 애플리케이션 번들) 및&rsquo; SMI(서비스 메시 인터페이스) 사양 모두에서 HashiCorp와 협업할 수 있게 되어 기쁩니다.</p>


  <p>작년에 HashiConf 2018에서 Terraform과 Packer를 Azure 플랫폼에 통합하기 시작한 방법을 공유할 기회가 있었습니다. Im&rsquo;은 올해 다시 돌아와 이러한 통합이 어떻게 진행되고 있는지 공유하고 클라우드 네이티브 네트워킹에서 새로운 협업을 공유할 수 있게 되어 매우 기쁩니다. 이 새로운 작업을 통해 이제 고객이 HashiCorp 기술을 사용하여 Azure에서 애플리케이션을 연결하고 운영하는 데 도움이 되는 협업이 있습니다.</p>


  <h2>&mdash; 커넥트 HashiCorp Consul Service on Azure</h2>


  <p>컨테이너 및 Kubernetes 이후 마이크로 서비스에서 가장 중요한 혁신 중 하나는 서비스 메시의 개념 개발이었습니다. 올해 초 우리는 HashiCorp 및 다른 사람들과 협력하여 <a href="https://smi-spec.io" target="_blank">서비스 메시</a> 기술의 구성 및 배포를 위한 협력적이고 구현에 구애받지 않은 API인 Service Mesh Interface의 릴리스를 <a href="https://cloudblogs.microsoft.com/opensource/2019/05/21/service-mesh-interface-smi-release/">발표</a>했습니다. Consul 커넥트 사용하여 TAC(트래픽 액세스 제어)의 제어 규칙 구현을 생성하기 위해 HashiCorp와 협업했습니다. &rsquo;오늘날 Azure 고객은 Azure Managed Applications 플랫폼으로 구동되는 <a href="https://www.hashicorp.com/blog/announcing-consul-service-on-azure" target="_blank">Azure의 HashiCorp Consul Services</a>를 활용할 수 있다는 사실에 매우 기쁘게 생각합니다. HashiCorp Consul은 서비스 네트워킹을 간소화하고 보호하는 솔루션을 제공하며, 이 새로운 관리형 제품으로 공동 고객은 HashiCorp의 전문가가 서비스 관리를 처리하고 있다고 확신하면서 Consul의 가치에 집중할 수 있습니다. 고객의 복잡성을 줄이고 클라우드 네이티브 혁신에 집중할 수 있도록 합니다.</p>


  <h2>Azure에서 HashiCorp Terraform 프로비전&nbsp;&mdash;</h2>


  <p>HashiCorp Terraform은 Azure에 선언적 배포를 수행하는 데 유용한 도구입니다. 연초 이후 고객 수가 두 배로 증가함에 따라 Azure에서 HashiCorp Terraform을 채택하면서 큰 모멘텀을 볼&#39;있습니다. 고객은 다양한 시나리오에서 Azure 인프라 배포 및 운영을 자동화하기 위해 Terraform을 사용하고 있습니다.&nbsp;</p>


  <p>이 모멘텀은 <a href="https://github.com/terraform-providers/terraform-provider-azurerm" target="_blank">Azure Resource Manager용 Terraform 공급자</a>에 대한 약 180명의 고유한 기여자와 함께 기여 전선에서 환상적입니다. 3주 간의 릴리스 주기 증가(현재 버전 1.32)와 함께 커뮤니티의 참여를 통해 Terraform에서 Azure 서비스를 더 많이 적용할 수 있습니다. 또한 Azure에 대한 추가 Terraform 모듈의 필요성에 대한 고객 및 커뮤니티 피드백 후에 고품질 모듈을 추가하기 위해 열심히 노력한&#39;이제 <a href="https://registry.terraform.io/browse/modules?provider=azurerm" target="_blank">terraform 레지스트리</a>의 Azure 모듈 수를 두 배로 늘려 120개가 넘는 모듈로 가져왔습니다.&nbsp;</p>


  <p>이러한 모든 추가 통합을 통해 고객은 코드로 인프라를 보다 쉽게 관리하고 클라우드 환경 관리를 간소화할 수 있습니다. <a href="https://azure.microsoft.com/en-us/solutions/devops/terraform/" target="_blank">Azure의 Terraform에</a> 대해 자세히 알아봅니다.</p>


  <p>Microsoft와 HashiCorp는 Azure에서 Terraform에 대한 통합 지원을 제공하기 위해 협력하고 있습니다. Microsoft&#39;Azure 클라우드에서 Terraform을 사용하는 고객은 상호 고객이며 두 회사 모두 통합되어 문제 해결 및 지원 서비스를 제공합니다. 이 공동 자격 프로세스는 원활한 고객 환경을 제공하면서 회사 및 플랫폼 간에 공동 지원을 제공합니다. Azure용 Terraform Provider를 사용하는 고객은 Microsoft 지원에 지원 티켓을 제출할 수 있습니다. Azure 지원에서 Terraform을 사용하는 고객은 Microsoft 또는 HashiCorp에 지원 티켓을 제출할 수 있습니다.</p>


  <h2>클라우드 네이티브 애플리케이션 번들에 공동 작업 배포&nbsp;&mdash; 사양</h2>


  <p>컨테이너에서 해결하는 중요한 문제 중 하나는 이진 파일을 전 세계에 공유하고 배포하기 쉬운 패키지로 밀폐된 패키징입니다. 그러나 클라우드 네이티브 애플리케이션은 이진 애플리케이션 이상이며, 이는 HashiCorp 및 기타와 함께 CNAB(Coud Native Application Bundle) 사양의 공동 개발로 이어졌습니다. CNAB&nbsp; 를 사용하면 Terraform 및 기타 아티팩트와 같은 구성 도구와 함께 이미지를 패키지하여 사용자가 단일 패키지에서 애플리케이션을 원활하게 배포할 수 있습니다. 커뮤니티&rsquo;가 함께 작동하여 CNAB가 모든 배포&rsquo; 요구 사항에 대비하고 있음을 보여 주는 <a href="https://cloudblogs.microsoft.com/opensource/2019/09/10/cloud-native-application-bundle-cnab-1-0-updates" target="_blank">1.0 릴리스</a>에 대한 사양을 빌드하는 것을 보게 되어 기쁩니다. 작업과 환상적인 파트너십에 대한 팀에 축하드립니다.</p>


  <p>클라우드 네이티브 개발을 더 쉽게 만들기 위해 Azure 및 HashiCorp가 공동 작업하는 방법에 대해 자세히 알아보려면 아래 링크를 확인하세요.</p>


  <ul>
      <li>Azure의 HashiCorp Consul Service 제품에 대한 <a href="https://www.hashicorp.com/blog/announcing-consul-service-on-azure" target="_blank">HashiCorp 공지</a></li>
      <li><a href="https://azure.microsoft.com/en-us/solutions/devops/terraform/" target="_blank">Azure의 Terraform</a></li>
      <li><a href="https://aka.ms/cnab2jdf" target="_blank">CNAB(클라우드 네이티브 애플리케이션 번들)</a></li>
  </ul>
