### YamlMime:Yaml
ms.openlocfilehash: 6e69aa01c0884adde4de4683e528773c11c5704c
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139911076"
Slug: compute-and-stream-iot-insights-with-data-driven-applications
Title: 데이터 기반 애플리케이션을 사용하여 IoT 인사이트 컴퓨팅 및 스트리밍
Summary: 세계에서 가장 강력한 최첨단 기술로 캡처할 수 있는 것보다 훨씬 더 많은 데이터가 있습니다. 에지 컴퓨팅과 IoT(사물 인터넷)는 유용한 데이터의 양을 늘리는 기술의 두 가지 예에 불과합니다.
Content: >-
  <p>세계에서 가장 강력한 최첨단 기술로 캡처할 수 있는 것보다 훨씬 더 많은 데이터가 있습니다. 에지 컴퓨팅과 IoT(사물 인터넷)는 유용한 데이터의 양을 늘리는 기술의 두 가지 예에 불과합니다. 현재 통신 인프라가 전송하는 데 어려움을 겪을 정도로 많은 데이터가 생성되고 있으며 클라우드조차도 저장에 부담을 줄 수 있습니다. 통신에서 5G의 출현과 클라우드 스토리지의 급속한 성장에도 불구하고 데이터 증가는 두 인프라의 용량을 계속 능가할 것입니다. 한 가지 솔루션은 SWIM의 기술을 사용하여 상태 저장 데이터 기반 애플리케이션을 빌드하는 것입니다 <a href="https://www.swim.ai/" target="_blank">. AI</a>.</p>


  <p>Azure 플랫폼은 파트너가 업계 솔루션을 향상, 확장 및 빌드할 수 있는 풍부한 서비스를 제공합니다. 여기서는 한 Microsoft 파트너가 Azure를 사용하여 고유한 문제를 해결하는 방법을 설명합니다.</p>


  <h2>공유 인식 및 통신</h2>


  <p>볼륨의 증가는 특히 IoT 디바이스가 서로를 인식하고 공유 정보를 통신해야 하는 경우 다른 결과를 초래합니다. IoT 자산 간의 P2P(피어 투 피어) 통신은 네트워크를 압도하고 성능을 저하시킬 수 있습니다. 스마트 그리드는 센서 또는 전기 미터가 배포 그리드를 통해 네트워크로 연결되어 전기 전달의 전반적인 안정성과 비용을 개선하는 방법의 예입니다. 미터를 사용하여 문제의 지역을 확인하면 거주지, 이웃, 지방 자치 단체, 부문 또는 지역에 대한 서비스를 개선하는 데 도움이 될 수 있습니다. 공유 인식의 개념은 V2V(차량 간) 및 V2I(차량 간) 통신으로 확장됩니다. 네트워크로 연결된 AI가 더 많은 자동차 및 디바이스로 확산됨에 따라 다른 자산의 성능 또는 상태를 알면 이점이 있습니다. 기타 사용 사례는 다음과 같습니다.</p>


  <ul>
   <li>이웃을 가로 질러 차량의 흐름에 반응 신호등.</li>
   <li>이전 프로세스 단계의 영향을 확인할 수 있는 공정 제조 장비입니다.</li>
   <li>다운스트림 석유/가스 센서 유효성 검사에 반응하는 업스트림 석유/가스 장비 성능입니다.</li>
  </ul>


  <h2>문제: 초과 데이터는 데이터 손실을 의미합니다.</h2>


  <p>많은 양의 데이터를 처리할 때 기업은 보존할 데이터, 보존할 양 및 보존 기간을 결정하는 데 어려움을 겪는 경우가 많습니다. 기본적으로, 그들은 그것의 어떤을 유지 하지 않을 수 있습니다. 또는 데이터를 하위 샘플링하고 불완전한 데이터 집합을 유지할 수 있습니다. 손실된 데이터에는 잠재적으로 높은 가치의 인사이트를 포함할 수 있습니다. 예를 들어 효율적인 차량 라우팅, 통근 안전, 보험 분석 및 정부 인프라 검토에 사용할 수 있는 교통 정보를 고려합니다. 라스베이거스시는 매일 45TB 이상의 데이터를 생성할 수 있는 1,100개 이상의 신호등 교차로를 유지 관리합니다. 앞에서 설명한 것처럼 IoT 데이터는 이러한 볼륨에서 데이터를 전송하고 저장하는 기능에 도전합니다.</p>


  <p>데이터가 집계될 때&rsquo;도 과도해질 수 있습니다. 예를 들어 통신 및 네트워크 장비는 일반적으로 데이터의 스냅샷을 만들고 15분마다 보냅니다. 시간이 지남에 따라 이 데이터를 요약으로 정규화하면 세분성이 손실됩니다. 즉, 고유하고 직관적인 이벤트와 함께 시간에 따른 데이터의 특성 또는 패턴이 누락됩니다. 고정 시간 창 요약 데이터를 캡처하는 모든 장비에도 동일하게 적용됩니다. 데이터 손실은 디바이스가 인식 또는 통신을 위해 데이터를 공유하는 네트워크에 해롭습니다. 수천 또는 수백만 개의 디바이스로 구성된 전체 네트워크에 대해 스냅샷만 캡처되고 집계되기 때문에 이 문제는 더욱 복잡해졌습니다. 실시간이 목표입니다.</p>


  <h2>실시간이 목표입니다.</h2>


  <p>거의 실시간으로 상태 비주거 애플리케이션 아키텍처에 대한 현재 표준이지만 &ldquo;거의&rdquo; 실시간으로 더 이상 충분히 빠르지 않습니다. 실시간 처리 또는 처리는 V2V 또는 V2I 통신의 새로운 표준이며 훨씬 더 성능이 좋은 아키텍처가 필요합니다. 수영은 상태 저장 API&rsquo;를 활용하여 이 작업을 수행합니다. 상태 저장 연결을 사용하면&rsquo; 네트워크의 피어 간에 신속하게 응답할 수 있습니다. 속도는 효율성과 안정성에 엄청난 영향을 미치며 충돌 방지와&rsquo; 같이 안전이 가장 중요한 시스템에 필수적입니다. 자율 시스템은 안전을 위해 실시간 성능에 의존합니다.</p>


  <h2>지능형 에지 데이터 전략</h2>


  <p>수영. AI는 확장 가능한 스트리밍 애플리케이션을 빌드하기 위한 솔루션을 제공합니다. 그들의 사이트에 따르면 <a href="https://www.swim.ai/opensource/" target="_blank">수영 을 충족</a> :</p>


  <p><em>&ldquo;별도의 메시지 브로커, 앱 서버 및 데이터베이스를 구성하는 대신, Swim은 고유한 지속성, 메시징, 일정 예약, 클러스터링, 복제, 내성 및 보안을 제공합니다. 모든 것이 통합되기 때문에 스윔은 기존 클라우드 애플리케이션 아키텍처의 인프라 및 개발 비용의 일부에 대해 에지, 클라우드 및 클라이언트 간에 원활하게 확장됩니다.&rdquo;</em></p>


  <p>아래 그림에서는 스윔이 IoT 아키텍처를 간소화하는 방법에 대한 추상적인 보기를 보여 줍니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/4a7702c1-0bba-492e-918b-c7d029862e01.png"><img alt="Diagram display of how Swim can simplify architectures" border="0" height="697" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/fb010b18-6d5d-41e6-8b34-6b7921ae03f5.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="수영이 아키텍처를 간소화하는 방법의 다이어그램 표시" width="1118"></a></p>


  <h2>중간 스트림에서 데이터 수집</h2>


  <p>수영. AI는 경량 <a href="https://www.swim.ai/opensource/" target="_blank">수영</a> 플랫폼을 사용하여 2MB의 공간만 생성하여 IoT 인사이트를 계산하고 스트리밍하며 데이터 기반 애플리케이션을 빌드 &ldquo;합니다.&rdquo; 이러한 애플리케이션은 데이터 스트림에 배치되고 표시되는 각 데이터 원본에 대해 고유한 지능형 웹 에이전트를 생성합니다. 그런 다음 이러한 지능형 웹 에이전트는 원시 데이터를 스트림할 때 처리하고 데이터 스트림에서 상태 변경 내용만 게시합니다. 이 스트리밍된 데이터는 다른 웹 에이전트에서 사용하거나 Azure와 같은 데이터 레이크에 저장할 수 있습니다.</p>


  <p>수영은 &ldquo;건초 더미&rdquo; 은유에 바늘을 사용하여이 독특한 이점을 설명합니다. 수영은 바늘을 검색하기 전에 보석, 수송 또는 곡물을 저장하지 않고, 바늘을 찾기 위해 곡물을 수확하는 동안 금속 탐지기를 적용 할 수 있습니다. 이점은 지능형 웹 에이전트가 시간이 지남에 따라 학습하거나 임계값을 설정하는 도메인 전문가의 영향을 받을 수 있는 데이터를 지속적으로 처리하는 것입니다.</p>


  <p>스윔의 상태 저장 아키텍처로 인해 필요한 최소 데이터만 네트워크를 통해 전송됩니다. 또한 애플리케이션 서비스는 클라우드가 애플리케이션 컨텍스트를 설정할 때까지 기다릴 필요가 없습니다. 이로 인해 상태 저장 연결에 따라 데이터베이스를 읽고 쓰거나 설문 조사 요청에 따라 업데이트하는 대기 시간이 발생하지 않기&rsquo; 때문에 대기 시간이 매우 짧아질 수 있습니다.</p>


  <p>수영에. <a href="https://www.swim.ai/showcase/traffic/" target="_blank">스마트 시티 애플리케이션</a>인 AIs&rsquo; 웹 사이트는 수천 개의 센서가 있는 100개의 교차로에서 조명 및 트래픽의 실시간 상태를 보여줍니다. 앱을 사용하는 클라이언트는 교차로에 접근하는 연결된 또는 자율 주행 자동차일 수 있습니다. 교차로 옆에 있는 핸드헬드 장치이거나 인접한 미국에서 천 마일 떨어진 브라우저일 수 있습니다. 실시간 대기 시간은 인터넷을 통해 눈 깜박임보다 적은 75-150ms입니다.</p>


  <h2>이점</h2>


  <ul>
   <li>즉각적인 이점은 데이터 전송 및 저장 비용을 절감하는 것입니다.</li>
   <li>수영&rsquo; 기술을 통해 세분성을 유지할 수 있습니다. 예를 들어 1,000개의 신호등 교차로마다 생성된 하루 10초의 TB를 사용합니다. 하루에 100초의 GB까지 데이터를 표시하는 Winnow입니다. 그러나 수집된 데이터 세트는 원래 원시 데이터 세트를 완전히 설명합니다.</li>
   <li>다양한 데이터 원본에 대한 효율적인 네트워크 앱을 만듭니다. 예를 들어 인터넷을 통해 차량, 디바이스, 센서 및 기타 데이터 원본과 같은 자산 간의 피어 투 피어 인식 및 통신을 달성합니다.</li>
   <li>75-150밀리초 범위에서 매우 낮은 대기 시간을 달성합니다. 이는 인식 및 통신을 위해 데이터에 의존하는 앱을 만드는 데 핵심적인 요소입니다.</li>
  </ul>


  <h2>솔루션에 사용된 Azure 서비스</h2>


  <p>SWIM의 DataFabric 데모입니다. AI는 보안, 프로비전, 관리 및 스토리지에 핵심 Azure 서비스를 사용합니다. 또한 DataFabric은 <a href="https://docs.microsoft.com/common-data-model/?WT.mc_id=ptx-azblog-ditambur" target="_blank">Common Data Model</a>을 사용하여 Azure에서 <a href="https://powerbi.microsoft.com/?WT.mc_id=ptx-azblog-ditambur" target="_blank">Power BI</a> 또는 <a href="https://powerapps.microsoft.com/?WT.mc_id=ptx-azblog-ditambur" target="_blank">PowerApps</a>와 같은 다른 시스템과의 정보 공유를 간소화합니다. Azure 기술을 사용하면 고객&rsquo; 분석을 이벤트 및 네이티브 ML 및 Cognitive Services와 통합할 수 있습니다.</p>


  <p>DataFabric은 <a href="https://aka.ms/iotrefarchitecture" target="_blank">Microsoft IoT 참조 아키텍처</a> 를 기반으로 하며 다음과 같은 핵심 구성 요소를 사용합니다.</p>


  <ul>
   <li><a href="https://azure.microsoft.com/services/iot-hub/?WT.mc_id=ptx-azblog-ditambur" target="_blank">IoT Hub</a>: 디바이스 및 해당 데이터를 관리하는 클라우드의 중심점을 제공합니다.</li>
   <li><a href="https://azure.microsoft.com/services/iot-edge/?WT.mc_id=ptx-azblog-ditambur" target="_blank">IoT Edge 필드 게이트웨이</a>: 클라우드 인텔리전스를 제공하기 위한 온-프레미스 솔루션입니다.</li>
   <li><a href="https://azure.microsoft.com/services/event-hubs/?WT.mc_id=ptx-azblog-ditambur" target="_blank">Azure Event Hubs</a>: 초당 수백만 개의 이벤트를 수집합니다.</li>
   <li><a href="https://azure.microsoft.com/services/storage/blobs/?WT.mc_id=ptx-azblog-ditambur" target="_blank">Azure Blob</a>: 핫, 웜 및 보관된 데이터에 대한 옵션을 포함하는 효율적인 스토리지입니다.</li>
   <li><a href="https://azure.microsoft.com/services/storage/data-lake-storage/?WT.mc_id=ptx-azblog-ditambur" target="_blank">Azure Data Lake Storage</a>: 빅 데이터 분석을 위한 확장성이 뛰어나고 비용 효율적인 데이터 레이크 솔루션입니다.</li>
   <li><a href="https://azure.microsoft.com/services/stream-analytics/?WT.mc_id=ptx-azblog-ditambur" target="_blank">Azure Streaming Analytics</a>: 데이터를 실행 가능한 인사이트 및 예측으로 거의 실시간으로 변환하기 위한 것입니다.</li>
  </ul>


  <h2>다음 단계</h2>


  <p>다른 산업 솔루션에 대해 자세히 알아보려면 <a href="https://azure.microsoft.com/industries/discrete-manufacturing/?WT.mc_id=ptx-azblog-ditambur" target="_blank">Azure for Manufacturing</a> 페이지로 이동하세요.</p>


  <p>이 솔루션에 대해 자세히 알아보려면 <a href="https://azuremarketplace.microsoft.com/en-us/marketplace/apps/swim-ai.swim-ai?tab=Overview" target="_blank">Azure IoT DataFabric</a>으로 이동하여 <strong>지금 가져오기를</strong> 선택합니다.</p>
