### YamlMime:Yaml
ms.openlocfilehash: 19e401fd4dfa15d18b9ab9f9d171002e09c9c62c
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139901729"
Slug: configuring-barracuda-web-application-firewall-for-azure-app-service-environment
Title: Azure App Service Environment에 대한 웹 애플리케이션 방화벽 구성
Summary: App Service Environment에 대한 Barracuda 웹 애플리케이션 방화벽 구성
Content: <a href="https://azure.microsoft.com/en-us/documentation/articles/app-service-app-service-environment-intro/">Azure App Service Environment는</a> 고객에게 애플리케이션에 대한 더 큰 격리 및 크기 조정 특성을 가진 환경을 제공합니다. App Service Environment의 보안을 개선하기 위해 이 환경에 <a href="https://azure.microsoft.com/documentation/articles/app-service-app-service-environment-web-application-firewall">대한 Barracuda WAF(웹 애플리케이션 방화벽)를 구성</a>하여 SQL 삽입, 사이트 간 스크립팅 및 기타 공격으로부터 애플리케이션을 보호하는 방법에 대한 설명서를 발표했습니다. <a href="https://www.barracuda.com/programs/azure">해당 웹 사이트에서</a> Barracuda WAF에 대해 자세히 알아보고 <a href="https://azure.microsoft.com/marketplace/partners/barracudanetworks/waf-byol/">Azure Marketplace</a>를 통해 구성할 수 있습니다.
