### YamlMime:Yaml
ms.openlocfilehash: d078d185523758f2a6678f9c5360dd894e9b14d0
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139911978"
Slug: connect-your-applications-to-azure-with-open-service-broker-for-azure
Title: Azure용 Open Service Broker를 사용하여 애플리케이션을 Azure에 커넥트
Summary: 오늘 Azure 서비스용 Open Service Broker API 구현인 OSBA(Open Service Broker for Azure)의 미리 보기를 발표하게 되어 기쁩니다. 다중 클라우드, 다중 플랫폼 세계에서,...
Content: >-
  <p>Im&rsquo;은 오늘 <a href="https://github.com/azure/open-service-broker-azure" target="_blank">Azure 서비스용 Open Service Broker API 구현인 OSBA(Open Service Broker for Azure)</a>의 <a href="https://openservicebrokerapi.org/" target="_blank"></a> 미리 보기를 발표하게 되어 기쁩니다. 다중 클라우드 다중 플랫폼 환경에서 개발자는 마켓플레이스에서 사용할 수 있는 다양한 서비스에 애플리케이션을 연결하는 표준 방법을 원합니다. Open Service Broker API는 이러한 수요를 간단하고 안전하게 충족하기 위한 업계 전반의 노력입니다. OSBA는 Azure Database for MySQL과 같은 표준 제품부터 전역적으로 분산된 다중 모델 데이터베이스인 Azure Cosmos DB와 같은 고유한 Azure 솔루션에 이르기까지 애플리케이션을 가장 인기 있는 Azure 서비스 제품군에 연결하는 가장 간단하고 유연한 방법입니다. 현재 11개의 Azure 서비스를 제공하며 내년에 대부분의 다른 서비스를 지원할 예정입니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/211b4faa-63d1-4c67-8546-20e106cb277f.png"><img alt="Open Service Broker for Azure" border="0" height="716" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/8ad03f4d-1b1a-44ed-92d8-04cb78228d51.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="Azure용 Service Broker 열기" width="1430"></a></p>


  <p align="center"><em>Azure용 Open Service Broker 및 서비스 카탈로그 CLI를 사용하면 Kubernetes 애플리케이션을 Azure 서비스에 쉽게 연결할 수 있습니다.</em></p>


  <p>&nbsp;</p>


  <p><iframe allowfullscreen="" frameborder="0" height="540" src="https://channel9.msdn.com/Shows/Azure-Friday/Open-Service-Broker-for-Azure/player" width="960"></iframe></p>


  <p>Azure용 Open Service Broker는 모든 환경에서 실행되는 OSB 호환 플랫폼에 배포할 수 있습니다. &rsquo;Azure, Azure Stack에서 Kubernetes, Cloud Foundry 또는 OpenShift를 사용하든, 사용자 고유의 온-프레미스 환경(또는 다른 곳)을 사용하든 간에 Azure에서 제공하는 모든 훌륭한 서비스를 활용할 수 있습니다. Microsoft는 2016년 Cloud Foundry에 대한 서비스 브로커 투자로 거슬러 올라가는 이 공간에서 혁신에 대한 오랜 실적을 보유하고 있으며, 이를 <a href="https://github.com/azure/meta-azure-service-broker" target="_blank">공개적으로 수행</a>했습니다. OSBA는 이 작업을 기반으로 하며 Open Service Broker API에 대한 당사의 약속을 보여주면서 새로운 플랫폼 및 서비스로 확장합니다. 오늘&rsquo; 발표로 인해 OSBA를 위해 meta-azure-service-broker 프로젝트를 대체하고 원활한 마이그레이션을 보장하기 위해 Cloud Foundry 고객과 긴밀히 협력할 예정입니다.</p>


  <p>Kubernetes에 대한 광범위한 투자의 일환으로 Microsoft는 서비스 카탈로그에 적극적으로 기여해 왔으며, 이를 통해 Kubernetes 운영자는 Azure와 같은 플랫폼에서 제공하는 클라우드 네이티브 서비스를 활용할 수 있습니다. 오늘 <a href="https://github.com/Azure/service-catalog-cli" target="_blank">Kubernetes 서비스 카탈로그에 대한 CLI의 알파 릴리스</a>도 발표됩니다.</p>


  <p>이 도구를 사용하면 브로커, 서비스 인스턴스 및 서비스 바인딩과 같은 잘 정의된 서비스 카탈로그 개체와의 상호 작용을 허용하므로 서비스 카탈로그와의 상호 작용이 훨씬 간단합니다. 서비스 카탈로그 CLI는 배포되는 위치에 관계없이 서비스 카탈로그와 함께 작동하며, Kubernetes 커뮤니티의 나머지 부분과 협업할 수 있기를 기대합니다.</p>


  <p>아래 데모에서는 OSBA를 사용하여 지원되는 일부 환경에 대해 Azure Services를 프로비전하고 바인딩하는 것이 얼마나 쉬운지를 보여 줍니다. Kubernetes의 경우 여기에는 Helm 패키지 관리자와의 자연스러운 통합 및 새 서비스 카탈로그 CLI의 사용이 포함됩니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/3a1e4982-f01b-4369-9f84-6716348dc023.gif"><img alt="OSBdemovideo-Fdraft3" border="0" height="810" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/17b8701e-5f5f-4a63-acc5-f433985c3b1a.gif" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="OSBdemovideo-Fdraft3" width="1296"></a></p>


  <p>현재 OSBA를 사용하여 Azure 기반 애플리케이션 빌드를 시작할 수 있습니다. <a href="https://github.com/Azure/helm-charts/tree/master/open-service-broker-azure" target="_blank">Kubernetes</a> 및 <a href="https://github.com/Azure/open-service-broker-azure/blob/master/contrib/cf/README.md" target="_blank">Cloud Foundry</a>에 배포하기 위한 지침이 있으며 OpenShift 및 Azure Service Fabric 곧 제공될 예정입니다. Kubernetes를 대상으로 하는 경우 OSBA에서 프로비전된 Azure 서비스를 사용하도록 향상된 WordPress 및 Concourse와 같은 인기 있는 Helm 차트의 예를 볼 수 있는 <a href="https://github.com/Azure/helm-charts/" target="_blank">Helm 차트</a> 를 확인해야 합니다.</p>


  <p>감사합니다, 그리고 우리는&rsquo; GitHub 당신을 볼 수 있습니다!</p>


  <p>숀</p>
