### YamlMime:Yaml
ms.openlocfilehash: d2e17720da832dc9b6d29b982302f3432be13091
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139907227"
Slug: creating-cloud-ready-environments-with-azure-landing-zones
Title: Azure 랜딩 존을 사용하여 클라우드 준비 환경 만들기
Summary: Azure용 Microsoft 클라우드 채택 프레임워크의 Azure 랜딩 존은 운영 모델을 매핑, 현대화 또는 재구상하기 위한 노력을 가속화하도록 설계되었습니다. Azure 랜딩 존은 클라우드의 요구 사항에 맞는 최적의 기술 작업에 맞춰 클라우드 환경을 구축하는 데 도움이 됩니다.
Content: >-
  <p>클라우드로 이동하면 일시 중지하고 IT 환경을 운영하는 방법을 생각할 수 있습니다. 전 세계 대부분의 조직에서는 기존 IT 환경을 제어하는 규칙 및 운영 모델에 따라 클라우드 기술을 혁신하고 채택하는 기능이 느려지는 것을 보았습니다. 조직에는 이러한 환경이 비즈니스 요구를 지속적으로 지원할 수 있도록 고유한 프로세스, 도구 및 전담 직원이 있습니다.</p>


  <p>클라우드 환경으로 전환하면 IT 운영의 차단을 해제하는 새로운 도구 및 프로세스에 대한 액세스 권한이 IT에서 제공됩니다. 운영 모델을 다시 검토하면 기술 중심 팀과 Azure 파트너가 조직이 민첩성, 비용 및 규모를 개선하는 데 도움이 될 수 있습니다.</p>


  <p><a href="https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/" target="_blank">Azure용 Microsoft 클라우드 채택 프레임워크</a>의 <a href="https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/migrate-landing-zone" target="_blank">Azure 랜딩 존</a>은 운영 모델을 매핑, 현대화 또는 재구상하기 위한 노력을 가속화하도록 설계되었습니다. Azure 랜딩 존은 클라우드의 요구 사항에 맞는 최적의 기술 작업에 맞춰 클라우드 환경을 구축하는 데 도움이 됩니다.</p>


  <p>다음 비유에서 알 수 있듯이 표준화된 기초는 조직 및 운영 모델에서 볼 수 있는 다양한 요구 사항에 맞지 않습니다&rsquo;. 옵션 및 사용자 지정에 대한 요구 사항을 존중하여 다양한 랜딩 존 아키텍처 및 구현 옵션을 제공합니다. 조직은 현재 클라우드 전략에 가장 명확하게 부합하는 구현 옵션을 사용할 수 있습니다. 클라우드 플랫폼을 관리, 운영 및 관리하는 접근 방식이 성숙해짐에 따라 고객을 지원하고 Azure 랜딩 존 구현을 리팩터링하여 운영 모델의 변경 내용을 반영할 수 있습니다.</p>


  <h2>랜딩 존 비유</h2>


  <p>클라우드 환경은 모든 건설 프로젝트의 토대를 마련하는 것과 비슷합니다. 모든 설계자는 모든 건물의 기초를 설계하고 배치할 때 일반적인 결정을 고려해야 합니다. 그들은 모두 배관이나 전기와 같은 필요한 유틸리티를 가져오기 위해 콘크리트, 철근 및 도관과 같은 것들을 공유합니다. 기초에는 유사한 요소와 고려 사항이 포함되어 있지만 고유하고 격렬하게 다른 다른 고려 사항이 있을 수 있습니다. 집의 기초는 간결하고 잘 포함되어 있습니다. 경기장의 기초는 더 크고 더 복잡합니다. 브리지의 기초는 훨씬 더 복잡하며 더 엄격한 거버넌스 및 성능 표준이 필요할 수 있습니다. 올바른 기초를 설계하려면 해당 재단이 지원할 내용을 이해해야 합니다.</p>


  <p>Azure 랜딩 존에서 만든 클라우드 환경은 모두 동일한 공통 디자인 요소에서 빌드된 것과 매우 유사합니다. 공통점은 모든 환경에 존재하지만 각 랜딩 존 구현은 특정 유형의 구조 또는 클라우드 운영 모델을 지원하도록 사용자 지정됩니다. 기존의 기초와 마찬가지로 클라우드 환경은 조직의&rsquo; 장기적인 요구를 지원하기 위해 숙련된 설계자의 검토, 수정 및 반복이 필요합니다.</p>


  <p>작업을 시작하거나 재고할 때 Azure 랜딩 존은 클라우드 환경의 설계, 검토 및 구현을 가속화하는 데 도움이 됩니다. 고객과 협력하여 여정을 가속화할 때 Azure 랜딩 존은 Azure 랜딩 존의 유효성을 검사하고, 사용자 지정하고, 확장하여 디지털 변환을 위한 토대를 구축할 때 협업을 안내할 수 있습니다.</p>


  <h2>Azure 랜딩 존</h2>


  <p>Azure 랜딩 존은 초기 클라우드 환경을 만들기 위한 명확한 아키텍처, 참조 구현 및 코드 샘플을 제공합니다. 이 환경은 <a href="https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/design-areas" target="_blank">공통 디자인 영역</a> 집합을 일관되게 적용하여 다른 모든 채택 작업을 지원합니다. 이러한 디자인 영역은 운영 모델이 클라우드에서 지원되는 방식을 나타냅니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/11168e94-35aa-4db0-a35d-c36589720c40.png"><img alt="Design areas of a well-architected landing zone." border="0" height="423" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/9d315b5b-2839-47e1-a647-958e6137eead.png" style="border: 0px currentcolor; border-image: none; display: inline; background-image: none;" title="잘 설계된 랜딩 존의 디자인 영역." width="1024"></a></p>


  <p>Azure 랜딩 존 구현 옵션은 환경에 영향을 주는 네트워킹, ID, 리소스 조직, 거버넌스, 운영 및 기타 디자인 영역에 대한 결정을 내리는 데 도움이 되는 참조 구현 또는 접근 방식을 제공합니다. 이 옵션은 조직이 따를 수 있는 구조를 제공하여 최소한의 디자인 고려 사항을 모두 수행하고 클라우드 환경에서 의사 결정이 일관되게 반영되도록 합니다.</p>


  <h2>Azure 랜딩 존 구현 옵션</h2>


  <p>Azure 랜딩 존은 오늘날의&rsquo; 요구 사항에 따라 고객의 고유한 요구 사항을 충족한 다음, 맞춤형 랜딩 존 구현을 사용자 지정하고 완성할 수 있는 명확한 경로를 제공하도록 설계되었습니다. 이는 클라우드 환경에 대한 시작점을 신속하게 배포하는 <a href="https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/implementation-options" target="_blank">랜딩 존 구현 옵션을</a> 선택하는 것으로 시작됩니다.</p>


  <p>일부 Azure 랜딩 존은 기술 개발 및 사용자 지정을 장려하기 위해 디자인상 작습니다. &ldquo;시작 작은&rdquo; 구현 옵션은 코드로서의 인프라 접근 방식을 설정한 다음 IT 팀에 일련의 의사 결정 가이드를 제공합니다. 이 방법은 수행해야 하는 생각과 결정을 안내하는 데 도움이 됩니다. 이 반복적인 접근 방식은 클라우드 환경이 성숙함에 따라 팀이 구체적인 결정을 내릴 수 있도록 클라우드 채택 계획과 병행하여 기반을 구축합니다.</p>


  <p>잘 정의된 운영 모델을 &ldquo;사용하는 조직의 경우 엔터프라이즈 규모&rdquo; 구현 옵션이 이러한 결정을 채웁니다. 이 옵션에는 보안, 거버넌스 및 운영에 대한 매우 자세한 솔루션이 포함됩니다. 이러한 솔루션은 Azure Policy 및 참조 구현의 다른 거버넌스 도구에 의해 자동화되고 적용됩니다. 엔터프라이즈 규모로 시작하는 경우 조직은 의사 결정 지점 수를 줄이고 검증된 클라우드 운영 모델을 더 빠르게 구현할 수 있습니다.</p>


  <h2>Azure 랜딩 존 개발</h2>


  <p>선택한 랜딩 존에 관계없이 <a href="https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/" target="_blank">Azure용 CAF(클라우드 채택 프레임워크)의 준비 방법론은</a> 조직을 안내하는 동시에 클라우드 환경을 만들고 지원하는 데 필요한 기술을 개발하는 데 도움이 됩니다. Azure 랜딩 존의 이론은 인프라 관리 기능에 잘 확립된 개발 사례를 제공합니다.</p>


  <p>Azure 랜딩 존이 구현되고 사용자 지정됨에 따라 팀은 일반적인 Azure 아키텍처에서 기술을 개발합니다. 또한 새로운 비즈니스 및 기술 요구 사항을 충족하기 위해 <a href="https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/refactor" target="_blank">랜딩 존을 리팩터링</a> 하는 방법과 <a href="https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/considerations/azure-test-driven-development" target="_blank">테스트 기반 개발을</a> 통해 고품질의 변화가 클라우드 환경에 가치를 더하도록 보장하는 방법을 배우는 것도 중요합니다. &rsquo;또한 Azure의 거버넌스 도구를 사용하여 환경 팩터리를 만들어 고객에게 보안, 잘 관리되는 잘 관리되는 Azure 랜딩 존의 신속한 배포를 제공하는 방법을 경험하게 됩니다.</p>


  <p>고객의&rsquo; 클라우드 채택 노력이 발전함에 따라 <a href="https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/govern/">거버넌스</a> 및 <a href="https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/manage/">관리</a> 방법론에 있는 지침을 사용하여 거버넌스 및 운영 관리 상태를 완성하는 데 도움이 될 수 있습니다. 이러한 프로세스와 분야가 성숙함에 따라 Azure 랜딩 존 및 Azure 거버넌스 도구 제품군은 기존 환경에 변경 내용을 적용하는 편리한 접근 방식을 제공합니다. 이를 통해 공동 기술 팀은 적절한 속도로 거버넌스 및 관리를 완성하는 동시에 기술 호환성 문제에 의해 이러한 진행이 지연되지&rsquo; 않도록 할 수 있습니다.</p>


  <h2>자세한 정보</h2>


  <p>Azure 랜딩 존에 대해 자세히 알아보려면 다음을 포함하여 <a href="https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/overview">CAF(클라우드 채택 프레임워크)</a> 에서 준비 섹션을 확인하세요.</p>


  <ul>
      <li><a href="https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/refactor" target="_blank">정의된 Azure 랜딩 존을 읽습니다</a>.</li>
      <li><a href="https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/design-areas" target="_blank">Azure 랜딩 존 설계 영역을</a> 검토하고 랜딩 존 요구 사항에 대해 생각하기 시작합니다.</li>
      <li><a href="https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/implementation-options" target="_blank">Azure 랜딩 존 구현 옵션을</a> 평가하여 요구 사항에 가장 적합한 배포 방법을 찾습니다.</li>
  </ul>


  <p>고객이 Azure 랜딩 존을 배포할 수 있도록 도와줄 준비가 되면 다음 리소스를 통해 시작하는 데 도움이 됩니다.</p>


  <ul>
      <li><b>작게 시작하고 확장합니다</b> . <a href="https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/migrate-landing-zone" target="_blank">CAF 마이그레이션 랜딩 존</a> 청사진을 배포하여 마이그레이션 준비 환경 빌드를 시작합니다. <a href="https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/foundation-blueprint">CAF 청사진</a>을 추가하여 모든 환경에 거버넌스 도구 추가를 시작합니다.</li>
      <li><b>엔터프라이즈 규모로 시작:</b> 보다 강력한 구현을 위해 <a href="https://github.com/Azure/Enterprise-Scale/blob/main/docs/reference/contoso/Readme.md" target="_blank">참조 구현</a>을 활용하여 <a href="https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/enterprise-scale/" target="_blank">CAF 엔터프라이즈 규모 랜딩 존</a>을 배포합니다.</li>
      <li><b>타사 다중 클라우드 옵션:</b> <a href="https://docs.microsoft.com/en-us/azure/cloud-adoption-framework/ready/landing-zone/terraform-landing-zone#customize-and-deploy-your-first-landing-zone" target="_blank">CAF Terraform 모듈을</a> 사용하여 랜딩 존을 배포합니다.</li>
  </ul>


  <p>이미 Azure에 워크로드가 있고 모범 사례에 대해 평가하고 싶으신가요? <a href="https://docs.microsoft.com/en-us/azure/architecture/framework/" target="_blank">Microsoft Azure Well-Architected Framework</a> 및 <a href="https://docs.microsoft.com/en-us/assessments/?id=azure-architecture-review&amp;mode=pre-assessment" target="_blank">Microsoft Azure Well-Architected 검토를 확인합니다</a>.</p>


  <p>Azure 랜딩 존을 활용하여 고객에게&rsquo; 클라우드 채택 요구를 지원할 수 있는 올바른 클라우드 환경을 만들어 비즈니스를 성장시키고 신뢰할 수 있는 클라우드 어드바이저로서의 입지를 강화하세요! 올바른 환경을 구축하면 사용자와 고객의&rsquo; 최신 운영에서 조직의 혁신 및 마이그레이션 요구를 지원할 수 있습니다. Azure 랜딩 존 위에 클라우드를 채택하는 것은 고객&rsquo; IT 포트폴리오 전체에서 클라우드의 민첩성, 규모 및 비용 이점을 잠금 해제하는 첫 번째 단계입니다.</p>
