### YamlMime:Yaml
ms.openlocfilehash: 95497fae919eb86fd505e6087f329030511312fb
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139908501"
Slug: cross-post-applications-are-now-open-for-the-microsoft-accelerator-for-windows-azure-2013
Title: '교차 게시: 이제 애플리케이션이 Windows Azure용 Microsoft Accelerator에 대해 열려 있습니다. - 2013'
Summary: 지난 몇 달 동안 Windows Azurehave&nbsp;용 Microsoft Accelerator의 신생 기업은 비즈니스 및 기술 리더의 멘토링을 받았으며 투자자들과 만나 서로에게서 배웠습니다,...
Content: <p>지난 몇 달 동안 Windows Azurehave&nbsp;용 Microsoft Accelerator의 신생 기업은 비즈니스 및 기술 리더의 멘토링을 받고, 투자자들과 만나 서로에게서 배웠으며, 가장 중요한 것은 훌륭한 제품을 구축했습니다. 첫 번째 클래스의 신생 기업 및 Windows Azurehere&nbsp;를 사용하는 방법에&rsquo; 대해 자세히 알아볼 수 있습니다.</p>  <p>첫 번째 클래스가 1월 17<sup>일에</sup> 데모의 날에 가까워지면서 오늘 Windows Azure용 Microsoft Accelerator의 두 번째 클래스에 대한 애플리케이션을 열고 있음을 발표하게 되어 기쁩니다. 이는 2013년 4월 1<sup>&nbsp;</sup>일에 시작되어 2013년 6월 26일에 데모의 날로 끝납니다.</p>  <p>현재 신생 기업에서 일하거나 자신의 회사를 설립하는 것을 고려하는 경우, 우리는 당신이 적용하는&nbsp; 것이 좋습니다. Were&rsquo;는 2013년 2월 1<sup>일까지</sup> 신청서를 수락했습니다. Accelerator 및 애플리케이션 프로세스&nbsp;에 대한 자세한 정보를 찾을 수 <a href="https://www.microsoft.com/bizspark/accelerator/" target="_blank">있습니다</a>.</p>  <p>여기에 내 원래 게시물을 읽어 <a href="https://weblogs.asp.net/scottgu/archive/2012/12/19/applications-are-now-open-for-the-microsoft-accelerator-for-windows-azure-2013.aspx" target="_blank">보</a>십시오.</p>
