### YamlMime:Yaml
ms.openlocfilehash: 8dfb5b4416423ecd4778c58faaf683c95f9194ee
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139898040"
Slug: custom-data-and-cloud-init-on-windows-azure
Title: Microsoft Azure의 사용자 지정 데이터 및 Cloud-Init
Summary: >-
  사용자 지정 데이터란?

  고객이 프로비저닝 시간에 Microsoft Azure Virtual Machine으로 스크립트나 다른 메타데이터를 삽입할 수 있는지 질문하는 경우가 종종 있습니다.다른 클라우드에서는 이 개념을 종종 ...라고 합니다.
Content: >-
  <h4>사용자 지정 데이터란?</h4>


  <p>고객은 종종 프로비전 시 스크립트 또는 다른 메타데이터를 Microsoft Azure 가상 머신에 삽입하는 방법을 묻습니다.&nbsp; 다른 클라우드에서는 이 개념을 <em>사용자 데이터</em>라고도 합니다. &nbsp;Microsoft Azure <em>사용자 지정 데이터</em>라는 유사한 기능이 있습니다. 사용자 지정 데이터는 새 호스트 이름, 사용자 이름, 암호, 인증서 및 키 등과 같은 다른 프로비저닝 구성 정보와 함께 VM으로 전송됩니다.&nbsp; 이 데이터는 Base64로 인코딩된 데이터로 Azure API에 전달됩니다. &nbsp;Windows 이 데이터는 <em>%SYSTEMDRIVE%\AzureData\CustomData.bin</em>에서 이진 파일로 끝납니다.&nbsp; Linux에서 이 데이터는 프로비전 중에 /var/lib/waagent 디렉터리에 복사되는 ovf-env.xml 파일을 통해 VM에 전달됩니다.&nbsp; 최신 버전의 Microsoft Azure Linux 에이전트는 편의상 base64로 인코딩된 데이터를 <em>/var/lib/waagent/CustomData</em>에도 복사합니다.</p>


  <h4>Cloud-Init는 어떤가요?</h4>


  <p>현재 Microsoft Azure 갤러리의 Ubuntu 이미지만 cloud-init를 미리 설치하고 프로비전 중에 전송된 사용자 지정 데이터에 대해 작동하도록 구성되었습니다.&nbsp; 즉, Ubuntu의 경우 사용자 지정 데이터를 사용하여 cloud-init 구성 파일을 사용하여 VM을 프로비전하거나 프로비전 중에 cloud-init에서 실행되는 스크립트만 보낼 수 있습니다.&nbsp; 자세한 내용은 <a href="https://help.ubuntu.com/community/CloudInit">cloud-init 설명서를 참조하세요</a>. 이미지에서 cloud-init를 사용할 수 없는 경우 데이터를 읽을 수 있는 시스템에 스크립트 또는 기타 도구를 미리 설치하는 경우 사용자 지정 데이터를 계속 사용할 수 있습니다.&nbsp; 이 경우 <em>부팅 시 %SYSTEMDRIVE%\AzureData\CustomData.bin</em>(Windows) 또는 <em>/var/lib/waagent/ovf-env.xml</em> (Linux) 파일을 통해 사용자 지정 데이터를 읽을 수 있는 스크립트를 설치하여 디코딩하고 데이터에 대해 작업할 수 있습니다.&nbsp; 스크립트가 설치되면 <a href="https://azure.microsoft.com/en-us/documentation/articles/virtual-machines-capture-image-windows-server/">Windows</a> 또는 <a href="https://azure.microsoft.com/en-us/documentation/articles/virtual-machines-linux-capture-image/">Linux</a> 이미지를 프로비전 해제하고 다시 사용하도록 캡처할 수 있습니다.</p>


  <h4>어떻게 작동하나요?</h4>


  <p>현재 사용자 지정 데이터를 IaaS VM에 삽입하는 가장 쉬운 방법은 <a href="https://azure.microsoft.com/en-us/documentation/articles/xplat-cli/">Windows Azure 명령줄 도구를 사용하는 것입니다</a>.&nbsp; Microsoft Azure Powershell cmdlet에서 이 기능에 대한 지원은 아직 제공되지 않지만 곧 출시될 예정입니다. CLI 도구 버전 0.7.5를 기준으로 <em>--custom-data</em>라는 새 매개 변수가 있습니다.&nbsp; 이 매개 변수는 파일 이름을 인수로 사용하고 도구는 base64에서 파일 내용을 인코딩하고 프로비저닝 구성 정보와 함께 보냅니다. &nbsp;여기서 유일한 제한은 파일이 64KB 미만이어야 하거나 Azure API가 요청을 수락하지 않는다는 것입니다. 다음은 사용자 지정 데이터를 프로비전하고 Ubuntu Linux VM에 전달하는 방법에 대한 간단한 예제입니다. <a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/1768/3426.stephen.png"><img alt="" border="0" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/1768/3426.stephen.png"></a> 이 예제에서는 <em>custom-data.txt</em> cloud-init 구성 파일이거나 단순히 셸 스크립트일 수 있습니다(#!으로 시작하는 한 cloud-init에서 실행). 시도해 보세요.</p>


  <h4>추가 참조:</h4>


  <ul>
      <li><a href="https://docs.microsoft.com/en-us/previous-versions/azure/reference/jj157186(v=azure.100)?redirectedfrom=MSDN">역할 작업 설명서 추가</a></li>
      <li>Azure Virtual Machines의 <a href="https://docs.microsoft.com/en-us/azure/virtual-machines/custom-data">사용자 지정 </a><a href="https://docs.microsoft.com/en-us/azure/virtual-machines/custom-data">데이터</a><a href="https://docs.microsoft.com/en-us/azure/virtual-machines/custom-data"> 및 Cloud-Init 설명서 </a></li>
  </ul>
