### YamlMime:Yaml
ms.openlocfilehash: 03393ff648305976f131e6c88857afeb506d5054
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139901290"
Slug: customer-success-stories-with-application-insights-analytics-2
Title: Application Insights Analytics를 사용하는 고객 성공 사례
Summary: //Build 2016에서 발표된 Visual Studio Application Insight의 새로운 진단 및 분석 기능에 대한 훌륭한 피드백을 받았습니다.
Content: >-
  <p>//Build 2016에서 발표된 <a href="https://azure.microsoft.com/services/application-insights/">Application Insight에 Visual Studio</a> <a href="https://azure.microsoft.com/en-us/blog/new-diagnostics-and-analytics-capabilities-in-application-insights/">새로운 진단 및 분석 기능에</a>&nbsp; 대한 훌륭한 피드백을 받았습니다.</p>


  <p>다음은 몇 가지 고객 성공 사례입니다.</p>


  <h2>Quorum</h2>


  <blockquote>

  <p><a href="https://na01.safelinks.protection.outlook.com/?url=http%3a%2f%2fwww.qbsol.com%2f&amp;data=01%7c01%7ckghelani%40exchange.microsoft.com%7ce154670939ef44a19c1208d352866925%7c72f988bf86f141af91ab2d7cd011db47%7c1&amp;sdata=zSBqwwy6MeqY%2f7YzTxPYFlu1z8Da7XaeIN%2fK7sxTfT0%3d">쿼럼</a> (<a href="https://na01.safelinks.protection.outlook.com/?url=http%3a%2f%2fwww.qbsol.com&amp;data=01%7c01%7ckghelani%40exchange.microsoft.com%7ce154670939ef44a19c1208d352866925%7c72f988bf86f141af91ab2d7cd011db47%7c1&amp;sdata=y5RhIhg2Zx72pjedrkP7xbL7B9O07WQ8HyZe1mXjQ%2bs%3d">qbsol.com</a>)은 탄화수소 및 에너지 비즈니스 관리를 위한 혁신적인 소프트웨어를 만듭니다. Were&rsquo;는 에너지 가치 체인 전반에 걸쳐 고객 이익을 창출하는 것으로 입증된 통합 솔루션 플랫폼으로 업계를 발전시켰습니다. <a href="https://na01.safelinks.protection.outlook.com/?url=http%3a%2f%2fwww.qbsol.com%2ffield-operations%2f&amp;data=01%7c01%7ckghelani%40exchange.microsoft.com%7ce154670939ef44a19c1208d352866925%7c72f988bf86f141af91ab2d7cd011db47%7c1&amp;sdata=bq6FO3PIbXTmYHmDQgniyzsZWize5%2f%2bE834RrwICRs0%3d">프로덕션 작업 및 현장 작업을 위한</a> 쿼럼&rsquo; 클라우드 기반 소프트웨어는 Microsoft Azure 실행됩니다. 즉, 석유 및 가스 회사는 탁월한 속도와 성능의 혜택을 누릴 수 있습니다.</p>


  <p>App Insights 추가된 새로운 분석 기능을 통해 팀은 중요한 애플리케이션 및 서비스 상태 원격 분석에 즉시 액세스할 수 있습니다. 앱 데이터에 대한 SQL 같은 쿼리를 작성하고 즉각적인 응답을 받아서 마지막, 5분, 30분 또는 90분 동안 어떤 일이 일어나고 있는지에 대한 질문에 답하려고 할 때 이것이 이동 도구라고 생각합니다. 이제 시간이 지남에 따라 데이터 추세를 보고 플랫폼 및 해당 서비스를 개선하기 위해 사전에 변경하려는 경우 Power BI 같은 것이 필요합니다.</p>


  <p>모든 도구가 유용하려면 사용하기로 한 결정과 도구에서 제공하는 값 사이에 장벽이 적어야 합니다. 데이터 수집 및 스토리지에 대한 단일 관리형 플랫폼을 사용하더라도 데이터를 분석할 수 있을 때까지 실제 값이 달성되지 않아 사용할 수 있는 정보로 전환됩니다. Intellisense와 같은 작은 것들은 앱 Insights 시장에서 다른 경쟁 서비스 사이의 차별화 요인으로 봅니다.</p>


  <p>궁극적으로 관리할 다른 클러스터가 아니라 활용할 서비스를 찾고 있었습니다. 처음에는 오픈 소스 검색 및 분석 엔진을 사용하여 모든 원격 분석을 해당 엔진으로 이동하려고 했습니다. 클러스터를 사용할 수 없는 몇 번이면 방향을 변경하고 오버헤드를 줄이도록 하는 대안을 찾아야 했습니다. 솔루션에 대한 앱 Insights 분석을 선택했습니다.</p>


  <p>App Insights 새로운 분석 기능에 대한 장기적인 잠재력은 클라우드 및 온-프레미스, 데스크톱 및 스마트 디바이스, 서비스 상태 및 성능, 석유 및 가스 환경 전반에 걸쳐 디바이스 및 센서 데이터에 모두 존재합니다. - <strong>Shawn Cutter, Quorum Business Solutions 부사장</strong></p>

  </blockquote>


  <h2>OSIsoft</h2>


  <blockquote>

  <p>샌프란시스코 베이 지역에 본사를 둔 30년 된 소프트웨어 회사인 <a href="https://www.osisoft.com/Default.aspx">OSIsoft</a>는 산업 프로세스 데이터 및 운영 인텔리전스 분야의 글로벌 리더입니다. OSIsofts&rsquo; <a href="https://www.osisoft.com/software-support/what-is-pi/What_Is_PI.aspx">PI 시스템은</a> 포춘 500대 산업 기업 중 65% 이상에서 실시간 의사 결정 지원 및 고급 분석을 위해 대량의 센서 기반 운영 데이터를 수집, 저장, 처리 및 제공하는 데 사용됩니다.</p>


  <p>OSIsoft에서는 센서 기반 데이터 인프라 기술의 클라우드 네이티브 개선 사항을 개발하기 시작했으며 곧 분산된 대규모 시스템과 함께 작동하는 원격 분석 솔루션을 찾고 있었습니다. 다음 두 가지 요구 사항을 충족하는 것이 필요했습니다.</p>


  <ul>
      <li>대량의 로그 및 메트릭 데이터를 대규모로 저장하는 기능</li>
      <li>이 데이터를 안정적으로 쿼리하는 기능</li>
  </ul>


  <p>Microsoft와의 긴밀한 관계 덕분에 하나 또는 다른 요구 사항을 충족하지 않는 여러 기술을 탐색한 끝에 마침내 그 당시의 내부 Microsoft 기술인 Kusto로 끝났습니다. Kusto를 원격 분석 프레임워크에 통합하기 시작하면 데이터 소비율에 매우 감명을 받았습니다. Kusto를 사용하면 분산 프레임워크에서 실행되는 여러 마이크로 서비스의 원격 분석 데이터를 기록하는 동시에 스키마 및 스키마 없는 스토리지를 통해 향후 변경에 적절하게 적응하는 메커니즘을 보장할 수 있습니다. &ldquo;확장성이 뛰어난 마이크로 서비스 아키텍처를 사용하면 원격 분석에 대한 어려운 과제가 발생합니다. Kusto는 규모, 견고성 및 유연성&rdquo; 의 이상적인 조합을 제공했습니다. OSIsoft의 소프트웨어 개발자인 Sai Roop Tetali는 말했습니다.</p>


  <p>Kusto의 SQL 같은 쿼리 기능은 스토리지 기능만큼이나 인상적입니다. 방대한 양의 데이터를 선별하고 필요한 정보를 신속하게 제공하는 풍부한 쿼리를 작성할 수 있습니다. Kusto로 이전한 이후 빠른 턴어라운드로 문제를 진단하는 데 결정된 개선을 보았습니다. &ldquo;Kusto는 매우 좋은 쿼리 기능을 제공했습니다. 구문 쿼리와 같은 SQL 갖는 것은 팀이 신속하게 온보딩하고 즉시 우리의 서비스가 대규모로 작동하는 방법에 대한 훨씬 더 깊은 통찰력을 얻기 시작하는 데 필요한 램프 업 시간에 큰 차이를 만들었다,&rdquo; Tetali는 말했다.</p>


  <p>또한 Kusto에 저장하는 원시 원격 분석 데이터를 쿼리하여 여러 테넌트에서 분산 애플리케이션의 사용량을 추적할 수 있습니다.&quot; 과거에&rsquo;는 정적 데이터를 볼 수 있었습니다. OSIsoft의 서비스 운영 제품 관리자인 앨리슨 무라스키(Allison Muraski)는 도움이 되지만 실제로는 이야기를&rdquo; 들려주지 않는다고&rsquo; 말했습니다. &ldquo;Kusto는 정적 메트릭을 반환하고 집계 및 계산을 제공할 뿐만 아니라 데이터를 수동으로 조작하지 않고도 질문에 신속하게 대답할 수 있는 방식으로 렌더링하는 어려운 작업을 해결합니다.&quot;</p>


  <p>&quot;Kusto는 애플리케이션 Insights 큰 도약입니다. 특히 Kusto Explorer는 사용하기에 매우 좋습니다. 이제 간편한 소비를 바탕으로 애플리케이션&quot; 에 대한 더 많은 데이터를 기록할 계획을 세울 수 있다고 OSIsoft의 클라우드 서비스 이니셔티브 책임자 인 Chad Chisholm은 말했습니다. Kusto 덕분에 대량의 고주파 원격 분석 데이터를 저장할 수 있을 뿐만 아니라 다양한 조건에서 애플리케이션이 작동하는 위치와 방법에 대한 인사이트를 개발할 수 있는 풍부한 쿼리 기능도 있습니다. Kusto를 사용하는 팀의 피드백은 매우 긍정적이었으며, 이제 OSIsoft의 여러 다른 팀에 배포하고 있습니다. - <strong>Manas Talukdar, 소프트웨어 엔지니어링 팀 리더, OSIsoft, LLC</strong></p>

  </blockquote>


  <p>참고: OSIsoft는 <a href="https://blogs.msdn.microsoft.com/bharry/2016/03/28/introducing-application-analytics/">Brian Harrys&rsquo; 블로그</a>에서 참조한 대로 애플리케이션 Insights 분석 기능에 대한 내부 코드 이름 &ldquo;Kusto&rdquo;를 언급합니다.</p>


  <p>자세한 내용은 Channel 9에서 Application Insights Analytics 기능에 대한 자세한 내용을 참조하세요.</p>


  <p><iframe allowfullscreen="" frameborder="0" height="315" src="https://channel9.msdn.com/Events/Build/2016/T666/player" width="560"></iframe></p>


  <p>&nbsp;</p>


  <p><iframe allowfullscreen="" frameborder="0" height="315" src="https://channel9.msdn.com/Events/Build/2016/P591/player" width="560"></iframe></p>
