### YamlMime:Yaml
ms.openlocfilehash: 4039ffeed371f709f3f9a9ccb65e147e37f18afa
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139911957"
Slug: customize-your-agent-update-settings-azure-virtual-machine-disaster-recovery
Title: Azure Virtual Machine 재해 복구에 대한 자동 업데이트 설정 사용자 지정
Summary: Azure VM의 재해 복구에 사용되는 에이전트의 자동 업데이트 기능을 릴리스했을 때 가장 자주 받은 피드백은 액세스 제어와 관련이 있었습니다. 고객의 요청은 구독에서 올바른 액세스 권한을 위임받은 사람이 승인하고 만든 이전에 만든 자동화 계정을 제공할 수 있도록 허용하는 것이었습니다.
Content: >-
  <p>오늘날&rsquo; 클라우드 기반 환경에서는 직원들이 업무를 효과적으로 수행하는 데 반드시 필요한 데이터에만 액세스할 수 있습니다. 이러한 제한된 액세스는 직원이 많거나 공급업체에 참여하는 경우처럼 액세스 동작을 모니터링하기 어려운&#39;시나리오에서 특히 중요합니다. 액세스는 일반적으로 작업 책임, 권한 및 기능을 기반으로 합니다. 따라서 일부 작업 프로필은 책임을 이행할 필요가 없는 경우 특정 데이터 또는 특정 작업을 수행할 수 있는 권한에 액세스할 수 없습니다. 따라서 액세스를 제어하지만 인프라 관리자 프로필에 맞게 작업 의무를 수행할 수 있는 기능은 점점 더 관련성이 높아지고 고객이 자주 요청합니다.</p>


  <h2>당신은 물었다, 우리는 듣고!</h2>


  <p>Azure VM(Virtual Machines)의 DR(재해 복구)에 사용되는 에이전트의 자동 업데이트를 릴리스했을 때 가장 자주 받은 피드백은 액세스 제어와 관련이 있었습니다. 고객에게는 DR을 사용하도록 설정, 장애 조치 또는 테스트하기 위한 작업을 실행할 수 있는 충분한 권한이 부여된 DR 관리자가 있었습니다. 자동 업데이트를 사용하도록 설정하고 월별 업데이트를 모니터링하고 에이전트를 수동으로 업그레이드해야 하는 번거로움을 피하고 싶었지만 DR 관리자 기여자에게 구독에 대한 액세스 권한을 부여하지 않으려는&#39;자동화 계정을 만들 수 있습니다. 고객이 구독에서 올바른 액세스 권한을 위임받은 사용자가 승인하고 만든 기존 자동화 계정을 제공할 수 있도록 했습니다. 그런 다음 이 자동화 계정을 사용하여 새 업데이트를 확인하고 새 릴리스가 있을 때마다 기존 에이전트를 업그레이드하는 Runbook을 실행할 수 있습니다.</p>


  <h2>기존 자동화 계정을 선택하는 방법</h2>


  <ol>
   <li>복제를 사용하도록 설정할 가상 머신을 선택합니다.</li>
   <li><strong>고급 설정</strong> 블레이드의<strong> 확장 설정</strong> 아래에서 이전에 만든 Automation 계정을 선택합니다.</li>
  </ol>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/fa6bf496-647b-4933-982b-4bfcb335a37e.jpg"><img alt="blog-Auto-accnt" border="0" height="584" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/fce72507-b066-4cf5-999b-8be2920c26a9.jpg" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="blog-Auto-accnt" width="610"></a></p>


  <p>이 자동화 계정은 <strong>Recovery Services</strong> 자격 증명 모음 내의 모든 Azure 가상 머신에 대한 에이전트를 자동으로 업데이트하는 데 사용할 수 있습니다. 하나의 가상 머신에 대해 변경하면 모든 가상 머신에도 동일하게 적용됩니다.</p>


  <p><em>이 기능은 Hyper-V/VMware가 아닌 Azure 가상 머신의 재해 복구에만 적용 </em> 됩니다. Vm</p>


  <p>관련 문서:</p>


  <ul>
   <li><a href="https://docs.microsoft.com/azure/site-recovery/azure-to-azure-autoupdate#how-automatic-updates-work" target="_blank">자동 업데이트의 작동 원리</a></li>
   <li><a href="https://docs.microsoft.com/azure/site-recovery/azure-to-azure-autoupdate#enable-automatic-updates" target="_blank">자동 업데이트를 사용하도록 설정하는 방법</a></li>
  </ul>


  <p>이 외에도 최근에&#39;받은 최고 고객 요청 중 하나를 발표하여 워크로드를 더 잘 제어할 수 있습니다.</p>


  <ul>
   <li>
   <p><a href="https://docs.microsoft.com/azure/site-recovery/azure-to-azure-enable-replication-added-disk" target="_blank">새로 추가된 디스크</a> &ndash; 에 대해 복제 사용 재해 복구를 위해 이미 구성된&#39;Azure VM에 새로 추가된&#39;데이터 디스크에 대해 복제를 사용하도록 설정할 수 있습니다.</p>
   </li>
  </ul>


  <p>Azure는 기본적으로 중요 업무용 워크로드에 대한 고가용성 및 안정성을 제공하며, Azure Site Recovery에서 제공하는 재해 복구를 사용하여 보호를 개선하고 규정 준수 요구 사항을 충족하도록 선택할 수 있습니다. <a href="https://docs.microsoft.com/azure/site-recovery/" target="_blank">Azure Site Recovery</a>를 시작하는 것은 간단합니다. <a href="https://aka.ms/asr_ga_azureblog_pricing" target="_blank">가격 정보를</a> 확인하고 <a href="https://aka.ms/asr_ga_azureblog_trial" target="_blank">무료 Microsoft Azure 평가판에 등록</a>하세요. <a href="https://aka.ms/asr_ga_azureblog_forum" target="_blank">MSDN의 Azure Site Recovery 포럼을</a> 방문하여 추가 정보를 확인하고 다른 고객과 소통할 수도 있습니다.</p>
