### YamlMime:Yaml
ms.openlocfilehash: 3948e103808c80aad9796850eb18098818b7f3e7
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139898643"
Slug: deep-diagnostics-for-web-apps-with-application-insights
Title: Application Insights 사용하는 Web Apps에 대한 심층 진단
Summary: 오늘, 뉴욕에서 커넥트 () 2015에서, 우리는 애플리케이션 분석 및 진단에 대한 우리의 제안에 몇 가지 발표를했다.
Content: >-
  <p>오늘 뉴욕의 커넥트() 2015에서 다음 제품으로 구성된 애플리케이션 분석 및 진단 제품에 대한 몇 가지 공지 사항을 발표했습니다.</p>


  <ul>
   <li><strong>웹앱 및 서비스</strong>: <a href="https://azure.microsoft.com/en-us/services/application-insights/">Visual Studio 애플리케이션 Insights</a></li>
   <li><strong>모바일 앱</strong>: <a href="https://hockeyapp.net/features/">HockeyApp</a></li>
  </ul>


  <p>이제 이러한 각 제품을 강화하고 Visual Studio 및 Visual Studio Team Services 포함한 ALM 도구 및 서비스에 대한 통합을 확장하는 데 주력하고 있습니다.</p>


  <p><strong>HockeyApp</strong>은 iOS, OS X, Android 또는 Windows 디바이스 앱을 빌드하는 사용자뿐만 아니라 Xamarin, Cordova 및 Unity를 기반으로 하는 플랫폼 간 앱을 빌드하는 사람들을 위한 모바일 DevOps 솔루션입니다. 이를 통해 빌드를 베타 테스터에게 배포하고, 충돌 데이터를 수집하고, 사용자 피드백을 얻을 수 있습니다. &rsquo;간편한 빌드 배포 및 작업 항목 통합을 지원하는 Visual Studio Team Services 통합됩니다. <a href="https://support.hockeyapp.net/kb">HockeyApp 기술 자료에서</a> 자세히 알아보고 <a href="https://hockeyapp.net/blog/">HockeyApp 블로그</a>에서 최신 정보를 확인할 수 있습니다.</p>


  <p>이 게시물에서는 웹앱 및 서비스에 대한 <strong>애플리케이션 Insights</strong> 대해 이야기하게 되어 기쁩니다.</p>


  <h1>Visual Studio 통합</h1>


  <p>광범위한 <a href="https://www.visualstudio.com/features/alm-devops-vs">Microsoft ALM/DevOps 스택</a> 내에서 애플리케이션 Insights 역할은 개발자가 라이브 웹앱에서 문제를 감지 및 진단하고 영향을 기반으로 문제의 우선 순위를 지정하도록 돕는 것입니다. 개발 팀이 지속적인 업데이트를&rsquo; 채택함에 따라 빠르게 변화하는 앱에서 발생하는 일을 최우선으로 하는 것이 중요합니다.</p>


  <p>&rsquo;따라서 애플리케이션 Insights 개발 프로세스의 필수적인 부분으로 만듭니다. 이미 <a href="https://azure.microsoft.com/en-us/documentation/articles/app-insights-start-monitoring-app-health-usage/#ide">Visual Studio 2013 및 2015</a>의 일부로 제공되므로 최소한의 노력으로 새 앱 또는 기존 앱을 신속하게 온보딩할 수 있습니다.</p>


  <p><img alt="New Project" border="0" height="445" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/66d40ca0-0758-46b2-96de-10d536c4413c.png" style="border-top: 0px; border-right: 0px; background-image: none; border-bottom: 0px; float: none; padding-top: 0px; padding-left: 0px; margin-left: auto; border-left: 0px; display: block; padding-right: 0px; margin-right: auto" title="새 프로젝트" width="640"></p>


  <p>Visual Studio 2015 업데이트 1이 곧 릴리스되면 이제 IDE를 종료하지 않고도 Azure Preview Portal에서 사용한 것과 동일한 애플리케이션 Insights Search 환경을&rsquo; 시작할 수 있습니다. 즉, 문제를 조사하거나 버그를 심사하는 동안 브라우저를 시작하지 않고도 프로덕션 원격 분석을 통해 검색하고, 결과를 보고, 해당 이벤트의 세부 정보를 드릴할 수 있습니다. 이렇게 하면 애플리케이션 Insights 개발 도구로 사용하고 프로덕션 환경에 푸시하기 전에 사용자 지정 원격 분석을 쉽게 테스트할 수 있습니다.</p>


  <p><img alt="Application Insights Search experience" border="0" height="433" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/1aa2b653-8075-4322-bd75-787afc4887a2.jpg" style="border-top: 0px; border-right: 0px; background-image: none; border-bottom: 0px; float: none; padding-top: 0px; padding-left: 0px; margin-left: auto; border-left: 0px; display: block; padding-right: 0px; margin-right: auto" title="애플리케이션 Insights 검색 환경" width="640"></p>


  <p>또한 업데이트 1부터 애플리케이션 Insights <a href="https://blogs.msdn.com/b/visualstudioalm/archive/2015/07/20/performance-and-diagnostic-tools-in-visual-studio-2015.aspx">Visual Studio Diagnostics Hub</a>와 통합되어 F5 디버깅 환경을 Application Insights SDK에서 내보낸 데이터와 결합합니다. 프로젝트에 SDK를 설치하면 다른 F5 진단 조사에 사용하는 동일한 이벤트 타임라인에서 애플리케이션 Insights 원격 분석 이벤트를 볼 수 있습니다.</p>


  <p><img alt="Diagnostic Tools" border="0" height="470" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/308b81d6-7164-4a13-a7f7-5360d00f4da4.jpg" style="border-top: 0px; border-right: 0px; background-image: none; border-bottom: 0px; float: none; padding-top: 0px; padding-left: 0px; margin-left: auto; border-left: 0px; display: block; padding-right: 0px; margin-right: auto" title="진단 도구" width="640"></p>


  <p>&rsquo;곧 VSTS(Visual Studio Team Services)와 더 많은 통합을 확인하여 사전 및 사후 프로덕션, 테스트 및 모니터링 간에 브리지를 만듭니다. &rsquo;애플리케이션 Insights 차트 및 그래프에 <a href="https://www.visualstudio.com/features/release-management-vs">VSTS Release Management</a> 배포 주석을 표시하여 성능 변경 내용을 빌드와 쉽게 상호 연결할 수 있습니다.</p>


  <h1>사전 문제 감지</h1>


  <p>애플리케이션 Insights 개발자를 위해 설계되었습니다. 개발 팀은 더 이상 애플리케이션을 ops 팀에게 던지지 않습니다. 개발 주기는 엄격하며 개발자는 앱이 라이브 상태인 동안&rsquo; 앱에 어떤&rsquo; 일이 일어나는지 알아야 합니다. 그러나 라이브 환경과 디버그 또는 테스트 환경의 큰 차이점은 야생에서 조건의 가변성입니다. 응답 시간이 전반적으로&rsquo; 악화되면 쉽게 볼 수 있지만 일부 사용자에게만 영향을 주는 변형을 발견하기가 더 어려울 수 있습니다.</p>


  <p>비정상적인 세그먼트 및 서비스 저하를 식별하는 기계 학습 기반 환경을 도입하는 중입니다. 이렇게 하면 문제의 특성에 대한 심층적인 인사이트를 제공하여 프로덕션 문제를 완화하는 시간이 단축됩니다. 예를 들어 웹앱이 특정 시간에 특정 서버에서 느리게 응답하는 경우 문제 세부 정보를 알려 줍니다. 사용해 보시려면 연락 <a href="mailto:AppInsightsML@microsoft.com">AppInsightsML@microsoft.com</a> 주시면 저희가 함께 작업하여 설정해 주세요.</p>


  <h1>Azure Application Diagnostics Hub</h1>


  <p>Azure 앱 개발자가 직면한 주요 문제, 특히 성능 저하 진단, 앱 배포 및 업그레이드 실패를 <a href="https://azure.microsoft.com/en-us/blog/tag/application-insights/">해결</a>하여 애플리케이션 Insights Azure Application Diagnostics의 허브로 만듭니다.</p>


  <p><a href="https://azure.microsoft.com/en-us/blog/announcing-the-azure-sdk-2-8-for-net/">Azure SDK 2.8</a>부터 Application Insights 사용하여 웹 역할, 작업자 역할 및 Windows VM에서 <a href="https://azure.microsoft.com/en-us/documentation/articles/cloud-services-dotnet-diagnostics/">Azure Diagnostics</a> 원격 분석에 액세스할 수 있습니다. 이제 애플리케이션 Insights 이러한 성능 카운터, Windows 이벤트 로그 및 앱 추적과 앱 내에서 전송된 응답 시간, 종속성 및 사용자 지정 이벤트의 상관 관계를 지정할 수 있습니다. 이제 문제를 더 빠르게 감지, 심사 및 진단하는 데 필요한 모든 정보가 한 곳에 있습니다.</p>


  <h1>확장 가능하고 개방적이며 유연합니다.</h1>


  <p>Application Insights 기본 제공 원격 분석으로 값의 큰 청크를 제공하지만 애플리케이션에서 추적, 예외, 페이지 보기, 종속성 등을 캡처하는 <a href="https://azure.microsoft.com/en-us/documentation/articles/app-insights-api-custom-events-metrics/">사용자 지정 계측</a>을 제공할 수도 있습니다. 데이터 수집에 대한 더 많은 제어를 제공하기 위해 최근에 <a href="https://azure.microsoft.com/en-us/documentation/articles/app-insights-sampling/">샘플링</a> 개념을 도입했습니다. 기본적으로 포털에서 애플리케이션 데이터에 대한 통계적으로 올바른 분석을 유지하면서 감소된 원격 분석 집합을 수집하고 저장할 수 있습니다.</p>


  <p>모든 SDK는 <a href="https://github.com/Microsoft/ApplicationInsights-Home">GitHub 오픈 소스</a>이며 커뮤니티 기여를 환영하고 지원합니다. 현재 ASP.NET, J2EE, Ruby, PHP, JavaScript, Node.JS 및 Python을 비롯하여 다양한 플랫폼을 지원하는 다양한 SDK가 있습니다.</p>


  <p>데이터를 다른 데이터 원본과 매시업하려는 경우 <a href="https://azure.microsoft.com/en-us/documentation/articles/app-insights-export-telemetry/">연속 내보내</a>기를 설정하여 SQL, Excel, Power BI 및 기타 도구에서 데이터를 분석할 수 있습니다. 최근에 발표된 <a href="https://azure.microsoft.com/en-us/blog/application-insights-content-pack-for-power-bi/">Power BI 애플리케이션 Insights 콘텐츠 팩</a>을 사용하여 판매 데이터 및 웹 사이트 사용량을 동일한 실시간 Power BI 대시보드로 끌어올 수 있습니다.</p>


  <p><img alt="Application Insights - Power BI" border="0" height="310" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/e020ef0e-4c0d-4a22-a10b-dcdb74aa745f.png" style="border-top: 0px; border-right: 0px; background-image: none; border-bottom: 0px; float: none; padding-top: 0px; padding-left: 0px; margin-left: auto; border-left: 0px; display: block; padding-right: 0px; margin-right: auto" title="애플리케이션 Insights - Power BI" width="640"></p>


  <h1>결론</h1>


  <p>애플리케이션 Insights 찾고 있던 강력한 애플리케이션 분석 솔루션으로 성장하고 있습니다. 서비스 문제를 효율적으로 검색, 심사 및 조사할 수 있는 강력한 로그 및 메트릭 분석과 함께 성능 및 예외 진단이 기본 제공되었습니다.</p>


  <p>고객 중 한 명이 Application Insights 대한 경험을 요약하는 방식을 좋아합니다.</p>


  <blockquote>

  <p>&quot;며칠 전, &#39;부&#39; 핫픽스를 배포했습니다. 광범위한 테스트 통과를 실행하지&#39;않았지만, 불행히도 일부 예기치 않은 변경이 페이로드에 병합되어 프런트 엔드와 백 엔드 간에 호환되지 않습니다. 즉시, 서버 예외 사항이 급증했고 경고가 발생했으며 상황을 인식하도록 했습니다. 애플리케이션 Insights 포털에서 몇 번의 클릭으로 문제를 좁힐 수 있는 예외 호출 스택에서 충분한 정보를 얻었습니다. 즉시 롤백하고 손상을 제한했습니다. 애플리케이션 Insights DevOps 주기의 이 부분을 매우 쉽고 실행 가능하게 만들었습니다.&quot;</p>

  </blockquote>


  <p>애플리케이션 Insights User Voice 페이지에서 새 기능 또는 향상된 기능에 대한 아이디어를 공유하세요. 궁금한 내용은 <a href="https://social.msdn.microsoft.com/Forums/vstudio/en-US/home?forum=ApplicationInsights">애플리케이션 Insights 포럼</a>을 방문하세요.</p>
