### YamlMime:Yaml
ms.openlocfilehash: 5a9e44b9b5e20c01f005cc65cd2b1889e187c6c6
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139899293"
Slug: deep-learning-simulation-and-hpc-applications-with-docker-and-azure-batch
Title: Docker 및 Azure Batch를 사용한 심층 Learning, 시뮬레이션 및 HPC 애플리케이션
Summary: Azure Big Compute 팀은 일괄 처리 스타일 Dockerized 워크로드를 Azure Batch 컴퓨팅 풀에 쉽게 배포할 수 있는 Batch Shipyard 도구 키트의 버전 1.0.0을 발표하게 되어 기쁩니다. Azure...
Content: >-
  <p>Azure Big Compute 팀은 일괄 처리 스타일 Dockerized 워크로드를 <a href="https://azure.microsoft.com/en-us/services/batch/">Azure</a> Batch 컴퓨팅 풀에 쉽게 배포할 수 있는 <a href="https://azure.github.io/batch-shipyard/">Batch Shipyard</a> 도구 키트의 버전 1.0.0을 발표하게 되어 기쁩니다. Azure Batch를 사용하면 인프라를 관리할 필요 없이 클라우드에서 병렬 작업을 실행할 수 있습니다. &rsquo;매개 변수 스윕, NVIDIA GPU를 사용한 심층 Learning 학습 및 MPI 및 InfiniBand를 사용하는 시뮬레이션에 이상적입니다.</p>


  <p>단일 컴퓨터에서 컨테이너화된 작업을 실행해야 하든 수백 또는 수천 대의 컴퓨터에서 컨테이너화된 작업을 실행해야 하든, Batch Shipyard는 대규모 VM 배포 및 관리의 복잡성, 높은 처리량, 고가용성 작업 예약 및 애플리케이션 패키징을 위한 Docker 컨테이너의 기능과 함께 사용하는 것에 대해서만 비용을 지불하기 위한 자동 크기 조정과 같은 Azure Batch의 기능을 혼합합니다.&nbsp;  Batch Shipyard를 사용하면 일괄 처리 스타일 및 HPC 컨테이너화된 워크로드에 대한 배포 일관성 및 격리를 활용하고 Azure Batch SDK에 직접 개발할 필요 없이 규모에 관계없이 실행할 수 있습니다.</p>


  <p>Batch Shipyard의 초기 릴리스에는 다음과 같은 주요 기능이 있습니다.</p>


  <ul>
   <li>Azure Batch 컴퓨팅 노드에 대해 조정된 자동화된 <a href="https://www.docker.com/">Docker 호스트 엔진</a> 설치</li>
   <li>컴퓨팅 노드에 필요한 Docker 이미지의 자동화된 배포</li>
   <li>컴퓨팅 노드 간에 Docker 이미지의 프라이빗 피어 투 피어 배포를 통해 많은 수의 VM으로 구성된 컴퓨팅 풀에 대규모로 가속화된 Docker 이미지 배포</li>
   <li>지정된 경우 Azure Storage 백업된 Docker 이미지를 사용하여 컴퓨팅 노드에서 자동화된 Docker Private Registry 인스턴스 만들기</li>
   <li>다음을 위한 자동 공유 데이터 볼륨 지원: <ul>
    <li>지정된 경우 Azure Storage 지원되는 SMB/CIFS에 대한 <a href="https://github.com/Azure/azurefile-dockervolumedriver">Azure 파일 Docker 볼륨 드라이버</a> 설치 및 공유 설정</li>
    <li><a href="https://www.gluster.org/">지정된 경우 GlusterFS</a> 분산 네트워크 파일 시스템 설치 및 설정</li>
   </ul>
   </li>
   <li>컴퓨팅 노드에서 실행되는 컨테이너에 대한 <a href="https://azure.microsoft.com/en-us/documentation/articles/batch-api-basics/">Azure Batch API</a> 의 전체 통과와 함께 Azure Batch 작업, 작업 및 파일 개념과 원활하게 통합</li>
   <li>Docker 컨테이너를 사용하여 복잡한 처리 파이프라인 및 그래프를 허용하는 <a href="https://azure.microsoft.com/en-us/documentation/articles/batch-task-dependencies/">Azure Batch 작업 종속성</a> 지원</li>
   <li><a href="https://azure.microsoft.com/en-us/blog/azure-n-series-preview-availability/">Azure N 시리즈 VM 인스턴스</a>에서 <a href="https://github.com/NVIDIA/nvidia-docker">GPU 가속 Docker 애플리케이션</a>에 대한 투명한 지원(<a href="https://gpu.azure.com/">미리 보기</a>)</li>
   <li>자동 작업 정리를 사용하여 컴퓨팅 풀에서 Dockerized MPI 및 다중 노드 클러스터 애플리케이션을 수용하기 위한 다중 인스턴스 작업 지원</li>
   <li><a href="https://azure.microsoft.com/en-us/documentation/articles/virtual-machines-windows-a8-a9-a10-a11-specs/">HPC 대기 시간이 짧은 Azure VM 인스턴스</a>(예: STANDARD_A8 및 STANDARD_A9)에서 MPI용 Infiniband/RDMA를 활용하는 Docker 컨테이너를 실행하기 위한 투명한 지원</li>
   <li>지정된 경우 컴퓨팅 노드의 Docker 호스트에 대한 SSH 터널링 자동 설정</li>
  </ul>


  <p>또한 Weve&rsquo;는 딥 Learning, CFD(Computational Fluid Dynamics), MD(분자 역학) 및 Batch Shipyard를 사용한 비디오 처리와 같은 시나리오를 가능하게 하는 <a href="https://github.com/Azure/batch-shipyard/tree/master/recipes">초기 레시피 집합</a>을 제공했습니다. 실제로 Azure Batch의 심층 Learning 쉽고 낮은 마찰 환경으로 만드는 것을 목표로 하고 있습니다. 도구 키트가 설치되고 Azure Batch 및 Azure Storage 자격 증명이 있으면 <a href="https://github.com/Azure/batch-shipyard/blob/master/docs/02-batch-shipyard-quickstart.md">15분 안에</a> Azure Batch 컴퓨팅 풀에서 실행되는 <a href="https://cntk.ai/">CNTK</a>, <a href="https://caffe.berkeleyvision.org/">Caffe</a> 또는 <a href="https://www.tensorflow.org/">TensorFlow</a>를 가져올 수 있습니다. 다음은 nvidia-smi가 있는 Batch Shipyard를 통해 GPU 지원 STANDARD_NC6 VM에서 실행되는 CNTK 스크린샷입니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/e9f6135b-83ad-41f2-b76b-16e735e290fa.png"><img alt="CNTK" border="0" height="489" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/a6c99e17-f9d8-42f8-98ea-520daeead6aa.png" style="border: 0px currentColor; border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; display: inline; background-image: none;" title="CNTK" width="529"></a></p>


  <p>앞으로도 Batch Shipyard에서 사용할 수 있는 레시피의 레퍼토리를 계속 확장할 수 있기를 바랍니다.</p>


  <p>Batch Shipyard 도구 키트는 <a href="https://github.com/Azure/batch-shipyard">GitHub</a> 찾을 수 있습니다. 우리는 어떤 피드백과 기여를 환영합니다!</p>
