### YamlMime:Yaml
ms.openlocfilehash: a84f1f3924aacb81213782b778981b5d48d87edc
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139899288"
Slug: deliver-ai-powered-application-search-with-azure-cognitive-search-and-ba-insight
Title: Azure Cognitive Search 및 BA Insight를 사용하여 AI 기반 애플리케이션 검색 제공
Summary: 데이터가 기하급수적으로 증가하고 있으며 데이터의 80% 이상이 구조화되지 않은 상태로 조직에서 고객에게 올바른 정보를 찾고 노출하는 데 어려움을 줍니다. 조직에 필요한 것은 관련 정보 및 의미 있는 패턴을 신속하게 식별하여 모든 콘텐츠에서 잠재 인사이트를 파악할 수 있는 솔루션입니다.
Content: >-
  <p>데이터가 기하급수적으로 증가하고 있으며 데이터의 80% 이상이 비정형<sup>1</sup>이므로 조직에서 고객에게 올바른 정보를 찾고 노출하는 데 어려움을 줍니다. 조직에 필요한 것은 관련 정보 및 의미 있는 패턴을 신속하게 식별하여 모든 콘텐츠에서 잠재 인사이트를 파악할 수 있는 솔루션입니다.</p>


  <p><a href="https://azure.microsoft.com/en-us/solutions/knowledge-mining/" target="_blank">지식 마이닝</a> 은 여러 AI 기능을 통합하여 개발자가 더 빠르게 인사이트를 얻을 수 있도록 하는 AI의 범주입니다. Azure Cognitive Search는 지식 마이닝 솔루션을 통해 대규모로 관련 콘텐츠를 쉽게 식별하고 탐색할 수 있습니다.</p>


  <p><a href="https://azure.microsoft.com/en-us/services/search/" target="_blank">Azure Cognitive Search</a>를 통해 클라우드 검색은 구조화되고 구조화되지 않은 콘텐츠의 수집, 보강 및 탐색을 통해 AI 기능을 포함하도록 발전했습니다. 개발자는 API 및 도구를 사용하여 웹, 모바일 및 엔터프라이즈 애플리케이션의 다양한 콘텐츠를 통해 풍부한 검색 환경을 제공하는 솔루션을 빌드할 수 있습니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/1c5f0527-800e-489b-b0aa-357805ff1a04.jpg"><img alt="Three phrases to Knowledge Minig with Cognitive Search: Ingest, Enrich, and Explore" border="0" height="380" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/3825d129-7b61-4af7-9e9e-6ea06c242b9c.png" style="border: 0px currentcolor; border-image: none; display: inline; background-image: none;" title="" width="1024"></a></p>


  <p>여러 산업의 고객은 Azure Cognitive Search를 활용하여 향상된 앱 검색 환경을 제공했습니다. <a href="https://channel9.msdn.com/Shows/AI-Show/Learn-how-Amway-is-using-Azure-Cognitive-Search-to-serve-better-and-faster-search-results-to-million" target="_blank">Amway</a> 는 Azure Cognitive Search를 사용하여 애플리케이션을 구동하고 판매자가 제품 정보를 더 잘 탐색하고 이해할 수 있도록 지원했습니다. 그 결과 판매자의 검색 시간이 크게 단축되어 매일 4배 더 많은 고객을 도울 수 있습니다. <a href="https://azure.microsoft.com/en-us/resources/videos/how-the-atlantic-is-preserving-published-history-with-azure-ai/" target="_blank">Atlantic은</a> Azure Cognitive Search를 활용하여 보관을 위한 디지털 시스템으로 전환했습니다. 이는 대서양의 작가들이 이야기의 바다에서 통찰력을 도출하고 과거와 현재 사이의 연결을 구축하는 데 도움이되었습니다.</p>


  <p><a href="https://customers.microsoft.com/en-IN/story/811347-pwc-partner-professional-services-azure" target="_blank">PwC</a>, <a href="https://customers.microsoft.com/en-us/story/archive360-partner-professional-services-azure-search" target="_blank">Archive360</a>, <a href="https://customers.microsoft.com/en-us/story/764974-wix-partner-professional-services-azure-cognitive-search" target="_blank">Wix</a> 및 <a href="https://customers.microsoft.com/en-IN/story/762687-royal-ihc-manufacturing-azure-cognitive-search" target="_blank">OrangeNXT</a>와 같은 수많은 파트너는 금융, 소매, 제조 및 기타 산업 전반에서 고객을 지원하기 위해 Azure Cognitive Search 기반 검색 솔루션을 구축했습니다.</p>


  <p>BA Insight는 Azure Cognitive Search 및 기타 Azure AI 서비스에서 제공하는 Workplace 솔루션에 <a href="https://www.bainsight.com/azure-search/" target="_blank">대한 Search</a> 를 빌드했습니다. 이를 통해 엔터프라이즈 사용자는 저장소별 정보 검색을 중지하고 정보가 어디에 있든 관계없이 모든 콘텐츠에서 사용자에게 정보를 제공할 수 있습니다. 사용자는 개인 설정된 정보에 대한 권장 사항을 받고 기본 제공 커넥터를 통해 콘텐츠 리포지토리, 애플리케이션 및 데이터베이스에 연결하거나 SDK를 통해 사용자 지정 커넥터를 만들 수 있습니다. 자동 분류자는 새 콘텐츠를 생성할 때 사용자에게 태그를 지정하는 부담을 제거하고 기존 콘텐츠에 정확하고 일관되게 태그를 지정합니다. 앱 내 검색 환경을 사용하면 사용자가 매일 사용하는 애플리케이션 내에서 검색을 수행하여 기존 작업 방식에 원활하게 통합할 수 있습니다.</p>


  <p>이 솔루션은 BA Insights&rsquo; Enterprise Search를 통해 클라우드 서비스로 또는 고객&rsquo; 환경 내에서 배포할 수 있습니다. Enterprise Search를 클라우드 서비스로 사용하면 조직은 사용자 지정 개발의 부담을 덜어주는 고도로 개인화되고 지능적이며 관련 있는 사용자 환경을&mdash; 제공하는 완전 관리형 엔터프라이즈 검색 배포를 활용할 수 있습니다. Microsoft Teams, Microsoft Dynamics, Microsoft Exchange, Microsoft Outlook, Salesforce, Microsoft Edge 및 ServiceNow와 같은 애플리케이션과 통합됩니다.</p>


  <p>최근 BA Insight 회장 겸 CEO인 Massood Zarrabian과 Azure Cognitive Search의 수석 프로그램 관리자인 Liam Cavanagh는 작업 공간 검색 솔루션에 대해 대화를 나섰습니다. <a href="https://azure.microsoft.com/en-us/resources/videos/azure-cognitive-search-x-ba-insight-joint-podcast" target="_blank">이 팟캐스트를 시청하고 자세히 알아보세요</a>.</p>


  <p>BA Insight에는 BA Insight<a href="https://www.bainsight.com/whats-possible/" target="_blank">에서 제공하는 Art of Possible</a> 제품을 활용하여 솔루션이 콘텐츠와 어떻게 작동하는지에 대한 실제&rdquo; 보기를 얻고&ldquo;, 검색 전략 세션에 참여하여 현재 환경 및 과제를 논의하고, 사용자의 선택 팀에 대한 테스트를 직접 수행할 수 있는 특별한 제안이&mdash; 있습니다.</p>


  <h2>추가 리소스</h2>


  <ul>
      <li><a href="https://www.bainsight.com/azure-search/" target="_blank">작업 공간에 대한 BA Insight Search</a>.&nbsp;</li>
      <li><a href="https://azure.microsoft.com/en-us/free/cognitive-search/">Azure Cognitive Search 무료 평가판에 등록</a>합니다.</li>
      <li><a href="https://www.bainsight.com/resources/">BA Insight 리소스.</a></li>
  </ul>


  <p>&nbsp;</p>


  <p><sup>1</sup> <a href="https://azure.microsoft.com/en-us/resources/knowledge-mining-the-next-wave-of-artificial-intelligence-led-transformation/">지식 마이닝: 인공 Intelligence-Led 변환의 다음 물결</a></p>


  <ul>

  </ul>
