### YamlMime:Yaml
ms.openlocfilehash: 15ef393af8622c9fdd0060db6e9f2532e1a11e69
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139907220"
Slug: dependency-call-stack-and-application-insights-sdk-labs
Title: 종속성 호출 스택 및 애플리케이션 Insights SDK 랩
Summary: Visual Studio Application Insights 수집된 모든 종속성 호출에 대한 스택을 추적하기 위한 실험적 패키지를 릴리스했습니다. 이 프로젝트는 .NET용 Application Insights SDK를 확장하여 수집된 모든 종속성에 대한 호출 스택 정보를 제공합니다.
Content: >-
  <a href="https://azure.microsoft.com/services/application-insights/">Visual Studio Application</a> Insights 수집된 모든 종속성 호출에 대한 스택을 추적하는 실험적 패키지를 릴리스했습니다. <a href="https://azure.microsoft.com/documentation/articles/app-insights-start-monitoring-app-health-usage/">.NET용 기존 SDK</a>를 사용하면 앱에서 데이터베이스 또는 REST API와 같은 외부 종속성으로의 호출을 추적하고 느리거나 실패한 호출을 찾을 수 있습니다. 그러나 현재 SDK를 사용하면 앱에서 호출한 함수를 쉽게 찾을 수 없습니다. 실험적 패키지인 NuGet 이 문제를 해결합니다. 이 프로젝트는 .NET용 Application Insights SDK를 확장하여 수집된 모든 종속성에 대한 호출 스택 정보를 제공합니다.

  <h2><img style="background-image: none; float: none; padding-top: 0px; padding-left: 0px; margin: 0px auto; display: block; padding-right: 0px; border-width: 0px;" title="010" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/010.png" alt="010" width="323" height="337" border="0" />

  요구 사항</h2>

  <ul>
   <li>ASP.NET 웹 애플리케이션 프로젝트</li>
   <li>프로젝트에 설치된 <a href="https://www.nuget.org/packages/Microsoft.ApplicationInsights.Web/">.NET 웹 애플리케이션용 애플리케이션 Insights SDK</a>(Visual Studio 사용하여 프로젝트에 애플리케이션 Insights 추가하는 경우 가져오는 SDK)</li>
  </ul>

  SDK는 각 종속성 원격 분석 데이터 요소에 하나의 사용자 지정 속성을 추가합니다.

  <h2>설치</h2>

  종속성 호출 스택 패키지는 새 SDK Labs NuGet 갤러리에서 호스트됩니다. Visual Studio 사용하여 프로젝트에서 NuGet 패키지를 관리하는 경우 수행할 일은 다음과 같습니다.

  <ol>
   <li><a href="https://www.myget.org/gallery/applicationinsights-sdk-labs">애플리케이션 Insights SDK Labs</a> 패키지 원본을 NuGet 추가합니다.
  소스: <a href="https://www.myget.org/F/applicationinsights-sdk-labs/">https://www.myget.org/F/applicationinsights-sdk-labs/</a><img style="background-image: none; float: none; padding-top: 0px; padding-left: 0px; margin: 0px auto; display: block; padding-right: 0px; border-width: 0px;" title="nuget" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/nuget.png" alt="nuget" width="606" height="610" border="0" /></li>
   <li>프로젝트에 시험판 패키지 Microsoft.ApplicationInsights.DependencyCallstacks를 추가합니다. 시험판 패키지를 포함해야 합니다.<img style="background-image: none; float: none; padding-top: 0px; padding-left: 0px; margin: 0px auto; display: block; padding-right: 0px; border-width: 0px;" title="020" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/020.png" alt="020" width="610" height="191" border="0" /></li>
   <li>정말 간단하죠. 앱을 다시 빌드하고 실행합니다.</li>
  </ol>

  <strong>명령줄 패키지 관리자를 사용하는 경우</strong> 다음이 필요합니다.

  <pre class="prettyprint">&gt; Install-Package "Microsoft.ApplicationInsights.DependencyCallstacks" -Source "https://www.myget.org/F/applicationinsights-sdk-labs/" -Pre</pre>

  <h2>호출 스택 보기</h2>

  이 실험을 사용하면 이 새 데이터를 지원하도록 Azure Portal의 환경이 변경됩니다. 애플리케이션 Insights 관련 종속성이 있는 요청을 보면 이제 종속성 간의 관계를 보여 주는 보기가 표시됩니다.


  이 새 보기에서 종속성을 클릭하여 종속성 세부 정보 블레이드를 표시합니다. 이제 사용 가능한 경우 클래스 및 함수 이름뿐만 아니라 파일 이름 및 줄 번호가 포함된 호출 스택 섹션이 포함됩니다.


  <img style="background-image: none; float: none; padding-top: 0px; padding-left: 0px; margin: 0px auto; display: block; padding-right: 0px; border-width: 0px;" title="osvaldo" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/osvaldo.png" alt="osvaldo" width="610" height="420" border="0" />


  &nbsp;


  이 실험적 환경 가져오기를 중지하려면 프로젝트에서 패키지를 제거합니다. 프로젝트에서 패키지를 제거하면 모든 새 요청이 Azure Portal의 기본 UI에 표시됩니다. 패키지를 설치할 때 수행한 이전 요청은 위의 보기에 계속 표시됩니다.

  <h2>현재 제한 사항</h2>

  <ul>
   <li>일부 비동기적으로 호출된 종속성에는 호출 스택 정보가 수집되지 않을 수 있습니다.</li>
   <li>호출 스택의 "내 코드만" 버전만 수집됩니다.</li>
  </ul>

  <h2>SDK Labs 정보</h2>

  이 프로젝트를 통해 Application Insights SDK Labs의 개념을 소개합니다. 이 프로젝트는 <a href="https://github.com/Microsoft/ApplicationInsights-SDK-Labs">GitHub 오픈 소스</a>이며 <a href="https://www.myget.org/gallery/applicationinsights-sdk-labs">MyGet</a> 갤러리에서 릴리스됩니다.

  <h3>우리의 전략:</h3>

  <ol>
   <li>모든 실험 프로젝트는 독립 실행형 NuGet 패키지입니다.</li>
   <li>전용 <a href="https://myget.org/">MyGet</a> 피드에 프로젝트를 게시합니다.</li>
   <li>실험적 기능을 사용하여 다운로드 및 참여 고객 수를 모니터링합니다.</li>
   <li>실험이 성공했는지 여부를 결정합니다. 도움이 되지 않는 경우 이 프로젝트를 중단하고 리포지토리에서 제거합니다.</li>
   <li>성공적인 프로젝트를 자체 리포지토리 또는 Application Insights SDK로 승격합니다.</li>
  </ol>

  <h2>요약</h2>

  이 프로젝트는 몇 가지 추가 진단 시나리오를 사용하도록 설정합니다. 더 자세한 정보를 제공하고 기존 기능의 기능을 늘려 애플리케이션 Insights 향상시킵니다. 우리는이 추가가 매우 유용 할 것이라고 생각합니다. 패키지는 인턴 프로젝트로 만들어졌으며 SDK에 기본값을 포함할 수 있도록 관심을 얻을 수 있기를 바랍니다.


  GitHub 대한 피드백을 제공하여 이 기능을 평가할 수 있도록 도와주세요.<a href="https://github.com/Microsoft/ApplicationInsights-SDK-Labs">https://github.com/Microsoft/ApplicationInsights-SDK-Labs</a>


  더 많은 기능을 원하십니까? <a href="https://github.com/Microsoft/ApplicationInsights-Home">저희에게 물어보세요</a>.

  <h2>크레딧</h2>

  나는이 블로그 게시물을 준비하기위한이 패키지, <a href="https://github.com/OsvaldoRosado">오스발도 로사도</a> 의 저자에게 감사드립니다.
