### YamlMime:Yaml
ms.openlocfilehash: 2ff6521db6bc190dd78b616557ae23310ffc1a8f
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139906826"
Slug: design-azure-infrastructure-services-to-host-a-multi-tier-lob-application
Title: 다중 계층 LOB 애플리케이션을 호스트하도록 Azure 인프라 서비스 디자인
Summary: 디자인 방법을 사용하여 Azure 인프라 서비스의 네트워킹, 스토리지 및 컴퓨팅 요소에 대해 가상 머신에서 실행되는 다중 계층 비즈니스 애플리케이션을 조정합니다.
Content: >-
  <p>Azure에서 다중 계층 LOB(기간 업무) 애플리케이션을 가상 머신으로 배포하는 것은 다음의 조합입니다.</p>


  <ul>
   <li>
   <p>이미 알고 있는 것은 로컬 데이터 센터에서 서버 및 전체 애플리케이션을 구성하는 방법입니다.</p>
   </li>
   <li>
   <p>아직 알 수 없는 것은 Azure 인프라 서비스의 네트워킹, 스토리지 및 컴퓨팅 요소에 맞게 애플리케이션을 조정하고 디자인하는 방법입니다.</p>
   </li>
  </ul>


  <p>아직 알 수 없는 사항을 돕기 위해 다음을 통합하는 디자인 방법을 단계별로 실행할 수 있습니다.</p>


  <ol>
   <li>리소스 그룹</li>
   <li>연결</li>
   <li>스토리지</li>
   <li>ID</li>
   <li>보안</li>
   <li>가상 머신</li>
  </ol>


  <p>이 디자인 방법론을 이해하고 사용자 고유의 LOB 애플리케이션에 사용하려면 <a href="https://techcommunity.microsoft.com/t5/CAAB-Cloud-Adoption-Advisory/EXTRA-November-2016-Webinar/m-p/30058#M41"><u>AZURE IaaS 비디오에서 LOB 애플리케이션 빌드 및</u></a> CAAB(클라우드 채택 자문 위원회)에 대한 2016년 11월 웨비나의 슬라이드 데크를 &nbsp;참조&nbsp;하세요.</p>


  <p><img height="456" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/3b1d1b54-6fc0-4a0e-9d22-d86db6da9b94.png" style="width: 532px; height: 287px;" width="816"></p>


  <p>웨비나 비디오에는 다음 섹션이 있습니다.</p>


  <ul>
   <li>정의 및 가정(3:12부터 시작)</li>
   <li>디자인 프로세스(8:05에 시작)</li>
   <li>디자인 예제(38:50부터 시작)</li>
   <li>Azure PowerShell 사용하여 빌드(50:30에 시작)</li>
  </ul>


  <p><a href="https://docs.microsoft.com/azure/guidance/guidance-architecture"><u>Azure 패턴 및 Practicesrecommendations</u></a>&nbsp; 및 모범 사례를 통합&nbsp;하는 디자인 프로세스의 결과는 가상 머신 및 해당 Azure 인프라 관련 설정의 테이블입니다. 다음은 예제입니다.</p>


  <p><img src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/e7024566-bc1b-4a90-ae7b-a43849589a6f.png"></p>


  <p>테이블 항목을 결정한 후에는 요소를 빌드하고 모든 Azure 인프라 설정을 올바르게 만드는 것이&rsquo; 훨씬 쉽습니다. 예를 들어 테이블과 PowerShell 명령 블록을 사용하여 가상 네트워크 및 해당 서브넷을 만드는 방법은 다음과 같습니다.</p>


  <p><img src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/0b46beb2-d0db-42a4-b272-3af217f43ff1.png"></p>


  <p>또한 테이블과 PowerShell 명령 블록을 사용하여 가상 머신을 만드는 방법은 다음과 같습니다.</p>


  <p><img src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/5a710c04-5a79-40a4-96c3-78ca4bf21d0e.png"></p>


  <p><a href="https://onedrive.live.com/download.aspx?cid=6b7cf2bd5f47f487&amp;id=documents&amp;resid=6B7CF2BD5F47F487%212825&amp;authkey=AFRK6VNhGGpbLaI"><u>슬라이드 데크</u></a>에는 웨비나에서 다루지 않은 다음과 같은 부록이 있습니다.</p>


  <ul>
   <li><strong>PowerShell 명령 블록</strong>&nbsp;&nbsp; 각 슬라이드는 Azure 인프라 서비스의 요소를 빌드하기 위한 Azure PowerShell 명령의 빈 채우기 집합입니다.</li>
   <li><strong>명명 규칙</strong>&nbsp;&nbsp; 디자인 Azure 인프라 요소의 이름을 지정하는 방법을 결정하는 팁.</li>
  </ul>


  <p>Azure 인프라 서비스에서 호스트되는 LOB 애플리케이션을 가속화하고 성공적으로 배포하려면 이 디자인 방법론을 사용합니다.</p>


  <p>&nbsp;</p>
