### YamlMime:Yaml
ms.openlocfilehash: c64a3c38f08d631b14c31001d7dcdd2bfa86de66
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139901706"
Slug: dev-test-starts-with-it-how-to-resource-vms-for-your-dev-test-environment
Title: 'IT로 시작하는 Dev-Test: 개발 테스트 환경에 VM을 리소스하는 방법'
Summary: Azure VM(Virtual Machines)은 클라우드에서 개발 테스트 기능 탐색을 시작하기에 좋은 장소입니다.
Content: >-
  <p><em>개발자&rsquo;의 65%는 개발 테스트 리소스를 얻기에는 너무 복잡하고 시간이 많이 소요됩니다.* 그럴 필요는 없습니다&rsquo;.</em></p>


  <p><em>이 블로그 시리즈에서는 Microsoft 클라우드의 도움을 받아 개발 테스트 환경을 설정하는 방법에 대한 지침을 제공하므로 몇 시간 또는 며칠이 아닌 몇 분 &mdash; 안에 개발 테스트를 최대한 활용할 수 있습니다.</em></p>


  <p><br>

  <a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/46cb9d84-ab6c-473a-a120-fb1ad66b4092.jpg"><img alt="IaaS_BlogSeries" border="0" height="143" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/c76a2a5b-1b53-4e25-83c7-b43016f0c722.jpg" style="border: 0px currentColor; border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; display: inline; background-image: none;" title="IaaS_BlogSeries" width="250"></a><br>

  <br>

  Azure VM(Virtual Machines)은 클라우드에서 개발 테스트 기능 탐색을 시작하기에 좋은 장소입니다. 개발 그룹은 종종 VM을 빠르고 쉬운 방법으로 사용하여 앱을 코딩하고 테스트하는 데 필요한 특정 구성으로 환경을 만듭니다. Azure는 VM을 만들고 사용한 다음 더 이상 필요하지 않은 경우&rsquo; 삭제하는 간단하고 경제적인 방법을 제공합니다. Azure Portal을 통해 주문형 컴퓨팅 솔루션을 위해 Windows 및 Linux를 비롯한 광범위한 VM을 신속하게 구성하고 배포할 수 있습니다. <a href="https://azure.microsoft.com/en-us/documentation/articles/virtual-machines-about/?wt.mc_id=WW_CE_IAAS_OO_BLOG_NONE">Azure VM을 사용하는 방법에 대해 자세히 알아봅니다</a>.</p>


  <p>&rsquo;개발 테스트 환경을 시작하기 위해 많은 수의 VM을 쉽게 스핀업할 수 있습니다. 이 <a href="https://azure.microsoft.com/en-us/get-started/?wt.mc_id=WW_CE_IAAS_OO_BLOG_NONE">짧은 비디오를</a> 시청하고 단계별 자습서를 검토하여 몇 분 만에 <a href="https://azure.microsoft.com/en-us/documentation/articles/virtual-machines-windows-tutorial/?wt.mc_id=WW_CE_IAAS_OO_BLOG_NONE">Windows VM</a> 또는 <a href="https://azure.microsoft.com/en-us/documentation/articles/virtual-machines-linux-tutorial-portal-rm/?wt.mc_id=WW_CE_IAAS_OO_BLOG_NONE">Linux VM</a>을 만듭니다. 자세한 내용은 <a href="https://azure.microsoft.com/en-us/documentation/articles/virtual-machines-questions/?wt.mc_id=WW_CE_IAAS_OO_BLOG_NONE">이러한 질문과 대답을</a> 살펴보세요.</p>


  <p>Azure Resource Manager는 Azure에서 컴퓨팅, 네트워크 및 스토리지 리소스를 그룹으로 배포하고 관리하는 데 도움이 되는 미리 빌드된 애플리케이션 템플릿을 제공합니다. Resource Manager 템플릿을 사용하면 복잡한 애플리케이션을 빠르게 배포할 수 있습니다. <a href="https://azure.microsoft.com/en-us/documentation/articles/virtual-machines-deploy-rmtemplates-powershell/?wt.mc_id=WW_CE_IAAS_OO_BLOG_NONE">Windows</a> 및 <a href="https://azure.microsoft.com/en-us/documentation/articles/virtual-machines-deploy-rmtemplates-azure-cli/?wt.mc_id=WW_CE_IAAS_OO_BLOG_NONE">Linux</a> 개발 테스트 환경에 대한 단계를 참조하세요.</p>


  <p>Azure에서 <em>개발 테스트</em> 환경을 만드는 방법에 대한 IT 시리즈의 개발 테스트 시작에서 다음 게시물을 찾습니다.</p>


  <p><a href="https://azure.microsoft.com/en-us/pricing/free-trial/?wt.mc_id=WW_CE_IAAS_OO_BLOG_NONE">무료 Azure 평가판을 시작합니다.</a></p>


  <p><a href="https://azure.microsoft.com/en-us/solutions/dev-test/?wt.mc_id=WW_CE_IAAS_OO_BLOG_NONE">Azure에서 개발 테스트에 대해 자세히 알아봅니다.</a></p>


  <p><br>

  *출처: 테스트 환경 관리 백서에 대한 비즈니스 사례, Cognizant</p>
