### YamlMime:Yaml
ms.openlocfilehash: d6bcc1816e1c6236f82f4123ceb03b17178cd149
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139901713"
Slug: dev-test-starts-with-it-create-simple-cloud-only-dev-test-configurations-using-resource-manager-templates
Title: 'Dev-Test IT 시작: Resource Manager 템플릿을 사용하여 간단한 클라우드 전용 개발 테스트 구성 만들기'
Summary: Azure를 사용하면 애플리케이션 및 모든 구성 요소(웹앱, 데이터베이스, 데이터베이스 서버, 스토리지 및 타사 서비스)에 대한 개발 테스트 환경을 쉽게 설정할 수 있습니다. Azure Resource Manager를 사용하면 모든 앱 리소스 및 서비스의 배포 및 관리를 간소화할 수 있습니다.
Content: >-
  <p><em></em><em>개발자&rsquo;의 65%는 개발 테스트 리소스를 얻기에는 너무 복잡하고 시간이 많이 소요됩니다.* 그렇게 할 필요는 없습니다&rsquo;.</em></p>


  <p><em>이 블로그 시리즈에서는 Microsoft 클라우드의 도움을 받아 개발 테스트 환경을 설정하는 방법에 대한 지침을 제공하므로 몇 시간 또는 며칠 동안 개발 테스트를&mdash; 최대한 활용합니다.</em></p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/9073a6a5-14b2-44b0-a9cb-5809b3f247aa.jpg"><img alt="IaaS_BlogThumb_250x143" border="0" height="137" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/7409c381-c525-47b5-bd54-7b9bc3be5fc6.jpg" style="border-top: 0px; border-right: 0px; background-image: none; border-bottom: 0px; padding-top: 0px; padding-left: 0px; border-left: 0px; display: inline; padding-right: 0px" title="IaaS_BlogThumb_250x143" width="240"></a></p>


  <p>Azure를 사용하면 애플리케이션 및 모든 구성 요소(웹앱, 데이터베이스, 데이터베이스 서버, 스토리지 및 타사 서비스)에 대한 개발 테스트 환경을 쉽게 설정할 수 있습니다(Azure에서 자체 개발 테스트 환경을 만드는 데 대한 리소스에 대한 <a href="https://azure.microsoft.com/en-us/blog/dev-test-starts-with-it-how-to-resource-vms-for-your-dev-test-environment/?wt.mc_id=WW_CE_IAAS_OO_BLOG_NONE">이전 블로그 게시물 참조</a> ). <a href="https://azure.microsoft.com/en-us/documentation/articles/resource-group-overview/?wt.mc_id=WW_CE_IAAS_OO_BLOG_NONE">Azure Resource Manager</a> 를 사용하면 모든 앱 리소스 및 서비스의 배포 및 관리를 간소화할 수 있습니다.</p>


  <p>Resource Manager를 사용하면 서비스 및 리소스를 개별적으로 처리하는 대신 리소스 그룹에서 앱의 구성 요소를 배포, 관리 및 모니터링할 수 있습니다. 리소스 그룹을 만든 다음 리소스를 다른 그룹으로 이동하고 기존 그룹에 새 리소스를 추가할 수 있습니다.</p>


  <p>Resource Manager 템플릿을 사용하여 다음과 같은 클라우드 전용 개발 테스트 구성을 포함하여 새 리소스 그룹 또는 기존 리소스 그룹 내에서 <a href="https://azure.microsoft.com/en-us/documentation/articles/resource-group-template-deploy/?wt.mc_id=WW_CE_IAAS_OO_BLOG_NONE">앱을 신속하게 배포</a> 할 수도 있습니다.</p>


  <ul>
   <li><a href="https://azure.microsoft.com/en-us/documentation/articles/virtual-machines-workload-template-ad-domain/?wt.mc_id=WW_CE_IAAS_OO_BLOG_NONE">Active Directory 도메인 컨트롤러</a>, 고가용성 2 서버 Active Directory Domain Services 도메인 구성</li>
   <li><a href="https://azure.microsoft.com/en-us/documentation/articles/virtual-machines-workload-template-sharepoint/?wt.mc_id=WW_CE_IAAS_OO_BLOG_NONE">SharePoint Server 2013, 3</a>개 서버 또는 9개 서버 SharePoint 팜</li>
   <li><a href="https://azure.microsoft.com/en-us/documentation/articles/virtual-machines-workload-template-sql-alwayson/?wt.mc_id=WW_CE_IAAS_OO_BLOG_NONE">SQL Server AlwaysOn</a>, 가용성 그룹 구성이 포함된 5개 서버 SQL Server AlwaysOn</li>
   <li><a href="https://azure.microsoft.com/en-us/documentation/articles/virtual-machines-workload-template-wordpress/?wt.mc_id=WW_CE_IAAS_OO_BLOG_NONE">WordPress Server</a>, Ubuntu에서 실행되는 WordPress 서버</li>
  </ul>


  <p>이는 <a href="https://azure.microsoft.com/en-us/documentation/articles/resource-group-authoring-templates/?wt.mc_id=WW_CE_IAAS_OO_BLOG_NONE">직접 작성</a>하기 전에 Resource Manager 템플릿을 탐색하는 데 유용한 시작점입니다.</p>


  <p><a href="https://azure.microsoft.com/en-us/campaigns/dev-test-starts-with-it-webinar-series/?wt.mc_id=WW_CE_IAAS_OO_BLOG_NONE">IT 웹 세미나를 사용하여 예정된 개발 테스트에 참석하세요</a>.<br>

  <a href="https://azure.microsoft.com/en-us/solutions/dev-test/?wt.mc_id=WW_CE_IAAS_OO_BLOG_NONE">Azure의 개발 테스트에 대해 자세히 알아봅니다</a>.</p>


  <p><br>

  *출처: 테스트 환경 관리 백서에 대한 비즈니스 사례, 인식</p>
