### YamlMime:Yaml
ms.openlocfilehash: 1392d6a91877a1aff1b72494bef5c0cac3fd8866
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139901711"
Slug: dev-test-starts-with-it-how-to-create-a-dev-test-environment-in-azure
Title: 'Dev-Test IT 시작: Azure에서 개발 테스트 환경을 만드는 방법'
Summary: 개발 테스트 환경을 만드는 프로세스를 가속화하는 더 간단한 방법이 있습니다. Azure를 사용하면 사용자 고유의 개발 테스트 환경을 만드는 첫 번째 단계인 가상 머신을 쉽게 만들고 함께 네트워크로 연결할 수 있습니다.
Content: >-
  <p><em>개발자&rsquo;의 65%는 개발 테스트 리소스를 얻기에는 너무 복잡하고 시간이 많이 소요됩니다.* 그럴 필요는 없습니다&rsquo;. </em></p>


  <p><em>이 블로그 시리즈에서는 몇 시간 또는 며칠 이내에 개발 테스트를 최대한 활용할 수 있도록 Microsoft 클라우드의 도움을 받아 개발 테스트&mdash; 환경을 설정하는 방법에 대한 지침을 제공합니다.</em></p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/0186c362-e22b-4a33-b647-08e1d820271a.jpg"><img alt="IaaS_BlogSeries" border="0" height="143" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/d4d4e919-e98e-4809-8049-6e32b6c606c6.jpg" style="border: 0px currentColor; border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; display: inline; background-image: none;" title="IaaS_BlogSeries" width="250"></a></p>


  <p>&rsquo;개발 테스트 환경을 만드는 프로세스를 가속화하는 간단한 방법이 있습니다. Azure를 사용하면 가상 머신을 쉽게 만들고( <a href="https://azure.microsoft.com/en-us/blog/dev-test-starts-with-it-how-to-resource-vms-for-your-dev-test-environment?wt.mc_id=WW_CE_IAAS_OO_BLOG_NONE" target="_blank">Azure VM을 구성하고 배포하는 데 도움이 되는 리소스</a>에 대한 이전 게시물 참조) 자체 개발 테스트 환경을 만드는 첫 번째 단계와 함께&mdash; 네트워크를 형성할 수 있습니다.</p>


  <p>첫 번째 단계로 클라우드 전용 가상 네트워크를 만든 다음(단계별 지침에 따라 <a href="https://azure.microsoft.com/en-us/documentation/articles/virtual-networks-create-a-vnet/?wt.mc_id=WW_CE_IAAS_OO_BLOG_NONE" target="_blank">가상 네트워크를 만들기</a>) VM을 추가할 수 있습니다. 클라우드 전용 가상 네트워크는 온-프레미스 네트워크에 다시 연결되지 않습니다. 인터넷에 연결된 간소화된 온-프레미스 네트워크를 만들려면 <a href="https://azure.microsoft.com/en-us/documentation/articles/virtual-machines-base-configuration-test-environment/?wt.mc_id=WW_CE_IAAS_OO_BLOG_NONE" target="_blank">기본 구성 테스트 환경을 참조하세요</a>.</p>


  <p>다음 단계로 온-프레미스 네트워크에 연결하고 확장하는 프레미스 간 가상 네트워크를 만들 수 있습니다. <a href="https://azure.microsoft.com/en-us/documentation/articles/virtual-networks-setup-hybrid-cloud-environment-testing/?wt.mc_id=WW_CE_IAAS_OO_BLOG_NONE" target="_blank">하이브리드 클라우드 환경을 설정</a>하여 개발 테스트를 위한 실제 하이브리드 환경을 시뮬레이션할 수 있습니다. 아직도 호기심이 있으시나요? <a href="https://azure.microsoft.com/en-us/documentation/articles/virtual-machines-hybrid-cloud-test-environments/?wt.mc_id=WW_CE_IAAS_OO_BLOG_NONE" target="_blank">Azure 하이브리드 클라우드 테스트 환경에 대해 자세히 알아봅니다</a>.</p>


  <p><a href="https://azure.microsoft.com/en-us/documentation/articles/virtual-networks-overview/?wt.mc_id=WW_CE_IAAS_OO_BLOG_NONE" target="_blank">VNet에 대해 자세히 알아보</a> 고 많은 네트워킹 기본 사항을 다루는 질문과 <a href="https://azure.microsoft.com/en-us/documentation/articles/virtual-networks-faq/?wt.mc_id=WW_CE_IAAS_OO_BLOG_NONE" target="_blank">대답</a> 을 살펴봅니다.</p>


  <p>테스트용 하이브리드 환경을 설정하는 방법에 대한 <em>IT 시리즈의 개발-테스트 시작</em> 에서 다음 게시물을 찾습니다.<br>

  &nbsp;</p>


  <p><a href="https://azure.microsoft.com/en-us/pricing/free-trial/?wt.mc_id=WW_CE_IAAS_OO_BLOG_NONE" target="_blank">Azure 평가판을 시작합니다</a>.<br>

  <a href="https://azure.microsoft.com/en-us/solutions/dev-test/?wt.mc_id=WW_CE_IAAS_OO_BLOG_NONE" target="_blank">Azure에서 개발 테스트에 대해 자세히 알아봅니다</a>.</p>


  <p><br>

  *출처: 테스트 환경 관리 백서에 대한 비즈니스 사례, Cognizant</p>
