### YamlMime:Yaml
ms.openlocfilehash: 7405e92d0213fe96764d35d606f4d2a4f01d7b5c
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139912990"
Slug: dev-test-starts-with-it-set-up-a-hybrid-cloud-environment-for-testing
Title: 'Dev-Test IT 시작: 테스트를 위한 하이브리드 클라우드 환경 설정'
Summary: 프로덕션을 모방하는 개발 테스트 환경을 만드는 경우 특히 하이브리드 애플리케이션 및 워크로드의 경우 확장성 및 복잡성으로 인해 종종 문제가 발생합니다. Azure를 사용하면 온-프레미스 네트워크에 연결하고 확장하는 프레미스 간 가상 네트워크를 쉽게 만들 수 있습니다.
Content: >-
  <p><em>개발자&rsquo;의 65%는 개발 테스트 리소스를 얻기에는 너무 복잡하고 시간이 많이 소요됩니다.* 그럴 필요는 없습니다&rsquo;. </em></p>


  <p><em>이 블로그 시리즈에서는 몇 시간 또는 며칠 만에 개발 테스트를 최대한 활용할 수 있도록 Microsoft 클라우드의 도움을 받아 개발 테스트&mdash; 환경을 설정하는 방법에 대한 지침을 제공합니다.</em></p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/d7ed6200-a490-4f8e-a7bf-b43d685c4926.jpg"><img alt="IaaS_BlogSeries" border="0" height="143" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/694f926d-a3a1-42da-bcd4-4e42c5bb46b0.jpg" style="border-top: 0px; border-right: 0px; background-image: none; border-bottom: 0px; padding-top: 0px; padding-left: 0px; border-left: 0px; display: inline; padding-right: 0px" title="IaaS_BlogSeries" width="250"></a></p>


  <p>프로덕션을 모방하는 개발 테스트 환경을 만드는 경우 특히 하이브리드 애플리케이션 및 워크로드의 경우 확장성 및 복잡성으로 인해 종종 문제가 발생합니다.&nbsp;</p>


  <p>Azure를 사용하면 온-프레미스 네트워크에 연결하고 확장하는 프레미스 간 가상 네트워크를 쉽게 만들 수 있습니다( <a href="https://azure.microsoft.com/en-us/blog/dev-test-starts-with-it-how-to-create-a-dev-test-environment-in-azure?wt.mc_id=WW_CE_IAAS_OO_BLOG_NONE" target="_blank">클라우드 전용 가상 네트워크를 만드는 데 도움이 되는 리소스</a>에 대한 이전 블로그 항목 참조).</p>


  <p>Azure는 만들 수 있는 <a href="https://azure.microsoft.com/en-us/blog/new-set-of-hybrid-cloud-test-environments/?wt.mc_id=WW_CE_IAAS_OO_BLOG_NONE" target="_blank">새로운 하이브리드 클라우드 테스트 환경 집합</a> 을 제공합니다. 테스트를 위한 하이브리드 클라우드 환경을 설정하는 단계별 지침에 따라 Azure에서 개발 테스트를 <a href="https://azure.microsoft.com/en-us/documentation/articles/virtual-networks-setup-hybrid-cloud-environment-testing/?wt.mc_id=WW_CE_IAAS_OO_BLOG_NONE" target="_blank">위한 실제 하이브리드 프로덕션 환경을</a> 시뮬레이션할 수 있습니다. 하이브리드 환경은 로컬 인터넷 연결 및 공용 IP 주소 중 하나를 사용하여 작동하는 프레미스 간 Azure 가상 네트워크를 설정합니다. 단일 Hyper-V 또는 다른 가상화 서버에서 호스트할 수 있는 격리된 서브넷에 세 대의 컴퓨터를 사용하여 이 구성의 간소화된 인트라넷 부분을 만듭니다.</p>


  <p>이 기본 구성을 확장하거나 조정하여 하이브리드 클라우드 기반 IT 워크로드에 대한 개발 테스트 환경 또는 개념 증명 구성을 만들 수 있습니다. 이는 Azure 기능을 실험하고, 애플리케이션 개발 및 테스트를 수행하고, 간소화된 IT 워크로드를 실험하고, 인터넷에서 사용자의 위치를 기준으로 사이트 간 VPN 연결의 성능을 측정하는 좋은 방법입니다.</p>


  <p>직접 인터넷 연결이나 사용 가능한 공용 IP 주소가 없는 경우 <a href="https://azure.microsoft.com/en-us/blog/simulated-hybrid-cloud-test-environment/?wt.mc_id=WW_CE_IAAS_OO_BLOG_NONE" target="_blank">시뮬레이션된 하이브리드 클라우드를</a> 만들 수도 있습니다. 다음 단계별 지침에 따라 <a href="https://azure.microsoft.com/en-us/documentation/articles/virtual-networks-setup-simulated-hybrid-cloud-environment-testing/?wt.mc_id=WW_CE_IAAS_OO_BLOG_NONE" target="_blank">테스트를 위해 시뮬레이션된 하이브리드 클라우드 환경을 설정합니다</a>. 이 구성에서는 Azure 인프라 구성 요소만 사용하여 추가 Azure VNet(가상 네트워크)에서 간소화된 인트라넷을 만든 다음 VNet 간 연결로 이 두 가지를 연결합니다. 이 구성은 진정한 크로스-프레미스 가상 네트워크의 환경을 제공하지는 않지만 개발 테스트 기능을 수행하고 간소화된 IT 워크로드를 실행하는 데 계속 사용할 수 있습니다.</p>


  <p>테스트를 위해 하이브리드 클라우드에서 SharePoint 팜을 설정하는 방법에 대한 <em>IT 시리즈의 개발 테스트 시작</em> 시리즈의 다음 게시물을 찾습니다.</p>


  <p><a href="https://azure.microsoft.com/en-us/pricing/free-trial/?wt.mc_id=WW_CE_IAAS_OO_BLOG_NONE" target="_blank">무료 Azure 평가판을 시작</a>합니다.<br>

  <a href="https://azure.microsoft.com/en-us/solutions/dev-test/?wt.mc_id=WW_CE_IAAS_OO_BLOG_NONE" target="_blank">Azure의 개발 테스트에 대해 자세히 알아봅니다</a>.</p>


  <p><br>

  <br>

  *출처: 테스트 환경 관리 백서에 대한 비즈니스 사례, 인식</p>
