### YamlMime:Yaml
ms.openlocfilehash: 3dc45763484cf28029b43567a32fa733da3310d0
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139903330"
Slug: dev-test-starts-with-it-set-up-a-lob-application-in-a-hybrid-cloud-for-testing
Title: 'Dev-Test IT 시작: 테스트를 위해 하이브리드 클라우드에서 LOB 애플리케이션 설정'
Summary: 계층화된 LOB(기간 업무) 애플리케이션을 배포하고 테스트하는 데 필요한 인프라를 만드는 훨씬 더 빠른 방법이 있습니다. Azure를 사용하면 인터넷의 위치에서 LOB 앱 프로덕션 환경을 쉽게 시뮬레이션할 수 있습니다.
Content: >-
  <p><em>개발자&rsquo;의 65%는 개발 테스트 리소스를 얻기에는 너무 복잡하고 시간이 많이 소요됩니다.* 그럴 필요는 없습니다&rsquo;.</em></p>


  <p><em>이 블로그 시리즈에서는 몇 시간 또는 며칠 만에 개발 테스트를 최대한 활용할 수 있도록 Microsoft 클라우드의 도움을 받아 개발 테스트&mdash; 환경을 설정하는 방법에 대한 지침을 제공합니다.</em></p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/32b2d55e-59a8-47d6-9d5e-df0b87bf9797.jpg"><img alt="IaaS_BlogThumb_250x143" border="0" height="137" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/bd91e93e-4687-4e79-9b3f-5e493f2df651.jpg" style="border-top: 0px; border-right: 0px; background-image: none; border-bottom: 0px; padding-top: 0px; padding-left: 0px; border-left: 0px; display: inline; padding-right: 0px" title="IaaS_BlogThumb_250x143" width="240"></a></p>


  <p>계층화된 LOB(기간 업무) 애플리케이션을 배포하고 테스트하는 데 필요한 인프라를 만드는 훨씬 더 빠른 방법은&#39;. Azure를 사용하면 인터넷의 위치에서 LOB 앱 프로덕션 환경을 쉽게 시뮬레이션할 수 있습니다.</p>


  <p>Azure 인프라 서비스를 사용하여 VM(가상 머신)을 스핀업하고 VNet(가상 네트워크)을 만들면( <a href="https://azure.microsoft.com/en-us/blog/dev-test-starts-with-it-how-to-resource-vms-for-your-dev-test-environment/?wt.mc_id=WW_CE_IAAS_OO_BLOG_NONE">Azure VM</a> 및 <a href="https://azure.microsoft.com/en-us/blog/dev-test-starts-with-it-how-to-create-a-dev-test-environment-in-azure/?wt.mc_id=WW_CE_IAAS_OO_BLOG_NONE">VNet</a>에 대한 더 많은 리소스에 대한 이전 블로그 게시물 참조) LOB 앱을 배포하고 실행하는 <a href="https://azure.microsoft.com/en-us/documentation/articles/virtual-networks-setup-hybrid-cloud-environment-testing/?wt.mc_id=WW_CE_IAAS_OO_BLOG_NONE">하이브리드 클라우드 테스트 환경을 신속하게 만들</a> 수 있습니다.</p>


  <p>다음 <a href="https://azure.microsoft.com/en-us/documentation/articles/virtual-networks-setup-lobapp-hybrid-cloud-testing/?wt.mc_id=WW_CE_IAAS_OO_BLOG_NONE">단계별 지침</a>에 따라 하이브리드 클라우드 테스트 환경에서 계층화된 웹 기반 LOB 앱을 배포하고 테스트하는 인프라를 만듭니다. 하이브리드 클라우드 테스트 환경의 웹 기반 LOB(기간 업무) 애플리케이션 은 SQL Server 2014 서버와 IIS(인터넷 정보 서비스) 서버를 하이브리드 클라우드 기본 구성에 추가합니다.</p>


  <p>이는 Azure에서 SQL Server 2014 데이터베이스 백 엔드를 사용하여 IIS에서 호스트되는 LOB 앱을 개발하고 테스트하고 하이브리드 클라우드 기반 IT 워크로드 테스트를 수행하기 위한 좋은 시작점입니다.</p>


  <p>웹 또는 데이터베이스 계층에 새 Azure VM을 추가하여 LOB 앱 테스트 환경의 용량을 확장합니다. <a href="https://azure.microsoft.com/en-us/documentation/articles/load-balancer-internal-overview/?wt.mc_id=WW_CE_IAAS_OO_BLOG_NONE">내부 부하 분산 장치를</a> 추가하여 여러 IIS 서버에 트래픽을 분산합니다.</p>


  <p>개발 및 테스트 후 <a href="https://azure.microsoft.com/en-us/documentation/articles/virtual-machines-workload-high-availability-lob-application-overview/?wt.mc_id=WW_CE_IAAS_OO_BLOG_NONE">Azure에서 고가용성 LOB 앱을 배포하여</a> 프로덕션 환경을 만들기 위한 다음 단계별 지침을 따릅니다. Azure VNet은 온-프레미스 네트워크의 확장이므로 사용자는 앱이 온-프레미스 데이터 센터에 있는 것처럼 프로덕션 LOB 앱 서버에 계속 액세스합니다.</p>


  <p><a href="https://azure.microsoft.com/en-us/campaigns/dev-test-starts-with-it-webinar-series/?wt.mc_id=WW_CE_IAAS_OO_BLOG_NONE">IT 웨비나로 예정된 개발 테스트 시작에 참석하세요</a>.<br>

  <a href="https://azure.microsoft.com/en-us/solutions/dev-test/?wt.mc_id=WW_CE_IAAS_OO_BLOG_NONE">Azure의 개발 테스트에 대해 자세히 알아봅니다</a>.</p>


  <p>&nbsp;</p>


  <p>*출처: 테스트 환경 관리 백서에 대한 비즈니스 사례, 인식</p>
