### YamlMime:Yaml
ms.openlocfilehash: 0d46ca548d194829bb923313d289e2d3e45991c0
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139905558"
Slug: dev-test-starts-with-it-cloud-development-and-test-environments
Title: 'Dev-Test IT 시작: 클라우드 개발 및 테스트 환경'
Summary: Azure의 개발 테스트는 공동 작업 팀에 이상적이며 사용자 환경에 대한 민첩한 관리를 제공합니다.
Content: >-
  <p><em>개발자&rsquo;의 65%는 개발 테스트 리소스를 얻기에는 너무 복잡하고 시간이 많이 소요됩니다.* 그럴 필요는 없습니다&rsquo;.</em></p>


  <p><em>이 블로그 시리즈에서는 Microsoft 클라우드의 도움을 받아 개발 테스트 환경을 설정하는 방법에 대한 지침을 제공하므로 몇 시간 또는 며칠이 아닌 몇 분 &mdash; 안에 개발 테스트를 최대한 활용할 수 있습니다.</em></p>


  <p><br>

  <a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/a7528a29-2455-46fc-be5a-35313845c861.jpg"><img alt="IaaS_BlogSeries" border="0" height="143" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/b3676513-5962-4543-ac45-668f854fa24a.jpg" style="border-top: 0px; border-right: 0px; background-image: none; border-bottom: 0px; padding-top: 0px; padding-left: 0px; border-left: 0px; display: inline; padding-right: 0px" title="IaaS_BlogSeries" width="250"></a></p>


  <p>클라우드에서 일관된 개발 테스트 환경을 만드는 속도와 경제성은 물리적 환경의 기존 비용 및 과제와 극명하게 대조됩니다.</p>


  <p>클라우드 리소스는 탐색하기 쉬운 빠르고 비용 효율적인 옵션을 제공합니다. 예를 들어 Microsoft Azure 고유한 용어로 완전한 개발 테스트 환경을 프로비전하고 관리하는 데 필요한 모든 것이 있습니다. 몇 분 안에 가상 머신을 프로비전하여 며칠 또는 몇 주를 절약할 수 있습니다. 필요한 만큼 가상 머신을 스핀업하고, 네트워크로 연결하고, 개발자에게 할당합니다. 실제 사용 시나리오를 복제하고 프로덕션 규모에서 테스트하여 더 이상 추측을 해제 &mdash; 하지 않고 문제를 식별하고 해결할 수 있습니다.</p>


  <p>Azure의 개발 테스트는 공동 작업 팀에 적합하며 사용자 환경에 대한 민첩한 관리를 제공합니다. 실시간 사용률 데이터를 사용하면 컴퓨팅 리소스 및 사용량을 파악하고 제어할 수 있습니다. 낭비를 제거하고 신속하게 변경하여 제한을 설정하고 비용을 제어합니다. Azures&rsquo; 종량제 서비스를 사용하면 수요에 맞게 확장하거나 축소할 수 있으므로 사용한 만큼만 지불할 수 있습니다.</p>


  <p>Microsoft 및 오픈 소스 애플리케이션 및 운영 체제에 대한 광범위한 지원을 통해 기존 앱, 기술 및 전문 지식을 최대한 활용하세요. System Center 또는 PowerShell 스크립팅과 같은 기본 도구를 사용하여 Azure에서 개발 테스트 환경의 프로비저닝, 배포 및 관리를 더욱 쉽게 수행할 수 있습니다.</p>


  <p>개발 및 테스트를 위해 VM을 다시 소싱하는 방법에 대한 <em>IT 시리즈의 개발-테스트 시작</em> 에서 다음 게시물을 찾습니다.</p>


  <p><a href="https://azure.microsoft.com/en-us/pricing/free-trial?wt.mc_id=WW_CE_IAAS_OO_BLOG_NONE/">Azure 평가판을 시작합니다.</a></p>


  <p><a href="https://azure.microsoft.com/en-us/solutions/dev-test/?wt.mc_id=WW_CE_IAAS_OO_BLOG_NONE">Azure에서 개발 테스트에 대해 자세히 알아봅니다.</a></p>


  <p>&nbsp;</p>


  <p>*출처: 테스트 환경 관리 백서에 대한 비즈니스 사례, Cognizant</p>
