### YamlMime:Yaml
ms.openlocfilehash: 9457c5118259d05f5e9c8161cc443e356c1fa732
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139908436"
Slug: developing-hybrid-applications-with-azure-stack
Title: Azure Stack을 사용하여 하이브리드 애플리케이션 개발
Summary: 점점 더 많은 고객으로부터 하이브리드 애플리케이션을 구축하는 것이 비즈니스에 필요하다는 소식을 듣습니다. Microsoft Azure 애플리케이션을 빌드하기 위한 플랫폼으로 계속 사용되지만 Azure Stack과 Azure를 함께 사용하면 하이브리드 애플리케이션을 빌드할 수 있습니다.
Content: >-
  <p>점점 더 많은 고객으로부터 하이브리드 애플리케이션을 구축하는 것이 비즈니스에 필요하다는 소식을 듣습니다. Microsoft Azure 애플리케이션을 빌드하기 위한 플랫폼으로 계속 사용되지만 Azure Stack과 Azure를 함께 사용하면 하이브리드 애플리케이션을 빌드할 수 있습니다. 둘 다에서 일관된 환경을 사용하면 쉽게 수행할 수 있습니다. 광산 맨 아래, 태평양 한가운데에 있는 화물선의 컨테이너 내부 또는 안데스 산맥에서 가장 높은 산인 아콘카과(Aconcagua) 꼭대기에서 어디서나 Azure 서비스를 사용할 수 있습니다. 말 그대로 기존 데이터 센터가&rsquo; 없는 모든 위치에서 Azure에서 개발한 앱을 실행할 수 있습니다.</p>


  <p>즐겨 찾는 도구 및 프로그래밍 언어를 사용하는 동안 작업에 가까운 Azure Stack을 사용할 수 있습니다. 단일 통합 DevOps 파이프라인을 사용하여 개발, 테스트 및 프로덕션으로 앱을 푸시합니다.</p>


  <p>팀이 설계하고 구현한 <a href="https://www.youtube.com/watch?v=nTXdJN0IW5Y" target="_blank">재해 구호 프로토타입</a> 과 같은 하이브리드 앱의 기능을 보여주는 것은 없습니다. 원격 환경에서 연결이 끊어진 모바일 배포에서 Azure 서비스의 훌륭한 데모입니다. 이 솔루션은 데이터 수집 및 의사 결정을 지원하며, 의료와 같은 분야에서도 테스트되는 것을 볼 수 있습니다.</p>


  <p>Azure Stack은 현재 고유한 하이브리드 솔루션 개발을 쉽게 시작할 수 있는 기능을 제공합니다. Azure Stack에서 Azure 서비스를 사용하는 핵심은 <a href="https://docs.microsoft.com/azure/azure-stack/user/azure-stack-version-profiles" target="_blank">Azure Resource Manager API 프로필입니다</a>. API 프로필은 Azure 및 Azure Stack에서 사용할 수 있는 리소스 종류 및 버전 집합을 제공합니다.</p>


  <p>함께 작동하는 리소스 유형, API 버전 및 클라우드를 조사하는 대신 솔루션에 대한 코드를 만드는 데 집중할 수 있습니다. API 프로필을 사용하여 코드가 특정 프로필을 지원하는 Azure 클라우드에서 작동할 수 있도록 합니다.</p>


  <p>API 프로필은 <a href="https://docs.microsoft.com/azure/azure-stack/user/azure-stack-version-profiles-powershell" target="_blank">PowerShell</a>, <a href="https://docs.microsoft.com/azure/azure-stack/user/azure-stack-version-profiles-azurecli2" target="_blank">Microsoft Azure CLI</a>, <a href="https://docs.microsoft.com/azure/azure-stack/user/azure-stack-version-profiles-net" target="_blank">.NET</a>, <a href="https://docs.microsoft.com/azure/azure-stack/user/azure-stack-version-profiles-java" target="_blank">Java</a>, <a href="https://docs.microsoft.com/azure/azure-stack/user/azure-stack-version-profiles-go" target="_blank">Go</a>, <a href="https://docs.microsoft.com/azure/azure-stack/user/azure-stack-version-profiles-ruby" target="_blank">Ruby</a> 및 Python에서 사용할 수 <a href="https://docs.microsoft.com/azure/azure-stack/user/azure-stack-version-profiles-python" target="_blank">있습니다</a>. 어디서나 Azure에서 작동하는 스크립트 및 자동화 워크플로를 만들 수 있습니다.</p>


  <p>코드 작성은 하이브리드 애플리케이션 개발의 일부일 뿐입니다. 파이프라인을 만들고 어디서나 Azure를 대상으로 하는 도구도 필요합니다. Azure DevOps Azure <a href="https://docs.microsoft.com/azure/devops/pipelines/targets/azure-stack?view=vsts" target="_blank">Stack을 대상으로 지정할</a> 수 있습니다.</p>


  <p>마지막으로 하이브리드 앱 개발을 시작하는 방법에 대한 지침을 찾을 수 있습니다. <a href="https://aka.ms/azsdevtutorials" target="_blank">클라우드 간 크기 조정, Edge의 AI 등에 대한 자습서를</a> 찾을 수 있습니다. 하이브리드 환경을 보여 주는 샘플 앱을 포함하는 <a href="https://github.com/Azure/AzureStack-QuickStart-Templates/tree/master/sample-hybrid-application" target="_blank">기술 지침 시리즈의 첫 번째 설치</a>를 찾을 수도 있습니다.</p>


  <p>아직 시작하지 않은 경우 <a href="https://azure.microsoft.com/en-us/overview/azure-stack/development-kit/" target="_blank">Azure Stack 개발자 키트</a> 를 다운로드하고 이 블로그 게시물에 나열된 리소스를 검토하여 시작하는 것이 좋습니다. 하이브리드 개발에 대한 향후 문서를 확인하세요! 보고 싶은 다른 항목이 있으면&rsquo; 알려주세요.</p>
