### YamlMime:Yaml
ms.openlocfilehash: 6713c172e51ac0c5d946239152c3cd1e3319125d
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139912981"
Slug: developing-applications-for-the-cloud-on-azure
Title: Azure에서 클라우드용 애플리케이션 개발
Summary: '[이 문서는 SQL Azure 팀에서 제공했습니다.] Microsoft Patterns Practices &amp; 그룹은 클라우드용 애플리케이션 개발에 관한 두 번째 무료 온라인 책 볼륨을 게시했습니다.'
Content: <p>[이 문서는 SQL Azure 팀에서 제공했습니다.]</p><p>Microsoft Patterns Practices &amp; 그룹은 <a href="https://msdn.microsoft.com/en-us/library/ff966499.aspx">Microsoft Windows Azure Platform에서 클라우드용 애플리케이션 개발에</a> 대한 두 번째 <b>무료 온라인</b> 책 볼륨을 게시했습니다. 이 책에서는 Windows Azure 플랫폼을 사용하여 클라우드에서 실행할 다중 테넌트 SaaS(Software as a Service) 애플리케이션을 만드는 방법을 보여 줍니다. 이 책은 클라우드에서 실행되거나 상호 작용하는 애플리케이션 및 서비스를 설계, 빌드 또는 운영하는 모든 설계자, 개발자 또는 IT(정보 기술) 전문가를 위한 것입니다.</p>  <p>설문 조사 애플리케이션에서 데이터로 작업하는 것은 SQL Azure 관련하여 특히 흥미롭습니다. 질문, 우려 사항, 의견이 있나요? 아래에 게시하고 우리는 그들을 해결하기 위해 노력할 것입니다.</p>
