### YamlMime:Yaml
ms.openlocfilehash: c441734a37c49e698fa14931a1cab6105ad78684
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139903328"
Slug: devtalk-app-service-ssl-settings-revamp
Title: 'DevTalk : App Service – SSL 설정 개선'
Summary: App Service SSL 설정 환경은 App Service에서 가장 많이 사용되는 기능 중 하나입니다. 고객 피드백에 따라 Azure App Service에서 인증서를 관리하는 전반적인 환경을 해결하고 개선하기 위해 UX를 다음과 같은 변경 작업을 수행합니다.
Content: >-
  <p><em>이 블로그 게시물은 Microsoft의 수석 소프트웨어 엔지니어인 Chibi Vikramathithan이 작성했습니다.</em></p>


  <p>App Service SSL 설정 환경은 App Service에서 가장 많이 사용되는 기능 중 하나입니다. 고객 피드백에 따라 Azure App Service에서 인증서를 관리하는 전반적인 환경을 해결하고 개선하기 위해 UX를 다음과 같은 변경 작업을 수행합니다.</p>


  <h2>탭</h2>


  <p>새 SSL 설정 환경은 기능을 3개의 탭으로 나눕니다.즉, SSL 바인딩, 개인 인증서(.pfx) 및 공용 인증서(.cer)입니다. 바인딩 탭을 사용하면 사용자가 프로토콜 설정을 구성하고 SSL 바인딩을 추가/편집/삭제할 수 있으며, 프라이빗 인증서 탭을 사용하면 사용자가 SSL 바인딩에 사용되는 개인 인증서(.pfx)를 업로드하고 관리할 수 있으며, 공용 인증서 탭을 사용하면 공용 인증서(.cer)를 업로드하고 관리할 수 있습니다. 또한 고객이 각 기능에 사용해야 하는 인증서 유형도 설명합니다.</p>


  <p><img src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/88b12050-d506-4a2b-8cfc-f8a20549cca7.png"></p>


  <h3>SSL 바인딩 편집</h3>


  <p>SSL 설정은 기존 SSL 바인딩을 업데이트하는 방법이 없었고&rsquo; 편집할 기능이 있었지만 바인딩 추가 흐름에서 숨겨집니다. 몇 번의 스프린트를 편집할 수 있는 기능을 사용하도록 설정했고, 기능을 더욱 다듬었으며, 이제 고객은 행을 클릭하여 바인딩을 자유롭게 편집할 수 있습니다. IP 기반 SSL 바인딩의 지문을 변경하면 IP가 손실되지 않지만 IP 기반 SSL에서 SNI로 변경하면 IP가 손실됩니다. 바인딩을 제거하고 다시 추가하지 않고 인증서를 변경하는 기능은 과거에 이 릴리스에서 해결한 문제였습니다. SSL 바인딩 추가에 대한 자세한 내용은 <a href="https://docs.microsoft.com/en-us/azure/app-service/app-service-web-tutorial-custom-ssl">여기</a>를 클릭하세요.</p>


  <p><img src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/77456fee-50db-4d62-9066-e7956e862e4a.png"></p>


  <h2>프라이빗 인증서 세부 정보</h2>


  <p>App Service에서 사용되는 개인 인증서는 인증서를 업로드하거나 App Service 인증서에서 가져오거나 KeyVault에서 가져올 때 이미 수집한 정보를 표시하기 위해 패시프트가 필요했습니다. 운전 이유는 앱에 구성된 수백 개의 개인 인증서를 보고 인증서를 탐색하는 데 힘든 시간을 보냈을 때 고객이 이제 업로드 및 가져온 인증서의 세부 정보를 얻을 수 있게 해줍니다. 세 가지 가능한 상태(정상, 경고 및 만료됨)를 보여 주는 새 상태 열을 그리드에 추가했습니다. 인증서가 향후 60일 이내에 만료될 것임을 경고합니다. 또한 프라이빗 인증서를 추가하려면 .pfx 파일을 업로드해야 한다는 내용도 명시적으로 언급되었습니다.</p>


  <p><img src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/572e1048-d342-4ae0-9184-51c36f19b7f6.png"></p>


  <p>또한 KeyVault 세부 정보 및 App Service 인증서에서 가져온 인증서와 같이 KeyVault에서 가져온 인증서의 동기화 상태를 보여 줍니다.</p>


  <p><img src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/197ecd98-c205-463a-a6ad-810df9864deb.png"></p>


  <h3>인증서 업로드</h3>


  <p>업로드 인증서 환경은 프라이빗 인증서가 .pfx 파일만 허용하고 App Service에 프라이빗 인증서를 추가하려면 유효한 pfx가 필요하다는 것을 보여 주는 데 전반적으로 더 일관됩니다. 다른 피드백을 처리하면서 두 업로드 경로 모두 표시를 중지했습니다. 이제 프라이빗 인증서에서 인증서를 업로드하면 .cer 또는 .pfx 파일 업로드에 대한 혼동을 방지하기 위해 프라이빗 인증서만 업로드할 수 있는 UX가 열립니다. 공용 인증서 탭에서 업로드 인증서 흐름을 열면 공용 인증서 옵션만 표시됩니다.</p>


  <p><img src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/cd0ab651-4bd9-46ad-8bb0-cb5624f10eee.png"></p>


  <p>업로드 블레이드를 벗어나지 않고 인증서를 업로드하는 동안 오류를 표시하도록 업로드 인증서 UX 및 구현되는 기본 방법을 업데이트했습니다.</p>


  <p><img src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/307047fc-7882-478b-a97d-1010c53b9b34.png"></p>


  <h2>공용 인증서</h2>


  <p>공용 인증서는 앱에서만 사용할 수 있으며 SSL 바인딩을 만드는 데 사용할 수 없습니다. 우리는 그것이 더 합리적 일 수있는 곳으로 옮길 수있는 방법을 노력하고 있습니다. 현재 SSL 설정은 공용 인증서가 상주하는 위치입니다. 프라이빗 인증서는 해당 기능(&rsquo;<a href="https://azure.microsoft.com/en-us/blog/using-certificates-in-azure-websites-applications/">여기서</a>는 매우 오래되었지만 신뢰할 수 있는 블로그에서 다루는 기능)을 사용하도록 설정해야 하며, 이제 공용 인증서는 (.cer) 파일을 업로드하고 런타임에 인증서를 가져올 수 있도록 하여 해당 기능에 또 다른 차원을 추가합니다.</p>


  <p><img src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/b2245e8a-8869-434f-8fe5-3eccd131d938.png"></p>


  <p>읽어 주셔서 감사합니다. 이 블로그를 작성하여 매일 App Service를 사용하는 고객의 전반적인 인증서 관리 환경을 개선하기 위해 변경한 내용을 소개합니다. 우리는 항상 피드백에 열려 있으며 의견을 기대합니다.</p>


  <p>기능 요청 또는 문제에 대해 자유롭게 문의하세요.</p>
