### YamlMime:Yaml
ms.openlocfilehash: 04ed39cbc6a8f17a0da5a5cf9c8b003502197d7d
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139902611"
Slug: dont-sweat-it-move-your-applications-to-the-public-cloud-the-right-way
Title: IT에 땀을 흘리지 않음 - 애플리케이션을 올바른 방식으로 퍼블릭 클라우드로 이동
Summary: '편집자&rsquo; 주: 오늘&rsquo; 게시물 패트릭 맥클로리에서 온다, RightScale에서 솔루션 건축가. RightScale&reg; Inc. 클라우드 관리를 통해 조직은 비즈니스를 쉽게 배포하고 관리할 수 있습니다-...'
Content: >-
  <p><b><img alt="Patrick McClory" height="153" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/6521.PMcClory_5F00_headshot_2D00_200px.jpeg" style="float: right;" title="패트릭 맥클로리" width="144"></b><strong>Editors&rsquo; 참고:</strong> 오늘&rsquo; 게시물 <b>패트릭 맥클로리</b>에서 온다, RightScale에서 솔루션 건축가. RightScale&reg; Inc. 클라우드 관리를 통해 조직은 퍼블릭, 프라이빗 및 하이브리드 클라우드에서 비즈니스에 중요한 애플리케이션을&nbsp; 쉽게 배포하고 관리할 수 있습니다. RightScale은 클라우드 컴퓨팅 인프라 및 애플리케이션의 효율적인 구성, 모니터링, 자동화 및 거버넌스를 제공합니다.</p>


  <p>&nbsp;</p>


  <p>&nbsp;</p>


  <p>&nbsp;</p>


  <p>&nbsp;</p>


  <p>분리 불안은 <a href="https://azure.microsoft.com/en-us/overview/choosing-a-cloud-service-provider">클라우드 컴퓨팅으로 전환할</a> 때 흔히 발생합니다. &rsquo;그러나 IT 업계는 중복성, 확장성 및 자동화와 같은 성공적인 클라우드 배포를 위해 몇 년 동안 필요한 기본 요소를 연습해 왔습니다. 이러한 아이디어는 반드시 새로운 것은 아니지만 이제는 새로운 Windows Azure Virtual Machines(서비스로서의 인프라)에 전체적으로 적용하여 기존의 데이터 센터 접근 방식보다 훨씬 적은 시간에 지리적으로 분산되고 중복성이 높은 아키텍처를 달성할 수 있습니다. 이는 모든 규모의 회사에 매력적인 제안이며, RightScale&rsquo;에서는 2006년부터 크고 작은 기업이 클라우드에 애플리케이션을 배포할 수 있도록 지원해 왔습니다. 클라우드 관리 범주를 개척하여 조직이 클라우드 환경에서 애플리케이션을 배포하고 관리할 수 있는 플랫폼을 제공했으며, 고객은 말 그대로 수백만 대의 서버를 클라우드에 출시했습니다. &nbsp;</p>


  <p>RightScale은 Windows Azure 전략적 파트너임을 자랑스럽게 생각하며, Windows Azure 커뮤니티에 자신을 소개하는 방법으로 우리는 세계에서 가장 큰 클라우드 배포를 구동하는 고유한 경험에서 개발한 몇 가지 모범 사례를 공유하고자 합니다. 시작하자&rsquo;.</p>


  <h4><b>중복성은 왕입니다.</b>&nbsp;</h4>


  <p>부하 분산된 웹 애플리케이션 계층 및 미러된 데이터베이스는 한동안 시스템 배포의 오류를 관리하는 일반적인 구성이었습니다. 클라우드의 장점은 지리적으로 분산된 배포를 사용하여 클라이언트에 더 가까운 콘텐츠를 제공할 뿐만 아니라 데이터 센터 경계를 넘어 재해 장애 조치 기능을 제공할 수 있다는 점입니다. 시스템 중복성을 디자인할 때 고려해야 할 몇 가지 사항이 있습니다.</p>


  <ul>
   <li>서버 중복을 계획하지&#39;않고, 서버 가동 시간을&#39;수 없다면 상당히 쓸모가 없습니다. 공용 DNS 인프라도 중요합니다.</li>
   <li>실패를 계획하고 계획을 자주 실행합니다. 재해 복구 및 장애 조치(failover) 테스트는 장기적인 가동 시간을 보장하는 데 중요합니다. &nbsp;</li>
   <li>자동으로 장애 조치(failover)의 의미에 대해 생각해 보세요. 일부 시스템의 경우 자동 장애 조치(failover)로 인해 데이터 손상이 발생할 수 있습니다. 서버 가동 시간뿐만 아니라 <i>서비스</i> 가동 시간 및 데이터 무결성에 대한 장애 조치(failover) 계획을 테스트하고 평가합니다.</li>
  </ul>


  <h4><b>확장성으로 새 문이 열립니다.</b></h4>


  <p>주문형으로 확장 및 축소할 수 있으므로 장기적으로 총 소유 비용을 최적화할 수 있습니다.&nbsp; &rsquo;애플리케이션에 더 많은 리소스가 필요한 경우 몇 시간 또는 몇 분 안에 소수의 서버에서 클라우드의 수백 개의 서버로 이동하는 것이 가능합니다. 이러한 수요가 감소하면 유휴 리소스에 대한 비용을 지불하지 않도록 신속하게 축소할 수 있습니다. 크기 조정을 위해 디자인하는 경우:</p>


  <ul>
   <li>배포를 배포하여 실패를 계획해야 합니다.</li>
   <li>지역 또는 영역 간의 데이터 전송 비용을 평가합니다.</li>
   <li>스케일 업해야 하는 시기와 규모를 축소해야 하는 시기를 나타내는 성능 메트릭 및 시스템 트리거에 대해 생각해 보세요.</li>
  </ul>


  <h4><b>Automateeverything&hellip;&nbsp;&nbsp;</b>&nbsp;</h4>


  <p>당신이 자신을 관리하는 모든 menial 작업 - 그것은 놓을 시간이&#39;. 자동화된 방식으로 프로세스를 구축하면 기술 팀이 프로덕션 지원 항목에 집중하지 않고 회사를 발전시킬 업데이트, 제품, 기능 및 솔루션에 더 집중할 수 있습니다. 신속하고 주문형으로 스케일 업 및 다운을 활용할&#39;있는 경우 자동화는 서버를 부팅하고 부팅에서 서버가 완전히 작동하는 시점까지의 시간을 최소화할 수 있도록 하는 열쇠입니다. 웹 서버의 경우 웹 사이트&#39;코드 설치 관리에서 부하 분산 설정에 연결하는 것까지 모든 것을 포함할 수 있습니다. 미러링된 데이터베이스 서버의 경우 인스턴스 크기를 상당히 쉽게 확장 및 축소할 수 있지만 미러링 세션을 다시 초기화하고 새 보조 노드를 가져오는 프로세스를 자동화하면 데이터 계층의 마력(및 비용)을 훨씬 쉽게 늘리거나 줄일 수 있습니다. 고려해야 할 몇 가지 사항은 다음과 같습니다.</p>


  <ul>
   <li>프로비전 <i>및</i> 서비스 해제 프로세스를 자동화합니다. 두 작업 세트 모두 세부 지향적이며 애플리케이션 사용 가능 및 가동 시간을 보장하기 위해 100% 정확도가 필요합니다.</li>
   <li>PowerShell을 알아보고 사용하는 제품에 사용할 수 있는 Cmdlet을 알아봅니다. MSDeploy 및 MSBuild 알아가세요. 작업을 최소화하기 위해 다시 배포할&#39;기술에 대해 이미 만들어진 도구를 활용합니다.</li>
   <li>이 시간을 사용하여 프로세스를 개선합니다. 사용 중인 제품에 대한 모범 사례를 확인하고 새로 자동화된 프로세스에서 제품을 구현하기 위해 노력합니다.</li>
  </ul>


  <p>개별적으로 이러한 아이디어는&#39;새로운 것이 아닙니다. 그러나 이를 올바르게 구현하면 팀이 물리적 하드웨어에 집중할 필요가 없으며, 시스템(또는 팀)이 더 작은 쪽에 있더라도 고가용성 솔루션에 대한 모범 사례에 집중할 수 있습니다. 크고 작은 배포는 모두 중복되고 확장 가능하며 자동화되는 이점을 누릴 수 있습니다. 프로세스를 더 구체화할수록 팀이 단기 및 장기적으로 성장을 관리할 수 있는 더 나은 기능을 갖추게 됩니다. Windows Azure에서 이러한 기본 기술 중 일부를 사용하려는 경우<a href="https://www.rightscale.com/s/azure.php?sd=Partner_Azure_Blog&amp;campaign=70170000000hPsp" target="_blank"> RightScale 무료 버전은</a> 빠르고 쉽게 시작할 수 있는 방법입니다.</p>
