### YamlMime:Yaml
ms.openlocfilehash: e5e961e2be4ae1db9e700fe4c207a58d80e169ad
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139911912"
Slug: elastic-and-microsoft-azure-unified-observability-for-spring-boot-applications
Title: '탄력적 및 Microsoft Azure: Spring Boot 애플리케이션에 대한 통합 관찰성'
Summary: Microsoft Azure Spring Cloud 데이터를 탄력적 데이터로 원활하게 제공하고 클라우드 여정의 모든 단계를 모니터링합니다. 클라우드 및 온-프레미스 환경의 Spring Boot 애플리케이션 및 기타 데이터 집합에서 전체적인 보기를 얻을 수 있습니다.
Content: >-
  <p>오늘, Azure에서 Spring Boot 애플리케이션의 통합된 관찰성을 위해 탄력적 통합의 가용성을 발표하고 있습니다. Microsoft Azure Spring Cloud <a href="https://aka.ms/Start-Elastic">로그 및 메트릭</a>을 Elastic에 원활하게 제공하고<a href="https://aka.ms/Start-Elastic-APM">, Spring Boot 애플리케이션을 계측</a>하고, 클라우드 여정의 모든 단계를 모니터링할 수 있습니다. 또한 클라우드 및 온-프레미스 환경에서 Spring Boot 애플리케이션 및 기타 로그 및 메트릭에 대한 전체적인 보기를 얻을 수 있습니다.</p>


  <p>지난 2년 동안 많은 엔터프라이즈 고객과 협력하여 직면한 시나리오에 대해 알아봅니다. 이러한 고객 중 상당수는 온-프레미스 데이터 센터에서 수천 개의 Spring Boot 애플리케이션을 실행하고 있습니다. 이러한 애플리케이션을 클라우드로 마이그레이션할 때 이러한 애플리케이션에서 로그 및 메트릭을 집계하고 개발자가 익숙하고 수년 동안 사용해 온 솔루션을 사용하여 APM(애플리케이션 성능 모니터링)을 위해 계측해야 합니다. 또한 이미 로그 및 메트릭을 전달하고 Elastic과 같은 시스템을 사용하여 엔드 투 엔드 모니터링을 위해 미리 계측된 기존 서버 쪽 소프트웨어의 연속성을 보장해야 합니다. 더 심층적인 애플리케이션 가시성을 확보하고 근본 원인 분석에 소요되는 시간을 줄이며 웹 및 모바일 애플리케이션에서 일관된 고객 환경을 제공할 수 있습니다. <a href="https://techcommunity.microsoft.com/t5/apps-on-azure-blog/2021-report-how-developers-migrate-spring-apps-to-the-cloud/ba-p/3021421" target="_blank">또한 2021년 설문 조사에 따르면</a> 엔드 투 엔드 모니터링&rdquo;은 DevOps 두 번째로 큰 과제이며 IT 관리자는 Spring Boot 애플리케이션을 클라우드로 마이그레이션할 때 직면합니다.&ldquo; Elastic에서 Azure Spring Cloud 로그 및 메트릭을 통합하면 여정을 간소화하고 통합된 관찰성을 위해 Spring Boot 애플리케이션을 쉽게 계측할 수 있습니다.</p>


  <p><a href="https://www.youtube.com/watch?v=KjmQX1SxZdA&amp;ab_channel=JavaonAzure" target="_blank"><img alt="Unified Observability" border="0" height="583" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/c281fe9a-d979-4ba3-96f4-3e141023500a.jpg" style="border: 0px currentcolor; border-image: none; display: inline; background-image: none;" title="통합된 관찰성" width="1024"></a></p>


  <p><em><strong>그림 1:</strong> Elastic을 사용하는 Spring Boot 애플리케이션에 대한 관찰 가능성을 보여 주는 대시보드가 있는 비디오 스크린샷</em></p>


  <p>이제 Elastic은 Microsoft Azure Spring Cloud에서 로그 및 메트릭을 원활하게 수집하여 DevOps 및 SRE가 <a href="https://www.elastic.co/observability/cloud-monitoring" target="_blank">클라우드, 온-프레미스 또는 하이브리드 환경에서</a>&mdash; Spring Boot 애플리케이션&mdash;을 모니터링하고 모니터링 사일로를 제거하여 운영 효율성 및 개발자 생산성을 높일 수 있습니다. DevOps 및 SRE는 Spring Boot 로그와 애플리케이션 메트릭을 Elastic에 자동으로 전달하여 모든 환경에서 모니터링할 수 있습니다. 또한 Teams 전체적인 엔드 투 엔드 모니터링을 위해 환경 전체에서 다른 관찰 가능성 데이터 집합과 컨텍스트를 상호 연결하고 Spring 데이터에 추가할 수 있습니다.</p>


  <p>&ldquo;Elastic은 조직이 애플리케이션과 인프라&rdquo; 를 관찰, 이해 및 최적화할 수 있도록 돕는 데 전념하고 있다고 <strong>Elastic 제품 관리 담당 부사장인 Steve Kearns</strong>는 말했습니다. &quot;Azure Spring Cloud와 Elastic Observability 솔루션 간의 이 네이티브 통합을 통해 애플리케이션, 인프라 및 사용자 데이터 전반에서 Spring Boot 애플리케이션의 통합 보기를 통합하는 것이 그 어느 때보다 쉽게&#39;.&quot;</p>


  <p style="margin-left: 40px;"><em>&quot;Microsoft는 고객이 클라우드에서 Java 애플리케이션을 보다 쉽게 현대화할 수 있도록 하기 위해 최선을 다하고 있습니다. Elastic on Azure의 확장된 네이티브 통합에는 고객이 단순히 Spring Boot 애플리케이션의 종단 간 관찰 가능성을 달성할 수 있도록 하는 Azure Spring Cloud에 대한 지원이 포함되어 있습니다.&quot;</em>&mdash; <strong>Julia Liuson, Microsoft 개발자 부서 사장</strong></p>


  <h2>Elastic에 Azure Spring Cloud 로그 전달</h2>


  <p>네이티브 통합을 통해 탄력적 관찰 가능성 솔루션에 로그를 원활하게 제공할 수 있습니다. 데이터가 Elastic으로 제공되면 턴키 시각화 및 대시보드를 사용하여 몇 분 안에 분석을 시작합니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/09a849cc-259b-4dad-be42-626cc0fd98cf.png"><img alt="Diagnostic Setting blade for Azure Spring Cloud Service" height="530" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/f061a8d5-c317-46da-a798-3aa14c78779f.png" style="display: inline;" title="진단 설정" width="1024"></a></p>


  <p><em><strong>그림 2: </strong> Azure Spring Cloud Service에 대한 진단 설정 블레이드</em></p>


  <h2>Spring Boot 애플리케이션 계측</h2>


  <p>&quot;Elastics Terraform 또는 ARM 템플릿을&quot; 사용하여 만들고 배포하는 새 애플리케이션을 계측하고 모니터링하기 위한 완전한 실습 환경을 위해 프로비저&rsquo;닝 자동화를 실행합니다. 또는 Azure CLI(명령줄 인터페이스)를 사용하여 주문형으로 실행하여 유연성과 제어를 강화할 수 있습니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/da847632-4782-41c3-b0bf-f339d6f255a1.jpg"><img alt="Code example" border="0" height="238" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/63a2b5a7-777f-420b-a88e-0a7074d492ac.jpg" style="border: 0px currentcolor; border-image: none; display: inline; background-image: none;" title="코드 예제" width="780"></a></p>


  <p><em><strong>그림 3:</strong> Azure CLI(명령줄 인터페이스)를 사용하여 탄력적 계측을 설정하는 예제</em></p>


  <h2>Spring Boot 애플리케이션 성능 분석</h2>


  <p>Spring Boot 애플리케이션에서 로그를 계측하고 전달한 후 Elastic Observability를 사용하여 데이터를 모니터링, 분석 및 검색하여 애플리케이션의 성능을 유지할 수 있습니다.</p>


  <p>Elastic Observability 내에서 기본 제공 Azure Spring Cloud 대시보드를 사용하여 Azure Spring Cloud 로그에서 즉각적인 인사이트를 얻을 수도 있습니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/bb032c48-f6a7-4260-9938-4258591f597d.png"><img alt="Out-of-the-box dashboards" height="768" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/cfe4678c-a515-47b8-8fa4-6d7f671431df.png" style="display: inline;" title="Elastic Observability의 Azure Spring Cloud Service 로그에 대한 기본 대시보드" width="914"></a></p>


  <p><em><strong>그림 4:</strong> Elastic Observability의 Azure Spring Cloud Service 로그에 대한 기본 대시보드</em></p>


  <p>APM(탄력적 애플리케이션 성능 모니터링)을 사용하면 애플리케이션 성능 데이터를 분석하고 검색할 수 있습니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/ded9082c-b99a-4d69-9f0f-05827cb3c122.png"><img alt="Service Map for customer service from Spring Petclinic Application" height="575" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/d1543db3-e93a-41c6-bd84-203646f702ea.png" style="display: inline;" title="서비스 맵" width="1024"></a></p>


  <p><em><strong>그림 5:</strong> Spring Petclinic 애플리케이션의 고객 서비스에 대한 서비스 맵</em></p>


  <p>Elastic APM을 사용하여 JVM(Java Virtual Machine) 메트릭을 확인하여 증거 기반 용량 계획 결정을 내리는 데 도움이 되는 힙 메모리 사용량, 시스템 메모리 사용량, CPU 사용량 및 기타 메트릭을 이해할 수도 있습니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/86e2a6c4-7609-4b22-9972-7b498aa06acc.png"><img alt="Java Virtual Machines metrics" height="522" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/0f7e10e1-d030-4a29-a7cb-a337fae0b2dc.png" style="display: inline;" title="고객 서비스를 위한 Elastic APM의 JVM 메트릭" width="1024"></a></p>


  <p>&nbsp;</p>


  <p><em><strong>그림 6: </strong> 고객 서비스를 위한 Elastic APM의 JVM 메트릭</em></p>


  <p>Elastic APM의 분산 추적 기능을 활용하여 애플리케이션의 성능을 자세히 파악하여 고객에게 가장 많은 영향을 미치는 트랜잭션과 해당 트랜잭션이 가장 많이 소요되는 시간을 파악할 수 있습니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/6a7ac6fc-1e10-4c0b-84c5-520f84b0a032.png"><img alt="Distributed tracing in Elastic APM for customers-service's GET owners operation" height="546" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/753b4f7f-6087-4121-b6a0-7235e48aeef5.png" style="display: inline;" title="Elastic APM의 분산 추적" width="1024"></a></p>


  <p><em><strong>그림 7:</strong> 고객 서비스&#39;GET 소유자 작업을 위한 Elastic APM의 분산 추적</em></p>


  <h2>기계 학습이 변칙을 자동으로 검색합니다.</h2>


  <p>Elastics&rsquo; <a href="https://www.elastic.co/what-is/elasticsearch-machine-learning">기본 제공 기계 학습 기능을</a> 사용하면 Azure Spring Cloud 데이터에서 새로운 인사이트를 추출하는 것은 단추&mdash; 메이킹 기계 학습을 클릭하는 것만큼 간단합니다.</p>


  <p>Elastic Stack은 수집 시 데이터를 처리하여 근본 원인을 식별하거나 이벤트에 컨텍스트를 추가하는 데 필요한 메타데이터가 있는지 확인합니다. 데이터 시각화 도우미와 같은 기본 제공 도구는 찾고&#39;작업을 찾고 기계 학습과 잘 어울리는 데이터 필드를 식별하는 데 도움이 됩니다.</p>


  <p>탄력적 관찰 가능성 내에서 풍부한 경고 및 변칙 검색 기능을 사용하여 로그 및 APM 데이터에서 실행 가능한 인사이트를 도출할 수 있습니다. 예를 들어 Azure Spring Cloud에서 애플리케이션의 응답 시간에 불규칙한 로그 속도 또는 비정상적인 동작을 발견할 수 있습니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/76130358-4414-4063-92f4-4746b432ffeb.png"><img alt="Anomaly Explorer in Elastic" height="591" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/b15a5e22-76c1-4229-b0cc-a5fbe6a0817f.png" style="display: inline;" title="탄력적 변칙 탐색기" width="1024"></a></p>


  <p><em><strong>그림 8: </strong> 탄력적 변칙 탐색기</em></p>


  <h2>동일한 로그를 사용하여 클라우드 규모에서 위협 중지</h2>


  <p>Elastic은 공통 스키마 및 단일 리포지토리를 제공하므로 Spring 애플리케이션 및 기타 데이터 집합의 동일한 관찰성 데이터를 XDR(확장 검색 및 응답)에 사용하여 평균 검색 시간을 0으로 유도할 수도 있습니다. <a href="https://www.elastic.co/security" target="_blank">Elastic Security</a> 는 SIEM(보안 정보 및 이벤트 관리)과 엔드포인트 보안을 결합하여 조직이 다양한 원본에서 대량의 데이터를 수집 및 보존하고, 데이터를 더 오래 저장 및 검색하고, 검색 및 기계 학습을 통해 위협 헌팅을 강화할 수 있도록 합니다.</p>


  <h2>조명을 켜두는 동안 고객 가치에 집중</h2>


  <p>Azure에서 Elastic의 네이티브 통합은 Azure에서 Elastic을 시작하는 가장 쉽고 빠른 방법입니다. Azure Spring Cloud 로그 및 APM 데이터를 Elastic으로 신속하게 배송하고, 필요한 경우 어디서나 모든 유형의 데이터에 액세스합니다. 데이터가 온-프레미스이거나 다중 클라우드 또는 하이브리드 클라우드 환경에서 가장&mdash; 많이 필요합니다. 이 전체적인 보기는 Spring Boot 애플리케이션을 클라우드로 마이그레이션하는 것을 간소화하는 데 도움이 됩니다. 또한 Elastic Cloud <a href="https://www.elastic.co/cloud/shared-responsibility" target="_blank">는 보안, 유지 관리 및 유지 관리를 처리</a>하여 가시성 향상, 운영 개선 및 사이버 복원력으로 비즈니스를 발전시킬 수 있습니다.</p>


  <h2>솔루션을 빌드하고 현재 모니터링</h2>


  <p>Azure Spring Cloud는 Microsoft 및 VMware에서 공동으로 빌드, 운영 및 지원합니다. 인프라 및 Spring Cloud 미들웨어 관리의 복잡성을 추상화하여 비즈니스 논리를 빌드하는 데 집중하고 Azure에서 동적 크기 조정, 패치, 보안, 규정 준수 및 고가용성을 처리할 수 있도록 하는 Spring Boot 애플리케이션용 완전 관리형 서비스입니다. 몇 단계를 통해 Azure Spring Cloud를 프로비저닝하고, 애플리케이션을 만들고, Spring Boot 애플리케이션을 배포하고 크기를 조정하고, 몇 분 안에 모니터링을 시작할 수 있습니다. 계속해서 더 많은 개발자 친화적이고 엔터프라이즈 지원 기능을 Azure Spring Cloud에 도입할 예정입니다. Azure Spring Cloud를 사용하여 영향력 있는 솔루션을 빌드하는 방법을 듣고 싶습니다.</p>


  <p><a href="https://aka.ms/Start-Elastic" target="_blank">Elastic을 사용하여 로그 및 메트릭을 분석</a> 하고 Spring Boot 애플리케이션을 <a href="https://aka.ms/Start-Elastic-APM" target="_blank">모니터링</a> 합니다.</p>


  <p><strong>리소스</strong></p>


  <ul>
      <li>GitHub <a href="https://docs.microsoft.com/en-us/learn/modules/azure-spring-cloud-workshop/" target="_blank">MS Learn 모듈</a> 또는 <a href="https://github.com/microsoft/azure-spring-cloud-training" target="_blank">자가 진행 워크샵</a> 사용 알아보기</li>
      <li><a href="https://docs.microsoft.com/en-us/azure/spring-cloud/" target="_blank">Azure Spring Cloud</a>에서 솔루션 구현에 대해 자세히 알아보기</li>
      <li>Spring Petclinic 애플리케이션의 <a href="https://github.com/Azure-Samples/spring-petclinic-microservices" target="_blank">분산 버전 배포</a></li>
      <li><a href="https://docs.microsoft.com/en-us/azure/spring-cloud/reference-architecture" target="_blank">Azure Spring Cloud 참조 아키텍처</a>를 통해 엔터프라이즈 모범 사례를 활용하여 Spring Boot 애플리케이션 배포</li>
      <li><a href="https://docs.microsoft.com/en-us/azure/developer/java/migration/migrate-spring-boot-to-azure-spring-cloud" target="_blank">Spring Boot</a>, <a href="https://docs.microsoft.com/en-us/azure/developer/java/migration/migrate-spring-cloud-to-azure-spring-cloud" target="_blank">Spring Cloud</a> 및 <a href="https://aka.ms/migrate-tomcat-to-azure-spring-cloud-service" target="_blank">Tomcat 애플리케이션을</a> Azure Spring Cloud로 마이그레이션</li>
      <li><a href="https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/" target="_blank">Azure 서비스와 상호 작용하는</a> Wire Spring 애플리케이션</li>
      <li>피드백 및 질문의 경우 <a href="mailto:mailto:AzureSpringCloud-Talk@service.microsoft.com">이메일을 보내</a>주세요.</li>
  </ul>
