### YamlMime:Yaml
ms.openlocfilehash: 6f890942d944b081961500d88bbb5442e0a10fa6
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139902164"
Slug: empower-an-adaptive-it-environment-for-people-processes-and-culture-with-inside-azure-for-it
Title: It용 Inside Azure를 사용하여 적응형 IT 환경 강화
Summary: 7월에는 클라우드 전문가가 Azure 모범 사례 및 인사이트를 사용하여 IT 운영을 혁신할 수 있도록 설계된 온라인 기술 기술 리소스인 It용 Azure 내부를 발표했습니다. 이 팀은 IT용 Inside Azure를 사용하여 거의 모든 곳에서 연결하고 공동 작업한 사용자 수에서 영감을 받았습니다.
Content: >-
  <p>7월에는 클라우드 전문가가 Azure 모범 사례 및 인사이트를 사용하여 IT 운영을 혁신할 수 있도록 설계된 온라인 기술 기술 리소스인 It <a href="https://azure.microsoft.com/en-us/blog/enhance-your-cloud-skills-and-accelerate-digital-transformation-with-inside-azure-for-it/" target="_blank">용 Azure 내부를 발표</a>했습니다. 이 팀은 <a href="https://azure.microsoft.com/en-us/overview/what-is-azure/iaas/it-resources/?wt.mc_id=IAFITc" target="_blank">IT용 Inside Azure</a> 를 사용하여 거의 모든 곳에서 연결하고 공동 작업한 사용자 수에서 영감을 받았습니다. 내가 호스트하는 새로운 비디오 시리즈의 월간 <a href="https://techcommunity.microsoft.com/t5/azure-infrastructure/inside-azure-for-it-ask-the-product-experts-live-save-the-date/ba-p/2461257" target="_blank">라이브 제품 전문가 세션</a>&nbsp; 공유&nbsp; 학습에 참여하든, Azure 팀과 저는 여러분의 참여, 피드백 및 파트너십에 감사드립니다.&nbsp;</p>


  <p>우리 모두는 IT 작업이 점점 더 어려워지고 있다는 것을 알고 있습니다. 여러분은&rsquo; 직원들이 현지에 있거나 전 세계에 퍼져 있는 하이브리드 작업을 가능하게&mdash; 해야 했습니다. 이는 클라우드를 빠른 속도로 수용하는 것을 의미했으며, 이를 수행하는 동안 보안,&rsquo; 가용성 및 일관된 관리를 보장하기 위해 내부 팀 및 개발자와 더 잘 협력해야 했습니다.</p>


  <p>저는 최근에 IT 디렉터와 이야기를 나누고 있었는데, 직원들이 집이나 사무실에서 일할 수 있도록 하는 데 많은 노력을 기울였음에도 불구하고&rsquo; 이를 위해 서두르면서 오래된 IT 프로세스를 남겼습니다. IT 관리 및 거버넌스&nbsp;를 개선하기 위해 취할 수 있는 단순하면서도 영향력 있는 단계에 대해 이야기하여 보다 적응적이고 유연하게 작업할 수 있도록 했습니다. 오늘,&rsquo; IT용 Inside Azure의 두 번째 에피소드를 통해 업계나 비즈니스 규모에 관계없이 오늘 사용할 수 있는&rsquo; 팁을 제공하기 위해 몇 가지 조언을 살펴봅니다.</p>


  <h2>기술 및 클라우드 기술 리소스 활용&nbsp;</h2>


  <p>Weve&rsquo;는 에피소드를 세 &ldquo;가지 간식 세그먼트&rdquo; 로 나누어, 그래서 당신은 당신이 순간에 필요한 조언에 따라 주제 사이를 점프 할 수 있습니다.</p>


  <h3>세그먼트 1: Microsoft 365 및 Azure를 사용하여 인력 커넥트</h3>


  <p>고객 성공 엔지니어링의 기업 부사장인 Tara Roth는 <a href="https://aka.ms/Episode2-pt1" target="_blank">사용자가 어디서나 모든 장치에서 안전하게 작업할 수 있도록 하는</a> 방법에 대해 이야기합니다. 신입 사원을 처음으로 설립하는 것 이상으로, 사람들이 계속 운영할 수 있도록 돕는 데 필요한 도구를 사용하여 복원력과 민첩성을 구축하는 것에 대해 논의합니다.</p>


  <h3>세그먼트 2: 대규모 하이브리드 및 분산 IT 환경 관리</h3>


  <p>Windows Server의 수석 프로그램 관리자인 Jeff Woolsey와 저는 <a href="https://aka.ms/Episode2-pt2" target="_blank">운영 방식을 개선하기 위해 클라우드로 비즈니스 프로세스 및 레거시 시스템을 현대화하는 방법에</a> 대해 설명합니다. 또한 Jeff는 작업을 간소화하고 시간을 절약할 수 있는&mdash; 리소스&mdash;를 관리, 모니터링 및 보호하는 방법을 자동화하는 실제 예제를 공유합니다.</p>


  <h3>세그먼트 3: DevOps 사용하여 어디서나 클라우드 네이티브 앱 빌드</h3>


  <p>마지막으로, Im&rsquo;은 VS 및 .NET용 파트너 프로그램 관리자인 Scott Hanselman과 함께 개발 팀과 협업하고 DevOps 문화에서 디지털 변환을 구동<a href="https://aka.ms/Episode2-pt3" target="_blank">하는 클라우드 네이티브 애플리케이션을 빌드하는 모범 사례를</a> 공유했습니다. Scott과 저는 원격 엔지니어링의 다양한 단계에서 문제를 극복할 수 있는 방법에 대해 설명합니다.</p>


  <p>이러한 대화를 통해 관찰할 때&rsquo; 작은 단계는 사람, 인프라 프로세스 및 투자 권한을 부여하는 데 있어 큰 결과를 초래할 수 있습니다. 이러한 학습을 적용하면 원격 소프트웨어 개발 및 IT 관리의 모든 단계에서 문제를 해결하는 데 도움이 될 수 있습니다.</p>


  <h2>IT용 Azure 내부를 최신 상태로 유지</h2>


  <p>IT용Inside Azure를 통해&nbsp; 사용할 수 있는 더 많은 기술 및 클라우드 기술 리소스가 있습니다. 생산성, 디지털 변환 및 혁신을 가능하게 하도록 설계된 모범 사례 및 리소스를 사용하여 적응형 IT 환경을 강화하는 방법에 대해 자세히 알아봅니다. 기술 교육 비디오를 활용하고 <a href="https://azure.microsoft.com/en-us/overview/what-is-azure/iaas/it-resources/?wt.mc_id=IAFITc" target="_blank">IT용 Inside Azure</a>를 사용하여 이러한 시나리오를 구현하는 방법을 알아봅니다.</p>


  <ul>
      <li>단계별 지침인 <a href="https://azure.microsoft.com/en-us/resources/azure-strategy-and-implementation-guide-fourth-edition/?wt.mc_id=IAFITc" target="_blank">Azure 전략 및 구현 가이드</a>를 시작합니다.</li>
      <li>일정을 확인하세요. <a href="https://techcommunity.microsoft.com/t5/azure-infrastructure/inside-azure-for-it-ask-the-product-experts-live-save-the-date/ba-p/2461257" target="_blank">제품 전문가에게 실시간으로 문의</a>하세요.</li>
      <li>Microsoft 365 <a href="https://aka.ms/Episode2-pt1" target="_blank">및 Azure를 사용하여 인력을 커넥트</a> 세그먼트 1을&nbsp; 시청합니다.</li>
      <li>시계 세그먼트 2:&nbsp; <a href="https://aka.ms/Episode2-pt2" target="_blank">하이브리드 및 분산 IT 환경을 대규모로 관리합니다</a>.</li>
      <li>세그먼트 3 보기:&nbsp; <a href="https://aka.ms/Episode2-pt3" target="_blank">DevOps 사용하여 어디서나 클라우드 네이티브 앱을 빌드</a>합니다.</li>
  </ul>
