### YamlMime:Yaml
ms.openlocfilehash: 22fb7e26bd8efcbcec47eff5f6ecea21c11ce904
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139898015"
Slug: enable-client-side-monitoring-in-azure-with-application-insights
Title: 애플리케이션 Insights 사용하여 Azure에서 클라이언트 쪽 모니터링 사용
Summary: 애플리케이션 Insights JavaScript SDK를 사용하면 웹 페이지 또는 앱의 성능과 사용량을 수집하고 조사할 수 있습니다. 지금까지 수동으로 추가를 통해 온보딩을 제공했습니다.
Content: >-
  <p>애플리케이션 Insights JavaScript SDK를 사용하면 웹 페이지 또는 앱의 성능과 사용량을 수집하고 조사할 수 있습니다. 지금까지 애플리케이션에 스크립트를 수동으로 추가하고 다시 배포하는 방법을 통해 온보딩을 제공했습니다. 스크립트를 수동으로 추가하는 기능은 계속 지원되지만, 최근에는 몇 번의 클릭으로 Azure Portal에서 클라이언트 쪽 모니터링을 추가하는 기능도 추가되었습니다.</p>


  <h1>사용 여부</h1>


  <p>Azure에서 Application Insights를 사용하도록 설정한 경우 페이지 보기 및 사용자 원격 분석을 추가할 수 있습니다. <a href="https://docs.microsoft.com/en-us/azure/application-insights/app-insights-monitor-performance-live-website-now">설명서</a>에서 서버 쪽 모니터링을 켜는 방법을 알아볼 수 있습니다.</p>


  <p>&nbsp;&nbsp;&nbsp;&nbsp; 1. 설정 -&gt;&nbsp;Application 설정 선택</p>


  <p><img alt="step one" border="0" height="529" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/debb70c9-16fe-49f3-9856-31e6c10815ed.png" style="margin: 0px auto; border: 0px currentColor; border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; float: none; display: block; background-image: none;" title="1단계" width="661"></p>


  <p>&nbsp;&nbsp;&nbsp;&nbsp; 2. 앱 설정 아래에서 새로운 키 값 쌍을 추가합니다.</p>


  <blockquote>

  <p style="margin-left: 40px;">키: APPINSIGHTS_JAVASCRIPT_ENABLED</p>

  </blockquote>


  <blockquote>

  <p style="margin-left: 40px;">값: true</p>


  <p><img alt="step two" border="0" height="141" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/97761839-1c18-42cb-9c43-a15eb3b05ab0.png" style="margin: 0px auto; border: 0px currentColor; border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; float: none; display: block; background-image: none;" title="2단계" width="697"></p>


  <p>&nbsp;</p>

  </blockquote>


  <p>&nbsp;&nbsp;&nbsp;&nbsp; 3. 설정을 저장하고 개요 탭에서 앱을 다시 시작합니다.</p>


  <p>&nbsp;</p>


  <p>Application Insights JavaScript SDK가 이제 각 웹 페이지에 삽입됩니다.</p>


  <h1>피드백</h1>


  <p>JavaScript SDK에 대한 질문이 있거나 문제가 발생하는 경우 <a href="https://github.com/Microsoft/ApplicationInsights-JS">GitHub</a> 문제를 자유롭게 여세요.</p>
