### YamlMime:Yaml
ms.openlocfilehash: 7f5c3ca460a631e9435f9cef96df4e6b553faf97
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139911906"
Slug: enhanced-app-usage-monitoring-and-investigative-features-in-azure-application-insights
Title: Azure Application Insights 향상된 앱 사용 모니터링 및 조사 기능
Summary: "애플리케이션 성능 문제를 조사할 때 정보를 찾기 위해 분주히 움직이고 있나요? 애플리케이션의 사용량 및 인시던트에 대한 수집 및 보고를 이해 관계자에게 보고하는 데 몇 시간(때로는 며칠)이 소요되나요? \n"
Content: >-
  <p>애플리케이션 성능 문제를 조사할 때 정보를 찾기 위해 분주히 움직이고 있나요? 애플리케이션의 사용량 및 인시던트에 대한 수집 및 보고를 이해 관계자에게 보고하는 데 몇 시간(때로는 며칠)이 소요되나요?</p>


  <p><a href="https://azure.microsoft.com/services/application-insights/">Azure 애플리케이션 Insights</a> 기계 학습 및 임시 분석을 기반으로 실시간 인사이트를 제공하여 앱 및 서비스의 성능과 유용성을 학습, 반복 및 개선할 수 있습니다. 사용자에게 영향을 주기 전에 애플리케이션 성능 문제를 감지, 조사 및 완화하는 데 도움이 됩니다.</p>


  <p>현재 공개 미리 보기로 제공되는 Azure 애플리케이션 Insights 새로운 기능을 사용하면 모든 관련 정보를 쉽게 수집하고 보고할 수 있습니다. 애플리케이션 성능 문제를 조사하든 애플리케이션 사용량을 탐색하든 관계없이 결과를 저널링하고 앱의 전체 스토리를 설명합니다.</p>


  <h3>애플리케이션 사용 모니터링 통합 문서</h3>


  <p>애플리케이션 Insights 새로운 기능인 통합 문서를 사용하면 사용량 현황 데이터, 분석 쿼리 및 텍스트의 시각화를 대화형 문서로 결합할 수 있습니다. 이를 통해 제품 소유자는 사용자, 세션, 이벤트, 보존 및 분석과 같은 여러 시각화 도구에 걸쳐 있는 앱 사용량에 대한 질문에 답변한 다음 결과를 읽기 쉬운 양식으로 가져와 팀과 공유할 수 있습니다. 팀의 다른 사람에게 통합 문서를 보낼 때 통합 문서를 편집할 수 있도록 하는 데 사용한 컨트롤과 쿼리가 계속 편집 가능합니다. 이렇게 하면 통합 문서를 쉽게 탐색하고 확장하며 실수를 확인할 수 있습니다. 통합 문서는 현재 애플리케이션 Insights 사용 현황 섹션에서 사용할 수 있습니다.</p>


  <p>자세한 내용은 <a href="https://go.microsoft.com/fwlink/?linkid=851491">사용량 현황 데이터를 조사하고 공유하는</a> 방법에 대한 설명서 페이지를 참조하세요.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/7edd6a9a-39c7-4791-ba04-ac6d754c4769.png"><img alt="Workbooks in Insights" border="0" height="518" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/3c14f5ae-cea7-4d18-b707-98d877d90cad.png" style="border: 0px currentColor; border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="Insights 통합 문서" width="924"></a></p>


  <p align="center"><em>Azure 애플리케이션 Insights 통합 문서의 스크린샷</em></p>


  <h3>사용자 및 세션 타임라인 시각화</h3>


  <p>개별 사용자의 동작을 분석하면 빛을 발할 수 있습니다. 예를 들어 고객이 직접 제품을 사용하는 것을 확인하면 유용성 향상이 필요한 위치를 알아볼 수 있습니다. 따라서&rsquo;&rsquo; 애플리케이션 Insights 개별 사용자 및 세션으로 더 쉽게 필터링할 수 있습니다. 사용자, 세션 및 이벤트 도구&rsquo;에서 쿼리에 따라 각각 5명의 샘플 사용자, 세션 또는 이벤트를 제공하는 섹션을 찾을 수 있습니다. &rsquo;세션 도구에서 샘플 세션을 클릭할 때 새 타임라인 보기로 한 단계 더 나아가야 합니다. 이 타임라인을 사용하면 스토리와 같은 세션의 세부 정보, 페이지 보기 및 사용자 지정 이벤트를 쉽게 찾아볼 수 있습니다. 이러한 방식으로 사용자&rsquo; 환경을 한 단계씩 실행하면 제품을 사용하는 동안 겪었을 수 있는 어려움이나 목표를 유추한 다음 사이트의 향후 릴리스에서 이를 해결할 수 있습니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/72ef3756-eb32-459e-a07f-abd584525452.png"><img alt="Screenshot highlighting Session Timeline in Azure Application Insights" border="0" height="517" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/4ffb85df-1a96-4360-854c-1e4c9c344c93.png" style="border: 0px currentColor; border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="Azure 애플리케이션 Insights 세션 타임라인을 강조 표시하는 스크린샷" width="929"></a></p>


  <p align="center"><em>Azure 애플리케이션 Insights 세션 타임라인을 강조 표시하는 스크린샷</em></p>


  <h3>사용자 흐름을 이해하는 깔때기</h3>


  <p>깔때기를 사용하면 복잡한 쿼리를 작성하지 않고 시각적 표현을 통해 이벤트 시퀀스의 변환을 쉽게 측정할 수 있습니다. Funnels를 사용하여 사용자가 하차하는 위치를 파악하고 고객에게 문제를 일으키는 이벤트 또는 페이지를 정확히 파악할 수 있습니다. 자세한 내용은 <a href="https://go.microsoft.com/fwlink/?linkid=846142">웹 애플리케이션의 사용 현황 분석에 대한</a> 설명서 페이지를 참조하세요.&nbsp;</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/60ef3009-7cff-498b-9f72-749a23a34401.png"><img alt="Funnels in Azure Application Insights." border="0" height="415" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/4e57ecd2-5c41-4a70-acfb-6b0ce8515ca4.png" style="border: 0px currentColor; border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="Azure 애플리케이션 Insights 깔때기입니다." width="924"></a></p>


  <p align="center"><em>Azure 애플리케이션 Insights 깔때기의 스크린샷</em></p>


  <h3>큐레이팅된 성능 조사 개선 사항</h3>


  <p>여러분의 의견을 경청하고 애플리케이션 성능 조사 환경을 개선했습니다. 이제 성능 블레이드에 각 차트 및 그리드에 대한 제목이 포함됩니다. 또한 운영 응답성의 추세를 제공하고 관심 있는 특정 느린 작업에 대한 세부 정보를 드릴할 수 있습니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/67345940-9307-434f-9a41-b744b0260778.jpg"><img alt="Screenshot of performance investigation in Azure Application Insights" border="0" height="594" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/86a4575f-5475-44af-a0c9-3d9823135a4a.jpg" style="border: 0px currentColor; border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="Azure 애플리케이션 Insights 성능 조사 스크린샷" width="929"></a></p>


  <p>&nbsp;</p>


  <p align="center"><em>Azure 애플리케이션 Insights 성능 조사 스크린샷</em></p>


  <h3>공개 미리 보기 관리</h3>


  <p>Application Insights 새로운 기능을 지속적으로 혁신하고 릴리스하면서 새로운 기능을 활용하는 데 필요한 유연성과 제어를 제공하고자 합니다. 이와 관련하여 공개 미리 보기 관리를 통해 비즈니스 운영 중단을 최소화하면서 새로운 환경을 제공할 수 있습니다. 여기서는 프로덕션 환경으로 이동하기 전에 자체 일정에 따라 애플리케이션 Insights 대한 새로운 향상된 기능을 사용해 본 후 사전 프로덕션 환경에서 테스트할 수 있습니다.</p>


  <p>미리 보기를 구성하는 방법에 대한 자세한 내용은 <a href="https://docs.microsoft.com/azure/application-insights/app-insights-previews">예정된 변경 내용을 미리 보는</a> 방법에 대한 설명서 링크를 참조하세요.</p>


  <p>지금 이러한 기능을 사용해 보고 <a href="https://feedback.azure.com/forums/357324-application-insights">Application Insights UserVoice</a>에서 어떻게 생각하는지 알려주세요.</p>
