### YamlMime:Yaml
ms.openlocfilehash: 09e78e73ebc87c8170edc06c0214b09f283be841
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139902157"
Slug: ensuring-high-availability-of-web-applications-in-windows-azure
Title: Windows Azure에서 웹 애플리케이션의 고가용성 보장
Summary: Windows Azure 애플리케이션에서 플랫폼 업그레이드 중에 가용성이 손실되는 것을 방지하려면 웹 연결 역할의 인스턴스를 둘 이상 배포하는 것이 좋습니다. 수행 중...
Content: '<p><a target="_blank" href="https://windowsazure.com/">Windows Azure</a> 애플리케이션이 플랫폼 업그레이드 중에 가용성 손실이 발생할 수 없도록 하려면 웹 연결 역할의 인스턴스를 둘 이상 배포하는 것이 좋습니다. 이렇게 하면 지정된 애플리케이션에 대해 둘 이상의 역할 인스턴스가 배포될 때 인터넷 연결 역할에 대해 99.95% 외부 연결을 보장하는 Windows Azure Compute SLA(서비스 수준 계약)도 적용됩니다. &nbsp;전체 Windows Azure Compute SLA를 다운로드하려면 여기를 클릭하세요.</p>  <p><iframe scrolling="no" frameborder="0" src="https://www.facebook.com/plugins/like.php?href=;layout=box_count&amp;show_faces=false&amp;width=300&amp;action=like&amp;font=segoe+ui&amp;colorscheme=light&amp;height=50" style="width: 300px; height: 50px; overflow: hidden;"></iframe><br><a data-url="" data-count="horizontal" data-via="Windowsazure" href="https://twitter.com/share" class="twitter-share-button">짹짹</a>  <script src="https://platform.twitter.com/widgets.js" type="text/javascript"></script>  </p>'
