### YamlMime:Yaml
ms.openlocfilehash: 642f410d038aa46d6961700f3d3a04990ab059d6
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139899839"
Slug: estimate-throughput-requirements-for-documentdb-applications
Title: DocumentDB 처리량 요구 사항을 예측해야 합니까? 사용할 수 있는 새 계산기
Summary: Azure DocumentDB는 일반적인 애플리케이션 작업에 대한 요청 단위(처리량) 요구 사항을 예측하는 데 도움이 되는 새로운 웹 기반 도구를 출시했습니다.
Content: >-
  <p><a href="https://azure.microsoft.com/services/documentdb/">DocumentDB</a> 는 전 세계적으로 분산된 고가용성 앱을 위한 타오르는 빠른 행성 규모 NoSQL 데이터베이스 서비스입니다. <a href="https://azure.microsoft.com/en-us/blog/documentdb-goes-planet-scale-with-global-databases-new-pricing-and-more-developer-choices/">//Build 2016</a>에서 발표된 DocumentDB 가격 변경 및 크기 조정 옵션을 통해 많은 고객이 스토리지와 독립적으로 예약된 처리량을 구매하고 크기를 조정할 수 있는 기능을 활용할&#39;있습니다. 이를 통해 고객은 필요한 것에 대해서만 비용을 지불하고 필요할 때 스토리지 및 처리량을 확장할 수 있습니다. 고객이 처리량 예측을 미세 조정할 수 있도록&#39;다음과 같은 일반적인 작업에 대한 요청 단위 요구 사항을 예측하는 데 도움이 되는 새로운 <a href="https://www.documentdb.com/capacityplanner">웹 기반 도구를</a> 출시했습니다.</p>


  <ul style="margin-left: 40px;">
   <li>문서 만들기(쓰기)</li>
   <li>문서 읽기</li>
   <li>문서 삭제</li>
  </ul>


  <p>이 도구는 샘플 문서 및 처리량 요구 사항을 사용하여 애플리케이션&#39;요구 사항을 충족하는 데 필요한 요청 단위 수를 계산합니다. 요청 요금은 JSON 문서의 크기 및 모양(인덱싱된 속성 수)에 따라 다르므로 도구는 여러 샘플 문서를 지원합니다.</p>


  <p><img alt="" height="437" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/RUEstimatorResults.png" width="610"></p>


  <p>도구를 사용하는 방법에 대한 자세한 내용은 <a href="https://azure.microsoft.com/documentation/articles/documentdb-request-units/#estimating-throughput-needs">DocumentDB 문서의 요청 단위를</a> 참조하세요. 또한 애플리케이션&#39;프로비전된 리소스 요구 사항을 정확하고 효과적으로 예측할 수 있도록 이 도구를 계속 개선할&#39;있습니다.</p>


  <p>DocumentDB에 대한 자세한 내용은 <a href="https://azure.microsoft.com/services/documentdb/">DocumentDB 제품 페이지를 방문하세요</a>. 도움이 필요하거나 질문이나 피드백이 있는 경우 <a href="https://stackoverflow.com/questions/tagged/azure-documentdb">Stack Overflow의 개발자 포럼에</a> 문의하세요.</p>


  <p>Twitter <a href="https://twitter.com/DocumentDB">@DocumentDB</a>에서 팔로우하여 최신 DocumentDB 뉴스 및 기능을 최신 상태로 유지하세요.</p>
