### YamlMime:Yaml
ms.openlocfilehash: db0e755c6688b8a49491b34d58e9bdad17141a92
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139901254"
Slug: expanding-the-azure-stack-portfolio-to-run-hybrid-applications-across-the-cloud-datacenter-and-the-edge
Title: 클라우드, 데이터 센터 및 에지에서 하이브리드 애플리케이션을 실행하도록 Azure Stack 포트폴리오 확장
Summary: 2017년에 Azure Stack을 발표한 이후 클라우드를 고객의 데이터 센터로 확장하는 단계를 설정했습니다. 하이브리드 클라우드는 처음부터 Azure의 디자인 원칙 중 하나입니다.
Content: >-
  <p>2017년에 Azure Stack을 발표한 이후 클라우드&rsquo;를 고객&rsquo; 데이터 센터로 확장하는 단계를 설정했습니다. 하이브리드 클라우드는 처음부터 Azure의 디자인 원칙 중 하나입니다. 현재 홍콩 거래소 및 클리어링 리미티드, <a href="https://www.youtube.com/watch?v=eexMnJyFj28" target="_blank">KPMG 노르웨이</a>, <a href="https://www.youtube.com/watch?v=nhbuox9eWdA&amp;t=2s" target="_blank">에어버스</a> 및 <a href="https://www.youtube.com/watch?v=Z64yEqbRbOk" target="_blank">몰타 정보 기술 기관을</a> 포함한 고객은 IT 민첩성을 개선하고 효율성을 극대화하며 새로운 비즈니스 시나리오를 가능하게 하기 위해 퍼블릭 클라우드와 연결되거나 연결이 끊어질 수 있는 Azure Stack으로 구동되는 하이브리드 솔루션을 구축하고 있습니다.&nbsp;&nbsp; <img align="right" alt="Image of Editor's choice 2019 StorageReview award" border="0" height="295" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/c694eb19-ba15-4010-97a6-e828b4bb19f8.jpg" style="margin: 0px 0px 0px 7px; border: 0px currentcolor; border-image: none; float: right; display: inline; background-image: none;" title="편집자가 선택한 2019 StorageReview 상 이미지" width="452"></p>


  <p>6개월 전에 Azure Stack HCI를 사용하여 Azure Stack 제품군에 추가를 발표했습니다. 그 이후로 기업은 Azure Stack HCI를 사용하여 데이터 센터를 현대화하고, 하드웨어 및 스토리지를 새로 고치고 통합하며, Windows 관리 센터를 사용하여 Azure Site Recovery 및 Azure Backup을 포함한 Azure 서비스를 활용하고 있습니다. 기업은 <a href="https://www.storagereview.com/node/7484" target="_blank">이 범주</a>에서 가장 성능이 뛰어난 시스템 중 하나에서 중요 업무용 애플리케이션을 실행하고 있습니다. StorageReview.com 따르면, &ldquo;이 숫자에서 볼 수 있듯이 테스트 중인 DataON 클러스터(Azure Stack HCI)&rsquo;는 시장 중반 4노드 HCI 클러스터에서 가장 빠른 weve&rsquo;인 엄청난 숫자를 게시했습니다.&rdquo; 이제 Azure Stack HCI 카탈로그에 20개의 OEM(원본 장비 제조업체)의 150개 이상의 솔루션이 있습니다.</p>


  <p>올해 초, 소매, 제조, 정부 및 기타 산업에서 흔히 볼 수 있는 혁신적인 에지 컴퓨팅 시나리오를 해결하기 위해 Intel Arria 10 FPGA를 사용하는 <a href="https://www.cnbc.com/2018/09/24/microsoft-designs-ai-hardware-boxes-for-use-outside-of-data-centers.html" target="_blank">AI 지원 에지 컴퓨팅 어플라이언</a> 스인 Azure Data Box Edge의 일반 공급도 발표했습니다. 예를 들어 <a href="https://venturebeat.com/2019/05/10/microsoft-is-addressing-tough-paradigms-on-the-intelligent-edge-with-azure-data-boxes/" target="_blank">소매점은 Data Box Edge의 Azure Machine Learning 기능을 사용하여</a> 재고를 추적하고 소비자&rsquo; 소매 환경을 현대화할 수 있습니다.</p>


  <p>고객과의 관계를 계속 강화하면서 배포 패턴(클라우드 네이티브, 컨테이너, VM(가상 머신), 관리되는 서비스)에서 환경 조건, 규제 환경, 레거시 및 최신 앱, 용량 요구 사항 및 채택 곡선에 이르기까지 다양한 요구 사항을 충족해야 한다는 요구를 듣습니다.</p>


  <p>&rsquo;오늘날, Azure Stack 포트폴리오에 대한 새로운 투자, 기능 및 폼 팩터를 공유하여 에지 인프라가 고객&rsquo; 솔루션에 원활하게 부합하도록 하게 되어 매우 기쁩니다. 오늘 소식을 통해 Azure Stack은 Azure Stack HCI, Azure Stack Hub(이전의 Azure Stack) 및 Azure Stack Edge(이전의 Azure Data Box Edge)로 구성된 제품 포트폴리오를 포함하도록 확장될 예정입니다.</p>


  <h2>Azure Stack 포트폴리오</h2>


  <p>Azure Stack 포트폴리오는 데이터 센터, 에지 위치, 원격 사무실 및 클라우드에서 하이브리드 애플리케이션을 지속적으로 빌드하고 실행하는 Azure의 확장입니다. Azure Stack은 퍼블릭 클라우드에서 연결 또는 연결이 끊어질 수 있는 Azure Stack Hub를 사용하는 일관된 하이브리드 클라우드 온-프레미스에서 Azure Stack HCI를 사용하는 고성능 가상화 온-프레미스 또는 Azure Stack Edge를 통해 에지에서 지능형 컴퓨팅 및 AI를 제공하는 Azure 관리형 어플라이언스에 이르기까지 솔루션 요구 사항에 따라 고객에게 선택과 유연성을 제공합니다.</p>


  <p><img alt="Azure Stack portfolio including of Azure Stack Edge, Azure Stack HCI, and Azure Stack Hub" border="0" height="1081" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/27413067-c64e-4627-a47c-2025a662704a.jpg" style="border: 0px currentcolor; border-image: none; display: inline; background-image: none;" title="Azure Stack Edge, Azure Stack HCI 및 Azure Stack Hub를 포함한 Azure Stack 포트폴리오" width="1902"></p>


  <h3>Azure Stack Edge</h3>


  <p>Azure Stack Edge는 Azure의 컴퓨팅, 스토리지 및 인텔리전스를 에지에 제공하는 Azure 관리 어플라이언스입니다. 선불 비용 없이 Azure 서비스를 실행하기 위해 고객에게&rsquo; 제공되는 자사 Microsoft 어플라이언스입니다(Azure 청구서에서 매월 지불). 고객은 Azure Portal을 사용하여 Azure Stack Edge를 주문하고 프로비전할 수 있습니다. Azure 관리 도구는 업데이트를 모니터링하고 실행하는 데 사용됩니다. Azure Stack Edge를 사용하면 개발자 도구에서 액세스 제어, 워크로드 관리에 이르기까지 모든 클라우드 및 에지에서 일관된 환경을 얻을 수 있습니다.<img align="right" alt="Azure Stack Edge Ruggedized backpack" border="0" height="323" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/1d25f9d1-a0f5-4308-8ce8-2e673a7efce1.jpg" style="margin: 0px 0px 0px 10px; border: 0px currentcolor; border-image: none; float: right; display: inline; background-image: none;" title="Azure Stack Edge 러기드 백팩" width="485"></p>


  <p>Azure Stack Edge가 곧 가상 머신, Kubernetes 클러스터, NVIDIA GPU 지원 및 고가용성 지원을 비롯한 새로운 컴퓨팅 및 AI 기능을 지원할 것임을 공유하게 되어 기쁘게 생각합니다. 이러한 기능을 통해 Azure Stack Edge는 시장에서 에지 컴퓨팅의 최전선으로 빠르게 발전하고 있습니다. 또한 Azure Stack Edge에 MEC(다중 액세스 에지 컴퓨팅)의 기술 미리 보기를 추가하여 프라이빗 셀룰러 네트워크를 서비스로 사용하도록 설정하고 있습니다.</p>


  <p>Azure Stack Edge에는 현재 엔터프라이즈 데이터 센터 또는 에지 위치에 대한 상업용 시리즈가 포함되어 있습니다. 가혹한 환경이있는 사이트에 대한 러기드 시리즈는 <a href="https://blogs.microsoft.com/bayarea/2019/10/31/dean-paron-shows-the-impact-of-azure-data-box-edge/" target="_blank">배낭에 운반 할 수있는 배터리 구동 폼 팩터</a>를 포함하여 곧 출시 될 예정입니다. 이러한 Azure Stack Edge 폼 팩터 및 클라우드 관리 기능의 다재다능함은 소매점, 공장 현장, 병원, 현장 운영, 재해 지역 및 구조 작업에 클라우드 인텔리전스 및 컴퓨팅을 제공합니다.</p>


  <p><iframe allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen="" frameborder="0" height="315" src="https://www.youtube.com/embed/2K-DOWjV_vU?rel=0" width="560"></iframe></p>


  <h3>Azure Stack HCI</h3>


  <p>고객이 HCI 아키텍처를 가장 효율적으로 선택할 수 있도록 Microsoft Ignite에서 Azure Stack HCI 프로그램의 확장을 도입하고 있습니다. Azure Stack HCI 유효성 검사 프로그램 외에도 HCI 아키텍처에 가장 인기 있는 많은 워크로드에 대해 솔루션을 최적화할 수 있습니다. 지점 및 에지는 2노드, 복원력 있는 가상 및 컨테이너화된 애플리케이션, 가상 데스크톱 인프라를 사용하여 자체 디바이스를 가져오고 회사 데이터를 보호할 수 있습니다. 고성능 Microsoft SQL Server  가상 환경에서 최적화된 데이터베이스 작업을 제공하기 위해 하드웨어에서 OS로 보안 구현 지침을 활용하는 신뢰할 수 있는 엔터프라이즈 가상화 및 스케일 아웃 스토리지를 사용하여 원격 스토리지 구현을 위한 고가용성 스토리지를 확장합니다.</p>


  <p>이러한 워크로드에 최적화된 Azure Stack HCI 카탈로그의 솔루션은 이제 카탈로그에 특별한 지정으로 표시되므로 잠재 고객이 워크로드에 가장 적합한 선택을 쉽게 식별할 수 있습니다. 이러한 각 워크로드는 Azure Stack HCI를 사용하여 연결된 하이브리드 솔루션을 매우 쉽게 배포할 수 있는 Windows Admin Center를 활용하여 Azure의 부가 가치 서비스와 결합할 수 있습니다.</p>


  <p>고객의 요구에 대응하여 범용 Kubernetes를 포함한 추가 워크로드가 개발 중입니다.</p>


  <h3>Azure Stack Hub</h3>


  <p>Azure Stack Hub는 엔터프라이즈 및 공공 부문 고객, 특히 공용 인터넷과 연결이 끊어진 클라우드 환경을 운영하거나 규정 및 규정 준수 요구 사항을 충족하는 데 관심이 있는 고객을 위한 클라우드 네이티브 제품이 될 것입니다. &rsquo;NVIDIA V100 GPU에서 사용하도록 설정된 N 시리즈 가상 머신을 포함하여 Azure Stack Hub 로드맵에 대한 몇 가지 새로운 업데이트를 공유합니다. 또한 Azure Stack Hub에서 Kubernetes의 일반 공급도 발표할&#39;있습니다. 이제 AKS(Azure Kubernetes Service) 엔진을 사용하여 Azure Stack Hub에서 Kubernetes 클러스터를 쉽게 프로비전하여 Kubernetes 클러스터의 생성, 업데이트 및 크기 조정을 자동화할 수 있습니다. 2020년 상반기에는 Event Hubs 및 Azure Stream Analytics도 공개 미리 보기로 사용할 수 있습니다.</p>


  <h3>Azure Arc 및 Azure Stack 포트폴리오</h3>


  <p>Microsoft Ignite에서는 모든 인프라에 Azure 서비스 및 관리를 제공하기 위한 Azure <a href="https://azure.microsoft.com/services/azure-arc/" target="_blank">Arc</a> 의 미리 보기를 발표했습니다. Azure Arc를 사용하면 모든 Kubernetes 클러스터에 Azure SQL 데이터베이스를 배포할 수 있습니다. Azure Arc 및 Azure Stack 포트폴리오는 상호 보완적입니다. Azure Arc의 이점을 Azure Stack 포트폴리오와 결합하면 Azure Arc가 Azure Stack의 컴퓨팅 및 클라우드 기능을 활용하여 유효성이 검사되고 통합된 시스템의 Azure Stack 포트폴리오에서 가상 머신, 컨테이너를 관리하고 Azure Data Services를 실행할 수 있습니다.</p>


  <p>Azure Stack 포트폴리오 전용 세션 12개, 여러 엑스포 부스 및 파트너 전시회를 포함하여 바쁜 Ignite가 있습니다. 또한 Intel과 협력하여 Ignite 2019 엑스포 플로어에서 인텔리전트 리테일 환경을 시연했으므로 방문해 보세요!</p>


  <hr>

  <p><em>Azure. 목적에 따라 발명.</em></p>
