### YamlMime:Yaml
ms.openlocfilehash: d299c985ca2bc1fd2db6451ad73fa02ba8f1240c
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139902582"
Slug: experts-tips-on-hardening-security-with-azure-security
Title: Azure 보안으로 보안 강화에 대한 전문가 팁
Summary: Microsoft Azure 고객이 인프라 및 애플리케이션을 호스트할 수 있는 안전한 기반을 제공합니다. Microsoft...
Content: >-
  <p><em>참고: 이 블로그는 Microsoft 위협 인텔리전스 센터에서 작성했습니다.</em></p>


  <p>Microsoft Azure 고객이 인프라 및 애플리케이션을 호스트할 수 있는 안전한 기반을 제공합니다. Microsofts&rsquo;는 물리적, 인프라 및 운영 보안 전반에 걸쳐 기초를 보호합니다. 운영 보안의 일부로 보안 연구 및 개발에 전념하는 여러 팀에 걸쳐 3,500명 이상의 사이버 보안 전문가가 포함됩니다. Microsoft 위협 인텔리전스 센터는 보안 환경 전반에 걸쳐 위협을 발생시키고 완화하는 Microsoft의 보안 팀 중 하나일 뿐입니다.</p>


  <p>Microsoft Mechanics&rsquo;의 오늘&rsquo; 에피소드에서는 Microsoft 위협 인텔리전스 센터의 작업이 Azure 및 글로벌 보안 환경을 보호하는 데 어떻게 도움이 되는지 확인할 수 있습니다. 이 팀은 피어 투 피어 네트워킹 소프트웨어, 표준 봇넷 및 랜섬웨어 공격, 해커 또는 국가 국가 후원 그룹의 악의적 위협과 같은 문제를 식별하기 위해 노력하고 있습니다.</p>


  <p>또한 팀은 여러 지역에 걸쳐 광범위한 시각을 가지며 Azure에서 실행되는 서비스에 대한 보기를 제공합니다. 이 인사이트를 통해 팀은 일반적인 공격 패턴을 볼 수 있습니다. 이러한 패턴은 네트워크 수준, 서비스 수준, 앱 수준 또는 OS 수준에 있을 수 있습니다. 악용이 감지되는 즉시 Microsoft 위협 인텔리전스 센터는 Microsoft의 다른 팀과 협력하여 제품 및 서비스에 대한 완화를 구축합니다. 또한 팀은 공격이 발생한 위치, 영향을 받은 환경 및 공격을 수정하기 위해 수행해야 하는 단계와 같은 세부 정보를 제공하는 위협 인텔리전스 보고서를 만듭니다.&nbsp;</p>


  <p>Microsoft 위협 인텔리전스 센터가 Azure 플랫폼을&rsquo; 대상으로 하는 공격을 완화하는 방법 외에도 해당 인텔리전스가 서비스에 다시 공급되는 방법과 이러한 도구를 사용하여 조직 보안을 강화하는 방법을 알아봅니다. 예를 들어 <a href="https://azure.microsoft.com/en-us/services/security-center/">Azure Security Center</a> 를 사용하여 하이브리드 클라우드 리소스의 보안 상태에 대한 중앙 집중식 실시간 모니터링 보기를 가져와서 문제에 대한 조치를 신속하게 수행할 수 있습니다. 또한 Security Centers&rsquo; Just-In-Time VM 액세스를 사용하여 가상 머신 관리 포트에 대한 액세스를 필요한 경우에만 줄여 무차별 암호 대입 공격 등의 위협으로부터 보호할 수 있습니다. Security Centers&rsquo; 조사 경로는 SQL 삽입과 같이 공격과 관련된 모든 엔터티를 탐색하고 공격에 대해 신속하게 수정하는 데 도움이 됩니다.</p>


  <p>오늘&rsquo; 개요가 도움이 되기를 바랍니다. 여러분의 의견을 알려주세요. 자유롭게 질문을 게시해 주세요.</p>


  <p style="text-align: center;"><iframe allow="autoplay; encrypted-media" allowfullscreen="" frameborder="0" height="315" src="https://www.youtube.com/embed/n58eHSLoU9w" width="560"></iframe></p>
