### YamlMime:Yaml
ms.openlocfilehash: 093072cfaaacf143ca52f932e003c05208eeb97c
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139911055"
Slug: gain-application-insights-for-big-data-solutions-using-unravel-on-azure-hdinsight
Title: Azure HDInsight에서 해명 데이터를 사용하여 빅 데이터 솔루션에 대한 애플리케이션 인사이트 얻기
Summary: HDInsight에서 해명하면 개발자와 IT 관리자가 성능, 자동 크기 조정 & 비용 최적화를 그 어느 때보다 효율적으로 관리할 수 있습니다. Azure HDInsight 애플리케이션 플랫폼에서 해명을 발표하게 되어 기쁘게 생각합니다.
Content: >-
  <p>HDInsight에서 해명하면 개발자와 IT 관리자가 성능을 관리하고 비용 최적화를 자동으로 스케일링할 &amp; 수 있습니다.</p>


  <p><a href="https://azure.microsoft.com/en-us/services/hdinsight/partner-ecosystem/" target="_blank">Azure HDInsight 애플리케이션 플랫폼에서</a> <a href="https://unraveldata.com/" target="_blank">해명을</a> 발표하게 되어 기쁘게 생각합니다. <a href="https://azure.microsoft.com/en-us/services/hdinsight/" target="_blank">Azure HDInsight</a> 는 엔터프라이즈를 위한 완전 관리형 오픈 소스 빅 데이터 분석 서비스입니다. 인기 있는 오픈 소스 프레임워크(<a href="https://docs.microsoft.com/en-us/azure/hdinsight/hadoop/apache-hadoop-introduction" target="_blank">Hadoop</a>, <a href="https://docs.microsoft.com/en-us/azure/hdinsight/spark/apache-spark-overview" target="_blank">Spark</a>, <a href="https://docs.microsoft.com/en-us/azure/hdinsight/interactive-query/apache-interactive-query-get-started" target="_blank">LLAP</a>, <a href="https://docs.microsoft.com/en-us/azure/hdinsight/kafka/apache-kafka-introduction" target="_blank">Kafka</a>, <a href="https://docs.microsoft.com/en-us/azure/hdinsight/hbase/apache-hbase-overview" target="_blank">HBase</a> 등)를 사용하여 ETL, 데이터 웨어하우징, Machine Learning, IoT 등과 같은 광범위한 시나리오를 다룰 수 있습니다. Unravel는 이러한 시나리오 등에 대한 포괄적인 APM(애플리케이션 성능 관리)을 제공합니다. 이 애플리케이션은 고객이 애플리케이션 성능 문제를 분석, 최적화 및 해결하고 매끄럽고 사용하기 쉽고 마찰 없는 방식으로 SLA를 충족하는 데 도움이 됩니다. 일부 고객은 HDInsight의 해명&rsquo; 튜닝 기능을 사용하여 50% 더 저렴한 비용으로 최대 200% 더 많은 작업을 보고합니다.</p>


  <p>자세한 내용은 클라우드 비용을 예산 내에서 유지하면서 <a href="https://info.unraveldata.com/webinar-lp-big-data-apps-microsoft-azure-hdinsight.html?utm_source=msft&amp;utm_medium=msft&amp;utm_campaign=180613_webinar&amp;utm_content=msft" target="_blank">Azure에서 빠르고 신뢰할 수 있는 빅 데이터 앱을 빌드하는 방법을</a> 알아보려면 6월 13일 웨비나에서 <a href="https://www.linkedin.com/in/rastogipranav/" target="_blank">Pranav Rastogi</a>, Microsoft Azure 빅 데이터의 프로그램 관리자, Unravel의 <a href="https://www.linkedin.com/in/shivnath-babu-82607550/" target="_blank">Shivnath Babu</a> CTO에 참여하세요.</p>


  <h2>빅 데이터 솔루션에서 SLA를 보장하는 것은 얼마나 복잡한가요?</h2>


  <p>빅 데이터 시스템의 내재된 복잡성, 모니터링을 위한 이질적인 도구 집합 및 이러한 오픈 소스 프레임워크 최적화에 대한 전문 지식의 부족은 SLA를 보장하는 최종 사용자에게 중요한 과제를 야기합니다. 현재 사용자는 클러스터 상태, 성능 및 사용률을 관리하는 인프라 메트릭만 제공하는 <a href="https://docs.microsoft.com/en-us/azure/hdinsight/hdinsight-troubleshoot-failed-cluster" target="_blank">Ambari</a> 를 사용하여 애플리케이션을 모니터링해야 합니다. 빅 데이터 솔루션은 다양한 오픈 소스 프레임워크를 사용합니다. 이러한 모든 프레임워크에서 실행되는 애플리케이션을 모니터링하는 것은 어려운 작업입니다. 사용자는 YARN, Hive, Tez, LLAP, Pig, Spark, Kafka 등 <a href="https://docs.microsoft.com/en-us/azure/hdinsight/hdinsight-hadoop-access-yarn-app-logs-linux" target="_blank">에서 로그를 분석하여</a> 문제를 수동으로 해결해야 합니다. 성능을 향상시키려면 사용자는 <a href="https://docs.microsoft.com/en-us/azure/hdinsight/spark/apache-spark-perf" target="_blank">Spark 실행기</a>, YARN 큐, Kafka 토픽 구성, HBase의 지역 서버, 스토리지 제한, 컴퓨팅 크기 조정 등의 설정을 변경해야 할 수 있습니다. 이러한 복잡성을 해명하는 것은 예술과 과학입니다.</p>


  <h2>이제 Unravel을 사용하여 빅 데이터 애플리케이션 모니터링이 쉬워집니다.</h2>


  <p>HDInsight의 해명은 빅 데이터에 대한 지능형 애플리케이션 및 운영 관리를 제공합니다. 애플리케이션 성능 관리는 전체 스택 성능의 상관 관계를 지정하고 자동화된 인사이트와 권장 사항을 제공합니다. 이제 사용자는 문제 해결을 분석하고 성능을 쉽게 최적화할 수 있습니다. HDInsight에서의 해명에 대한 주요 가치 제안은 다음과 같습니다.</p>


  <h3>자동 관리 경고 및 자동 작업</h3>


  <ul>
   <li>SLA가 누락되거나, 사용 정책을 위반하거나, 클러스터에서 실행되는 다른 애플리케이션에 영향을 주는 애플리케이션에 대한 사전 경고입니다.</li>
   <li>동적 임계값 및 잘못된 애플리케이션을 종료하고 우선 순위 수준에 따라 앱을 다시 지시하는 것과 같은 회사 정의 정책을 사용하여 위의 문제를 해결하는 자동 작업입니다.</li>
  </ul>


  <h3>앱 성능 분석</h3>


  <ul>
   <li>병목 상태, 문제 영역 및 오류에 대한 드릴다운 기능을 사용하여 애플리케이션 성능에 대한 직관적인 엔드 투 엔드 보기입니다.</li>
   <li>리소스 할당, 컨테이너 사용률, 잘못된 구성 설정, 작업 실행 패턴, 데이터 레이아웃, 리소스 경합 등 앱 성능에 영향을 주는 모든 요인에 대한 상관 관계 인사이트입니다.</li>
   <li>애플리케이션으로 인한 성능 및 비용 문제를 신속하게 검색합니다.</li>
  </ul>


  <p>다음은 해명에서 Tez 애플리케이션의 Hive로 인한 리소스 사용량 저하 및 높은 비용을 진단하는 방법의 예입니다. Unravel에서 제공하는 권장 사항을 사용하여 애플리케이션을 조정하면 이 애플리케이션을 실행하는 비용이 10배 감소했습니다.</p>


  <p><img alt="cost_wastage" border="0" height="408" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/67056bf9-d884-40fc-a6f9-cdcbf437f1b6.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="cost_wastage" width="610"></p>


  <p>다음은 Unravel를 사용한 후 클러스터 사용률의 예입니다. 해명하면 리소스를 효율적으로 활용 <a href="https://unraveldata.atlassian.net/wiki/spaces/UN42/pages/486539455/Autoscaling+HDInsight+Spark+Cluster+using+Unravel+API" target="_blank">하고 SLA 요구 사항에 따라 클러스터의 크기를 자동으로 조정</a>하여 비용을 절감할 수 있습니다.</p>


  <p><img alt="auto_scaling" border="0" height="278" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/6a2a826e-7410-47c5-8d79-57a771f4cfd5.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="auto_scaling" width="610"></p>


  <h3>AI 기반 지능형 권장 사항 엔진</h3>


  <ul>
   <li>데이터 병렬 처리, 최적의 컨테이너 크기, 작업 수 등을 포함하여 가장 빠른 실행 및/또는 최소 리소스 사용률에 최적 값을 권장합니다.</li>
  </ul>


  <p>아래 예제에서는 Unravels&rsquo; AI 기반 엔진이 Hive 쿼리의 최적의 성능을 위해 실행 가능한 권장 사항을 제공하는 방법을 보여 줍니다.</p>


  <p><img alt="tez_recommendations" border="0" height="263" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/659370ab-159b-4607-ae77-6b97f34b66c0.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="tez_recommendations" width="610"></p>


  <ul>
   <li>잘못된 실행, 기울이기, 비용이 많이 드는 조인, 너무 많은 매퍼/감속기, 캐싱 등과 관련된 문제를 식별하고 자동으로 해결합니다.</li>
  </ul>


  <p>다음은 Spark Streaming Kafka를 사용하여 실시간 IoT 애플리케이션에서 지연을 자동으로 감지<a href="https://docs.microsoft.com/en-us/azure/hdinsight/hdinsight-apache-kafka-spark-structured-streaming?toc=%2Fen-us%2Fazure%2Fhdinsight%2Fkafka%2FTOC.json&amp;bc=%2Fen-us%2Fazure%2Fbread%2Ftoc.json" target="_blank">하고 &amp;</a> 솔루션을 권장하는 해명<u> </u>예제입니다.</p>


  <p><img alt="Streaming recommendations" border="0" height="221" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/ad608360-3e2e-4ee0-a87e-dead579480db.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="스트리밍 권장 사항" width="610"></p>


  <h2>HDInsight에서 해명 시작</h2>


  <p>고객은 Azure Portal에서 한 번의 클릭으로 HDInsight에 Unravel을 쉽게 설치할 수 있습니다. Unravel는 Azure HDInsight에서 Hadoop, Hive, Spark, Kafka, LLAP 등과 같은 오픈 소스 프레임워크를 사용하여 빅 데이터 애플리케이션의 동작에 대한 라이브 보기를 제공합니다.</p>


  <p><img alt="Installing unravel" border="0" height="312" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/01f58206-5c25-4918-95b5-469a7f2efa2d.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="해명 설치" width="610"></p>


  <p>설치 후 아래와 같이 클러스터의 애플리케이션 블레이드에서 Unravel 애플리케이션을 시작할 수 있습니다.</p>


  <p><img alt="Launching unravel data" border="0" height="295" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/917b72da-5484-41c5-a2cf-330c684ec6e0.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="해명 데이터 시작" width="610"></p>


  <h2>HDInsight에서 지금 해명해 보세요!</h2>


  <ul>
   <li><a href="https://azure.microsoft.com/en-us/services/hdinsight/" target="_blank">Azure HDInsight에 대해 자세히 알아보기</a></li>
   <li><a href="https://unraveldata.com/unravel-data-collaborates-microsoft-azure-boost-performance-reliability-big-data-workloads-cloud/" target="_blank">해명 보도 자료</a></li>
   <li><a href="https://unraveldata.atlassian.net/wiki/spaces/UN42/pages/423264310/Install+Unravel+HDInsight+app" target="_blank">HDInsight에서 해명 시작 가이드</a></li>
   <li><a href="https://www.youtube.com/watch?v=kEZnsfsC-eE" target="_blank">HDInsight에서 해명 사용 비디오</a></li>
   <li><a href="https://unraveldata.atlassian.net/wiki/spaces/UN42/pages/486539455/Autoscaling+HDInsight+Spark+Cluster+using+Unravel+API" target="_blank">비즈니스 SLA를 기반으로 해명을 사용하여 HDInsight 클러스터 자동 크기 조정</a></li>
   <li><a href="https://unraveldata.com/" target="_blank">해명 웹 사이트</a></li>
   <li><a href="https://azure.microsoft.com/en-us/services/hdinsight/partner-ecosystem/" target="_blank">HDInsight 애플리케이션 플랫폼에서 더 많은 애플리케이션 알아보기</a></li>
  </ul>


  <h2>웨비나에 참석하세요!</h2>


  <p>자세한 내용은 6월 13일 웹 세미나에서 <a href="https://www.linkedin.com/in/rastogipranav/" target="_blank">Pranav Rastogi</a>, Microsoft Azure 빅 데이터의 프로그램 관리자, Unravel의 <a href="https://www.linkedin.com/in/shivnath-babu-82607550/" target="_blank">Shivnath Babu</a> CTO에 참여하여 클라우드 비용을 예산 내에서 유지하면서 <a href="https://info.unraveldata.com/webinar-lp-big-data-apps-microsoft-azure-hdinsight.html?utm_source=msft&amp;utm_medium=msft&amp;utm_campaign=180613_webinar&amp;utm_content=msft" target="_blank">Azure에서 빠르고 신뢰할 수 있는 빅 데이터 앱을 빌드하는 방법에</a> 대해 알아보세요.</p>


  <h2>요약</h2>


  <p>Azure HDInsight는 <a href="https://docs.microsoft.com/en-us/azure/hdinsight/hadoop/apache-hadoop-introduction" target="_blank">Hadoop</a>, <a href="https://docs.microsoft.com/en-us/azure/hdinsight/spark/apache-spark-overview" target="_blank">Spark</a>, <a href="https://docs.microsoft.com/en-us/azure/hdinsight/hadoop/apache-hadoop-linux-create-cluster-get-started-portal" target="_blank">Hive</a>, <a href="https://docs.microsoft.com/en-us/azure/hdinsight/interactive-query/apache-interactive-query-get-started" target="_blank">LLAP</a>, <a href="https://docs.microsoft.com/en-us/azure/hdinsight/kafka/apache-kafka-introduction" target="_blank">Kafka</a>, <a href="https://docs.microsoft.com/en-us/azure/hdinsight/hbase/apache-hbase-overview" target="_blank">HBase</a>, <a href="https://docs.microsoft.com/en-us/azure/hdinsight/storm/apache-storm-overview" target="_blank">Storm</a> 등과 같은 광범위한 완전 관리형 프레임워크를 제공하는 가장 포괄적인 플랫폼입니다. <a href="https://unraveldata.com/" target="_blank">해명을</a> 포함하도록 <a href="https://azure.microsoft.com/en-us/blog/azure-hdinsight-application-platform-install-solutions-built-for-the-apache-hadoop-ecosystem/" target="_blank">HDInsight 애플리케이션 플랫폼</a>의 확장을 발표하게 되어 기쁘게 생각합니다. Unravel는 고객이 애플리케이션 성능 문제를 분석, 최적화 및 해결하고 원활하고 사용하기 쉽고 마찰 없는 방식으로 SLA를 충족할 수 있도록 다양한 오픈 소스 분석 프레임워크에서 포괄적인 APM(애플리케이션 성능 관리)을 제공합니다.<a name="_GoBack"></a></p>


  <p>Twitter <a href="https://twitter.com/search?q=%23HDInsight&amp;src=typd" target="_blank">#HDInsight</a> 및 <a href="https://twitter.com/AzureHDInsight" target="_blank">@AzureHDInsight</a>에서 팔로우하여 최신 Azure HDInsight 뉴스 및 기능을 최신 상태로 유지하세요. 질문 및 피드백은 다음으로 <a href="mailto:AskHDInsight@microsoft.com">AskHDInsight@microsoft.com</a>문의하세요.</p>
