### YamlMime:Yaml
ms.openlocfilehash: 182310525bec08de413748abab7543eca654c2d2
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139897371"
Slug: general-availability-of-user-behavior-analytics-tools-in-azure-application-insights
Title: Azure Application Insights 사용자 동작 분석 도구의 일반 공급
Summary: Microsoft Build 2017에서는 애플리케이션 Insights 대한 사용자 동작 분석 도구 집합을 미리 보기로 도입했습니다. 그 이후로 사용자 의견을 듣고 추가 기능을 추가하고...
Content: >-
  <p>Microsoft Build 2017에서는 <a href="https://azure.microsoft.com/blog/new-tools-for-understanding-user-behavior-with-application-insights/" target="_blank">애플리케이션 Insights 대한 사용자 동작 분석 도구</a> 집합을 미리 보기로 도입했습니다. 그 이후로 Weve&rsquo;는 피드백을 듣고 추가 기능을 추가하고 버그를 스쿼시했습니다. 또한 Weve&rsquo;는 이러한 사용자 동작 분석 도구를 직접 사용하여 질문할 필요 없이 환경을 개선할 수 있는 기회를 찾았습니다.</p>


  <p>이 추가 폴란드어로, 오늘은&rsquo; 일반 공급에 미리 보기에서 이러한 도구를 졸업. 이러한 도구 &ndash; 사용자, 세션, 이벤트, 사용자 흐름, 깔때기, 보존, 코호트 및 영향 &ndash; 도구는 향후 애플리케이션 Insights 안정적이고 잘 지원되는 부분이 될 것으로 예상할 수 있습니다.&nbsp;</p>


  <h2>이러한 도구를 어떻게 시도할 수 있나요?</h2>


  <p>사용자, 세션, 이벤트 및 기타 사용자 동작 분석 도구는 Azure Portal의 각 애플리케이션 Insights 리소스의 일부입니다. 애플리케이션 Insights 시작하려면 <a href="https://docs.microsoft.com/azure/application-insights/" target="_blank">앱&rsquo; 스택에 따라 빠른 시작 중 하나를 수행합니다</a>. 애플리케이션 Insights 리소스&rsquo;가 있으면 사용 현황 아래&ldquo;의 왼쪽 메뉴에서 사용자 동작 분석 도구를 찾을 수 있습니다.&rdquo;</p>


  <h2>작년 이후 새로운 점은 무엇입니까&rsquo;?</h2>


  <p><em>많이!</em> 사용자, 세션 및 이벤트는 처음부터 다시 빌드되어 응답성이 더 높고, 더 빠르게 로드되며, 더 많은 인사이트를 자동으로 제공합니다. <a href="https://docs.microsoft.com/en-us/azure/application-insights/app-insights-usage-segmentation" target="_blank">사용자, 세션 및 이벤트에</a> 대해 자세히 알아봅니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/bed7cd85-8d89-4d20-9ec8-05815c25f2fb.png"><img alt="User, sessions, and events" border="0" height="799" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/15a7569a-69cc-4274-aa72-54e7b3d65c99.png" style="border: 0px currentcolor; border-image: none; display: inline; background-image: none;" title="사용자, 세션 및 이벤트" width="1429"></a></p>


  <p>또한 사용자 흐름, 깔때기, 영향, 사용자 및 세션 타임라인, Visual Studio App Center 통합 및 코호트를 포함한 6가지 주요 새로운 도구 및 통합을 추가했습니다.</p>


  <p><strong>사용자 흐름은</strong> 사용자가 앱의 페이지와 기능 사이를 탐색하는 방법을 한눈에 볼 수 있으므로 사용자가 여정을 시작하고 종료하는 위치&rsquo;와 그 사이에 수행하는 작업을 확인할 수 있습니다. <a href="https://docs.microsoft.com/en-us/azure/application-insights/app-insights-usage-flows" target="_blank">사용자 흐름</a>에 대해 자세히 알아봅니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/df7fc0e3-c41b-4732-9164-c384bfab162c.png"><img alt="User flows" border="0" height="801" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/1e275098-626e-44ea-9987-44e25b560128.png" style="border: 0px currentcolor; border-image: none; display: inline; background-image: none;" title="사용자 흐름" width="1429"></a></p>


  <p><strong>깔때기를</strong> 사용하면 팀이 웹앱의 주요 여정에 대한 변환 속도를 자세히 추적할 수 있습니다. 각 단계에서 완료하고 중단한 사용자를 분석하여 팀이 제품&rsquo; 전환율을 개선하는 데 도움을 줄 수 있습니다. <a href="https://docs.microsoft.com/en-us/azure/application-insights/usage-funnels" target="_blank">깔때기에</a> 대해 자세히 알아보세요.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/72c69d83-dbf8-4f28-b35d-944933ca8e5d.png"><img alt="Funnels" border="0" height="784" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/8f37076a-302d-4a4e-b97b-7b2fc89ef38b.png" style="border: 0px currentcolor; border-image: none; display: inline; background-image: none;" title="퍼 널" width="1429"></a></p>


  <p>느린 페이지 로드 시간 때문에 비즈니스에서 테이블에 돈을 남기고 있습니까? <strong>영향</strong> 도구는 페이지 로드 시간 또는 다른 메트릭 간의 관계와 해당 페이지의 작업으로의 변환 속도를 분석합니다. 이렇게 하면 개발 팀이 데이터 기반 방식으로 성능 향상에 투자할 수 있습니다. <a href="https://docs.microsoft.com/en-us/azure/application-insights/app-insights-usage-impact" target="_blank">Impact</a>에 대해 자세히 알아보세요.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/1ca09c97-f56f-47ef-b26a-16027b146413.png"><img alt="Impact" border="0" height="804" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/8e58a401-3c3d-42e7-b43b-a43f08410f26.png" style="border: 0px currentcolor; border-image: none; display: inline; background-image: none;" title="영향" width="1429"></a></p>


  <p><strong>사용자 및 세션 타임라인은 로그가</strong> 전송되었을 때 고객이 수행한 작업 측면에서 사용자 작업, 예외 및 기타 로그를 컨텍스트화하는 데 도움이 됩니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/1e00e917-673c-4ff4-9fdb-5d7ed76dfff1.png"><img alt="User and session timelines" border="0" height="809" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/7c7ac79e-521d-4201-9381-b6ac76661340.png" style="border: 0px currentcolor; border-image: none; display: inline; background-image: none;" title="사용자 및 세션 타임라인" width="1432"></a></p>


  <p><strong>코호트를</strong> 사용하면 사용자, 세션, 이벤트 또는 작업의 정확한 그룹을 정의할 수 있으므로 다른 사용자 동작 분석 도구에서 보다 쉽게 분석할 수 있습니다. <a href="https://docs.microsoft.com/en-us/azure/application-insights/app-insights-usage-cohorts" target="_blank">코호트에</a> 대해 자세히 알아보세요.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/245d26b6-907d-4c08-b52c-61b1100df150.png"><img alt="Cohorts" border="0" height="702" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/cd09d3e4-0078-4ea6-945a-756cd79e68a1.png" style="border: 0px currentcolor; border-image: none; display: inline; background-image: none;" title="동료" width="1280"></a></p>


  <p>마지막으로, 이러한 사용자 동작 분석 도구는 웹앱을 넘어갑니다. <strong>Visual Studio App Center 통합</strong>을 사용하면 고객&rsquo; Android, iOS 및 Windows 디바이스에서 보낸 App Center 원격 분석 복사본을&rsquo; 애플리케이션 Insights 보낼 수 있습니다. 그런 다음, 모바일 앱 원격 분석의 애플리케이션 Insights 이러한 모든 분석 도구를 사용할 수 있습니다. <a href="https://docs.microsoft.com/en-us/azure/application-insights/app-insights-mobile-center-quickstart" target="_blank">Application Insights App Center 통합</a>에 대해 자세히 알아봅니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/831fdfe2-1246-4743-92dd-7f16e0fe8aca.png"><img alt="Visual Studio App Center integration" border="0" height="825" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/9bfd87b5-d8fe-460d-a711-6c43a724a321.png" style="border: 0px currentcolor; border-image: none; display: inline; background-image: none;" title="App Center 통합 Visual Studio" width="1429"></a></p>


  <p>자세히 알아보시겠어요? <a href="https://docs.microsoft.com/azure/application-insights/app-insights-usage-overview" target="_blank">애플리케이션 Insights 사용자 동작 분석 도구</a>에 대한 설명서 페이지를 방문하여 자세히 알아보세요.</p>
