### YamlMime:Yaml
ms.openlocfilehash: b34a5b9ca55f16d49b6e8e65ca21526ff4fbdb14
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139903254"
Slug: getting-started-with-iot-driving-business-action-through-analytics-and-automation
Title: 'IoT 시작: 분석 및 자동화를 통한 비즈니스 작업 추진'
Summary: 현재 인사이트 또는 장기적인 추세를 찾고 있든, 정보의 가치는 비즈니스의 유용성만큼이나 유용합니다. 일부 정보는 즉시 조치를 취해야 하지만 시간이 지남에 따라 추세에 대한 장기적이고 큰 그림 분석을 위해 저장할 수도 있습니다. 각 경우에 사용할 도구가 서로 다르며 Azure IoT 다룹니다.
Content: >-
  <p>현재 인사이트나 장기적인 추세를 찾고 있든&rsquo;, 정보의 가치는 비즈니스에 유용할 뿐입니다. 일부 정보는 즉시 조치를 취해야 하지만 시간이 지남에 따라 추세에 대한 장기적이고 큰 그림 분석을 위해 저장할 수도 있습니다. 각 경우에 사용할 도구가 서로 다르며 Azure IoT 다룹니다.</p>


  <h2>근 실시간 데이터 분석</h2>


  <p><strong>Azure Stream Analytics</strong> 는 다양한 원본에서 데이터를 수집하는 종량제 서비스입니다. IoT Hub의 실시간 데이터 외에도 Azure Blob Storage 기록 데이터를 가져와서 Event Hub 데이터를 다른 원본과 결합하여 상관 관계를 강조 표시하거나 비교 분석을 실행할 수도 있습니다.</p>


  <p>Azure Portal을 사용하여 Azure Stream Analytics 작업을 시작하고, 적절한 데이터 집합으로 전달하고, 특정 데이터, 패턴 또는 관계를 찾는 방법에 대한 지침을 제공할 수 있습니다.</p>


  <p>Stream Analytics가 작업을 완료하면 결과를 Blob Storage, SQL Server, Data Lake 또는 Cosmos DB와 같은 서비스 제공 데이터베이스로 보낼 수 있습니다. 추가 분석 및 시각화를 위해 HD Insights 또는 Power BI 데이터를 보낼 수도 있습니다.</p>


  <p>이름에서 설명한 대로<strong> Azure 시계열 Insights</strong> 본질적으로 시간순 또는 순차적인 모든 데이터를 저장, 인덱싱, 쿼리 및 시각화하도록 설계되었습니다. 또한 테라바이트 단위의 데이터 또는 수십억 개의 이벤트를 처리하든 대규모로 처리할 수 있습니다.</p>


  <p>시계열 Insights 가장 일반적인 애플리케이션은 다음과 같습니다.</p>


  <ul>
      <li>근본 원인 분석 수행</li>
      <li>시계열 데이터를 분석하거나 시각화하는 사용자 지정 앱 빌드</li>
      <li>비즈니스와 다른 위치의 데이터를 공유하면 협업을 향상할 수 있습니다.</li>
  </ul>


  <p>큰 데이터 집합을 처리하는 경우&rsquo; <strong>Apache Spark</strong> 가 원하는 도구일 수 있습니다. 병렬 처리를 사용하여 장기 분석 작업에 이상적인 솔루션입니다. 분석 효율성을 높이기 위해 데이터를 처리하기 전에 더 작은 청크로 분할하므로 몇 초밖에 걸리지 않지만 대기 시간 문제가 발생할 수 있습니다.</p>


  <h2>기록 데이터 분석</h2>


  <p>장기적인 트렌드를 찾는 것은 차 잎을 읽는 것과 비슷할 수 있습니다. 데이터 과학 및 고급 분석을 위한 엔드 투 엔드 솔루션인 <strong>Azure Machine Learning(AML</strong>)를 사용하는 것이 좋습니다. 기존 데이터 세트를 사용하여 향후 결과 및 추세를 예측할 수 있습니다. 시간이 지남에 따라 Azure Machine Learning 초점 영역에 대한 이해를 개발하여 보다 효과적인 실험을 개발하고 더 나은 결과를 얻을 수 있는 토대를 마련할 것입니다.</p>


  <p>또한 AML 컴퓨터 비전, 재무 및 수요 예측 및 텍스트 분석을 비롯한 특정 영역에서 기계 학습 모델의 개발을 가속화하는 데 도움이 되는 Python 코드의 특수 라이브러리를 제공합니다.</p>


  <p>빅 데이터 분석을 위한 원래 오픈 소스 솔루션인 <strong>Azure HD Insight</strong> 는 Hadoop을 기반으로 하는 완전 관리형 서비스입니다. HD Insight는 여러 오픈 소스 프레임워크를 지원하므로 유연하고 빠르고 비용 효율적인 솔루션입니다. 또한 HD Insight용 Kafka를 지원하기 때문에 대량의 데이터를 처리하도록 확장할 수 있는 관리형 비용 효율적인 스트리밍 분석 솔루션을 만들 수 있습니다.</p>


  <p>HD Insights 주요 이점은 다음과 같습니다.</p>


  <ul>
      <li>Azure Log Analytics와 통합하면 클러스터의 성능을 모니터링하기 위한 단일 포털이 제공됩니다.</li>
      <li>다양한 개발자 환경과의 호환성을 통해 선택한 도구를 사용할 수 있습니다.</li>
      <li>기록, 실시간, 구조화, 구조화되지 않은 데이터 및 빅 데이터를 비롯한 다양한 데이터 집합을 분석하는 데 탁월합니다.</li>
  </ul>


  <p>데이터 분석을 통한 작업 추진 외에도 IoT Hub의 특정 이벤트를 기반으로 작업을 트리거하는 서버리스 컴퓨팅 모델을 만들 수도 있습니다. <strong> </strong>이전 블로그 게시물에서는 <a href="https://azure.microsoft.com/en-us/blog/getting-started-with-iot-what-do-you-do-with-all-that-data/">Event Grid를 사용하여 작업을 트리거하는 방법을</a> 설명했습니다. Azure Functions를 사용하여 새 파일 업로드와 같은 이벤트에 대한 응답으로 코드 조각을 실행할 수도 있습니다.</p>


  <p>Azure Functions는 전체 앱 및 지원 인프라를 작성하는 번거로움에서 벗어날 수 있습니다. 대신, 현재 문제에 초점을 맞춘 짧은 코드 조각(선택한 언어 사용)을 작성하기만 하면 됩니다. 이 간소화된 접근 방식을 통해 Functions는 주문 처리, 파일 유지 관리 또는 정기적으로 작동해야 하는 대부분의 기타 작업에 적합합니다.</p>


  <p>실시간 또는 기록 데이터를 다시 처리할&#39;있거나 함수를 자동화해야 하든 Azure IoT 요구 사항을 충족하는 도구가 있습니다. IoT 작업에 대해 자세히 알아보고 첫 번째 배포를 시작하는 것이 얼마나 쉬운지 알아보려면 <a href="https://content.microsoft.com/iot/developerguide"><strong>IoT 개발자 가이드를 다운로드</strong></a>하세요.</p>
