### YamlMime:Yaml
ms.openlocfilehash: f87ecc5cdf215e0516bf48a77f9cb9aeb4089297
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139911259"
Slug: glimpse-application-insights
Title: 애플리케이션 Insights 원격 분석 살펴보기
Summary: 애플리케이션 Insights 사랑하는 사람들이 있고, Glimpse을 사랑하는 사람들이 있으며, 이러한 훌륭한 도구에 대해 들어본 적이 없는 사람들이 있습니다. 잠시 시간을 내어 자세히 알아보세요.
Content: >-
  <p>애플리케이션 Insights 사랑하는 사람들이 있고, Glimpse을 사랑하는 사람들이 있으며, 이러한 훌륭한 도구에 대해 들어본 적이 없는&rsquo; 사람들이 있습니다.</p>


  <p>개발 중에 웹앱을 프로파일링하고 디버깅하는 데 유용한 반면, Application Insights 라이브 프로덕션에서 문제를 진단하고 성능을 모니터링하는 도구입니다. 둘 다 필요하기 때문에 이러한 제품을 통합하기로 결정했습니다.</p>


  <h1>Application Insights란?</h1>


  <p><a href="https://www.visualstudio.com/features/application-insights-vs">애플리케이션 Insights</a> 성능, 가용성 및 사용을 위해 프로덕션 환경에서 웹 애플리케이션을 모니터링합니다. 사용자가 앱에서 수행하는 작업을 이해하고, 실패한 요청 및 예외를 진단하고, 브라우저, 웹 서버 또는 백 엔드 서비스에서 성능 문제를 찾는 데 도움이 됩니다.</p>


  <p><img alt="appinsights" border="0" height="123" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/ede00e7f-3376-46d9-b9a1-a93641780a4b.png" style="border-left-width: 0px; border-right-width: 0px; background-image: none; border-bottom-width: 0px; float: none; padding-top: 0px; padding-left: 0px; margin: 0px auto; display: block; padding-right: 0px; border-top-width: 0px" title="appinsights" width="610"></p>


  <h1>엿보기란?</h1>


  <p>웹용 진단 플랫폼을 엿볼 수 있습니다. 웹앱을 디버깅하는 동안 Glimpse은 웹 요청이 발생하는 대로 검사하여 디버깅 시간을 줄이고 모든 개발자가 웹 애플리케이션을 개선할 수 있는 인사이트와 도구를 제공합니다.</p>


  <p><img alt="glimpse2" border="0" height="189" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/622c0212-d91c-4b28-bcc6-1551f1d47992.png" style="border-left-width: 0px; border-right-width: 0px; background-image: none; border-bottom-width: 0px; float: none; padding-top: 0px; padding-left: 0px; margin: 0px auto; display: block; padding-right: 0px; border-top-width: 0px" title="glimpse2" width="610"></p>


  <h1>통합은 무엇을 제공하나요?</h1>


  <p>애플리케이션 Insights 요청에 대한 클라이언트 및 서버 쪽 원격 분석과 비즈니스 메트릭뿐만 아니라 종속성에 대한 아웃바운드 호출을 자동으로 수집합니다. 이제 애플리케이션 Insights 새 범주인 엿보기 타임라인 탭을 통해 엿보기에서 수집한 다른 데이터와 함께 이러한 항목에 액세스할 수 있습니다. 오늘 엿볼 아웃바운드 HTTP 호출에 대 한 정보를 제공 하지 않습니다 하지만 애플리케이션 Insights, 당신은 그들을 볼 수 있습니다.</p>


  <p><img alt="glimpse-trace" border="0" height="183" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/ba1a2ed5-bcbd-402c-a7d8-7b54579cf54d.png" style="border-left-width: 0px; border-right-width: 0px; background-image: none; border-bottom-width: 0px; float: none; padding-top: 0px; padding-left: 0px; margin: 0px auto; display: block; padding-right: 0px; border-top-width: 0px" title="엿보기 추적" width="610"></p>


  <p>애플리케이션 Insights 로그 추적 및 예외 보고서도 수집합니다. 추적 엿보기 탭에 표시됩니다.</p>


  <p><img alt="glimpse-trace2" border="0" height="121" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/49818b42-17f6-41fd-8f56-854a9da55bac.png" style="border-left-width: 0px; border-right-width: 0px; background-image: none; border-bottom-width: 0px; float: none; padding-top: 0px; padding-left: 0px; margin: 0px auto; display: block; padding-right: 0px; border-top-width: 0px" title="glimpse-trace2" width="610"></p>


  <p>새 애플리케이션 Insights 탭에는 애플리케이션이 프로덕션 환경에 배포된 후 수집할 클라이언트 및 서버의 모든 애플리케이션 Insights 원격 분석이 표시됩니다.</p>


  <p><img alt="glimpse-ai" border="0" height="183" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/9dd6f747-f600-4334-9d55-edc754d463d1.png" style="border-left-width: 0px; border-right-width: 0px; background-image: none; border-bottom-width: 0px; float: none; padding-top: 0px; padding-left: 0px; margin: 0px auto; display: block; padding-right: 0px; border-top-width: 0px" title="glimpse-ai" width="610"></p>


  <h1>개발 주기</h1>


  <p>이 도구 조합을 사용하면 Glimpse 및 Visual Studio Diagnostics Hub를 사용하여 각 웹 요청에 대한 응답을 추적할 수 있습니다. 이러한 도구를 사용하면 요청 매개 변수, 세션 상태, SQL 쿼리 및 구성 설정에 즉시 액세스할 수 있습니다. 이렇게 하면 개발 프로세스가 간소화되고 디버깅이 신속하게 수행됩니다.</p>


  <p><img alt="developmentcycle2" border="0" height="230" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/809f6161-5a13-4e64-995b-390aed0ee597.png" style="border-left-width: 0px; border-right-width: 0px; background-image: none; border-bottom-width: 0px; float: none; padding-top: 0px; padding-left: 0px; margin: 0px auto; display: block; padding-right: 0px; border-top-width: 0px" title="개발 주기2" width="303"></p>


  <p>앱이 프로덕션 환경에서 라이브로 실행되는 경우 진단 프로세스는 다릅니다. 모든 요청이 발생하는 것을 엿볼 때 보는 대신, 예를 들어 응답 시간이 부하에 따라 어떻게 달라지는지, 그리고 종속성 &ndash; REST 서비스, 데이터베이스 등에서 발생하는 변동량에 대한 통계를 수집하려고 합니다. 실패한 요청&rsquo;이 있는 경우 영향을 받는 사용자 수를 평가한 다음&rsquo; 일부 오류를 선택하여 추적을 자세히 검사하려고 합니다. 애플리케이션 Insights 장점이 있습니다.</p>


  <p>대부분의 경우 애플리케이션 Insights 사용하도록 설정하는 것만으로도 라이브 앱에 필요한 모든 진단 및 사용 정보를 제공할 수 있습니다. 그러나 원격 분석을 사용자 지정하여 사용량 및 성능에 대한 자세한 피드백을 얻을 수도 있습니다. Glimpse 및 Application Insights 통합하면 프로덕션 환경에서 애플리케이션 Insights 가져오는 원격 분석을 미세 조정할 수 있습니다.</p>


  <p>애플리케이션 Insights 탭을 보면 애플리케이션을 탐색할 때 특정 페이지에 대해 수집되는 데이터를 정확히 확인할 수 있습니다. 개발 중에 이 작업을 수행하면 의도한 방식으로 원격 분석 컬렉션을 구현했는지 확인할 수 있습니다. 체크 아웃 가격 또는 큐 길이를 올바르게 보냈습니까? 성공적인 트랜잭션이 비즈니스 원격 분석 이벤트로 보고되었나요? 애플리케이션을 릴리스한 후 이 원격 분석은 비즈니스 및 진단 인사이트의 원본이 됩니다.</p>


  <p>이 통합은 개발에서 수집된 데이터에서 프로덕션 환경에서 수집된 데이터로 전환하는 데 도움이 되지만, 더 가치 있게 통합을 개선할 계획입니다. 다음 버전의 Glimpse 및 Application Insights NuGet 사용하여 애플리케이션의 새 버전을 개발할 때 이전 버전의 애플리케이션의 프로덕션 데이터를 Glimpse UI에 표시할 계획입니다.</p>


  <h1>지금 평가판 사용</h1>


  <p>이 통합이 작동하는 것을 확인하고 NuGet 패키지 중 하나를 설치하여 사용자 고유의 애플리케이션에서 사용해 보세요. 현재 두 개의 NuGet 패키지를 사용할 수 있습니다.</p>


  <p><a href="https://www.nuget.org/packages/Glimpse.ApplicationInsights.Web/1.0.0">엿보기 애플리케이션 Insights 웹 패키지를</a> 설치하면 애플리케이션에 대한 애플리케이션 Insights 켜지고 기본 Glimpse 패키지 집합이 활성화됩니다. 이 패키지에는 웹 애플리케이션에 필요한 다른 패키지에 대한 종속성이 포함되어 있어 모두를 위한 간단한 솔루션이 됩니다. Application Insights 온보딩하지 않은 경우 이 패키지를 사용해야 합니다. 엿보기 애플리케이션 Insights 웹은 추가 작업 없이 .NET 웹 애플리케이션을 지원합니다.</p>


  <p><img alt="package_glimpse" border="0" height="125" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/a54c5696-0b7c-466f-acd7-65826c1236b2.png" style="border-left-width: 0px; border-right-width: 0px; background-image: none; border-bottom-width: 0px; float: none; padding-top: 0px; padding-left: 0px; margin: 0px auto; display: block; padding-right: 0px; border-top-width: 0px" title="package_glimpse" width="610"></p>


  <p><strong>참고:</strong> Application Insights 및 Glimpse를 이미 온보딩한 경우 <a href="https://www.nuget.org/packages/Glimpse.ApplicationInsights/1.0.0">애플리케이션 Insights NuGet 패키지를</a> 사용하는 것이 좋습니다. 추가 기능을 원하는 경우 ADO.NET, ASP.NET 및 EnityFramework 또는 기타 확장을 수동으로 설치할 수 있습니다.</p>


  <h1>특별 감사</h1>


  <p>엿보기 및 애플리케이션 Insights 통합은 여러 기여자를 통해 가능한 오픈 소스 프로젝트입니다. 기예르모 제페 <a href="https://github.com/avanderhoorn"></a> 다, <a href="https://github.com/JoseCarlosMM">호세 카를로스 멘데즈</a>, 알레한드로 다미안, 카를로스 파즈, 호르헤 로드리게스, 프란시스코 브라보, <a href="https://github.com/SusanaL">클라우디아 수사나 로페즈</a>, 카를로 로렌자나, 세르게이 <a href="https://github.com/SergeyKanzhelev">칸젤 Insights레프</a>의 도움을 받아 <a href="https://github.com/oscargarciacolon">오스카 가르시아 콜론</a>(MVP)의 ALM Latam OOS 팀 리더에게 특별한 감사를 전하고 <a href="https://github.com/nikmd23">싶습니다.</a> 함께, 세 개의 서로 다른 팀은 우리 모두가 당신이 즐길 희망 통합을 만들 수 있었다.</p>


  <h1>알려주세요.&hellip;</h1>


  <p>엿보기 및 애플리케이션 Insights 통합은 진행 중인 작업입니다. 문제 또는 기능 요청은 <a href="https://github.com/glimpse/glimpse.applicationInsights/issues">리포지토리</a>를 방문하세요.</p>


  <p>애플리케이션 Insights 팀은 개발자에게 양질의 도구를 제공하기 위해 최선을 다하고 있습니다. 피드백 또는 새로운 기능 권장 사항에 감사드립니다.</p>
