### YamlMime:Yaml
ms.openlocfilehash: 46b9383f34e5aeda00999afce52191987c9aeca7
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139901217"
Slug: guidance-for-enterprises-looking-to-take-their-application-portfolio-to-the-cloud
Title: 애플리케이션 포트폴리오를 클라우드로 활용하려는 기업을 위한 지침
Summary: '애플리케이션 카탈로그를 사용하여 엔터프라이즈 환경을 클라우드로 이동하는 것이 무엇을 의미하는지에 대한 광범위한 연구를 수행했습니다. 최근에 출판된 전자책에서 자세히 알아보세요. '
Content: >-
  <p>전체 포트폴리오의 모든 비즈니스 도메인 및 애플리케이션에서 효율성과 혁신을 모두 달성할 수 있다면 어떨까요? 클라우드와 모든 리소스 및 기능을 활용하여 전체를 얻을 &ldquo;수 있다면 그 부분&rdquo; 효과의 합보다 더 클 수 있을까요? 좋은 로드맵과 길을 선도하는 입증 된 전략으로, 당신은 할 수 있습니다. 애플리케이션 카탈로그를 사용하여 엔터프라이즈 환경을 클라우드로 이동하는 것이 무엇을 의미하는지에 대한 광범위한 연구를 수행했습니다. Barry Briggs와 본인의 최근 출판된 전자책 &ldquo;Enterprise 클라우드 전략&rdquo;에서 Microsoft는 고객의 경험뿐만 아니라 Microsoft&rsquo;의 경험에서 예제와 학습 경험을 제공합니다.</p>


  <p><a href="https://info.microsoft.com/enterprise-cloud-strategy-ebook.html?wt.mc_id=WW_CE_IAAS_OO_BLOG_NONE">고유한 로드맵을 빌드하는 데 도움이 되는 전략을 제공하는 eBook을 읽어보세요.</a></p>


  <p><img alt="Enterprise Cloud Strategy" border="0" height="360" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/91e9bef9-1c31-4939-aa6b-e5f6647f69a8.jpg" style="border-top: 0px; border-right: 0px; background-image: none; border-bottom: 0px; padding-top: 0px; padding-left: 0px; border-left: 0px; display: inline; padding-right: 0px" title="Enterprise 클라우드 전략" width="295"></p>


  <p>다양한 마이그레이션 방법을 강조하고 이러한 이점과 복잡성을 자세히 설명합니다.</p>


  <ul>
   <li><strong>다시 호스트합니다.</strong> 온-프레미스 데이터 센터에서 호스트 또는 클라우드로 VM 또는 운영 환경을 이동합니다. 이 모델을 공동 위치라고도 합니다.</li>
   <li><strong>다시 플랫폼화합니다.</strong> 레거시 환경은 비용 또는 운영 요구 사항에 따라 지속 불가능해집니다. 솔루션은 &ldquo;코드를 변경하지 않고 애플리케이션을 유지하고 래핑&rdquo; 하여 작업의 무결성과 보안을 손상시킬 수 있습니다.</li>
   <li><strong>사용 중지 및 다시 작성(또는 다시 구상).</strong> 이전 환경에서 충족할 수 없는 충분한 새 요구 사항이 있는 경우 진행하는 가장 좋은 방법은 더 적합한 최신 환경에서 애플리케이션을 다시 작성하는 것입니다. 애플리케이션 포트폴리오를 검사하고 유사한 기능을 가진 여러 애플리케이션을 통합할 때 종종 발생합니다.</li>
   <li><strong>버스트 아웃.</strong> 클라우드 환경에서 제공되는 모든 새로운 컴퓨팅, 데이터 및 서비스 모델이 각각 IT 환경에서 이전에는 액세스할 수 없었던 기능과 용량을 제공하면서 많은 애플리케이션이 클라우드로 급증하고 있습니다. 이러한 애플리케이션은 혁신적인 유형의 분석, 보고, 고성능 컴퓨팅, 시각화 등을 수행하고 있습니다. 자주 사용되는(&ldquo;핫&rdquo;) 데이터를 로컬로 유지하면서 자주 액세스하지 않는(&ldquo;콜드&rdquo;) 데이터를 훨씬 저렴한 클라우드 스토리지로 유지하는 것은 또 다른 일반적인 패턴입니다.</li>
   <li><strong>확장.</strong> 이제 기업은 이전 애플리케이션을 확장하는 방법과 이전에 컴퓨터 화면으로 제한되었던 것과 동일한 기능을 사용하여 모바일 디바이스 및 웹 프런트 엔드에 제공하는 기능을 추가하는 방법을 모색하고 있습니다. 예를 들어 검색 또는 비디오 서비스를 사용하여 애플리케이션을 개선하기 위해 움직이고 있습니다.</li>
   <li><strong>클라우드 네이티브 애플리케이션.</strong> 회사에서 클라우드 조사를 시작하면 빅 데이터와 같은 새로운 형태의 애플리케이션, 새로운 유형의 분석, 기계 학습과 같은 완전히 새로운 기능 및 클라우드에 고유하게 적합한 IoT(사물 인터넷)용 애플리케이션이 있다는 사실을 자주 알게 됩니다.</li>
  </ul>


  <p>예를 들어 권장되는 클라우드 마이그레이션 계획은 정적 계획 문서보다 더 많은 프로세스이며, 각 마이그레이션의 세부 사항은 일반적으로 다음 패턴을 따릅니다.</p>


  <ol>
   <li><strong>분석.</strong> 현재 상태를 원하는 상태로 매핑하는 프로세스입니다. 이 프로세스는 현재 가지고 있는 작업과 해당 워크로드를 클라우드로 마이그레이션하는 데 걸리는 작업 간의 차이를 식별하는 데 도움이 됩니다. 이러한 간격에는 워크로드 아키텍처가 변경되거나 프로그램을 완전히 다시 작성해야 할 수 있습니다.</li>
   <li><strong>애플리케이션 마이그레이션.</strong> 특정 워크로드를 클라우드로 이동해야 한다고 판단할 때 가장 좋은 방법은 최소한의 데이터로 워크로드 버전을 만들어 애플리케이션이 클라우드에서 작동하도록 하거나 새 버전의 애플리케이션을 빌드하는 것입니다. 애플리케이션이 이미 VM에서 실행 중인 경우 추가 변경 없이 VM을 클라우드로 마이그레이션하기만 하면 됩니다. 일반적으로 대부분의 온-프레미스 애플리케이션은 최소한의 변경이나 변경 없이 Microsoft Azure 실행할 수 있지만, 이는 애플리케이션이 성능, 확장성 및 보안에 최적화된다는 것을 의미하지는 않습니다. 최신 서비스 지향 원칙을 사용하여 어느 정도 애플리케이션을 다시 디자인하고 다시 빌드해야 할 수도 있습니다.</li>
   <li><strong>데이터 마이그레이션.</strong> 이는 데이터 구조를 클라우드의 관계형(Azure SQL Database, SQL Server) 또는 비관계형(Blob, 테이블, 큐, Azure DocumentDB 등) 위치로 그대로 이동할 수 있다는 측면에서 애플리케이션 마이그레이션과 다소 유사합니다. 이러한 종류의 마이그레이션은 매우 쉽고 SQL Server Azure 마이그레이션 마법사와 같은 마법사의 도움을 받아 수행할 수 있습니다. 그러나 성능, 확장성, 복원력 및 보안 향상을 위해 데이터 모델을 새로운 Azure SQL Database 다시 빌드하는 것이 좋습니다. 온-프레미스와 SQL Database 간 또는 서로 다른 SQL Database 서버 간에 데이터를 동기화해야 하는 경우 SQL 데이터 동기화 서비스를 설정하고 구성합니다. 또한 사용자 오류 또는 자연 재해가 발생할 경우 데이터 복구 계획을 설정하고 구성하는 것이 가장 좋습니다.</li>
   <li><strong>최적화 및 테스트.</strong> 응용 프로그램 및 데이터를 Azure로 마이그레이션한 후 기능 및 성능 테스트를 수행합니다. 이 단계에서는 클라우드에서 응용 프로그램을 테스트하여 예상한 대로 작동하는지 확인합니다. 그런 다음, 온-프레미스와 Azure 간의 성능 결과를 비교합니다. 그런 다음 클라우드 응용 프로그램의 기능, 성능 또는 확장성 문제를 해결합니다.</li>
   <li><strong>작업 및 관리.</strong> 테스트 및 최적화 단계가 끝나면 Azure Application Insights 사용하여 애플리케이션 모니터링 및 추적을 설정하고 구현하여 애플리케이션에서 원격 분석을 수집하고 분석할 수 있습니다. 이 데이터를 사용하여 디버깅 및 문제 해결, 성능 측정, 리소스 사용량 모니터링, 트래픽 분석 및 용량 계획 및 감사를 수행할 수 있습니다.</li>
  </ol>


  <p>에두아르도 카스너와 배리 브릭스에 의해 Enterprise 클라우드 전략&rdquo;에서 &ldquo;적응. Kassner는 Microsoft의 Worldwide Enterprise 및 파트너 그룹의 클라우드 솔루션 아키텍처 디렉터입니다. Briggs는 소프트웨어 및 엔터프라이즈 컴퓨팅 분야에서 오랜 역사를 가진 독립 컨설턴트입니다.</p>


  <p><a href="https://info.microsoft.com/enterprise-cloud-strategy-ebook.html?wt.mc_id=WW_CE_IAAS_OO_BLOG_NONE">지금 전자책을 다운로드하세요.</a></p>
