### YamlMime:Yaml
ms.openlocfilehash: dbb89b29bb23c4e981c847062be8e449456dab63
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139905936"
Slug: harness-the-power-of-data-and-ai-in-your-applications-with-azure
Title: Azure를 사용하여 애플리케이션에서 데이터 및 AI의 기능 활용
Summary: 개발자에 대한 우리의 약속은 Azure를 데이터와 AI의 기능을 활용하는 지능형 애플리케이션을 개발하기 위한 최고의 클라우드로 만드는 것입니다. Microsoft Build에서는 개발자가 Azure 데이터 및 AI 서비스를 시작할 수 있도록 쉽고 비용 효율적인 몇 가지 흥미로운 새로운 기능과 제안을 발표합니다.
Content: >-
  <p>지난 1년&rsquo; 동안 이러한 전례 없는 시기를 탐색하는 기업은 새로운 수준의 민첩성이 필요하다는 것이 분명해졌습니다. 이 민첩성의 핵심은 한때 상상할 수 없는 것으로 여겨졌던 소프트웨어 개발 우수성의 수준을 달성하는 것입니다. 모든 개발자에게 무한한 규모, 선택 및 가능성을 부여하는 데 있어 Microsoft Azure 뒤로 물러났습니다.</p>


  <p>개발자에 대한 우리의 약속은 Azure를 데이터와 AI의 기능을 활용하는 지능형 애플리케이션을 개발하는 데 가장 적합한 클라우드&nbsp;로 만드는 것입니다. Microsoft Build에서는 개발자가 Azure 데이터 및 AI 서비스를 시작할 수 있도록 쉽고 비용 효율적인 몇 가지 흥미로운 새로운 기능과 제안을 발표합니다.</p>


  <h2>Azure 데이터베이스 서비스로 혁신</h2>


  <p>개발자가 Azures&rsquo; 데이터베이스 서비스를 사용하여 혁신할 수 있는 몇 가지 새로운 기능을 발표합니다. <a href="https://aka.ms/sql-ledger-blog" target="_blank">&rsquo;Azure SQL Database 원장 기능은</a> 미리 보기에서 중요한 레코드에 대한 암호화 확인을 제공합니다. 영국 석유와 같은 고객은 이미 이 흥미로운 기능을 활용하고 있습니다. <a href="https://azure.microsoft.com/en-us/services/synapse-analytics/" target="_blank">Microsoft Dataverse용 Azure Synapse Link는 Microsoft</a> Dynamics 365 및 Microsoft Power Platform 애플리케이션에서 즉각적인 인사이트를 제공하는 반면, <a href="https://aka.ms/2021BuildPowerBI" target="_blank">Microsoft Power BI 스트리밍 데이터 흐름</a>은 신호에서 인사이트로의 병목 현상을 제거&nbsp;합니다. 개발자가 다음을 포함하여 모든 규모의 고성능 애플리케이션을 빌드하고 현대화하는 데 도움이 되는 Azure Cosmos DB에 대한 몇 가지 업데이트도 있습니다.</p>


  <ul>
      <li>이제 <a href="https://aka.ms/cosmos-devblog-build-1" target="_blank">Azure Cosmos DB 서버리스</a>&nbsp;를 모든 API에 일반 공급합니다. 서버리스 요금은 소비되는 리소스에만 적용되므로 트래픽 패턴이 뾰족한 애플리케이션에 적합한 배포 옵션입니다. Albertsons 및 Swiss Re와 같은 고객은 현재 이 기능을 활용하고 있습니다.</li>
      <li><a href="https://aka.ms/cosmos-devblog-build-2" target="_blank">Azure Cosmos DB 통합 캐시</a>&nbsp;는 현재 미리 보기로 제공됩니다. 통합 캐시는 비용을 최적화하고 읽기가 많은 워크로드의 성능을 각각 최대 96%와 300% 향상시킵니다. ASOS와 같은 고객은 이미 이 흥미로운 기능을 활용하고 있습니다.</li>
      <li><a href="https://aka.ms/cosmos-devblog-build-2" target="_blank">Azure Cosmos DBis</a>&nbsp;에 대한 Always Encrypted가 미리 보기로 제공됩니다. Always Encrypted를 사용하면 개발자가 데이터베이스에 저장되기 전에 클라이언트 애플리케이션 내에서 중요한 데이터를 암호화할 수 있습니다.</li>
      <li><a href="https://aka.ms/cosmos-devblog-build-2" target="_blank">이제 Azure Cosmos DB RBAC(역할 기반 액세스 제어</a>)&nbsp;를 일반적으로 사용할 수 있습니다. RBAC를 사용하면 관리자가 특정 규칙을 사용하여 역할을 정의하고 azure AD(Azure Active Directory) 프로필에 역할을 적용하여 액세스 수준을 결정할 수 있습니다.</li>
  </ul>


  <p>Azure Cosmos DB는 가장 까다로운 중요 업무용 애플리케이션에&rsquo; 전력을 공급하기 위한 이동 데이터베이스가 되었습니다. 예를 들어 월마트는 연말연시에 전자 상거래 플랫폼을 준비하면서 Azure Cosmos DB로 전환하여 페타바이트 규모로 10밀리초 미만의 고가용성 대기 시간을 제공하고 수십억 개의 일일 요청을 처리할 수 있었습니다.&nbsp;&nbsp;</p>


  <p>또한&rsquo; Azure Cosmos DB, Azure Database for PostgreSQL 및 Azure Database for MySQL에 대한 추가 저가 및 무료 옵션을 발표했습니다. 현재 일반 공급<a href="https://aka.ms/cosmos-devblog-build-1" target="_blank">되는 Azure Cosmos DB&rsquo; 확장 무료 계층</a>은 개발자에게 1,000RU/프로&nbsp;비전 처리량 및 25GB의 무료 스토리지로 혁신할 수 있는 유연성을 제공합니다. <a href="https://aka.ms/cosmos-devblog-build-1" target="_blank">Azure Cosmos DB&rsquo;</a> 무료 Linux 에뮬레이터를 미리 보기에서 Linux 개발자는 Linux 및 macOS 머신에서 로컬로 Azure Cosmos DB에서 빌드, 테스트 및 학습할 수 있습니다. 6월에 제공되는 <a href="https://aka.ms/postgresqlbuild21" target="_blank">Azure Database for PostgreSQL</a> 및 <a href="https://aka.ms/SunilBuild2021MySQL" target="_blank">Azure Database for MySQL</a> 유연한 서버에 대한 12개월 무료 제품은 개발자에게 Azure 체험 계정으로 처음 12개월 동안 한 달에 최대 750시간을 무료로 제공합니다. 또한 Azure Database for PostgreSQL - 하이퍼스케일(Citus) <a href="https://docs.microsoft.com/en-us/azure/postgresql/concepts-hyperscale-tiers" target="_blank">기본 계층</a>은 미리 보기에서 단일 노드에서 하이퍼스케일(Citus)을 시작하는 비용 효율적인 옵션을 제공하며, 작업자 노드를 더 쉽게 추가하여 사실상 무한한 규모를 달성할 수 있도록 합니다.</p>


  <h2>Azure AI를 사용하여 지능형 애플리케이션 빌드</h2>


  <p>Azures&rsquo; AI 서비스는 모든 기술 수준의 개발자가 선택한 도구와 언어를 사용하여 지능형 애플리케이션을 빌드할 수 있도록 지속적으로 지원합니다. 기계 학습 환경이 없는 개발자는 간단한 API 호출을 통해 고품질 비전, 음성, 언어 및 의사 결정 AI 모델에 액세스할 수 있습니다. 자체 기계 학습 모델을 빌드하는 개발자는 Jupyter Notebook, Visual Studio&nbsp; Code 및 PyTorch 및 TensorFlow와 같은 오픈 소스 프레임워크와 같은 도구를 사용할 수 있습니다.</p>


  <p>개발자가 AI 솔루션을 더 빠르게 빌드할 수 있도록 <a href="https://aka.ms/AppliedAITC" target="_blank">Azure Applied AI Services</a>라는 추가 서비스 범주를 발표합니다. 이러한 서비스는 <a href="https://azure.microsoft.com/en-us/services/cognitive-services/" target="_blank">Azure Cognitive Services</a> 를 작업별 AI 및 비즈니스 논리와 결합하므로 개발자는 문서 처리, 고객 서비스 및 콘텐츠에서 인사이트 추출과 같은 일반적인 시나리오에 대한 AI 솔루션 빌드를 가속화할 수 있습니다. 적용된 AI 서비스에는 <strong>Azure Bot Services, Azure Cognitive Search, Azure Form Recognizer, Azure Metrics Advisor 및 Azure 몰입형 리더</strong> 포함되며, 많은 개발자가 이미 알고 있습니다. 오늘부터 <a href="https://azure.microsoft.com/en-us/services/bot-service/" target="_blank">Azure Bot Services</a>를 사용하면 통합 개발 환경을 통해 텍스트, 음성 또는 전화 통신 기반 봇을 더 쉽게 빌드, 테스트 및 게시할 수 있습니다.&nbsp; 이제 일반 공급되는 <a href="https://azure.microsoft.com/en-us/services/metrics-advisor/" target="_blank">Azure Metrics Advisor</a>는 가동 중지 시간을 최소화하기 위해 문제를 자동으로 검색하고 진단합니다. <a href="https://aka.ms/AppliedAISamsung" target="_blank">삼성은 Azure Metrics Advisor를 사용하여</a> SmartTV 서비스를 개선합니다. 현재 미리 보기 상태인 <a href="https://azure.microsoft.com/en-us/products/video-analyzer" target="_blank">Azure Video Analyzer</a>는 개발자가 AI 기반 비디오 분석 솔루션을 신속하게 빌드할 수 있도록 Live Video Analytics 및 Video Indexer를 함께 제공합니다. Dow는 작업 공간 안전을 개선하기 위해 <a href="https://aka.ms/AppliedAIDow" target="_blank">Azure Video Analyzer를 사용</a>하며 루프<a href="https://aka.ms/AppliedAILufthansa" target="_blank">트한자는 이를 사용하여 운영 효율성을 개선하고</a> 항공기 소요를 더 안전하게 처리합니다.</p>


  <p>개발자는 Azure Machine Learning 자체 사용자 지정 모델을 가져와 적용된 AI 서비스를 확장할 수 있습니다. <a href="https://aka.ms/AzureMLbuild2021" target="_blank">Azure Machine Learning 관리형 엔드포인트</a>를 사용하면 개발자가 모델을 애플리케이션에 제공하는 데 사용되는 인프라 만들기 및 관리를 자동화할 수 있습니다. 기계 학습에 PyTorch를 사용하는 개발자의 경우 이제 <a href="https://aka.ms/PyTorchEnterpriseHeroBlog" target="_blank">PyTorch Enterprise</a> 사용하여 우선 순위가 지정된 요청 및 실습 지원과 같은 이점을 통해 보다 안정적인 프로덕션 환경을 제공할 수 있습니다.</p>


  <p>낮은 코드 환경에서 빌드를 선호하는 개발자를 위해 Microsoft Power Apps 계속 제공합니다. 이제 모든 개발자는 <a href="https://aka.ms/2021BuildPowerApps" target="_blank">AI 기반 앱 개발 방법을</a> 사용하여 자연어를 코드 및 프로그램으로 전환할 수 있습니다. 이 환경은 세계에서 가장 큰 자연어 모델 중 하나인 OpenAI GPT-3 모델을 통해 제공됩니다. Power Apps 이 추가 기능은 Azure Machine Learning&rsquo; 관리형 엔드포인트에서 가능합니다.</p>


  <h2>오늘 시작</h2>


  <p>이러한 공지 사항을 종합하면 모든 기술 수준의 개발자가 데이터와 AI의 기능을 활용하는 지능형 애플리케이션을 빌드할 수 <em>있는 클라우드로</em> Azure를 더욱 공지합니다.&nbsp; &nbsp;개발자가 그 어느 때보다 Azure에서 혁신할 수 있도록 더욱 원가적이고 비용 효율적일&#39;있습니다.</p>


  <ul>
      <li>자세한 내용을 보려면 디지털 Microsoft Buildthis&nbsp; 주간에 라이브 또는 주문형으로 다음 세션을 확인하세요.&nbsp; <ul>
          <li><a href="https://mybuild.microsoft.com/sessions/46f12ac0-4d74-4a53-95b1-22e406edd72c" target="_blank">Azure를 사용하여 애플리케이션의 데이터 기능 활용</a>&nbsp;</li>
          <li><a href="https://mybuild.microsoft.com/sessions/2ba55238-d398-46f9-9ff2-eafcd9d69df3" target="_blank">세계적 수준의 AI가 주입된 지능형 애플리케이션 빌드</a>&nbsp;</li>
      </ul>
      </li>
      <li>Azure&#39;관리되는 데이터베이스 및 AI 서비스에 대한 자세한 내용은 다음을 수행합니다. <ul>
          <li><a href="https://azure.microsoft.com/en-us/solutions/databases/" target="_blank">완전 관리형 데이터베이스를 사용하여 애플리케이션 개발 간소화</a></li>
          <li><a href="https://azure.microsoft.com/en-us/overview/ai-platform/" target="_blank">Azure AI를 사용하여 검증되고 안전하며 책임 있는 AI 기능 얻기</a></li>
      </ul>
      </li>
  </ul>


  <p><a href="https://azure.microsoft.com/en-us/free/" target="_blank">오늘 시작하세요</a>. 다음에 빌드하는 내용을 보기 위해 기다릴 수 있습니다&rsquo;.</p>


  <hr>

  <p><em>Azure. 목적에 따라 발명.</em></p>
