### YamlMime:Yaml
ms.openlocfilehash: 3aaa53c2c11f142f810fae206b602b1bcdb4fb17
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139911017"
Slug: hdinsight-tools-for-vscode-supports-azure-environments-worldwide
Title: HDInsight Tools for VSCode는 전 세계 Azure 환경을 지원합니다.
Summary: 전 세계 HDInsight 고객에게 더 나은 서비스를 제공하기 위해 이제 HDInsight 서비스를 호스트하는 모든 Azure 환경에 VSCode용 HDInsight 도구를 연결할 수 있습니다.
Content: >-
  <p align="left">전 세계 HDInsight 고객에게 더 나은 서비스를 제공하기 위해 이제 HDInsight 서비스를 호스트하는 모든 Azure 환경에 VSCode용 HDInsight 도구를 연결할 수 있습니다. 여기에는 특정 규정 준수 및 데이터 주권 요구 사항이 있는 고객이 사용하는 Azure 정부 및 지역 클라우드가 포함됩니다. 개발자는 VSCode 명령 팔레트에서 <b>Azure 환경 설정</b> 명령을 통해 여러 Azure 환경에서 쉽게 전환할 수 있습니다. 이 기능은 Azure 정부 및 지역 환경에 대한 쉬운 데이터 쿼리 또는 작업 제출을 통해 편집기를 사용하려 하지만 어려운 경우를 발견한 Hive 및 Spark 개발자에게 특히 유용합니다. 이 새로운 기능을 통해 HDInsight Tools for VSCode에 빠르고 간단한 액세스를 제공하고 클릭 한 번으로 Azure 환경에 연결하여 고객을 지원합니다.</p>


  <h2><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/66b04a50-7e5d-4955-b31e-17a877ca37f6.png"><img alt="Azure Command" border="0" height="60" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/a4f5855d-b9be-4832-888b-f6a2c1377af4.png" style="border-width: 0px; padding-top: 0px; padding-right: 0px; padding-left: 0px; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="Azure 명령" width="600"></a></h2>


  <h2><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/69cf1678-055b-4fde-ad2e-049e335d843f.png"><img alt="Azure Environment" border="0" height="130" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/8edc054c-e7b4-4a22-9f9d-438d2ba12b5d.png" style="border-width: 0px; padding-top: 0px; padding-right: 0px; padding-left: 0px; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="Azure 환경" width="600"></a></h2>


  <p align="left">이전 통신에서 설명한 대로 VSCode용 HDInsight 도구는 Hive Interactive Query, Hive Batch, PySpark Interactive 및 PySpark Batch를 지원합니다. 경량 플랫폼 간이며 HDInsight의 개발 환경을 크게 향상시킵니다. 최근 공지 사항은 아래 블로그를 참조하세요.</p>


  <ul>
   <li><a href="https://azure.microsoft.com/en-us/blog/run-you-hive-llap-pyspark-job-in-visual-studio-code-vscode/">Visual Studio Code Hive LLAP &amp; Batch 작업 실행</a></li>
   <li><a href="https://azure.microsoft.com/en-us/blog/run-your-pyspark-interactive-query-and-batch-job-in-visual-studio-code/">Visual Studio Code PySpark 대화형 쿼리 및 일괄 처리 작업 실행</a></li>
  </ul>


  <h2>설치 또는 업데이트 방법</h2>


  <p align="left">먼저 Visual Studio Code 설치하고 Mono 4.2.x(Linux 및 Mac용)를 다운로드합니다. 그런 다음 VSCode 확장 리포지토리 또는 VSCode Marketplace로 이동하여 VSCode용 &rdquo;HDInsight 도구를 검색 &ldquo; 하여 최신 <strong>HDInsight 도구를</strong> 가져옵니다.</p>


  <p align="center"><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/afcf4676-91c3-4fe0-a8c5-a6fb0fc3d93e.png"><img alt="a4991f2e-c132-4794-8a4c-08b3cf68b328" border="0" height="300" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/b9c84107-ffd7-44c0-91f5-20a4ebf6b0e2.png" style="border-image: none; display: inline; background-image: none;" title="a4991f2e-c132-4794-8a4c-08b3cf68b328" width="600"></a></p>


  <p align="left">VSCode용 HDInsight 도구에 대한 자세한 내용은 다음 리소스를 사용하세요.</p>


  <ul>
   <li>사용자 설명서: <a href="https://docs.microsoft.com/en-us/azure/hdinsight/hdinsight-for-vscode">VSCode용 HDInsight 도구</a></li>
   <li>사용자 설명서: <a href="https://docs.microsoft.com/en-us/azure/hdinsight/set-up-pyspark-interactive-environment?branch=pr-en-us-26060">PySpark 대화형 환경 설정</a></li>
   <li>데모 비디오: <a href="https://youtu.be/RLjVNP8ufuw">VSCode 비디오용 HDInsight</a></li>
   <li>Hive LLAP: <a href="https://docs.microsoft.com/en-us/azure/hdinsight/interactive-query/apache-interactive-query-get-started">HDInsight에서 대화형 쿼리 사용</a></li>
  </ul>


  <p><a href="https://azure.microsoft.com/en-us/blog/">Azure 블로그</a> 및 <a href="https://blogs.msdn.microsoft.com/azuredatalake">빅 데이터 블로그</a>에서 오늘&rsquo; 공지 사항에 대해 자세히 알아보세요. <a href="https://azure.microsoft.com/en-us/updates/">Azure 서비스 업데이트 페이지에서 자세히 알아보기</a></p>


  <p>질문, 피드백, 의견 또는 버그 보고서가 있는 경우 아래의 의견을 사용하거나 메모를 <a href="mailto:hdivstool@microsoft.com">hdivstool@microsoft.com</a>보내주세요.</p>
