### YamlMime:Yaml
ms.openlocfilehash: f41001109a02f34d7c1b12bd424f3475a37a8572
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139907774"
Slug: hololens-2-industrial-edition-brings-mixed-reality-to-regulated-environments
Title: HoloLens 2 인스트리얼 에디션은 규제 환경에 혼합 현실을 제공합니다.
Summary: 그것은 HoloLens 2 대한 활기찬 첫 해, 시장에서이었다. 우리는 HoloLens 2 산업 전반의 고객이 생산성을 높이고 목적을 가지고 혁신할 수 있도록 하는 방법을 보는 것을 좋아했습니다.
Content: >-
  <p>그것은&rsquo; <a href="https://www.microsoft.com/en-us/hololens/buy" target="_blank">HoloLens 2</a> 대한 활기찬 첫 해, 시장에서이었다. 우리는 HoloLens 2 산업 전반의 고객이 생산성을 높이고 목적을 가지고 혁신할 수 있도록 하는 방법을 보는 것을 좋아했습니다.</p>


  <ul>
      <li><a href="https://www.youtube.com/watch?v=GRLyP7_cqNc" target="_blank">록히드 마틴은</a> 오리온 우주선을 구축하고 8 시간 교대를 요구하는 데 사용되는 터치 노동&mdash;을 줄이기 위해 HoloLens 2 사용하여 이제 45 분 만에 완료 할 수 있습니다.</li>
      <li><a href="https://customers.microsoft.com/en-ca/story/825289-imperial-nhs" target="_blank">임페리얼 칼리지 헬스케어 NHS 트러스트</a>는 의료 직원&#39;COVID-19 환자에 대한 노출을 제한하기 위해 HoloLens 2 사용하여 직원이 질병에 노출되는 시간을 83 %까지 줄입니다.</li>
      <li><a href="https://customers.microsoft.com/en-ca/story/839709-mercedes-benz-automotive-holoLens-en-usa" target="_blank">메르세데스-벤츠 USA</a>는 HoloLens 2 사용하여 서비스 기술자 효율성을 개선하고 문제 해결 시간을 줄여 서비스 기술자 여행이 35~40% 감소하고 있습니다.</li>
  </ul>


  <p>경청과 항상 학습의 일환으로, 우리는 엄격한 요구 사항이 있거나 업계 인증에 의해 규제되는 환경에서 HoloLens 2 운영해야 한다는 강한 요구를 들었습니다. 반도체 및 제약 산업에서 파트너는 고도로 제어되는 청정실 환경에 진입하고 작동하기 위해 입자 배출 기준을 충족하는 장치를 요구합니다. 에너지 부문에서 파트너는 잠재적으로 위험한 환경에서 안전하게 작동할 수 있는 장치가 필요합니다.</p>


  <h2>작업자 생산성 향상 및 혁신 가속화</h2>


  <p>규제된 산업 환경을 지원하기 위해 설계, 빌드 및 테스트된 테더링되지 않은 혼합 현실 디바이스인 HoloLens 2 Industrial Edition을 발표합니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/18ff41b8-5c63-4fa5-9b8b-0d059635e0d5.png"><img alt="Medical worker in protective gear using Microsoft HoloLens 2" height="574" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/b3c47754-4d4b-4ec9-b1bf-aa8a15dc90b8.png" style="margin-right: auto; margin-left: auto; display: block;" title="hololens 1" width="1024"></a></p>


  <p>HoloLens 2 Industrial Edition은 다음과 같은 산업 표준 및 인증을 충족합니다.</p>


  <table class="MsoTableGrid" style="border-collapse:collapse; border:none">
      <tbody>
          <tr>
              <td style="border-bottom:2px solid black; width:312px; padding:0in 7px 0in 7px; border-top:2px solid black; border-right:2px solid black; border-left:2px solid black" valign="top">
              <p><strong>HoloLens 2 인더스트리얼 에디션 표준</strong></p>
              </td>
              <td style="border-bottom:2px solid black; width:312px; padding:0in 7px 0in 7px; border-top:2px solid black; border-right:2px solid black; border-left:none" valign="top">
              <p><strong>평가</strong></p>
              </td>
          </tr>
          <tr>
              <td style="border-bottom:2px solid black; width:312px; padding:0in 7px 0in 7px; border-top:none; border-right:2px solid black; border-left:2px solid black" valign="top">
              <p>클린룸 호환</p>
              </td>
              <td style="border-bottom:2px solid black; width:312px; padding:0in 7px 0in 7px; border-top:none; border-right:2px solid black; border-left:none" valign="top">
              <p>ISO 14644-1 클래스 5-8</p>
              </td>
          </tr>
          <tr>
              <td style="border-bottom:2px solid black; width:312px; padding:0in 7px 0in 7px; border-top:none; border-right:2px solid black; border-left:2px solid black" valign="top">
              <p>내장 안전성</p>
              </td>
              <td style="border-bottom:2px solid black; width:312px; padding:0in 7px 0in 7px; border-top:none; border-right:2px solid black; border-left:none" valign="top">
              <p>UL 클래스 I, Division2&nbsp;</p>
              </td>
          </tr>
      </tbody>
  </table>


  <p>산업 표준 등급 외에도 HoloLens 2 Industrial Edition은 2년 보증 및 신속한 교체 프로그램을 통해 지원됩니다. 신속한 교체 프로그램은 사전 교환 및 신속한 배송을 통해 가동 중지 시간을 최소화합니다.</p>


  <p>HoloLens 2 Industrial Edition을 사용하면 이제 고객은 공간, 프로토콜 또는 워크플로를 수정하지 않고 제한된 환경에서 HoloLens 2 사용할 수 있습니다. Azure의 안정성, 보안 및 규모에 따라 지원되는 자사 및 제3자 혼합 현실 애플리케이션의 강력한 에코시스템에서 지원되는 HoloLens 2 Industrial Edition은 규제 환경에서 운영되는 기업이 다음을 수행할 수 있도록 지원합니다.</p>


  <ul>
      <li>필요할 때마다 원격 전문가에게 액세스 권한을 작업자에게 제공합니다.</li>
      <li>대화형 3D 가이드를 사용하여 이전보다 빠르고 정확하게 작업을 완료합니다.</li>
      <li>접근 방식을 수행&rdquo;하여 학습을 통해 &ldquo;새 직원을 더 빠르게 교육하고 온보딩합니다.</li>
  </ul>


  <p>HoloLens 2 인더스트리얼 에디션은 HoloLens 2 사용할 수 있는 일부 시장에서 예약 주문이 가능하며 2021년 봄에 배송이 시작됩니다. <a href="https://www.microsoft.com/en-us/hololens/buy" target="_blank">자세한 내용을 알아보</a> 거나 Microsoft 채널 공급자에게 문의하세요.</p>
