### YamlMime:Yaml
ms.openlocfilehash: 704bdce5176dc0dc2552004962337ac127009fca
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139912811"
Slug: how-to-optimize-your-azure-environment
Title: Azure 환경을 최적화하는 방법
Summary: 올바른 도구와 접근 방식이 없으면 클라우드 최적화는 시간이 많이 걸리고 어려운 프로세스가 될 수 있습니다. 따라야 할 모범 사례 목록이 계속 늘어나고 있으며 클라우드 워크로드가 진화함에 따라 지속적으로 유동적으로 변하고 있습니다.
Content: >-
  <p>올바른 도구와 접근 방식이 없으면 클라우드 최적화는 시간이 많이 걸리고 어려운 프로세스가 될 수 있습니다. 따라야 할 모범 사례 목록이 계속 늘어나고 있으며&rsquo; 클라우드 워크로드가 진화함에 따라 지속적으로 유동적으로 발전합니다. 매일 직면하는 과제와 비상 사태를 추가하고 클라우드&rsquo; 리소스가 최적으로 실행되도록 하는 데 사전 예방하기가 어려운 이유를&rsquo; 쉽게 이해할 수 있습니다.</p>


  <p>Azure는 워크로드를 최적으로 실행하고 투자를 최대한 활용하도록 여러&rsquo; 가지 방법을 제공합니다.</p>


  <h2>최적화의 세 가지 종류: 조직, 아키텍처 및 전술</h2>


  <p>이에 대해 생각하는 한 가지 방법은 제공되는 조언과 최적화의 고도입니다: 조직, 건축 또는 전술.<br>

  전술 또는 리소스 수준에서 고가용성, 보안, 성능 및 비용을 위해 Azure 리소스를 최적화하는 데 도움이 되는 무료 Azure 서비스인 Azure <a href="https://aka.ms/advisor-acom" target="_blank">Advisor</a>가 있습니다. Advisor는 리소스 사용량 및 구성을 검사하고 100개가 넘는 개인 설정된 권장 사항을 제공합니다. 각 권장 사항에는 클라우드 리소스 최적화를 빠르고 쉽게 수정하기 위한 인라인 작업이 포함됩니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/a3f087a2-f6c0-4a4e-b33d-35cfd5279f6d.png"><img alt="Software as a Service plan creation in Partner Center showing seat based billing." border="0" height="606" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/d89d53e3-064b-44ea-bb61-5197e37b1994.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="좌석 기반 청구를 보여 주는 파트너 센터에서 Software as a Service 계획 생성" width="1024"></a></p>


  <p>스펙트럼의 다른 쪽 끝에는 조직 및 아키텍처 모범 사례를 이해하고 워크로드를 최적화하는 데 도움이 되는 Azure 전문가가 만든 무료 가이드 모음인 Azure <a href="https://docs.microsoft.com/en-us/azure/architecture/" target="_blank">Architecture Center</a>가 있습니다. 이 지침은 클라우드에 대한 새 워크로드를 디자인하거나 기존 워크로드를 온-프레미스에서 클라우드로 마이그레이션할 때&rsquo; 특히 유용합니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/d1e61232-da2c-43fe-ba1a-2e2be585f494.png"><img alt="Azure Architechture Center main page." border="0" height="607" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/78aa57a7-d568-45a9-8a05-31dca3551b8b.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="Azure Architechture Center 기본 페이지입니다." width="1024"></a></p>


  <p>Azure 아키텍처 센터의 가이드는 클라우드 채택 및 전략에 대한 조직의&rsquo; 접근 방식을 안내하는 데 도움이 되는 <a href="https://docs.microsoft.com/en-us/azure/architecture/cloud-adoption/" target="_blank">Azure용 Microsoft 클라우드 채택 프레임워크</a>부터 AI, IoT, 마이크로 서비스, 서버리스, SAP, 웹앱 등과 같은 일반적인 시나리오에 권장되는 아키텍처 및 사례를 제공하는 <a href="https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/" target="_blank">Azure 참조 아키텍처</a>에 이르기까지 다양합니다.</p>


  <h2>작게 시작하고 모멘텀을 얻습니다.</h2>


  <p>Azure 환경 최적화를 시작하는 방법에는 여러 가지가 있습니다. 클라우드 채택 전략에서 조직으로 정렬하거나, 제공하는 참조 아키텍처에 대해 워크로드 아키텍처를 검토하거나, Advisor를 열고 모범 사례 권장 사항이 있는 리소스를 확인할 수 있습니다. 이는 단지 몇 가지 예에 불과하며, 궁극적으로&rsquo;는 사용자와 조직만 선택할 수 있습니다.</p>


  <p>조직이 가장 비슷하다면 소규모로 시작하여 추진력을 얻는 데 도움이 됩니다. Weve&rsquo;는 많은 고객이 전술 또는 리소스 수준에서 최적화 여정을 시작한 다음 워크로드 수준에서 궁극적으로 조직 수준까지 작업하는 데 성공하여 배운 내용을&rsquo; 통합하고 정책을 구현할 수 있습니다.</p>


  <h2>Azure Adviser 시작</h2>


  <p>Advisor&rsquo;를 방문하면 환경을 최적화하기 위해 수행할 수 있는 많은 권장 작업을 찾을 수 있습니다. 우리의 조언? 압도하지 마십시오&rsquo;. 그냥 시작. 권장 사항에서 사용자와 조직에 가장 의미 있는 기회를 검색합니다. 일부 경우 VM 백업과 같은 고가용성 고려 사항, 특히 개발/테스트에서 프로덕션으로 전환할 때 VM 만들기에 대한 일반적인 감독일 수 있습니다. 다른 사용자의 경우 사용이 부족한 VM을 확인하여 비용 절감을 찾을 수 있습니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/67294587-2ab5-480e-bd9f-68d551c9dc09.png"><img alt="Azure Advisor recommendation details screen." border="0" height="608" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/4f753c06-3c79-4819-9704-47743b2c9430.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="Azure Advisor 권장 사항 세부 정보 화면" width="1024"></a></p>


  <p>&rsquo;적절한 권장 사항이 발견되면 <a href="https://www.youtube.com/watch?v=xO3V3FZWXwc" target="_blank">이 비디오에 표시된 대로</a> 수정합니다. 최적화는 진행 중인 프로세스이며 실제로 완료되지는 않았지만 모든 단계는 올바른 방향으로 나아가는 단계입니다.</p>


  <p><a href="https://aka.ms/azureadvisor" target="_blank">Azure Portal의 Advisor를 방문하여</a> 권장 사항 검토 및 수정을 시작합니다. 자세한 지침은 <a href="https://aka.ms/azureadvisordocs" target="_blank">Azure Advisor 설명서를 참조하세요</a>. <a href="https://aka.ms/advisorfeedback" target="_blank">여기에 피드백 도구</a>에 아이디어를 제출하여 Advisor에 대한 제안이 있는지 알려주세요.</p>
