### YamlMime:Yaml
ms.openlocfilehash: 9291a2996b73703898cc6b0d152fe60916bbfdc1
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139898602"
Slug: how-to-configure-azure-sql-database-geo-dr-with-azure-key-vault
Title: Azure Key Vault에서 Azure SQL Database Geo-DR을 구성하는 방법
Summary: 고가용성을 유지하기 위해 지역에서 복제된 데이터베이스에 BYOK를 사용하여 TDE를 활용하려면 시나리오를 신중하게 구성하고 테스트해야 합니다. 이 게시물은 가장 일반적인 구성 옵션을 살펴보겠습니다.
Content: >-
  <p>Azure SQL Database 및 Data Warehouse는 데이터베이스, 로그 파일 및 백업을 포함하여 디스크에 기록된 모든 데이터에 대한 TDE(투명한 데이터 암호화)를 제공하여 미사용 암호화를 제공합니다. 이렇게 하면 하드웨어에 무단으로 액세스하는 경우 데이터를 보호합니다. TDE는 데이터를 암호화하는 데 사용되는 DEK(데이터베이스 암호화 키)를 암호화하는 데 사용되는 TDE 보호기를 제공합니다. 현재 미리 보기로 제공되는 TDE 및 BYOK(Bring Your Own Key) 제품을 통해 고객은 Azure Key Vault에서 TDE 보호기를 제어할 수 있습니다.</p>


  <p>고가용성을 유지하기 위해 지역에서 복제된 데이터베이스에 BYOK를 사용하여 TDE를 활용하려면 시나리오를 신중하게 구성하고 테스트해야 합니다. 이 게시물은 가장 일반적인 구성 옵션을 살펴보겠습니다.</p>


  <p>활성 지역 복제 인스턴스 또는 SQL 장애 조치(failover) 그룹에서 단일 실패 지점을 만들지 않도록 하려면 중복 Azure Key Vault를 구성해야 합니다. 각 지역 복제 서버에는 동일한 Azure 지역의 서버와 공동 배치해야 하는 별도의 키 자격 증명 모음이 필요합니다. 한 지역에서 중단으로 인해 주 데이터베이스에 액세스할 수 없게 되고 장애 조치가 트리거되면, 보조 데이터베이스에서 보조 키 자격 증명 모음을 사용하여 인수할 수 있습니다.</p>


  <p>지역 복제된 Azure SQL 데이터베이스에 필요한 Azure Key Vault 구성은 다음과 같습니다.</p>


  <ul>
   <li>지역에 하나의 키 자격 증명 모음이 있는 주 데이터베이스 및 지역에 하나의 키 자격 증명 모음이 있는 하나의 보조 데이터베이스가 있습니다.</li>
   <li>하나 이상의 보조 데이터베이스가 필요합니다(최대 4개 지원).</li>
   <li>보조(체인)&nbsp;의 보조는 지원되지 않습니다.</li>
  </ul>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/21d2541b-d8c9-40b6-8f39-02c88bdb368c.png"><img alt="Geo-DR config" border="0" height="454" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/6f81f172-b829-4ad1-919e-271ccac11284.png" style="border: 0px currentColor; border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="지역 DR 구성" width="826"></a></p>


  <p>새 Geo-DR 구성으로 시작하는 경우 데이터베이스 간의 지역 연결을 설정하기 전에 두 키 자격 증명 모음에 동일한 TDE 보호기가 있는지 확인해야 합니다.</p>


  <p>기존 Geo-DR 배포를 사용하는 경우 먼저 보조 서버에 키 자격 증명 모음을 할당해야 합니다. Azure Key Vault를 사용하여 보조 서버를 구성한 후 주 서버에 대해 이 단계를 완료하고 해당 TDE 보호기가 업데이트된 후에 완료할 수 있습니다. 이 시점에서 복제된 데이터베이스에서 사용하는 TDE 보호기를 두 서버에서 모두 사용할 수 있기 때문에 기존 지역 DR 링크가 계속 작동합니다.</p>


  <p><a href="https://docs.microsoft.com/en-us/sql/relational-databases/security/encryption/transparent-data-encryption-byok-azure-sql#how-to-configure-geo-dr-with-azure-key-vault" target="_blank">자세한 단계별 구성 지침은 설명서를 참조하세요.</a></p>


  <h2>요약</h2>


  <p>Azure Key Vault에서 SQL Database Geo-DR 시나리오를 위해 고객 관리 키를 사용하여 TDE를 활성화하기 전에 SQL Database 지역 복제에 사용될 동일한 지역에 동일한 콘텐츠가 있는 두 개의 Azure Key Vault를 만들고 유지 관리해야 합니다. &ldquo;동일한 콘텐츠는&rdquo; 특히 두 서버가 모든 데이터베이스에서 사용하는 TDE 보호기에 액세스할 수 있도록 두 키 자격 증명 모음에 동일한 TDE 보호기의 복사본을 포함해야 한다는 것을 의미합니다. 앞으로 두 키 자격 증명 모음을 동기화 상태로 유지해야 합니다.&nbsp; 즉, 키 회전 후 두 키 자격 증명 모음에 동일한 TDE 보호기 복사본이 포함되어야 하며 로그 파일 또는 백업에 사용되는 이전 버전의 키를 유지 관리해야 합니다. 또한 TDE 보호기는 동일한 키 속성을 유지해야 하며 키 자격 증명 모음은 SQL 대해 동일한 액세스 권한을 유지해야 합니다. 시나리오가 계속 작동하는지 확인하기 위해 정기적으로 장애 조치(failover)를 테스트하고 트리거하는 것이 가장 좋습니다. 장애 조치(failover)를 관리하고 트리거하는 방법에 대한 자세한 내용은 장애 조치 <a href="https://docs.microsoft.com/en-us/azure/sql-database/sql-database-geo-replication-overview#programmatically-managing-failover-groups-and-active-geo-replication" target="_blank">(failover) 그룹 설명서 페이지에</a> 설명되어 있습니다.</p>
