### YamlMime:Yaml
ms.openlocfilehash: 5bfc1b328e58559fd0581840411177cb3c85dd54
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139906741"
Slug: how-to-using-visual-studio-to-build-applications-that-integrate-with-hdinsighthadoop
Title: "\"방법\": Visual Studio 사용하여 HDInsight/Hadoop과 통합되는 애플리케이션 빌드"
Summary: 사용자 지정 애플리케이션에서 "빅 데이터"로 생산성을 Visual Studio 개발자를 만들기 위해 Azure SDK의 최근 업데이트에서 Visual Studio HDInsight에 대한 심층적인 도구 환경을 추가했습니다.
Content: >-
  개발자가 사용자 지정 애플리케이션에서 "빅 데이터"로 생산성을 Visual Studio 있도록 Azure <a href="https://azure.microsoft.com/blog/2014/11/12/announcing-azure-sdk-2-5-for-net-and-visual-studio-2015-preview/">SDK</a>의 최근 업데이트에서 Visual Studio HDInsight에 대한 심층적인 도구 환경을 추가했습니다. 이 Visual Studio 확장은 개발자가 친숙하고 강력한 도구에서 Hadoop 클러스터, 테이블 및 관련 스토리지를 시각화하는 데 도움이 됩니다. 이제 개발자는 Visual Studio 내에서 클러스터에 대해 직접 HDInsight에 대한 임시 Hive 쿼리를 만들고 제출하거나 다른 Visual Studio 프로젝트처럼 관리되는 Hive 애플리케이션을 빌드할 수 있습니다.


  <a href="https://www.microsoft.com/web/handlers/webpi.ashx/getinstaller/VWDOrVs2013AzurePack.appids">VS 2013VS 2012VS</a> <a href="https://www.microsoft.com/web/handlers/webpi.ashx/getinstaller/VWDOrVs11AzurePack.appids">2015</a>| <a href="https://www.microsoft.com/web/handlers/webpi.ashx/getinstaller/VWDOrVs2015AzurePack.appids">Preview</a>용 Azure SDK를 지금 다운로드합니다.|


  HDInsight 개체를 "서버 탐색기"에 통합하면 Azure의 다른 클라우드 서비스와 동일한 페이지에 빅 데이터 자산이 제공됩니다. 이렇게 하면 클러스터, Hive 테이블 및 해당 스키마를 빠르고 간단하게 탐색하여 테이블의 처음 100개 행을 쿼리할 수 있습니다.이렇게 하면 Visual Studio 작업 중인 데이터의 모양을 빠르게 이해할 수 있습니다.


  또한 Hive 쿼리를 만들고 작업으로 제출하는 도구도 있습니다. Hadoop 클러스터에 대해 상황에 맞는 메뉴를 사용하여 Hive 쿼리 스크립트 작성을 즉시 시작합니다. 아래 예제에서는 지리적 정보가 포함된 Hive 테이블에 대한 간단한 쿼리를 만들어 모든 국가의 수를 찾아 국가별로 정렬합니다. 작업 브라우저 도구를 사용하면 작업 제출 및 상태를 시각화할 수 있습니다.작업을 두 번 클릭하여 Hive 작업 요약 창에서 요약 및 세부 정보를 가져옵니다.


  또한 Azure Blob 컨테이너로 이동하여 열면 해당 컨테이너에 포함된 파일로 작업할 수 있습니다. 백업 저장소는 Azure 대시보드에서 클러스터를 만드는 동안 Hadoop 클러스터와 연결됩니다. Hadoop 클러스터의 관리는 동일한 Azure 대시보드에서 계속 수행됩니다.


  <a href="https://acom.azurecomcdn.net/80C57D/blogmedia/blogmedia/2014/11/27/clip_image002.jpg"><img style="padding-top: 0px; padding-left: 0px; padding-right: 0px; border: 0px;" title="clip_image002" alt="clip_image002" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/clip_image002_thumb.jpg" width="539" height="325" border="0" /></a>


  더 복잡한 스크립트 개발 및 수명 주기 관리를 위해 Visual Studio 내에 Hive 프로젝트를 만들 수 있습니다. 새 프로젝트 대화 상자(아래 참조)에서 새 HDInsight 템플릿 범주를 찾을 수 있습니다. 유용한 시작점은 Hive 샘플 프로젝트 유형입니다. 이 프로젝트는 웹 서버 로그를 처리하는 경우 보다 복잡한 Hive 쿼리 및 샘플 데이터로 미리 채워집니다.


  <a href="https://acom.azurecomcdn.net/80C57D/blogmedia/blogmedia/2014/11/27/clip_image004.png"><img style="padding-top: 0px; padding-left: 0px; padding-right: 0px; border: 0px;" title="clip_image004" alt="clip_image004" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/clip_image004_thumb.png" width="538" height="374" border="0" /></a>


  시작하려면 다음 리소스를 활용하세요.

  <ul>
   <li><a href="https://channel9.msdn.com/Events/Visual-Studio/Connect-event-2014/410">채널 9의 비디오 데모</a></li>
   <li><a href="https://azure.microsoft.com/en-us/documentation/articles/hdinsight-hadoop-visual-studio-tools-get-started/">문서 시작</a></li>
  </ul>
