### YamlMime:Yaml
ms.openlocfilehash: 78c5c8b4c425c788cb7409f8788e974971c562bc
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139906757"
Slug: how-azure-security-center-helps-you-protect-your-environment-from-new-vulnerabilities
Title: Azure Security Center를 통해 새 취약성으로부터 환경을 보호하는 방법
Summary: 최근 취약성(CVE-2019-5736)의 공개가 OSS(오픈 소스 소프트웨어) 컨테이너 런타임인 runc에서 발표되었습니다. 이 취약성을 통해 공격자는 "호스트"에서 루트 수준 코드 실행을 얻을 수 있습니다. runc"는 널리 사용되는 많은 컨테이너 아래의 기본 컨테이너 런타임입니다.
Content: >-
  <p>최근 <a href="https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2019-5736" target="_blank">취약성(CVE-2019-5736)의 공개</a> 가 OSS(오픈 소스 소프트웨어) 컨테이너 런타임인 runc에서 발표되었습니다. 이 취약성을 통해 공격자는 호스트에서 루트 수준 코드 실행을 얻을 수 있습니다. Runc는 널리 사용되는 많은 컨테이너 아래에 있는 기본 컨테이너 런타임입니다.</p>


  <p>Azure Security Center는 Microsoft Azure, 온-프레미스 또는 기타 클라우드 내에서 사용자 환경에서 취약한 리소스를 검색하는 데 도움이 될 수 있습니다. Azure Security Center는 악용이 발생했음을 감지하고 사용자에게 경고할 수도 있습니다.</p>


  <p>Azure Security Center는 악의적인 동작을 완화하거나 검색하기 위해 적용할 수 있는 몇 가지 방법을 제공합니다.</p>


  <ul>
      <li><strong>보안 태세</strong> &ndash; 강화 Azure Security Center는 리소스의 보안 상태를 주기적으로 분석합니다. 잠재적인 보안 취약성을 식별하면 권장 사항이 생성됩니다. 권장 사항은 필요한 컨트롤을 구성하는 프로세스를 안내합니다. 패치되지 않은 리소스가 검색되면 권장 사항을 추가할 계획입니다. <a href="https://docs.microsoft.com/en-us/azure/security-center/security-center-recommendations" target="_blank">Azure Security Center의 보안 권장 사항 관리</a> 설명서를 &ldquo; 방문하여 보안 상태 강화에 대한 자세한 정보를 확인할 수 있습니다.&rdquo;</li>
      <li><strong>FIM(파일 무결성 모니터링)</strong> &ndash; 이 메서드는 운영 체제, 애플리케이션 소프트웨어 등의 파일 및 레지스트리 키를 검사하여 공격을 나타낼 수 있는 변경 내용을 확인합니다. FIM을 사용하도록 설정하면 Azure Security Center는 악의적인 활동을 나타낼 수 있는 디렉터리의 변경 내용을 검색할 수 있습니다. FIM을 사용하도록 설정하고 Linux 머신에서 파일 추적을 추가하는 방법에 대한 지침은 <a href="https://docs.microsoft.com/en-us/azure/security-center/security-center-file-integrity-monitoring#add-a-new-entity-to-monitor" target="_blank">Azure Security Center의 파일 무결성 모니터링</a> 설명서 &ldquo; 에서 찾을 수 있습니다.&rdquo;</li>
      <li><strong>보안 경고</strong> &ndash; Azure Security Center는 감사된 프레임워크를 사용하여 Linux 머신에서 의심스러운 활동을 검색합니다. 수집된 레코드는 위협 탐지 파이프라인으로 흐르고 악의적인 활동이 감지되면 경고로 표시됩니다. 보안 경고 범위에는 곧 Runc 취약성으로 손상된 머신을 식별하는 새로운 분석이 포함됩니다. Azure <a href="https://docs.microsoft.com/en-us/azure/security-center/security-center-detection-capabilities" target="_blank">Security Center 검색 기능</a> 설명서를 &ldquo; 방문하여 보안 경고에 대한 자세한 정보를 확인할 수 있습니다.&rdquo;</li>
  </ul>


  <p>최상의 보안 위생 사례를 적용하려면 배포 공급자의 최신 업데이트를 포지싱하도록 환경을 구성하는 것이 좋습니다. 시스템 업데이트는 Azure Security Center를 통해 수행할 수 있습니다. 자세한 지침은 Azure <a href="https://docs.microsoft.com/en-us/azure/security-center/security-center-apply-system-updates" target="_blank">Security Center의 시스템 업데이트 적용</a> 설명서를 &ldquo; 참조하세요.&rdquo;</p>
