### YamlMime:Yaml
ms.openlocfilehash: 668293f9c669d85e2834619431db12b6ec993a85
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139898588"
Slug: how-to-develop-secure-applications-using-azure-cosmos-db
Title: Azure Cosmos DB를 사용하여 보안 애플리케이션을 개발하는 방법
Summary: 'Azure Cosmos DB는 링 제로 Azure 서비스입니다. 즉, 온라인 상태가 되는 즉시 모든 새 Azure 데이터 센터에서 사용할 수 있으며 모든 규정 준수 인증서를 최신 상태로 유지해야 합니다. '
Content: >-
  <p>Azure Cosmos DB를 사용하여 보안 애플리케이션을 개발하는 방법을 알아보기 전에 Azure Cosmos DB에서 제공하는 다양한 보안 계층 중 일부를 강조 표시해야 합니다. 다음 이미지는 이러한 다양한 보안 계층을 보여 줍니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/e9133f43-c841-48df-bbf5-8fc545b136d3.png"><img alt="flow chart for the various layers of security provided by Cosmos DB " border="0" height="394" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/ecf8d2a1-ea8d-4734-beba-714696e85a97.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="Cosmos DB에서 제공하는 다양한 보안 계층에 대한 흐름도" width="640"></a></p>


  <p>Azure Cosmos DB는 링 제로 Azure 서비스입니다. 즉, 온라인 상태가 되는 즉시 모든 새 Azure 데이터 센터에서 사용할 수 있으며 모든 규정 준수 인증서를 최신 상태로 유지해야 합니다. Azure Cosmos DB에는 Azure #CosmosDB 블로그 게시물&ldquo;( <a href="https://azure.microsoft.com/en-us/blog/azure-cosmosdb-secure-private-compliant/" target="_blank">보안, 프라이빗, 규격</a>)에서 자세히 읽을 수 있는 다양한 인증이 있습니다.&rdquo;</p>


  <p>Azure의 첫 번째 계층은 데이터 센터의 물리적 안전성과 DDoS 공격으로부터의 지속적인 보호를 제공합니다. Azure에는 보안 문제를 지속적으로 모니터링하는 전용 팀이 있습니다. 모든 Azure 서비스는 일반적인 보안 에이전트를 실행하여 비정상적인 활동을 수집합니다. 프로덕션 리소스는 정기적으로 패치되며 모든 비밀, 인증서 또는 암호는 정의된 수명을 갖습니다. 이러한 인증서 또는 비밀은 만료된 후 순환해야 합니다. Azure Cosmos DB의 모든 프로덕션 포트는 정기적으로 검사되고 침투 테스트됩니다. 소스 코드는 보안 문제를 검사하고 제품에 통합하기 전에 두 명의 승인자가 필요합니다. 자세한 내용은 <a href="https://azure.microsoft.com/en-us/global-infrastructure/" target="_blank">Azure 데이터 센터에</a> 대해 자세히 알아보세요.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/4287e9ce-5cb7-4751-b248-dad4d00d52b2.png"><img alt="Map of availability regions, announced regions, and availability zones" border="0" height="392" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/6d9d8af5-70d6-4daf-a074-6735869579c6.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="가용성 지역, 발표된 지역 및 가용성 영역의 지도" width="800"></a></p>


  <p>Azure에 대한 액세스가 제한됩니다. Azure Cosmos DB에서 작업하는 운영 직원 또는 개발자는 머신에서 프로덕션에 액세스할 수 없습니다. 모든 프로덕션은 전용 SAW(보안 액세스 워크스테이션)를 통해 액세스됩니다. 이러한 워크스테이션은 방수이며 Azure를 통해서가 아닌 한 이러한 컴퓨터에서 외부 액세스가 없습니다. 엔지니어는 모든 프로덕션 액세스에 대해 JIT(Just-In-Time) 승인을 받습니다. 모든 액세스가 모니터링되고 엔지니어의 모든 활동이 에스코트에 의해 모니터링됩니다.&nbsp; 모든 프로덕션 배포에는 테스트 로그오프 및 승인자를 포함하여 여러 승인이 필요합니다.</p>


  <p>Azure에는 Microsoft 담당자의 매우 엄격한 액세스 정책이 있습니다. 권한이 없는 경우 Microsoft 직원이 프로덕션 시스템에 액세스하는 것은 거의 불가능합니다. 고객이 Azure에서 데이터가 안전한지 여부와 Azure Cosmos DB 엔지니어링 팀이 데이터에 액세스할 수 있는지 묻기 때문에 이러한 세부 정보를 언급합니다.</p>


  <h2>IP 방화벽에서 제공하는 보안</h2>


  <p>IP 방화벽을 사용하는 것이 데이터베이스를 보호하기 위한 첫 번째 보호 계층입니다. Azure Cosmos DB는 인바운드 방화벽 지원을 위해 정책 중심 IP 기반 액세스 제어를 지원합니다. 이 모델은 기존 데이터베이스 시스템의 방화벽 규칙과 같으며 Azure Cosmos DB 계정에 추가 수준의 보안을 제공합니다. 이제 이 모델을 사용하여 승인된 컴퓨터 및/또는 클라우드 서비스에서만 액세스할 수 있도록 Azure Cosmos DB 계정을 구성할 수 있습니다. 이러한 승인된 컴퓨터 및 서비스에서 Azure Cosmos DB 리소스에 액세스하려면 여전히 호출자가 유효한 권한 부여 토큰을 제공해야 합니다.</p>


  <p>IP 액세스 제어 정책은 Azure Portal에서 설정하거나 ipRangeFilter&rdquo; 속성을 업데이트&ldquo;하여 <a href="https://docs.microsoft.com/en-us/azure/cosmos-db/cli-samples" target="_blank">Azure CLI</a>, <a href="https://docs.microsoft.com/en-us/azure/cosmos-db/powershell-samples" target="_blank">Azure PowerShell</a> 또는 <a href="https://docs.microsoft.com/en-us/azure/cosmos-db/powershell-samples" target="_blank">REST API</a>를 통해 프로그래밍 방식으로 설정할 수 있습니다. 자세한 내용은 <a href="https://docs.microsoft.com/en-us/azure/cosmos-db/firewall-support" target="_blank">Cosmos DB용 IP 방화벽을 설정하는 방법에 대해</a> 자세히 알아보세요.</p>


  <h2>가상 네트워크에서 제공하는 보안</h2>


  <p>가상 네트워크는 Azure Cosmos DB 계정을 보호하는 다음 계층입니다. Azure Cosmos DB 계정을 구성하여 Azure Virtual Network의 특정 서브넷에서만 액세스할 수 있도록 할 수 있습니다. 가상 네트워크 및 해당 서브넷에서 Azure Cosmos DB에 <a href="https://docs.microsoft.com/en-us/azure/virtual-network/virtual-network-service-endpoints-overview" target="_blank">대한 서비스 엔드포인트</a>를 사용하도록 설정하면 트래픽이 Azure Cosmos DB에 대한 최적의 안전한 경로를 보장합니다.</p>


  <p>Azure Cosmos DB 계정이 가상 네트워크 서비스 엔드포인트로 구성되면 지정된 서브넷에서만 액세스할 수 있으며 공용 또는 인터넷 액세스가 제거됩니다. 서비스 엔드포인트에 대해 자세히 알아보려면 Azure &ldquo;<a href="https://docs.microsoft.com/en-us/azure/virtual-network/virtual-network-service-endpoints-overview" target="_blank">Virtual Network 서비스 엔드포인트</a>&rdquo; 개요 문서를 참조하세요. 가상 네트워크 설명서의 Access Azure Cosmos DB 리소스에서 &ldquo; 가상 네트워크 &ldquo;및 <a href="https://docs.microsoft.com/en-us/azure/cosmos-db/vnet-service-endpoint" target="_blank">Azure Cosmos DB에</a> 대해 자세히 알아볼 수도 있습니다.</p>


  <p>네트워크 보안 그룹을 사용하여 <a href="https://docs.microsoft.com/en-us/azure/virtual-network/virtual-networks-overview" target="_blank">Azure Virtual Network의 Azure</a> 리소스에서 네트워크 트래픽을 필터링할 수 있습니다. 네트워크 보안 그룹에는 여러 유형의 Azure 리소스에서 인바운드 네트워크 트래픽 및 아웃바운드 네트워크 트래픽을 허용하거나 거부하는 <a href="https://docs.microsoft.com/en-us/azure/virtual-network/security-overview#security-rules" target="_blank">보안 규칙이</a> 포함되어 있습니다. 자세한 내용은 <a href="https://docs.microsoft.com/en-us/azure/virtual-network/security-overview" target="_blank">네트워크 보안 그룹에</a> 대해 자세히 알아보세요.</p>


  <h2>키를 사용하여 액세스 제어</h2>


  <p>지금까지 설명한 보안 계층은 Azure Cosmos DB의 일부로 제공되며 방화벽 및 가상 네트워크를 구성하는 것 외에는 그다지 필요하지 않습니다&rsquo;. 이제 애플리케이션 개발자로서 수행할 수 있는 작업에 대해 설명합니다&rsquo;. Azure Cosmos DB에 대한 모든 액세스는 마스터 키와 읽기 전용 키라는 두 개의 키로 제어됩니다. 이름에서 알 수 있듯이 마스터 키는 마스터 키이며 Azure Cosmos DB에서 모든 작업을 수행할 수 있습니다. 읽기 전용 키를 사용하면 데이터를 읽을 수 있지만 이 키로는 다른 작업을 수행할 수 없습니다.</p>


  <p>개발자는 누군가가 키를 훔치고 데이터에 액세스할 수 있는지 궁금해하면서 키에 대해 걱정할 수 있습니다. 이 게시물의 나머지 부분에는 Azure Cosmos DB에서 보안 애플리케이션을 빌드하기 위해 채택해야 하는 아키텍처에 대해 설명합니다.</p>


  <h2>보안 애플리케이션을 빌드하기 위한 아키텍처</h2>


  <p>첫째, <strong>애플리케이션에는 구성 파일 또는 코드에 액세스 키가 없어야 합니다</strong>. 키는 항상 Key Vault에 보관해야 합니다. 애플리케이션 또는 사용자는 Key Vault에 관리 <a href="https://docs.microsoft.com/en-us/azure/app-service/app-service-managed-service-identity" target="_blank">ID</a> 를 등록할 수 있으며 런타임에 키를 가져올 수 있습니다. <a href="https://docs.microsoft.com/en-us/azure/cosmos-db/access-secrets-from-keyvault" target="_blank">Azure Cosmos DB와 키 자격 증명 모음을 통합하는 방법에</a> 대해 자세히 알아보세요.</p>


  <p>둘째,<strong> 애플리케이션이 데이터베이스에 직접 액세스하려고 하면 안 됩니다. 데이터에 액세스하려면 중간 계층 웹 서비스가 있어야 합니다.</strong> 이 방법은 다음과 같은 이점을 제공합니다.</p>


  <ul>
   <li>프런트 엔드 애플리케이션은 REST 서비스를 호출하여 데이터를 가져올 수 있습니다. 프런트 엔드는 Azure Cosmos DB의 다른 API&rsquo;를 이해할 필요가 없습니다. Azure Cosmos DB는 다중 모델 데이터베이스이며 데이터를 다양한 형식으로 유지할 수 있지만 프런트 엔드 애플리케이션은 데이터 액세스의 모든 세부 정보에서 추상화할 수 있습니다.</li>
   <li>일반적으로 동일한 데이터에 액세스하는 다양한 형식(PC, 휴대폰 및 웹)의 많은 애플리케이션이 있을 수 있습니다. 모든 애플리케이션이 데이터 검색 논리를 반복해야 하는 것은 아닙니다.</li>
   <li>웹 서비스 계층의 불량 애플리케이션에 필요한 경우 데이터베이스에 해를 끼치기 전에 제한을 제공할 수 있습니다.</li>
   <li>데이터베이스에 대한 모든 액세스를 더 세부적으로 감사할 수 있습니다.</li>
   <li>물론 데이터 계층의 추상화, 캐싱 기회, 서로 다른 팀이 서로 다른 계층에서 병렬로 작업하고, 다른 계층을 별도로 크기 조정하고, 유지 관리의 용이성 등과 같은 3계층 아키텍처의 다양한 이점이 있습니다.</li>
  </ul>


  <p>또한 가장 큰 이점은 키에 액세스해야 하는 서비스가 하나뿐이라는 것입니다. 키를 회전할 때 수백 또는 수천 개의 클라이언트가 아닌 하나의 서비스만 새로 고쳐야 합니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/f3e2a3bb-7b96-4c63-85b0-88554e462119.png"><img alt="Flow chart of Application authentication by Azure Active Directory and REST web service " border="0" height="514" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/4c3eadfd-8e6e-40f1-9d7d-ddf66618ff5c.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="Azure Active Directory 및 REST 웹 서비스에 의한 애플리케이션 인증의 Flow 차트" width="640"></a></p>


  <p>위와 같이 AAD 인증되고 REST 웹 서비스를 호출하는 애플리케이션을 가질 수 있습니다. 위에 표시된 애플리케이션은 수만 개의 웹 사이트 인스턴스일 수 있습니다. REST API는 호출에서 호출자 ID를 가져옵니다. 이 웹 서비스에서 통화에 대한 몇 가지 비즈니스 규칙을 적용할 수 있는 기회는 다음과 같습니다. 이 웹 서비스는 사용자 지정 규칙을 참조하여 Azure Cosmos DB 컬렉션에 대한 권한이 있는 사용자를 확인할 수 있습니다. 비즈니스 규칙 계층이 호출의 유효성을 검사하면 Data Service는 Key-Vault 키를 가져와 Azure Cosmos DB에서 데이터에 액세스할 수 있습니다.</p>


  <p>Azure Cosmos DB를 자세히 따르는 경우 <a href="https://docs.microsoft.com/en-us/azure/cosmos-db/secure-access-to-data#resource-tokens" target="_blank">리소스 토큰</a>에 대해 궁금할 수 있습니다. 리소스 토큰을 분배할 수 있는 서비스를 구현하는 대신 위의 아키텍처를 선호해야 합니다. 그런 다음 클라이언트가 해당 리소스 토큰을 사용하여 Azure Cosmos DB에 직접 액세스할 수 있습니다.</p>


  <p>여러 클라이언트 앱이 데이터베이스에 직접 액세스하도록 하는 것보다 데이터 서비스를 사용하는 것이 더 나은 디자인이라고 주장합니다. 리소스 토큰은 작은 애플리케이션에 적합한 솔루션이지만 몇 가지 제한 사항이 있습니다. 리소스 토큰은 모든 API&rsquo;에 대해 작동하지 않습니다. SQL API에 대해서만 작동합니다. 여전히 비즈니스 규칙에 따라 토큰을 분배하는 웹 서비스를 만들어야 하므로 해당 서비스가 한 단계 앞서 데이터 자체를 분배하지 않는&rsquo; 이유는 무엇인가요?</p>


  <p>예, 애플리케이션에 대한 홉을 추가하고 몇 밀리초가 추가될 수 있지만 리소스 토큰에 대한 더 나은 대안입니다.<br>

  Azure Cosmos DB는 모든 데이터를 미사용 및 유선으로 암호화된 상태 유지합니다.&nbsp; 가상 네트워크, IP 필터링 Key-Vault 사용하여 Azure Cosmos DB를 사용하여 매우 안전한 애플리케이션을 빌드할 수 있습니다.</p>


  <h2>규정 준수 리소스</h2>


  <ul>
   <li><a href="https://servicetrust.microsoft.com/ComplianceManager" target="_blank">Microsoft Compliance Manager</a></li>
   <li><a href="https://servicetrust.microsoft.com/FrameworkDetailV2/d484c25a-3141-426a-be3c-3888908a434b" target="_blank">Microsoft Service Trust Portal</a></li>
   <li><a href="https://www.microsoft.com/en-us/trustcenter/compliance/complianceofferings" target="_blank">Microsoft 보안 센터</a></li>
   <li><a href="https://azure.microsoft.com/en-us/blog/azure-cosmosdb-secure-private-compliant/" target="_blank">Azure #Cosmos DB: 보안, 프라이빗, 규격</a></li>
  </ul>


  <h2>위험 평가 리소스</h2>


  <ul>
   <li><a href="https://ecosystemmanager.azurewebsites.net/v2/home" target="_blank">Azure Eco System Manager</a></li>
   <li><a href="https://msazure.visualstudio.com/AzureWiki/_wiki/wikis/AzureWiki.wiki?pagePath=%2FAzure-Wiki-Home%2FCompliance%2FRisk-Assessment&amp;wikiVersion=GBwikiMaster" target="_blank">Microsoft Azure 개발자 도구</a></li>
  </ul>
