### YamlMime:Yaml
ms.openlocfilehash: ce10f31dd9dd6919be98cfa9327b0fc2bda005e6
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139906758"
Slug: how-azure-security-center-helps-protect-your-servers-with-web-application-firewall
Title: Azure Security Center가 웹 애플리케이션 방화벽을 사용하여 서버를 보호하는 방법
Summary: 악의적 사용자는 인터넷에서 사이버 공격을 탑재하는 데 사용할 수 있는 많은 도구를 가지고 있습니다. 이러한 도구의 대부분을 통해 엔터프라이즈 IT 리소스에 대한 액세스 및 제어를 얻을 수 있습니다. 그 동안,...
Content: >-
  <p>악의적 사용자는 인터넷에서 사이버 공격을 탑재하는 데 사용할 수 있는 많은 도구를 가지고 있습니다. 이러한 도구의 대부분을 통해 엔터프라이즈 IT 리소스에 대한 액세스 및 제어를 얻을 수 있습니다. 그 동안 보안 전문가는 방어해야 하는 IT 리소스에 기본 제공되는 취약성을 항상 인식하지는 않습니다. ASC(Azure Security Center)는 이러한 격차를 해소하는 데 도움이 될 수 있습니다.</p>


  <p>이 블로그 게시물은 ASC(Azure Security Center)를 사용하여 SQL 삽입 공격으로부터 Azure 기반 리소스를 검색하고 보호하는 데 관심이 있는 IT 및 보안 전문가를 위한 것입니다. 이 게시물의 목표는 1) 잘 알려진 코드 삽입이 발생하는 방식을 설명하고 2) ASC가 IT 리소스를 보호하기 위해 이 공격을 감지하고 해결하는 방법을 설명하는 것입니다.&nbsp;</p>


  <h2>도구는 SQL 주입을 쉽게</h2>


  <p>서버 및 애플리케이션은 사이버 범죄자를 위한 쉬운 대상입니다. 데이터 기반 애플리케이션을 공격하는 잘 알려진 방법 중 하나는 SQL 주입을 통해서입니다. SQL 삽입은 의도되지 않은 데이터베이스 액세스로 이어지는 실행을 위해 악성 코드가 삽입되는 공격 기술입니다. 공격자가 악의적인 삽입에 사용할 수 있는 인기 있는 도구는 sqlmap입니다. sqlmap을 사용하면 취약한 SQL 데이터베이스를 쉽게 검색하고 콘텐츠를 노출할 수 있습니다. 공격자는 데이터베이스, 테이블을 인증 및 검색하고 사용자 및 해시된 암호를 덤프하기 위한 적절한 요청 헤더만 제공해야 합니다. 공격자가 이 데이터를 가지고 나면 다음 단계는 노출된 해시에 대해 무차별 암호 대입 분석을 사용하는 것이며, sqlmap 도구의 또 다른 기본 제공 기능을 사용하여 아래와 같이 일반 텍스트 사용자 자격 증명을 가져옵니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/404df6cd-b642-4b43-a5dd-5f9e2e2dba96.png"><img alt="Plaintext user credentials" border="0" height="255" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/9319e029-d814-4544-be4a-2497f750712d.png" style="border-top: 0px; border-right: 0px; background-image: none; border-bottom: 0px; float: none; padding-top: 0px; padding-left: 0px; margin-left: auto; border-left: 0px; display: block; padding-right: 0px; margin-right: auto" title="일반 텍스트 사용자 자격 증명" width="612"></a></p>


  <h2>Azure Security Center를 사용하여 위험 식별</h2>


  <p>무료 및 평가판 구독을 포함하여 Azure의 모든 구독 계층에서 사용할 수 있는 ASC(Azure Security Center)는 HTTP 엔드포인트를 사용하여 연결된 IT 자산을 식별하는 데 도움이 될 수 있습니다. 또한 ASC는 WAF(웹 애플리케이션 방화벽) 리소스의 배포를 자동화하여 비준수 리소스를 보호하는 동시에 검색된 악의적인 SQL 삽입 시도를 지적할 수 있습니다. 검색 목록은 보안 수정이 필요한 보호되지 않는 웹 서버를 가리킵니다. ASC는 Azure 구독에서 가상 머신을 검사하고 위험에 처한 리소스에 해당하는 웹 애플리케이션 방화벽을 추가하도록 권장합니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/85177103-f5ef-4cb7-b381-75273348db3d.png"><img alt="Power BI 1" border="0" height="282" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/c5515170-fd9c-4200-a8b2-dbce90db76cb.png" style="border-top: 0px; border-right: 0px; background-image: none; border-bottom: 0px; padding-top: 0px; padding-left: 0px; border-left: 0px; display: inline; padding-right: 0px" title="Power BI 1" width="318"></a><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/85daa2ec-883e-419e-a80d-663b065e9505.png"><img alt="Power BI 2" border="0" height="281" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/e6ac7457-691a-4520-bc53-56236b2c5c3c.png" style="border-top: 0px; border-right: 0px; background-image: none; border-bottom: 0px; padding-top: 0px; padding-left: 0px; border-left: 0px; display: inline; padding-right: 0px" title="Power BI 2" width="427"></a></p>


  <p>그런 다음 ASC는 파트너 또는 자사 솔루션에 대한 웹 애플리케이션 방화벽을 배포하고 구성하는 프로세스를 통해 지침을 제공합니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/f7cd5d53-b4f8-4740-a638-5f50472196a4.png"><img alt="Create a new Web Application Firewall solution" border="0" height="350" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/fa4c385c-d1de-413e-9356-3b7c1f47bfc5.png" style="border-top: 0px; border-right: 0px; background-image: none; border-bottom: 0px; float: none; padding-top: 0px; padding-left: 0px; margin-left: auto; border-left: 0px; display: block; padding-right: 0px; margin-right: auto" title="새 웹 애플리케이션 방화벽 솔루션 만들기" width="494"></a></p>


  <p>웹 애플리케이션 방화벽을 통한 IP 트래픽 터널링에 대한 추가 지침도 제공됩니다. 이 프로세스는 취약한 웹 애플리케이션에 추가된 보호 계층을 제공합니다.</p>


  <p>Azure Security Center는 웹 애플리케이션 방화벽을 포함한 보호 및 검색에서 리소스에 추가되었으므로&rsquo; 가시성을 제공합니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/3734844c-628d-4dbe-a054-62af2362866d.png"><img alt="Security alerts" border="0" height="356" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/359942e2-55c0-45ab-a81b-d1f4b4c6ba05.png" style="border-top: 0px; border-right: 0px; background-image: none; border-bottom: 0px; float: none; padding-top: 0px; padding-left: 0px; margin-left: auto; border-left: 0px; display: block; padding-right: 0px; margin-right: auto" title="보안 경고" width="494"></a></p>


  <h2>방지를 사용하여 작업 수정</h2>


  <p><a href="https://docs.microsoft.com/en-us/azure/application-gateway/application-gateway-customize-waf-rules-portal" target="_blank">WAF를 방지 모드로 구성</a> 하면 sqlmap 도구가 액세스 권한이 있어야&rsquo; 하는 데이터베이스 및 테이블에 액세스하지 못하게 됩니다. 따라서 sqlmap은 콘텐츠에 대한 데이터베이스를 트래버스하는 것은 물론 백 엔드에서 실행되는 데이터베이스 형식을 열거하는 것을 방지할 수 있습니다. 방지 모드에서 WAF는 의심스러운 활동을 방지합니다. ASC는 이를 감지하고 차단된 활동을 보고합니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/5e1f5b2f-0ad5-4d40-a1b0-f4c112ce1c50.png"><img alt="Prevention mode" border="0" height="554" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/902cadf5-8e24-48b7-a9a1-f8ea3e57b477.png" style="border-top: 0px; border-right: 0px; background-image: none; border-bottom: 0px; float: none; padding-top: 0px; padding-left: 0px; margin-left: auto; border-left: 0px; display: block; padding-right: 0px; margin-right: auto" title="방지 모드" width="476"></a></p>


  <h2>결론</h2>


  <p>sqlmap과 같은 공격 도구는 저렴하고 쉽게 사용할 수 있습니다. &ldquo;심층&rdquo; 방어 접근 방식은 애플리케이션이 SQL 주입에 취약하지 않도록 하는 데 중요합니다. 이러한 공격으로부터 리소스를 검색하고 보호하기 위한 가시성과 제어가 매우 중요합니다. ASC를 사용하면 IT 및 보안 전문가가 클라우드 기반 리소스에서 위험에 처한 엔드포인트를 검색할 수 있습니다. ASC의 권장 사항에 따라 탐지 및 보호를 구현하여 조직에서 정보 보안 규정 준수 표준을 충족할 수 있도록 지원합니다. ASC는 Azure의 모든 구독 계층에서 사용할 수 있지만 표준 계층의 ASC는 더 심층적인 수준의 인사이트, 작업 및 위협 방지에 액세스할 수 있습니다. 엔터프라이즈에 심층적이고 세분화된 수준의 클라우드 보안이 필요한 경우 <a href="https://azure.microsoft.com/en-us/free/" target="_blank">Azure Standard 무료 평가판을 활성화</a> 하여 ASC가 비즈니스에 어떻게 도움이 되는지 확인합니다.</p>


  <p>이 블로그 게시물은 심층적인 단계별 플레이북을 칭찬합니다. 자세한 내용은 <em><a href="https://gallery.technet.microsoft.com/ASC-Playbook-Protect-38bd47ff" target="_blank">ASC 플레이북: 웹앱 방화벽을 사용하여 서버 보호</a></em>에 대해 읽어보세요.</p>


  <p>질문이 있으세요? 에서 이메일을 보내 <a href="mailto:AskCESec@microsoft.com" target="_blank">AskCESec@microsoft.com</a>주세요.</p>


  <p>- 헤이든 @hhainsworth</p>
