### YamlMime:Yaml
ms.openlocfilehash: 530cb689e574495081485556e77c7802cd7e0206
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139898961"
Slug: hybrid-management-in-azure-automation
Title: Azure Automation의 하이브리드 관리
Summary: '이 게시물에서는 새로운 Hybrid Runbook Worker 기능의 기본 사항 및 몇 가지 주요 기능을 안내합니다. '
Content: >-
  <a href="https://azure.microsoft.com/en-us/services/automation/">Azure Automation</a>의 최신 릴리스에서는 Hybrid Runbook Worker를 사용하여 온-프레미스 시스템에 연결하는 기능을 도입했습니다. 이제 새로운 Hybrid Runbook Worker 기능을 사용하여 아웃바운드 포트를 열 필요 없이 클라우드 및 데이터 센터에 걸쳐 있는 리소스를 관리할 수 있습니다.


  이 게시물에서는 새로운 Hybrid Runbook Worker 기능의 기본 사항 및 몇 가지 주요 기능을 안내합니다. Azure Automation 소개부터 시작하겠습니다.

  <h2>Azure Automation 정의</h2>

  아직 익숙하지 않은 경우 Azure Automation은 어디서나(퍼블릭, 호스팅 또는 프라이빗 클라우드) 리소스를 관리하기 위한 IT 프로세스 자동화 서비스입니다. Azure 환경의 리소스 만들기, 모니터링, 배포 및 유지 관리를 자동화하는 데 사용할 수 있습니다. Dev/Ops는 Automation을 사용하여 Runbook을 구성, 실행 및 관리하여 IT 프로세스를 통합, 오케스트레이션 및 자동화할 수 있습니다. Windows PowerShell 워크플로 엔진에서 실행되는 Automation Runbook


  자세한 내용은 을 참조하세요 <a href="https://azure.microsoft.com/en-us/services/automation/">https://azure.microsoft.com/en-us/services/automation/</a>.


  이제 <b>Hybrid Runbook Worker</b> 기능에 대해 이야기하고 몇 가지 기본적인 질문으로 시작하겠습니다. 하이브리드 작업자는 정확히 무엇이며, 왜 필요한지, 어떻게 사용해야 하나요?

  <h2>Hybrid Runbook Worker란?</h2>

  Azure Automation의 Hybrid Runbook Worker 기능을<s> </s>사용하면 로컬 리소스를 관리하기 위해 데이터 센터에 있는 컴퓨터에서 Runbook을 실행할 수 있습니다. Runbook은 Azure Automation에 저장 및 관리된 다음, 실행되는 하나 이상의 온-프레미스 머신에 배달됩니다.

  <h2>하이브리드 자동화 개요</h2>

  <a href="https://acom.azurecomcdn.net/80C57D/blogmedia/blogmedia/2015/07/23/Hybrid-Automation-Overview.png"><img style="background-image: none; padding-top: 0px; padding-left: 0px; display: inline; padding-right: 0px; border-width: 0px;" title="하이브리드 자동화 개요" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/Hybrid-Automation-Overview_thumb.png" alt="Hybrid Automation Overview" width="1318" height="732" border="0" /></a>


  하이브리드 기능을 사용할 수 있게 될 때까지 Azure Automation은 주로 클라우드에서 이러한 Runbook이 실행되므로 클라우드에서 리소스를 관리하는 데 사용되었습니다. 이제 Hybrid Runbook Worker를 사용하여 로컬 데이터 센터에 있는 Hybrid Runbook Worker에서 Runbook을 실행하여 온-프레미스 리소스를 관리할 수 있습니다.


  Runbook 및 참조된 자산은 모두 Azure 자동화에 저장되며 실행 시간 동안 실행되는 하나 이상의 온-프레미스 머신(Hybrid Runbook Worker로 지정됨)에 배달됩니다. Runbook은 문제 해결을 위해 Azure Automation에 자세한 작업 정보를 전송하므로 관리 중인 리소스에 관계없이 모든 작업 출력을 단일 위치로 모니터링할 수 있습니다. Hybrid Runbook Worker로 지정된 컴퓨터에서 자산 및 모듈을 사용하는 방법에 대한 자세한 내용은 <a href="file:///C:/Users/v-katisc/Desktop/#creating-runbooks-for-hybrid-runbook-wor">아래</a> 를 참조하세요. 방화벽 규칙을 열 필요가 없습니다. 지정된 Hybrid Runbook Worker가 인터넷에 액세스할 수 있는지 확인합니다.

  <h2>Hybrid Runbook Worker를 사용하는 이유는 무엇인가요?</h2>

  <ul>
   <li>하이브리드 작업자는 Azure, AWS 등의 퍼블릭 클라우드 또는 기타 서비스 공급자 또는 Microsoft 또는 기타 비 Microsoft 스택(예: VMWare 또는 OpenStack)과 같은 온-프레미스 솔루션에 있든 상관없이 리소스를 관리하기 위한 단일 솔루션으로 Azure Automation을 사용할 수 있습니다.</li>
   <li>하이브리드 작업자와 함께 Azure Automation을 사용하면 Service Management Automation, Orchestrator 등의 온-프레미스 자동화 제품을 배포, 유지 관리 및 업그레이드할 필요가 없습니다.</li>
  </ul>

  <h2>Hybrid Runbook Worker를 사용하려면 어떻게 하나요?</h2>

  <h3>1단계: 온-프레미스 컴퓨터 식별</h3>

  온-프레미스 컴퓨터를 선택할 때 고려해야 할 몇 가지 권장 사항은 다음과 같습니다.

  <ol>
   <li>Hybrid Runbook Worker는 Windows Server 2012 이상에서 실행됩니다.</li>
   <li>SMA(서비스 관리 자동화) Runbook Worker 또는 SCO(System Center Orchestrator) Runbook Server 컴퓨터와 마찬가지로 사용자 환경에서 고가용성 컴퓨터를 선택하여 Hybrid Runbook Worker로 지정하는 것이 좋습니다. 하이브리드 작업자는 SMA 또는 SCO 환경과 공존할 수 있습니다.</li>
   <li>Runbook이 완료되면 전체 작업 데이터가 Azure Automation으로 다시 전송되므로 <a href="https://azure.microsoft.com/en-us/regions/#services">Azure Automation 지역에</a> 가까운 위치에서 컴퓨터를 사용하는 것이 좋습니다.</li>
  </ol>

  <h3>2단계: Hybrid Runbook Worker 설치 및 구성</h3>

  OMS( <a href="https://www.microsoft.com/en-us/server-cloud/operations-management-suite/overview.aspx">Operations Management Suite</a> ) MMA(Microsoft Management Agent) 채널 및 인텔리전스 팩/솔루션 채널을 사용하여 Hybrid Runbook Worker로 지정한 온-프레미스 머신에 Hybrid Runbook Worker 비트를 제공합니다.


  Hybrid Runbook Worker 설치 및 구성에 대한 자세한 내용은 에서 찾을 수 있습니다. <a href="https://azure.microsoft.com/en-us/documentation/articles/automation-hybrid-runbook-worker/">https://azure.microsoft.com/en-us/documentation/articles/automation-hybrid-runbook-worker/</a>

  <h3>3단계: Hybrid Runbook Worker에서 Runbook 시작</h3>

  <a href="https://azure.microsoft.com/en-us/documentation/articles/automation-starting-a-runbook">Azure Automation에서 Runbook 시작</a> 에 Runbook을 시작하는 여러 가지 방법이 설명되어 있습니다. Hybrid Runbook Worker는 Hybrid Runbook Worker 그룹의 이름을 지정할 수 있는 <strong>실행</strong> 옵션을 추가합니다. 그룹을 지정하면 해당 그룹의 작업자 중 하나가 Runbook을 검색하고 실행합니다. 이 옵션을 지정하지 않으면 Runbook이 Azure 클라우드에서 정상적으로 실행됩니다.


  Azure 미리 보기 포털에서 Runbook을 시작하면 <strong>Azure</strong> 또는 <strong>Hybrid Worker</strong>를 선택할 수 있는 <strong>실행</strong> 옵션이 표시됩니다. <strong>Hybrid Worker</strong>를 선택하는 경우 드롭다운에서 Hybrid Runbook Worker 그룹을 선택할 수 있습니다.


  <a href="https://acom.azurecomcdn.net/80C57D/blogmedia/blogmedia/2015/07/23/Runbook-Migration-Demo1.png"><img style="background-image: none; padding-top: 0px; padding-left: 0px; display: inline; padding-right: 0px; border-width: 0px;" title="Runbook 마이그레이션 데모1" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/Runbook-Migration-Demo1_thumb.png" alt="Runbook Migration Demo1" width="1097" height="420" border="0" /></a>

  <h2>Hybrid Runbook Worker 그룹</h2>

  각 Hybrid Runbook Worker는 에이전트를 설치할 때 지정하는 Hybrid Runbook Worker 그룹의 구성원입니다. 그룹에는 단일 작업자가 포함될 수 있지만 고가용성을 위해 그룹에 여러 작업자를 설치할 수 있습니다.


  Hybrid Runbook Worker에서 Runbook을 시작하면 Runbook이 실행될 그룹을 지정하고 그룹의 작업자가 작업을 실행할 수 있습니다. 현재 특정 작업자를 지정할 수 없습니다.

  <h2>Hybrid Runbook Worker용 Runbook 만들기</h2>

  Azure Automation에서 실행되는 Runbook과 Hybrid Runbook Worker에서 실행되는 Runbook에는 차이가 없습니다. 그러나 Hybrid Runbook Worker와 함께 사용되는 Runbook은 일반적으로 데이터 센터에서 로컬 리소스를 관리하는 반면 Azure Automation의 Runbook은 일반적으로 Azure 또는 다른 클라우드의 리소스를 관리하므로 하이브리드용으로 작성된 Runbook은 다른 Runbook과 다를 수 있습니다. 예를 들어 Hybrid Runbook Worker를 사용하여 Hyper-V에서 VM을 관리하거나 System Center Orchestrator에서 마이그레이션된 Runbook을 실행할 수 있습니다. 또 다른 용도는 Azure Automation에 설치할 수 없는 모듈에 대한 것입니다. 하이브리드 작업자에 이러한 모듈을 설치하고 Runbook에서 사용할 수 있습니다. VMware PowerCLI cmdlet을 사용하여 VMware를 관리할 수 있는 좋은 예입니다.


  Orchestrator Runbook을 Azure Automation으로 마이그레이션하는 방법에 대한 자세한 내용은 다음을 참조하세요 <a href="https://www.microsoft.com/en-us/download/details.aspx?id=47323">https://www.microsoft.com/en-us/download/details.aspx?id=47323</a>.

  <h2>디버깅 및 문제 해결:</h2>

  Hybrid Worker에서 Runbook 작업이 완료되면 자세한 상태를 Azure Automation으로 다시 보내서 Azure에서 실행되는 작업 문제를 해결하는 것과 같은 방식으로 작업을 보고 문제를 해결할 수 있습니다.


  <a href="https://acom.azurecomcdn.net/80C57D/blogmedia/blogmedia/2015/07/23/RBMigration.png"><img style="background-image: none; padding-top: 0px; padding-left: 0px; display: inline; padding-right: 0px; border-width: 0px;" title="RBMigration" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/RBMigration_thumb.png" alt="RBMigration" width="1471" height="757" border="0" /></a>

  <h2>Azure Automation에서 자산 사용</h2>

  변수, 자격 증명, 연결 및 인증서와 같은 Automation 자산은 Hybrid Worker에서 실행되는 Runbook에서 사용할 수 있습니다. 자산은 Azure Automation에 저장되며 이를 참조하는 Runbook에서 사용하기 위해 작업자에게 자동으로 전달됩니다.


  현재 Hybrid Worker에서 Runbook을 예약할 수 없습니다. 대안은 Azure 클라우드에서 실행되고 Start-AzureAutomationRunbook cmdlet을 사용하여 작업자에서 Runbook을 시작하는 다른 Runbook을 예약하는 것입니다.

  <h2>PowerShell 모듈</h2>

  Hybrid Runbook Worker 기능의 주요 목적은 로컬 리소스를 관리하는 것이기 때문에 이러한 리소스를 지원하는 모듈을 설치해야 합니다. 이러한 모듈은 Hybrid Worker에 자동으로 배포되지 않으므로 현재 각 작업자에 수동으로 설치해야 합니다. 그러나 가까운 장래에 해당 모듈을 작업자에게 자동으로 배포하기 위해 노력하고 있습니다.

  <h2>Runbook 사용 권한</h2>

  Runbook은 Hybrid Runbook Worker의 로컬 시스템 계정 컨텍스트에서 실행되므로 액세스할 리소스에 대한 자체 인증을 제공해야 합니다. Azure 외부의 <a href="https://azure.microsoft.com/en-us/documentation/articles/automation-hybrid-runbook-worker/automation-configuring.md/#configuring-authentication-to-azure-resources">리소스에 액세스하므로 일반적으로 Azure 리소스에 인증하는 Runbook에 사용되는</a> 것과 동일한 메서드를 사용할 수 없습니다.


  <a href="https://acom.azurecomcdn.net/80C57D/blogmedia/blogmedia/2015/07/23/Services.png"><img style="background-image: none; padding-top: 0px; padding-left: 0px; display: inline; padding-right: 0px; border-width: 0px;" title="서비스" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/Services_thumb.png" alt="Services" width="1118" height="490" border="0" /></a>


  다른 리소스에 인증할 수 있도록 자격 증명을 지정할 수 있는 cmdlet을 사용하여 Runbook에서 <a href="https://msdn.microsoft.com/library/dn940015.aspx">자격</a> 증명 및 <a href="https://msdn.microsoft.com/library/dn940013.aspx">인증서</a> 자산을 사용할 수 있습니다. 다음 예제에서는 컴퓨터를 다시 시작하는 Runbook의 일부를 보여 줍니다. 이 예제에서는 자격 증명 자산에서 자격 증명을 검색하고 변수 자산에서 컴퓨터 이름을 검색한 다음 Restart-Computer cmdlet에서 이러한 값을 사용합니다.

  <pre class="prettyprint">$Cred = Get-AutomationCredential "MyCredential"

  $Computer = Get-AutomationVariable "ComputerName"


  Restart-Computer -ComputerName $Computer -Credential $Cred

  </pre>

  <a href="https://technet.microsoft.com/library/jj129719.aspx">PSCredential 일반 매개 변수</a>로 지정된 자격 증명을 사용하여 다른 컴퓨터에서 코드 블록을 실행할 수 있는 <a href="https://azure.microsoft.com/en-us/documentation/articles/automation-hybrid-runbook-worker/automation-runbook-concepts.md/#inline-script">InlineScript</a> 작업을 사용할 수도 있습니다.

  <h2>요약</h2>

  Hybrid Runbook Worker를 사용하는 Azure Automation의 하이브리드 연결은 Azure Automation을 어디서나 워크로드를 관리하기 위한 플랫폼(데이터 센터, 프라이빗, 퍼블릭 및 호스트된 클라우드)을 만드는 강력한 기능입니다.


  최근에 릴리스된 다른 새로운 기능을 확인하세요.

  <ul>
   <li>그래픽 작성: <a href="https://azure.microsoft.com/blog/2015/05/07/azure-automation-new-graphical-and-textual-authoring-features/">https://azure.microsoft.com/blog/2015/05/07/azure-automation-new-graphical-and-textual-authoring-features/</a></li>
   <li>웹 후크: <a href="https://azure.microsoft.com/en-us/documentation/articles/automation-webhooks/">https://azure.microsoft.com/en-us/documentation/articles/automation-webhooks/</a></li>
   <li>Azure Automation DSC: <a href="https://azure.microsoft.com/en-us/documentation/articles/automation-dsc-overview/">https://azure.microsoft.com/en-us/documentation/articles/automation-dsc-overview/</a></li>
  </ul>

  이후 게시물에서는 Hybrid Runbook Worker에 추가하는 새로운 기능과 예제 시나리오에 대해 설명합니다. 그때까지, 행복한 자동화!


  Azure Automation을 시작하기만 하면 되었나요? <a href="https://aka.ms/Q2p1ap">여기에서</a> 서비스에 대해 알아보고 Twitter에서 <a href="https://twitter.com/AzureAutomation">Azure Automation</a>을 따르세요.
