### YamlMime:Yaml
ms.openlocfilehash: e382fadbf30ca78b9f85255edc6dd7aeea8288d7
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139899810"
Slug: hybrid-application-innovation-with-azure-and-azure-stack
Title: Azure Stack TP3는 하이브리드 애플리케이션 혁신을 제공하고 종량제 가격 책정 모델을 소개합니다.
Summary: 속도와 실험 정신으로 혁신적인 애플리케이션을 구축하는 것이 클라우드 혁명의 핵심입니다. 우리는 전 세계 기업들이 디지털 트랜스포메이션을 수용하는 데 어려움을 겪고 있으며, 앱이 고객을 기쁘게 하고 새로운 비즈니스 라인을 주도하는 엔진이 될 수 있는 방법을 재고하고 있습니다. Azure 확장인 Azure Stack에서 진행한 성과를 공유하여 온-프레미스 환경에 클라우드 컴퓨팅의 민첩하고 빠르게 변화하는 혁신을 실현하게 되어 기쁩니다.
Content: >-
  <p>조직이 성장을 가속화하고 차별화된 고객 환경을 만들기 위해서는 클라우드 기술에 혁신적인 애플리케이션을 구축하는 것이 중요합니다. 종량제 가격 책정을 통해 클라우드 기술을 활용하는 애플리케이션이 이제 표준이 되었습니다. 우리의 목표는 하이브리드 클라우드 환경을 선택하는 조직이 비즈니스 목표 및 애플리케이션 디자인과 일치하도록 동일한 유연성과 혁신 기능을 갖도록 하는 것입니다. 이 때문에 Azure Stack을 사용하여 온-프레미스에서 Azure 기술을 확장하고 있으며, 현재 Azure Stack에 대한 몇 가지 업데이트를 발표하고 있습니다.</p>


  <ul>
      <li><strong>다운로드할 수 있는 TP3:</strong> <a href="https://azure.microsoft.com/en-us/overview/azure-stack/">기술 미리 보기 3(TP3)은 현재 다운로드할 수</a> 있으며 최신 애플리케이션 기능을 사용하도록 설정하는 새로운 기능이 있습니다. Azure에 연결하지 않고 위치에서 실행 중 인프라 및 보안 향상과 함께</li>
      <li><strong>패키징 및 가격 책정 모델: </strong> Azure Stack은 종량제 가격 책정을 통해 클라우드 경제 모델을 온-프레미스에 제공합니다.</li>
      <li><strong>로드맵 업데이트: </strong> TP3 직후 <a href="https://azure.microsoft.com/en-us/services/functions/??WT.srch=1&amp;WT.mc_id=AID559320__SEM_T2EIoLH6&amp;">Azure Functions</a> 를 TP3에서 실행할 수 있고 블록 <a href="https://github.com/Azure/azure-quickstart-templates/tree/master/ethereum-consortium-blockchain-network">체인</a>, <a href="https://github.com/Azure/azure-quickstart-templates/tree/master/bosh-setup">Cloud Foundry</a> 및 <a href="https://github.com/Azure/AzureStack-QuickStart-Templates/blob/master/mesos-windows-jumpbox/README.md">Mesos</a> 템플릿이 뒤따릅니다. 지속적인 혁신은 일반 공급 이상까지 Azure Stack에 제공됩니다. TP3은 Azure Stack 통합 시스템을 CY17 중반에 주문할 수 있기 전에 마지막으로 계획된 주요 기술 미리 보기입니다.</li>
  </ul>


  <h2>Azure 온-프레미스 확장</h2>


  <p>Azure Stack을 사용하면 클라우드 및 온-프레미스 환경에서 새 앱을 빌드하고/또는 기존 앱을 개조하려는 조직을 위한 세 가지 고유한 하이브리드 클라우드 시나리오를 사용할 수 있습니다.</p>


  <ul>
      <li><strong>일관된 하이브리드 애플리케이션 개발:</strong> 사람, 프로세스 및 애플리케이션에 투자하는 조직은 Azure와 Azure Stack 간에 양도할 수 있다는 것을 알면 그렇게 할 수 있습니다. 기술을 개발하려는 개인은 Azure를 사용하여 모든 조직에 이러한 기술을 사용할 수 있습니다. Azure와 Azure Stack 간의 일관성은 조직이 첫날 생산성을 높일 수 있는 전 세계 인재 풀에서 한 프로젝트에서 다른 프로젝트로 쉽게 이동할 수 있음을 의미합니다.&nbsp; Azure 기술을 가진 개인은 프로젝트, 팀, DevOps 프로세스 또는 조직을 쉽게 이동할 수 있습니다. API, 포털, PowerShell cmdlet 및 Visual Studio 환경<a href="https://aka.ms/consistentappdev">은 모두 동일합니다</a>.</li>
      <li><strong>온-프레미스에서 사용할 수 있는 Azure 서비스:</strong> 인프라 및 플랫폼 서비스는 차세대 애플리케이션 혁신을 촉진합니다. <a href="https://aka.ms/servicesonprem">온-프레미스에서 Azure IaaS 및 PaaS 서비스를</a> 제공하면 조직은 비즈니스 및 기술 요구 사항에 따라 하이브리드 클라우드 컴퓨팅을 채택할 수 있습니다. 공용, 서비스 공급자 및 온-프레미스 배포 모델의 적절한 조합을 유연하게 선택할 수 있습니다. 앱을 다른 위치에 배포하기로 결정한 경우 수정 없이 쉽게 이동할 수 있습니다.</li>
      <li><strong>운영 우수성을 위해 특별히 빌드된 시스템:</strong> 조직이 비즈니스를 구동하는 작업에 집중할 수 있도록 Azure Stack은 예측 가능하고 중단 없는 방식으로 <a href="https://aka.ms/purposebuiltsystems">Azure 혁신을 지속적으로 통합</a> 하도록 설계된 통합 시스템을 통해 제공됩니다.</li>
  </ul>


  <h2>Azure 및 Azure Stack에 대한 하이브리드 사용 사례</h2>


  <p>고객에게 클라우드 전략에 대해 이야기할 때 하이브리드는 안정적인 상태 운영 모델이 될 것이며 몇 가지 주요 시나리오에서 Azure Stack을 사용하여 클라우드 전략을 보강하려고 합니다.</p>


  <ol>
      <li><strong>에지 및 연결이 끊긴 솔루션:</strong> Azure Stack에서 로컬로 데이터를 처리한 다음 Azure에서 집계하여 대기 시간 및 연결 요구 사항을 해결합니다. 이 두 가지 모두에서 공통 애플리케이션 논리를 사용하여 추가 분석을 위해 Azure에서 집계합니다.&nbsp;</li>
      <li><strong>클라우드 및 온-프레미스의 최신 애플리케이션:</strong> Azure 웹 &amp; 모바일 서비스, 컨테이너, 서버리스 및 마이크로 서비스 아키텍처를 적용하여 온-프레미스 및 클라우드에서 일관된 DevOps 프로세스를 사용하는 동시에 Azure Stack을 사용하여 레거시 애플리케이션을 업데이트하고 확장합니다.</li>
      <li><strong>모든 규정을 충족하는 클라우드 애플리케이션:</strong> 코드 변경 없이 규정 또는 정책 요구 사항을 충족하기 위해 Azure Stack을 사용하여 온-프레미스를 배포할 수 있는 모든 유연성을 갖춘 Azure에서 애플리케이션을 개발하고 배포합니다.</li>
  </ol>


  <p>공장 현장 자동화, 크루즈 선박 및 광산과 같은 원격 사용 요구 사항 또는 정부 시스템과 같은 격리 요구 사항이 있는 고객은 모두 최신 디자인을 채택하고 클라우드에서 개발하고 해당 위치에 배포할 수 있습니다.&nbsp;</p>


  <h2>Azure Stack TP3의 새로운 기능&rsquo;</h2>


  <p>Azure Stack TP3을 통해 Weve&rsquo;는 TP2의 다양한 버그 수정, 업데이트 및 배포 안정성 &amp; 호환성 향상을 통해 제품을 개선하기 위해 고객과 협력했습니다. Azure Stack TP3을 사용하면 고객은 다음을 수행할 수 있습니다.</p>


  <ul>
      <li>연결이 끊긴 시나리오를 위해 ADFS를 사용하여 배포</li>
      <li>스케일 아웃 워크로드에 Azure Virtual Machine Scale Sets 사용 시작</li>
      <li>Azure Stack에서 사용할 수 있도록 Azure Marketplace의 신디케이트 콘텐츠</li>
      <li>Azure D 시리즈 VM 크기 사용</li>
      <li>Azure와 일치하는 Temp Disks를 사용하여 템플릿 배포 및 만들기</li>
      <li>격리된 관리자 포털의 향상된 보안에 편안함을 더하세요.</li>
      <li>IaaS 및 PaaS 기능 개선 사항 활용</li>
      <li>향상된 경고와 같은 향상된 인프라 관리 기능 사용</li>
  </ul>


  <h2>로드맵 업데이트</h2>


  <p>지속적인 혁신 모델의 일환으로 TP3 직후 Azure Functions, VM 확장 배포 및 다중 테넌트를 추가할 예정입니다. 블록체인, Cloud Foundry 및 Mesos 템플릿과 같은 새로운 워크로드가 뒤따릅니다.&nbsp; CY17 중반에 GA가 될 때까지 TP3을 계속 새로 고칠 것입니다.</p>


  <p>CY17 중반에 POC(개념 증명) 배포의 이름이 Microsoft Azure Stack Development Kit로 바뀝니다. 이 단일 서버 개발/테스트 도구를 사용하면 고객이 하이브리드 애플리케이션의 프로토타입을 만들고 유효성을 검사할 수 있습니다. Azure Stack이 Azure의 새로운 기능을 고객에게 신속하게 제공하는 데 사용하는 지속적인 혁신 모델의 핵심 요소입니다. 새 업데이트를 고객에게 조기에 배포하여 실험, 학습 및 피드백을 제공할 수 있는 방법을 제공합니다.&nbsp;&nbsp;</p>


  <p>TP3는 GA 이전의 최종 계획된 주요 기술 미리 보기입니다.&nbsp; Azure Stack 개발 키트는 먼저 GA로 릴리스되며 동시에 하드웨어 파트너에게 소프트웨어를 릴리스하여 다중 서버 Azure Stack 통합 시스템인 CY17 중반을 제공하는 데 필요한 공동 엔지니어링 작업의 마지막 마일을 완료할 수 있도록 합니다.</p>


  <p>GA 후에는 잦은 업데이트를 통해 추가 기능을 지속적으로 제공할 예정입니다. GA 이후의 첫 번째 업데이트는 1) 향상된 애플리케이션 현대화 시나리오 및 2) 향상된 시스템 관리 및 규모라는 두 가지 영역에 초점을 맞췄습니다. 이러한 업데이트는 애플리케이션을 개발할 때 고객이 선택한 IaaS 및 PaaS 기술을 계속 확장하고, 증가하는 애플리케이션 포트폴리오에 맞게 관리 효율성을 개선하고 Azure Stack의 공간을 확장합니다.</p>


  <h2>종량제 가격으로 클라우드 경제성을 온-프레미스로 확장</h2>


  <p>Azure Stack은 종량제 가격 책정을 <a href="https://aka.ms/maspayasyougo">통해 클라우드 경제 모델을 온-프레미스</a>에 제공합니다. Azure와 마찬가지로 Azure Stack에서 Azure 서비스를 사용하기 위한 선불 라이선스 요금은 없으며 고객은 서비스를 사용할 때만 요금을 지불합니다. 서비스는 동일한 송장 및 구독을 사용하여 Azure에서와 동일한 방식으로 거래됩니다. 서비스는 일반적으로 Azure와 동일한 단위로 계량되지만 고객이 자체 하드웨어 및 시설을 운영하므로 가격이 낮아질 것입니다. 고객이 계량 정보를 Azure로 전송할 수 없는 시나리오의 경우 시스템의 코어 수에 따라 고정 가격 &ldquo;용량 모델&rdquo; 도 제공합니다.</p>


  <p>고객은 하드웨어 파트너인 Dell EMC, HPE, Lenovo 및 (올해 말) Cisco에서 Azure Stack 하드웨어를 획득합니다. 우리는 하드웨어 파트너와 협력하여 통합 시스템을 뒷받침하는 하드웨어에 종량제를 포함한 유연한 구매 옵션을 제공하게 되어 기쁩니다.</p>


  <p>고객은 자세한 가격 책정 정보를 Microsoft 및 하드웨어 파트너 계정 담당자에게 문의할 수 있습니다.</p>


  <h2>최종 생각 및 다음 단계</h2>


  <p>전 세계 모든 산업의 모든 회사가 단순히 디지털 기술을 사용하는 조직에서 디지털 조직으로 전환합니다. Microsoft는 고객을 위해 지속적으로 진화하는 제품을 만들어 조직의 성장을 돕기 위해 최선을 다하고 있습니다.</p>


  <p>Azure 및 Azure Stack 통합 시스템을 통해 기업은 애플리케이션 포트폴리오를 비즈니스의 전략적 차별화 요소로 전환하는 데 에너지와 인재를 투자하는 데 집중할 수 있습니다. 이 접근 방식을 사용하면 고객이 비즈니스 요구 사항을 가장 잘 충족하는 애플리케이션을 배포하고 운영할 수 있습니다. IT 팀은 셀프 서비스 프로비저닝 및 클라우드 서비스를 통해 개발 팀에 권한을 부여하는 동시에 비즈니스 정책 및 요구 사항을 충족하는 DevOps 워크플로를 구축함으로써 훨씬 더 큰 가치를 제공할 수 있습니다.</p>


  <p><a href="https://azure.microsoft.com/en-us/overview/azure-stack/">Azure Stack에 대해 자세히 알아보고 Azure Stack TP3를 다운로드합니다.</a></p>


  <p>Jeffrey Snover<br>

  Azure 인프라 및 관리 기술 펠로우<br>

  트위터에서 나를 따르라 <a href="https://twitter.com/jsnover">@jsnover</a></p>
