### YamlMime:Yaml
ms.openlocfilehash: abe21f42251147b599279a92158d17dfb50f5c4b
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139901191"
Slug: imanis-data-cloud-migration-backup-for-your-big-data-applications-on-azure-hdinsight
Title: Imanis Data - Azure HDInsight의 빅 데이터 애플리케이션에 대한 클라우드 마이그레이션, 백업
Summary: 이 결합된 Azure HDInsight의 Imanis Data 제품과 Azure Blob Storage 및 Data Lake Store와의 긴밀한 통합을 통해 고객은 클라우드로 더 빠르게 마이그레이션하고 애플리케이션 또는 사용자 오류로부터 중요한 데이터 자산을 보호할 수 있습니다.
Content: >-
  <p>Azure에서 Imanis Data의 가용성을 발표하게 되어 기쁘게 생각합니다.</p>


  <p><a href="https://azure.microsoft.com/en-us/services/hdinsight/" target="_blank">Azure HDInsight</a> 는 업계 최고의 완전 관리형 클라우드 Apache Hadoop &amp; Spark 제품으로, 고객이 업계 최고의 SLA를 사용하여 신뢰할 수 있는 오픈 소스 분석을 실행할 수 있도록 합니다. <a href="https://www.imanisdata.com" target="_blank">Imanis Data</a> 는 사용자가 데이터를 마이그레이션하고 빅 데이터 애플리케이션에 대한 백업 및 복원 기능을 추가할 수 있는 데이터 관리 소프트웨어를 제공합니다.</p>


  <p>이 결합된 HDInsight Imanis Data 제품과 Azure Blob Storage 및 Data Lake Store와의 통합을 통해 고객은 클라우드로 더 빠르게 마이그레이션하고 애플리케이션 또는 사용자 오류로부터 중요한 데이터 자산을 보호할 수 있습니다.</p>


  <h2>HDInsight Microsoft Azure – 엔터프라이즈급 및 규모에서 신뢰할 수 있는 오픈 소스 분석</h2>


  <p>HDInsight는 99.9% SLA를 통해 지원되는 Spark, Hive, Interactive Hive, MapReduce, HBase, Storm, Kafka 및 R Server에 최적화된 오픈 소스 분석 클러스터를 제공하는 유일한 완전 관리형 클라우드 Hadoop 제품입니다. 이러한 각 빅 데이터 기술은 엔터프라이즈 수준의 보안 및 모니터링을 통해 관리형 클러스터로 쉽게 배포할 수 있습니다.</p>


  <h2>Imanis Data – 빅 데이터 애플리케이션에 대한 클라우드 마이그레이션, 백업 및 복원</h2>


  <p>일반적으로 클라우드 컴퓨팅의 폭발적인 증가와 빅 데이터 애플리케이션의 증가로 인해 이전에 온-프레미스에서 실행되었던 워크로드가 Azure에서 대규모로 실행되도록 해야 했습니다. 뿐만 아니라 기본 HDInsight 데이터 자산을 재해, 사용자 오류 및 애플리케이션 손상으로부터 보호합니다.</p>


  <p>이를 위해 Azure에서 소프트웨어 솔루션을 방금 시작한 Imanis Data(이전의 Talena, Inc.)를 강조하게 되어 기쁩니다. Imanis Data는 다음을 포함하여 HDInsight 고객에게 도움이 되는 광범위한 사용 사례를 다루는 데이터 관리 소프트웨어를 제공합니다.</p>


  <ul>
   <li>온-프레미스 또는 다른 클라우드 빅 데이터 워크로드를 Azure HDInsight로 마이그레이션: Imanis Data는 회사에서 사용 중인 Hadoop 배포와 관계없이 빅 데이터 워크로드를 HDInsight로 마이그레이션할 수 있는 강력한 방법을 제공합니다. 여기에는 데이터 및 애플리케이션별 메타데이터도 모두 포함됩니다.</li>
   <li>클라우드 재해 복구: Imanis Data는 Hive, HBase, Spark와 같은 오픈 소스 워크로드의 데이터와 메타데이터를 보조 지역으로 이동하여 지역 간 DR을 사용하도록 설정하는 기초로 쉽게 사용할 수 있습니다.</li>
   <li>확장 가능한 백업 및 신속한 복구: Imanis Data를 사용하면 Hive, HBase, Spark와 같은 오픈 소스 워크로드에서 사용하는 페타바이트 규모의 데이터를 매우 빠르게 백업하고 특정 시점으로 복구할 수 있습니다.</li>
   <li>테스트 데이터 관리: 기업이 데이터를 클라우드로 이동함에 따라 PII 보호가 중요합니다. Imanis Data의 네이티브 데이터 마스킹 기능을 통해 기업은 데이터를 QA, 데이터 분석 또는 클라우드의 다른 클러스터로 마이그레이션하는 동안 중요한 데이터를 보호할 수 있습니다.</li>
   <li>규정 준수 및 규정 요구 사항에 대한 보관.</li>
   <li>Microsoft Azure Blob Storage 및 Azure Data Lake Store와의 네이티브 통합<br>&nbsp; </li>
  </ul>


  <p>이러한 다양한 사용 사례를 지원하기 위해 Imanis Data 소프트웨어 아키텍처는 다음을 통합합니다.</p>


  <ul>
   <li>페타바이트 규모 워크로드를 지원할 수 있는 확장성이 뛰어난 분산 파일 시스템입니다.</li>
   <li>직관적인 메타데이터 카탈로그를 사용하는 신속한 복구 기능, 다양한 데이터베이스 토폴로지로 복구할 수 있는 유연성 및 병렬 데이터 전송을 지원합니다.</li>
   <li>증분-영구 백업, 전역 블록 수준 중복 제거 및 압축에 중점을 둔 기본 제공 스토리지 최적화 엔진입니다.</li>
   <li>다양한 데이터베이스와 에이전트 없는 통합</li>
   <li>여러 Azure 지역에서 데이터 미러링 및 복제를 지원합니다.</li>
  </ul>


  <p>Azure의 Imanis Data 제품에 대해 자세히 알아보려면 다음을 참조하세요.</p>


  <ul>

  </ul>


  <h2>Azure HDInsight에서 Imanis Data 시작</h2>


  <p><a href="https://azuremarketplace.microsoft.com/en-us/marketplace/apps/talena-inc.talena-solution-template?tab=Overview" target="_blank">Azure Marketplace에서 Imanis Data를</a> 설치할 수 있습니다. Imanis Data 소프트웨어는 클러스터 외부에 있는 VM에 설치됩니다.</p>


  <p>Azure HDInsight용 Imanis Data를 구성하려면 이 자세한 <a href="https://www.imanisdata.com/wp-content/uploads/2017/08/HDITalena-Resources-Deployment-Guide.pdf" target="_blank">가이드</a>를 참조하세요. 다음은 HDInsight용 Imanis Data를 구성하는 스크린샷입니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/470518c9-1823-481b-8c9a-278c64b46441.png"><img width="610" height="308" title="스크린샷 2017-08-15 오후 2.45.04" style="border: 0px currentcolor; border-image: none; margin-right: 0px; margin-left: 0px; display: inline; background-image: none;" alt="Screen Shot 2017-08-15 at 2.45.04 PM" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/2480c34c-d644-4b56-a8a8-466689c491c9.png" border="0"></a></p>


  <p><br></p>


  <p>설치한 후 Azure HDInsight 클러스터에 연결하고 다음 작업을 수행합니다.</p>


  <ul>
   <li><strong>Imanis Data를 온-프레미스 Hadoop 또는 Spark 클러스터로 커넥트:</strong> Imanis Data는 온-프레미스 Hadoop, Spark 또는 HBase의 데이터뿐만 아니라 이러한 워크로드와 연결된 메타데이터를 클라우드로 마이그레이션하는 데 도움이 될 수 있습니다. Azure Blob Storage 또는 Azure Data Lake Store에 데이터를 저장할 수 있습니다. 데이터를 이동하면 Hadoop, Spark 또는 HBase를 실행하거나 Azure HDInsight의 R Server를 사용하여 고급 분석을 수행할 수 있습니다.</li>
   <li><strong>클라우드 재해 복구:</strong> Imanis Data는 Hive, HBase, Spark와 같은 오픈 소스 워크로드의 데이터와 메타데이터를 보조 지역으로 이동하기 위한 기준으로 쉽게 사용할 수 있으므로 지역 간 DR을 사용할 수 있습니다.</li>
   <li><strong>확장 가능한 백업 및 빠른 복구:</strong> Imanis Data를 사용하면 Hive, HBase, Spark와 같은 오픈 소스 워크로드에서 사용하는 페타바이트 규모의 데이터를 매우 빠르게 백업하고 특정 시점으로 복구할 수 있습니다.</li>
   <li><strong>테스트 데이터 관리:</strong> 기업이 데이터를 클라우드로 이동함에 따라 PII 보호가 중요합니다. Imanis Data의 네이티브 데이터 마스킹 기능을 통해 기업은 데이터를 QA, 데이터 분석 또는 클라우드의 다른 클러스터로 마이그레이션하는 동안 중요한 데이터를 보호할 수 있습니다.</li>
   <li><strong>규정 준수 및 규정 요구 사항에 대한 보관</strong>.</li>
  </ul>


  <h2>클라우드 마이그레이션, 백업 및 복원 등에 대한 공동 웨비나</h2>


  <p>6월 27일에 공동 웨비나를 개최했으며, 그 동안 기업이 Imanis Data를 사용하여 HDInsight에서 빅 데이터 애플리케이션을 관리하는 방법을 강조했습니다. Imanis Data를 사용하여 Azure의 여러 지역에서 하이브리드 환경, 개발/테스트 관리, 백업 및 복원 및 복제를 설정하는 방법에 대한 다양한 패턴을 설명했습니다. 다음 다이어그램에서는 다루는 패턴의 요약을 보여 줍니다. 당신이 그것을 놓친 경우, 당신은 여전히 자세한 내용을 보려면 <a href="https://go.imanisdata.com/Microsoft-Azure-Optimize-Performance-Reliability.html" target="_blank">웨비나를 볼</a> 수 있습니다. 우리는 당신과 이야기하고 피드백을 얻기를 기대합니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/6da51be3-50a9-4e86-b339-e2eb5b3adf37.png"><img width="610" height="356" title="스크린 샷 2017-08-16 에 10.09.16 오후" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" alt="Screen Shot 2017-08-16 at 10.09.16 PM" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/c4a86b0f-959a-47c1-8011-6d89ff2e441e.png" border="0"></a></p>


  <h2>리소스</h2>


  <p>이 통합에 대해 자세히 알아볼 수 있는 리소스는 다음과 같습니다.</p>


  <ul>
   <li><a href="https://docs.microsoft.com/en-us/azure/hdinsight/" target="_blank">Azure HDInsight에 대해 자세히 알아보기</a></li>
   <li><a href="https://globenewswire.com/news-release/2017/06/22/1027652/0/en/Talena-Enables-Rapid-Migration-of-Modern-Data-Workloads-to-Microsoft-Azure-HDInsight.html" target="_blank">Talena를 사용하면 최신 데이터 워크로드를 신속하게 마이그레이션하여 HDInsight를 Microsoft Azure 수 있습니다.</a></li>
   <li><a href="https://azuremarketplace.microsoft.com/en-us/marketplace/apps/talena-inc.talena-solution-template?tab=Overview" target="_blank">Azure Marketplace에서 Imanis 데이터 가져오기</a></li>
   <li><a href="https://www.imanisdata.com/wp-content/uploads/2017/08/Talena-Deployment-User-Guide.pdf" target="_blank">Azure에서 Imanis Data 시작</a></li>
   <li><a href="https://www.imanisdata.com/wp-content/uploads/2017/08/HDITalena-Resources-Deployment-Guide.pdf" target="_blank">Azure HDInsight에서 Imanis Data 시작</a></li>
   <li><a href="https://www.imanisdata.com/resources-cpt/microsoft-azure-datasheet/" target="_blank">Azure 데이터 시트의 Imanis 데이터 관리 솔루션</a></li>
   <li><a href="https://github.com/Talena/public-templates/" target="_blank">지역 간 복제 scenrio를 위해 Azure HDInsight에 Imanis Data 배포</a></li>
   <li><a href="https://www.imanisdata.com/solutions/microsoft-azure/" target="_blank">Azure의 Imanis Data에 대해 자세히 알아보기</a></li>
   <li><a href="https://stackoverflow.com/questions/tagged/hdinsight" target="_blank">stackoverflow에 대한 HDInsight 질문하기</a></li>
  </ul>


  <h2>요약</h2>


  <p>이 결합된 HDInsight Imanis Data 제품과 Azure Blob Storage 및 Data Lake Store와의 통합을 통해 고객은 클라우드로 더 빠르게 마이그레이션하고 애플리케이션 또는 사용자 오류로부터 중요한 데이터 자산을 보호할 수 있습니다. 피드백이나 질문이 있는 경우 언제든지 전자 메일 hdiask@microsoft.com을 보내주세요. Microsoft는 여러분의 의견을 기다리고 있습니다!</p>
