### YamlMime:Yaml
ms.openlocfilehash: 3791ac3db0415670c8871617887eec63e27a5b0b
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139905920"
Slug: improvements-sql-database-elastic-pool-configuration-experience
Title: SQL 탄력적 풀 구성 환경 개선
Summary: Azure Portal에서 SQL 탄력적 풀 구성 환경을 크게 개선했습니다. 이러한 변경 내용은 탄력적 풀에 대한 새 vCore 기반 구매 모델과 함께 릴리스됩니다...
Content: >-
  <p>Azure Portal에서 SQL 탄력적 풀 구성 환경을 크게 개선했습니다. 이러한 변경 내용은 탄력적 풀 및 단일 데이터베이스에 대한 <a href="https://azure.microsoft.com/en-us/blog/a-flexible-new-way-to-purchase-azure-sql-database/">새 vCore 기반 구매 모델</a> 과 함께 릴리스됩니다. 우리의 목표는 탄력적 풀을 구성하는 환경을 간소화하고 구성 선택에 확신을 갖도록 하는 것입니다.</p>


  <h2>기존 풀에 대한 서비스 계층 변경</h2>


  <p>이제 서비스 계층 간에 기존 탄력적 풀을 확장 및 축소할 수 있습니다. 서비스 계층 간에 쉽게 이동하고 비즈니스 요구 사항에 가장 적합한 계층을 검색할 수 있습니다. DTU 기반 서비스 계층과 새 vCore 기반 서비스 계층 간에 전환할 수도 있습니다. 업무 시간 외 풀을 축소하여 비용을 절감할 수도 있습니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/466cee59-114c-47f9-8d60-7286f8652c1e.jpg"><img alt="servicetiers (002)" border="0" height="215" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/a8e502d2-88ef-4f65-8864-bfe61dcfcd93.jpg" style="border: 0px currentcolor; border-image: none; display: inline; background-image: none;" title="servicetiers(002)" width="1592"></a></p>


  <h2>풀 및 해당 데이터베이스의 구성 간소화</h2>


  <p>탄력적 풀은 고객이 사용자 지정할 수 있는 많은 설정을 제공합니다. 새 환경은 풀 설정, 데이터베이스 설정 및 데이터베이스 관리 간에 풀 관리의 각 측면을 분리하고 간소화하는 것을 목표로 합니다. 이렇게 하면 풀의 이러한 각 측면을 보다 쉽게 추론하면서 모든 설정 변경 내용을 하나의 일괄 처리로 저장할 수 있습니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/8a1d1d9c-aaaf-4b89-96f9-bd84dc59790c.png"><img alt="configurepool" border="0" height="988" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/7cac481c-4654-4e11-adf2-80c3965aa0fb.png" style="border: 0px currentcolor; border-image: none; display: inline; background-image: none;" title="configurepool" width="1641"></a></p>


  <h2>새 비용 요약을 사용하여 청구서 이해</h2>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/4d305e4f-97ae-49fe-b834-546c02cd7814.jpg"><img align="right" alt="costsummary" border="0" height="236" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/4ebbb456-a85e-486c-be0e-3761674f66ad.jpg" style="border: 0px currentcolor; border-image: none; float: right; display: inline; background-image: none;" title="costummaryOur" width="340"></a> 탄력적 풀 및 단일 데이터베이스에 대한 새로운 비용 요약 환경은 선택 항목의 가격 책정을 이해하는 데 도움이 됩니다. 청구서에 기여하는 각 설정은 세분화되고 합산되어 총 월별 예상 청구서를 표시합니다. 모든 구성을 선택한 후에 비용이 어떻게 영향을 미치는지 알 수 있다는 확신을 갖고 싶습니다.</p>


  <p>&nbsp;</p>


  <p>&nbsp;</p>


  <p>&nbsp;</p>


  <p>자세한 내용은 <a href="https://docs.microsoft.com/en-us/azure/sql-database/sql-database-service-tiers" target="_blank">서비스 계층</a> 및 <a href="https://docs.microsoft.com/en-us/azure/sql-database/sql-database-elastic-pool" target="_blank">탄력적 풀</a>에 대한 설명서를 참조하세요.</p>
