### YamlMime:Yaml
ms.openlocfilehash: 5144144ab3fc2d2fe355374611de4ec19bb86cb3
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139908383"
Slug: insights-and-best-practices-to-run-businesscritical-applications-on-azure
Title: Azure에서 중요 비즈니스용 애플리케이션을 실행하는 Insights 및 모범 사례
Summary: '2020년 9월에는 IT 조직이 현재 중요 업무용 인프라를 관리할 때 직면하는 주요 과제를 분석했습니다. '
Content: >-
  <p>2020년 9월에는 <a href="https://azure.microsoft.com/en-us/blog/run-your-core-applications-on-azure/" target="_blank">IT 조직이 현재 중요 업무용 인프라를 관리할</a> 때 직면하는 주요 과제를 분석했습니다. 보안 문제, 높은 비용 및 환경 업데이트의 어려움을 가장 염두에 두었습니다. 반대로 클라우드로의 이동은 이러한 많은 장애물을 해결하는 데 도움이 되었습니다. 실제로 전환을 완료한 고객은 다음과 같은 이점을 자주 꼽습니다.</p>


  <ul>
      <li>향상된 보안 및 규정 준수.</li>
      <li>업무에 중요한 시스템의 성능 향상 및 대기 시간 단축</li>
      <li>더 빠른 인프라 구현 시간.</li>
      <li>더 큰 민첩성(새로운 기능을 개발하는 동안 기존 시스템을 현대화할 수 있는 기회로 인해).</li>
  </ul>


  <p>또한 조직에서 핵심 비즈니스 프로세스를 실행하기 위해 클라우드를 사용하는 경우 상당한 운영 이점을 활용할 수 있습니다. 이것은 불확실성의 기후에서 특히 사실이다. 따라서 조직이 애플리케이션을 클라우드로 계속 마이그레이션하는 속도가 느려지지 않고 비즈니스에 중요한 애플리케이션이 포함됩니다.</p>


  <h2>비즈니스에 중요한 광범위한 애플리케이션</h2>


  <p>우리는 또한 미션 및 비즈니스에 중요한 애플리케이션의 스펙트럼이 기존의 기록 시스템을 넘어 계속 확대되고 진화하는 방법을 관찰했습니다. 디지털 트랜스포메이션 이니셔티브를 진행하면서 거의 모든 업계에서 이 패턴을 볼 수 있습니다.</p>


  <p>Azure에서 <a href="https://info.microsoft.com/ww-landing-insights-and-practices-to-run-business-critical-apps-on-azure.html" target="_blank">Business-Critical 앱을</a>&nbsp; 실행하기 위한 웹 세미나 미니 Insights 및 사례 중에 Azure를 핵심 비즈니스용 애플리케이션을 제공하는 플랫폼으로 채택한 몇몇 고객과 ISV(독립 소프트웨어 공급업체)에게 클라우드 경험 중에 축적된 경험을 공유해 달라고 요청합니다. 또한 고객을 더 잘 돕기 위해 이러한 전례 없는 시대가 클라우드 마이그레이션 우선 순위에 어떻게 영향을 미쳤는지 더 광범위한 규모로 이해하고자 합니다. 이를 위해 업계 동료의 진정한 관점 외에도 Forrester의 업데이트된 시장 조사 인사이트를 제공합니다.</p>


  <p>이 세 부분으로 구성된 Azure 웨비나 미니세이퍼에서는 다음을 수행할 수 있습니다.</p>


  <ul>
      <li>Forrester에서 중요 비즈니스용 애플리케이션에 대한 클라우드 마이그레이션 전략을 빌드할 때 고려해야 하는 중요한 성공 요인에 대해 알아봅니다.</li>
      <li>Azure에서 제공되는 최신 혁신을 통해 비즈니스에 중요한 애플리케이션의 복원력과 성능을 지속적으로 개선하는 방법을 알아보세요.</li>
      <li>실제 예제를 검토하고 아키텍처를 참조하며 Riversand, Teradata 및 Unit4의 모범 사례를 알아봅니다.</li>
  </ul>


  <h2>1부: 중요 비즈니스용 애플리케이션을 클라우드로 전환</h2>


  <p>첫 번째 웨비나에서 포레스터 리서치의 수석 애널리스트인 트레이시 우(Tracy Woo)는 지난 몇 달 동안 수집된 최신 시장 동향을 공유합니다. 또한 고객이 중요 비즈니스용 애플리케이션을 클라우드에 배포하는 데 도움이 되도록 Microsoft가 최근에 Azure에 도입한 기능 중 일부를 소개합니다. 이 세션에서는 확장성, 보안, 규정 준수 및 가용성에 초점을 맞출 것입니다. 이 모든 정보를 실제 고객 환경의 컨텍스트로 가져오기 위해Riversand 경영진과&nbsp; 패널 토론을 진행합니다. Azure에서 제공하는 기능을 사용하여 마스터 데이터 관리 및 제품 정보 관리 솔루션을 배포하는 방법을 알아봅니다.</p>


  <h2>2부: Azure의 수요에 따라 데이터 분석 플랫폼 크기 조정</h2>


  <p>비즈니스에 중요한 애플리케이션에 대해서만 이야기하는 경우가 많지만, 애플리케이션 자체보다 중요하지 않은 경우 데이터는 중요합니다. 두 번째 웨비나에서는 Azure에서 대규모 데이터 웨어하우스 환경의 성능을 관리하는 데 도움이 되는 입증된 방법론을 검토하도록 Teradata 주제 전문가를 초대합니다. Teradata는 수년 동안 클라우드 기반 데이터 웨어하우징, 비즈니스 인텔리전스 및 데이터 분석 솔루션을 기업에 제공해 왔습니다. 주요 발표자는 보안 기능, 하이브리드 클라우드 배포, 확장성 요소 및 클라우드 기반 데이터 분석 플랫폼에 대한 추가 권장 사항을 해결하는 방법을 포함하여 Teradata Vantage와 관련된 여러 측면을 검토합니다. 또한 공유 디스크를 비롯한 새로운 Azure Disk Storage 기능과 가동 중지 시간 없이 중요한 애플리케이션에 대한 디스크 스토리지 성능을 확장 및 축소하는 방법을 통해 시장에 출시한 최신 혁신을 제시합니다.</p>


  <h2>3부: Azure에서 ERP 솔루션을 실행하여 보안, 가용성 및 규정 준수 향상</h2>


  <p>마지막으로 중요 업무용 애플리케이션을 생각할 때 ERP(엔터프라이즈 리소스 계획) 시스템이 가장 먼저 떠오릅니다. 지난 몇 년 동안 Unit4는 전문 서비스, 공공 부문, 비영리 및 교육을 포함한 산업에서 최신 ERP 소프트웨어 솔루션을 제공해 왔습니다. Unit4s&rsquo; CTO는 입증된 모범 사례, 지침 및 본격적인 관점을 제공합니다. Unit4에서 고객&rsquo; 배포 전략을 안내하는 방법도 중요합니다. IaaS 기반 리프트 앤 시프트 전략에서 클라우드 네이티브 마이크로 서비스 기반 환경에 이르기까지 클라우드 여정에 대해 들어보겠습니다. 또한 고객이 사용 중인 동안 데이터를 암호화하는 기능을 포함하여 비즈니스에 중요한 애플리케이션의 보안, 규정 준수 및 복원력을 지속적으로 개선하는 데 도움이 되는 최신 Azure 기능을 제공합니다.&nbsp;</p>


  <p>이 세 세션에서는 청중의 온라인 질문을 받아 특정 관심 분야를 다룹니다.</p>


  <h2>지금 등록</h2>


  <p><a href="https://info.microsoft.com/ww-landing-insights-and-practices-to-run-business-critical-apps-on-azure.html" target="_blank">이제 웹 세미나 시리즈에 등록하여</a> 성장하는 Azure 커뮤니티의 구성원과 고유한 인사이트와 진정한 토론을 제공합니다.</p>


  <p>또한 Microsoft가 의뢰한 독점 <a href="https://forrester.co1.qualtrics.com/jfe/form/SV_5bfMfKmQdxOkKfc" target="_blank">Forrester 컨설팅 설문 조사에</a> 참여하여 조직이 중요 업무용 앱에 대해 어떻게 생각하고 있는지 공유하도록 초대합니다. 미니 시리즈가 완료되면 모든 설문 조사 참가자에게 집계되고 익명화된 결과에 대한 무료 보고서가 제공됩니다.</p>


  <p>토론에 참여하세요. 나는 이 다가오는 세션을 고대하고 있다.</p>
