### YamlMime:Yaml
ms.openlocfilehash: aa2bf616b984f137e014e495834d8b8a0028fac1
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139898910"
Slug: integrating-application-insights-into-a-modular-cms-and-a-multi-tenant-public-saas
Title: 모듈식 CMS 및 다중 테넌트 공용 SaaS에 애플리케이션 Insights 통합
Summary: 각 테넌트가 고유한 성능 및 사용량 모니터링을 가져오는 방식으로 애플리케이션 Insights 다중 테넌트 서비스에 통합했습니다.
Content: >-
  <p><strong>Orchard CMS 애플리케이션 Insights 모듈 및 DotNest 사례 연구</strong></p>


  <p><a href="https://azure.microsoft.com/services/application-insights/">애플리케이션 Insights</a> <a href="https://github.com/Microsoft/ApplicationInsights-Home">오픈 소스 SDK 및 퍼블릭 엔드포인트</a>를 사용하여 통합을 개발하는 파트너와 함께 <a href="https://docs.microsoft.com/azure/application-insights/app-insights-platforms">활성화된 에코시스템</a>을 보유하고 있습니다. 최근에 Lombiq(파트너 중 하나)가 Application Insights Orchard CMS와 동일한 다중 테넌트 공용 SaaS 버전에 통합했습니다.</p>


  <p><i>여기에 자신의 말로 자신의 경험의 사례 연구입니다, Zoltn&aacute; Lehczky&oacute;에 의해, <a href="https://lombiq.com/">롬비크의</a> 공동 설립자, 과수원 CMS 개발자.</i></p>


  <p>각 테넌트가 고유한 성능 및 사용량 모니터링을 가져오는 방식으로 애플리케이션 Insights 다중 테넌트 서비스에 통합했습니다. 동시에 서비스 공급자는 전체 플랫폼에 대한 전반적인 모니터링을 받습니다. <a href="https://github.com/Lombiq/Orchard-Azure-Application-Insights">작성한 코드</a>는 오픈 소스입니다.</p>


  <p>Visual Studio 몇 번의 클릭만으로 애플리케이션 <a href="https://azure.microsoft.com/services/application-insights/">Insights</a> 원격 분석을 ASP.NET 웹앱에 쉽게 추가할 수 있습니다. 그러나 웹앱이 자체 호스팅되거나 CMS as a Service로 제공될 수 있는 풍부한 기능을 갖춘 CMS(다중 테넌트 콘텐츠 관리 시스템)인 경우 모니터링 요구 사항의 복잡성이 증가합니다. 따라서 애플리케이션 Insights 라이브러리를 확장하여 플랫폼에 기본으로 느껴지는 통합을 빌드해야 합니다. 목표는 쉽게 사용할 수 있는 CMS 플랫폼과 관련된 애플리케이션 Insights 뛰어난 분석 및 모니터링 기능을 사용자에게 제공하는 것입니다. 이 블로그 게시물에서는 Orchard CMS 애플리케이션 Insights 모듈에서 사용되는 몇 가지 기술과 사례를 설명합니다.</p>


  <p><a href="https://lombiq.com">Lombiq Technologies</a>는 헝가리의 .NET 소프트웨어 서비스 회사입니다. Microsoft와 같은 국제적인 클라이언트가 있습니다. MVC CMS가 시작되고 Microsoft에서 계속 지원되기 ASP.NET 오픈 소스인 <a href="https://orchardproject.net/">Orchard</a>는 <a href="https://dotnest.com/">주로 DotNest</a>라는 공용 다중 테넌트 Orchard as a Service를 구축했습니다. 오랜 Azure 사용자로서 개발 초기 단계였던 애플리케이션 Insights 대해 알아보고 DotNest에서 활용할 수 있는 쉽게 사용할 수 있는 Orchard 통합을 빌드하기 시작했습니다. 그래서, 우리의 경험은 공유 가치가 무엇입니까?</p>


  <p>개발한 Application Insights Orchard 모듈은 오픈 소스이므로 더 많은 코드를 보려면 <a href="https://github.com/Lombiq/Orchard-Azure-Application-Insights">GitHub 체크 아웃</a>해야 합니다. 여기서 설명하는 모든 항목이 구현됩니다.</p>


  <h1>모듈식 다중 테넌트 CMS에서 애플리케이션 Insights 사용</h1>


  <p>기본적으로 제공되는 &ldquo;&rdquo;애플리케이션 Insights 단일 테넌트 애플리케이션에서 쉽게 작동하며,&rsquo; 루트 수준 XML 구성 파일이 필요한 문제가 없습니다. 그러나 코드가 Orchard CMS와 같은 다른 사용자&rsquo; 애플리케이션에 통합되는 모듈인 경우 모든 모니터링 확장을 포함한 코드가 자체 포함되도록 할 수 있습니다. 클라이언트가 애플리케이션 수준에서 구성 파일에 노출되는 것을 원하지 않습니다&rsquo;. 즉, 애플리케이션 Insights 코드에 통합하여 독립적으로 배포 가능한 단일 MVC 프로젝트를 만들어야 합니다. 분산 양식은 원본 리포지토리 또는 zip 파일일 수 있습니다.</p>


  <p>애플리케이션 Insights 코드에 패키지하려면 다음을 수행해야 합니다.</p>


  <ul>
   <li>애플리케이션 Insights 구성을 codethat&mdash;으로 이동하면 일반적으로 XML 구성 파일에서 수행되는 C#에서 동일한 작업을 수행합니다.</li>
   <li>코드에서 원격 분석 모듈의 수명을 관리합니다. 각 모듈은 다양한 유형의 원격 분석&mdash;, 예외, 종속성 등을 처리합니다. 일반적으로 이러한 모듈은 .config 파일을 읽을 때 인스턴스화되고 구성 파일에 매개 변수가 설정됩니다. (<a href="https://docs.microsoft.com/azure/application-insights/app-insights-configuration-with-applicationinsights-config">자세히 알아보세요</a>. <a href="https://github.com/Lombiq/Orchard-Azure-Application-Insights/blob/master/Services/AppWideSetup.cs">코드)</a>.</li>
   <li>정적 싱글톤에 의존하는 대신 사용자 지정 방식으로 개체를 <code>TelemetryConfiguration</code> 관리 <code>TelemetryClient</code> 합니다. 이렇게 하면 별도의 테넌트에 대한 원격 분석을 별도로 유지할 수 있습니다. (이 <a href="https://github.com/Lombiq/Orchard-Azure-Application-Insights/blob/master/Services/TelemetryConfigurationAccessor.cs">코드</a> 예제 참조)</li>
   <li>Orchard는 로깅에 <a href="https://logging.apache.org/log4net/">log4net</a> 을 사용합니다. <a href="https://docs.microsoft.com/azure/application-insights/app-insights-asp-net-trace-logs">Application Insights 이 데이터를 수집</a>할 수 있지만 구성 파일에 의존하는 대신 ApplicationInsightsAppender를 구성하는 코드를 다시 작성해야 합니다. (<a href="https://github.com/Lombiq/Orchard-Azure-Application-Insights/blob/master/Services/LoggerSetup.cs">코드</a>) <p>모두 좋습니다. 이제 앱 수준 XML 구성을 제거했습니다. 그러나 동일한 앱에 여러 테넌트가 있는 경우 어떻게 해야 할까요? 애플리케이션 Insights 기본 설정은 단일 테넌트만 염두에 두고 있으므로 좀 더 자세히 살펴보아야 합니다. (이 게시 &ldquo;테넌트를 위해 다른 테넌&rdquo; 트에 대해 높은 수준의 데이터 격리를 유지하는 애플리케이션 내의 구성 요소인 하위 애플리케이션을 의미합니다.)</p>
   </li>
   <li>요청 추적을 위해 애플리케이션 Insights 함께 제공되는 기능을 활용할 <code>HttpModule</code> 수&rsquo; 없습니다. 이는 전역 구성 파일(<code>Web.config</code>)을 변경해야 하므로&rsquo; 테넌트별로 요청 추적을 쉽게 켜거나 끌 수 없습니다. Owin 미들웨어 <a>를 </a>구현하고 일부 <a href="https://github.com/Lombiq/Orchard-Azure-Application-Insights/blob/master/Services/RequestTrackingMiddlewareProvider.cs">사용자 지정 코드를</a> 사용하여 요청 추적을 수행하는 시간입니다. 이러한 미들웨어는 코드에서 완전히 등록할 수 있으며 테넌트별로 사용하도록 설정할 수 있습니다.</li>
   <li>요청 추적은 고유한 방식으로 수행되므로 각 요청에 대한 코드에서 작업 ID를 추가해야 합니다. 애플리케이션 Insights <a href="https://docs.microsoft.com/azure/application-insights/app-insights-api-custom-events-metrics#operation-context">작업 ID</a>는 동일한 요청 서비스의 일부로 발생하는 원격 분석의 상관 관계를 지정하는 데 사용됩니다.</li>
   <li>&rsquo;또한 원격 분석의 일부가 시작되는 테넌트를 추가할 테넌트를 추가 <code>ITelemetryInitializer</code> 합니다. (<a href="https://docs.microsoft.com/azure/application-insights/app-insights-api-filtering-sampling#add-properties-itelemetryinitializer">자세히 알아보세요</a>. <a href="https://github.com/Lombiq/Orchard-Azure-Application-Insights/blob/master/TelemetryInitializers/ShellNameTelemetryInitializer.cs">코드</a>) <p>모든 작업이 완료되면&rsquo; 각 테넌트에 대해 별도로 Orchard 관리 사이트에서 사용하도록 설정하고 사용하지 않도록 설정할 수 있는 애플리케이션 Insights 플러그 인으로 끝납니다.</p>

   <p>&nbsp;</p>

   <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/5dc3c3a0-2cd9-41fc-a344-131725695e15.png"><img alt="Lombiq Modules" border="0" height="343" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/1eec4b56-72a5-49d8-a11d-49718a2d65c5.png" style="border: 0px currentColor; border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="Lombiq 모듈" width="580"></a></p>

   <p>&nbsp;</p>

   <h1>일부 과수원 추가</h1>

   <p>지금까지는 좋지만 결과는 CMS의 일부가 되기 위해 더 많은 작업이 필요합니다.&rsquo; 아직 구성할 곳이 없습니다.</p>

   <p>Orchard에서 <i>사이트 설정을</i> 사용할 수 있습니다. &rsquo;관리자가 웹 UI에서 변경할 수 있는 몇 가지 구성 옵션을 쉽게 추가할 수 있습니다. 이러한 설정은 테넌트 수준에 있습니다. Weve&rsquo;는 다음과 같은 설정 화면을 추가했습니다.</p>

   <p>&nbsp;</p>

   <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/0529a9dc-a217-4ac3-a146-01e0653989cb.png"><img alt="Enable application wide collection" border="0" height="445" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/cd5ee839-bcb7-4f2c-8b78-d3f55645ec2c.png" style="border: 0px currentColor; border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="애플리케이션 전체 컬렉션 사용" width="663"></a></p>

   <p>&nbsp;</p>

   <p>SQL 쿼리, 스토리지 작업 또는 원격 리소스에 대한 HTTP 요청과 같은 종속성에 대한 호출은 추적됩니다. 그러나 이렇게 하면 많은 데이터가&rsquo; 생성되므로 종속성 추적을 해제할 수 있습니다.</p>

   <p>일부 설정은 테넌트 수준에서 구성할 수 없거나(따라서 앱 수준이어야 함)&rsquo; 의미가 없습니다. 예를 들어 로그 항목이 테넌트에 연결되지 않고 전체 애플리케이션에 연결되지 않을 수 있으므로 모듈에서 앱 전체 컬렉션에만 사용할 수 있습니다(그럼에도 불구하고 추가 테넌트 수준 로그 수집이 가능함). 기본&rdquo; 테넌트에서만 사용할 수 있는&rsquo; 전체 구성이 &ldquo;표시됩니다.</p>

   <p>또한 개발자가 연결할 수 있는 몇 가지 확장 지점을 추가했습니다. &rsquo;따라서 동료 Orchard 개발자가 애플리케이션 Insights 구성을 재정의하거나 원격 분석 데이터에 고유한 컨텍스트를 추가하거나 이벤트 처리기(및 해당 문제에 대한 <a href="https://orcharddojo.net/orchard-resources/Library/Wiki/EventHandler">Orchard 스타일 이벤트</a>)를 활용할 수 있습니다.</p>

   <p>&nbsp;</p>

   <h1>공용 SaaS에서 애플리케이션 Insights 사용 가능</h1>

   <p>&rsquo;지금까지 살피는 것은 Application Insights 모니터링되는 자체 포함 구성 요소에 필요한 모든 기본 기능&rsquo;이었습니다. 그러나 모든 사용자가 등록할 수 있는 <a href="https://dotnest.com/">DotNest</a>에서는 Application Insights 두 가지 고유한 모니터링 계층이 필요합니다.</p>
   </li>
   <li>Microsoft는 자체 사용을 위해 전체 애플리케이션에 대한 자세한 원격 분석을 원합니다.</li>
   <li>DotNest 테넌트의 사용자는 애플리케이션 Insights 별도로 구성하고 테넌트에 대해 볼 수 있는 원격 분석을&rsquo; 수집하려고 합니다.
   <p>따라서&rsquo; DotNest 사용자는 전체 플랫폼 수준에서 관리되므로 원래 애플리케이션 Insights 구성 옵션도 볼 수 없습니다. 그러나 자체 계측 키를 구성할 수 있는 다른 사이트 설정 화면이 표시됩니다.</p>

   <p>&nbsp;</p>

   <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/5c65be51-30d8-40f1-9e7b-0928990526f7.png"><img alt="Azure Applications Telemetry Settings" border="0" height="327" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/23c9a35e-f5a8-4294-ac03-ca9b478887f3.png" style="border: 0px currentColor; border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="Azure 애플리케이션 원격 분석 설정" width="689"></a></p>

   <p>&nbsp;</p>

   <p>이러한 키가 제공되면 테넌트에 두 번째 애플리케이션 Insights 구성이 만들어지고 플랫폼 수준 1과 함께 사용되어 서버 쪽 및 클라이언트 쪽 요청 추적 및 오류 보고를 제공합니다. 따라서 Lombiq에서 서비스 소유자는 자체 애플리케이션 Insights 계정으로 모든 데이터를 볼 수 있지만 각 사용자는 평소와 같이 Azure Portal에서 자신의 테넌트&rsquo; 데이터만 볼 수 있습니다.</p>

   <p>이 테넌트 구성은 코드에서 원래 구성과 동일한 방식으로 만들어지고 관리됩니다.</p>

   <p>&nbsp;</p>

   <h1>결과 보기</h1>

   <p>이 모든 것이 설정되면 수집한 데이터의 종류를 확인하고 Azure <a href="https://portal.azure.com">Portal</a>에서 평소와 같이 발생합니다.</p>

   <h2>라이브 메트릭 스트림</h2>

   <p><a href="https://docs.microsoft.com/azure/application-insights/app-insights-live-stream">라이브 메트릭 스트림은</a> 실시간 모니터링을 제공합니다. 초기화 체인에 적절한 <a href="https://github.com/Lombiq/Orchard-Azure-Application-Insights/blob/master/TelemetryProcessors/DispatchingQuickPulseTelemetryProcessor.cs">원격 분석 프로세서</a> 를 포함했습니다. 여기에는 메모리 및 CPU 사용량과 같은 시스템 메트릭도 포함되며, 최근에&rsquo; App Service용 애플리케이션 Insights 확장을 설치할 필요도 없습니다.</p>

   <p>&nbsp;</p>

   <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/f997fe5b-859d-47b3-96ba-3d2c6fe39821.png"><img alt="Incoming requests outgoing requests" border="0" height="352" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/e3d60c73-c8d6-44ab-9f15-f3b80f8e1b60.png" style="border: 0px currentColor; border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="들어오는 요청 발신 요청" width="608"></a></p>

   <p>&nbsp;</p>

   <h2>추적 오류</h2>

   <p>그러나 문제가 발생하면 어떨까요? 로그 항목은 Azure Portal에서 추적(표준 로그 항목) 또는 예외(예외가 catch 및 기록되는 경우)로 표시됩니다.</p>

   <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/f66514c4-46d4-4a6f-8f6d-8b3ac7b4c948.jpg"><img alt="Something terrible happened" border="0" height="668" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/7e1335a8-fc7c-46eb-8a49-b46928c8a52e.jpg" style="border: 0px currentColor; border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="끔찍한 일이 일어났습니다." width="445"></a></p>

   <p>그러나 weve&rsquo;가 작업 ID를 구현했음을 기억하시겠습니까? 이벤트, 예외, 요청이 있으면 모든 데이터 요소가 단독으로만 표시되는 것이 아니라 컨텍스트에서 애플리케이션 Insights 원격 분석 데이터를 다른 데이터 요소와 상호 연결할 수 있다는 것입니다. 예를 들어 예외가 발생한 요청을 알릴 수 있습니다.</p>

   <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/2cf5acab-6662-46cb-a534-7bd234d25352.jpg"><img alt="Hosting Suite Modules" border="0" height="547" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/3cb1b0ce-fd3d-453d-a255-a377e9f592cb.jpg" style="border: 0px currentColor; border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="호스팅 제품군 모듈" width="759"></a></p>

   <p>이렇게 하면 프로덕션에서 방금 발생한 문제를 재현하는 방법을 더 쉽게 찾을 수 있습니다.</p>

   <h1>요약</h1>

   <p>통합을 재배포할 필요 없이 단일 구성으로 애플리케이션에 애플리케이션 Insights 추가하는 것 이상이 필요한 경우 애플리케이션 Insights 라이브러리&rsquo; API를 자세히 살펴보아야 합니다. 이제 라이브러리가 오픈 소스이기 때문에 이는 별로 문제가 되지 않으며 C#을 작성하여 완전히 구성하고 활용할 수 있습니다. <a href="https://github.com/Lombiq/Orchard-Azure-Application-Insights">Azure Application Insights Orchard 모듈</a>을 사용하면 이를 수행하는 문서화된 예제도 있습니다.</p>

   <p>그래서, 두려워하고 몇 가지 멋진 애플리케이션 Insights 통합을 코딩하지 마십시오&rsquo;! Azure Portal에서 멋진 그래프로 재생하려는 경우 <a href="https://dotnest.com/DotNest.Frontend/UserSiteManagement/EditSite">신속하게 무료 DotNest 사이트를 만들고</a> 일부 데이터 수집을 바로 시작할 수 있습니다.</p>
   </li>
  </ul>
