### YamlMime:Yaml
ms.openlocfilehash: 80134f756a54f02e838c9a2de3bfae3046393dce
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139905892"
Slug: introducing-health-integrated-rollouts-to-azure-deployment-manager
Title: Azure Deployment Manager에 상태 통합 롤아웃 소개
Summary: 안전하고 안정적인 배포를 수행하여 고가용성을 보장하고 Azure Deployment Manager에서 healthCheck를 사용한 회귀로 인한 서비스 가동 중지 시간을 크게 줄입니다.
Content: >-
  <p>Ignite 2018에서는 Azure Resource Manager 리소스의 단계적 롤아웃을 처음으로 미리 보기로 수행할 수 있는 Azure <a href="https://aka.ms/admblog" target="_blank">Deployment</a> Manager를 공개했습니다. 서비스의 상태를 모니터링하기 위해 지역 롤아웃 또는 지역 내 여러 단계의 일부로 이러한 지역과 통합된 상태 검사를 결합할 수 있습니다. &rsquo;이제 Azure Deployment Manager 미리 보기에서 상태 통합 기능을 사용할 수 있음을 알려드리게 되어 기쁩니다. 이러한 상태 통합 롤아웃은 허용되지 않는 신호가 감지되면 배포가 자동으로 중지되므로 영향의 규모를 문제 해결 및 줄일 수 있습니다. 이 정확한 도구 집합은 수백 Microsoft 서비스 내부적으로 안전하고 안정적인 배포를 수행하여 고가용성을 보장하고 업데이트의 회귀로 인한 서비스 가동 중지 시간을 방지하거나 크게 줄이는 데 이미 사용되고 있습니다.</p>


  <p>Azure Deployment Manager는 사전 프로덕션 환경에 배포하는 단계를 자동화하고, 다른 환경으로 점진적으로 이동하기 전에 일정 기간 동안 서비스 상태를 확인하고, 필요한 상태 검사를 수행합니다.&nbsp;</p>


  <p>이 기능은 다음과 같은 경우에 적합합니다.</p>


  <ul style="margin-left: 40px;">
   <li style="margin-bottom:4px;">&rsquo;여러 지역에 서비스를 배포하는 경우&nbsp;</li>
   <li style="margin-bottom:4px;">다양한 구성을 테스트하는 Youre&rsquo;</li>
   <li style="margin-bottom:4px;">이미 특정 종류의 상태 모니터링 서비스를 사용하고 있습니다.</li>
  </ul>


  <h2>서비스 상태 확인</h2>


  <p>상태 모니터링 공급자는 서비스 상태 문제를 모니터링하고 경고하는 몇 가지 메커니즘을 제공합니다. <a href="https://azure.microsoft.com/services/monitor/" target="_blank">Azure Monitor</a> 는 특정 임계값을 초과할 때 경고를 발생시키는 이러한 유형의 제품 중 하나의 예입니다. 일부 임계값은 초과될 때 서비스 상태에 문제가 있음을 나타냅니다. 예를 들어&rsquo; 서비스에 새 업데이트를 배포하고 메모리 및 CPU 사용률이 예상 수준을 초과하면 Azure Monitor 및 상태 모니터링 공급자가 문제를 알리므로 정정 작업을 수행할 수 있습니다.</p>


  <p>이러한 상태 공급자는 일반적으로 REST API를 제공하므로 서비스&rsquo; 모니터의 상태를 프로그래밍 방식으로 검사할 수 있습니다. REST API는 간단한 정상/비정상 신호(일반적으로 HTTP 응답 코드에 의해 결정됨)를 사용하거나 수신하는 신호에 대한 자세한 정보를 제공합니다.</p>


  <p>Azure Deployment Manager의 새 healthCheck 단계를 사용하면 정상 서비스를 나타내는 HTTP 코드를 선언하거나, 더 복잡한 REST 결과를 위해 일치하는 경우 정상 응답을 나타내는 정규식을 지정할 수도 있습니다. 더 쉽게 사용할 수 있도록 Azure Deployment Manager 팀은 상위 상태 모니터링 공급자와 긴밀하게 협력하여 이러한 HTTP 코드 및 정규식을 미리 작성하므로 이러한 공급자 중 하나를 사용하는 경우&rsquo; healthCheck 단계의 이 부분을 복사하여 붙여넣을 수 있습니다.&nbsp;</p>


  <p>Azure Deployment Manager 상태 검사를 사용하여 설정하는 프로세스는 간단합니다.</p>


  <ol style="margin-left: 40px;">
   <li style="margin-bottom:4px;">원하는 상태 서비스 공급자를 통해 상태 모니터를 만듭니다.</li>
   <li style="margin-bottom:4px;">Azure Deployment Manager 롤아웃의 일부로 하나 이상의 healthCheck 단계를 만듭니다.</li>
   <li style="margin-bottom:4px;">다음 정보를 사용하여 healthCheck 단계를 작성합니다. <ul>
    <li style="margin-bottom:4px;">상태 모니터에 대한 REST API에 대한 URI(상태 서비스 공급자가 정의한 대로)</li>
    <li style="margin-bottom:4px;">인증 정보(API 키 스타일 인증만 현재 지원됨)</li>
    <li style="margin-bottom:4px;">정상 응답을 정의하는 HTTP 상태 코드 또는 정규식</li>
   </ul>
   </li>
   <li style="margin-bottom:4px;">Azure Deployment Manager 롤아웃에서 적절한 시간에 healthCheck 단계를 호출합니다.</li>
  </ol>


  <h2>상태 검사 단계</h2>


  <p>이 시점에서 Azure Deployment Manager는 서비스의 상태와 이를 위해 롤아웃의 단계를 쿼리하는 방법을 알고 있습니다. 그러나 Azure Deployment Manager를 사용하면 이러한 검사의 타이밍을 심층 구성할 수도 있습니다. healthCheck 단계는 구성 가능한 기간이 있는 간단한 3단계 프로세스에서 실행되며, Azure 자체를 구성하는 가장 큰 Microsoft 서비스 상태 모니터링 요구를 지원할 수 있을 만큼 풍부합니다.</p>


  <p style="text-align: center;"><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/1a030fcb-1e6d-48f6-9bde-2dee79c184a4.png"><img alt="Phases of a health check" border="0" height="278" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/6b9dca2a-d785-4e75-8b08-c18582091ebe.png" style="width:80%; border: 0px currentcolor; border-image: none; display: inline; background-image: none;" title="상태 검사 단계" width="1370"></a></p>


  <p><strong>Wait</strong></p>


  <ul style="margin-left: 40px;width:80%">
   <li style="margin-bottom:4px;">배포 작업이 완료된 후 업데이트가 안정적인 상태에 도달하지 않았기 때문에 서비스 상태를 아직 확인하는 것은 의미가 없을 수 있습니다. 서비스가 상태 모니터링 공급자에 의해 집계되는 상태 신호를 유용한 것으로 내보내기 시작하는 데 시간이 걸리며, VM이 처음으로 시작되거나, 다시 부팅되거나, 새 데이터에 따라 다시 구성될 수 있습니다. 서비스 상태는 이 격동의 프로세스 중에 정상 상태와 비정상 상태 간에 진동할 수 있습니다.</li>
   <li style="margin-bottom:4px;">대기 단계 중에는 배포된 리소스가 상태 검사 프로세스를 시작하기 전에 베이킹할 시간을 허용하기 위해 서비스 상태가 모니터링되지 않습니다.</li>
  </ul>


  <p><strong>Elastic</strong></p>


  <ul style="margin-left: 40px; width:80%;">
   <li style="margin-bottom:4px;">리소스가 안정되기 전에 얼마나 오래 걸리는지 알 수 없는 경우가 많기 때문에 탄력적 단계에서는 리소스가 잠재적으로 불안정한 시기와 정상적이고 안정적인 상태를 유지해야 하는 시점 사이의 유연한 기간을 허용합니다.</li>
   <li style="margin-bottom:4px;">탄력적 단계가 시작되면 Azure Deployment Manager는 서비스 상태에 대해 제공된 REST 엔드포인트를 주기적으로 폴링합니다. 폴링 간격은 Azure Deployment Manager 미리 보기에 대해 3분으로 설정되지만 나중에 구성할 수 있습니다.</li>
   <li style="margin-bottom:4px;">상태 모니터가 서비스가 비정상임을 나타내는 신호와 함께 돌아오면 해당 신호가 무시되고 탄력적 단계가 유지되고 폴링이 계속됩니다.</li>
   <li style="margin-bottom:4px;">상태 모니터가 서비스가 정상임을 나타내는 신호와 함께 돌아오자마자 탄력적 단계가 종료되고 HealthyState 단계가 시작됩니다.</li>
   <li style="margin-bottom:4px;">따라서 탄력적 단계에 지정된 기간은 정상 응답이&nbsp; 필수로 간주되기 전에 서비스 상태에 대한 폴링을 사용할 수 있는 시간의 최대&nbsp;값입니다.</li>
  </ul>


  <p><strong>HealthyState</strong></p>


  <ul style="margin-left:40px; width:80%;">
   <li style="margin-bottom:4px;">HealthyState 단계 동안 서비스 상태는 탄력적 단계와 동일한 간격으로 지속적으로 폴링됩니다.</li>
   <li style="margin-bottom:4px;">이 서비스는 전체 지정된 기간 동안 상태 모니터링 공급자의 정상 신호를 유지 관리해야 합니다.</li>
   <li style="margin-bottom:4px;">비정상 응답이 검색되면 Azure Deployment Manager는 전체 롤아웃을 중지하고 비정상 서비스 신호를 전달하는 REST 응답을 반환합니다.</li>
   <li style="margin-bottom:4px;">HealthyState 단계 기간이 종료되면 healthCheck가 완료되고 배포가 다음 단계로 계속됩니다.</li>
  </ul>


  <h2>다음 단계</h2>


  <p>몇 가지 리소스로 Azure Deployment Manager 사용을 시작합니다.</p>


  <ul style="margin-left: 40px;">
   <li style="margin-bottom:4px;">Azure <a href="https://docs.microsoft.com/azure/azure-resource-manager/deployment-manager-overview" target="_blank">Deployment Manager를 사용하여 안전한 배포 사례를</a> 사용하도록 설정합니다.</li>
   <li style="margin-bottom:4px;"><a href="https://docs.microsoft.com/azure/azure-resource-manager/deployment-manager-tutorial" target="_blank">Resource Manager 템플릿에서 Azure Deployment Manager를 사용하는</a> 방법을 알아봅니다.</li>
   <li style="margin-bottom:4px;">의견이 있으신가요? <a href="https://aka.ms/admfeedback" target="_blank">Wed&rsquo; love to hear you!</a></li>
  </ul>
