### YamlMime:Yaml
ms.openlocfilehash: 30e42fc912a119f34e74f4083c511314a1c3f876
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139910983"
Slug: introducing-azure-event-grid-an-event-service-for-modern-applications
Title: 최신 애플리케이션을 위한 이벤트 서비스인 Azure Event Grid 소개
Summary: 오늘 저는 이벤트 기반 및 서버리스 애플리케이션을 Azure에서 더욱 쉽게 빌드할 수 있도록 하고 있음을 발표하게 되어 기쁩니다. Azure Event Grid는 완전 관리형 이벤트 라우팅 서비스이며 해당 종류의 첫 번째 서비스입니다.
Content: >-
  <p>대부분의 최신 애플리케이션은 IoT 디바이스의 변경 내용에 대응하든, 모바일 앱에서 사용자 클릭에 응답하든, 고객 요청에서 비즈니스 프로세스를 시작하는지에 관계없이 이벤트를 &ndash; 사용하여 빌드됩니다. 이벤트 기반 프로그래밍이 증가함에 따라 서버리스 플랫폼(예: Azure <a href="https://azure.com/serverless" target="_blank">Functions, 서버리스</a> 컴퓨팅 엔진 및 서버리스 워크플로 오케스트레이션 엔진인 Azure Logic Apps)에 대한 포커스가 늘어나고 있습니다. 두 서비스 모두 인프라, 프로비전 또는 크기 조정에 대한 걱정 없이 애플리케이션에 집중할 수 있습니다.</p>


  <p>오늘 저는 이벤트 기반 및 서버리스 애플리케이션을 Azure에서 더욱 쉽게 빌드할 수 있도록 하고 있음을 발표하게 되어 기쁩니다. <a href="https://azure.microsoft.com/en-us/services/event-grid/" target="_blank">Azure Event Grid</a> 는 완전 관리형 이벤트 라우팅 서비스이며 해당 종류의 첫 번째 서비스입니다. Azure Event Grid는 이벤트 기반 애플리케이션 개발을 크게 간소화하고 서버리스 워크플로 만들기를 간소화합니다. Azure Event Grid는 단일 서비스를 사용하여 모든 애플리케이션에 대해 모든 원본에서 대상으로 이벤트의 모든 라우팅을 관리합니다.</p>


  <p>Azure Event Grid는 Azure에서 이벤트를 일류 개체로 만드는 혁신적인 제품입니다. Azure Event Grid를 사용하면 Azure 리소스에서 발생하는 모든 이벤트를 구독하고 Functions 또는 Logic Apps와 같은 서버리스 플랫폼을 사용하여 반응할 수 있습니다. Event Grid는 Blob Storage 및 리소스 그룹과 같은 서비스를 사용하여 이벤트에 대한 기본 제공 게시 지원을 제공하는 것 외에도 유연성을 제공하며 사용자 지정 이벤트를 만들어 서비스에 직접 게시할 수 있습니다. Event Grid는 Functions, Logic Apps 및 Azure Automation과 같은 이벤트에 대한 기본 제공 처리기가 포함된 광범위한 Azure 서비스를 보유하는 것 외에도 이벤트를 유연하게 처리할 수 있으며, 사용자 지정 웹 후크를 지원하여 Azure 외부의 타사 서비스까지도 모든 서비스에 이벤트를 게시할 수 있습니다. 이러한 유연성은 끝없는 애플리케이션 옵션을 만들고 Azure Event Grid를 퍼블릭 클라우드에서 진정으로 고유한 서비스로 만듭니다.&nbsp;</p>


  <p>작동 방식은 다음과 같습니다.</p>


  <p><iframe allowfullscreen="" frameborder="0" height="540" src="https://channel9.msdn.com/Shows/Azure-Friday/Azure-Event-Grid/player" width="960"></iframe></p>


  <p>다음은 이 새 Azure 서비스에 대한 몇 가지 추가 세부 정보입니다.</p>


  <ul>
   <li><strong>지능형 필터링을 포함하는 일류 개체로서의 이벤트:</strong> Azure Event Grid는 이벤트 유형, 접두사 또는 접미사를 사용하여 직접 이벤트 필터링을 사용하도록 설정하므로 애플리케이션은 관심 있는 이벤트만 수신하면 됩니다. 스토리지에 추가되는 파일과 같은 기본 제공 Azure 이벤트를 처리하거나 사용자 고유의 사용자 지정 이벤트 및 이벤트 처리기를 생성하려는 경우 Event Grid는 동일한 기본 모델을 통해 이를 사용하도록 설정합니다. 따라서 서비스 또는 사용 사례에 관계없이 지능형 라우팅 및 필터링 기능은 모든 이벤트 시나리오에 적용되며, 앱이 라우팅 이벤트에 대해 걱정하지 않고 핵심 비즈니스 논리에 집중할 수 있도록 합니다.</li>
   <li><strong>크기 조정을 위해 빌드됩니다.</strong> Azure Event Grid는 가용성이 높고 대규모를 동적으로 처리하여 중요한 서비스에 대한 일관된 성능과 안정성을 보장하도록 설계되었습니다.</li>
   <li><strong>새 서버리스 가능성을 엽니다.</strong> 서버리스 엔드포인트가 새 이벤트 원본에 반응할 수 있도록 함으로써 Azure Event Grid를 사용하면 이벤트 기반 시나리오가 새 서비스에 쉽게 걸쳐 서버리스 애플리케이션의 가능성을 높일 수 있습니다. Functions의 코드 중심 애플리케이션과 Logic Apps의 시각적 워크플로 애플리케이션 모두 Azure Event Grid의 이점을 누릴 수 있습니다.</li>
   <li><strong>ops 자동화에 대한 장벽을 낮춥니다.</strong> 동일한 통합 이벤트 관리 인터페이스를 사용하면 VM 생성 또는 인프라 변경에 대응할 수 있도록 Azure Automation을 기본적으로 지원하는 보다 간편한 정책 적용을 포함하여 더 간단한 운영 및 보안 자동화를 사용할 수 있습니다.</li>
  </ul>


  <p>현재 Azure Event Grid는 다음 서비스와 기본적으로 통합되어 있습니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/ff3644c9-58ab-4729-8939-66a83ab0605d.png"><img alt="Event Publishers and Handlers" border="0" height="672" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/1f132bce-f3c0-4ba0-aa0c-9da1c32da9c1.png" style="border-top: 0px; border-right: 0px; background-image: none; border-bottom: 0px; float: none; padding-top: 0px; padding-left: 0px; margin-left: auto; border-left: 0px; display: block; padding-right: 0px; margin-right: auto" title="Event Publishers 및 HandlersWe" width="1369"></a>는 올해 말 Azure Active Directory, API Management, IoT Hub, Service Bus, Azure Data Lake Store, Azure Cosmos DB, Azure Data Factory 및 Storage 큐를 포함하여 더 많은 이벤트 원본 및 대상을 제공하기 위해 노력하고 있습니다.</p>


  <p>Azure Event Grid에는 이벤트당 종량제 가격 책정 모델이 있으므로 사용하는 항목에 대해서만 요금을 지불합니다. 또한 빠르게 시작할 수 있도록 매월 처음 100,000개의 작업이 무료입니다. 매월 100,000개 이상의 가격은 미리 보기 기간 동안 백만 작업당 $0.30(작업당)입니다. 자세한 내용은 <a href="https://azure.microsoft.com/pricing/details/event-grid/" target="_blank">가격 책정 페이지</a>에서 찾을 수 있습니다.</p>


  <p>Azure Event Grid는 누락된 서버리스 애플리케이션의 절반을 완료합니다. 탁월한 유연성으로 이벤트 라우팅 및 이벤트 처리를 간소화합니다. 나는 끝없는 가능성에 대해 흥분!</p>


  <p>계속해서 시도해 보세요. 나는 당신이 구축 무엇을보고 기다릴 수 없어&rsquo;. 자세히 알아보려면 <a href="https://docs.microsoft.com/en-us/azure/event-grid/" target="_blank">빠른 시작을 시도</a>하세요.</p>


  <p>주변을 둘러보십시오.</p>


  <p>코리</p>
