### YamlMime:Yaml
ms.openlocfilehash: b1b7e4405ec3a5a52f286490526fce503dd95db7
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139903233"
Slug: introducing-app-service-environment
Title: App Service Environment 소개
Summary: 오늘 추가 전용 Premium 서비스 계획 옵션인 App Service Environment의 공개 미리 보기를 도입하게 되어 기쁩니다.
Content: >-
  최근에 확장된 크기 조정 옵션과 앱 개발자에게 Premium Connectors를 사용하는 Biztalk Services를 도입한 Azure App Service용 Premium 계층을 <a href="https://azure.microsoft.com/blog/2015/03/30/azure-app-service-premium-tier/">발표</a>했습니다.오늘 추가 전용 Premium 서비스 계획 옵션인 App Service Environment의 공개 미리 보기를 도입하게 되어 기쁩니다.


  App Service Environment는 <a href="https://azure.microsoft.com/en-us/documentation/articles/app-service-web-overview/">Web Apps</a>, <a href="https://azure.microsoft.com/en-us/documentation/articles/app-service-mobile-value-prop-preview/">Mobile</a> Apps, <a href="https://azure.microsoft.com/en-us/documentation/articles/app-service-api-apps-why-best-platform/">API Apps</a> 및 <a href="https://azure.microsoft.com/en-us/documentation/articles/app-service-logic-what-are-logic-apps/">Logic</a> Apps를 비롯한 모든 앱을 안전하게 실행하기 위한 완전히 격리된 전용 환경을 제공합니다.App Service Environment는 항상 지역 가상 네트워크 내에 만들어집니다.이렇게 하면 앱이 사이트 간 및 <a href="https://azure.microsoft.com/services/expressroute/">ExpressRoute</a> 연결을 통해 연결된 엔드포인트를 포함하여 가상 네트워크 내에서만 액세스할 수 있는 다른 엔드포인트<a href="https://msdn.microsoft.com/library/azure/dn133795.aspx">에</a> 안전하게 연결할 수 있습니다.또한 App Service Environment를 업스트림 어플라이언스, 방화벽 및 네트워크 SaaS 공급자 뒤에서 보호하도록 합니다.


  App Service Environment에서 실행되는 앱에는 최대 50개(50개) 컴퓨팅 인스턴스 및 새 P4 컴퓨팅 리소스에서 실행하는 기능을 포함하여 더 많은 크기 조정 옵션도 있습니다.


  고객은 <a href="https://portal.azure.com">포털</a>의 만들기 메뉴에서 App Service Environment를 빠르게 시작할 수 있습니다.


  <a href="https://acom.azurecomcdn.net/80C57D/blogmedia/blogmedia/2015/04/24/web-portal.png"><img style="background-image: none; float: none; padding-top: 0px; padding-left: 0px; margin-left: auto; display: block; padding-right: 0px; margin-right: auto; border: 0px;" title="웹 포털" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/web-portal_thumb.png" alt="web portal" width="264" height="610" border="0" /></a>


  App Service Environment를 만드는 동안 가상 네트워크 및 크기 조정 구성에 대한 기본 선택이 이루어집니다.아래 예제에서는 기본 구성을 사용하여 <i>expenseapps</i> 라는 App Service Environment를 만드는 방법을 보여 줍니다.


  <a href="https://acom.azurecomcdn.net/80C57D/blogmedia/blogmedia/2015/04/24/App-Service-Enviornment.png"><img style="background-image: none; float: none; padding-top: 0px; padding-left: 0px; margin-left: auto; display: block; padding-right: 0px; margin-right: auto; border: 0px;" title="App Service Enviornment" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/App-Service-Enviornment_thumb.png" alt="App Service Enviornment" width="298" height="609" border="0" /></a>


  App Service Environment가 만들어지면 새 앱을 쉽게 구성할 수 있습니다.다음은 <i>expenseapps</i> App Service Environment에서 새 앱(<i>모바일 expenseapp</i>)을 만들기 위한 포털 환경을 보여 줍니다. 위치 선택에서 <i>앱이 expenseapps</i> App Service Environment에서 생성됨을 나타내는 방법을 확인합니다.


  <a href="https://acom.azurecomcdn.net/80C57D/blogmedia/blogmedia/2015/04/24/WebApp.png"><img style="background-image: none; float: none; padding-top: 0px; padding-left: 0px; margin-left: auto; display: block; padding-right: 0px; margin-right: auto; border: 0px;" title="WebApp" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/WebApp_thumb.png" alt="WebApp" width="298" height="610" border="0" /></a>


  App Service Environment 내에서 <i>실행되는 모바일 expenseapp </i>을 사용하면 이제 동일한 가상 네트워크에 연결된 내부 회사 리소스에 액세스할 수 있습니다.업스트림 서비스 및 방화벽에서만 액세스를 허용하도록 앱을 보호 할 수도 있습니다.

  <h2>시작하기</h2>

  App Service Environment는 오늘부터 미리 보기로 제공됩니다.App Service Environment 옵션은 <a href="https://azure.microsoft.com/blog/2015/03/30/azure-app-service-premium-tier/">Azure App Service Premium 계층</a>의 일부이며, 제한된 시간 동안 Premium 계층 가격은 기존 표준 계층 가격 책정에서 사용할 수 있습니다.시작에 대한 도움말  <a href="https://go.microsoft.com/fwlink/?LinkID=532956">은 App Service Environment란?</a> 및 <a href="https://go.microsoft.com/fwlink/?LinkId=534235">App Service Environment를 만드는 방법을 참조하세요</a>.

  <h2>추가 리소스</h2>

  App Service Environment를 만들고 작업하고 App Service Environment와의 네트워크 통신을 보호하는 방법에 대한 자세한 내용은 다음 설명서에서 App Service Environment를 자세히 살펴보세요.

  <ul>
   <li><a href="https://go.microsoft.com/fwlink/?LinkId=534235">App Service Environment를 만드는 방법</a></li>
   <li><a href="https://go.microsoft.com/fwlink/?LinkId=534233">App Service Environment에서 웹앱을 만드는 방법</a></li>
   <li><a href="https://go.microsoft.com/fwlink/?LinkID=532960">App Service Environment에서 웹앱 크기를 조정하는 방법</a></li>
   <li><a href="https://go.microsoft.com/fwlink/?LinkID=532962">App Service Environment를 구성하는 방법</a></li>
   <li><a href="https://go.microsoft.com/fwlink/?LinkID=532969">App Service Environment에 대한 인바운드 트래픽을 보호하는 방법</a></li>
   <li><a href="https://go.microsoft.com/fwlink/?LinkID=532970">App Service Environment에서 백 엔드 리소스에 안전하게 커넥트 방법</a></li>
  </ul>
