### YamlMime:Yaml
ms.openlocfilehash: d6c98964df71e57d90c59d1608b7b90858d9602c
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139910964"
Slug: irap-protected-compliance-from-infra-to-sap-application-layer-on-azure
Title: AZURE의 인프라에서 SAP 애플리케이션 계층으로 IRAP 보호 규정 준수
Summary: 호주 정부 조직은 호주 ASD(Signals Directorate)에서 생성된 호주 정부 정보 보안 매뉴얼(ISM)의 목표를 준수하는 AU-PROTECTED 정부 데이터의 처리, 스토리지 및 전송에 적합한 PaaS(Platform as a Service) 환경의 배포를 제공할 수 있는 클라우드 관리 서비스 공급자를 찾고 있습니다.
Content: >-
  <p><em>이 게시물은 로히트 쿠마르 체루쿠리, 판카즈 바다야, 비넷 불불레프&nbsp;롬 Cloud4C가 공동 저술했습니다.</em></p>


  <p>호주 정부 조직은 <a href="https://asd.gov.au/">호주 ASD(Signals Directorate)</a>에서 생성된 호주 정부 정보 보안 매뉴얼(ISM)의 목표를 준수하는 AU-PROTECTED 정부 데이터의 처리, 스토리지 및 전송에 적합한 PaaS(Platform as a Service) 환경을 배포할 수 있는 클라우드 관리 서비스 공급자를 찾고 있습니다.</p>


  <p>국가의 재정을 개선하고 유지하는 호주&rsquo; 최대의 연방 기관 중 하나는 중요한 정보를 보호하고 전송, 저장 및 검색과 관련된 보안 제어를 보장하는 데 중요한 정보 보안 등록 평가자 프로그램 (IRAP)을 구현하려고했습니다.</p>


  <p>정보 보안 등록 평가자 프로그램은 고품질 ICT(정보 및 통신 기술) 보안 평가 서비스를 정부에 제공하는 호주 신호 디렉토리 이니셔티브입니다.</p>


  <p>오스트레일리아 신호 디렉토리는 적절한 자격을 갖춘 정보 및 통신 기술 전문가를 보증하여 광범위한 산업 및 호주 정부 정보 및 관련 시스템을 보호하는 것을 목표로 하는 관련 보안 서비스를 제공합니다.</p>


  <p>Cloud4C는 클라우드 배달 플랫폼에서 이 연방 클라이언트를 사용하도록 설정하기 위해 이 문제를 해결했습니다. Cloud4C는 정보 보안 등록 평가자 프로그램 지침 내에서 엄격한 규정 준수 요구 사항을 분석하고 평가했습니다.</p>


  <p>내부 기준선에 따라 Cloud4C는 전체 평가를 물리적, 인프라 및 관리되는 서비스의 세 가지 &ndash; 범주로 나눕니다. 정보 보안 등록 평가자 프로그램에는 이러한 세 가지 특정 영역에 대한 엄격한 보안 제어가 있습니다.</p>


  <p>Cloud4C는 이 과제를 성공적으로 충족하는 가장 좋은 방법은 함께 황당하지만 성공적이고 가치 있는 평가를 달성하기 위한 책임을 파트너로 공유하고 공유하는 것임을 깨달았습니다. 2018년 4월, 호주 사이버 보안 센터(ACSC)는 <a href="https://www.microsoft.com/en-us/trustcenter/compliance/ccsl">PROTECTED 분류에서 Azure 및 Office 365 인증을 발표했습니다</a>. Microsoft는 이 수준의 인증을 달성한 최초의 유일한 퍼블릭 클라우드 공급자가 되었습니다. Cloud4C는 Microsoft와 협력하여 AZURE에 SAP 애플리케이션 및 SAP HANA 데이터베이스를 배포하고 모든 정보 보안 등록 평가자 프로그램 호환 인프라 혜택을 활용하여 Azure에서 네이티브 및 마켓플레이스 도구 및 기술을 원활하게 통합할 수 있도록 했습니다.</p>


  <p>Cloud4C는 물리적 보안 및 정보 및 통신 장비 배치에 대해 매우 엄격한 정보 보안 등록 평가자 프로그램 평가를 거친 오스트레일리아, 오스트레일리아 중부 및 오스트레일리아 중부 2에 적합한 Azure 데이터 센터를 확인했습니다.</p>


  <p>인프라 및 재해 복구를 위한 Azure의 이러한 규정 준수로 Cloud4C는 클라우드 서비스 공급자에게만 초점을 맞춘 나머지 대부분의 제어를 해결하기 위해 에너지를 집중시키는 관리 서비스 공급자로서 엄청난 시작을 했습니다.</p>


  <p>Cloud4C에 대한 정보 보안 등록 평가자 프로그램 평가에는 Azure 재해 복구에서 해결된 제어를 수행한 후 22개 주요 범주에 분산된 412개의 높은 위험과 19가지 가장 중요한 보안 측면을 충족하는 것이 포함되었습니다.</p>


  <p><there 22="" a="" amount="" and="" by="" challenge="" cloud4c="" controls="" diligently="" expertise="" maturity="" meeting="" needed="" of="" p="" significant="" staff="" that="" the="" this="" towards="" were="" who="" worked=""> </there></p>


  <h2>솔루션 개요</h2>


  <p>참여 범위는 분류된 정보의 처리, 스토리지 및 검색을 위해 정보 보안 등록 평가자 프로그램 보호 분류 표준을 유지하면서 SAP 기준 계층까지 관리되는 서비스를 사용하여 Azure에 SAP 환경을 구성하고 관리하는 것이었습니다. 참여 모델이 PaaS이므로 책임 매트릭스는 SAP 기준 계층에 달려 있으며 애플리케이션 관리 서비스는 이 계약의 범위를 벗어났습니다.</p>


  <h3>단일 서비스 수준 계약 및 정보 보안 등록 평가자 프로그램 보호 분류를 사용하는 Platform as a Service</h3>


  <p>제안된 솔루션에는 SAP HANA, SAP MaxDB 및 이전 Sybase 데이터베이스를 비롯한 여러 데이터베이스가 혼합된 SAP ERP, SAP BW, SAP CRM, SAP GRC, SAP IDM, SAP Portal, SAP Solution Manager, Web Dispatcher 및 Cloud Connector를 비롯한 다양한 SAP 솔루션이 포함되었습니다. 기본 재해 복구인 Azure 오스트레일리아 중부 및 보조 재해 복구 지역인 오스트레일리아 중부 2는 정보 보안 등록 평가자 프로그램 보호 준수 환경을 빌드하기 위한 물리적 재해 복구 위치로 확인되었습니다. 제안된 아키텍처에는 SAP 워크로드에 대한 인증된 SKU(가상 머신 재고 유지 단위), 최적화된 스토리지 및 디스크 구성, 적절한 보호를 사용하는 올바른 네트워크 SKU, 고가용성, 재해 복구, 백업 및 모니터링을 달성하는 메커니즘, 네이티브 및 외부 보안 도구의 적절한 조합, 그리고 가장 중요한 것은 서비스 제공과 관련된 프로세스 및 지침이 포함됩니다.</p>


  <p>다음 Azure 서비스는 제안된 아키텍처의 일부로 간주되었습니다.</p>


  <ul>
   <li>Azure 가용성 집합</li>
   <li>Azure Active Directory</li>
   <li>Azure Privileged Identity Management</li>
   <li>Azure Multi-Factor Authentication</li>
   <li>Azure ExpressRoute 게이트웨이</li>
   <li>웹 애플리케이션 방화벽이 있는 Azure 애플리케이션 게이트웨이</li>
   <li>Azure Load Balancer</li>
   <li>Azure Monitor</li>
   <li>Azure Resource Manager</li>
   <li>Azure Security Center</li>
   <li>Azure Storage 및 디스크 암호화</li>
   <li>Azure DDoS Protection</li>
   <li>Azure Virtual Machines(SAP 애플리케이션 및 SAP HANA 데이터베이스용 인증된 가상 머신)</li>
   <li>Azure Virtual Network</li>
   <li>Azure Network Watcher</li>
   <li>네트워크 보안 그룹</li>
  </ul>


  <h3>정보 보안 등록 평가자 프로그램 규정 준수 및 평가 프로세스</h3>


  <p>Cloud4C는 호주 정부 보안을 이해하고 구현하고 SAP 애플리케이션 및 SAP HANA 데이터베이스를 Azure 보호 클라우드의 정보 보안 등록 평가자 프로그램 보호 설정으로 이식하는 기술적 타당성을 구축하는 데 도움을 준 정보 보안 등록 평가자 프로그램 평가자의 도움을 받아 인증 프레임워크를 탐색했습니다.</p>


  <p>정보 보안 등록 평가자 프로그램 평가자는 시스템&#39;보안 제어의 구현, 적합성 및 효율성을 평가했습니다. 이 작업은 <a href="https://acsc.gov.au/infosec/ism/index.htm">ISM(호주 정부 정보 보안 매뉴얼)</a>에 설명된 대로 두 가지 보안 평가 단계를 통해 수행되었습니다.</p>


  <ul>
   <li>1단계<b></b>: 보안 평가는 시스템 소유자가 수정하거나 완화하는 보안 결함을 식별합니다.</li>
   <li>2단계: 보안 평가에서 잔차 규정 준수 평가</li>
  </ul>


  <p>Cloud4C는 모든 적용 가능한 정보 보안 수동 제어 하에서 성공적인 평가를 달성하여 위험 환경이 0이 되도록 하고 Microsoft의 지원을 통해 중요한 정보 시스템을 보호합니다.</p>


  <p>Microsoft 팀은 Azure 네이티브 도구를 활용하여 규정 준수를 달성하는 방법에 대한 모범 사례에 대한 지침을 제공했습니다. Microsoft 솔루션 설계자 및 엔지니어링 팀은 설계 토론에 참여하여 Azure 네이티브 보안 도구, 타사 보안 도구에 대한 통합 시나리오 및 아키텍처의 가능한 최적화에 관한 기존 기술 자료를 가져왔습니다.</p>


  <p>평가 중에 Cloud4C 및 Information Security 등록 평가자 프로그램 평가자는 다음 작업을 수행했습니다.</p>


  <ul>
   <li>전체 통신과 관련된 모든 구성 요소 및 관련자를 통합하는 시스템 아키텍처 설계</li>
   <li>오스트레일리아 정부 보안 정책에 대한 매핑된 보안 규정 준수</li>
   <li>정보 보안 등록 평가자 프로그램에서 인증한 Azure 데이터 센터 오스트레일리아 중부 및 오스트레일리아 중부 2의 확인된 물리적 시설</li>
   <li>구현된 정보 보안 수동 보안 제어</li>
   <li>비준수에 대한 정의된 완화 전략</li>
   <li>시스템에 대한 위험을 식별하고 완화 전략을 정의했습니다.</li>
  </ul>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/ad41b64b-767c-4368-a245-c4e9857b66a3.png"><img alt="Placeholder" border="0" height="322" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/8e63d431-5515-4fde-b478-7bd3c7bc606f.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="643" width="640"></a></p>


  <h3>자동화 및 프로세스 개선을 보장하는 단계</h3>


  <ul>
   <li>도구와 결합된 ARM(Azure Resource Manager) 템플릿을 사용하여 빠른 배포 이는 한 달 이내에 100개 이상의 가상 머신과 10개의 SAP 솔루션으로 구성된 대규모 환경을 배포하는 데 도움이 됩니다.</li>
   <li>RPA(로봇 프로세스 자동화) 도구를 사용하여 자동화를 처리합니다. 이를 통해 정보 보안 등록 평가자 프로그램 환경에 배포된 SAP 에코 시스템 내에서 <em>비즈니스를 일반적인 </em>단계로 식별하고 애플리케이션 가용성을 보장하는 인프라 수준을 처리하는 자동화를 기반으로 실제 비즈니스 프로세스에 대한 최소한의 중단을 보장하는 프로세스를 향상시켰습니다.</li>
  </ul>


  <h3>프로세스 중에 구현된 학습 및 각 솔루션</h3>


  <ul>
   <li>Azure Central 및 Azure Central 2 지역은 서브-ms 대기 시간보다 짧은 파이버 링크를 통해 서로 연결되었으며, SAP 애플리케이션 및 SAP HANA 데이터베이스 복제는 동기 모드로, RPO(복구 지점 목표)는 0으로 달성되었습니다.</li>
   <li>Azure Active Directory Domain Services는 오스트레일리아 중부 지역에서 사용할 수 없으므로 Azure South-East 지역을 활용하여 원활한 제공을 보장했습니다.</li>
   <li>Azure Site Recovery는 SAP Max DB 데이터베이스의 복제에 성공적으로 사용되었습니다.</li>
   <li>Azure ExpressRoute를 통해 흐르는 트래픽은 기본적으로 암호화되지 않았으며 Microsoft 보안 파트너의 네트워크 가상 어플라이언스로 암호화되었습니다.</li>
  </ul>


  <p>정보 보안 등록 평가자 프로그램을 준수하려면 오스트레일리아 신호 디렉터리에서 정의한 자격을 충족하고 평가 단계를 통과해야 합니다. Cloud4C는 다음과 같은 이점을 제공했습니다.</p>


  <ul>
   <li>출시 시간 단축 - Cloud4C는 거의 1~2년의 업계 성과에 비해 9개월 만에 평가 프로세스를 완료했습니다.</li>
   <li>Cloud4Cs&rsquo; 환경 및 Azure에서 고객을 위한 여러 지역 및 업계별 규정 준수를 제공하는 지식은 Azure 네이티브 및 외부 보안 도구를 사용하여 올바른 컨트롤을 매핑하는 데 도움이 됩니다.</li>
  </ul>


  <p>Microsoft와의 파트너십을 통해 Cloud4C는 또 다른 이정표에 도달하고 Azure Hyperscaler가 엄격한 규정 및 지리적 규정 준수를 충족하기 위해 제공해야 하는 모든 보안 기능을 활용할 수 있습니다.</p>


  <p>Cloud4C는 Azure Native 및 Azure Marketplace에서 쉽게 사용할 수 있는 많은 보안 솔루션을 사용하여 출시 시간을 줄여 줍니다. Cloud4C는 고객&#39;인프라를 보호하고 클라이언트를 MSP(Azure Expert Managed Service Provider)로 지원하는 안전한 문화를 장려하는 측면에서 Azure 포트폴리오를 최대한 활용했습니다. Azure 보안 포트폴리오는 성장하고 있으며 Cloud4C는 솔루션 제품을 사용하는&#39;있습니다.</p>


  <p>Cloud4C와 Microsoft는 다양한 지역 및 산업 분야에 걸쳐 마켓플레이스의 고객에게 타의 추종을 불허하는 클라우드 환경을 제공하는 측면에서 이 파트너십을 훨씬 더 높은 높이로 끌어들일 계획입니다.</p>


  <h3>자세한 정보</h3>


  <ul>
   <li><a href="https://docs.microsoft.com/en-us/azure/security/fundamentals/services-technologies">Microsoft의 Azure 보안 솔루션</a></li>
   <li><a href="https://docs.microsoft.com/en-us/azure/#pivot=products">Azure 네이티브 제품</a></li>
   <li><a href="https://docs.microsoft.com/en-us/azure/cloud-solution-provider/migration/migration-from-on-premises-to-azure-csp">Azure로 워크로드 마이그레이션</a></li>
   <li><a href="https://www.cloud4c.com/azure-managed-services">Cloud4C Azure Managed Services</a></li>
   <li><a href="https://www.cloud4c.com/azure-sap">Azure의 SAP용 Cloud4C 솔루션</a></li>
  </ul>
