### YamlMime:Yaml
ms.openlocfilehash: 62aaaa62e2bd9055375ed567d285a3b593e69f35
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139910959"
Slug: isolate-app-integrations-for-stability-scalability-and-speed-with-an-integration-service-environment
Title: 통합 서비스 환경을 사용하여 안정성, 확장성 및 속도를 위해 앱 통합 격리
Summary: 대규모 혁신은 대규모 조직이 직면한 일반적인 과제입니다. 과제의 주요 기여자는 수많은 앱과 환경을 조정하는 복잡성입니다.
Content: >-
  <p><a href="https://azure.microsoft.com/en-us/blog/connecting-the-colossal-how-to-scale-innovation-with-serverless-integration/" target="_blank">대규모 혁신</a> 은 대규모 조직이 직면한 일반적인 과제입니다. 과제의 주요 기여자는 수많은 앱과 환경을 조정하는 복잡성입니다.</p>


  <p><a href="https://azure.microsoft.com/en-us/services/logic-apps/" target="_blank">Azure Logic Apps</a> 같은 통합 도구를 사용하면 온-프레미스 또는 클라우드에서 원하는 만큼 빠르게 크기를 조정하고 혁신할 수 있습니다. 클라우드로 마이그레이션하거나 클라우드 네이티브로 마이그레이션할 때 또는 클라우드 네이티브로&#39;경우에도 이 기능이 필요합니다. 종종 통합은 사실 이후에 해야 할 일로 강등되었습니다. 그러나 최신 기업에서 애플리케이션 통합은 애플리케이션 개발 및 혁신과 함께 수행해야 하는 작업입니다.</p>


  <p>통합 서비스 환경은 시끄러운 인접 문제, 데이터 격리 또는 핵심 Logic Apps 서비스가 제공하는 것보다 더 많은 유연성과 구성이 필요한 조직에 이상적인 솔루션입니다.</p>


  <p>기존 기능 집합을 토대로 다음과 같은 통합 서비스 환경을 더욱 개선하도록 <a href="https://aka.ms/integrated-service-environment-azure-update" target="_blank">새롭고 흥미로운 다양한 변경 내용을</a> 릴리스하고 있습니다.</p>


  <ul>
      <li>이전 프로비전 시간을 절반으로 줄임으로써 더 빠른 배포 시간</li>
      <li>개별 논리 앱 및 커넥터에 대한 높은 처리량 제한</li>
      <li>이제 개별 논리 앱을 최대 1년(365일) 동안 실행할 수 있습니다.</li>
  </ul>


  <p>Logic Apps용 통합 서비스 환경은 핵심 애플리케이션 개발 전략의 일환으로 통합을 추구하는 조직을 위한 다음 단계입니다. 통합 서비스 환경에서 제공할 수 있는 항목은 다음과&rsquo; 같습니다.</p>


  <ul>
      <li><strong>가상 네트워크 리소스에 대한 직접 보안 액세스</strong>. Logic Apps는 Azure <a href="https://azure.microsoft.com/en-us/services/expressroute/" target="_blank">ExpressRoute</a> 또는 사이트 간 VPN을 통해 서비스 엔드포인트 및 온-프레미스 리소스가 있는 Azure 서비스를 포함하여 가상 네트워크의 가상 머신, 서버 및 기타 서비스와 같은 프라이빗 리소스에 안전하고 직접 액세스할 수 있도록 합니다.</li>
      <li><strong>일관되고 매우 신뢰할 수 있는 성능</strong>입니다. 시끄러운 인접 문제를 제거하여 Logic Apps만 실행되는 전용 런타임으로 비즈니스 중요 프로세스에 영향을 미칠 수 있는 일시적인 속도 저하에 대한 두려움을 제거합니다.</li>
      <li><strong>격리된 프라이빗 스토리지</strong>. 규정의 적용을 받는 중요한 데이터는 비공개로 안전하게 유지되어 새로운 통합 기회를 창출합니다.</li>
      <li><strong>예측 가능한 가격 책정</strong>. Logic Apps에 대한 고정 월별 비용을 제공합니다. 각 통합 서비스 환경에는 표준 통합 계정 1개와 엔터프라이즈 커넥터 1개의 무료 사용이 포함됩니다. Logic Apps 작업 실행 수가 매월 5천만 개 이상의 작업 실행을 초과하면 통합 서비스 환경이 더 나은 가치를 제공할 수 있습니다.</li>
  </ul>


  <p>Logic Apps에 대한 통합 서비스 환경이 새로운가요? 도움이 필요하면 이 <a href="https://www.youtube.com/watch?v=1EnNdpz3UM0&amp;feature=youtu.be" target="_blank">Azure Friday 소개 비디오를</a> 시청하세요.</p>


  <p>현재 <a href="https://docs.microsoft.com/en-us/azure/logic-apps/connect-virtual-network-vnet-isolated-environment-overview" target="_blank">Azure Logic Apps 통합 서비스 환경을</a> 시작합니다.</p>
