### YamlMime:Yaml
ms.openlocfilehash: 22cec21f1de3458ef364efb53c687a5bbd55034a
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139903213"
Slug: july-update-for-web-apps-and-app-service-environments-in-the-azure-preview-portal
Title: Azure 미리 보기 포털의 웹앱 및 App Service 환경에 대한 7월 업데이트
Summary: Azure 미리 보기 포털에서 웹앱 및 App Service 환경 환경에 주목할 만한 몇 가지 개선 사항을 롤아웃했습니다.
Content: >-
  지난 몇 주 동안 바빴습니다!Azure 미리 보기 포털에서 <strong>웹앱</strong> 및 <strong>App Service</strong> 환경 환경에 주목할 만한 몇 가지 개선 사항을 롤아웃했습니다.

  <h1>웹앱에 대한 새 만들기 환경</h1>

  <div id="attachment_323761" align="alignleft" width="1366"><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/July-001.png"><img class="size-full wp-image-323761" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/July-001.png" alt="New web App Create experience" width="1366" height="768" /></a> 새 웹앱 만들기 환경</div>


  웹앱 만들기 환경을 간소화하여 더 빠르고 훨씬 간단하게 만들었습니다. 이 새로운 환경을 통해 웹앱을 만드는 것은 이름을 제공하는 것만큼 간단합니다. 위치 및 가격 책정 계층과 같은 App Service 계획 속성은 논리적으로 그룹화되고 중요한 위치에 표시됩니다. 위치 및 인스턴스 수와 같은 웹앱에 적합한 App Service 계획을 선택하는 데 도움이 되는 관련 정보가 이제 컨텍스트에 표시됩니다.

  <h1>웹앱 리소스 블레이드 개선 사항</h1>

  다음 영역에서 웹앱 리소스 블레이드를 많이 개선했습니다.

  <h2>웹앱 블레이드 성능</h2>

  대부분의 릴리스 및 업데이트에는 성능 및 안정성 수정이 포함되며, 일반적으로 몇 초의 개선이 추가됩니다. 그러나 지난 몇 주 동안 웹앱 블레이드에 대한 성능 수정 사항을 강조했습니다. 이 특정 업데이트에서는 경험에서 전체 초를 면도할 수 있으므로 성능을 내보낼 수 있습니다. 이러한 향상된 기능은 더 나은 탐색, 보다 안정적인 리소스 블레이드 로드 및 더 나은 전반적인 환경으로 변환됩니다. 또한 새로운 성능 병목 현상 또는 회귀를 식별하고 사전에 해결할 수 있는 위치에서 원격 분석을 개선했습니다.

  <h2>App Service 계획 렌즈</h2>

  <div id="attachment_323771" align="alignleft" width="1366"><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/July-002.png"><img class="size-full wp-image-323771" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/July-002.png" alt="App Service plan lens" width="1366" height="768" /></a> App Service 계획 렌즈</div>


  많은 App Service 계획 개념이 "<strong>Usage Lens</strong>"의 웹앱 리소스 블레이드에 표시되어 혼동을 일으켰습니다. 웹앱 블레이드에서 이 렌즈의 이름을 "<strong>App Service 계획</strong>"으로 변경하여 해당 렌즈에 포함된 정보를 더 잘 나타냅니다. App Service 계획 렌즈에는 App Service 계획 블레이드를 여는 직접 링크도 포함되어 있습니다.

  <h2>새 도구 메뉴</h2>

  <div id="attachment_323781" align="alignleft" width="1366"><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/July-003.png"><img class="size-full wp-image-323781" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/July-003.png" alt="Web App Tools menu" width="1366" height="768" /></a> 웹앱 도구 메뉴</div>


  제공된 도구에 대한 빠른 액세스를 제공하는 방법으로 도구 <strong>메뉴를</strong> 작업 표시줄에 추가했습니다. <strong>문제 해결</strong> 및 <a title="리소스 탐색기" href="https://resources.azure.com" target="_blank"> 탐색<strong>기와</strong></a> 같은 이 메뉴의 많은 도구는 한동안 사용되어 왔지만 찾기가 쉽지 않았습니다.

  <h2>웹앱에 대한 새 Java 구성 옵션</h2>

  <div id="attachment_323801" align="alignleft" width="1366"><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/July-004.png"><img class="size-full wp-image-323801" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/July-004.png" alt="Web App Java configuration" width="1366" height="768" /></a> Web App Java 구성</div>


  Java 사용자는 <strong>컨테이너</strong>뿐만 아니라 <strong>주</strong>  버전과 <strong>부</strong> 버전을 구성할 수 있는 새 <strong>Java</strong> 버전 선택기를 활용할 수 있습니다.

  <h1>App Service Environment에 대한 업데이트</h1>

  <div id="attachment_323811" align="alignleft" width="1366"><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/July-005.png"><img class="size-full wp-image-323811" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/July-005.png" alt="App Service Environment metrics" width="1366" height="768" /></a> App Service Environment 메트릭</div>


  App <strong>Service Environment</strong> 리소스 블레이드에는 이제 작업자 풀에서 사용률을 모니터링할 수 있는 메트릭 그래프가 있습니다.


  또한 이제 많은 고객이 요청한 대로 더 작은 <strong>서브넷</strong> (8개의 IP 주소 또는 /29 마스크)으로 App Service Environment를 만들 수 있습니다.
