### YamlMime:Yaml
ms.openlocfilehash: 9fd305c911e049a2a161c645477531a173933041
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139905495"
Slug: keeping-your-environment-secure-with-update-management
Title: 업데이트 관리를 사용하여 환경 보안 유지
Summary: 업데이트 관리를 사용하면 머신에 대한 업데이트 및 패치를 관리할 수 있습니다.  업데이트 관리를 사용하면 사용 가능한 업데이트의 상태를 신속하게 평가하고, 필요한 업데이트의 설치를 예약하고, 배포 결과를 검토하여 업데이트가 성공적으로 적용되는지 확인할 수 있습니다. 머신이 Azure VM, AWS VM, 다른 클라우드 공급자가 호스트하는 또는 온-프레미스인지에 관계없이 가능합니다.
Content: >-
  <p>Azure 업데이트 관리 서비스는 <a href="https://azure.microsoft.com/en-us/pricing/details/automation/">Azure 구독의 일부로 포함됩니다</a>. 업데이트 관리를 사용하면 머신에 대한 업데이트 및 패치를 관리할 수 있습니다. 업데이트 관리를 사용하면 사용 가능한 업데이트의 상태를 신속하게 평가하고, 필요한 업데이트의 설치를 예약하고, 배포 결과를 검토하여 성공적으로 적용되는 업데이트를 확인할 수 있습니다. 이는 머신이 Azure VM이든, 다른 클라우드 공급자가 호스트하든, 온-프레미스이든 간에 가능합니다.</p>


  <p>업데이트 관리를 사용하려면 몇 가지 필수 구성 요소를 처리해야 합니다. Azure VM이 이미 있는 경우 이 프로세스는 간단합니다.</p>


  <ol>

  </ol>


  <p>VM으로 이동하고 왼쪽 메뉴에서 <strong>업데이트 관리를</strong> 선택합니다.</p>


  <ol>

  </ol>


  <p>다음 화면에서<strong> 사용</strong> 단추를 클릭합니다. 기본값을 사용하여 로그 분석 작업 영역 및 Automation 계정을 만듭니다. 기존 작업 영역 또는 Automation 계정이 있는 경우 해당 계정도 선택할 수 있습니다.</p>


  <ol>

  </ol>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/26d65595-12c6-4d59-a132-caf71433517e.png"><img alt="2_configure" border="0" height="464" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/d9110880-6110-4389-9da5-d9966aff3309.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="2_configure" width="1110"></a></p>


  <p>이 작업이 완료되면 업데이트 관리 보기가 표시됩니다. 데이터가 채워지는 데는 다소 시간이 걸리지만 이 보기는 단일 VM에 대한 정보를 제공합니다. <strong>여러 컴퓨터 관리를</strong> 클릭하여 액세스할 수 있는 다중 컴퓨터 보기도 있습니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/229786e8-0d98-449b-b274-a13bbf2ad8a2.png"><img alt="3_multi" border="0" height="879" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/8c95a597-33a3-424f-90e9-1f1ef2aaab01.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="3_multi" width="1029"></a></p>


  <p><strong>Azure VM 추가 또는 비 Azure</strong> <strong>컴퓨터 추가</strong>를 선택하여 이 보기에서 더 많은 컴퓨터를 쉽게 추가할 수 있습니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/1ea1207c-bf7e-4a66-b327-c41571dac683.png"><img alt="4_multi (1)" border="0" height="594" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/7a191042-1d4c-4cf1-9e23-d5bc63b40982.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="4_multi (1)" width="958"></a></p>


  <h2>업데이트 관리를 사용하여 업데이트 준수에 대한 가시성 가져오기</h2>


  <p><a href="https://aka.ms/winvmupdate">업데이트 관리에서 컴퓨터를 등록하면 컴퓨터</a> 상태에 대해 보고하는 대시보드에 액세스할 수 있습니다. 머신이 Azure VM, AWS VM, 다른 클라우드 공급자 또는 온-프레미스인지에 관계없이 가능합니다.</p>


  <h2>보안 업데이트 배포</h2>


  <p>컴퓨터에 패치를 배포하려면 다중 머신 보기에서 <strong>업데이트 배포 예약을 선택합니다</strong> .</p>


  <p><img alt="" border="0" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/5_schedule-1.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;"></p>


  <p>&nbsp;</p>


  <p>그러면 새 블레이드가 표시됩니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/8f3fa92a-394e-47a9-9442-e2e8da044502.png"><img alt="6_deploy" border="0" height="881" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/08f3ca21-a853-4be2-9c05-27f4181ff122.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="6_deploy" width="317"></a></p>


  <p>이 블레이드에서 업데이트를 받아야 하는 컴퓨터를 선택할 수 있습니다. 원하는 경우 <strong>업데이트 분류를</strong> 필터링하여 보안 업데이트만 적용할 수 있습니다. 업데이트 실행은 한 번 또는 반복적으로 실행되도록 예약할 수 있습니다. 유지 관리 기간은 컴퓨터에서 업데이트 프로세스를 실행할 수 있는 기간을 정의합니다.</p>


  <p>자세한 내용은 <a href="https://docs.microsoft.com/en-us/azure/automation/manage-update-multi#schedule-an-update-deployment">업데이트 배포 예약</a> 및 <a href="https://docs.microsoft.com/en-us/azure/automation/automation-tutorial-update-management">업데이트 관리 자습서</a>를 참조하세요.</p>
