### YamlMime:Yaml
ms.openlocfilehash: 49e4951f2bd5fd7f1f17b2ec49184f4cda6450ae
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139906715"
Slug: leveraging-complex-data-to-build-advanced-search-applications-with-azure-search
Title: 복잡한 데이터를 활용하여 Azure Search를 사용하여 고급 검색 애플리케이션 빌드
Summary: 데이터는 거의 간단하지 않습니다.  모든 데이터가 행과 열의 단일 Excel 워크시트에 잘 맞을 수 있는 것은 아닙니다.  데이터에는 단일 고객 또는 여러 저자 및 단일 책의 장르에 대한 여러 위치 및 전화 번호와 같은 다양한 관계가 있습니다.
Content: >-
  <p>데이터는 거의 간단하지 않습니다. 모든 데이터가 행과 열의 단일 Excel 워크시트에 잘 맞을 수 있는 것은 아닙니다. 데이터에는 단일 고객 또는 여러 저자 및 단일 책의 장르에 대한 여러 위치 및 전화 번호와 같은 다양한 관계가 있습니다. 물론 관계는 일반적으로 이보다 훨씬 더 복잡하며, AI를 활용하여 데이터를 이해하기 시작하면 관계의 복잡성에 추가되는 추가 학습이 추가됩니다. 이러한 이유로 고객이 데이터를 검색하고 탐색할 수 있도록 데이터를 평면화해야 한다고 기대하는 것은 종종 비현실적입니다. 우리는 이것을 자주 들었으며 빠르게 <a href="https://feedback.azure.com/forums/263029-azure-search/suggestions/6670910-modelling-complex-types-in-indexes" target="_blank">가장 많이 요청된 Azure Search 기능 중 하나가</a> 되었습니다. 이 때문에 Azure Search에서 복잡한 형식 지원의 일반 공급에 대해 발표하게 되어 기뻤습니다. 이 게시물에서는 Azure Search에 추가되는 복잡한 형식과 이 기능을 사용하여 빌드할 수 있는 항목의 종류를 설명하는 데 약간의 시간이 걸립니다.&nbsp;</p>


  <p>Azure Search는 개발자가 자체 클라우드 검색 솔루션을 만드는 데 도움이 되는 서비스로서의 플랫폼입니다.</p>


  <h2>복잡한 데이터가란?</h2>


  <p>복잡한 데이터는 테이블 형식 행 집합으로 깔끔하게 세분화되지 않는 계층 구조 또는 중첩된 하위 구조를 포함하는 데이터로 구성됩니다. 예를 들어 각 작성자가 여러 특성을 가질 수 있는 여러 작성자가 있는 책은 저자를 개체 컬렉션으로 모델링하는 방법이 없다면 단일 데이터 행으로 나타낼 수&rsquo; 없습니다. 복합 형식은 이 기능을 제공하며 문자열 또는 정수와 같은 단순 필드 구조에서 데이터를 모델링할 수 없는 경우에 사용할 수 있습니다.</p>


  <h2>복합 형식 적용 가능성</h2>


  <p>Microsoft Build 2019&nbsp; 에서는 복잡한 형식을 활용하여 <a href="https://mybuild.techcommunity.microsoft.com/sessions/76964?source=sessions">효과적인 검색 애플리케이션을 빌드</a>하는 방법을 설명했습니다. 세션에서는 StackExchange에서 지원하는 많은 온라인 커뮤니티 중 하나인 Travel Stack Exchange 사이트를 살펴보았습니다.</p>


  <p>StackExchange 데이터는 Azure Search로 쉽게 수집할 수 있도록 JSON 구조로 모델링되었습니다. 이 사이트에 대한 첫 번째 게시물을 살펴보고 처음 몇 개의 필드에 초점을 맞추면 <a href="https://docs.microsoft.com/en-us/rest/api/searchservice/supported-data-types">컬렉션</a>으로 모델링할 수 있는 태그 또는 문자열 배열을 포함하여 간단한 데이터 형식을 사용하여 모든 필드를 모델링할 수 있습니다.</p>


  <pre>

  {
     &quot;id&quot;: &quot;1&quot;,
      &quot;CreationDate&quot;: &quot;2011-06-21T20:19:34.73&quot;,
      &quot;Score&quot;: 8,
      &quot;ViewCount&quot;: 462,
      &quot;BodyHTML&quot;: &quot;&lt;p&gt;My fianc&eacute;e and I are looking for a good Caribbean cruise in October and were wondering which
      &quot;Body&quot;: &quot;my fianc&eacute;e and i are looking for a good caribbean cruise in october and were wondering which islands
      &quot;OwnerUserId&quot;: 9,
      &quot;LastEditorUserId&quot;: 101,
      &quot;LastEditDate&quot;: &quot;2011-12-28T21:36:43.91&quot;,
      &quot;LastActivityDate&quot;: &quot;2012-05-24T14:52:14.76&quot;,
      &quot;Title&quot;: &quot;What are some Caribbean cruises for October?&quot;,
      &quot;Tags&quot;: [
          &quot;caribbean&quot;,
          &quot;cruising&quot;,
          &quot;vacations&quot;
      ],
      &quot;AnswerCount&quot;: 4,
      &quot;CommentCount&quot;: 4,
      &quot;CloseDate&quot;: &quot;0001-01-01T00:00:00&quot;,</pre>

  <p>그러나 이 데이터 세트를 자세히 살펴보면 데이터가 더 복잡해지고 플랫 구조로 매핑할 수 없다는 것을 알 수 있습니다. 예를 들어 단일 문서와 관련된 수많은 주석과 답변이 있을 수 있습니다.&nbsp; 여기에서 투표도 복잡한 형식으로 정의됩니다(기술적으로는 평면화될 수 있지만 데이터를 변환하는 작업이 추가됨).</p>


  <pre>

  &quot;CloseDate&quot;: &quot;0001-01-01T00:00:00&quot;,
      &quot;Comments&quot;: [
          {
              &quot;Score&quot;: 0,
              &quot;Text&quot;: &quot;To help with the cruise line question: Where are you located? My wife and I live in New Orlea
              &quot;CreationDate&quot;: &quot;2011-06-21T20:25:14.257&quot;,
             &quot;UserId&quot;: 12
          },
          {
              &quot;Score&quot;: 0,
              &quot;Text&quot;: &quot;Toronto, Ontario. We can fly out of anywhere though.&quot;,
              &quot;CreationDate&quot;: &quot;2011-06-21T20:27:35.3&quot;,
              &quot;UserId&quot;: 9
          },
          {
              &quot;Score&quot;: 3,
              &quot;Text&quot;: &quot;\&quot;Best\&quot; for what?  Please read [this page](
              &quot;UserId&quot;: 20
          },
          {
              &quot;Score&quot;: 2,
              &quot;Text&quot;: &quot;What do you want out of a cruise? To relax on a boat? To visit islands? Culture? Adventure?
              &quot;CreationDate&quot;: &quot;2011-06-24T05:07:16.643&quot;,
              &quot;UserId&quot;: 65
          }
      ],
      &quot;Votes&quot;: {
          &quot;UpVotes&quot;: 10,
          &quot;DownVotes&quot;: 2
      },
      &quot;Answers&quot;: [
          {
              &quot;IsAcceptedAnswer&quot;: &quot;True&quot;,
              &quot;Body&quot;: &quot;This is less than an answer, but more than a comment&hellip;\n\nA large percentage of your travel b
              &quot;Score&quot;: 7,
              &quot;CreationDate&quot;: &quot;2011-06-24T05:12:01.133&quot;,
              &quot;OwnerUserId&quot;: 74</pre>

  <p>이 모든 데이터는 검색 환경에 중요합니다. 예를 들어, 다음을 수행합니다.</p>


  <ul>
      <li>원래 질문뿐만 아니라 주석에서도 구를 <a href="https://docs.microsoft.com/rest/api/searchservice/search-documents" target="_blank">검색하고 강조</a> 표시합니다.</li>
      <li><a href="https://docs.microsoft.com/azure/search/search-filters" target="_blank">문서</a>&nbsp; 제한 특정 사용자가 답변을 제공한 사용자에 대한 것입니다.</li>
      <li><a href="https://docs.microsoft.com/azure/search/index-add-scoring-profiles" target="_blank">특정 문서</a>&nbsp; 승격 높은 개수의 득표가 있는 경우 검색 결과에서 더 높습니다.</li>
  </ul>


  <p>실제로 Cognitive <a href="https://azure.microsoft.com/en-us/blog/announcing-cognitive-search-azure-search-cognitive-capabilities/" target="_blank">Search</a> 를 활용하여 답변에서 핵심 구를 추출하여 검색 상자의 사용자 유형으로 <a href="https://docs.microsoft.com/rest/api/searchservice/autocomplete" target="_blank">자동 완성</a> 에 대한 잠재적 구를 제공하여 기존 StackExchange 검색 인터페이스를 개선할 수도 있습니다.</p>


  <p>이제 이 데이터를 복잡한 구조에 매핑할 수 있는 것뿐만 아니라 검색 쿼리가 향상된 구조를 지원하여 더 나은 검색 환경을 구축할 수 있기 때문에 이 모든 것이 가능합니다.</p>


  <h2>다음 단계</h2>


  <p>Azure Search 복합 형식에 대해 자세히 알아보려면 <a href="https://docs.microsoft.com/azure/search/search-howto-complex-data-types" target="_blank">설명서를</a> 방문하거나 이 Travel StackExchange 데이터를 자세히 살펴보는 <a href="https://mybuild.techcommunity.microsoft.com/sessions/76964?source=sessions" target="_blank">비디오 및 관련</a> <a href="https://github.com/liamca/build2019aidemos" target="_blank">코드를</a> 확인하세요.</p>
