### YamlMime:Yaml
ms.openlocfilehash: 15ba3e285e80a2e16048de720c0732554e9f8e34
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139901117"
Slug: line-of-business-application-hosted-in-azure-iaas
Title: Azure의 웹 기반 인트라넷 기간 업무 애플리케이션
Summary: Azure 인프라 서비스에서 다음 웹 기반 인트라넷 기간 업무 애플리케이션을 구성할 수 있습니다.
Content: >-
  <p>Azure 가상 머신과 Azure 크로스-프레미스 가상 네트워크의 조합을 사용하여 Azure에서 다음 웹 기반 인트라넷 기간 업무 애플리케이션을 배포할 수 있습니다.</p>


  <p>기본 프로세스는 다음과 같습니다.</p>


  <ol>
   <li>온-프레미스 개인 주소 공간의 일부를 사용하여 애플리케이션의 각 계층에 대해 여러 서브넷이 있는 Azure 가상 네트워크를 만듭니다.</li>
   <li>사이트-사이트 VPN 연결 또는 ExpressRoute를 사용하여 Azure 가상 네트워크를 온-프레미스 네트워크에 커넥트.</li>
   <li>LOB 애플리케이션의 각 계층에서 가상 머신에 대한 리소스 그룹, 가용성 집합, 스토리지 계정 및 부하 분산 장치를 만듭니다.</li>
   <li>LOB 애플리케이션에 대한 ID 및 인증에 사용되는 서버를 만들고 구성합니다.</li>
   <li>LOB 애플리케이션에 대한 데이터베이스 서버를 만들고 구성합니다.</li>
   <li>LOB 애플리케이션에 대한 웹 및 기타 서버를 만들고 구성합니다.</li>
  </ol>


  <p>사용 예는 다음과 같습니다.</p>


  <ul>
   <li>ID 및 인증을 위한 두 개의 AD(Windows Server Active Directory) 도메인 컨트롤러입니다.</li>
   <li>데이터베이스 계층에 대한 Windows Server 클러스터 및 SQL Server AlwaysOn 가용성 그룹입니다.</li>
   <li>들어오는 연결을 두 웹 서버에 분산하는 내부 부하 분산 장치입니다.</li>
  </ul>


  <p><a href="https://acom.azurecomcdn.net/80C57D/blogmedia/blogmedia/2015/08/24/Workload-lobapp-phase4.png"><img alt="Workload-lobapp-phase4" border="0" height="258" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/Workload-lobapp-phase4_thumb.png" style="border: 0px currentColor; border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; display: inline; background-image: none;" title="Workload-lobapp-phase4" width="640"></a>&nbsp;&nbsp;</p>


  <p>인트라넷 사용자에 대한 다른 관점 및 작동 방식에 대한 설명은 Business Applications <a href="https://msdn.microsoft.com/dn630664">아키텍처 청사진</a>을 참조하세요.</p>


  <p>&nbsp; <a href="https://acom.azurecomcdn.net/80C57D/blogmedia/blogmedia/2015/08/24/LOB_Arch_Blueprint.png"><img alt="LOB_Arch_Blueprint" border="0" height="476" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/LOB_Arch_Blueprint_thumb.png" style="border: 0px currentColor; border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; display: inline; background-image: none;" title="" width="640"></a> LOB_Arch_Blueprint &nbsp;</p>


  <p>다음을 빌드하는 <a href="https://azure.microsoft.com/documentation/articles/virtual-machines-windows-ps-hybrid-cloud-test-env-lob/">시뮬레이션된 하이브리드 클라우드 구성</a>에서 이를 테스트할 수도 있습니다.</p>


  <p><img src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/b421993c-1c3e-4050-b406-29421036caee.png"></p>
