### YamlMime:Yaml
ms.openlocfilehash: 9d33ff207c1c02aa7822552bec79b5649f756918
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139905850"
Slug: linux-on-azure-app-service-environment-now-generally-available
Title: 이제 Azure App Service Environment의 Linux를 일반 공급
Summary: Azure Virtual Network에서 Linux 또는 컨테이너화된 웹앱을 배포하는 데 관심이 있으신가요? Azure App Service 팀은 Azure App Service에서 Linux의 일반 공급에 대해 발표하게 되어 기쁩니다...
Content: >-
  <p>Azure Virtual Network에서 Linux 또는 컨테이너화된 웹앱을 배포하는 데 관심이 있으신가요? Azure App Service 팀은 <strong>Linux 및 App Service Environment의 App Service 기능을 결합한 ASE(Azure App Service Environment)에서 Linux의 일반 공급</strong>에 대해 발표하게 되어 기쁩니다. 공개 미리 보기 릴리스 시 발표된 대로 Linux 고객은 보안 네트워크 액세스 또는 대규모로 실행되는 앱을 위해 애플리케이션을 VNet에 배포하는 데 적합한 App Service Environment에서 Linux 및 컨테이너화된 앱을 배포하는 것을 활용할 수 있습니다.&nbsp;</p>


  <h2>ASE에서 Linux로 무엇을 할 수 있나요?</h2>


  <p>ASE의 Linux를 사용하면 사용자 고유의 사용자 지정 컨테이너를 가져와서 Linux 웹 애플리케이션을 Azure VNet(가상 네트워크)에 배포하거나 기본 제공 이미지 중 하나를 사용하여 코드를 가져올 수 있습니다.</p>


  <ul>
   <li>사용자 지정 Docker 컨테이너를 가져오려면 DockerHub, Azure Container Registry 또는 사용자 고유의 프라이빗 레지스트리에서 이미지를 가져올 수 있습니다.</li>
   <li>기본 제공 이미지 중 하나를 사용하려는 경우 노드, PHP, Java, .NET Core 등 많은 인기 있는 스택을 지원합니다.</li>
  </ul>


  <p>Windows, Linux 및 컨테이너화된 웹 애플리케이션을 동일한 ASE에 배포하여 동일한 VNet을 공유할 수 있습니다. Windows 및 Linux 웹앱이 동일한 App Service Environment에 있을 수 있지만 Windows 및 Linux 웹앱은 별도의 App Service 계획에 있어야 합니다. ASE의 Linux를 사용하면 Dv2 VM과 추가 크기 조정 기능(하나의 ASE에서 Windows Linux 간에 최대 <strong>100개의 총 App Service 계획 인스턴스</strong>)과 함께 격리된 SKU를 사용합니다.</p>


  <p>사용 사례에 가장 적합한 ASE 종류를 결정하려면 ASE에서 호스트되는 앱을 노출하는 데 사용할 IP 종류를 고려해야 합니다. 퍼블릭 또는 프라이빗인가요? 인터넷에 액세스할 수 있는 엔드포인트를 원하는지 여부에 따라 만들 수 있는 두 가지 종류의 ASE가 있습니다.</p>


  <ul>
   <li>인터넷에 액세스할 수 있는 엔드포인트가 있는 <em>외부 ASE</em> 입니다.</li>
   <li>ILB(내부 부하 분산 장치)가 있는 VNet의 개인 IP 주소가 있는 내부 <em>ASE</em> 입니다.</li>
  </ul>


  <p>설명서 페이지에서 <a href="https://docs.microsoft.com/en-us/azure/app-service/environment/create-external-ase" target="_blank">는 시작하는</a> 단계와 <a href="https://docs.microsoft.com/en-us/azure/app-service/environment/network-info" target="_blank">ASE에 대한 네트워킹을 구성하는 방법에</a> 대한 자세한 컨텍스트를 제공합니다.</p>


  <h2>미리 보기에서 가격 변경</h2>


  <p>App Service Environment에 배포된 Linux 및 컨테이너화된 앱은 Linux 및 App Service Environment 가격 책정에서 일반 App Service로 돌아갑니다. 공개 미리 보기에서 Linux App Service 계획에 대한 50% 할인은 일반 공급에 대해 제거되고 더 이상 제공되지 않습니다.</p>


  <h2>새 지역/국가가 추가됨</h2>


  <p>공개 미리 보기 이후 ASE의 Linux를 Linux&rsquo; 20개 이상의 지역/국가의 모든 App Service로 확장했습니다.</p>


  <table border="1" cellpadding="2">
   <tbody>
    <tr>
     <td valign="top">
     <ul>
      <li>오스트레일리아 동부</li>
      <li>오스트레일리아 남동부</li>
      <li>브라질 남부</li>
      <li>캐나다 중부</li>
      <li>캐나다 동부</li>
      <li>인도 중부</li>
      <li>미국 중부</li>
      <li>동아시아</li>
      <li>미국 동부</li>
     </ul>
     </td>
     <td valign="top">
     <ul>
      <li>미국 동부 2</li>
      <li>일본 동부</li>
      <li>일본 서부</li>
      <li>한국 중부</li>
      <li>한국 남부</li>
      <li>미국 중북부</li>
      <li>북유럽</li>
      <li>미국 중남부</li>
      <li>인도 남부</li>
     </ul>
     </td>
     <td valign="top">
     <ul>
      <li>동남아시아</li>
      <li>영국 남부</li>
      <li>영국 서부</li>
      <li>미국 중서부</li>
      <li>서유럽</li>
      <li>인도 서부</li>
      <li>미국 서부</li>
      <li>미국 서부 2</li>
     </ul>
     </td>
    </tr>
   </tbody>
  </table>


  <h2>시작하는 방법</h2>


  <p>새 웹앱을 만들고 LINux를 OS(기본 제공 이미지)로 선택하거나, Docker(사용자 지정 컨테이너)를 선택하거나, 새 Web App for Containers(사용자 지정 컨테이너)를 만들어 새 ASE로 Linux 웹앱을 만들 수 있습니다.</p>


  <p>자세한 지침이 필요한 경우 다음 지침에 따라 첫 번째 Linux/컨테이너화된 웹앱을 ASE로 만들기 시작 <a href="https://docs.microsoft.com/en-us/azure/app-service/environment/create-external-ase" target="_blank">합니다</a>.</p>


  <p>Wed&rsquo; love to hear you think! <a href="https://feedback.azure.com/forums/169385-web-apps?category_id=333220" target="_blank">Wed Apps 포럼</a>을 사용하여 ASE의 Linux에 대한 피드백을 남겨 주세요.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/1e60d802-c415-4e63-ade1-4d8d694ce097.png"><img alt="Getting started" border="0" height="827" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/15943a4b-f8f6-4c70-96eb-bf34bd0657f2.png" style="border: 0px currentcolor; border-image: none; display: inline; background-image: none;" title="시작" width="1128"></a></p>


  <p>App Service Environment의 Linux 일반 공급에 대한 일반적인 질문에 대한 답변은 이 <a href="https://aka.ms/linuxasega">블로그 게시물을</a> 확인하세요.</p>
