### YamlMime:Yaml
ms.openlocfilehash: 2eadef6176270e366f4c40ef9b22656ec1c00d21
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139902537"
Slug: log-alerts-for-application-insights-preview
Title: 애플리케이션 Insights 로그 경고 기능 미리 보기
Summary: 애플리케이션 Insights(미리 보기) 애플리케이션 Insights 대한 로그 경고는 여러 플랫폼에서 웹 개발자를 위한 확장 가능한 APM(애플리케이션 성능 관리) 서비스입니다.
Content: >-
  <p><em>이 블로그 게시물은 Azure 인프라 관리의 수석 PM 관리자인 Vijay Nagarajan, 선임 프로그램 관리자 및 Kiran Madnani가 공동 저술했습니다.</em></p>


  <h4>이 기능은 이제 일반 공급됩니다. Azure Portal 외에도 Azure CLI, PowerShell 및 Azure 리소스 관리자 템플릿에서 직접 또는 예약된 <a href="https://docs.microsoft.com/en-us/rest/api/monitor/scheduledqueryrules">쿼리 규칙 REST API</a> 를 호출할 수 있습니다( <a href="https://docs.microsoft.com/en-us/azure/monitoring-and-diagnostics/monitor-alerts-unified-log-template#managing-log-alert-on-application-insights">리소스 관리자를 사용하여 로그 경고 관리</a> 읽기). 가격 책정은 <a href="https://azure.microsoft.com/en-us/pricing/details/monitor/">Azure Monitor 가격 책정 페이지에서</a> 사용할 수 있습니다.</h4>


  <p>애플리케이션 Insights 여러 플랫폼에서 웹 개발자를 위한 확장 가능한 APM(애플리케이션 성능 관리) 서비스입니다. 고객은 애플리케이션 Insights 사용하여 라이브 웹 애플리케이션을 모니터링하고, 성능 이상을 감지하고, 문제를 진단하고, 사용 패턴을 이해합니다. 이제 다른 메트릭을 기반으로 하는 애플리케이션 상태에 대한 경고 외에도 지정된 간격으로 실행되도록 쿼리를 설정하고 결과에 따라 경고를 트리거하여 전자 로그 파일을 모니터링할 수 있습니다. 예를 들어 특정 예외에 대한 새 수정 사항을 배포하고 다시 표시되지 않도록&rsquo; 하려는 경우를 가정해 보겠습니다&rsquo;. 이제 애플리케이션 Insights 추적 파일에 예외가 나타나는 경우 트리거하도록 경고를 설정할 수 있습니다.</p>


  <p>새 Azure Alerts 환경에서 애플리케이션 Insights 대한 로그 <a href="https://portal.azure.com/?feature.customportal=false#blade/Microsoft_Azure_Monitoring/AzureMonitoringBrowseBlade/alertsV2">경고</a>에 액세스할 수 있습니다. <a href="https://azure.microsoft.com/en-us/blog/new-alerts-preview-in-azure-monitor/" target="_blank">Azure Alerts(미리 보기)에 대해 자세히 알아보세요</a>. 새 경고를 만들고 애플리케이션 Insights 대상 리소스를 지정합니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/8c721d8a-0b78-4e70-8ed8-656696d60116.png"><img alt="Alerts - Select Application Insights" border="0" height="889" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/b37b42ef-166f-453e-aa6e-e8f10f9dc8e8.png" style="border-width: 0px; padding-top: 0px; padding-right: 0px; padding-left: 0px; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="경고 - 애플리케이션 Insights 선택" width="527"></a></p>


  <p><br clear="all">

  Log Analytics 고객은 경고를 만들기 위한 친숙한 인터페이스를 찾을 수 있습니다. Log Analytics와 마찬가지로 로그 경고는 다음 두 가지 유형을 지원합니다.</p>


  <ul>
   <li><b><u>레코드 수</u></b>: Application Insights 쿼리에 대해 반환된 레코드 수에 따라 경고를 트리거합니다. 예: 웹앱이 500 응답을 제공할 때마다 경고를 원합니다. 쿼리를 사용하여 레코드 유형 수 및 임계값을 하나로 설정하는 로그 경고를 만듭니다 <i>. 요청 | where resultCode == &quot;500&quot;</i></li>
   <li><b><u>메트릭 측정</u></b>: 애플리케이션 Insights 쿼리에서 집계된 숫자 값의 패턴에 따라 경고를 트리거합니다. 예를 들어 지역 간 애플리케이션 Insights ping/가용성 테스트 기간이 2회 연속 15분 동안 평균적으로 매우 높은 경우 경고를 원합니다. 연속 위반에 대한 트리거가 두 개 이상인 형식 메트릭 측정의 로그 경고를 만들고 query를 사용하여 AggregateValue에서 집계를 만듭니다. <i>availabilityResults | summarize AggregatedValue = avg(duration) by bin(timestamp, 15m)</i></li>
  </ul>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/090fc8d7-b53c-4a69-8074-14f01d41cf39.png"><img alt="Alerts - Log Alerts - Application Insights (003)" border="0" height="889" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/3d252db9-78f3-4012-896a-4391064f4d5c.png" style="border: 0px currentColor; border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="경고 - 로그 경고 - 애플리케이션 Insights(003)" width="486"></a></p>


  <p><br clear="all">

  로그 경고에 대한 자세한 내용은 로그 경고에 <a href="https://docs.microsoft.com/en-us/azure/monitoring-and-diagnostics/monitor-alerts-unified-log">대한 Microsoft Azure 설명서</a>에서 찾을 수 있습니다. 다음은 애플리케이션용 로그 경고(미리 보기)를 시작하는 데 도움이 되는 짧은 비디오입니다.</p>


  <p style="text-align: center;"><iframe allowfullscreen="" frameborder="0" height="540" src="https://channel9.msdn.com/Blogs/Azure/Log-Alerts-for-Application-Insights-Preview/player" width="960"></iframe></p>


  <h6>애플리케이션 Insights 대한 로그 경고 및 새 경고 환경은 모두 미리 보기 상태이며 오늘부터 모든 지역에 예약된 방식으로 배포될 예정입니다. 귀하의 의견을 듣고 싶습니다. 다음으로 <a href="mailto:azurealertsfeedback@microsoft.com">azurealertsfeedback@microsoft.com</a>이메일을 보내 주세요.</h6>
