### YamlMime:Yaml
ms.openlocfilehash: fb3e045266cb67333be55056c09448688441bc53
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139902096"
Slug: managed-applications-are-now-generally-available-in-the-azure-marketplace
Title: 관리되는 애플리케이션은 이제 Azure Marketplace에서 일반 공급됩니다.
Summary: Azure Marketplace에서 관리되는 애플리케이션의 일반 공급에 대해 발표하게 되어 기쁩니다. Azure 고유 제품인 관리되는 애플리케이션을 사용하면 전체 애플리케이션을 배포하고 파트너가 사용자 환경에서 애플리케이션을 완전히 관리하고 유지 관리할 수 있도록 할 수 있습니다.
Content: >-
  <p>Azure Marketplace에서 관리되는 애플리케이션의 일반 공급에 대해 발표하게 되어 기쁩니다. Azure 고유 제품인 관리되는 애플리케이션을 사용하면 전체 애플리케이션을 배포하고 파트너가 사용자 환경에서 애플리케이션을 완전히 관리하고 유지 관리할 수 있도록 할 수 있습니다. 즉, Xcalar와 같은 파트너는 VM 집합에 배포하는 것 이상을 제공할 수 있습니다. Xcalar는 이제 Ap/Ops를 제공하는 &ldquo;애플리케이션과 완전히 작동하는 솔루션을 모두 제공할 수 있습니다.&rdquo; 또한 Xcalar와 같은 파트너는 Azure 환경에서 애플리케이션 솔루션을 직접 유지 관리하고 서비스합니다.</p>


  <p>파트너를 위한 이 새로운 배포 채널은 퍼블릭 클라우드에서 고객의 기대치를 변경합니다. 경쟁 업체와 달리 Azure에서 마켓플레이스 애플리케이션은 이제 배포 및 설정 그 이상이 될 수 있습니다. 이제 완전히 지원되고 관리되는 솔루션이 될 수 있습니다. 퍼블릭 클라우드의 첫 번째 클라우드입니다!</p>


  <p>사용자와 파트너는 Azure Managed Applications에 영감을 줍니다. IT 운영을 혁신하려는 많은 고객으로부터 모든 인프라 허브버브 없이 완전 관리형 애플리케이션의 단순함이 필요하다는 소식을 듣습니다. 또한 파트너는 포트폴리오에 서비스 운영을 추가하여 고객에게 더 많은 가치를 제공할 기회를 찾고 있습니다. 관리되는 애플리케이션을 사용하면 사용자와 파트너가 이러한 목표를 달성할 수 있습니다. 제품에 대한 몇 가지 세부 정보는 다음과 같습니다.</p>


  <ul>
      <li>MSP(관리 서비스 공급자), ISV(Independent Software Vendor) 및 SIS(시스템 통합자)는 Azure Resource Manager 템플릿을 사용하여 턴키 클라우드 솔루션을 빌드할 수 있습니다. 애플리케이션 IP와 기본 미리 구성된 Azure 인프라를 모두 봉인되고 서비스 가능한 솔루션으로 쉽게 패키지할 수 있습니다. 이렇게 하면 &ldquo;Ap/Ops가&rdquo; 애플리케이션과 작업을 하나의 패키지로 함께 제공할 수 있습니다.</li>
      <li>고객은 솔루션 수명 주기 동안 파트너가 완전히 작동하고 유지 관리하는 봉인된 서비스로 자체 Azure 구독에 이러한 턴키 솔루션을 배포할 수 있습니다. 또한 특히 봉인된 솔루션 및 해당 수명 주기 작업에 대해 최소한의 액세스 수준만 부여됩니다.</li>
      <li>그 결과 파트너에 의해 완벽하게 관리되는 고객에 대한 서비스 품질이 향상됩니다. 관리되는 애플리케이션의 봉인되고 변경할 수 없는 특성 덕분에 신뢰할 수 있는 파트너의 명시적 수명 주기 작업이 아니면 애플리케이션 또는 인프라 구성이 변경되지 않습니다.</li>
  </ul>


  <p>이러한 솔루션이 사용자 지정 빌드 및 유지 관리되는 MSP 또는 ISV에서 배달 및 서비스되는 패키지된 애플리케이션인 복잡한 애플리케이션이든 관계없이 다른&rsquo; 사용자 소프트웨어를 실행하는 것에 대해 크게 걱정할 필요 없이 비즈니스 변환을 가속화하기 위해 수행해야 할 일에 집중할 수 있습니다. 관리형 애플리케이션은 가장 진보된 애플리케이션 시나리오에서도 혁신을 가속화하여 최상의 서비스로서의 소프트웨어와 서비스로서의 인프라를 함께 제공합니다.</p>


  <p>Ignite에서 파트너는 <a href="https://azure.microsoft.com/en-us/blog/announcing-general-availability-of-azure-managed-applications-service-catalog/">고객 소유 엔터프라이즈 서비스 카탈로그 내에서 관리되는 애플리케이션을 배포하고 서비스할 수 있도록 했습니다</a>. 현재&rsquo; 배포 채널로 Azure Marketplace가 추가됨에 따라 파트너는 증분 고정 월 요금으로 수명 주기 및 지원 서비스를 추가하여 마켓플레이스 제품에 가치를 더할 수 있습니다. 우리의 출시 파트너는 흥분하고 갈 준비가되어 있습니다 ...</p>


  <blockquote>

  <p>&ldquo;Azure Managed Applications를 사용하면 OpsLogix 고객이 지속적인 유지 관리 및 서비스 복잡성을 수행하지 않고도 솔루션을 쉽게 배포하고 사용할 수 있습니다.&rdquo;<br>

  빈센트 드 브리스, CEO, OpsLogix</p>

  </blockquote>


  <blockquote>

  <p>&ldquo;Azure Managed Applications를 사용하면 Xcalar Data Platform이 더 높은 서비스 품질을 제공하고 고객과의 보다 강력한 파트너십을 구축하도록 도와줍니다. 이제 Enterprise 애플리케이션, Azure 클라우드 인프라 및 프로덕션 작업을 단일 솔루션으로 패키지할 수 있습니다.&rdquo;<br>

  비크람 조시 공동 창립자 겸 CEO, Xcalar</p>


  <p>&quot;&#39;Microsoft Azure 사용하는 고객에게 Cisco Meraki 클라우드 네트워킹의 힘과 단순성을 제공하게 되어 기쁩니다. 두 회사 모두 더 나은 IT에 대한 열정을 공유하고 강력한 자동 VPN 및 SD-WAN 기능을 활용하여 매일 사용하는 리소스에 사용자를 원활하게 연결할 수 있습니다.&quot;<br>

  Raviv Levi, 수석 제품 라인 관리자, 시스코 메라키</p>

  </blockquote>


  <p>가서 시도해 보세요. Azure Managed Applications 및 파트너 솔루션에 대한 귀하의 경험에 대해 여러분의 의견을 듣고 싶습니다. <a href="https://feedback.azure.com/forums/281804-azure-resource-manager">사용자 음성 채널</a> 또는 아래의 의견 섹션에 의견을 남겨 주세요.</p>


  <p>파트너에 대한 더 많은 혁신이 수평선에 있으므로 계속 지켜봐 주시기 바랍니다! 그리고, 이것이 어떻게 작동하는지에 대한 후드 아래 자세히 보기에 대한 <a href="https://azure.microsoft.com/en-us/blog/azure-managed-application-in-azure-marketplace-under-the-hood/">Gauravs&rsquo; 블로그</a> 를 확인하는 것을 잊지 마세요.</p>


  <p>주위를 둘러보십시오.</p>


  <p>코리 샌더스</p>
