### YamlMime:Yaml
ms.openlocfilehash: 4c95bd0341fed4aee37016837be6114264f5ee43
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139897619"
Slug: microsoft-creates-industry-standards-for-datacenter-hardware-storage-and-security
Title: Microsoft는 데이터 센터 하드웨어 스토리지 및 보안에 대한 업계 표준을 만듭니다.
Summary: 오늘 저는 산호세에서 열린 컴퓨팅 Project(OCP) 2018 미국 정상회담에서 SSD(반도체 디바이스) 스토리지에 대한 차세대 사양인 Project Denali를 발표합니다. 우리는 ...
Content: >-
  <p>오늘 Im&rsquo;은 우리가 반도체 상태 장치 (SSD) 스토리지에 대한 차세대 사양을 발표하는 산호세에서 오픈 컴퓨팅 Project (OCP) 미국 정상 회담 2018에서 연설, Project Denali. Were&rsquo;는 또한 현재까지 서버 하드웨어에서 누락된 보안 보호를 위한 중요한 구성 요소인 플랫폼 펌웨어에 대한 공격으로부터 보호, 검색 및 복구를 제공하는 Project Cerberus에 대해서도 논의합니다. 스토리지와 보안은 모두 하드웨어 혁신의 다음 분야이며, 오늘날&rsquo; 클라우드의 미래를 가능하게 하는 업계를 발전시키기 위해 이러한 주요 초점 영역의 최신 발전을 강조합니다.</p>


  <h2>클라우드 SSD 스토리지에 대한 새로운 표준</h2>


  <p>Storage 패러다임은 온-프레미스에서 잘 수행되었지만 클라우드 기반 모델에 필요한 성능 및 비용 효율성을 높이기 위한 혁신을 초래하지 않았습니다&rsquo;. 이러한 이유로 클라우드&rsquo; 기반 워크로드를 대상으로 하는 플래시 스토리지에 대한 새로운 표준을 정의하고, Im&rsquo;은 CNEX Labs를 통해 확립된 Project Denali&rsquo;를 공개하게 되어 기쁩니다. 기본적으로 Project Denali는 소프트웨어 정의 데이터 레이아웃 및 미디어 관리에 대한 기능을 세분화하여 SSD 펌웨어 인터페이스를 표준화합니다. Project Denali를 사용하면 고객은 클라우드 규모에서 발생하는 비용 절감 경제성을 활용하면서 더 높은 수준의 성능을 달성할 수 있습니다.</p>


  <p>Project Denali는 표준 인터페이스에서 호스트의 역할과 SSD의 역할을 정의하는 오픈 채널의 표준화 및 진화입니다. 미디어 관리, 오류 수정, 잘못된 블록 매핑 및 플래시 생성과 관련된 기타 기능은 호스트가 임의 쓰기를 수신하고, 순차 쓰기 스트림을 전송하고, 주소 맵을 유지 관리하고, 가비지 수집을 수행하는 동안 디바이스에 유지됩니다. Denali를 사용하면 호스트 쪽에서 FPGA 또는 마이크로 컨트롤러를 지원할 수 있습니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/08daac0d-48ac-43aa-82e4-0684566a1c6d.png"><img alt="Flash storage" border="0" height="459" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/fd5f521e-2047-4bfc-8721-2b489e03f6c6.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="플래시 스토리지" width="816"></a></p>


  <p>이는 진정한 클라우드 우선 아키텍처 프레임워크를 제공합니다. 제안된 모듈식 아키텍처는 애플리케이션과 SSD 디바이스 간의 긴밀한 통합을 통해 향상된 워크로드 성능과 함께 새로운 비휘발성 미디어 채택(NAND 및 Storage 클래스 메모리 모두)에 민첩성을 가능하게 합니다.&nbsp; 또한 SSD에서 소프트웨어 정의 데이터 배치를 사용하여 이전 모놀리식 스토리지 모델을 분리하는 모델을 정의합니다. 데이터 배치 관리가 NAND 관리 알고리즘과 분리되면 비휘발성 스토리지 미디어는 혁신을 위한 자체 일정을 따르도록 해제됩니다. Project Denali를 사용하면 하드웨어 회사가 더 간단하고 덜 복잡한 하드웨어를 빌드하여 비용을 절감하고, 출시 시간을 줄이고, 워크로드별 튜닝을 허용하고, 새로운 NAND 및 메모리 기술을 빠르게 개발할 수 있습니다.</p>


  <p>전체 에코시스템 파트너와 함께 Project Denali를 숙성한 후, 우리는 업계에 Project Denali 표준을 기여하여 더욱 광범위한 채택을 촉진할 계획입니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/7a66a35e-a3b4-4285-9f5a-95f72c1ae79c.png"><img alt="Project Denali" border="0" height="459" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/4062da79-feb9-4b9e-b159-47f7c38a99cb.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="Project 데날리" width="816"></a></p>


  <h2>하드웨어 보안 사용</h2>


  <p>Microsoft Azure 클라우드 보안 및 개인 정보 보호의 최첨단을 나타냅니다. Microsoft는 사이버 보안에 연간 10억 달러를 지출하며, 이러한 투자의 상당 부분은 Azure를 신뢰할 수 있는 클라우드 플랫폼으로 만드는 근본적인 개선으로 이뤄집니다. 보안에 집중하면서 하드웨어 보안을 위한 업계 표준의 필요성을 인식하고 있습니다. Microsofts&rsquo; Project Cerberus는 플랫폼 보안을 위한 개방형 업계 표준을 만들기 위해 개발되었습니다.</p>


  <p>Project Cerberus는 컴퓨팅 플랫폼의 모든 하드웨어 디바이스에 대한 신뢰의 루트를 설정하고 다음으로부터 플랫폼 펌웨어를 방어하는 데 도움이 되는 보안 공동 프로세서입니다.</p>


  <ul>
   <li>관리 권한 또는 하드웨어에 대한 액세스 권한이 있는 악의적인 내부자</li>
   <li>운영 체제, 애플리케이션 또는 하이퍼바이저에서 버그를 악용하는 해커 및 맬웨어</li>
   <li>공급망 공격(제조, 어셈블리, 전송 중)</li>
   <li>손상된 펌웨어 이진 파일</li>
  </ul>


  <p>Cerberus는 호스트의 액세스를 가로채 SPI 버스(펌웨어가 저장된 위치)를 통해 플래시하는 보안 코드를 실행하는 암호화 마이크로 컨트롤러로 구성되므로 이러한 액세스를 지속적으로 측정하고 증명하여 펌웨어 무결성을 보장하고 무단 액세스 및 악의적인 업데이트로부터 보호할 수 있습니다. 이렇게 하면 시스템의 모든 펌웨어 구성 요소에 대해 강력한 사전 부팅, 부팅 시간 및 런타임 무결성이 가능합니다.</p>


  <p>사양은 CPU 및 I/O 아키텍처에 구애받지 않으며 시간이 지남에 따라 다양한 공급업체 디자인에 쉽게 통합되어 데이터 센터에서 IoT 디바이스에 이르는 업계 전체의 모든 플랫폼 유형에서 보다 안전한 펌웨어 구현을 가능하게 합니다. 또한 이 사양은 동일한 아키텍처 원칙을 사용하여 플랫폼 보안을 모든 I/O 주변 장치로 확장할 수 있도록 계층적 신뢰 루트를 지원합니다.</p>


  <p>2017년 말 Project Cerberus가 도입된 이래, 표준을 지원하는 에코시스템은 계속해서 성장하고 있으며, 더 큰 협업과&rsquo; 채택을 위해 하드웨어 구현을 커뮤니티에 기여하기 직전에 분노하고 있습니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/8860a4b2-9df5-4020-869a-3183542792d1.png"><img alt="Project Ceberus" border="0" height="459" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/3f849ad1-b2f3-4f34-a3ab-d9469c7c935d.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="Project 세베로스" width="816"></a></p>


  <p>2015&rsquo;년부터 OCP 커뮤니티와 Microsoft Azure 서버 및 데이터 센터 디자인을 공유하면서 업계가 데이터 센터 성능, 효율성 및 전력 소비를 개선하는 혁신을 활용할 수 있도록 힘을 실어주고 있습니다.&nbsp;</p>


  <p>이 <a href="https://azure.com/ocp" target="_blank">링크를</a> 따라 오늘 발표한 작업에 대해 자세히 알아보거나 이 <a href="https://azure.microsoft.com/en-us/blog/project-denali-to-define-flexible-ssds-for-cloud-scale-applications/" target="_blank">블로그</a>에서 Project Denali에 대한 자세한 기술 정보를 확인할 수 있습니다.</p>
