### YamlMime:Yaml
ms.openlocfilehash: 010bd0aa1455052d851cdf680ba0ba0882127ca9
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139911677"
Slug: microsoft-open-sources-data-accelerator-an-easy-to-configure-pipeline-for-streaming-at-scale
Title: 대규모 스트리밍을 위해 구성하기 쉬운 파이프라인인 Microsoft 오픈 소스 Data Accelerator
Summary: '처음으로 데이터 파이프라인을 설치하는 것은 어려운 과제가 될 수 있으며, 프로젝트 시작 시 결정하면 초기 배포가 배포된 후 오랫동안 선택을 제한할 수 있습니다. 종종 필요한 것은 솔루션 공간에서 사용 가능한 옵션 및 기능에 대해 알아보고 평가하는 놀이터입니다. '
Content: >-
  <p><em>이 블로그 게시물은 Microsoft의 수석 그룹 엔지니어링 매니저인 Dinesh Chandnani가 공동 저술했습니다. &nbsp;</em></p>


  <p>처음으로 데이터 파이프라인을 설치하는 것은 어려운 과제가 될 수 있으며, 프로젝트 시작 시 결정하면 초기 배포가 배포된 후 오랫동안 선택을 제한할 수 있습니다. 종종 필요한 것은 솔루션 공간에서 사용 가능한 옵션 및 기능에 대해 알아보고 평가하는 놀이터입니다. 이를 위해 <a href="https://github.com/Microsoft/Data-Accelerator" target="_blank">Data Accelerator</a> 로 알려진 내부 Microsoft 프로젝트가 이제 오픈 소스로 공급되고 있음을 발표하게 되어 기쁩니다.</p>


  <p><a href="https://github.com/Microsoft/Data-Accelerator" target="_blank">Data Accelerator</a> 는 2017년에 Microsoft&rsquo; 개발자 부서의 대규모 데이터 처리 프로젝트로 시작되었으며, 결국 규모와 속도를 이유로 Apache Spark에서 스트리밍에 착수했습니다. 현재 파이프라인은 Microsoft 규모로 작동합니다.</p>


  <p>더 넓은 커뮤니티에 가치가 있다고 생각하는 이유 중 일부는 다음과 같습니다.</p>


  <ul>
      <li><strong>빠른 Dev-Test 루프:</strong> 이벤트를 샘플링하여 쿼리의 로컬 실행을 지원하고, 잘못 배치된 세미콜론으로 인해 7분 후에 실패할 수 있도록 작업을 클러스터에 제출하는 대기 및 지연을 단락할 수 있습니다.</li>
      <li><strong>로컬 테스트 및 검색을 위한 원박스 배포:</strong> 프로토타입에 커밋하기 전에 알아봅니다.</li>
      <li><strong>디자이너 기반 규칙 및 쿼리 빌드:</strong> 코드를 작성하거나 세부 정보를 자세히 살펴보지 않고 엔드투엔드 ETL 파이프라인을 설치합니다.</li>
      <li><strong>SQL-Spark 구문에 추가된 시간 범위, 참조 데이터 및 출력 기능:</strong> SQL-Spark 구문에 대한 키워드 확장은 이러한 일반적인 작업의 복잡성 및 오류가 발생하기 쉬운 관리를 방지합니다.</li>
  </ul>


  <p>Microsoft 개발자 부서는 매일 <a href="https://github.com/Microsoft/Data-Accelerator" target="_blank">프로덕션 환경에서 Data Accelerator</a> 를 사용하고 있으며 시간이 지남에 따라 도구 체인을 계속 개선할 예정이지만, 필요한 경우 도구 집합이 더 많은 작업을 수행할 수 있다는 것을 알고 있습니다. 이 프로젝트를 열면 <a href="https://github.com/Microsoft/Data-Accelerator" target="_blank">일부 사용자가 Data Accelerator</a> 를 훨씬 더 유용하게 사용할 수 있기를 바랍니다.</p>


  <p><a href="https://github.com/Microsoft/Data-Accelerator" target="_blank">데이터 가속기의</a> 오픈 소싱에 대한 자세한 내용은 <a href="https://cloudblogs.microsoft.com/opensource/2019/04/16/microsoft-open-sources-data-accelerator-for-apache-spark" target="_blank">오픈 소스 블로그</a>의 공지 사항을 참조하세요.</p>
