### YamlMime:Yaml
ms.openlocfilehash: 00006e015b034dde6821393f50d517461d0cce56
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139898879"
Slug: microsoft-government-cloud-application-center-connects-customers-with-windows-azure-partner-solutions
Title: Microsoft Government 클라우드 Application Center Windows Azure 파트너 솔루션으로 고객을 연결합니다.
Summary: 클라우드로의 이동을 평가하는 주 및 지방 정부는 비즈니스를 충족할 수 있는 올바른 클라우드 기반 솔루션으로 파트너 및 솔루션을 찾을 수 있는 중앙 위치가 있어야 합니다.
Content: <p>클라우드로의 이동을 평가하는 주 정부와 지방 정부는 비즈니스 요구 사항을 충족할 수 있는 올바른 클라우드 기반 솔루션으로 파트너 및 솔루션을 찾을 수 있는 중앙 위치가 있어야 합니다.&nbsp; 이러한 요구를 충족하기 위해 공공 부문 팀은 정부 고객에게 Windows <a target="_blank" href="https://azure.microsoft.com/">Azure</a> 플랫폼과 같은 Microsoft 클라우드 컴퓨팅 기술을 기반으로 구축된 파트너 애플리케이션을 신속하게 찾고 배울 수 있는 중앙 집중식 장소를 제공하기 위해 Microsoft <a target="_blank" href="https://www.microsoft.com/industry/government/solutions/CloudApplications.aspx">Government 클라우드 애플리케이션 센터를</a> 발표했습니다.&nbsp;  파트너, 솔루션 또는 기술로 검색할 수 있는 고객은 호환성을 평가하고 연락처 정보 및 파트너 웹 사이트에 대한 링크와 같은 추가 정보를 얻습니다.</p>  <p>정부 클라우드 애플리케이션 센터는 잠재적인 고객에게 azure 솔루션 및 서비스에 Windows <a target="_blank" href="https://www.microsoft.com/industry/government/products/bpos/default.aspx">BPOS(Business Productivity Online Suite)</a>를 기반으로 하는 고객에게 직접 소개할 수 있는 좋은 장소를 제공하기 때문에 파트너에게도 승리입니다. &nbsp;&nbsp;새 파트너 솔루션이 항상 추가되면 자주 확인하고 다시 확인하세요.</p>
