### YamlMime:Yaml
ms.openlocfilehash: 9f898b9a371e7cd67479a5283e02f977c0d2c849
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139901615"
Slug: microsoft-introduces-steps-to-improve-internet-routing-security
Title: Microsoft는 인터넷 라우팅 보안을 개선하는 단계를 소개합니다.
Summary: '인터넷은 BGP(Border Gateway Protocol)에서 실행됩니다. 네트워크 또는 AS(자율 시스템)는 출처에 의문을 제기하지 않고 피어가 보급한 경로를 신뢰, 수락 및 전파할 수 밖에 없습니다. '
Content: >-
  <p>인터넷은 BGP(Border Gateway Protocol)에서 실행됩니다. 네트워크 또는 AS(자율 시스템)는 출처에 의문을 제기하지 않고 피어가 보급한 경로를 신뢰, 수락 및 전파할 수 밖에 없습니다. 이것이 BGP의 강점이며 인터넷이 신속하게 업데이트되고 오류를 치유할 수 있게 해줍니다. 그러나 네트워크를 소유하는 접두사에 대한 경로는&mdash; 트래픽을 리디렉션, 가로채거나 차단하기 위해 사고 또는 악의적 인 의도로 변경할 수 있습니다. 작년에만 경로 하이재킹 및 누출과 같은 수백 건의 라우팅 중단 또는 사고가 있었습니다. 이러한 사건으로 인해 대규모 DDoS(분산 서비스 거부) 공격, 도난당한 데이터, 수익 손실, 평판 손상 등이 발생했습니다.</p>


  <p>라우팅 보안은 인터넷의 미래와 안정성에 매우 중요하며 Microsoft는 오랫동안 인터넷 라우팅 보안을 개선하기 위해 노력해 왔습니다. 2019년에 Microsoft는 매일 기업과 소비자에게 영향을 미치는 라우팅 보안과 관련된 문제를 해결하기 위해 MANRS( <a href="https://www.manrs.org/" target="_blank">상호 합의된 라우팅 보안 규범</a> ) 이니셔티브에 참여했습니다. 운영에서 기존 MANRS 프레임워크를 구현하고 <a href="https://www.internetsociety.org/" target="_blank">인터넷 사회</a>, <a href="https://cybertechaccord.org/" target="_blank">사이버 보안 기술 협정</a> 및 기타 조직과 협력하여 네트워크 운영자 및 IXP(인터넷 교환 지점)를 넘어서는 행위자가 라우팅 보안에 효과적으로 기여할 수 있는 방법을 검토했습니다.</p>


  <p>오늘 우리는 <a href="https://www.manrs.org/cdn-cloud-providers/" target="_blank">MICROSOFT가 MANRS 클라우드 및 CDN 프로그램에서</a> 정의한 <a href="https://www.manrs.org/2020/12/we-can-do-more-for-routing-security-say-participants-in-the-manrs-cdn-cloud-provider-programme/" target="_blank">새로운 작업을</a> 구현하기 위해 취할 단계를 발표하게 되어 기쁘게 생각합니다. 이러한 작업 집합에는 다음이 포함됩니다.</p>


  <h2>RPKI(리소스 공개 키 인프라) 원본 유효성 검사</h2>


  <p>RPKI는 인터넷&rsquo; 라우팅 인프라를 보호하도록 설계된 공개 키 인프라 프레임워크입니다. BGP 경로 원본 정보를 보호하는 데 사용됩니다. RPKI는 먼 길을 왔으며 <a href="https://rpki-monitor.antd.nist.gov/" target="_blank">채택은 지난 1 년 동안 두 배로 증가했습니다</a>. Microsoft는 ASN( <a href="https://www.peeringdb.com/net/694" target="_blank">자치 시스템 번호</a> )에서 발표한 모든 BGP 경로 서명을 완료했습니다. 최근 2021년 중반까지 RPKI 필터링을 구현하겠다는 약속으로 <a href="https://docs.microsoft.com/en-us/azure/internet-peering/policy" target="_blank">피어링 정책을</a> 업데이트했습니다. 이러한 변경은 시간이 걸릴 수 있으며 인터넷 피어와 협력하여 이러한 전환이 원활하게 진행되도록 할 것입니다.</p>


  <h2>경로 개체 유효성 검사</h2>


  <p>공용 인터넷 RoutingRegistries&nbsp;(IRR)는 경로 원본 정보 및 관계의 상당 부분을 계속&nbsp; 보유합니다. Microsoft는 IRR 데이터베이스를 사용하여 들어오는 모든 경로의 유효성을 검사합니다. <a href="https://www.radb.net/" target="_blank">RADb</a>의 모든 레코드를 업데이트하고 네트워크를 보호하기 위해 피어 네트워크와 협력하여 공용 IR의 경로 레코드를 업데이트합니다. Microsoft 내에서 글로벌 네트워크를 보호하기 위해 RADAR(글로벌 경로 변칙 검색 및 수정) 시스템을 개발했습니다. RADAR는 인터넷에서 실시간 Microsoft 경로 하이재킹을 감지하고 완화합니다. RADAR는 또한 Microsoft 네트워크 및 인터넷에서 경로 누수도 감지합니다. BGP 경로 누수는 의도한 범위를 벗어나는 라우팅 공지의 전파입니다. RADAR를 사용하면 공용 경로 데이터베이스를 사용하여 의도한 네트워크 경로 정보(AS 경로)를 설정합니다.</p>


  <p>RADAR를 사용하면 악의적인 활동이 검색되더라도 기본 경로를 통해 Microsoft에서 고객으로 트래픽을 라우팅해야 합니다. <a href="https://docs.microsoft.com/en-us/azure/peering-service/about" target="_blank">AZURE Peering Service</a>에 가입한 ISP(인터넷 서비스 공급자), IXP(인터넷 교환 파트너) 및 SDCI(소프트웨어 정의 클라우드 상호 연결) 공급자를 활용하는 고객은 RADAR 정보에 등록하고 경로 변칙이 검색될 때 정보를 유지할 수도 있습니다.</p>


  <h2>피어 네트워크 및 레지스트리를 사용하여 공동 작업 향상</h2>


  <p>Microsoft는 <a href="https://docs.microsoft.com/en-us/azure/networking/microsoft-global-network" target="_blank">현재 위치의 170개 이상의 에지 지점을</a> 통해 수천 개의 네트워크와 상호 연결됩니다. 인터넷을 통해 트래픽을 보호하기 위해 allpeer&nbsp; 네트워크와 협력할 것입니다. <a href="https://docs.microsoft.com/en-us/azure/internet-peering" target="_blank">피어링 포털</a>에서는 이미 수신된 모든 경로에 대한 RPKI 및 경로 개체 정보를 제공합니다. 피어 네트워크는 포털에서 RPKI, 경로 개체 및 네트워크 경로 정보를 볼 수 있으며 각 레지스트리에서 경로를 수정할 수 있습니다. 오늘날 주소 공간은 다른 레지스트리(<a href="https://www.arin.net/" target="_blank">ARIN</a>, <a href="https://www.lacnic.net/" target="_blank">LACNIC</a>, <a href="https://www.ripe.net/" target="_blank">RIPE</a> 등)에서 관리되며 모든 레지스트리에서 경로 개체를 관리하기가 쉽지 않습니다. Microsoft는 레지스트리를 사용하여 인터넷 피어를 보다 쉽게 만들고 일반적으로 모든 인터넷 서비스 공급자가 이러한 경로 개체를 쉽게 관리할 수 있도록 할 것입니다.</p>


  <p>인터넷 라우팅 보안에는 표준에 대한 지속적인 업데이트가 필요합니다. 현재 인터넷에서 발생하는 문제를 해결할 수 있는 단일 표준은 없으며 새로운 위협이 발생할 때 라우팅 보안 표준을 업데이트해야 합니다. 최근에 우리는 이러한 표준을 업데이트하기 위해 MANRS 커뮤니티와 협력했으며 다른 MANRS 멤버와 함께 구현하게 되어 기쁩니다. 마지막으로, 이 중요한 주제에 대해 인터넷 커뮤니티를 하나로 모으고 인터넷 보안을 가속화하는 원동력이 된 <a href="https://www.manrs.org/" target="_blank">MANRS</a> 와 인터넷 <a href="https://www.internetsociety.org/" target="_blank">협회</a> 에 감사드립니다.</p>
