### YamlMime:Yaml
ms.openlocfilehash: a783ff5efaf126ce6ce01b83eea360834f1d01ef
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139903156"
Slug: microsoft-azure-uses-error-correcting-code-memory-for-enhanced-reliability-and-security
Title: Microsoft Azure 향상된 안정성 및 보안을 위해 Error-Correcting Code 메모리를 사용합니다.
Summary: Microsoft Azure 배포된 시스템 전체에서 ECC(Error-Correcting Code) 메모리를 활용하여 보호합니다.
Content: >-
  메모리 디바이스는 전기, 자기, 배경 방사선 또는 제조 결함을 비롯한 다양한 소스에서 오류가 발생하기 쉽습니다. 일반적인 유형의 메모리 오류는 0에서 1까지의 단일 비트 "대칭 이동"이거나 그 반대의 경우도 마찬가지입니다. 검색되지 않거나 수정되지 않은 메모리 오류로 인해 코드 또는 데이터 손상, 시스템 또는 애플리케이션 충돌과 같은 안정성 및 보안 문제가 발생할 수 있으며 보안에 중요한 코드, 데이터 또는 정책이 무단으로 변경되어 시스템의 보안이 저하될 수 있습니다. Microsoft Azure 배포된 시스템 전체에서 ECC(Error-Correcting Code) 메모리를 활용하여 이러한 종류의 문제로부터 보호합니다.


  ECC 메모리는 단일 비트 및 여러 비트 오류의 특정 사례를 포함하여 많은 유형의 메모리 오류를 감지하고 수정할 수 있는 기술입니다. ECC 메모리를 사용하면 오류 수정이 애플리케이션/서비스에 투명하게 처리되고 애플리케이션은 항상 원래 메모리에 기록된 데이터를 읽습니다. 오류를 수정할 수 없는 경우 Microsoft Azure 호스트 운영 체제가 즉시 다시 부팅되고 자세한 이벤트를 기록하도록 구성되므로 애플리케이션이 메모리 손상에 노출되지 않습니다. ECC 메모리는 비 ECC 메모리보다 비용이 더 많이 들며, Microsoft는 이 기술이 Azure에서 엔터프라이즈급 고객 데이터 호스팅을 지원하는 데 적절하다고 생각했습니다.


  Microsoft는 데이터 센터 내에 배포된 Azure 제품 서버에서 Rowhammer라고 하는 메모리 프로세스 크기 조정 문제에 대해 광범위한 테스트를 수행했습니다. Rowhammer는 마켓플레이스에 배포된 DRAM 메모리 모듈의 하위 집합에 영향을 줄 수 있는 메모리 하드웨어 문제이며, 특정 메모리 읽기 작업 패턴을 실행하여 악용될 수 있으며, 이로 인해 권한 있는 메모리 영역에서 "비트 대칭 이동"을 통해 무단 쓰기가 발생할 수 있습니다.


  Rowhammer 익스플로잇을 시도하려면 공격자가 대상 시스템에서 선택한 코드를 실행할 수 있어야 합니다. Office365와 같은 대부분의 클라우드 서비스는 고객이 서비스를 호스트하는 시스템에서 임의 소프트웨어를 실행하는 것을 허용하지 않으므로 공격자는 Rowhammer 공격을 직접 실행할 수 없습니다. 그러나 Microsoft Azure 통해 고객은 IAAS 가상 머신과 같이 잠재적으로 악성 소프트웨어를 포함한 임의의 소프트웨어를 실행할 수 있습니다.


  몇 달 전에 수행된 테스트에 따라 프로덕션 서버, 고객 VM 및 고객 데이터가 Rowhammer의 영향을 받지 않는 것으로 확인되었습니다.


  Microsoft Azure ECC 메모리가 있는 시스템을 배포하여 테스트 중에 유도되고 유효성이 검사된 Rowhammer 오류 유형을 감지하고 수정합니다.심층 방어의 추가적인 조치로, Microsoft Azure 수정되고 수정할 수 없는 메모리 오류 조건과 Rowhammer 공격 시도를 감지하기 위해 모니터링 및 경고를 배포했습니다.


  ECC 메모리에 대한 자세한 내용은 <a href="https://en.wikipedia.org/wiki/ECC_memory">여기</a>를 참조하세요.


  Rowhammer에 대한 자세한 내용은 <a href="https://users.ece.cmu.edu/~yoonguk/papers/kim-isca14.pdf">여기</a>를 참조하세요.
