### YamlMime:Yaml
ms.openlocfilehash: aae73d33a2b6f62493a7c060a08f99dc7512c43f
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139907683"
Slug: migrating-a-java-spring-framework-application-to-windows-azure
Title: Java Spring Framework 애플리케이션을 Windows Azure로 마이그레이션
Summary: 이제 막 새로운 자습서 및 샘플 코드를 게시하여 많은 Azure Java 관련 기술을 Windows 보여 줍니다.&nbsp; 이 가이드에서는 다음을 보여 주는 단계별 자습서를 제공합니다.
Content: >-
  <p>이제 막 <a href="https://aka.ms/JavaAzureTutorial" target="_blank">새로운 자습서</a> 및 샘플 코드를 게시하여 많은 Azure Java 관련 기술이 작동하는 Windows 보여 줍니다.&nbsp; 이 가이드에서는 Java Spring Framework 애플리케이션(PetClinic 샘플 애플리케이션)을 Windows Azure Cloud로 마이그레이션하는 방법을 보여 주는 단계별 자습서를 제공합니다.&nbsp; 이 문서와 함께 제공되는 코드도 <a href="https://github.com/Logic2020Inc/spring-petclinic-mod" target="_blank">GitHub</a> 게시됩니다.&nbsp; Java 개발자는 이 새로운 샘플 및 자습서를 다운로드하고 탐색하는 것이 좋습니다.</p>

  <h4>세부 정보</h4>

  <p>Windows Azure는 개방형 클라우드 플랫폼이며 Microsoft .NET, Java, Node.js, PHP, Python 및 Ruby를 비롯한 다양한 프로그래밍 언어 및 프레임워크를 지원합니다.&nbsp; 이 가이드는 일반적인 Java 애플리케이션을 Windows Azure 클라우드로 마이그레이션하는 방법을 보여 주기 위해 Java 개발자를 위해 특별히 작성되었습니다. 이 자습서에서는 인기 있는 Spring Framework 샘플 애플리케이션(Java PetClinic)에 중점을 둡니다. 이 자습서에서는 Memcached, Windows Azure Cloud Services, Windows Azure SQL Database 사용하여 Azure 캐싱을 Windows Eclipse용 Azure Java SDK뿐만 아니라 다른 많은 유형의 Java 애플리케이션에서 사용되는 다양한 다른 기술을 소개합니다.</p>

  <h4>Azure Cloud Services(PaaS) 또는 Windows Azure Virtual Machines(IaaS)를 Windows?</h4>

  <p>기본적으로 Windows Azure에서 웹 사이트와 같은 애플리케이션 계층을 실행하는 방법에는 두 가지가 있습니다.&nbsp; 첫 번째는 Azure Cloud Services를 통한 PaaS(Platform as a Service)를 통한 것입니다. 두 번째는 Windows Azure VM(Virtual Machines)을 통해 IaaS(Infrastructure as a Service)를 통해 이루어집니다.&nbsp; 둘 중 하나를 사용하여 개발자는 여러 전 세계 데이터 센터(미국에 4개, 유럽에 2개, 아시아에 2개) 중 하나를 선택하여 애플리케이션을 호스트합니다.</p>

  <ul>

  <li><a href="https://azure.microsoft.com/en-us/develop/net/fundamentals/compute/#CloudServices" target="_blank">Windows Azure Cloud Services</a>를 사용하면 개발자는 애플리케이션에만 초점을 맞추고, 플랫폼은 애플리케이션 계층이 실행되는 인스턴스를 자동으로 프로비전하고 유지 관리합니다(아래는 YHyperHY Hyper-V VM에 Windows).&nbsp; 인스턴스는 1개에서 수백 개의 클론으로 수평으로 크기를 조정할 수 있으며 부하 분산은 자동으로 수행됩니다.&nbsp; 인스턴스의 크기는 서로 다른 수의 가상 코어 및 메모리로 지정할 수 있지만, 인스턴스는 OS 계층의 모든 패치 및 보안 업데이트를 포함하여 Windows Azure에서 기본적으로 관리됩니다. 이 가이드에서는 Windows Azure Cloud Services에서 Java Pet Clinic 샘플 애플리케이션을 실행하는 데 중점을 둡니다.</li>

  <li><a href="https://azure.microsoft.com/en-us/develop/net/fundamentals/compute/#VMachine" target="_blank">Windows Azure Virtual Machines</a>를 사용하여 개발자는 자신의 VM 이미지를 만들고 VM에 설치할 소프트웨어를 포함하여 해당 VM을 설치하고 관리할 책임이 있습니다.&nbsp; Java 개발자에게는 Windows 및 <strong>여러 Linux 배포</strong>를 포함하여 다양한 미리 빌드된 VM 이미지를 사용할 수 있습니다.&nbsp; 또한 개발자는 OS 및 VM에 대한 낮은 수준의 제어를 가지며, 모든 수의 VM에 mySQL과 같은 다른 소프트웨어를 직접 설치하여 애플리케이션 계층에서 데이터 계층으로 전체 애플리케이션을 빌드할 수 있으므로 이 방법은 Windows Azure Cloud에서 Java 애플리케이션을 실행하는 좋은 방법입니다. 대부분의 Java 애플리케이션은 코드 변경이 거의 또는 전혀 필요 없이 마이그레이션됩니다. 여러 VM(Tomcat/JSP 계층 실행)이 라운드 로빈을 통해 부하 분산되도록 부하 분산을 설정할 수도 있습니다. 그러나 Azure Cloud Services와 달리 개발자는 VM이 온-프레미스에서 실행되는 것처럼 보안 패치를 포함하여 VM을 관리해야 합니다. 새 자습서에서는 Windows Azure Cloud Services에서 실행되는 Java에 중점을 두지만, 개발자는 Windows 또는 Linux VM을 사용하여 Azure Virtual Machines를 Windows 사용해보는 것이 좋습니다.</li>

  </ul>

  <h4>Windows Azure 플랫폼의 Spring Framework&nbsp;</h4>

  <p>Spring Frameworks&rsquo;에서 최근에 업데이트한 PetClinic 샘플은 Spring Data JPA, MVC, AOP, JMX, EhCache 및 Logback과 같은 확장 가능한 Java EE 애플리케이션을 만드는 데 사용되는 여러 엔터프라이즈 기술을 시연하기 위한 친숙한 수단이기 때문에 이 새로운 가이드에 선택되었습니다. 임시 오류 처리를 주입하고 AOP를 통해 Azure Cache에 Memcached를 주입하여 PetClinic을 확장할 예정입니다.</p>

  <p>Eclipse 및 STS에 익숙한 Java 개발자를 위해 Microsoft는 Java&rsquo;와 <a href="https://msdn.microsoft.com/en-us/library/windowsazure/hh690946.aspx" target="_blank">함께 Eclipse용 Azure Toolkit Windows</a> 제공 &lsquo; 했습니다. 이 도구 키트는 Windows Azure의 Eclipse에서 Java 개발을 지원하기 위한 다음 리소스를 제공합니다.&nbsp;</p>

  <ul>

  <li>Java를 사용하여 Eclipse용 Azure 플러그 인 Windows</li>

  <li>microsoft JDBC 4.0 Driver for SQL Server 및 Windows Azure SQL Database</li>

  <li>JMS용 Apache Qpid 클라이언트 라이브러리용 패키지</li>

  <li>Java용 Windows Azure 라이브러리 패키지</li>

  <li>Azure Access Control Services 필터 Windows</li>

  <li>Azure Common 플러그 인 Windows</li>

  </ul>

  <p>이 가이드에서는 Java 및 Microsoft JDBC 4.0 Driver for SQL Server Windows Azure Plugin for Eclipse를 사용합니다. Eclipse에 대한 플러그 인은 Windows Azure 서비스 및 Windows Azure 에뮬레이터에 대한 Java 래퍼를 제공합니다.</p>

  <h4>결론</h4>

  <p>Windows Azure는 개방형 클라우드 플랫폼이며 다양한 프로그래밍 언어 및 프레임워크를 지원합니다. Java 개발자는 <a href="https://aka.ms/JavaAzureTutorial" target="_blank">Windows Azure 자습서</a> 및 샘플 코드에서 새로운 Java를 탐색하여 많은 azure Java 관련 기술이 작동하는 Windows 보여 줍니다.&nbsp;&nbsp;</p>
