### YamlMime:Yaml
ms.openlocfilehash: 39a3fa71298881f66fe9f8dfa5832e534eecd008
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139907711"
Slug: migrate-heterogeneous-it-environments-to-azure-with-asr
Title: ASR을 사용하여 다른 유형의 IT 환경을 Azure로 마이그레이션
Summary: AoD를 지원하는 기술인 Azure Site Recovery는 Hyper-V 및 VMware 가상 머신 및 물리적 서버를 Azure에 복제하는 통합 솔루션을 제공하여 다른 유형의 IT 환경에 대한 워크로드 인식 복구 및 마이그레이션을 지원합니다.
Content: >-
  <p>Microsoft는 <a href="https://aka.ms/asr_migration_aod">하이브리드 및 다른 유형의 환경을 위해 Azure에서 포괄적인 AoD(가용성)</a>를 제공하므로 조직은 DevTest, 클라우드 버스팅, 마이그레이션, 보고/분석, 복구, 백업 및 장기 데이터 보존을 위해 클라우드에서 거의 무제한으로 컴퓨팅 및 스토리지를 활용할 수 있습니다. AoD를 지원하는 기술인 <a href="https://aka.ms/asr_migration_landingpage">Azure Site Recovery</a> 는 <a href="https://aka.ms/asr_migration_hyperv">Hyper-V</a> 및 <a href="https://aka.ms/asr_migration_vmware">VMware 가상 머신 및 물리적 서버를 Azure</a>에 복제하는 통합 솔루션을 제공하여 다른 유형의 IT 환경에 대해 워크로드 인식 복구 및 마이그레이션을 가능하게 합니다. ASR&rsquo; 복제 기술을 사용하여 자동화된 애플리케이션 인식 보호를 사용하도록 설정하고 물리적 및 가상화된 워크로드의 원클릭 복구/마이그레이션을 Azure로 오케스트레이션할 수 있습니다. 물리적 서버 및 VMware, AWS 및 Hyper-V 가상 머신을 Azure로 마이그레이션할 수 있는 Microsoft Migration Accelerators&rsquo; 기능이 이제 Azure Site Recovery에 통합되었습니다. 애플리케이션 데이터는 Azure에 한 번만 복제해야 하며 마이그레이션 및 재해 복구 모두에 사용할 수 있습니다. 또한 Azure Portal에서 일관된 ASR 환경을 얻을 수 있습니다. AoD를 사용하면 ASR을 사용하여 다른 유형의 워크로드를 Azure로 마이그레이션하고 Microsoft Azure 기능으로 IT 과제를 해결할 수 있습니다.</p>


  <ul>
   <li>IT에 대한 부담을 줄이고 온-프레미스 인프라에 대한 비용을 낮춥니다.</li>
   <li>진정한 하이브리드 환경을 위해 앱을 실행하고 데이터를 저장하는 위치 제어</li>
   <li>계층 1 및 계층 2 워크로드 모두에 대한 확장 가능하고 안정적인 플랫폼</li>
   <li>요청 시 거의 무제한인 클라우드 확장성을 사용하여 데이터 센터 민첩성 향상</li>
  </ul>


  <p>&nbsp; 기존 온-프레미스 가상화된 워크로드를 Azure로 마이그레이션할 수 있는 솔루션을 원하는 고객은 결정을 내릴 때 가장 자주 세 가지 매우 중요한 고려 사항을 찾습니다.</p>


  <ul>
   <li>마이그레이션 중 프로덕션 워크로드의 가동 중지 시간 줄이기</li>
   <li>마이그레이션 전에 Azure에서 애플리케이션 테스트</li>
   <li>마이그레이션 및 복구를 위해 Azure에 한 번만 데이터 복제</li>
  </ul>


  <p>&nbsp; 위의 기준(및 그 이상)을 충족하는 통합 솔루션을 원하는 고객의 경우 기본 제공 기능을 사용하여 Azure Site Recovery를 사용하면 Azure로의 마이그레이션을 간단하고 안정적이며 빠르게 만들 수 있습니다. 온-프레미스 애플리케이션을 Azure로 마이그레이션하는 방법은 다음과 같습니다. <a href="https://acom.azurecomcdn.net/80C57D/blogmedia/blogmedia/2015/04/21/ASR_Migration_Flowchart.jpg"><img alt="Migrate VMware AWS Hyper-V to Azure" border="0" height="772" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/ASR_Migration_Flowchart_thumb.jpg" style="padding-top: 0px; padding-left: 0px; padding-right: 0px; border-width: 0px;" title="VMware AWS Hyper-V를 Azure" width="513"></a> &nbsp; 로 마이그레이션하기 위한 몇 가지 리소스는 다음과 같습니다.</p>


  <ul>
   <li><a href="https://aka.ms/asr_migration_documenation_vmware">온-프레미스 VMware 가상 머신 또는 물리적 서버와 Azure 간의 보호 설정</a></li>
   <li><a href="https://aka.ms/asr_migration_documentation_hyperv">온-프레미스 Hyper-V 사이트와 Azure 간 보호 설정</a></li>
  </ul>


  <p>&nbsp; 다음 표에는 ASR을 사용하여 Azure로 마이그레이션할 수 있는 다양한 온-프레미스 원본 환경이 나와 있습니다.</p>


  <table width="100%">
   <tbody>
    <tr>
     <td width="32%"><strong>원본</strong></td>
     <td width="14%"><strong>대상</strong></td>
     <td width="17%"><strong>가용성 </strong></td>
     <td width="35%"><strong>지원되는 게스트 OS 유형</strong></td>
    </tr>
    <tr>
     <td width="32%">Hyper-V 2012 R2</td>
     <td width="14%">Azure</td>
     <td width="17%">사용 가능</td>
     <td width="35%">Azure에서 지원하는 모든 게스트 OS 유형</td>
    </tr>
    <tr>
     <td width="32%">Hyper-V 2008 R2 SP1 및 2012</td>
     <td width="14%">Azure</td>
     <td width="17%">미리 보기에서 사용 가능</td>
     <td width="35%">Windows* 및 Linux*</td>
    </tr>
    <tr>
     <td width="32%">VMware vCenter Server 5.1, 5.5, ESXi 5.1, 5.5 및 물리적 서버</td>
     <td width="14%">Azure</td>
     <td width="17%">미리 보기에서 사용 가능</td>
     <td width="35%">Windows* 및 Linux*</td>
    </tr>
    <tr>
     <td width="32%">Amazon Web Services(Windows API)</td>
     <td width="14%">Azure</td>
     <td width="17%">미리 보기에서 사용 가능</td>
     <td width="35%">Windows Server 2008 R2 SP1+</td>
    </tr>
    <tr>
     <td width="32%">Hyper-V 2012</td>
     <td width="14%">Hyper-V 2012R2</td>
     <td width="17%">사용 가능</td>
     <td width="35%">Hyper-V에서 지원하는 모든 게스트 OS 유형</td>
    </tr>
   </tbody>
  </table>


  <p><i><span style="font-family: calibri; color: #000000;">*Windows Server 2008 R2 SP1+, CentOS 6.4, 6.5, 6.6, Oracle Enterprise Linux 6.4, 6.5, SUSE Linux Enterprise Server 11 SP3</span></i> &nbsp; 으로 제한됨 <a href="https://acom.azurecomcdn.net/80C57D/blogmedia/blogmedia/2015/04/21/ASR_Migration.jpg"><img alt="Migration to Azure" border="0" height="442" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/ASR_Migration_thumb.jpg" style="padding-top: 0px; padding-left: 0px; padding-right: 0px; border-width: 0px;" title="Azure" width="1028"></a>로 마이그레이션을 시작할 준비가 되면 <a href="https://aka.ms/asr_migration_landingpage">추가 제품 정보를 확인</a>하여 Azure Site Recovery를 사용하여 워크로드를 Microsoft Azure 마이그레이션을 시작합니다. &rsquo;이제 Azure Site Recovery를 사용하여 <a href="https://aka.ms/asr_migration_aod_page">주문형 가용성</a>을 사용하도록 설정하고 데이터 센터를 확장하고 보호할 수 있습니다. 복제하는 모든 새 물리적 서버 또는 가상 머신에 대해 31일 동안 Site Recovery의 강력한 복제 기능을 무료로 사용할 수 있습니다. <a href="https://aka.ms/asr_migration_ma">AoD 마이그레이션 발표 및 ASR 가격 변경</a>에 대한 자세한 내용은 Joel Ferman의 다음 블로그를 참조하세요.</p>
