### YamlMime:Yaml
ms.openlocfilehash: 7b3f41694aa3752172ede21e2fe21f508035532c
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139911670"
Slug: migrate-application-insights-to-hockeyapp
Title: 지금 애플리케이션 Insights 모바일 앱을 HockeyApp으로 마이그레이션
Summary: 현재 한 번의 클릭으로 기존 애플리케이션 Insights 모바일 앱을 HockeyApp으로 마이그레이션할 수 있습니다.
Content: >-
  <p>3월 초에 <a href="https://azure.microsoft.com/blog/transitioning-mobile-apps-from-application-insights-to-hockeyapp/">우리는</a> <a href="https://hockeyapp.net">HockeyApp</a>에서 모바일 및 데스크톱 고객을 위한 노력을 집중하고 있다고 발표했습니다. HockeyApp은 모바일 DevOps 솔루션의 핵심 구성 요소입니다. 이제 한 번의 클릭으로 애플리케이션 Insights HockeyApp으로 애플리케이션을 마이그레이션할 수 있습니다.</p>


  <h2>HockeyApp으로의 전환은 이제 라이브로 전환됩니다.</h2>


  <p>오늘부터 한 번의 클릭으로 애플리케이션 Insights HockeyApp으로 애플리케이션을 전송할 수 있음을 알려드리겠습니다. 앱에 로그인하기만 하면 앱 맨 위에 전환 상태 표시줄이 표시됩니다. 이 단일 단추 클릭은 기존 애플리케이션을 HockeyApp으로 전송합니다. SDK를 변경할 필요가 없으며 환경을 변경할 필요가 없습니다(애플리케이션 Insights 환경은 일몰 날짜에 도달하는 6월 15일까지 영향을 받지 않음).</p>


  <p><img alt="Transfer to HockeyApp Status Bar" border="0" height="231" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/054d1851-0b24-44ca-be7a-d8ea9e0a967b.png" style="border: 0px currentColor; border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="HockeyApp 상태 표시줄로 전송" width="610"></p>


  <p>이 전환에서 기존 고객을 가장 잘 지원하기 위해 Application Insights에서 HockeyApp으로 이동된 애플리케이션이 HockeyApp에서 무료로 지원된다는 사실을 발표하게 되어 기쁩니다. 전송을 통해 이 기간 동안 이동된 앱은 HockeyApp 구독 앱 제한에 포함되지 않습니다.</p>


  <h2>작동 원리</h2>


  <p>앱은 동일한 Azure 계정 자격 증명(MSA 또는 AAD)에 직접 연결된 HockeyApp 계정으로 전송됩니다. HockeyApp 계정이 없는&rsquo; 경우 자동으로 만들어집니다. 그런 다음 새 애플리케이션을 자동으로 프로비전하고 기존 애플리케이션 Insights 앱에 연결합니다. 이렇게 하면 데이터가 두 환경 모두로 흐를 수 있습니다. 또한 HockeyApp 앱은 애플리케이션 Insights 리소스로 전송된 기록 데이터에 액세스할 수 있습니다. 이 원활한 환경이 6월 15일에 애플리케이션 Insights 일몰 환경이 될 때까지 전환 환경에 도움이 되기를 바랍니다. 전환에 대한 자세한 내용은 기술 자료 <a href="https://support.hockeyapp.net/kb/general-account-management-2/hockeyapp-for-application-insights-device-customers">설명서를</a> 참조하세요.</p>


  <h2>결론</h2>


  <p>이러한 전환 환경과 무료 앱 전송이 전환 비용을 완화하는 데 도움이 되기를 바랍니다. 우리의 목표는 HockeyApp을 통해 앱을 배포, 테스트, 모니터링 및 관리하는 최상의 모바일 DevOps 환경을 제공하는 것입니다. 이 전환 프로세스 중에 문제가 있는 경우 자유롭게 <a href="https://support.hockeyapp.net">문의</a>하세요.</p>
