### YamlMime:Yaml
ms.openlocfilehash: ce2b4beba75731ec96526d00b3b2fffb38c30f13
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139901076"
Slug: modernize-your-applications-with-the-microsoft-data-accelerator-program
Title: Microsoft 데이터 가속기 프로그램을 사용하여 애플리케이션 현대화
Summary: 고객은 제공하는 모든 솔루션에서 최신 혁신을 요구하고 있습니다. 앱이 고객의 기대치를 충족하고 초과할 수 있도록 하려면 어떻게 해야 할까요? 효율적이고 안정적인 업그레이드 서비스인 Microsoft Data Accelerator 프로그램을 활용하여 온-프레미스 또는 클라우드 애플리케이션을 현대화합니다.
Content: >-
  <p>고객은 제공하는 모든 솔루션에서 최신 혁신을 요구하고 있습니다. 앱이 고객의&rsquo; 기대치를 충족 &mdash; 하고 초과 &mdash; 할 수 있도록 하려면 어떻게 해야 할까요? 효율적이고 안정적인 업그레이드 서비스인 Microsoft Data Accelerator 프로그램을 활용하여 온-프레미스 또는 클라우드 애플리케이션을 현대화합니다. 올해는 4가지 새로운 시나리오를 지원하도록 프로그램을 확장했습니다.</p>


  <p><strong><em>최신 버전의 SQL Server 업그레이드하여 클라우드로의 여정을 시작합니다.</em></strong> 온-프레미스 앱을 현대화하거나 Linux에서 SQL Server 2017을 지원하도록 애플리케이션을 확장합니다.</p>


  <p><strong><em>레거시 SQL Server 또는 Oracle 앱을 Azure SQL Database 마이그레이션합니다.</em></strong> Azure SQL Database 사용하면 유연한 성능과 비용 효율성으로 레거시 앱을 SaaS 지원 솔루션으로 쉽게 마이그레이션할 수 있습니다.</p>


  <p><strong><em>오픈 소스 투자를 활용하고 온-프레미스 앱을 현대화하여 MySQL 및 PostgreSQL에 대한 Azure SQL Database.</em></strong> MySQL 또는 Postgre SQL 데이터베이스에 이미 알고 있고 좋아하는 도구를 사용하여 새 앱을 신속하게 빌드하고 배포합니다.</p>


  <p><strong><em>Azure SQL Database Managed Instance를 사용하여 온-프레미스 SQL Server 앱을 클라우드로 리프트 앤 시프트합니다.</em></strong> Azure SQL Database Managed Instance를 사용하여 온-프레미스 SQL Server 앱을 클라우드로 이동합니다. 앱을 다시 디자인하지 않고도 SQL 애플리케이션을 완전 관리형 PaaS로 쉽게 마이그레이션할 수 있습니다.</p>


  <p>Microsoft&#39;데이터 가속기 프로그램을 사용하면 ISV&#39;온-프레미스 앱을 업그레이드하거나 클라우드 여정을 시작할 수 있습니다. 애플리케이션이 클라우드에서 태어났든 마이그레이션하려는&#39;상관없이 Data Accelerator 프로그램은 고객의&rsquo; 요구에 따라 앱을 현대화할 수 있는 유연성을 제공합니다. 오늘 적용하여 온-프레미스 앱을 업그레이드하거나 클라우드로 마이그레이션을 시작합니다.</p>


  <h4>Microsoft 데이터 가속기 프로그램에 <a href="https://info.microsoft.com/microsoft-data-accelerator-program-register.html">대해 자세히 알아보고 신청</a>하세요<strong>.</strong></h4>
