### YamlMime:Yaml
ms.openlocfilehash: 55d01dad33ea66642debb3118e478589bd4f1215
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139902071"
Slug: monitor-azure-services-and-applications-using-grafana
Title: Grafana를 사용하여 Azure 서비스 및 애플리케이션 모니터링
Summary: '오늘 Azure Monitor 및 애플리케이션 Insights Grafana 플러그 인을 도입하게 되어 기쁩니다. Azure Monitor 데이터 원본 플러그 인의 v0.1.0은 이제 Azure 미국 정부, Azure 독일 및 Azure 중국 클라우드에 대한 지원을 추가했습니다. '
Content: >-
  <p>오늘 Azure Monitor 및 애플리케이션 Insights Grafana 플러그 인을 도입하게 되어 기쁩니다. Azure Monitor 데이터 원본 플러그 인의 v0.1.0은 이제 Azure 미국 정부, Azure 독일 및 Azure 중국 클라우드에 대한 지원을 추가했습니다. Azure는 선호하는 도구와 프레임워크를 사용하여 빌드된 워크로드를 가져와 Azure의 다양한 서비스와 함께 호스팅할 수 있는 개방형 플랫폼입니다. 클라우드로의 여정을 계속하면서 애플리케이션을 Azure에 온보딩하면서 많은 사용자가 비즈니스 연속성을 위해 기존 오픈 소스 개발 및 관리 도구를 활용해야 한다고 밝혔습니다. 우리의 임무는 현재 위치에서 귀하를 만나고 Azure에서 이러한 도구를 원활하게 활용할 수 있도록 하는 것입니다. 인기 있는 도구 중 하나는 시계열 메트릭을 시각화하는 선도적인 오픈 소스 소프트웨어인 <a href="https://grafana.com/" target="_blank">Grafana</a>입니다. 몇몇 사용자가 기존 모니터링 투자의 일부인 Grafana의 Azure 서비스 및 애플리케이션에서 메트릭을 사용하는 기능에 대한 피드백을 제공했습니다. &ndash; 이제 Azure용 Grafana 데이터 원본 플러그 인을 사용하여 이 작업을 수행할 수 있습니다.</p>


  <h2>Azure Monitor 및 애플리케이션 Insights 미리 보기용 Grafana 플러그 인</h2>


  <p>Grafana를 이미 사용 중인 경우 Grafana 뒤에 있는 Grafana Labs 팀에서 빌드한 새로운 <a href="https://grafana.com/plugins/grafana-azure-monitor-datasource" target="_blank">Azure Monitor 데이터 원본 플러그 인</a> 덕분에 Azure 서비스 및 애플리케이션을 모니터링하는 데 사용할 수 있습니다. 현재 미리 보기로 제공되는 이 플러그 인을 사용하면 Grafana 대시보드에 Azure Monitor 및 애플리케이션 Insights 메트릭을 모두 포함할 수 있습니다. 설치 지침을 검토하려면 데이터 원본 플러그 인 <a href="https://grafana.com/plugins/grafana-azure-monitor-datasource/installation" target="_blank">설치 페이지를</a> 방문하세요.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/dab37ce8-46f5-4c73-9ec1-6df0e070c805.png"><img alt="Contoso Loans Grafana dashboard" border="0" height="1195" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/9040a751-7dfb-42d8-bc2f-66f2d08653c9.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="Contoso Loans Grafana 대시보드" width="2546"></a></p>


  <p align="center"><em>그림 1: Azure Monitor 및 애플리케이션 Insights 메트릭을 보여 주는 Grafana 대시보드</em></p>


  <p>이제 이 플러그 인을 사용하여 Collectd, Telegraf 및 Prometheus와 같은 다양한 오픈 소스 에이전트에서 수집된 모든 메트릭과 Azure 플랫폼 및 애플리케이션의 메트릭을 하나의 대시보드로 결합할 수 있습니다.</p>


  <h2>Azure Marketplace 제품을 통한 간편한 Grafana 설정</h2>


  <p>Grafana Labs 팀은 Azure에서 Grafana를 더 쉽게 시작하고 Azure Marketplace 제품을 빌드할 수 있도록 하고자 했습니다. <a href="https://azuremarketplace.microsoft.com/en-us/marketplace/apps/grafana-labs.grafana_oss" target="_blank">기본적으로 Grafana 대시보드 서버와 Azure</a> 플러그 인이 미리 설치된 VM인 Azure Marketplace에서 Grafana 서버를 활용할 수 있습니다.</p>


  <p>Azure Monitor 및 애플리케이션 Insights 메트릭을 사용하여 Grafana 대시보드를 설정하는 샘플 연습은 <a href="https://aka.ms/grafanawalkthrough" target="_blank"><em>Azure Monitor 설명서</em></a>에서 찾을 수 있습니다<em>.</em></p>


  <p>Grafana Labs의 팀은 플러그 인 및 Marketplace 제품에 대한 의견을 듣고 싶어합니다. Twitter&nbsp;<a href="https://twitter.com/search?q=%40grafana&amp;src=typd">@grafana</a>를 통해 연락하거나 <a href="https://github.com/grafana/azure-monitor-datasource">GitHub</a> 피드백을 제출할 수 있습니다.</p>


  <h2>요약</h2>


  <p>Microsoft는 플랫폼 및 서비스를 혁신하고 커뮤니티와 협력하여 좋아하는 오픈 소스 프레임워크 및 도구와 통합하여 더 많은 작업을 수행할 수 있도록 계속 힘을 실어줄 것입니다. Grafana 통합은 아직 제공되지 않은 많은 통합 중 하나일 뿐입니다. Azure의 애플리케이션 및 리소스에서 이 작업을 시도한 후 <a href="https://feedback.azure.com/forums/231545-diagnostics-and-monitoring" target="_blank">여러분의 의견을</a> 듣게 되어 기쁩니다.</p>
