### YamlMime:Yaml
ms.openlocfilehash: d16af0a3401c0f8b2bd3b1f57f540890e58f779c
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139901073"
Slug: more-reliable-event-driven-applications-in-azure-with-an-updated-event-grid
Title: 업데이트된 Event Grid를 사용하여 Azure에서 보다 안정적인 이벤트 기반 애플리케이션
Summary: '클라우드 애플리케이션 아키텍처의 핵심 구성 요소로서 이벤트 기반 프로그래밍의 등장에 참여하게 되어 매우 기쁩니다. 다음 기능을 일반적으로 사용할 수 있게 함으로써 Azure에서 보다 정교하고 성능이 높고 안정적인 이벤트 기반 애플리케이션을 빌드할 수 있기를 바랍니다. '
Content: >-
  <p>클라우드 애플리케이션 아키텍처의 핵심 구성 요소로서 이벤트 기반 프로그래밍의 등장에 참여하게 되어 매우 기쁩니다. 다음 기능을 일반적으로 사용할 수 있게 함으로써 Azure에서 보다 정교하고 성능이 높고 안정적인 이벤트 기반 애플리케이션을 빌드할 수 있기를 바랍니다. 이전에 미리 보기로 제공된 다음 기능 집합의 <strong>일반 공급</strong> 에 대해 발표하게 된 것을 자랑스럽게 생각합니다.</p>


  <ol>
      <li>배달 못한 편지</li>
      <li>재시도 정책</li>
      <li>큐를 대상으로 Storage</li>
      <li>하이브리드 연결을 대상으로</li>
      <li>수동 유효성 검사 핸드셰이크</li>
  </ol>


  <p>기능의 GA 상태를 활용하려면 2019-01-01 API 및 <a href="https://docs.microsoft.com/en-us/azure/event-grid/sdk-overview" target="_blank">SDK를</a> 사용하고 있는지 확인합니다. Azure Portal 또는 CloudShell&rsquo;을 사용하는 경우 이미 사용하기에 좋습니다. CLI 또는 PowerShell을 사용하는 경우 CLI용 버전 2.0.56 이상과 PowerShell용 1.1.0 버전이 있는지 확인합니다.</p>


  <h2>배달 못한 편지</h2>


  <p>배달 못 한 글자를 사용하면 중요 업무용 시스템에서 이벤트를 받을 수 있다는 보장을 한 번 이상 받을 수 있습니다. <a href="https://docs.microsoft.com/azure/event-grid/manage-event-delivery" target="_blank">배달 못한 편지 대상 집합을</a> 사용하면 이벤트 처리기가 다운되거나, 권한 부여가 실패하거나, 엔드포인트의 버그가 볼륨으로 과부하되는 경우에도 메시지가 손실되지 않습니다.</p>


  <p>배달 못 한 편지로 각 이벤트 구독을 스토리지 계정에 연결할 수 있으므로 기본 이벤트 파이프라인이 실패하는 경우 Azure Event Grid는 언제든지 사용할 수 있도록 해당 이벤트를 스토리지 계정에 제공할 수 있습니다.</p>


  <h2>재시도 정책</h2>


  <p>재시도 정책은 임시 오류가 발생할 경우 기본 이벤트 파이프라인을 더욱 강력하게 만듭니다. 데드 레터링에서는 시스템에 오래 지속되는 오류가 있는 경우 백스톱을 제공하지만 분산 시스템에서 일시적인 중단만 표시되는 것이 더 일반적입니다.</p>


  <p><a href="https://docs.microsoft.com/azure/event-grid/delivery-and-retry" target="_blank">재시도 정책을 구성</a> 하면 이벤트를 배달 못 한 편지 또는 삭제하기 전에 다시 시도할 횟수 또는 시간을 설정할 수 있습니다. 경우에 따라 이벤트가 얼마나 늦었는지에 관계없이 가능한 한 오랫동안 이벤트를 다시 시도하는 것이 좋습니다. 다른 경우에는 이벤트가 부실하면 값이 없으므로 즉시 삭제할 수 있습니다. 재시도 정책을 사용하면 가장 적합한 배달 일정을 선택할 수 있습니다.</p>


  <h2>큐를 대상으로 Storage</h2>


  <p>Event Grid는 이벤트를 Azure Storage 큐에 직접 푸시할 수 있습니다. <a href="https://docs.microsoft.com/en-us/azure/event-grid/custom-event-to-queue-storage" target="_blank">큐는 이벤트 처리기에 이벤트</a> 수신을 버퍼링하여 제대로 확장할 수 있도록 해야 하는 경우 강력한 이벤트 처리기가 될 수 있습니다. 마찬가지로 이벤트 처리기가 가동 시간을 보장할 수&rsquo; 없는 경우 스토리지 큐를 사이에 배치하면 해당 이벤트를 유지하고 이벤트 처리기가 준비되면 처리할 수 있습니다.</p>


  <p>Storage 큐에는 Event Grid 이벤트의 VNet 삽입을 허용하는 VNet(가상 네트워크) 통합도 있습니다. 이벤트 원본을 VNet 내에 있는 이벤트 처리기에 연결해야 하는 경우 Event Grid에 스토리지 큐에 게시한 다음 큐를 통해 VNet의 이벤트를 사용하도록 지시할 수 있습니다.</p>


  <h2>하이브리드 연결을 대상으로</h2>


  <p>이벤트에 대한 클라우드 리소스에 연결된 상태에서 로컬로 빌드하고 디버그하려는 경우 HTTP 엔드포인트를 노출할 수&rsquo; 없는 온-프레미스 서비스를 사용하거나 잠긴 방화벽 뒤에서 작업해야 하는 경우 <a href="https://docs.microsoft.com/en-us/azure/event-grid/custom-event-to-hybrid-connection" target="_blank">하이브리드 연결을 통해 해당 리소스를 Event Grid에 연결할 수 있습니다</a>.</p>


  <p>이벤트 처리기로서의 하이브리드 연결은 Event Grid를 연결할 HTTP 엔드포인트를 제공합니다. 또한 로컬 리소스에서 동일한 하이브리드 연결 인스턴스로 아웃바운드 WebSocket 연결을 만드는 옵션도 제공합니다. 하이브리드 연결은 Event Grid에서 온-프레미스 리소스로 들어오는 이벤트를 릴레이합니다.</p>


  <h2>수동 유효성 검사 핸드셰이크</h2>


  <p>모든 이벤트 처리기가 엔드포인트 소유권 증명을 제공하기 위해 HTTP 응답을 사용자 지정할 수 있는 것은 아닙니다. 수동 유효성 검사 핸드셰이크를 사용하면 복사 붙여넣기만큼 쉽게 엔드포인트의 권한이 있는 소유자임을 증명할 수 있습니다.</p>


  <p>Event Grid 구독을 등록하면 유효성 검사 이벤트가 유효성 검사 코드를 사용하여 엔드포인트로 전송됩니다. 유효성 검사 코드를 다시 에코하여 유효성 검사 이벤트에 응답할 수 있지만, 편리하지 않은 경우 이제 이벤트에서 <a href="https://docs.microsoft.com/azure/event-grid/security-authentication" target="_blank">포함된 유효성 검사 URL을 복사하여</a> 모든 브라우저에 붙여넣어 엔드포인트의 유효성을 검사할 수 있습니다. 엔드포인트에서 GET을 수행하면 소유권 증명의 유효성이 검사됩니다.</p>


  <p>우리는 당신이이 뉴스에 잘 <em>반응</em> 바랍니다.</p>


  <p>Azure Event Grid 팀</p>
