### YamlMime:Yaml
ms.openlocfilehash: 38d6a33c9a4fdf52f71cbf9a9d5accc9d53783cd
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139901063"
Slug: more-to-explore-configuration-options-unlocked-in-windows-azure-web-sites
Title: '자세히 살펴보기: Windows Azure 웹 사이트에서 잠금 해제된 구성 옵션'
Summary: WAWS(Windows Azure 웹 사이트)에서 웹 사이트를 관리하는 경우 Azure Portal을 사용하여 많은 옵션을 구성할 수 있으며 더 많은 옵션을 자주 추가합니다. 그러나 이미 알고 있는 것처럼...
Content: >-
  WAWS(Windows Azure 웹 사이트)에서 웹 사이트를 관리하는 경우 Azure Portal을 사용하여 많은 옵션을 구성할 수 있으며 더 많은 옵션을 자주 추가합니다. 그러나 이미 알고 있는 것처럼 실제 전원 옵션 중 일부는 사이트의 <strong>web.config </strong>파일을 직접 구성해야만 사용할 수 있습니다. 우리는 당신이 최근에 듣고 행복 할 것이다 확신, 우리는 몇 가지 새로운 옵션을 노출하고 <strong>web.config</strong>사용할 수 있도록했다!


  한동안 IIS에서 웹 사이트를 관리해 온 경우 IIS에 구성을 관리하기 위한 <a href="https://www.iis.net/learn/get-started/planning-your-iis-architecture/the-configuration-system-in-iis-7">복잡한 계층 시스템이</a> 있다는 것을 알 수 있습니다. 이 시스템에는 최상위 <strong>machine.config 및applicationHost.config</strong>파일부터 사이트별 및 <strong> 폴더별 </strong><strong>web.config </strong> 파일까지 여러 수준에 대한 구성 파일이 있습니다.

  Windows Azure 웹 사이트에서는 구성 계층의 다른 파일을 처리하는 복잡성을 제거하여 <strong>web.config</strong> 파일에만 구성 변경 내용을 집중하려고 노력했습니다.


  Azure 웹 사이트에 대한 최근 업데이트로 이제 개발자는 <strong>web.config</strong>위해 잠금 해제된 몇 가지 새로운 옵션을 사용할 수 있습니다. 과거에는 이러한 옵션이 사이트 수준에서 잠겨 있으므로 구성할 수 없습니다(시도하면 사이트에서 오류가 발생).


  예를 들어 Azure 웹 사이트 고객의 일반적인 요청은 동적 및 정적 콘텐츠 압축을 위해 MIME 형식을 조정할 수 있어야 했습니다. IIS 서버의 표준 기본 설치에서 마스터 구성 파일 <strong>applicationHost.config</strong> 파일에는 <strong>텍스트/*, 메시지/, 애플리케이션/* javascript, application/atom+xml</strong> 및 <strong>application/xaml+xml</strong> 정적 MIME 형식에 대해서만 다음과 같은 구성이 있습니다.


  <a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/3718.blog-post-1.28.png-550x526.png"><img class="alignnone  wp-image-132391" alt="3718.blog post 1.28.png-550x526" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/3718.blog-post-1.28.png-550x526.png" width="550" height="170" /></a>


  IIS 서버에서는 사이트 수준 <strong>web.config </strong>파일에서 다른 설정이나 추가 설정을 일반적으로 구성할 수 없도록 이 섹션도 잠깁니다.


  독립 실행형 IIS 서버에서 <strong>applicationHost.config </strong>파일을 쉽게 편집하고 설정을 추가하거나 <strong>httpCompression</strong> 섹션의 잠금을 해제한 다음 사이트 수준에서 구성 옵션을 추가할 수 있습니다.


  Azure 웹 사이트의 변경 내용으로 해당 섹션과 다른 여러 섹션의 잠금을 해제했으며, 이제 사이트의 <strong>web.config</strong> 파일에서 사용자 고유의 옵션을 정의할 수 있습니다. Azure 웹 사이트의 httpCompression 섹션이 약간 변경되어 구문이 간소화되었습니다.


  <a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/6443.Screenshot-11.png-550x526.png"><img class="alignnone  wp-image-132381" alt="6443.Screenshot (11).png-550x526" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/6443.Screenshot-11.png-550x526.png" width="550" height="340" /></a>


  보듯이 <strong>디렉터리 </strong>또는 <strong>구성표 이름을</strong> 지정할 필요가 없으며 <strong>정적 </strong>형식 또는 <strong>동적</strong> 형식에 대한 MIME 형식만 나열하면 됩니다.


  잠금 해제한 다른 섹션의 경우 구문은 일반 IIS 웹 사이트에 사용되는 구문과 유사합니다. 섹션의 전체 목록은 다음과 같습니다. 각 항목은 구성 스키마의 해당 부분과 구성 방법을 설명하는 IIS.NET 대한 문서로 연결됩니다.

  <ul>
   <li><a href="https://www.iis.net/configreference/system.webserver/asp">Asp</a></li>
   <li><a href="https://www.iis.net/configreference/system.webserver/httptracing">httpTracing</a></li>
   <li><a href="https://www.iis.net/configreference/system.webserver/security/access">보안/액세스</a></li>
   <li><a href="https://www.iis.net/configreference/system.webserver/security/authentication/anonymousauthentication">security/authentication/anonymousAuthentication</a></li>
   <li><a href="https://www.iis.net/configreference/system.webserver/serverruntime">serverRuntime</a></li>
   <li><a href="https://www.iis.net/configreference/system.webserver/serversideinclude">serverSideInclude</a></li>
   <li><a href="https://www.iis.net/configreference/system.webserver/tracing">tracing</a></li>
   <li><a href="https://www.iis.net/configreference/system.webserver/webdav">Webdav                </a></li>
   <li><a href="/b/windowsazure/archive/2013/12/09/ip-and-domain-restrictions-for-windows-azure-web-sites.aspx">ipSecurity</a></li>
   <li><a href="/b/windowsazure/archive/2013/08/27/confirming-dynamic-ip-address-restrictions-in-windows-azure-web-sites.aspx">동적 IP 제한</a></li>
  </ul>

  이제 이러한 새 설정을 사용할 수 있게 되었으므로 이제 구성에 대한 유연성이 훨씬 더 높아졌으며, 이를 통해 Azure 웹 사이트 Windows 보다 생산적인 웹 사이트를 빌드할 수 있기를 바랍니다.


  &nbsp;
