### YamlMime:Yaml
ms.openlocfilehash: b999e0800e66bfa38ac5ef828e623b24c79483fa
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139912754"
Slug: net-application-migration-using-azure-app-services-and-azure-container-services
Title: Azure App Services 및 Azure Container Services를 사용하여 .NET 애플리케이션 마이그레이션
Summary: 중요 비즈니스용 앱을 클라우드로 이동하는 방법을 이해해야 하는 개발자 및 솔루션 설계자를 위해 설계된 이 온라인 워크샵 시리즈는 기존 ASP.NET 기반 애플리케이션을 컨테이너 기반 애플리케이션으로 마이그레이션하기 위한 검증된 프로세스를 실습합니다. 5월 3일 수요일과 금요일부터 5월 3일까지 90분 동안 라이브로 참여하여 전문가의 지도를 받고 질문에 대한 답변을 얻을 수 있습니다.
Content: >-
  <p>중요 비즈니스용 앱을 클라우드로 이동하는 방법을 이해해야 하는 개발자 및 솔루션 설계자를 위해 설계된 이 온라인 워크샵 시리즈는 기존 ASP.NET 기반 애플리케이션을 컨테이너 기반 애플리케이션으로 마이그레이션하기 위한 검증된 프로세스를 실습합니다. 5월 3일 수요일과 금요일부터 5월 3일까지 90분 동안 라이브로 참여하여 전문가의 지도를 받고 질문에 대한 답변을 얻을 수 있습니다.</p>


  <p>이 시리즈와 함께 제공되는 선택적(권장되는) 실습 랩은 현재 사용할 수 있는 Azure Platform Services 및 다양한 Azure 컨테이너 솔루션을 활용하여 Virtual Machine 아키텍처에서 Azure로 다중 계층 웹앱 솔루션을 제공하는 POC(개념 증명)를 빌드하는 경험을 제공합니다. 또한 기본 데이터베이스를 SQL 2014 Virtual Machine 아키텍처에서 SQL Azure 마이그레이션합니다.</p>


  <p>이 시리즈의 끝부분에는 컨테이너 개념, Docker 아키텍처 및 작업, Azure Container Services, Azure Kubernetes Services 및 SQL Azure PaaS 솔루션에 대해 잘 이해할 수 있습니다.</p>


  <h2>1부: Azure를 사용한 디지털 앱 변환</h2>


  <p>첫 번째 세션에서는 기존 .NET Framework 애플리케이션을 현대화하는 전략적 방법을 다룹니다. 여기에는 Azure에서 VM 리프트 &amp; 시프트부터 PAAS(Platform as a Service)로의 앱 현대화를 위해 제공하는 다양한 선택 사항과 Azure에서 기본적으로 제공하는 컨테이너 서비스 및 오케스트레이터에 대한 개요가 포함됩니다.</p>


  <p><a href="https://info.microsoft.com/en-us-landing-NETApplicationMigrationUsingContainersPart1DigitalAppTransformationwithAzure.html">요청 시 시청</a></p>


  <h2>2부: ARM 템플릿을 사용하는 코드로서의 인프라</h2>


  <p>ARM(Azure Resource Manager) 템플릿은 코드로서의 인프라에 대한 Azure&rsquo; 응답이며 인프라 리소스를 배포하는 것 이상의 작업을 수행할 수 있습니다. 이 세션에서는 코드로서의 인프라를 통해 더 빠른 실행을 가능하게 하고, 위험을 줄이고, 비용을 절감하고, DevOps 통합하는 방법에 대해 설명합니다. &rsquo;자동화된 배포 및 지속적인 통합을 위해 ARM 템플릿을 사용해야 하는 이유, GitHub Azure 빠른 시작 템플릿을 찾는 방법 및 Visual Studio 사용하여 ARM 템플릿을 작성하는 방법에 대해 알아봅니다.</p>


  <p>ARM 템플릿이 Azure 리소스를 배포하는 방법을 배우는 것 외에도 한 단계 더 나아가 VM 구성을 자동화하는 전체 프로세스를 안내합니다. 이 세션&rsquo;이 끝나면 제공되는 랩을 통해 작업할 수 있습니다. 여기서 Azure 구독을 설치하고 Visual Studio 2017을 사용하여 원본 Virtual Machine 환경을 배포하고 워크샵 시리즈 전체에서 사용할 기준 2계층 애플리케이션 워크로드를 배포합니다.</p>


  <p><a href="https://info.microsoft.com/en-us-landing-NETApplicationMigrationUsingContainersPart2InfrastructureasCodeusingARMtemplates.html">요청 시 시청</a></p>


  <h2>3부: Azure Database Solutions | SQL Azure</h2>


  <p>Well&rsquo;은 보안 및 격리 문제 제거 및 고가용성/재해 복구를 통합하는 방법을 포함하여 SQL, IaaS 및 PaaS 옵션을 포함하는 것으로 시작합니다. &rsquo;주요 기능을 강조 표시할 Azure SQL 배포하는 심층 데모가 표시됩니다.</p>


  <p>&rsquo;그런 다음 마이그레이션 옵션에 대해 자세히 알아보고 데이터베이스 마이그레이션 도구를 강조 표시하여 SQL Management Studio 사용하여 SQL VM 데이터베이스를 SQL Azure 마이그레이션하는 랩을 완료할 수 있습니다&rsquo;.</p>


  <p>2019년 4월 17일 오전 10시/동부 오후 1시</p>


  <p><a href="https://info.microsoft.com/en-us-landing-NETApplicationMigrationUsingContainersPart3AzureDatabaseSolutionsSQLAzure.html">라이브 가입 등록</a></p>


  <h2>4부: Azure App Services | Azure Web Apps</h2>


  <p>이 데모 채워진 세션에서는 배포 슬롯,&rsquo; 크기 조정 및 자동 크기 조정, 가격 책정 계층, 통합 백업 및 Azure Web Apps의 핵심 기능과 강점을 이해할 수 있는 앱 인사이트를 비롯한 주요 기능에 대해 알아봅니다. 세션은 샘플 아키텍처 및 배포 수명 주기를 사용하여 Azure Web Apps for Containers로 마무리됩니다. 이 세션&rsquo;의 랩에서는 레거시 ASP.NET 애플리케이션을 Visual Studio 사용하여 Azure Web Apps로 마이그레이션합니다.</p>


  <p>2019년 4월 19일 오전 10시/동부 오후 1시</p>


  <p><a href="https://info.microsoft.com/en-us-landing-NETApplicationMigrationUsingContainersPart4AzureAppServicesAzureWebApps.html">라이브 가입 등록</a></p>


  <h2>5부: Docker 컨테이너</h2>


  <p>Docker 컨테이너는 글로벌 표준이며 기본적으로 Azure에서 지원되며, 엔터프라이즈는 향후 교정 및 비용 혜택을 위해 레거시 앱을 마이그레이션할 수 있는 흥미롭고 유연한 방법을 제공합니다. 이 세션에서&rsquo;는 Windows Docker 설치, 일반적인 Docker CLI 작업 실행 및 CLI 및 Visual Studio 2017을 사용하여 Docker 이미지를 빌드하는 방법에 대한 자세한 데모를 확인할 수 있습니다. 또한 Well&rsquo;은 Docker 빌드 문제 해결을 위한 중요한 팁을 설명합니다. 이 세션&rsquo;이 끝나면 Windows Docker CE를 사용하여 레거시 ASP.NET 애플리케이션을 컨테이너화하는 랩을 완료할 수 있습니다.</p>


  <p>2019년 4월 24일 오전 10시/동부 오후 1시</p>


  <p><a href="https://info.microsoft.com/en-us-landing-NETApplicationMigrationUsingContainersPart5DockerContainers.html">라이브 가입 등록</a></p>


  <h2>6부: Azure Container Registry | Azure Container Instance</h2>


  <p>Azure Container Registry는 오픈 소스 Docker 레지스트리 2.0을 기반으로 하는 관리되는 Docker 레지스트리 서비스로, Azure 컨테이너 레지스트리를 만들고 유지 관리하여 프라이빗 Docker 컨테이너 이미지를 저장하고 관리할 수 있습니다. Azure Container Instance는 가상 머신을 프로비전할 필요 없이 더 높은 수준의 서비스를 채택할 필요 없이 Azure에서 컨테이너를 실행하는 가장 빠르고 간단한 방법을 제공합니다. &rsquo;ACR과 ACI 둘 다에 대해 알아보고, ACR과 ACI가 긴밀하게 협력하는 방법에 대해 알아봅니다. 세션&rsquo;이 끝나면 Azure Container Registry를 배포하고, Azure Container Instance를 사용하고, 컨테이너화된 워크로드를 실행할 랩을 완료할 수 있습니다.</p>


  <p>2019년 4월 26일 오전 10시/동부 오후 1시</p>


  <p><a href="https://info.microsoft.com/en-us-landing-ExploreusingAzureContainerInstancetoruncontainerizedapplications.html">라이브 가입 등록</a></p>


  <h2>7부: Azure Container Services 및 Azure Kubernetes Services를 사용한 컨테이너 오케스트레이션</h2>


  <p>이 세션에서는 Azure에서 컨테이너 오케스트레이션을 사용하는 방법을 자세히 알아보고 ACS(Azure Container Services) 및 AKS(Azure Kubernetes Services)를 모두 다룹니다. Well&rsquo;은 두 작업의 유사성, 차이점 및 로드맵뿐만 아니라 몇 가지 일반적인 컨테이너 오케스트레이터 작업을 살펴봅니다. Kubernetes를 사용하여 ACS를 배포하고 AKS를 배포할 랩을 준비하려면 자세한&rsquo; 데모를 제공하고 관리 및 배포를 위한 샘플을 제공합니다. &rsquo;AKS에서 Docker 허브 이미지를 실행하는 데모도 표시됩니다.</p>


  <p>2019년 5월 1일 오전 10시/동부 오후 1시</p>


  <p><a href="https://info.microsoft.com/en-us-landing-LearntodeployAzureContainerServiceswithKubernetes.html">라이브 가입 등록</a></p>


  <h2>8부: Azure Kubernetes Services 관리 및 모니터링</h2>


  <p>&rsquo;AKS에서 컨테이너 확장성을 사용하도록 설정하고, AKS를 모니터링하고, AKS에서 Kubernetes 대시보드를 사용하는 방법을 알아봅니다. Well&rsquo;은 Azure Container Services 내에서 Container Registry 이미지를 실행하고, AKS를 스케일링하고, Azure에서 AKS를 모니터링하기 위한 많은 샘플과 자세한 데모를 제공합니다. 이 워크샵 시리즈의 마지막 랩에서는 AKS 관리 및 모니터링에 대해 알아차리게 됩니다.</p>


  <p>2019년 5월 3일 오전 10시/동부 오후 1시</p>


  <p><a href="https://info.microsoft.com/en-us-landing-NETApplicationMigrationUsingContainersPart8ManagingandMonitoringAzureKubernetesServices.html">라이브 가입 등록</a></p>


  <p>모든 세션은 라이브로 전달된 후 요청 시 보기에 기록되고 사용할 수 있으며 랩 및 기타 자료는 GitHub 사용할 수 있습니다.</p>
