### YamlMime:Yaml
ms.openlocfilehash: 120007cbd21f420fb2dac605725bbec905134f30
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139899645"
Slug: networking-for-a-hybrid-application-environment
Title: 하이브리드 애플리케이션 환경에 대한 네트워킹
Summary: David Lef는 LOB(기간 업무) 애플리케이션이 Azure를 사용하여 온-프레미스 환경에서 클라우드로 이동함에 따라 네트워크 환경을 지원하는 데 대한 고려 사항과 과제를 식별합니다.
Content: >-
  <h2>전환 중인 네트워크 지원:&amp; David Lef와 QA 블로그 게시물 시리즈</h2>


  <p><em>Microsoft IT의 수석 네트워크 설계자인 David Lef는 일련의 블로그 게시물에서 기존 인프라에서 완전 무선 클라우드 컴퓨팅 플랫폼으로 전환할 때 네트워크를 지원하는 방법에 대해 설명합니다. Microsoft IT는 전 세계 900개 위치와 220,000명의 사용자를 지원합니다. David는 변화하는 고객 요구와 최신 애플리케이션 디자인을 지원하는 Azure의 클라우드 기반 모델로 네트워크 토폴로지의 진화를 정의하는 데 도움을 주고 있습니다.</em></p>


  <p>David Lef는 LOB(기간 업무) 애플리케이션이 Azure를 사용하여 온-프레미스 환경에서 클라우드로 이동함에 따라 네트워크 환경을 지원하는 데 대한 고려 사항과 과제를 식별합니다.</p>


  <h4><strong>Q:</strong> 역할과 지원 환경을 설명할 수 있나요?</h4>


  <p><strong>A:</strong> Microsoft에서의 역할은 Microsoft IT의 주요 네트워크 설계자입니다. 우리 팀은 전 세계 약 900개의 사이트와 해당 사이트를 연결하는 네트워킹 구성 요소를 지원하며, 이 사이트는 220,000명이 넘는 Microsoft 직원과 공급업체를 대신하여 작업하는 조합으로 사용됩니다. Microsoft 네트워크는 2,500개 이상의 개별 애플리케이션 및 비즈니스 프로세스를 지원합니다. Were&rsquo;는 조직에 유선, 무선 및 원격 네트워크 액세스를 제공하고, 네트워크(네트워크 에지 포함)를 통해 네트워크 보안을 구현하고, 클라우드의 Microsoft Azure 대한 연결을 담당합니다. 내부 Windows Server Active Directory 포리스트와 동기화되는 단일 Azure Active Directory 테넌시를 사용하여 대규모 Azure 테넌시를 지원합니다. ExpressRoute를 사용하여 온-프레미스 데이터 센터에서 Azure로 여러 연결이 있습니다. Azure 테넌시는 광범위한 Azure 리소스를 지원하며, 그 중 일부는 공용 리소스이고 일부는 Microsoft 내부에서 앱 및 서비스로 호스트되지만 Azure 플랫폼에서 호스팅됩니다. 현재 Azure를 사용하여 LOB 앱의 40%를 호스팅하고 있으며, 그 수는 지속적으로 증가하고 있습니다.</p>


  <p><img alt="Figure 1. The Microsoft IT environment" border="0" height="354" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/cab18c22-e373-4e9c-a2ec-ecc784792b51.png" style="border: 0px currentColor; border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; display: inline; background-image: none;" title="그림 1. Microsoft IT 환경" width="480"></p>


  <h4><strong>Q:</strong> 이 마이그레이션이 어떻게 발생했으며 네트워크 팀이 어떻게 지원했는지에 대한 간략한 기록을 제공해 주시겠습니까?</h4>


  <p><strong>A:</strong> 내부 및 외부 앱 및 서비스 솔루션에 사용하던 Azure PaaS(Platform as a Service)로 시작했습니다. PaaS는 Azure에서 제공되는 첫 번째 기본 구성 요소이므로 솔루션을 개발할 때 자연스럽게 시작했습니다. 대부분의 초기 애플리케이션은 Azure에서 완전히 호스트되었습니다. 하이브리드 시나리오는 완전히 개발되거나 지원되지&rsquo; 않았기 때문에 솔루션에서 구현하지 않았습니다&rsquo;.</p>


  <p>그러나 Azure 네트워킹 및 IaaS(Infrastructure as a Service) 구성 요소가 도입되고 완성됨에&rsquo; 따라 Azure 기반 솔루션을 구현하는 방법과 이러한 솔루션이 서로 상호 작용하는 방식 및 온-프레미스 인프라에 훨씬 더 유연하게 대처할 수 있었습니다.</p>


  <p>가장 논리적인 마이그레이션 시나리오를 먼저 해결하는 Azure 마이그레이션 전략을 채택했습니다. 즉, 기본 웹앱, 모든 새 솔루션 및 재설계 대상으로 지정된 솔루션이 있습니다. 다음으로, 대역폭이 크거나 리소스 사용 요구 사항이 있는 앱이나 규제에 영향을 주거나 중요 비즈니스에 중요한 운영에 큰 영향을 미치는 앱과 같이 좀 더 까다로운 앱을 살펴보았습니다. 마지막으로 업데이트하기 어려운 코드가 있는 사용자 지정된 레거시 솔루션과 같이 가장 어렵고 비용이 많이 드는 앱이 남아 있습니다.</p>


  <p><img alt="Figure 2. Azure IT migration roadmap" border="0" height="172" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/ffa8fcb1-c7a5-4fa6-b5e5-5fbbc843e207.png" style="border: 0px currentColor; border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; display: inline; background-image: none;" title="그림 2. Azure IT 마이그레이션 로드맵" width="480"></p>


  <p>LOB(하이브리드 LOB) 앱에 대한 주요 사용 권한은 Azure 테넌트가 데이터 센터에서 Azure에 대한 프라이빗 전용 연결을 얻을 수 있는 기능을 제공하는 ExpressRoute를 추가하고, Azure IaaS의 성숙을 통해 온-프레미스 인프라를 사용하고 인프라의 구성 요소를 수정하지 않고도 Azure 호스팅 가상 머신으로 직접 마이그레이션할 수 있게 해줍니다. 또한 Office 365 같은 SaaS(Software as a Solution) 솔루션을 널리 채택했습니다.</p>


  <p>기본 지원 채널은 하이브리드 솔루션에 필요한 연결을 용이하게 하는 것이었습니다. ExpressRoute 및 데이터 센터를 Azure에 연결하는 데 필요한 구성 및 관리를 통해 많은 연결이 백 엔드에 있지만 Azure 내에서 네트워킹도 관리합니다. 클라우드와 온-프레미스가 혼합된 경우 몇 가지 중요한 보안 및 규정 준수 고려 사항이 있으며&rsquo;, 클라우드의 데이터 및 인프라가 데이터 센터와 마찬가지로 안전하게 유지되도록 부지런히 노력하고 있습니다. 대부분의 Azure 앱과 서비스는 일부 인터넷 터치 포인트에서 사용할 수 있으므로&rsquo; 솔루션 내에서 프런트 엔드와 백 엔드를 구분하는 것이 중요합니다. IaaS에 거주하는 인프라가 공용 인터넷에 노출되는 것을 원하지 않습니다&rsquo;.</p>


  <h4><strong>Q:</strong> 이 여정을 통해 어려움이 바뀌었습니까?</h4>


  <p><strong>A:</strong> 그들은&rsquo; 항상 변화! 변화는 클라우드의 본질이며&rsquo;, 실제로 우리가 직면한 첫 번째 과제는 솔루션, 프로세스 및 메서드가 유동적이고 Azure에서 변화한다는 것을 이해하는 것입니다. 제공 및 변경되는 기능의 연속 스트림이 있습니다. 그 중 일부는 솔루션에 중요하지 않을 수 있지만 다른 일부는 게임 체인저가 될 수 있습니다.</p>


  <p>데이터 센터 관점과 사용자 관점에서 Azure에 연결하는 방법에는 여러 가지가 있다는 것을 알고 있습니다. 가능한 한 Azure의 애플리케이션 소유자가 자신의 앱을 데이터 센터 및 고객에게 연결하는 방법을 선택할 수 있는 자유를 제공하기 위해 노력하고 있습니다.</p>


  <p>조직&rsquo;에서는 먼저 클라우드에 집중하기 위해 전략을 수정하는 방법을 배워야 했습니다. Azure에서 LOB 앱을 호스팅하는 것은 앱이 사용되고 지원되는 방식의 기본적인 변화입니다. Weve&rsquo;는 애플리케이션 소유자 및 고객과 함께 지원 및 통신 채널을 열어 두는 데 부지런히 일해 왔으며, 클라우드의 특성과&rsquo; 클라우드 및 비즈니스에 미치는 영향을 이해하는 것이 중요합니다. 클라우드 우선 모바일 우선 전략은 모든 것이 먼저 Azure로 전달된다는 것을 의미하며&rsquo;, CEO인 Satya Nadella가 주도하고 나머지 조직을 통해 연계된 문화적 변화를 의미합니다. 클라우드 전략의 지속적인 진화를 강조하는 훌륭한 <a href="https://www.microsoft.com/itshowcase/Article/Content/697/Microsoft-IT-cloud-computing-strategies-continue-to-evolve">문서가</a> 있습니다.</p>


  <p>기술적 관점에서 볼 때, 환경의 유동성과 일치하는 방식으로 Azure 리소스를 관리하는 데 도움이 되는 많은 도구와 프로세스가 있습니다. ARM(Azure Resource Manager)의 통합은 Azure 내에서 솔루션 관리 및 구성을 중앙 집중화하고 표준화하는 데 중요했습니다. 리소스 그룹 및 ARM 템플릿은 제대로 구성하고 앱 요구 사항 또는 Azure 기능 변경을 통해 제대로 구성되도록 하는 데 필요한 기능을 제공합니다. &rsquo;기술적으로나 물류적으로 데이터 센터와 Azure를 동시에 유지하는 것은 끊임없는 과제입니다. Azure로의 마이그레이션은 일정한 스트림이므로 데이터 센터 및 Azure 환경의 구성은 일정한 흐름에 있습니다. 우리는 잠시 동안&rsquo; 수행 될 긴 레거시 꼬리를 가지고 있을 것이므로 Azure와 온-프레미스 환경 간의 통신을 가능한 한 사전에 제공하고 관리하고 테넌트와 사용자에게 효과적으로 사용하는 방법을 교육해야 합니다.</p>


  <h2>자세한 정보</h2>


  <p>이 시리즈의 다른 블로그 게시물:</p>


  <ul>
   <li><a href="https://azure.microsoft.com/en-us/blog/supporting-network-architecture-that-enables-modern-work-styles/"><em>최신 작업 스타일을 지원하는 네트워크 아키텍처 지원</em></a></li>
   <li><a href="https://azure.microsoft.com/en-us/blog/engineering-the-move-to-cloud-based-services/"><em>클라우드 기반 서비스로의 이동 엔지니어링</em></a></li>
   <li><a href="https://azure.microsoft.com/en-us/blog/cloud-first-mobile-first-microsoft-moves-to-a-fully-wireless-network/"><em>클라우드 우선, 모바일 우선: Microsoft가 완전 무선 네트워크로 이동</em></a></li>
  </ul>


  <p><a href="https://www.microsoft.com/itshowcase/Article/Content/648/Architecting-your-network-for-successful-Azure-adoption">여기에서</a> Microsoft IT가 네트워크 아키텍처를 어떻게 발전시키는지에 대해 자세히 알아보세요.</p>
