### YamlMime:Yaml
ms.openlocfilehash: b8ed06c6b1a5da9ec6221ac2bd9dc5b60cf8c770
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139908836"
Slug: new-options-to-modernize-your-application-with-azure-sql-database
Title: Azure SQL Database 사용하여 애플리케이션을 현대화하는 새로운 옵션
Summary: 오늘날의 클라우드 중심 세계에서 기업은 클라우드 공급자에 의존하면서 핵심 역량에 점점 더 집중하고 있으며, 필요에 따라 확장되는 저렴한 걱정 없는 컴퓨팅 인프라를 제공합니다. 관리되는 서비스를 사용하면 수익에 도움이 되며, 출시 시간을 개선하고, 궁극적으로 비즈니스를 구동할 수 있습니다.
Content: >-
  <h2>비즈니스에 집중하고 나머지는 우리에게 맡기십시오.</h2>


  <p>오늘날&rsquo; 클라우드 중심 세계에서 기업은 클라우드 공급자에 의존하면서 핵심 역량에 점점 더 집중하고 있으며, 필요에 따라 확장되는 저렴하고 걱정없는 컴퓨팅 인프라를 제공합니다. 관리되는 서비스를 사용하면 수익에 도움이 되며, 출시 시간을 개선하고, 궁극적으로 비즈니스를 구동할 수 있습니다.</p>


  <p>Azure SQL Database 전 세계 38개 데이터 센터에서 수백만 개의 프로덕션 데이터베이스를 관리하는 빠르게 성장하고 완전히 관리되는 관계형 DBaaS(Database-As-A-Service)입니다. 고객은 간단한 트랜잭션 데이터 관리에서부터 전 세계적으로 고급 데이터 처리가 필요한 가장 데이터 집약적이고 중요 업무용 애플리케이션을 구동하는 것까지 광범위한 애플리케이션 및 워크로드를 지원하는 데 Azure SQL Database 사용할 수 있습니다.</p>


  <p>이 블로그 게시물에서 플랫폼을 차별화하고, 흥미로운 새로운 기능을 발표하고, 업계에서 가장 확장 가능하고 안전하며 고객 친화적인 데이터베이스 서비스를 유지하려는 계획에 대한 업데이트를 공유하는 업계 최고의 기능의 몇 가지 예를 공유하고 싶습니다.</p>


  <h2>새 공지 사항: 모든 애플리케이션에 대해 PaaS로 간편하게 리프트 앤 시프트</h2>


  <p>클라우드 산업이 성숙하고 더 많은 기업이 표준 사례로 클라우드 기술을 채택함에 따라 데이터베이스&rsquo; 커뮤니티의 고객들과 이야기를 나눴습니다. 클라우드에서 관리되는 데이터베이스 서비스의 이점을 절대적으로 즐기고 싶다고 말하지만, 지금까지 인스턴스 수준 기능 또는 격리 요구 사항으로 인해 이를 수행할 수 없었습니다. 인스턴스 수준 SQL Server 기능(예: SQL CLR 통합, SQL Server 에이전트, 데이터베이스 간 쿼리 등)에 깊이 투자한 고객은 Azure SQL Database 유사한 기능을 기대합니다. 마찬가지로, 규제가 높은 산업의 고객은 클라우드로 전환할 때 보안을 위해 격리를 유지해야 합니다.</p>


  <h3>관리되는 인스턴스</h3>


  <p>오늘 <strong><em>Managed Instance</em></strong>라는 Azure SQL Database 새 배포 옵션의 미리 보기를 발표했습니다.&nbsp; Managed Instance는 서비스로서의 플랫폼의 이점과 거의 100% SQL Server 호환성을 제공합니다. 여기에는 SQL CLR, SQL Server 에이전트 및 데이터베이스 간 쿼리와 같은 기능이 포함됩니다. 애플리케이션 디자인을 &ndash; 변경하지 않고 인스턴스 수준 기능을 계속 사용하는 관리되는 SQL Server 환경을 상상할 수 있다면 <strong>실제 게임 체인저가 됩니다.&rsquo;</strong>&nbsp;</p>


  <p>eSignature 및 DTM(디지털 트랜잭션 관리)의 글로벌 리더인 DocuSign은 작업 환경에서 Managed Instance 프라이빗 미리 보기를 테스트한 최초의 고객이었습니다. 188개국에서 300,000명 이상의 고객과 2억 명의 사용자에게 서비스를 제공하는 회사로서 데이터베이스의 확장성, 성능 및 관리 효율성은 중요합니다. 그리고 테스트에서 DocuSign은 핵심 플랫폼의 SQL Server 코드를 변경 없이 Managed Instance로 전환&rsquo;하고, 수석 설계자인 Eric Fleishman이 미래에 대한 놀라운 약속을 보여주는 몇 초 만에 &ndash; 쿼리 실행을 시작할 수 &lsquo;있었습니다.</p>


  <p>또한 새로운 <strong>Database Migration Serviceto&nbsp;</strong>가 Managed Instance로의 마이그레이션을&nbsp; 자동화하고, 위험을 감수하고, 가동 중지 시간을 몇 분 단위로 측정하도록 할&#39;있습니다.&nbsp; 이 서비스는 Oracle과 같은 SQL Server 및 비 Microsoft 데이터베이스 시스템을 Azure SQL Database 이동하도록 간소화합니다.</p>


  <p>규제가 높은 산업의&rsquo; 고객을 위해 개인 IP 주소를 지원하는 VNET과 제어된 서비스 업데이트라는 두 가지 중요한 혁신을 도입해야 합니다. VNET을 사용하면 고객은 공용 인터넷에서 데이터베이스 계층을 완전히 격리하고 애플리케이션과 사용자가 있는 다른 클라우드 VNET 또는 온-프레미스 네트워크에 조인할 수 있습니다. 제어된 서비스 업데이트를 통해 고객은 일반 Azure 퍼블릭 클라우드 구독에 배포된 테스트 환경을 실행하여 지속적인 서비스 업데이트를 받을 수 있습니다. 최신 업데이트로 애플리케이션의 유효성을 검사한 후에는 프로덕션 Managed Instance 환경에 예약된 방식으로 업데이트를 적용할 수 있습니다.</p>


  <p>Managed Instance는 현재 프라이빗 미리 보기(<a href="https://sqldatabase-migrationpreview.azurewebsites.net/" target="_blank">등록 페이지</a>)에 있으며&rsquo;, 이 기간 동안 Well은 얼리어답터 고객과 협력하여 가장 광범위한 기존 애플리케이션 집합에 대한 리프트 앤 시프트&rdquo; 요구 사항을 충족&ldquo;하는지 확인합니다. 애플리케이션이 Azure SQL Managed Database Instance에서 작동하는지 확인하는 데 관심이 있거나 사용자 고유의 마이그레이션 작업에 활용하려는 경우 오늘 <a href="https://info.microsoft.com/sql-database-managed-instance-register.html">등록</a>하여 자세한 내용을 확인하세요.</p>


  <p>Managed Instance 제품을 통해 지금까지 Azure SQL Database 혜택을 누릴 수 있는 경로가 없는 SQL Server 커뮤니티의 고객을 위해 클라우드에 대한 브리지(또는 사다리)를 제공합니다.</p>


  <h2>혁신과 진화</h2>


  <p>새로운 Managed Instance 제품과 함께 도입된 진화적 변화와 함께, 이 프리미어 플랫폼을 서비스로 제공하는 데 앞장서기 위해 성능, 인텔리전스, 가용성, 확장성 및 보안 전반에 걸쳐 지속적으로 혁신을 제공합니다.</p>


  <h3>기본 제공 지능형 최적화</h3>


  <p>Azure SQL Database 선택하면 기본 제공 패치, 업데이트, 데이터베이스 백업 및 고가용성을 얻을 뿐만 아니라 <em>기본 제공 인텔리전스</em>도 얻을 수 있습니다. 기본 제공 인텔리전스를 사용하면 데이터베이스 실행 및 관리 비용을 크게 줄이고 애플리케이션의 성능과 보안을 모두 극대화할 수 있습니다.&nbsp; 이 기능 아래에는 SQL Database Advisor, 자동 튜닝 및 적응형 쿼리 처리가 있습니다.</p>


  <h4>SQL Database 관리자</h4>


  <p>수백만 개의 고객 워크로드를 실행하는 Azure SQL Database 방대한 양의 원격 분석 데이터를 수집하고 처리하면서 고객 개인 정보를 완전히 존중합니다. 다양한 알고리즘은 서비스가 애플리케이션에 적용될 수 있도록 지속적으로 원격 분석 데이터를 평가합니다. 이 분석을 기반으로 서비스에서는 특정 워크로드에 맞게 성능 개선 권장 사항을 제공합니다.&nbsp;</p>


  <p>이 기본 제공 인텔리전스는 정확히 어떻게 드러나나요? Azure SQL Database 클러스터<a href="https://docs.microsoft.com/en-us/azure/sql-database/sql-database-advisor" target="_blank">되지 않은 올바른 인덱스를 자동으로 식별</a>하여 고객에게 실행 가능한 권장 사항으로 제공하거나, 고객이 자동 조정 모드로 선택하는 경우 데이터베이스에 대한 변경 내용을 사전에 구현합니다. 또한 이 기능은 각 작업을 자동으로 테스트하고 확인하여 성능이 계속 향상되도록 합니다. 즉, 데이터베이스의 성능을 신중하게 모니터링하고 모든 튜닝 작업 전후에 비교하며 성능이 개선되지 않으면&rsquo; 튜닝 작업이 되돌려집니다.</p>


  <h4>자동 튜닝</h4>


  <p>SQL Database Advisor를 통해 이미 사용할 수 있는 자동 인덱스 튜닝 외에도 Azure SQL Database 곧 새로운 적응 기능 배열을 받게 될 것입니다. 예를 들어 <a href="https://docs.microsoft.com/en-us/sql/relational-databases/automatic-tuning/automatic-tuning" target="_blank">쿼리 계획 자동 튜닝</a> 기능은 쿼리 계획 선택에 대한 안전망&rdquo;을 제공&ldquo;하므로 계획 회귀를 자동으로 수정하여 데이터베이스가 항상 최고 성능으로 실행되도록 지원합니다. 오늘날 Azure SQL Database&nbsp; 위에 SaaS 다중 테넌트 앱을 실행하는 많은&nbsp; 우리 파트너는 자동 성능 조정을 사용하여 애플리케이션이 항상 안정적이고 예측 가능한 성능을 갖도록 하고 있습니다. 이 기능은 갑자기 성능 인시던트가 발생하는 위험을 크게 줄여 줍니다. 또한 고객 기반의 일부가 SQL Server 사용하므로 Azure SQL Database 제공하는 것과 동일한 인덱싱 권장 사항을 사용하여 SQL Server 고객을 돕고 있습니다.</p>


  <h4>적응 쿼리 처리</h4>


  <p>또한 <a href="https://blogs.msdn.microsoft.com/sqlserverstorageengine/2017/04/19/introducing-interleaved-execution-for-multi-statement-table-valued-functions/" target="_blank">다중 문 테이블 반환 함수에 대한 인터리브 실행</a>, <a href="https://blogs.msdn.microsoft.com/sqlserverstorageengine/2016/11/29/introducing-batch-mode-adaptive-memory-grant-feedback/" target="_blank">일괄 처리 모드 메모리 부여 피드백 및 일괄 처리 모드</a> <a href="https://blogs.msdn.microsoft.com/sqlserverstorageengine/2017/04/19/introducing-batch-mode-adaptive-joins/" target="_blank">적응 조</a>인을 포함하여 Azure SQL Database 기능의 적응 쿼리 처리 제품군을 추가하고 있습니다. 이러한 각 적응 쿼리 처리 기능은 유사한 &ldquo;학습 및 적응&rdquo; 기술을 적용하여 역사적으로 난해한 쿼리 최적화 문제와 관련된 성능 문제를 추가로 해결하는 데 도움이 됩니다.</p>


  <h3>글로벌 확장성 및 가용성</h3>


  <p>Azure SQL Database 자동 백업, 지정 시간 복원 및 <a href="https://docs.microsoft.com/en-us/azure/sql-database/sql-database-geo-replication-overview" target="_blank">활성 지역 복제</a>를 포함하여 기본 제공 비즈니스 연속성 및 글로벌 확장성 기능을 제공하므로 동일하거나 전역적으로 분산된 Azure 데이터 센터에서 읽을 수 있는 보조 데이터베이스를 최대 4개까지 구성할 수 있습니다.&nbsp;  예를 들어 대량의 동시 읽기 전용 트랜잭션이 있는 카탈로그 데이터베이스가 있는 SaaS 애플리케이션이 있는 경우 활성 Geo-Replication 사용하여 전역 읽기 규모를 사용하도록 설정하고 읽기 워크로드로 인한 주 데이터베이스에서 병목 상태를 제거할 수 있습니다. &rsquo;또한 최근에 릴리스된 <a href="https://azure.microsoft.com/en-us/blog/azure-sql-database-now-supports-transparent-geographic-failover-of-multiple-databases-featuring-automatic-activation/">자동 장애 조치(failover) 그룹을</a> 사용하면 대규모 데이터베이스 및 탄력적 풀 집합의 투명한 지역 복제 및 장애 조치(failover)를 포함하여 글로벌 규모에서 고가용성 및 부하 분산을 사용하도록 설정할 수 있습니다. 이렇게 하면 관리 오버헤드를 최소화하면서 전역적으로 분산된 SaaS 애플리케이션을 만들 수 있으므로 모든 복잡한 모니터링, 라우팅 및 장애 조치(failover) 오케스트레이션이 SQL Database.</p>


  <h3>업계 최고의 고급 보안</h3>


  <p>최고 수준의 개인 정보를 유지하면서 고객 데이터를 보호하는 것은 항상 Microsoft 및 Data Services 조직의 최우선 과제였습니다. 나는 이전에 <a href="https://blogs.technet.microsoft.com/dataplatforminsider/2017/02/10/microsofts-sql-platform-continues-to-lead-the-market-with-advanced-data-security/" target="_blank">여기에 우리의 보안 투자</a> 에 대해 블로그와 우리가 업계에서 가장 높은 수준의 보안을 계속 제공하는 업계 최고의 보안 기능을 제공하는 방법에 대해 블로그. 이 서비스에는 투명한 데이터 암호화, SQL 위협 탐지, Always Encrypted, Multi-Factor Authentication 등이 포함됩니다.</p>


  <h4>투명한 데이터 암호화</h4>


  <p>보안이 효과적이기 위해서는 사용하기 쉬워야 한다는 것을 알고 있습니다. 예를 들어 이번 달부터 새로 만든 모든 Azure SQL 데이터베이스는 TDE(투명한 데이터 암호화)로 자동으로 보호됩니다. TDE는 스토리지&rsquo; 미디어의 도난으로부터 보호하기 위해 많은 규정 준수 표준에 필요한 입증된 미사용 암호화 기술 SQL. 고객은 Azure Key Vault를 사용하여 보안 및 규격 관리에서 TDE 암호화 키 및 기타 비밀을 관리할 수 있습니다.</p>


  <p>GEP는 Azure SQL Database 및 TDE를 사용하는 클라우드 기반 조달 소프트웨어 플랫폼을 제공하는 다국적 기업입니다.&nbsp; 자신의 말로:</p>


  <blockquote>

  <p>&ldquo;Azure 관리형 TDE는 고객에게 엄격한 데이터 암호화 정책을 준수하는 데 도움이 되었으며&nbsp; 많은 데이터베이스를 안전하게 관리하는 데 안심할 수 있게 해 주었습니다. 주요 이점은 애플리케이션 성능에 영향을 주지 않고 모든 고객에게 TDE 암호화를 제공할 수 있다는 것입니다.&rdquo; SAthyan Narasingh, GEP의 엔지니어링 관리자</p>

  </blockquote>


  <h4>SQL 위협 검색</h4>


  <p>또한 <a href="https://docs.microsoft.com/en-us/azure/sql-database/sql-database-threat-detection" target="_blank">SQL 위협 탐지</a>는 데이터베이스에서 잠재적으로 유해한 중요한 데이터에 액세스하려는 시도를 지속적으로 모니터링합니다. 예를 들어 E-Learning 회사의 경우 SQL 위협 탐지는 회사가 직원 자격 증명을 사용하지 않도록 설정하는 것을 잊은 후 중요한 데이터를 반출하는 불만을 품은 전직 직원의&rsquo; 활동을 식별했습니다. SQL 위협 탐지는 과거 액세스 위치 및 쿼리 패턴과 현재를 비교하고, 경고를 발생시켰으며, 고객이 누출을 신속하게 닫고 손상을 최소화하는 데 도움을 줄 수 있었습니다.</p>


  <h4>Always Encrypted</h4>


  <p>Azure SQL Database 상시 암호화를 사용하여 쿼리를 처리하는 동안 비행 중, 미사용 데이터 및 쿼리 처리 중에 중요한 데이터를 보호하는 유일한 데이터베이스 시스템입니다. Always Encrypted는 중요한 데이터의 도용을 비롯한 위반에 대해 최상의 데이터 보안을 제공하는 업계 최고의 기능입니다. 예를 들어 <a href="https://docs.microsoft.com/en-us/sql/relational-databases/security/encryption/always-encrypted-database-engine" target="_blank">Always Encrypted</a>를 사용하면 고객&rsquo; 신용 카드 번호는 쿼리 처리 중에도 <u><em>항상</em></u> 데이터베이스에 암호화되어 저장되므로 해당 데이터를 처리해야 하는 권한이 있는 직원 또는 애플리케이션에서 사용 시점에 암호를 해독할 수 있습니다.</p>


  <p>다음은 Always Encrypted가 <a href="https://www.medproctor.com/">Med+Proctor</a> - 가 빠르게 성장하는 의료 스타트업을 시작하는 데 어떻게 도움이 되었는지입니다.</p>


  <blockquote>

  <p>&quot;종종 의료 서비스 및 시작 SaaS 공급자와 최신 및 쉽게 감사 가능한 데이터 보안 간에 상당한 차이가 있습니다.&nbsp; Always Encrypted는 자체 솔루션을 만들거나 비용이 많이 드는 타사 도구를 구입하지 않고도 열 암호화, 관리형 액세스 및 키 회전을 위한 도구를 제공하여 Med+Proctor의 격차를 해소했습니다.&quot; - Andy Howden, CIO, <a href="https://www.medproctor.com/">Med+Proctor</a></p>

  </blockquote>


  <h4>Multi-Factor Authentication</h4>


  <p>Azure SQL Database 사용자는 이제 MFA(Multi-Factor Authentication)도 지원하는 Azure Active Directory 인증을 통해 Single Sign-On의 이점을 누릴 수 있습니다. MFA는 SSMS 또는 Visual Studio 같은 SQL Server 및 Azure SQL Database 걸쳐 점점 더 많은 도구와 서비스에 적합한 인증 옵션입니다.</p>


  <h2>경계 밀기</h2>


  <p>Azure SQL Database 모든 데이터 집약적 애플리케이션에 강력한 플랫폼을 제공하며 워크로드를 클라우드로 전환하는 것이 그 때보다 쉬워졌습니다. 앞으로도 다음&nbsp; 영역에서 경계를 계속 밀어붙일 것입니다.</p>


  <p><strong>규모: </strong> 몇 달 전에 탄력적 풀에 대한 더 많은 가격-성능 선택 항목을 추가했습니다. 여기에는 최대 4,000개의 DTU까지 높은 컴퓨팅 풀, 시작 가격이 낮은 50개의 DTU 풀, 풀당 데이터베이스 한도가 높아 데이터베이스당 비용이 효과적으로 감소했습니다. 4월에는 P11 및 P15 데이터베이스의 스토리지 한도를 1TB에서 4TB로 증가했습니다.&nbsp; 그리고 5월에는 가장 큰 Premium 탄력적 풀의 스토리지 제한이 750GB에서 4TB로 증가했습니다.&nbsp; 앞으로 몇 달 동안 Azure SQL Database 스토리지 한도를 더욱 높이고 독립 실행형 데이터베이스 및 탄력적 풀 모두에 대해 DTU와 별도로 스토리지를 구매할 수 있는 기능을 제공할 것입니다.</p>


  <p><strong>모니터링:</strong> 최근에 클라우드 데이터베이스의 중요한 메트릭을 대규모로 모니터링하고 중앙 집중식 위치에서 관심 메트릭에 대한 경고를 설정하는 데 도움이 되는 <a href="https://blogs.technet.microsoft.com/msoms/2017/02/21/azure-sql-analytics-solution-public-preview/" target="_blank">OMS 솔루션을</a> 출시했습니다. 곧 모든 클라우드 데이터베이스인 쿼리 저장소에서 실행되는 고급 &ldquo;플라이트 데이터 레코더&rdquo; 기능을 통해 지속적으로 공급되는 정밀도 쿼리 인사이트를 사용하여 이 솔루션을 개선할 예정입니다. 이렇게 하면 많은 데이터베이스에서 동일한 쿼리를 실행하는 SaaS 애플리케이션에 대한 유용한 인사이트를 제공하고 모든 데이터베이스에서 리소스를 가장 많이 사용하는 쿼리를 집계로 고정하는 데 도움이 됩니다.</p>


  <p><strong>기본 제공 인텔리전스:</strong> 앞으로 몇 달 동안 자체 최적화 및 자체 모니터링 데이터베이스 서비스에 대한 비전을 실현하는 데 훨씬 더 가까워질 것입니다. 이 혁신적인 기술은 전투 테스트되었으며 지난 1 년 동안 성숙해졌습니다. 이 글을 쓰면서 서비스의 약 50,000개 데이터베이스에서 이미 쉬지 않는 상태로 실행되고 있습니다. <em>모든 </em>서비스 데이터베이스에 대한 기본 설정을 자동으로 튜닝하는 성능을 만들 계획입니다. 즉, 클라우드 규모에서 모든 고객 데이터베이스에 대한 자동 계획 수정뿐만 아니라 비클러스터형 인덱스 조정 및 유지 관리를 제공합니다. Azure SQL Database 사용하는 모든 개발자 또는 IT Professional 노력을 투자하지 않고도 기본 제공 인텔리전스에서 가져온 향상된 성능과 안정성을 활용할 수 있습니다.</p>


  <p><strong>보안:</strong> 우리의 목표는 기업 고객이 Azure SQL Database 사용 가능한 보안 기능을 사용하여 전문 지식 수준과 관계없이 데이터베이스에 대한 효과적인 방어 전략을 구현하고 유지 관리할 수 있도록 하는 것입니다. 예를 들어 SQL 데이터베이스 보안은 원하는 보호 수준(예: 높은 비즈니스 영향)을 식별하고 데이터베이스를 보호하기 위해 적절한 정책을 적용하는 것만큼 간단해야 한다고 생각합니다. 수준을 정의하면 시스템에서 중요한 데이터와 데이터를 보호하는 데 필요한 기능을 식별하는 등 나머지 작업을 수행합니다. 데이터베이스가 사용 중인 동안 Azure SQL Database 구성의 변경 내용과 악의적인 공격의 징후일 수 있는 비정상적인 활동을 지속적으로 모니터링합니다.</p>


  <h2>시작하기만 하면</h2>


  <p>우리는 기본적으로 심층 보안을 제공하고, 마찰 없는 마이그레이션을 가능하게 하고, 최첨단 관계형 데이터베이스 기술과 함께 기계 학습 및 적응 기술을 사용하여 성능을 최적화하여 목표에 더 가까워지는 기능에 계속 투자할 것입니다. 우리는 비용 절감, 빠른 출시 시간, 기본 제공 인텔리전스 및 Azure SQL Database 오늘 제공하는 기본 제공 관리를 활용할 것을 초대합니다!&nbsp; 데이터 센터 또는 운영 팀이 필요하지 않습니다&rsquo;.&nbsp; 대신, 사용자와 조직에 가장 중요한 것에 집중하고 나머지는 우리에게 맡깁니다!</p>


  <p>Microsoft 데이터 그룹의 다른 공지 사항에 대해 알아보려면 여기에서 Joseph Siroshs&rsquo; <a href="https://aka.ms/m91203" target="_blank">Build 2017 공지 블로그 게시물을</a> 읽어보세요.</p>
