### YamlMime:Yaml
ms.openlocfilehash: 7951c2c49183bed869dff42cd61fc960cf4617c2
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139908267"
Slug: new-app-usage-monitoring-capabilities-in-application-insights
Title: Application Insights 새 앱 사용 모니터링 기능
Summary: Azure 모니터링 도구의 목표는 애플리케이션에 대한 전체 스택 모니터링을 제공하는 것입니다. 이 "스택"의 맨 위는 앱의 클라이언트 쪽이 아니라 사용자 자체입니다. 이해...
Content: >-
  <p>Azure 모니터링 도구의 목표는 애플리케이션에 대한 전체 스택 모니터링을 제공하는 것입니다. 이 &ldquo;스택&rdquo;의 맨 위는 앱&rsquo;의 클라이언트 쪽이 아니며&rsquo; 사용자 자체입니다. 사용자 동작을 이해하는 것은 비즈니스에서 관심 있는 메트릭을 구동하기 위해 앱을 올바르게 변경하는 데 중요합니다.</p>


  <p>Application Insights 사용 현황 분석 도구의 최근 개선 사항은 팀이 전반적인 사용량을 더 잘 이해하고, 성능이 고객 환경에 미치는 영향을 자세히 알아보고, 사용자 흐름에 대한 가시성을 높이는 데 도움이 될 수 있습니다.</p>


  <h2>사용자, 세션 및 이벤트에 대한 더 빠르고 통찰력 있는 환경</h2>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/764d0829-35c1-4c30-b251-abeec286f1e0.jpg"><img alt="users" border="0" height="1113" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/884a05b9-bf56-4288-bf48-67679e260b81.jpg" style="border: 0px currentcolor; border-image: none; display: inline; background-image: none;" title="사용자" width="2000"></a></p>


  <p>애플리케이션 사용을 이해하는 것은 개발 팀과 스마트하게 투자하는 데 중요합니다. 애플리케이션은 빠르고 안정적이며 고가용성일 수 있지만 사용자가&rsquo; 많지 않은&rsquo; 경우 비즈니스에 가치를 기여하지 않습니다.</p>


  <p>애플리케이션 Insights 사용자, 세션 및 이벤트 도구를 사용하면 가장 기본적인 사용 현황 분석 질문에 &ldquo;쉽게 답변할 수 있습니다. 내 애플리케이션과 각 기능을 얼마나 사용하나요?&rdquo;</p>


  <p>사용자, 세션 및 이벤트 도구를 다시 빌드하여 응답성을 높일&#39;있습니다. 일일 및 월간 사용 현황 메트릭의 새로운 사이드바를 사용하면 증가 및 보존 추세를 파악할 수 있습니다. 각 메트릭을 클릭하면 MAU(월간 활성 사용자)를 분석하기 위한 사용자 지정 통합 문서와 같은 자세한 정보가 제공됩니다. 또한 새로운 &ldquo;사용자&rdquo; 모임 카드는 일부 고객의 신발에 추가되어 타임라인에서 여정을 단계별로 따라갈 수 있도록 합니다.</p>


  <p><a href="https://docs.microsoft.com/azure/application-insights/app-insights-usage-segmentation" target="_blank">사용자, 세션 및 이벤트에</a> 대해 자세히 알아봅니다.</p>


  <h2>영향 도구 소개</h2>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/a6b7ffec-efc6-41bf-abd7-6cd5cdbe3aa0.jpg"><img alt="impact" border="0" height="1113" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/672a6fdf-6215-4ece-b008-0ecf3dba42e9.jpg" style="border: 0px currentcolor; border-image: none; display: inline; background-image: none;" title="영향" width="2000"></a></p>


  <p>느린 페이지가 앱에서 사용자 참여 문제의 원인을 로드하나요?</p>


  <p>Application Insights 새로운 영향 도구를 사용하면 쉽게 찾을 수 있습니다. 앱에서 페이지를 선택하고 해당 페이지에서 사용자 작업을 선택하면 영향 도구는 페이지 로드 시간별로 전환율을 그래프로 표시합니다. 이렇게 하면 성능으로 인해 사용자가 이탈하는지 쉽게 파악할 수 있습니다.</p>


  <p>영향 도구는 성능 영향 이상을 분석할 수 있습니다. 원격 분석의 모든 속성 또는 측정값과 변환 속도 간의 상관 관계를 찾을 수 있습니다. 따라서 변환이 국가, 장치 유형 등에 따라 어떻게 달라지는지 확인할 수 있습니다.</p>


  <p>우리 팀에서 영향 도구는 느린 페이지 로드 시간이 감소된 전환율과 밀접한 상관 관계가 있는 여러 위치를 발견했습니다. 하지만 영향 도구는 목표로 해야 하는 페이지 로드 시간을 정량화했는데, 이는 여전히 전환율이 가장 느린 가장 느린 페이지 로드 시간입니다.</p>


  <p><a href="https://docs.microsoft.com/azure/application-insights/app-insights-usage-impact" target="_blank">영향 도구</a>에 대해 자세히 알아봅니다.</p>


  <h2>사용자 흐름에 대한 추가 기능</h2>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/7a5b4263-832d-4804-9924-aa56ab319989.jpg"><img alt="userflows" border="0" height="1113" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/6e203740-d61e-4ede-9f1b-384776fb15e7.jpg" style="border: 0px currentcolor; border-image: none; display: inline; background-image: none;" title="userflows" width="2000"></a></p>


  <p>이제 사용자 흐름 도구는 사용자가 사이트의 일부 페이지 또는 사용자 지정 이벤트를 방문하기 전에 어떤 작업을 했는지 분석할 수 있습니다. 새 &ldquo;세션 시작&rdquo; 노드는 사용자가 사이트에 입력하는 방법을 확인할 수 있도록 사용자 세션에서 노드가 처음 있었던 위치를 보여 줍니다.</p>


  <p>새 분할 기준 옵션을 사용하면 노드를 속성 값으로 분할하여 보다 자세한 사용자 흐름 시각화를 만들 수 있습니다. 예를 들어 팀에서 단추 클릭&rdquo;과 같이 &ldquo;지나치게 일반적인 이름으로 사용자 지정 이벤트 이름을 수집하고 있다고 가정해 보겠습니다&rsquo;. 단추 이름&rdquo; 사용자 지정 차원으로 분할하여 클릭한 단추를 구분하여 사용자 동작을 &ldquo;더 잘 이해할 수 있습니다. 그런 다음 시각화&rsquo;에서 단추 클릭 위치 단추 이름 = 저장&ldquo;&rdquo;, 단추 클릭 위치 단추 이름 = 편집&rdquo; 등의 효과&ldquo;에 대한 노드가 표시됩니다.</p>


  <p>Weve&rsquo;는 사용자 흐름도 몇 가지 더 작게 개선했습니다. 이제 시각화가 더 작은 화면 크기에 더 잘 적응합니다. &ldquo;둘러보&rdquo;기 단추를 사용하면 사용자 흐름 도구에서 더 많은 것을 얻는 방법을 단계별로 살펴볼 수 있습니다. 또한 노드에서 컨트롤을 숨기고 표시하면 시각화에 대한 정보의 밀도를 더 쉽게 제어할 수 있습니다.</p>


  <p><a href="https://docs.microsoft.com/azure/application-insights/app-insights-usage-flows" target="_blank">사용자 흐름</a>에 대해 자세히 알아봅니다.</p>
