### YamlMime:Yaml
ms.openlocfilehash: cc77b8e9329e3e3a99c888867fca6d03c4537f5a
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139908264"
Slug: new-application-insights-functionality-on-azure-websites-with-the-application-insights-website-extension
Title: 애플리케이션 Insights 웹 사이트 확장을 사용하는 Azure Websites의 새 애플리케이션 Insights 기능
Summary: 애플리케이션 Insights 개발 팀이 애플리케이션을 360° 보기로 볼 수 있도록 설계된 Azure Preview 포털에서 사용할 수 있는 미리 보기 서비스입니다.
Content: >-
  <a href="https://azure.microsoft.com/en-us/services/application-insights/" target="_blank">애플리케이션 Insights</a> 개발 팀이 빠른 &amp; 강력한 문제 해결, 진단 및 사용 현황 인사이트를 통해 가용성, 성능 및 사용량 전반에 걸쳐 애플리케이션을 360° 볼 수 있도록 설계된 Azure Preview 포털에서 사용할 수 있는 미리 보기 서비스입니다.


  새 애플리케이션 Insights 웹 사이트 확장은 Azure 애플리케이션 Insights 팀과 Azure Websites 팀 간의 긴밀한 협업의 결과입니다.


  웹 사이트에서 이 확장을 사용하도록 설정하면 모든 애플리케이션 종속성 및 관련 통계를 볼 수 있습니다. 드릴다운하여 특정 요청과 관련된 종속성과 웹 사이트 또는 웹 애플리케이션의 성능에 미치는 영향을 확인할 수도 있습니다.

  <p align="center"><a href="https://acom.azurecomcdn.net/80C57D/blogmedia/blogmedia/2015/01/08/AppInsights.png"><img class="size-large wp-image-242121" alt="New Application Insights functionality on Azure Websites with the Application Insights Website extension" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/AppInsights-554x369.png" width="554" height="369" /></a></p>

  위의 그림은 드릴다운의 예를 보여줍니다. 여기서는 원격 종속성에 대한 호출이 SQL 75ms가 걸린 것을 볼 수 있습니다.


  <a href="https://blogs.msdn.com/b/visualstudioalm/archive/2015/01/07/application-insights-and-azure-websites.aspx">Vlad Joanovic</a>의 블로그 게시물에서 이에 대한 자세한 기술 세부 정보 및 구성 지침을 Visual Studio 블로그에서 확인할 수 있습니다.


  앞으로도 Azure Applications Insight 팀과 협력하여 Azure Websites에 더 많은 기능을 제공할 예정입니다.


  &nbsp;
