### YamlMime:Yaml
ms.openlocfilehash: 45785d7031ab8f5b8735b0d169f6c1ec1e15632e
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139901571"
Slug: new-azure-stack-developer-features-to-build-intelligent-hybrid-applications
Title: 지능형 하이브리드 애플리케이션을 빌드하는 새로운 Azure Stack 개발자 기능
Summary: 이번 주 빌드에서는 Azure 및 Azure Stack을 통해 개발자가 비즈니스에 필요한 모든 곳에서 지능형 애플리케이션을 빌드할 수 있는 방법을 보여 줍니다. 작년에 Azure Stack을 시작한 이후,...
Content: >-
  <p>이번 주 빌드에서는 Azure 및 Azure Stack을 통해 개발자가 비즈니스에 필요한 모든 곳에서 지능형 애플리케이션을 빌드할 수 있는 방법을 보여 줍니다. 작년에 Azure Stack을 시작한 이후 Azure Stack에 혁신을 지속적으로 제공하고 Azure와의 일관성을 유지합니다.</p>


  <p>&rsquo;아래에서 알림의 개요와 출시 이후 몇 가지 주요 업데이트에 대한 요약을 찾을 수 있습니다.</p>


  <h2>에지의 IoT 및 AI</h2>


  <p>Azure 서비스에 데이터를 가져올 수&rsquo; 없는 경우 Azure Stack은 Azure 애플리케이션 플랫폼을 확장하고 Azure 서비스를 데이터에 제공합니다. 네트워크 대기 시간이 짧거나 완전히 연결이 끊긴 에지 시나리오의 경우 특히 중요합니다.</p>


  <p>Edge는 연결이 제한된 위치에서 정기적으로 운영되지만 여전히 클라우드의 기능을 사용하려는 Chevron과 같은 고객에게 특히 유용합니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/ca668cef-6672-4d5d-9249-8c067aa1433c.png"><img align="left" alt="Chevron" border="0" height="69" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/17b4c0d6-3e77-4dad-a216-f8de69ff4000.png" style="margin: 6px 14px 0px 0px; border: 0px currentcolor; border-image: none; float: left; display: inline; background-image: none;" title="ChevronChevron" width="61"></a>&quot;은 기술에 대한 투자의 유산을 가지고 있으며, 클라우드는 데이터를 최적화하고 새로운 방식으로 비즈니스에 가치를 제공하는 데 도움이 됩니다. 따라서&rsquo;&rsquo; 위치와 관계없이 클라우드의 기능을 활용하고 데이터 주권 및 기타 규정을 준수할 수 있는 Microsoft Azure Stack과 같은 강력한 하이브리드 클라우드 솔루션을 갖게 되어 매우 기쁩니다. Chevron은 연결이 보장되지 않는 환경에서 작동하므로 Azure Stack 및 Azure를 사용하는 기능은 우리에게 판도를 바꿀 수 있는 기능이며, 비즈니스를 혁신하는 데 더 많은 용도를 모색하기를 기대합니다.&quot; 빅토리아 해리스, 매니저, 퍼블릭 클라우드, 셰브론</p>


  <ul>
   <li>최근, 하노버 Messe 2018에서 Azure IoT 팀은 <a href="https://blogs.microsoft.com/iot/2018/04/23/hannover-messe-2018-manufacturers-put-their-trust-in-microsofts-industrial-iot-platform/" target="_blank"><strong>Azure Stack용 Azure IoT Hub가 개발 중이라고 발표했습니다</strong></a>. 이 작업을 통해 고객과 파트너는 온-프레미스 또는 에지 시나리오에서 부분적으로 또는 완전히 실행되는 산업용 IoT 솔루션을 빌드할 수 있습니다.</li>
   <li>에지에서 AI를 사용하여 빠르게 시작하고 실행하려는 고객을 위해 Microsoft <strong>Machine Learning 서버는 현재 Azure Stack 마켓플레이스에서 사용할 수 있습니다</strong>. 해당 마켓플레이스 이미지를 사용하면 R-server 및 Azure Machine Learning Workbench를 사용하여 작업 환경을 쉽게 만들 수 있습니다.</li>
  </ul>


  <h2>하이브리드 클라우드 애플리케이션 및 도구</h2>


  <p>Azure SDK는 Azure 및 Azure Stack을 모두 대상으로 할 수 있습니다. 즉, 두 클라우드에 대해 언어와 동일한 개발 모델을 선택할 수 있습니다. 현재 Azure SDK는 Azure Stack에서 Go, Ruby 및 Python에 대한 API 프로필을 지원합니다. <strong>Were&rsquo;는 올 여름 .NET 및 기타 언어에 대한 API 프로필 기능을 사용하도록 설정하여 Azure SDK 지원을 Azure Stack으로 계속 확장합니다.</strong> 또한 Azure Stack의 최신 기능을 나타내는 <strong>새 API 프로필을 게시</strong> 하고 있습니다. <a href="https://docs.microsoft.com/en-us/azure/azure-stack/user/azure-stack-version-profiles" target="_blank">설명서</a>에서 API 버전 프로필에 대해 자세히 알아볼 수 있습니다.</p>


  <h2>하이브리드 DevOps</h2>


  <p>Hybrid Cloud는 애플리케이션 및 데이터가 호스팅되는 방식에 유연성이 필요한 조직에 대한 많은 기존 장애물을 제거한 반면, Azure 및 Azure Stack을 사용하여 최신 DevOps 지원하는 방법을 자주 묻습니다. <strong>Azure 및 Azure Stack에서 CI/CD와 같은 DevOps 시나리오를 지원하도록 VSTS(Visual Studio Team Services) 호스팅 DevOps 서비스가 확장되고 있음을</strong> 발표하게 되어 기쁩니다.</p>


  <p>특히 <strong>RM(VSTS Release Management)에서 Azure Stack 구독에 연결하는 기능을 추가했습니다</strong>. 또한 Were&rsquo;는 <a href="https://docs.microsoft.com/en-us/visualstudio/releasenotes/tfs2018-update2" target="_blank">TFS 2018 업데이트 2 GA 릴리스</a>에서 온-프레미스 TFS(Team Foundation Server) 고객에게 이와 동일한 기능을 제공합니다. 이제 이 새로운 기능을 통해 고객은 환경 구성 방법(Azure, Azure Stack 또는 하이브리드 클라우드 시나리오)에 관계없이 VSTS Release Management 주문형 배포 또는 VSTS 또는 TFS로 구동되는 CI/CD 파이프라인의 일부로 애플리케이션을 쉽게 배포할 수 있습니다.</p>


  <p>이 기능을 활용하려면 기존 애플리케이션에 대한 코드 변경이 필요하지 않습니다. 릴리스 정의 편집기 내에서 Azure 구독&rdquo; 드롭다운을 통해 &ldquo;사용하도록 설정하는 다른 VSTS RM 배포 대상과 동일한 기능을 사용하여 Azure Stack에 연결하기만 하면 됩니다.</p>


  <h2>하이브리드 클라우드 애플리케이션</h2>


  <p>&rsquo;또한 Azure 및 Azure Stack에서 작업을 시작하는 데 도움이 되는 <strong>첫 번째 하이브리드 클라우드 애플리케이션 솔루션을 게시</strong>하게 되어 기쁩니다. &rsquo;연결, ID 및 CI/CD 설정의 기본 사항부터 살펴보겠습니다.</p>


  <p>더 많은 고급 패턴을 계속 릴리스할 예정이며 <a href="https://aka.ms/azsdevtutorials" target="_blank">솔루션 페이지에서</a> 세부 정보를 볼 수 있습니다.</p>


  <h2>하나의 Azure 에코시스템</h2>


  <p>Microsoft는 고객이 적합한 소프트웨어를 실행할 인프라와 일치시키는 선택과 유연성을 오랫동안 지원해 왔으며, Azure Stack은 차세대 클라우드 네이티브 애플리케이션에 대한 기본 약속을 확장하는 데 도움이 됩니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/a557a746-d55f-4b6d-9084-97c8836e7537.png"><img alt="Microsoft Azure Stack" border="0" height="814" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/a2a7a8e7-09c3-4ff5-86f5-70037f59cf20.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="Microsoft Azure 스택" width="1513"></a></p>


  <ul>
   <li>Azure Stack 팀은 <strong>템플릿화된 Service Fabric 및 Kubernetes 클러스터의 미리 보기 릴리스를</strong> 발표하게 되어 기쁩니다. 이렇게 하면 Azure Stack의 IaaS 기능을 사용하여 마이크로 서비스 및 컨테이너 기반 워크로드를 실행하는 데 도움이 됩니다. 이러한 방식으로 고객은 클라우드 네이티브 워크로드에 투자하고 온-프레미스에 배포할 수 있습니다. 이 작업은 Azure Stack 사용자에 대한 배포 및 작업을 단순화하고 표준화합니다. <a href="https://aka.ms/azsk8" target="_blank">Kubernetes 템플릿</a> 및 <a href="https://aka.ms/azssf" target="_blank">Service Fabric 템플릿</a>을 사용해 보는 방법에 대해 자세히 알아볼 수 있습니다.</li>
   <li>Pivotal은 Pivotal Cloud Foundry 2.2가 6월에 Azure Stack에서 GA가 될 것이라고 발표했습니다. &ldquo;Azure Stack과 결합된 Pivotal Cloud Foundry는 하이브리드 일관성을 제공하여 온-프레미스 및 클라우드에서 운영 효율성과 개발자 생산성을 높입니다. PCF 및 Azure Stack을 사용하면 작업을 시작할 수 있습니다.&rdquo; &ndash; Ian Andrews, VP Product, Pivotal. Azure 및 Azure Stack의 Pivotal Cloud Foundry에 대해 자세히 알아보려면 Pivotal <a href="https://aka.ms/pcfonazurestack" target="_blank">블로그 게시물을</a> 확인하세요.</li>
  </ul>


  <h2>지난 6개월 동안 지속된 혁신</h2>


  <p>Azure Stack은 지속적인 혁신을 통해 Azure와 일관성을 유지하도록 설계되었습니다. 지난 몇 개월 동안 개발자가 탐색할 주요 항목 중 일부는 다음과 같습니다.</p>


  <ul>
   <li><strong>이제 Azure Stack은 여러 장애 도메인에서 가용성 집합을 지원합니다.</strong> 클라우드 애플리케이션 개발자는 Azure에서 가용성 집합을 사용하여 워크로드에 대한 고가용성을 보장하고 기본 유지 관리 및 중단으로부터 자신을 보호해 왔습니다. Azure Stack을 사용하여 이 기능을 사용자 고유의 시설로 가져올 수 있습니다.</li>
   <li><strong>Azure Stack에서 Azure Storage Services API 버전 2017-04-17을 릴리스했습니다.</strong> 이렇게 하면 Azure Stack 사용자가 URL 간 복사본을 수행하여 Azure와 Azure Stack 간의 데이터 이동을 간소화할 수 있습니다. 이는 Azure 및 Azure Stack에 걸쳐 있는 하이브리드 애플리케이션을 만들려는 고객에게 특히 유용합니다.</li>
   <li><strong>Azure Stack에 대한 준수 평가 보고서가 완료되었습니다.</strong> 고객이 클라우드 애플리케이션에 대한 사용자 지정 규정 요구 사항을 충족하도록 돕는 것은 Azure Stack의 전세 임무 중 하나입니다. 따라서&rsquo; 고객이 이 복잡하고 시간이 많이 걸리는 작업을 탐색할 수 있도록 많은 작업을 수행합니다. 보고서에 대해 자세히 알아보고 아키텍처를 고려할 수 있는 방법을 알아보려면 <a href="https://azure.microsoft.com/en-us/blog/compliance-assessment-reports-for-azure-stack-are-now-available/" target="_blank">블로그 게시물을</a> 확인하세요.</li>
  </ul>


  <p>&rsquo;무대 뒤에서 벌어지고 있는 일부 작품을 공유하는 것은 항상 흥미 롭습니다. <a href="https://aka.ms/AzureStackUserVoice" target="_blank">사용자 의견</a> 커뮤니티에서 Azure Stack으로 무엇을 생각하고 무엇을 하고&#39;있는지 알려주세요.</p>


  <p>나탈리아 맥케비치우스<br>

  파트너 디렉터 프로그램 관리, Azure Stack<br>

  @natmack</p>
