### YamlMime:Yaml
ms.openlocfilehash: 15bf0affdffca297f648844f33ba40fb296a7b8c
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139908846"
Slug: new-configurable-idle-timeout-for-azure-load-balancer
Title: '신규: Azure Load Balancer 대한 구성 가능한 유휴 시간 제한'
Summary: 이제 Azure Load Balancer PaaS 및 IaaS Cloud Services에 대해 구성 가능한 TCP 유휴 시간 제한을 지원한다는 사실을 발표하게 되어 기쁩니다.
Content: >-
  이제 Azure Load Balancer Cloud Services 및 Virtual Machines에 대해 구성 가능한 TCP 유휴 시간 제한을 지원한다는 사실을 발표하게 되어 기쁩니다. 이 기능은 <a href="https://msdn.microsoft.com/en-us/library/azure/ee460799.aspx" target="_blank">서비스 관리 API</a>, <a href="https://azure.microsoft.com/en-us/documentation/articles/install-configure-powershell/" target="_blank">PowerShell</a> 또는 <a href="https://msdn.microsoft.com/en-us/library/windowsazure/ee758711.aspx" target="_blank">서비스 모델을</a> 사용하여 구성할 수 있습니다.

  <h2>개요</h2>

  기본 구성에서 Azure Load Balancer '유휴 시간 제한' 설정은 4분입니다.


  즉, tcp 또는 http 세션에서 시간 제한 값 이상의 비활성 기간이 있는 경우 클라이언트와 서비스 간에 연결이 유지된다는 보장은 없습니다.


  연결을 닫으면 클라이언트 애플리케이션에 "기본 연결이 닫혔습니다. 활성 상태로 유지되어야 하는 연결이 서버에 의해 닫혔습니다."와 같은 오류 메시지가 표시됩니다.


  더 긴 기간 동안 연결을 활성 상태로 유지하는 일반적인 방법은 TCP Keep-alive를 사용하는 것입니다( <a href="https://msdn.microsoft.com/en-us/library/system.net.servicepoint.settcpkeepalive.aspx" target="_blank">여기서</a> .NET 예제를 찾을 수 있음). 연결에서 활동이 검색되지 않은 경우 패킷이 전송됩니다. 진행 중인 네트워크 활동을 유지하면 유휴 시간 제한 값이 적중되지 않으며 연결이 오랫동안 유지됩니다.


  TCP Keep-alive는 배터리가 제약 조건이 아닌 시나리오에서 잘 작동하지만 일반적으로 모바일 애플리케이션에 유효한 옵션은 아닙니다. 모바일 애플리케이션에서 TCP Keep-alive를 사용하면 디바이스 배터리가 더 빨리 소모될 수 있습니다.


  이러한 시나리오를 지원하기 위해 구성 가능한 유휴 시간 제한에 대한 지원이 추가되었습니다. 이제 4분에서 30분 사이의 기간 동안 설정할 수 있습니다. 이 설정은 인바운드 연결에서만 작동합니다.


  <a href="https://acom.azurecomcdn.net/80C57D/blogmedia/blogmedia/2014/08/Tcp-Idle-Timeout-.png"><img style="padding-top: 0px; padding-left: 0px; padding-right: 0px; border: 0px;" title="Tcp 유휴 시간 제한 " alt="Tcp Idle Timeout " src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/Tcp-Idle-Timeout-_thumb.png" width="330" height="410" border="0" /></a>


  &nbsp;

  <h2>시나리오</h2>

  PowerShell 또는 서비스 관리 API를 통해 <a href="https://azure.microsoft.com/en-us/documentation/articles/virtual-machines-set-up-endpoints/" target="_blank">가상 머신</a> 의 엔드포인트에 대한 TCP 시간 제한 구성


  PowerShell 또는 서비스 관리 API를 통해 Load-Balanced 엔드포인트 집합에 대한 TCP 시간 제한을 구성합니다.


  Instance-Level 공용 IP에 대한 TCP 시간 제한 구성


  <a href="https://msdn.microsoft.com/en-us/library/windowsazure/ee758711.aspx" target="_blank">서비스 모델을</a> 통해 웹/작업자 역할에 대한 TCP 시간 제한을 구성합니다.

  <h4></h4>

  <h2>PowerShell 예제</h2>

  <a href="https://github.com/Azure/azure-sdk-tools/releases/tag/v0.8.5-July2014" target="_blank">최신 Azure PowerShell</a> 다운로드하고 설치해야 합니다.


  &nbsp;

  <h3>Instance-Level 공용 IP에 대한 TCP 시간 제한을 15분으로 구성합니다.</h3>

  <pre class="prettyprint">Set-AzurePublicIP –PublicIPName webip –VM MyVM -IdleTimeoutInMinutes 15</pre>

  IdleTimeoutInMinutes는 선택 사항입니다. 설정하지 않으면 기본 시간 제한은 4분입니다. 이제 해당 값을 4분에서 30분 사이로 설정할 수 있습니다.


  &nbsp;

  <h3>Virtual Machine에서 Azure 엔드포인트를 만들 때 유휴 시간 제한 설정</h3>

  <pre class="prettyprint">Get-AzureVM -ServiceName "mySvc" -Name "MyVM1" | Add-AzureEndpoint -Name "HttpIn" -Protocol "tcp" -PublicPort 80 -LocalPort 8080 -IdleTimeoutInMinutes 15| Update-AzureVM</pre>

  &nbsp;

  <h3>유휴 시간 제한 구성 검색</h3>

  <pre class="prettyprint">PS C:\&gt; Get-AzureVM –ServiceName “MyService” –Name “MyVM” | Get-AzureEndpoint


  VERBOSE: 6:43:50 PM - Completed Operation: Get Deployment


  LBSetName : MyLoadBalancedSet


  LocalPort : 80


  Name : HTTP


  Port : 80


  Protocol : tcp


  Vip : 65.52.xxx.xxx


  ProbePath :


  ProbePort : 80


  ProbeProtocol : tcp


  ProbeIntervalInSeconds : 15


  ProbeTimeoutInSeconds : 31


  EnableDirectServerReturn : False


  Acl : {}


  InternalLoadBalancerName :


  IdleTimeoutInMinutes : 15</pre>

  &nbsp;

  <h3>부하 분산된 엔드포인트 집합에 대한 TCP 시간 제한 설정</h3>

  엔드포인트가 부하 분산 엔드포인트 집합의 일부인 경우 부하 분산 엔드포인트 집합에서 TCP 시간 제한을 설정해야 합니다.

  <pre class="prettyprint">Set-AzureLoadBalancedEndpoint -ServiceName "MyService" -LBSetName "LBSet1" -Protocol tcp -LocalPort 80 -ProbeProtocolTCP -ProbePort 8080 -IdleTimeoutInMinutes 15</pre>

  &nbsp;

  <h2>클라우드 서비스 예제</h2>

  <a href="https://azure.microsoft.com/blog/2014/08/04/announcing-release-of-visual-studio-2013-update-3-and-azure-sdk-2-4/" target="_blank">.NET 2.4용 Azure SDK</a>를 활용하여 클라우드 서비스를 업데이트할 수 있습니다.


  .csdef에서 Cloud Services용 엔드포인트 설정을 지정합니다. Cloud Services 배포의 TCP 시간 제한을 업데이트하려면 배포를 업그레이드해야 합니다. 단, 공용 IP에 대해서만 TCP 시간 제한을 지정하는 경우는 예외입니다. 공용 IP 설정은 .cscfg에 포함되어 있으므로 배포 업데이트 및 업그레이드를 통해 업데이트할 수 있습니다.


  아래에 .csdef에서 엔드포인트 설정을 변경하는 예제가 나와 있습니다.

  <pre class="prettyprint">&lt;WorkerRole name="worker-role-name" vmsize="worker-role-size" enableNativeCodeExecution="[true|false]"&gt;
    &lt;Endpoints&gt;
      &lt;InputEndpoint name="input-endpoint-name" protocol="[http|https|tcp|udp]" localPort="local-port-number" port="port-number" certificate="certificate-name" loadBalancerProbe="load-balancer-probe-name" idleTimeoutInMinutes="tcp-timeout" /&gt;
    &lt;/Endpoints&gt;
  &lt;/WorkerRole&gt;The .cscfg changes for the timeout setting on Public IPs are:


  &lt;NetworkConfiguration&gt;
    &lt;VirtualNetworkSite name="VNet"/&gt;
    &lt;AddressAssignments&gt;
      &lt;InstanceAddress roleName="VMRolePersisted"&gt;
        &lt;PublicIPs&gt;
          &lt;PublicIP name="public-ip-name" idleTimeoutInMinutes="timeout-in-minutes"/&gt;
        &lt;/PublicIPs&gt;
      &lt;/InstanceAddress&gt;
    &lt;/AddressAssignments&gt;
  &lt;/NetworkConfiguration&gt;</pre>

  &nbsp;

  <h2>API 예제</h2>

  <a href="https://msdn.microsoft.com/en-us/library/azure/ee460799.aspx">서비스 관리 API</a>를 사용하여 TCP 유휴 시간 제한을 구성할 수 있습니다.


  x-ms-version 헤더가 버전 2014-06-01 이상으로 설정되어 있는지 추가해야 합니다.


  &nbsp;

  <h3>배포의 모든 Virtual Machines에서 지정한 부하 분산된 입력 엔드포인트의 구성 업데이트</h3>

  <strong>요청</strong>

  <pre class="prettyprint">POST https://management.core.windows.net/&lt;subscription-id&gt;/services/hostedservices/&lt;cloudservice-name&gt;/deployments/&lt;deployment-name&gt;</pre>

  <strong>응답</strong>

  <pre class="prettyprint">&lt;LoadBalancedEndpointList xmlns="" xmlns:i="https://www.w3.org/2001/XMLSchema-instance"&gt;


  &lt;InputEndpoint&gt;


  &lt;LoadBalancedEndpointSetName&gt;endpoint-set-name&lt;/LoadBalancedEndpointSetName&gt;


  &lt;LocalPort&gt;local-port-number&lt;/LocalPort&gt;


  &lt;Port&gt;external-port-number&lt;/Port&gt;


  &lt;LoadBalancerProbe&gt;


  &lt;Path&gt;path-of-probe&lt;/Path&gt;


  &lt;Port&gt;port-assigned-to-probe&lt;/Port&gt;


  &lt;Protocol&gt;probe-protocol&lt;/Protocol&gt;


  &lt;IntervalInSeconds&gt;interval-of-probe&lt;/IntervalInSeconds&gt;


  &lt;TimeoutInSeconds&gt;timeout-for-probe&lt;/TimeoutInSeconds&gt;


  &lt;/LoadBalancerProbe&gt;


  &lt;LoadBalancerName&gt;name-of-internal-loadbalancer&lt;/LoadBalancerName&gt;


  &lt;Protocol&gt;endpoint-protocol&lt;/Protocol&gt;


  &lt;IdleTimeoutInMinutes&gt;15&lt;/IdleTimeoutInMinutes&gt;


  &lt;EnableDirectServerReturn&gt;enable-direct-server-return&lt;/EnableDirectServerReturn&gt;


  &lt;EndpointACL&gt;


  &lt;Rules&gt;


  &lt;Rule&gt;


  &lt;Order&gt;priority-of-the-rule&lt;/Order&gt;


  &lt;Action&gt;permit-rule&lt;/Action&gt;


  &lt;RemoteSubnet&gt;subnet-of-the-rule&lt;/RemoteSubnet&gt;


  &lt;Description&gt;description-of-the-rule&lt;/Description&gt;


  &lt;/Rule&gt;


  &lt;/Rules&gt;


  &lt;/EndpointACL&gt;


  &lt;/InputEndpoint&gt;


  &lt;/LoadBalancedEndpointList&gt;</pre>
