### YamlMime:Yaml
ms.openlocfilehash: 8e2efc00e6d843a16edecf7aec7f29f15855088a
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139898528"
Slug: new-azure-iot-offerings-simplify-iot-application-development
Title: 새로운 Azure IoT 제품은 IoT 애플리케이션 개발을 간소화합니다.
Summary: '우리는 기업이 개념 증명에서 프로덕션으로 이동하는 IoT의 티핑 포인트에 있습니다. 현재는 IoT 애플리케이션을 대규모로 관리하여 이 데이터에 대한 대량의 데이터와 추론을 실시간으로 수집하여 프로세스, 환경을 최적화하고 새 솔루션을 만들 수 있습니다. '
Content: >-
  <p>우리는 기업이 개념 증명에서 프로덕션으로 이동하는 IoT의 티핑 포인트에 있습니다. 현재는 IoT 애플리케이션을 대규모로 관리하여 이 데이터에 대한 대량의 데이터와 추론을 실시간으로 수집하여 프로세스, 환경을 최적화하고 새 솔루션을 만들 수 있습니다. 또한 디바이스 및 센서는 점점 더 정교해지고 AI를 에지에서 실행할 수 있게 되어 농업, 스마트 제조, 스마트 건물 및 공간 등과 같은 주요 산업에서 새로운 혁신의 기회를 창출하고 있습니다.</p>


  <p>올해 4월에는 고객이 IoT를 더 쉽게 활용할 수 있도록 신제품, 솔루션, 파트너십, 프로그램 등을 혁신하기 위해 IoT 및 인텔리전트 에지에 <a href="https://blogs.microsoft.com/iot/2018/04/04/microsoft-will-invest-5-billion-in-iot-heres-why/" target="_blank">5B 투자를</a> 발표했습니다. Were&rsquo;는 고객에게 이를 제공하는 혁신의 속도를 자랑스럽게 생각합니다. 이 모멘텀&rsquo;을 바탕으로 <a href="https://azure.microsoft.com/en-us/services/azure-sphere/" target="_blank">Azure Sphere</a> 및 <a href="https://azure.microsoft.com/en-us/services/digital-twins/" target="_blank">Azure Digital Twins</a>를 포함한 IoT 및 에지에서 새로운 혁신을 제공했으며 <a href="https://azure.microsoft.com/en-us/services/iot-edge/" target="_blank">Azure IoT Edge</a>, <a href="https://azure.microsoft.com/en-gb/services/azure-maps/" target="_blank">Azure 지도</a> 및 <a href="https://azure.microsoft.com/en-us/services/iot-central/" target="_blank">Azure IoT Central</a>을 일반 공급으로 가져왔습니다.</p>


  <p>오늘 커넥트(); 개발자 컨퍼런스에서는 풍부한 데이터 스트림을 클라우드에서 에지로 IoT 애플리케이션으로 가져오는 추가 기능과 IoT 개발 프로세스를 가속화하는 솔루션을 발표합니다.</p>


  <h2>IoT 솔루션에서 데이터를 관리하고 활용하는 새로운 기능</h2>


  <ul>
   <li><a href="https://aka.ms/asa-on-iot-edge" target="_blank"><strong>이제 IoT Edge의 Azure Stream Analytics가 일반 공급</strong></a><strong>됩니다.</strong> ASA(Azure Stream Analytics)는 Azure IoT Edge에 강력한 스트림 처리 기능을 제공하여 개발자가 데이터를 처리하고 로컬로 조건에 응답할 수 있도록 합니다. Azure IoT Edge의 ASA를 사용하면 고객이 대기 시간이 짧은 명령 및 제어가 필요하거나, 클라우드에 대한 연결이 제한되거나, 대역폭이 제한되거나, 특정 규정 준수 요구 사항이 있는 시나리오에서 중요할 수 있는 에지와 클라우드 간에 분석을 쉽게 이동할 수 있습니다.</li>
   <li><a href="https://azure.microsoft.com/en-us/blog/simplifying-confidential-computing-azure-iot-edge-security-with-enclaves-public-preview/" target="_blank"><strong>공개 미리 보기에서 IoT Edge enclave 보안 약속</strong></a><strong>:</strong> Were&rsquo;는 이제 에지의 디바이스에 대해 Open Enclave SDK를 통해 사용하는 &ndash; 동안 기밀 컴퓨팅 &ndash; 을 수행하거나 데이터 및 코드를 보호하는 방법을 제공합니다. Open Enclave는 Azure IoT Edge 보안 관리자와 통합되어 에지 개발자가 액세스할 수 있도록 합니다.</li>
   <li><a href="https://aka.ms/tsi-update-blog" target="_blank"><strong>Azure Time Series Insights 공개 미리 보기의 새로운 기능</strong></a><strong>:</strong> Azure Time Series Insights 고객이 IoT 디바이스에서 생성된 수십억 개의 시계열 측정값에서 신속하게 인사이트를 수집할 수 있도록 하는 완전 관리형 엔드투엔드 IoT 분석 솔루션입니다. 이 데이터의 가치를 최대화하고 운영 인텔리전스를 구동하기 위해 Microsoft는 광범위한 산업용 IoT 데이터 분석 시나리오를 지원하도록 시계열 Insights 제품을 업데이트하고 있습니다. 이제 고객은 시계열 모델을 통해 들어오는 원격 분석 데이터에 풍부한 컨텍스트화를 추가하여 운영 인사이트를 구동하고, 애플리케이션&rsquo; 요구 사항에 따라 IoT 데이터를 웜 또는 콜드 다중 계층 스토리지 &ndash; 에 저장하고, 고급 기계 학습 및 분석 솔루션과 원활하게 통합하여 예측 분석을 추진할 수 있습니다. 시계열 Insights 자산 기반 운영 인사이트를 풍부한 임시 분석과 결합하는 향상된 사용자 환경을 추가합니다. 이 릴리스의 일부로 Microsoft는 새로운 종량제&rsquo; 가격 책정 모델을 도입하여 &lsquo;고객에게 IoT 비즈니스에서 요구하는 가격 책정 확장성과 유연성을 제공합니다.</li>
   <li><a href="https://aka.ms/s1tier" target="_blank"><strong>Azure 지도 S1 SKU</strong></a><strong>:</strong> Azure 지도 간단하고 안전한 위치 API를 사용하여 데이터에 지리 공간적 컨텍스트를 추가하고 지리 공간적 인텔리전스를 IoT 디바이스에 추가하는 매핑, 탐색 및 트래픽 서비스의 포트폴리오입니다. 고객에게 향상된 서비스 옵션을 제공하기 위해 Microsoft는 표준 S0 제품을 보완하기 위해 Azure 지도 대한 새로운 S1 가격 책정 계층을 도입하고 있습니다. 2018년 12월 4일부터 제공되는 S1 제품은 엔터프라이즈 규모 배포를 위해 Azure 지도 초당 50개 이상의 쿼리, 고급 기능이 필요한 솔루션 및 중요 업무용 애플리케이션이 필요한 애플리케이션의 프로덕션 규모 배포를 위한 향상된 서비스 수준을 제공합니다.</li>
   <li><strong>Azure 지도 파트너십:</strong> Azure 지도 개발자를 위한 도구를 강화하고 모바일 데이터 및 분석 공급자와 긴밀한 관계를 구축하여 지리적 위치 서비스에서 리더십을 지속적으로 강화하고 있습니다. Microsoft는 대중 교통 분석 분야의 글로벌 리더인 Moovit과 새로운 파트너십을 발표하고 있습니다. <a href="https://moovit.com/" target="_blank">Moovit</a>은 실시간 대중 교통 데이터를 Azure 지도 직접 통합하여 개발자가 2019부터 운송 및 현장 서비스 물류를 관리하는 기업을 위해 더 풍부하고 정교한 앱을 빌드할 수 있도록 지원합니다. 이 파트너십은 개발자에게 위치 정보 및 스마트 시티 인사이트에 대한 엔드 투 엔드 대상을 제공하여 도시 교통 계획자가 사람들의 흐름을 최적화하는 동시에 소매업체, 소비자 및 더 많은 애플리케이션에 대한 더 나은 솔루션을 가능하게 합니다.</li>
  </ul>


  <h2>IoT 솔루션 개발 가속화</h2>


  <p>6월에는 고객이 Azure Stream Analytics 및 Azure Machine Learning 같은 클라우드 워크로드를 배포하여 IoT 디바이스에서 직접 실행할 수 있도록 <a href="https://azure.microsoft.com/en-us/blog/azure-iot-edge-generally-available-for-enterprise-grade-scaled-deployments/" target="_blank">Azure IoT Edge에 대한 일반 공급 및 오픈 소스 런타임</a>을 발표했습니다. <a href="https://azuremarketplace.microsoft.com/en-us/marketplace/apps/category/internet-of-things?page=1&amp;subcategories=iot-edge-modules" target="_blank">Azure Marketplace</a>를 통해 제공되는 미리 빌드된 에지 모듈을 인증하고 표시하여 에지 솔루션 개발을 가속화하고 있습니다. 솔루션 개발자는 <a href="https://docs.microsoft.com/en-us/azure/marketplace/iot-edge-module" target="_blank">여기에서 시작된</a> 에지 IP 오늘&mdash; 설정을 소개하고 수익을 창출할 수 있습니다.</p>


  <p>한동안 Microsoft는 완전히 사용자 지정 가능한 IoT 솔루션을 신속하게 개발하고 배포하는 방법으로 고객에게 <a href="https://www.azureiotsolutions.com/Accelerators" target="_blank">Azure IoT 솔루션 가속기를</a> 제공했습니다. 커넥트,&rsquo; 그 중 두 가지에 대한 추가 개선 사항의 집합을 발표, 특히:</p>


  <ul>
   <li><strong>Azure IoT 디바이스 시뮬레이션:</strong> Microsoft는 개발자가 개발 중인 IoT 솔루션을 테스트하는 고급 디바이스 시뮬레이션을 만들어 강력하고 확장 가능한 솔루션 개발을 간소화할 수 있도록 합니다. 자세한 내용은 Azure 블로그에서 Azure IoT 디바이스 시뮬레이션&rdquo;을 사용하여 IoT 솔루션 개발 및 테스트 가속화를 참조"><a href="https://azure.microsoft.com/en-us/blog/accelerating-iot-solution-development-and-testing-with-azure-iot-device-simulation/" target="_blank" title="&ldquo;https://azure.microsoft.com/en-us/blog/accelerating-iot-solution-development-and-testing-with-azure-iot-device-simulation/preview/하세요.</a>

   <ul>
    <li>샘플 시뮬레이션을 통해 빠르게 시작하고 실행할 수 있습니다.</li>
    <li>빠른 사용자 지정 디바이스를 만들거나 JavaScript를 사용하여 고급 디바이스 모델 만들기</li>
    <li>저장된 디바이스 모델을 사용하여 시뮬레이션 다시 실행</li>
    <li>여러 디바이스 유형을 사용하여 복잡한 디바이스 채우기 시뮬레이션</li>
    <li>처리량 메트릭 및 통합 <a href="https://azure.microsoft.com/en-us/services/iot-hub/" target="_blank">IoT Hub</a> 차트 보기</li>
   </ul>
   </li>
   <li><strong>Azure IoT 원격 모니터링: </strong>이 오픈 소스 솔루션을 업데이트하면 운영자가 IoT 솔루션의 모든 패싯을 보다 쉽게 관리할 수 있습니다.&nbsp; <ul>
    <li>IoT Edge 디바이스에 에지 모듈 배포</li>
    <li>디바이스 경고에 대한 응답으로 이메일 알림과 같은 작업 트리거</li>
    <li>자동 디바이스 관리를 사용하여 디바이스 업데이트 관리</li>
    <li>Azure Time Series Insights 사용하여 디바이스 데이터 시각화</li>
   </ul>
   </li>
  </ul>


  <p>Were&rsquo;는 또 다른 강력한 기능을 IoT 시장에 도입하게 되어 매우 기쁩니다. <a href="https://www.azure.com/iot" target="_blank">오늘 고객 경험을 시작</a>하려면 이러한 최신 공지 사항을 확인하세요!</p>
