### YamlMime:Yaml
ms.openlocfilehash: 7a64e301a699ec67120698b25c786f4ab4c047ff
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139908262"
Slug: new-application-insights-metric-widget-for-visual-studio-team-services
Title: Visual Studio Team Services 대한 새 애플리케이션 Insights 메트릭 위젯
Summary: 애플리케이션 Insights 데이터를 워크플로에 통합하는 데 도움이 되는 VSTS(Visual Studio Team Services) 대시보드에 대한 메트릭 위젯을 개발했습니다.
Content: >-
  <p>애플리케이션 Insights 정보를 일일 워크플로&rsquo;에 더 잘 통합하기 위한 지속적인 노력의 일환으로 VSTS(Visual Studio Team Services) 대시보드에 대한 메트릭 위젯을 개발했습니다. 설치 및 설정이&rsquo; 매우 간단하며 Azure Portal을 통해 볼 수 없는 경우에도&rsquo; 원격 분석 및 진단 데이터를 감시하는 데 도움이 됩니다.</p>


  <h3>애플리케이션 Insights 메트릭 위젯 가져오기 및 설치</h3>


  <p>앱 다운로드 Insights 메트릭 위젯 위젯</a>을 다운로드하고 설치<a href="https://marketplace.visualstudio.com/items?itemName=ms-appinsights.ApplicationInsightsWidgets" target="_blank" title="하려면 먼저 Visual Studio Marketplace에서 앱 다운로드를"> 찾아야 합니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/e0f0bdfd-2bfe-4fa0-ac15-111a25618671.png"><img alt="image" border="0" height="399" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/c38c5091-99e2-4f48-807f-e5a7c0b21b55.png" style="border: 0px currentColor; border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; display: inline; background-image: none;" title="이미지" width="496"></a></p>


  <p>VSTS 대시보드에서 화면 오른쪽 아래에 있는 편집 단추를 클릭하고 이제 목록에 표시할 애플리케이션 Insights 메트릭 위젯을 선택합니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/c4867f95-4eaf-416c-bd8e-7d01571ce802.png"><img alt="image" border="0" height="399" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/710db69b-cb12-4d0b-b039-a76f7de22e1e.png" style="border: 0px currentColor; border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; display: inline; background-image: none;" title="이미지" width="321"></a></p>


  <p><em>[참고: 위젯이 목록에 표시되지 않으면 웹 페이지를 새로 고칩니다.]</em></p>


  <h3>메트릭 위젯 구성</h3>


  <p>&rsquo;이제 위젯을 구성할 준비가 되었습니다. 이 프로세스는 매우 간단합니다. 애플리케이션 Insights 리소스에서 메트릭 데이터를 반환하려면 위젯에 애플리케이션 ID 및 API 키를 제공해야 합니다. 이러한 두 매개 변수를 찾으려면 Azure Portal에서 애플리케이션 Insights 리소스에 대한 설정<strong>/API Access</strong>를 확인합니다.</p>


  <p><img alt="API Acces in Azure Portal" height="398" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/AppInsights_HowToFindAppIdAndApiKey.png" width="546"></p>


  <p>위젯에 대한 구성 대화 상자는 대시보드에 추가할 때 자동으로 열렸어야 합니다. 다음 단계는 앱 ID 및 API 키를 구성 대화 상자&nbsp;의 적절한 필드에 복사/붙여넣기만 하면 추가 구성 필드가 활성화됩니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/0ab6ccf9-535b-4fcd-977d-6f20a10ae3ed.png"><img alt="ConfigurationPageWithNotes_FakeAppIdandArrow" border="0" height="674" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/d24ca4c6-f138-45b1-8068-db76c8370b6e.png" style="border: 0px currentColor; border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; display: inline; background-image: none;" title="ConfigurationPageWithNotes_FakeAppIdandArrow" width="313"></a></p>


  <p>이제 메트릭을 추적하려는 집계(예: 합계, 평균) 및 시간 범위와 함께 추적하려는 원하는 메트릭(드롭다운 목록은 지정된 리소스에 사용할 수 있는&rsquo; 메트릭에서만 생성됨)을 쉽게 선택할 수 있습니다. 이러한 작업을 제공했으면&rsquo; 저장&rdquo; 단추를 누르&ldquo;고&rsquo; 모두 완료했습니다! 메트릭 위젯은 VSTS 대시보드에서 사용 가능하고 활성화되어야 합니다.</p>


  <h3>위젯 사용</h3>


  <p>이 시점에서&rsquo; 위젯 측면에서 수행해야 하는 작업은 별로 없습니다. 대시보드에서 원하는 위치로 위치를 분명히 재배치할 수 있습니다. 한 가지 주의&rsquo;할 점은 위젯에서 데이터를 자동으로 새로 고치려면 대시보드에 대해 자동 새로 고침 옵션을 선택해야 한다는 것입니다. 대시보드의 오른쪽 위에 있는 설정 아이콘을 클릭하고 대시보드&rdquo; 자동 새로 고침 상자를 선택하여 &ldquo;이 옵션을 찾을 수 있습니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/02ab230b-955d-47e4-96a3-1b9800c9d121.png"><img alt="image" border="0" height="403" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/74feb298-7104-4e3a-a931-a2d78b777243.png" style="border: 0px currentColor; border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; display: inline; background-image: none;" title="이미지" width="366"></a></p>


  <p>위젯이 표시하는 내용을 명확히 하려면 제목, 추적된 메트릭(집계), 메트릭 값 및 시간 범위가 표시됩니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/425b9813-fb00-4faf-be41-ee3be951f5f4.png"><img alt="image" border="0" height="162" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/47985e53-7fa1-4203-a7aa-6afdff416f48.png" style="margin: 0px; border: 0px currentColor; border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; display: inline; background-image: none;" title="이미지" width="162"></a></p>


  <p>대시보드에 위젯을 여러 번 추가하여 다양한 메트릭 또는 여러 리소스를 동시에 추적할 수 있습니다. 이는 동일한 API 키에 대해 1분 기간 내에 수행할 수 있는 메트릭 호출 수에 제한이 있다는 점에 중요합니다. 그러나 제한은 60이므로 매우 바쁘고 복잡한 대시보드를 함께 배치하지 않는 한&rsquo; 해당 제한에&rsquo; 도달하지 않을 수 있습니다. 그러나 대시보드에 매우 많은 수의 메트릭을 동시에 표시해야 하는 경우 해당 시나리오를 처리하기 위해 추가 API 키를 생성해야 할 수 있습니다. 하지만, 특히 여러 리소스에서 다양한 메트릭을 많이 추적하는 경우 이러한 모든 항목이 실제로 얼마나 관련이 있는지 자문해 볼 것을 제안합니다. 모든 대시보드를 함께 볼 필요가 없다고&rsquo; 가정하고, VSTS에서 여러 대시보드를 정의할 수 있으며, 이 방법이 더 좋은 방법이 될 수 있습니다.</p>


  <p>많은 시나리오에서 모범 사례일 수 있는 또 다른 흥미로운 작업은 대시보드의 앱 Insights 위젯 근처에 배치할 기본 markdown 타일을 추가하는 것입니다. 우려되는 예상 메트릭 값 또는 임계값을 게시할 수 있습니다. 이 값은 팀이 보고 있는 데이터를&rsquo; 읽는 방법을 알려줍니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/201212e8-336b-4442-9cea-08fb40d2996b.png"><img alt="image" border="0" height="165" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/cc329d0a-4e31-4f08-bbdc-ac5d96301cca.png" style="margin: 0px; border: 0px currentColor; border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; display: inline; background-image: none;" title="이미지" width="166"></a></p>


  <p>위젯 자체가 이러한 항목을 나타내는 데 도움이 되는 방법을 조사하고 있지만, 이 초기 릴리스에서는 숫자가 팀에 의미하는 바를 쉽게 전달할 수 있는 좋은 방법입니다.</p>


  <p>마지막으로 위젯을 클릭하면 빠른 탐색을 위해 Azure Portal이 열립니다. 사용자를 특정 리소스로 직접 이동시키는 이 탐색의 가능성을 조사하고 있습니다(아마도 이 아이디어에 대한 메트릭 탐색기 &ndash;&rsquo;wed love 피드백에 착륙).</p>


  <h3>다음 단계</h3>


  <p>이것은 훌륭한 초기 대시보드 위젯이라고 생각하며, Weve&rsquo;는 이미 팀&rsquo; 매일 운영에서 매우 유용하다는 것을 발견했습니다. 그러나, 우리는 또한 개발하고자하는 다른 위젯&rsquo;뿐만 아니라 추가 할 수있는 몇 가지 잠재적 인 기능을 생각했다. 이러한 아이디어 중 일부에 대해 어떻게 생각하는지 알려주세요.</p>


  <ul>
   <li><strong>색 코딩:</strong> 위젯 배경색은 특정 조건에 따라 변경됩니다. 이렇게 하면 구성이 더 복잡해지지만 위젯에 추가 데이터 요소가 추가됩니다. 여기서 또 다른 가능성은 메트릭이 특정 임계값에 도달하면 위젯(예: 느낌표)에 아이콘을 표시하는 것입니다(이 후자의 아이디어는 색을 보는 데 어려움이 있는 사람들을 위한 접근성에 더 적합합니다).</li>
   <li><strong>경고 위젯: </strong> 경고에 따라 위젯을 만들거나 선택한 메트릭에 연결된 경고를 허용합니다.</li>
   <li><strong>Kusto 위젯: </strong> 메트릭 위젯과 동일한 기본 기능을 사용하지만 Kusto(App Analytics) 쿼리를 기반으로 위젯을 만들면 사용자가 고유한(아마도 매우 구체적인) 메트릭을 발명하고 반환할 수 있습니다.</li>
   <li><strong>차트: </strong> 일련의 데이터를 반환하고 차트에 표시할 수 있는 위젯을 만듭니다. 우리는 이것을 제공하기 위해 정리해야 할 몇 가지 내부 과제가 있지만&rsquo;, 우리는 그것에 대해 노력하고 있습니다.</li>
  </ul>


  <p>새 위젯을 통해 애플리케이션 Insights 데이터를 계속 사용할 수 있기를 바랍니다. 우리는 곧 당신을 위해 더 오고있다, 그래서 새로운 발표에 대한 formy&nbsp; Azure 블로그 게시물을&nbsp; 밖으로 눈을 유지하시기 바랍니다!</p>


  <p>언제나처럼 <a href="https://visualstudio.uservoice.com/forums/357324-application-insights">애플리케이션 Insights UserVoice 페이지에서</a> 새로운 기능 또는 향상된 기능에&nbsp; 대한 아이디어를 공유하세요. 질문이 있으면 <a href="https://social.msdn.microsoft.com/Forums/vstudio/en-US/home?forum=ApplicationInsights"><u>애플리케이션 Insights 포럼</u></a>을 방문하세요.</p>
