### YamlMime:Yaml
ms.openlocfilehash: d61366eee044c1d384cc5aceed1c060f3a4022ab
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139901058"
Slug: new-azure-web-sites-feature-configurable-environment-variables-2
Title: '새 Azure 웹 사이트 기능: 구성 가능한 환경 변수'
Summary: Azure에서 가장 인기 있고 강력한 기능 중 하나는 XDT(XML 문서 변환)로, Windows Azure 웹 사이트에서 ApplicationHost.config 파일의 콘텐츠를 변환할 수 있습니다.
Content: >-
  Azure에서 가장 인기 있고 강력한 기능 중 하나는 XDT(XML 문서 변환)로, Windows Azure 웹 사이트 사이트에서 <strong>ApplicationHost.config</strong> 파일의 콘텐츠를 변환할 수 있습니다. 이 프로세스를 사용하여 <a href="https://www.windowsazure.com/en-us/develop/nodejs/common-tasks/publishing-with-git/">Kuduand</a>  Monaco와 같은 사이트 확장을 설치할 수 있습니다. 사이트 확장을 사용하면 Azure 웹 사이트의 기본 기능이 거의 제한되지 않습니다.


  <sup>타사</sup>  사이트 확장의 한 가지 과제는 대부분 특정 구성 설정이 필요하다는 것입니다. 예를 들어  <a href="https://docs.newrelic.com/docs/dotnet/azure-web-sites">New Relic의 .NET 에이전트</a> 는 여러 구성 키(COR_ENABLE_PROFILING, COR_PROFILER, COR_PROFILER_PATH 및 NEWRELIC_HOME)를 제공합니다. 개발자가 자신의 Azure 웹 사이트에 에이전트를 설치할 때( <a href="https://azure.microsoft.com/en-us/documentation/articles/web-sites-transform-extend/">올바른 위치에 acustom XDT</a>를 삭제하여) 개발자에게 이 작업을 수행하는 것은 어렵지 않지만, New Relic이 에이전트에 대한 자동 설치 관리자를 만들고 싶다면 지금까지는 그렇게 할 방법이 없었습니다.


  이를 돕기 위해 최근에 이러한 종류의 자동화를 허용하는 새로운 기능을 추가했습니다. 새 기능을 사용하면 사이트 확장 개발자가 XDT를 사용하여 구성 키를 추가할 수 있습니다. 이를 사용하려면 다음 형식을 사용하여 코드를 수정하고 XDT에 키를 추가하기만 하면 됩니다.


  <a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/1714/1374.Erez-code.png"><img class="aligncenter" alt="" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/1714/1374.Erez-code.png" border="0"></a>


  확장의 디자인에 따라 사이트 루트 또는 전역 아래에 위치가 될 수 있습니다. XDT를 통해 값이 설정되면 Azure는 이러한 값을 자동으로 끌어와 작업자 프로세스에 환경 변수로 연결하여 확장에서 사용할 수 있도록 합니다. 사이트 확장 및 XDT에 대한 자세한 내용은 이 문서를 참조 <a href="https://azure.microsoft.com/en-us/documentation/articles/web-sites-transform-extend/">하세요</a>.
