### YamlMime:Yaml
ms.openlocfilehash: 83571bf6ae44aa7e1f39a37c442377de5a204626
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139905827"
Slug: new-disaster-recovery-tutorials-for-wingtip-tickets-sample-saas-application
Title: Wingtip Tickets 샘플 SaaS 애플리케이션에 대한 새로운 재해 복구 자습서
Summary: 'SaaS 앱 관리를 지원하는 Azure SQL 데이터베이스의 기능을 보여주는 일련의 자습서에서 중단 발생 시 앱 및 해당 리소스를 복구하기 위한 재해 복구 전략을 살펴보는 두 가지 새로운 자습서를 소개합니다. '
Content: >-
  <p>SaaS 앱 관리를 지원하는 Azure SQL 데이터베이스의 기능을 보여주는 <a href="https://docs.microsoft.com/azure/sql-database/saas-dbpertenant-wingtip-app-overview" target="_blank">일련의 자습서</a>에서 중단 발생 시 앱 및 해당 리소스를 복구하기 위한 재해 복구 전략을 살펴보는 두 가지 새로운 자습서를 소개합니다. DR(재해 복구)은 규정 준수 이유 또는 비즈니스 연속성 등 많은 애플리케이션에서 중요한 고려 사항입니다. 서비스 중단 시간이 길어지면 잘 준비된 DR 계획으로 비즈니스 중단을 최소화할 수 있습니다.</p>


  <p>이 자습서는 Wingtip Tickets 샘플의 테넌트별 데이터베이스 아키텍처 모델을 대상으로 하며 Azure SQL 데이터베이스의 지역 복원 기능을 사용한 복구 및 Azure SQL 데이터베이스의 지역 복제 기능을 사용한 복구를 보여 줍니다.</p>


  <h2>지역 복원을 사용하여 재해 복구</h2>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/31cb1969-9709-4423-b784-f91aee3101bc.png"><img alt="image" border="0" height="321" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/67b6eb90-dd05-4796-b93b-17a4bfd68329.png" style="border: 0px currentColor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="이미지" width="624"></a> 이 자습서에서는 지역 복원 기반 DR 전략을 사용하여 전체 재해 복구 시나리오를 탐색합니다. 지역 복원을 사용하여 카탈로그 및 테넌트 데이터베이스를 자동으로 유지 관리되는 지역 중복 백업에서 대체 복구 지역으로 복구합니다. 중단이 해결되면 지역 복제를 사용하여 새 데이터베이스와 변경된 데이터베이스를 원래 프로덕션 지역으로 송환합니다.</p>


  <p>이 패턴에 대해 자세히 알아보려면 GitHub 자습서 및 <a href="https://github.com/Microsoft/WingtipTicketsSaaS-DbPerTenant" target="_blank">관련 코드를</a> <a href="https://docs.microsoft.com/azure/sql-database/saas-dbpertenant-dr-geo-restore" target="_blank">확인</a>하세요.</p>


  <h2>지역에서 복제를 사용한 재해 복구</h2>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/710303c3-7776-4dc9-9dee-6f0cc0713f38.png"><img alt="image" border="0" height="303" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/1adb9cf5-cedf-4ccf-8d7d-63257bcfd810.png" style="border: 0px currentColor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="이미지" width="623"></a> 이 자습서에서는 지역에서 복제 기반 DR 전략을 사용하여 전체 재해 복구 시나리오를 탐색합니다. 중단되기 전에 지역 복제를 사용하여 대체 복구 지역에서 카탈로그 및 테넌트 데이터베이스의 보조 복제본을 만들고 유지 관리합니다. 중단이 발생하면 이러한 복제본으로 장애 조치(failover)하여 정상적인 비즈니스 작업을 다시 시작합니다. 장애 조치(Failover) 시 원래 지역의 데이터베이스는 복구 지역에 있는 데이터베이스의 보조 복제본이 됩니다. 이러한 복제본은 다시 온라인 상태가 되면 복구 지역의 데이터베이스 상태를 자동으로 파악합니다. 자습서의 뒷부분에서 애플리케이션 및 해당 데이터베이스를 원래 프로덕션 지역으로 장애 조치(failback)하여 중단이 해결된 후 어떤 일이 발생할지 탐색합니다.</p>


  <p>이 패턴에 대해 자세히 알아보려면 GitHub 자습서 및 <a href="https://github.com/Microsoft/WingtipTicketsSaaS-DbPerTenant" target="_blank">관련 코드를</a> <a href="https://docs.microsoft.com/azure/sql-database/saas-dbpertenant-dr-geo-replication" target="_blank">확인</a>하세요.</p>


  <h2>시작</h2>


  <p>Wingtip Tickets SaaS 앱 및 자습서를 확인하여 DR 패턴 및 기타 다중 테넌트 SaaS 앱 패턴에 대해 자세히 알아봅니다.&nbsp; 5분 이내에 Azure 구독에 샘플 앱을 배포하고 프로비전, 스키마 관리, 성능 관리 및 재해 복구를 비롯한 다양한 관리 시나리오를 탐색할 수 있습니다.</p>


  <p>샘플과 패턴에 대해 어떻게 생각하는지, 그리고 다음에 추가되는 것을 보고 싶은지&rsquo; 알려주세요<a href="mailto:saasfeedback@microsoft.com">saasfeedback@microsoft.com</a>.</p>
