### YamlMime:Yaml
ms.openlocfilehash: d8604f95dafc0950bb49e9589f20e3d435208e18
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139907615"
Slug: optimize-your-apps-for-your-business-with-azure-application-insights
Title: Azure Application Insights 사용하여 비즈니스용 앱 최적화
Summary: 오늘부터 Application Insights 앱의 성능 및 사용량을 모니터링하는 데 도움이 되는 몇 가지 새로운 기능과 향상된 기능을 릴리스하고 있습니다. 이제 모든 구성 요소의 상태를 볼 수 있습니다...
Content: >-
  <p>오늘부터 다른 언어로 작성되거나 서버리스 함수로 작성된 경우에도&rsquo; 단일 애플리케이션 맵 &ndash; 에서 클라우드 애플리케이션의 모든 구성 요소의 상태를 확인할 수 있습니다. 스마트 검색은 성능 문제를 알리고 원인을 식별하는 데 도움이 됩니다. 전체 시스템을 통해 특정 클라이언트 요청을 추적할 수 있습니다. 변수 및 매개 변수 값으로 완료된 문제가 있는 작업의 실행 스냅샷을 디버그할 수 있습니다. <a href="https://azure.microsoft.com/services/application-insights/">Azure Application Insights</a> 클라우드 애플리케이션에 가장 적합한 모니터링 솔루션을 제공하여 문제를 신속하게 찾고 해결하는 데 도움을 줍니다. 또한 이제 앱&rsquo; 유용성을 개선하는 데 도움이 되는 향상된 사용 현황 분석 도구를 제공합니다.</p>


  <p>애플리케이션 Insights 잘 알고 있다면&rsquo; 오늘 발표하는 향상된 기능&rsquo;만큼 흥분되기를 바랍니다&rsquo;. 요약은 다음과 같습니다&rsquo;.</p>


  <ul>
   <li><strong>스냅샷 디버거 및 프로파일러</strong> 에서는 고객이 문제가 발생한 라이브 웹앱의 실행 추적을 보여 줍니다(그리고 비교를 위해, 그렇지 않은&rsquo; 경우 몇 가지). 드문 오류 또는 성능 문제를 재현하려고 하는 시간이 더 이상 없으며 훨씬 더 빠른 수정이 있습니다!</li>
   <li>이제 <strong>애플리케이션 맵</strong>은 클라이언트, 웹 서비스, 백 엔드 서비스, Azure Functions, Service Fabric, Kubernetes를 비롯한 하나의 활성 다이어그램 &ndash; 에 애플리케이션의 모든 종속 역할 및 구성 요소를 표시합니다. 모든 노드는 성능을 표시하고 진단에 대한 클릭을 제공합니다.</li>
   <li><strong>스마트 검색</strong> 을 사용하면 성능 변칙의 근본 원인을 신속하게 식별할 수 있습니다.</li>
   <li><strong>사용량 및 보존 분석 도구는</strong> 사용자가 앱을 사용하여 수행하는 작업을 검색하는 데 도움이 되므로 각 기능의 성공을 측정하고 각 반복에서 인기를 향상시킬 수 있습니다.</li>
  </ul>


  <p>애플리케이션 Insights 새로운 기능이며 ASP.NET, Node.JS 또는 Java에서 웹앱을 개발하는 경우 실험&rsquo;적 사용량에 대해 쉽게 시작하고 무료로 시작할 수 있습니다. 또한 서버 또는 호스트 환경에서 실행되는 앱에 대해 작동합니다(현재&rsquo; 업데이트 중 일부는 Azure에서 실행되는 앱용이지만).</p>


  <p style="text-align: center"><iframe allowfullscreen="" frameborder="0" height="315" src="https://www.youtube.com/embed/WuOjX4Cic0s" width="560"></iframe></p>


  <h2>간소화된 디버깅 및 프로파일링</h2>


  <p><a href="https://azure.microsoft.com/en-us/blog/snapshot-debugger-for-azure/">스냅샷 디버거</a> 및 <a href="https://docs.microsoft.com/en-us/azure/application-insights/app-insights-profiler">애플리케이션 Insights Profiler</a>는 클라우드에서 라이브 디버깅 및 프로파일링을 위한 것입니다. 라이브 앱에서 문제를 보여 주는 웹 요청 인스턴스에서 작업하면 테스트 컴퓨터에서 문제를 복제할 필요가 없습니다.</p>


  <p>미리 보기에서 스냅샷 디버거는 원격 분석을 사용하여 애플리케이션에서 예외가 throw되는 지점에서 디버그 스냅샷을 캡처합니다. 포털에서 스냅샷을 보고 변수와 매개 변수를 보거나 전체 스냅샷 디버깅 환경을 위해 Visual Studio Enterprise 사용하여 열 수 있습니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/518a1752-b751-4e38-ad85-d0a10730bf87.png"><img alt="Debug Snapshot" border="0" height="396" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/2b9bfd34-725d-4b61-b57d-b9163720cd77.png" style="border-left-width: 0px; border-right-width: 0px; background-image: none; border-bottom-width: 0px; float: none; padding-top: 0px; padding-left: 0px; margin-left: auto; display: block; padding-right: 0px; border-top-width: 0px; margin-right: auto" title="스냅샷 디버그" width="598"></a></p>


  <p>이제 Azure App Services에서 일반 공급되는 Application Insights Profiler는 프로덕션에서 실행되는 코드의 샘플 프로필을 자동으로 수집하며 요청을 실행할 때 소요되는 시간의 코드 수준 분석을 볼 수 있습니다. 가상 머신, VM 확장 집합 및 클라우드 서비스에도 미리 보기 지원을 사용할 수 있습니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/3b80c6dc-0b35-421d-984f-65a0bb75fc93.png"><img alt="POST Shopping Cart" border="0" height="415" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/4a20b4df-9e47-426f-a952-46f268d712b7.png" style="border-left-width: 0px; border-right-width: 0px; background-image: none; border-bottom-width: 0px; float: none; padding-top: 0px; padding-left: 0px; margin-left: auto; display: block; padding-right: 0px; border-top-width: 0px; margin-right: auto" title="POST 쇼핑 카트" width="611"></a></p>


  <h2>향상된 개발 지원</h2>


  <p>코딩이 없으면 이제 Azure Portal에서 Node.js, JavaScript, ASP .NET Core에 대한 지원을 사용하도록 설정할 수 있습니다.</p>


  <p><a href="https://github.com/Microsoft/ApplicationInsights-node.js">Node.js SDK</a> 개선 사항을 사용하여 리소스 만들기 블레이드에서 Node.js 옵션으로 선택하고 MongoDB, Redis, MySQL 및 일반적인 Node.js 로깅 솔루션과 같은 일반적인 Node.js 종속성을 수집할 수 있습니다.</p>


  <p>Kubernetes에서 실행되는 .NET Core용 Application Insights SDK의 미리 보기 지원을 활용하고 관련 속성을 애플리케이션 맵 및 분석에 가져올 수도 있습니다.</p>


  <p>JavaScript를 사용하는 웹앱의 경우 Azure Portal에서 애플리케이션 설정을 즉시 업데이트하고 웹앱을 다시 시작하여 클라이언트 쪽 원격 분석을 볼 수 있습니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/97fc0d78-b482-4c84-bc8b-cf6d01b6c10b.png"><img alt="image" border="0" height="323" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/97c80b8a-5911-4488-bc79-11f1df4be6fe.png" style="border-left-width: 0px; border-right-width: 0px; background-image: none; border-bottom-width: 0px; float: none; padding-top: 0px; padding-left: 0px; margin-left: auto; display: block; padding-right: 0px; border-top-width: 0px; margin-right: auto" title="이미지" width="641"></a></p>


  <p>Azure Functions 및 Service Fabric 미리 보기에서 Application Insights 직접 통합하여 풍부한 모니터링 및 심층 분석을 쉽게 얻을 수 있습니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/0d5c8adf-6d6e-4f59-a675-f25522bf1cc7.png"><img alt="Application Settings" border="0" height="270" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/e8bbafed-e1cd-45c5-95ce-deec608e07ac.png" style="border-top: 0px; border-right: 0px; background-image: none; border-bottom: 0px; float: none; padding-top: 0px; padding-left: 0px; margin-left: auto; border-left: 0px; display: block; padding-right: 0px; margin-right: auto" title="애플리케이션 설정" width="655"></a></p>


  <h2>사용자 모니터링</h2>


  <p>가장 인기 있는 앱 기능은 무엇인가요? 사용자가 사이트로 돌아오는 빈도는 얼마나 되나요? 최신 향상된 기능이 사용자에게 도움이 되거나 사용자를 더 어렵게 만들 수 있나요? 이와 같은 질문에 답변하기 위해 Application Insights 고객이 웹앱을 사용하는 방법을 더 잘 이해할 수 있도록 새로운 <a href="https://docs.microsoft.com/azure/application-insights/app-insights-usage-overview">사용 현황 분석 도구</a>가 미리 보기로 제공됩니다.</p>


  <p><a href="https://docs.microsoft.com/azure/application-insights/app-insights-usage-segmentation">세분화 도구를</a> 사용하여 기능을 사용하는 사용자 수를 조사하고, 해당 사용량의 추세를 확인하고, 사용자의 여러 하위 그룹에 유사하거나 다른 동작 패턴이 있는지 더 자세히 확인할 수 있습니다.</p>


  <p>마찬가지로, 웹앱에 처음 사용한 후 얼마나 많은 사용자가 돌아오는지 궁금한 경우 <a href="https://docs.microsoft.com/azure/application-insights/app-insights-usage-retention">보존 분석</a> 도구를 사용하여 두 작업 간의 참여 패턴을 볼 수 있습니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/bb394dfd-6bde-4c03-8c75-ccb43536809b.png"><img alt="Users" border="0" height="236" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/d3a8ded8-40eb-4e49-ad6d-f5071d5f3e8b.png" style="border-left-width: 0px; border-right-width: 0px; background-image: none; border-bottom-width: 0px; float: none; padding-top: 0px; padding-left: 0px; margin-left: auto; display: block; padding-right: 0px; border-top-width: 0px; margin-right: auto" title="사용자" width="608"></a></p>


  <p>이러한 도구를 표준 페이지 보기 원격 분석에 적용할 수 있지만, 몇 줄의 코드를 삽입하여 계정 열기 또는 구매 완료와 같은 주요 비즈니스 이벤트 또는 사용자 작업을 기록할 때 가장 효과적인 지식을 얻을 수 있습니다.</p>


  <p>사용자와 팀은 이 데이터를 사용하여 기능 투자 및 우선 순위 지정에 대한 교육적이고 정보에 입각한 결정을 내려 비즈니스 목표를 달성하는 데 도움이 될 수 있습니다.</p>


  <h2>사용자 지정 라이브 메트릭</h2>


  <p>이제 라이브 메트릭 스트림에 표시되는 메트릭 및 이벤트를 선택하고 필터링할 수 <a href="https://docs.microsoft.com/azure/application-insights/app-insights-live-stream">있습니다</a>. 라이브 메트릭 스트림은 라이브 업데이트 및 현장 진단을 모니터링하는 데 매우 유용한 주요 메트릭의 거의 즉각적인 라이브 피드입니다. 이제 이를 사용하여 사용자 지정 KPI 또는 Windows 성능 카운터를 실시간으로 쉽게 모니터링할 수 있습니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/89f22714-ec52-48fe-8d1f-2c44c5275b52.png"><img alt="Query Builder" border="0" height="319" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/edeb64da-ce1e-41e0-8e03-e95bdebf8771.png" style="border-left-width: 0px; border-right-width: 0px; background-image: none; border-bottom-width: 0px; float: none; padding-top: 0px; padding-left: 0px; margin-left: auto; display: block; padding-right: 0px; border-top-width: 0px; margin-right: auto" title="쿼리 작성기" width="532"></a></p>


  <h2>Azure Monitor 통합</h2>


  <p>애플리케이션 Insights Azure Monitor에 네이티브 통합을 사용하면 앱과 인프라 간의 격차를 해소하여 인프라와 관련된 앱 문제를 보다 쉽게 진단하고 해결할 수 있습니다. 이제 새 구성 UX 및 문제 해결 개선 사항을 포함하여 애플리케이션 Insights 메트릭을 자동 크기 조정 설정의 원본으로 사용하여 요구 사항이 변경되더라도 앱이 최상의 성능을 발휘할 수 있도록 할 수 있습니다.</p>


  <p>또한 Azure 문제가 애플리케이션에 영향을 미칠 때 진단하고 지원을 받는 데 도움이 되는 Azure 리소스 상태 및 경고 정보는 이제 종속성 KPI와 함께 <a href="https://docs.microsoft.com/en-us/azure/application-insights/app-insights-app-map">애플리케이션 맵</a> 의 일부로 사용할 수 있습니다. 이제 애플리케이션 맵은 애플리케이션 내의 여러 애플리케이션 및 역할에서 들어오는 데이터를 표시할 수 있습니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/078f1115-358a-4b17-a501-d3dd86ce7a0f.png"><img alt="Application Map" border="0" height="411" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/cc04fd0e-092f-4ed5-a0b7-e584ff8e8b40.png" style="border-left-width: 0px; border-right-width: 0px; background-image: none; border-bottom-width: 0px; float: none; padding-top: 0px; padding-left: 0px; margin-left: auto; display: block; padding-right: 0px; border-top-width: 0px; margin-right: auto" title="애플리케이션 맵" width="542"></a></p>


  <p>애플리케이션 Insights 이러한 기능을 활용하여 DevOps 환경을 개선하고 비즈니스에 영향을 미치는 것이 좋습니다. <a href="https://azure.microsoft.com/en-us/blog/tag/application-insights/">애플리케이션 Insights 태그가 지정된 블로그 게시물을</a> 계속 확인하고 성공적인 혁신에 대해 자세히 알아보세요.&nbsp;</p>


  <p>언제나처럼 <a href="https://visualstudio.uservoice.com/forums/357324-application-insights">애플리케이션 Insights UserVoice 페이지에서</a> 새로운 기능 또는 향상된 기능에 대한 아이디어를 공유하세요. 질문이 있으면 <a href="https://social.msdn.microsoft.com/Forums/vstudio/en-US/home?forum=ApplicationInsights">애플리케이션 Insights 포럼</a>을 방문하세요.</p>
