### YamlMime:Yaml
ms.openlocfilehash: a372d2d6fdb537f11204cbf06e16efc1063dacd6
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139907619"
Slug: optimize-price-performance-with-compute-auto-scaling-in-azure-sql-database-serverless
Title: Azure SQL Database 서버리스에서 컴퓨팅 자동 크기 조정을 사용하여 가격 성능 최적화
Summary: 컴퓨팅 리소스 할당을 최적화하여 성능 목표를 달성하고 비용을 제어하는 것은 복잡한 사용 패턴이 있는 데이터베이스 워크로드의 경우 특히 어려운 균형이 될 수 있습니다. SQL Database 서버리스에서는 워크로드 수요 및 초당 사용되는 컴퓨팅 요금에 따라 컴퓨팅 크기를 자동으로 조정합니다.
Content: >-
  <p>컴퓨팅 리소스 할당을 최적화하여 성능 목표를 달성하고 비용을 제어하는 것은 복잡한 사용 패턴이 있는 데이터베이스 워크로드의 경우 특히 어려운 균형이 될 수 있습니다. 이러한 문제를 해결하기 위해 서버리스 Azure SQL Database 미리 보기를 발표하게 되어 기쁩니다. SQL Database 서버리스(미리 보기)는 가격 성능을 최적화하고 간헐적이고 예측할 수 없는 사용량이 있는 데이터베이스에 대한 성능 관리를 간소화하는 새로운 컴퓨팅 계층입니다. LOB(기간 업무) 애플리케이션, 개발/테스트 데이터베이스, 콘텐츠 관리 및 전자 상거래 시스템은 SQL Database 서버리스에 이상적인 사용 패턴에 적합한 다양한 애플리케이션의 몇 가지 예일 뿐입니다. SQL Database 서버리스는 비용을 줄이기 위해 컴퓨팅 크기 조정 불확실성 또는 워크로드를 자주 다시 조정해야 하는 새 애플리케이션에도 적합합니다. 서버리스 컴퓨팅 계층은 SQL Database 완전히 관리되는 기본 제공 인텔리전스 이점을 모두 활용하며 애플리케이션 개발을 가속화하고 운영 복잡성을 최소화하며 총 비용을 절감하는 데 도움이 됩니다.</p>


  <h2>컴퓨팅 자동 크기 조정</h2>


  <p>SQL Database 서버리스에서는 워크로드 수요 및 초당 사용되는 컴퓨팅 요금에 따라 단일 데이터베이스에 대한 컴퓨팅 크기를 자동으로 조정합니다. 서버리스는 고정 가격에 고정된 양의 컴퓨팅 리소스를 할당하고 시간당 요금이 청구되는 SQL Database 프로비전된 컴퓨팅 계층과 대조됩니다. 짧은 시간 동안 프로비전된 컴퓨팅 데이터베이스는 최대 사용량을 수용하거나 부족한 프로비전 및 성능 저하 위험을 수용하기 위해 비용으로 리소스를 과도하게 프로비전해야 합니다. 확장 시간이 길어질수록 프로비전된 컴퓨팅 데이터베이스의 크기를 조정할 수 있지만 이 솔루션에는 사용 패턴을 예측하거나 사용자 지정 논리를 작성하여 일정 또는 성능 메트릭에 따라 크기 조정 작업을 트리거해야 할 수 있습니다. 이렇게 하면 개발 및 운영 복잡성이 추가됩니다. 서버리스에서 구성 가능한 한도 내에서 컴퓨팅 크기 조정은 서비스에서 지속적으로 적절한 크기의 리소스로 관리됩니다. 서버리스는 비활성 사용 기간 동안 데이터베이스를 자동으로 일시 중지하고 활동이 반환되면 자동으로 다시 시작하는 옵션도 제공합니다.</p>


  <h2>사용된 컴퓨팅에 대해서만 지불</h2>


  <p>SQL Database 서버리스에서 컴퓨팅은 초당 사용되는 CPU 및 메모리 양에 따라 청구됩니다.&nbsp; 데이터베이스가 일시 중지되는 동안에는 스토리지만 요금이 청구되므로 추가 가격 최적화 이점이 제공됩니다.</p>


  <p>예를 들어 밤에 유휴 상태이지만 하루 종일 멀티 코어 버스팅 헤드룸이 필요한 기간 업무 애플리케이션 또는 개발/테스트 데이터베이스를 고려해 보세요. 애플리케이션이 최대 4개의 vcore 자동 일시 중지 및 자동 크기 조정을 허용하도록 구성된 서버리스 데이터베이스를 사용하고 있으며 24시간 동안 다음과 같은 사용 패턴이 있다고 가정합니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/163fe6da-77fa-4247-86b7-785735ab65d7.png"><img alt="Graph display of usage patterns for SQL Database serverless over a 24 hour period" border="0" height="380" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/0df33977-d0bd-42d7-a55b-ad28263fe766.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="Graph 24시간 동안 SQL Database 서버리스에 대한 사용 패턴 표시" width="1308"></a></p>


  <p>볼 수 있듯이 데이터베이스 사용량은 청구된 컴퓨팅 양에 해당하며, 이는 vcore 초 단위로 측정되고 24시간 동안 약 46k vcore 초로 합산됩니다. 서버리스 데이터베이스의 컴퓨팅 단가가 약 $0.000073/vcore/초라고 가정합니다. 그런 다음 이 1일 기간에 대한 계산 청구서는 $3.40 미만입니다. 계산 단가에 누적된 총 vcore 초 수를 곱하여 계산됩니다. 이 기간 동안 유휴 상태에서 데이터베이스가 자동으로 일시 중지되었고 고객의 개입 없이 최대 4개의 vcore 중 80%까지 에피소드가 파열되는 이점을 누릴 수 있었습니다. 이 예제에서는 동일한 4개 vcore 한도로 구성된 프로비전된 컴퓨팅 데이터베이스에 비해 서버리스를 사용한 가격 절감이 중요합니다.&nbsp;&nbsp;</p>


  <p><em>미리 보기로 가격 책정이 할인됩니다. 이 예제에서 가격은 2019년 5월 미국 동부 지역을 기준으로 하며 변경될 수 있습니다. 최신 가격 책정은 </em><a href="https://azure.microsoft.com/en-us/pricing/details/sql-database/single/" target="_blank"><em>Azure SQL Database 가격 책정 페이지를</em></a> 방문하세요<em>.</em></p>


  <h2>가격-성능 절상</h2>


  <p>SQL Database 서버리스를 사용하는 경우 고려해야 할 가격-성능 장부가 있습니다. 이러한 절충은 컴퓨팅 단가 및 낮은 또는 유휴 사용 기간 후 컴퓨팅 준비로 인한 애플리케이션 성능에 미치는 영향과 관련이 있습니다.</p>


  <h3>컴퓨팅 단가</h3>


  <p>서버리스가 일시적인 사용 패턴이 있는 워크로드에 최적화되어 있기 때문에 서버리스 데이터베이스의 컴퓨팅 단가는 프로비전된 컴퓨팅 데이터베이스보다 높습니다. CPU 또는 메모리 사용량이 충분히 높고 충분히 오랫동안 유지되는 경우 프로비전된 컴퓨팅 계층의 비용이 저렴할 수 있습니다.</p>


  <h3>낮은 사용량 후 컴퓨팅 준비</h3>


  <p>서버리스 데이터베이스가 온라인인 동안 CPU 또는 메모리 사용량이 충분히 낮으면 메모리가 점진적으로 회수됩니다. 워크로드 작업이 반환되면 데이터 페이지를 SQL 버퍼 풀로 리하이딩하기 위해 디스크 IO가 필요할 수 있습니다. 또는 쿼리 계획을 다시 컴파일해야 할 수도 있습니다. 낮은 사용량에 따라 캐시를 회수하는 이 메모리 관리 정책은 SQL Database 서버리스에 고유하며 고객 비용을 제어하기 위해 수행되지만 성능에 영향을 미칠 수 있습니다. 낮은 사용량에 따른 메모리 매립은 이러한 종류의 영향을 피할 수 있는 단일 데이터베이스 또는 탄력적 풀에 대해 프로비전된 컴퓨팅 계층에서 발생하지 않습니다.</p>


  <h3>일시 중지 후 컴퓨팅 준비</h3>


  <p>서버리스 데이터베이스를 일시 중지하고 다시 시작하는 대기 시간은 일반적으로 데이터베이스가 오프라인 상태인 동안 약 1분 이하입니다. 데이터베이스가 다시 시작된 후 최적의 성능 조건이 반환되기 전에 추가 대기 시간을 추가하는 메모리 캐시의 수분을 다시 지정해야 합니다. 자동 일시 중지가 발생하기 전에 경과해야 하는 유휴 기간은 이 성능 영향을 보정하도록 구성할 수 있습니다. 또는 이러한 영향에 민감한 워크로드에 대해 자동 일시 중지를 사용하지 않도록 설정할 수 있으며 자동 크기 조정의 이점을 누릴 수 있습니다. 컴퓨팅 최소값은 사용량에 관계없이 데이터베이스가 온라인 상태가 되는 동안 청구되므로 자동 일시 중지를 사용하지 않도록 설정하면 비용이 증가할 수 있습니다.</p>


  <h2>자세한 정보</h2>


  <p>Azure SQL Database 서버리스는 단일 데이터베이스에 대한 범용 계층에서 지원됩니다.</p>


  <ul>
   <li><a href="https://go.microsoft.com/fwlink/?linkid=2085062" target="_blank">Azure SQL Database 서버리스(미리 보기)</a>에 대해 자세히 알아보세요.</li>
   <li>서버리스 컴퓨팅 계층(미리 보기)에 대한 <a href="https://azure.microsoft.com/en-us/pricing/details/sql-database/single" target="_blank">Azure SQL Database 가격 책정</a>에 대해 자세히 알아봅니다.</li>
  </ul>
