### YamlMime:Yaml
ms.openlocfilehash: 2bd5cd052cdb2f35dbc11a35a3a3163d72fb3def
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139898253"
Slug: our-2019-resolution-help-you-transform-your-2008-server-applications-with-azure
Title: '2019 해결 방법: Azure를 사용하여 2008 서버 애플리케이션을 변환하는 데 도움이 됩니다!'
Summary: 새해의 시작은 항상 우리의 계획을 반영하는 시간입니다. Microsoft에서는 2008년 서버에 대한 지원이 종료되는 시점에 서버 새로 고침 과정을 어떻게 지원할 수 있는지 고민해 왔습니다. Azure에서 사용할 수 있는 모든 최첨단 혁신을 어떻게 활용할 수 있을까요?
Content: >-
  <p><em>이 블로그 게시물은 Erin Chapple, CVP, Microsoft Windows Server 및 Rohan Kumar, CVP, Microsoft Data가 공동 저술했습니다.</em></p>


  <p>새해의 시작은 항상 우리의 계획을 반영하는 시간입니다. Microsoft에서는 <a href="https://www.microsoft.com/en-us/cloud-platform/windows-sql-server-2008" target="_blank">2008년 서버에</a>&rsquo; 대한 지원이 종료되어 서버 새로 고침 과정을 어떻게 지원할 수 있는지 고민해 왔습니다. Azure에서 사용할 수 있는 모든 최첨단 혁신을 어떻게 활용할 수 있을까요?</p>


  <p>재고를 보유하면서 Azure가 2008 서버 애플리케이션을 변환하기에 가장 적합한 3가지 이유는 다음과 같습니다.</p>


  <ol>
      <li><strong>보안:</strong> 보안 위협이 점점 더 정교해짐에 따라 조직의&rsquo; 보안 정책을 강화하는 것이 가장 중요합니다. 좋은 소식은 <a href="https://azure.microsoft.com/en-us/overview/security/" target="_blank">Azure</a> 가 다른 퍼블릭 클라우드보다 더 많은 인증을 받은 시장에서 가장 신뢰할 수 있는 클라우드라는 것입니다.</li>
      <li><strong>혁신:</strong> <a href="https://www.azure.com/migrate" target="_blank">Azure</a>를 수용하는 데 도움이 되는 최적화된 저위험 경로가 있습니다. 이 경우 <a href="https://docs.microsoft.com/en-us/azure/sql-database/sql-database-managed-instance" target="_blank">Azure SQL Database</a>, <a href="https://www.azure.com/cosmosdb" target="_blank">Azure Cosmos DB</a> 및 <a href="https://azure.microsoft.com/en-us/overview/ai-platform/" target="_blank">Azure AI</a>와 같은 완전 관리형 서비스로 계속 혁신할 수 있습니다.</li>
      <li><strong>비용 절감:</strong> <a href="https://azure.microsoft.com/en-us/pricing/hybrid-benefit/" target="_blank">Azure 하이브리드 혜택</a> 및 <a href="https://www.microsoft.com/en-us/cloud-platform/windows-sql-server-2008" target="_blank">확장 보안 업데이트를</a> 활용하여 크게 절약할 수 있습니다. 예를 들어 100개의 2008 서버를 Azure로 이동하면 온-프레미스를 실행하는 비용에 비해 3년 동안 $300K 이상을 절약할 수 있습니다(자체 모델링을 수행하려면 <a href="https://azure.microsoft.com/en-us/pricing/tco/calculator/" target="_blank">Azure TCO 계산기를</a> 확인하세요). 또한 azure for Windows Server 및 SQL Server 생각할 필요가 없습니다&rsquo;. AWS는 <a href="https://azure.microsoft.com/en-us/overview/azure-vs-aws/cost-savings/" target="_blank">5배 더 비싸다</a>.&nbsp;&nbsp;&nbsp;&nbsp;</li>
  </ol>


  <h2>지금 &ndash; 시작해&rsquo; 보세요. 도움을 받으세요!</h2>


  <p><strong>SQL Server 2008/R2에 대한 지원 종료는 2019년 7월 9일에 6개월도 채 남지 않았으며 2020년 1월 14일에 Windows Server 2008/R2에 대한 지원이 종료됩니다</strong>. <a href="https://www.microsoft.com/en-us/microsoft-365/blog/2019/01/14/move-to-modern-windows-10-iot-safer-smarter-cloud-ready/" target="_blank">Windows 7</a>, <a href="https://www.microsoft.com/en-us/microsoft-365/blog/2019/01/14/2019-is-the-year-to-make-the-shift-to-a-modern-desktop/" target="_blank">Office 2010</a> 및 <a href="https://aka.ms/Exchange2010EndOfSupportBlog" target="_blank">Exchange Server</a> 또한 곧 확장 지원을 종료합니다. Microsoft와 파트너는 모든 단계에서 도움을 주기 위해 여기에 있습니다. 다음은 현대 부동산으로 전환하는 데 도움이 되는 3가지 단계입니다.</p>


  <h3>1단계: 환경 평가</h3>


  <p>첫 번째 단계는 2008 서버 환경의 전체 인벤토리를 가져오는 것입니다. 조직의 전략적 가치를 기준으로 각 워크로드의 순위를 지정합니다. 다음과 같은 질문에 대답합니다. 이 워크로드는 클라우드에서 실행하면 어떤 이점을 얻을 수 있을까요? 온-프레미스에 유지해야 하는 사항은 무엇인가요? 각 서버를 현재 버전으로 업그레이드하기 위한 전략은 무엇인가요? 처음에 우선 순위와 목표를 설정하면 마이그레이션이 더 성공적으로 수행되도록 할 수 있습니다.</p>


  <p>자세한 지침은 <a href="https://datamigration.microsoft.com/" target="_blank">Azure Database Migration Guide</a>, <a href="https://azure.microsoft.com/mediahandler/files/resourcefiles/azure-migration-guide-for-windows-server/Azure_Migration_Guide_for_Windows_Server.pdf" target="_blank">Windows Server Migration Guide</a>, <a href="https://docs.microsoft.com/en-us/sql/sql-server/sql-server-technical-documentation" target="_blank">Microsoft SQL Server Docs</a> 및 <a href="https://docs.microsoft.com/en-us/windows-server/get-started/modernize-windows-server-2008" target="_blank">Windows Server Docs</a>를 참조하세요.</p>


  <h3>2단계: 옵션 파악</h3>


  <p>Microsoft는 사용 약관에 따라 2008 서버 애플리케이션을 현대화하는 다양한 솔루션을 제공합니다.</p>


  <p><strong>Azure SQL Database Managed Instance:</strong> 기존 SQL Server 배포(2008년 SQL Server 시작)와의 전체 엔진 호환성을 확보하고 PaaS 기능(자동 패치 및 버전 업데이트, 자동화된 백업, 고가용성) 및 AI 기반 기능을 사용하여 관리 오버헤드 및 TCO를 크게 줄입니다.</p>


  <p><strong>Azure Virtual Machines의 Windows Server 및 SQL Server:</strong> 다양한 컴퓨팅 솔루션&mdash; 개발 및 테스트, 애플리케이션 실행 및 데이터 센터 확장에 대한 가상화의 유연성을 제공합니다.</p>


  <p><strong>Windows Server 및 SQL Server 온-프레미스:</strong> 혁신적인 보안 및 규정 준수 기능, 업계 최고의 성능, 중요 업무용 가용성, 고급 분석 기본 제공 및 컨테이너와 같은 새로운 배포 옵션을 제공합니다. <a href="https://www.microsoft.com/en-us/cloud-platform/windows-server" target="_blank">Windows Server 2016 및 2019 및 SQL Server 2017</a> <a href="https://www.microsoft.com/en-us/sql-server/sql-server-2019" target="_blank">및 2019</a>를 사용하여 하드웨어 및 소프트웨어 인프라를 새로 고칩니다.</p>


  <h3>3단계: 이동</h3>


  <p>널리 채택된 네 가지 전략인 <a href="https://azure.microsoft.com/en-us/migration/get-started/" target="_blank">리호스트, 리팩터링, 다시 아키텍처 지정 및 애플리케이션 다시</a> 빌드를 사용하여 클라우드 마이그레이션 계획을 빌드합니다. 새 데이터베이스 및 OS 옵션을 고려하여 비즈니스에 적합한 조합을 선택합니다. 다음 웨비나 및 이벤트에 참여하여 자세히 알아보세요.</p>


  <ul>
      <li>1월 15일부터 3월 21일까지: <a href="https://www.microsoftevents.com/profile/web/index.cfm?PKwebID=0x1130083abcd" target="_blank">SQL Server 및 Azure Data Services 로드쇼</a></li>
      <li>1월 24일: 웨비나: <a href="https://cloudblogs.microsoft.com/sqlserver/2019/01/07/four-ways-to-take-your-apps-further-with-cloud-data-and-ai-solutions-from-microsoft/" target="_blank">최신 데이터 자산으로 비즈니스 혁신</a></li>
      <li>1월 29일: 웨비나: <a href="https://info.microsoft.com/ww-landing-transform-windows-server-2008-apps-with-hybrid-cloud-innovation.html" target="_blank">Windows Server 2008 앱 및 인프라 변환</a></li>
  </ul>


  <p>이 모든 것을 추가하면 Microsoft는 지구상에서 가장 포괄적이고 강력한 클라우드, 데이터 및 AI 플랫폼을 보유하고 있습니다. Microsoft만 기존 투자에 전례 없는 가치를 제공하는 광범위한 프로그램을 제공하며 새로 고침 여정을 돕기 위해 여기에 있습니다. 여러분과 귀하의 조직이 어떻게 계속해서 혁신하고 세상을 변화시킬 수 있는지 확인하게 되어 기쁩니다!</p>
