### YamlMime:Yaml
ms.openlocfilehash: 1bfacc3d5cacbee4b905e495e4d9992776f38da9
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139899604"
Slug: performance-buckets-in-application-insights
Title: 애플리케이션 Insights 성능 버킷
Summary: 'MTTD 최소화: 검색-심사-진단 프로세스를 보다 효율적으로 만드는 데 도움이 되도록 성능 버킷을 사용하여 문제를 검색, 심사, 분석하고 마지막으로 문제를 진단하는 평균 시간입니다.'
Content: >-
  <p>이 블로그 게시물에서는 MTTD를 최소화하는 방법을 설명합니다. 즉, 애플리케이션 Insights 사용하여 문제를 검색, 심사, 평가 및 마지막으로 문제를 진단하는 데 걸리는 시간을 설명합니다. 이 시나리오를 진행하는 동안 새로운 기능인 <strong>성능 버킷</strong>이 도입<strong></strong>됩니다. 성능 버킷은 검색-심사-진단 프로세스를 보다 효율적으로 만드는 데 도움이 됩니다.</p>


  <p>Insights 애플리케이션은 개발자가 애플리케이션의 성능, 가용성 및 사용을 모니터링할 수 있는 서비스입니다. <a href="https://azure.microsoft.com/en-us/blog/service-monitoring-and-diagnostics-2/">애플리케이션 수명 주기</a>의 중요한 부분이 됩니다. 현재 웹 애플리케이션 성능과 관련된 시나리오에 대한 Detect-Triage-Diagnostice 프로세스를 살펴보겠습니다.<br>

  &nbsp;</p>


  <p><img alt="01-pipe1" border="0" height="99" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/b3595967-10c9-47c9-affd-516050294428.png" style="margin: 0px auto; border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; float: none; display: block; background-image: none;" title="01-pipe1" width="480"></p>


  <h1><br>

  검색: 서버 응답 시간 저하</h1>


  <p>애플리케이션 Insights 서비스 개요 블레이드는 애플리케이션 상태에 대한 개요를 제공하도록 설계되었습니다. 이 블레이드의 주요 차트 중 하나는 서버&rsquo; 평균 응답 시간입니다. 즐겨찾는 애플리케이션을 시작 페이지에 고정하거나 매일 시청하려는 메트릭에 대한 즐겨찾기 보기를 만들 수 있습니다. 이렇게 하면 애플리케이션 원격 분석에 빠르게 액세스할 수 있습니다.<br>

  <br>

  <img alt="detect2" border="0" height="610" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/b127a6ea-48da-44ec-af2a-eb9427a4b347.png" style="margin: 0px auto; border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; float: none; display: block; background-image: none;" title="detect2" width="474"></p>


  <p>&nbsp;</p>


  <p>Application Insights 서비스를 실행하여 매일 아침 주요 서비스의 상태를 검토합니다. 모든 변칙에 대해 검토하고 대응할 수 있는 주요 대시보드가 있습니다. 응답 시간은 추적하는 메트릭 중 하나입니다. 팀에도 비슷한 프로세스가 있을 수 있습니다.</p>


  <p>매일 동기화를 사용하면 변칙을 알 수 있습니다. 그러나 성능 관련 문제를 검색하는 평균 시간을 줄이려면 서버 응답 시간에 경고를 설정하는 것이 좋습니다. 애플리케이션 Insights 평균 서버 응답 시간이 원치 않는 방식으로 동작하는 경우를 인식할 수 있도록 경고 기능이 있습니다.</p>


  <h2>경고 설정</h2>


  <p>&rsquo;평균 응답 시간이 너무 크면 경고를 받습니다.<br>

  <br>

  메트릭의 비정상적인 값에 대한 알림을 메일로 받으려면 경고를 추가합니다. 계정 관리자나 특정 메일 주소로 메일을 보내도록 선택할 수 있습니다. <a href="https://azure.microsoft.com/documentation/articles/app-insights-alerts/">경고 규칙을 추가하려면 경고</a> 규칙&gt; &ndash;&rsquo; &lsquo;경고 추가&rsquo;를 클릭합니다.&lsquo;<br>

  <br>

  <img alt="appinsights-413setmetricalert" border="0" height="610" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/e45c8ca1-edc4-4545-b46c-cf4b54984f29.png" style="border-width: 0px; margin: 0px auto; padding-top: 0px; padding-right: 0px; padding-left: 0px; float: none; display: block; background-image: none;" title="appinsights-413setmetricalert" width="554"></p>


  <h1><br>

  심사: 문제 심각도 이해</h1>


  <p>경고를 받으면 문제가 얼마나 심각한지 알고 싶을 것입니다. 모든 사용자와 모든 페이지에 영향을 주나요, 아니면 일부 페이지에만 영향을 주나요? 어떤 브라우저를 사용 중&rsquo;인지, 어디에 있는지에 따라 달라지나요? 애플리케이션 Insights 사용하면 URL, 브라우저, 도시 등과 같은 속성으로 메트릭을 나눌 수 있으므로 상관 관계를 확인할 수 있습니다. 다양한 속성에 대한 평균 응답 시간을 보려면 서버 응답 블레이드에 차트를 추가할 수 있습니다.<br>

  <br>

  <img alt="PB_5" border="0" height="475" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/efd05cad-bd83-45fb-bc4d-a37224d35e1b.png" style="margin: 0px auto; border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; float: none; display: block; background-image: none;" title="PB_5" width="610"><br>

  그룹화할 특정 속성을 선택한 후 서버까지 아래로 스크롤하여 서버 응답 시간을 선택해야 합니다.<br>

  &nbsp;</p>


  <p><img alt="PB_6" border="0" height="329" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/f871126a-229a-4c55-850e-1da2fe33a7eb.png" style="margin: 0px auto; border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; float: none; display: block; background-image: none;" title="PB_6" width="480"></p>


  <p>이제 선택한 속성에 의한 서버 응답 시간의 평균이 있어야 합니다. 이 예제에서는 도시를 선택했습니다.<br>

  &nbsp;</p>


  <p><img alt="test" border="0" height="328" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/4d71ff4a-f5e8-43bb-952d-a293ab281c71.png" style="margin: 0px auto; border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; float: none; display: block; background-image: none;" title="test" width="480"></p>


  <p>성능에 가장 영향을 주는 속성을 찾은 후 이 속성으로 모든 요청을 필터링할 수 있습니다.</p>


  <p>심사 단계의 한 가지 목표는 근본 원인을 확인하기 위해 원하는 서버 응답 시간보다 높은 특정 페이지 요청을 찾는 것입니다. 이 개별 요청을 찾은 후에는 진단할 준비가 된 것입니다.</p>


  <p>이전에는 개별 요청을 찾은 것은 모든 개별 서버 요청 목록을 검색하여 응답 시간이 만족스럽지 않은 요청을 찾는 것을 의미했습니다. 선형 검색은 가장 효율적인 방법이 아니며, 수천 개의 개별 요청이 발생하는 일반적인 인스턴스에서 특히 지루할 수 있습니다. 이 때문에 <strong>성능 버킷</strong>이라는 새로운 기능이 도입되었습니다.</p>


  <h2>성능 버킷</h2>


  <p>성능 버킷을 사용하면 특정 시간(버킷) 내에 속하는 서버 응답 시간의 양을 볼 수 있습니다. 위에 표시된 대로 새 그리드 차트를 추가하기만 하면 되지만 요청 성능별로 그룹화합니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/3dd3c715-93b3-45c1-a880-b33d000e87b2.png"><img alt="Request Performance" border="0" height="370" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/f7afb971-1b55-41e3-af46-9d079ddc0427.png" style="border: 0px currentColor; border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="요청 성능" width="480"></a></p>


  <p><br>

  이렇게 하면 응답 시간 분포에 대한 좋은 개요를 제공할 뿐만 아니라 응답 시간을 버킷으로 편리하게 정렬할 수 있습니다. 이 기능을 사용하면 원하는 응답 시간을 지난 요청에 직접 액세스할 수 있습니다(응답 시간이 빠른 수천 개의 요청을 스크롤할 필요가 없음).</p>


  <p>성능 버킷 내에서 필터링할 수도 있습니다. 버킷을 선택하면 해당 응답 시간 기간 내에 만들어진 모든 요청이 표시됩니다. 특정 속성이 있는 요청만 보려면 필터를 선택합니다. 아래 그림은 250-500ms 서버 응답 시간 내의 요청을 보고 Redmond 시의 요청만 추가한 필터를 추가하는 프로세스를 보여 줍니다.<br>

  &nbsp;</p>


  <p><img alt="filter_bucket1" border="0" height="371" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/e0948a22-05a7-4cec-af4f-1ec9f73dcea6.png" style="margin: 0px auto; border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; float: none; display: block; background-image: none;" title="filter_bucket1" width="610"></p>


  <p><br>

  필터링 프로세스를 완료하려면 업데이트를 클릭합니다. 아래 그림은 250ms-500ms 범위로 떨어지고 레드먼드 시에서 만들어진 요청 목록을 보여줍니다.<br>

  &nbsp;</p>


  <p><img alt="filtered" border="0" height="610" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/3d5848d4-da81-4d24-839a-eafb6d8423a8.png" style="margin: 0px auto; border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; float: none; display: block; background-image: none;" title="필터링됨" width="399"></p>


  <p><br>

  성능 버킷별로 그룹화 및 필터링하면 빠르고 느린 페이지의 평균 성능이 무엇인지 이해할 수 있습니다. 다양한 가능성을 조사할 수 있습니다. 빠른 페이지 수가 감소하고 캐시 누락 수가 증가했나요? 또 다른 가능성은 느린 페이지에 대한 호출 수가 증가했다는 것입니다. 또는 더 많은 고객이 느린 보고 페이지를 실행하고 있습니다. 서버 응답 시간 문제를 해결하려는 경우 이러한 성능 버킷을 사용하면 응답 시간이 느린 요청을 찾는 프로세스가 신속하게 수행됩니다. 진단할 항목(원치 않는 서버 응답 시간이 있는 요청)을 찾았으므로 이제 마지막 단계인 진단으로 이동할 준비가 되었습니다.</p>


  <h1>진단: 응답 시간이 느린 이유</h1>


  <p>이제 서버 응답 시간이 느린 인스턴스를 찾았으므로 속도가 느린 이유를 조사할 수 있습니다. 서버 응답 시간이 저하되는 정확한 이유는 수정할 사항을 결정할 수 있도록 알아야 합니다. 다른 원격 분석을 사용하여 문제 영역을 정확히 파악할 수 있습니다.</p>


  <p>경우에 따라 새 SQL 쿼리 또는 http 요청/서비스 호출이 평균 서버 응답 시간에 영향을 줄 수 있습니다. 이 원인이 되는 쿼리를 식별하기 위해 종속성 모니터링을 늘릴 수 있습니다. <strong> </strong><a href="https://azure.microsoft.com/documentation/articles/app-insights-dependencies/">종속성 모니터링</a> 은 외부 서비스(데이터베이스, REST 서비스 등)에 대한 호출 수를 계산하고 각 호출의 성공 또는 실패와 응답하는 데 걸리는 시간을 기록합니다. 요청을 서비스하는 데 4.2초가 걸렸고 4초가 웨어하우스 서버에 있는 것을 볼 수 있다면 문제가 어디에 있는지 알 수 있습니다.</p>


  <p>서버 응답 시간이 증가할 수 있는 또 다른 가능성은 캐시 누락의 증가입니다. <a href="https://azure.microsoft.com/documentation/articles/app-insights-api-custom-events-metrics/">로그 추적 이벤트 또는 메트릭을</a> 사용하여 이전보다 더 많은 수의 캐시 누락이 발생했는지 확인할 수 있습니다. <strong>로그 추적 이벤트는</strong> 프로세스의 핵심 요소를 기록하고 내부 인터페이스에서 문제를 추적하는 데 특히 유용합니다. 로그 추적 이벤트를 사용하면 백 엔드 또는 프런트 엔드에서 문제가 발생하는지 검색하려고 할 때도 유용합니다.</p>


  <p>진단의 역할은 ASAP를 수정, 테스트 및 해제해야 하는 코드 결함인지, 즉 스케일 업으로 해결할 수 있는 리소스 문제인지 또는 외부 서비스에 대한 문제인지를 식별하는 것입니다.</p>


  <p><a href="https://azure.microsoft.com/blog/service-monitoring-and-diagnostics-2">빅터 무슈카틴&rsquo; 블로그</a>에서 진단에 대한 자세한 내용이&rsquo; 있습니다.</p>


  <h1>요약</h1>


  <p>성능 버킷 덕분에 심사에서 진단으로의 이동이 훨씬 더 원활합니다. 성능 버킷의 새로운 보기는 서버 응답 시간의 편리한 개요 및 배포를 제공합니다. 검색, 심사 및 진단 후 문제를 해결할 수 있습니다. 이제 실제 문제에 대해 작업하고 있다는 확신을 가지고 수정 프로세스에 들어갈 수 있습니다.</p>
