### YamlMime:Yaml
ms.openlocfilehash: 4e17973ad2f1c997a867f8cf5217c5570c8b28a2
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139911594"
Slug: powering-all-your-applications-from-cloud-to-edge-with-azure-infrastructure
Title: 'Azure 인프라를 사용하여 클라우드에서 에지로 모든 애플리케이션 전원 공급 '
Summary: 조직은 클라우드에서 에지로 변환하고, 기존 워크로드를 마이그레이션 및 최적화하고, 새로운 클라우드 네이티브 앱을 빌드하거나, 에지에서 새로운 시나리오를 잠금 해제하거나, 이러한 전략을 결합하여 모든 비즈니스 요구 사항을 충족하고 있습니다. Microsoft는 지속적인 기술 혁신을 통해 모든 단계에서 지원하도록 최선을 다하고 있습니다. 현재는 진행 중인 신속한 비즈니스 변환을 지원하기 위해 Azure 인프라 포트폴리오 전반에 걸쳐 제품 업데이트 및 향상된 기능을 발표하고 있습니다.
Content: >-
  <p>조직은 클라우드에서 에지로 변환하고, 기존 워크로드를 마이그레이션 및 최적화하고, 새로운 클라우드 네이티브 앱을 빌드하고, 에지에서 새로운 시나리오를 잠금 해제하고, 이러한 전략을 결합하여 다양한&nbsp; 비즈니스 요구 사항을 충족&nbsp;하고 있습니다. Microsoft는 지속적인 기술 혁신을 통해 모든 단계를 돕기&nbsp; 위해 최선을 다하고 있습니다.</p>


  <p>현재 Azure&rsquo; <a href="https://azure.microsoft.com/en-us/overview/what-is-azure/iaas/#overview" target="_blank">인프라 포트폴리오</a> 전체에서 제품 업데이트 및 향상된 기능을 발표하여 성능, 확장성 및 보안을 제공합니다&nbsp;. 비즈니스 요구 사항에 맞게 시나리오를 다시&nbsp; 구현할&nbsp;&#39;장기적인 성공을 위해 더 많은 유연성과 선택을 제공합니다.</p>


  <h2>성능, 확장성 및 보안 달성</h2>


  <p>클라우드에서 실행하는 애플리케이션 워크로드에 관계없이 기본 클라우드 인프라의 성능, 확장성 및 보안은 성공에 매우 중요합니다. 이를 위해 Azure는 새로운 IaaS(Infrastructure as a Service) 기능으로 혁신을 계속하여 사용자에게 권한을 부여합니다.</p>


  <p><strong>새 Azure VM(Virtual Machines)을 사용하여 가격 대비 성능 향상</strong> 새로운 인텔 기반 Dv5 및 Ev5 VM은 일반적으로 사용할 수 있으며 이전 세대에 비해 더 나은 가격 성능을 제공합니다. 새로운 AMD 기반 Dasv5 및 Easv5 VM도&nbsp; 사용할 수 있으므로 이전 세대에 비해 더 나은 가격 성능을 제공하고 로컬 디스크 스토리지&nbsp; 허용 가격대 없이 옵션을 제공합니다. 또한 이전 VM 세대에 비해 더 높은 원격 스토리지 성능(최대 4,000MB/s)을 제공하는 새로운 메모리 최적화 <a href="https://forms.office.com/pages/responsepage.aspx?id=v4j5cvGGr0GRqy180BHbR5v6ZePlPKxOoBzSWQpMAaRURFRSMEk0STk1WFRFQkpJTENPMThNM1hNWC4u" target="_blank">Ebsv5</a> VM 시리즈의 미리 보기를 발표하게 되어 기쁩니다. <a href="https://aka.ms/NewVMsBlog21" target="_blank">VM 포트폴리오가 확장</a>됨에 따라 <a href="https://aka.ms/vm-selector" target="_blank">VM 선택기를</a> 사용하여 다양한 워크로드에 적합한 VM 및 디스크 스토리지 옵션을 쉽게 식별할 수 있습니다.</p>


  <p><strong>Azure Virtual MachineScale&nbsp; Sets 유연한 오케스트레이션 모드를 사용하여 애플리케이션 가용성을 높입니다.</strong> 일반적으로 사용할 수 있는 이 새로운 기능은 확장 집합 내의 개별 VM을 <a href="https://aka.ms/VMSSFlexGABlogNov21" target="_blank">완전히 제어</a> 하는 동시에 수천 개의 VM에서 대규모로 애플리케이션 복원력을 높입니다.</p>


  <p><strong>새로운 Azure Storage 기능을 사용하여 확장성 및 성능을 향상합니다.</strong> 이제 일반 공급되는 주문형 디스크 버스팅을 사용하면 증가하는 수요를 처리하는 데 필요한 경우 프로비전된 제한을 초과하는 디스크 성능을 높일 수 있습니다. Azure Disk Storage 라이브 크기 조정 기능을 미리 보기로 사용하면 가동 중지 시간 없이 동적으로 용량을 늘려 수요 변화에 쉽게 적응할 수 있습니다. <a href="https://aka.ms/AzureDiskStorage-Ignite2021blog" target="_blank">Azure Disk Storage</a> 대해 자세히 알아보세요.</p>


  <p><strong>투명 네트워크 어플라이언스 삽입 규모</strong> <a href="https://aka.ms/gatewaylbblog" target="_blank">새 게이트웨이 Load Balancer</a>를 미리 보기로 사용하면 타사 네트워크 어플라이언스의 크기를 조정하고 배포할 수 있으며, 트래픽을 정상 어플라이언스 인스턴스로 자동으로 다시 라우팅하여 애플리케이션의 고가용성 및 안정성을 보장할 수 있습니다.</p>


  <p><strong>대규모 가상 네트워크 관리 </strong> <a href="https://aka.ms/avnm" target="_blank">Azure Virtual Network Manager</a>는 미리 보기로도 중앙 집중식 네트워크 관리를 위한 원스톱 상점입니다. 확장성이 뛰어나고 사용 가능한 네트워크 관리 솔루션을 사용하면 가상 네트워크 토폴로지 만들기 및 관리 및 네트워크 리소스를 대규모로 보호할 수 있습니다.&nbsp;</p>


  <p><strong>타의 추종을 불허하는 보안을 제공하기 위한 지속적인 혁신.</strong> 모든 2세대 Azure VM에 대해 신뢰할 수 있는 시작을 사용하면 워크로드를 강화하고 악의적인 공격으로부터 보호하는 것이&rsquo; 그 어느 때보다 쉬워졌습니다. 개인 정보 보호 및 보안을 강화하기 위해 기존 워크로드를 미리 보기에서 사용할 수 있는 <a href="https://aka.ms/ACCIgnite2021" target="_blank">새 기밀 VM</a>으로 전환할 수 있습니다. 또한 미리 보기에서 Intel SGX VM 및 AMD SEV-SNP VM의 AKS(Azure Kubernetes Service)는 기밀 컨테이너의 오케스트레이션을 보호하는 데 도움이 됩니다. 네트워크 보안을 극대화하기 위해 <a href="https://aka.ms/BastionStdSkuBlog" target="_blank">새 Azure Bastion Standard SKU</a>, 개인 피어링에 대한 IPv6 지원 및 고급 MACsec 지원이 모두 일반 공급됩니다. 추가 네트워크 보안 향상에는 확장된 ExpressRoute FastPath 지원 미리 보기 및 더 나은 성능을 제공하는 <a href="https://aka.ms/WAFIgniteBlog" target="_blank">새로운 Application Gateway WAF 엔진</a> 이 포함됩니다.</p>


  <h2>워크로드 마이그레이션, 현대화 또는 최적화</h2>


  <p>대부분의 조직에서는 기존 워크로드 및 특수 워크로드에서 최신 Applicationseach에 이르는 다양한 애플리케이션&mdash; 집합을&mdash; 실행하며 요구 사항과 클라우드 채택 전략이 다릅니다. 우리의 임무는 모든 사용자&nbsp; 신청에 전원을 공급할 수 있는 플랫폼 기능을 제공하는 것입니다. 다음은 다양한 워크로드 요구&#39;고객을 &nbsp;해결하는 최신 제품 업데이트의 하이라이트입니다.</p>


  <p><strong>Windows Server 및 Linux 워크로드에 대한 IT 작업을 간소화합니다.</strong> <a href="https://aka.ms/AutomanageTCBlog-Ignite21" target="_blank">Azure Automanage</a>는 IT 및 DevOps IT 관리를 자동화하고 최적화하는 데 사용됩니다. 이제 Windows Serverhelp&mdash;용 Azure Automanage의 QUICcapabilities&mdash;를 통해 Azure 및 SMB용 확장 네트워크를 일반적으로 사용할 수 있으므로 Windows Server 워크로드 마이그레이션이 간소화됩니다. 미리 보기에서는 사용자 지정 구성 프로필 및 Azure Arc 지원 서버 지원과 같은 새로운 향상된 기능을 통해 <a href="https://azure.microsoft.com/en-us/services/azure-automanage/" target="_blank">Windows 및 Linux VM을</a> 보다 유연하게 관리할 수 있습니다.</p>


  <p><strong>Azure VMware Solution을 사용한 마이그레이션을 위한 지역별 적용 범위 및 기능</strong> &rsquo;현재는 Azure VMware Solution을 독일 서부 지역으로 확장한다고 발표하여 현재 전 세계 18개 Azure 지역에서 솔루션을 사용할 수 있게 되었습니다. 또한 최근에 Azure VMware Solution에 대한 <a href="https://aka.ms/diskpool-blog" target="_blank">Azure Disk 풀 통합</a>을 미리 보기로 시작하여 데이터 집약적 워크로드에 대한 Azure Disk Storage 크기를 조정할 수 있습니다. 또한 새로 확장된 워크로드 시나리오에는 Azure VMware Solution <a href="https://azure.microsoft.com/en-us/services/virtual-desktop/citrix-virtual-apps-desktops-for-azure/" target="_blank">에서 Citrix Virtual Desktop 인프라</a> 를 지원하는 것이 포함됩니다.</p>


  <p><strong>새로운 Azure Virtual Desktop을 사용하여 원격 작업 최적화 기능 향상</strong> <a href="https://aka.ms/AVD-Ignite2021-BlogPost" target="_blank">Azure Virtual Desktop</a>은 Azure VM당 여러 사용자를 호스트하는 다중 세션 지원과 함께 전체 Windows 10 및 Windows 11 환경을 지원하는 유일한 클라우드 VDI 솔루션입니다. 추가 비용 최적화&rsquo;를 지원하기 위해 조직이 최대 워크로드에 대한 가용성을 예약하고 필요한 리소스에 대해서만 비용을 지불하는 데 도움이 되는 자동 크기 조정 지원 미리 보기를 발표합니다. 로컬로 실행하려는 데이터 및 애플리케이션 워크로드의 경우 미리 보기에서 Azure Stack HCI용 Azure Virtual Desktop이 도움이 될 수 있습니다.</p>


  <p><strong>Azure에서 클라우드 네이티브 기술로 현대화.</strong> Azure에서 가장 빠르게 성장하는 서비스 중 하나인 AKS(Azure Kubernetes Service<strong>&nbsp;</strong>)를 사용하면 완전히 관리되는 Kubernetes 서비스를 사용하여 컨테이너화된 애플리케이션을 보다 쉽게 배포하고 관리할 수 있습니다. <a href="https://myignite.microsoft.com/sessions/9c12d736-4ecc-4075-b6a4-5b1fa8ec665e?source=sessions" target="_blank">Microsoft Into Focus: 디지털 및 앱 혁신</a>에 참석하고 <a href="https://aka.ms/containerapps/ignite-blog" target="_blank">Azure Container Apps 미리 보기</a> 및 <a href="https://aka.ms/ignitenov21/cloudnativeappsblog" target="_blank">AKS용 Open Service Mesh 통합</a>의 일반 공급 등 최신 AKSand&nbsp; 클라우드 네이티브 업데이트에 대해 알아봅니다.</p>


  <p><strong>마이그레이션 및 현대화를 위한 추가 옵션입니다. </strong> 최근에 새로운 앱 컨테이너화 도구, SQL 및 .NET 웹 현대화를 위한 향상된 검색 및 평가 기능, Azure Migrate에서 에이전트 없는 소프트웨어 인벤토리 및 종속성 분석의 일반 공급이 발표되었습니다. 또한 Weve&rsquo;는 Azure Migrate 어플라이언스 온보딩 환경을 더욱 간소화했습니다. SAP, Azure Arc를 사용한 하이브리드, 보안 및 향상된 애플리케이션 현대화 지원을 포함하여 <a href="https://aka.ms/IgniteNov21/MigrateModernizeBlog" target="_blank">AMMP(Azure 마이그레이션 및 현대화 프로그램)</a> 의 추가 시나리오에 대해 새로 발표된 지원에 대해 자세히 알아봅니다.</p>


  <h2>하이브리드, 다중 클라우드 및 에지에서 새 시나리오 잠금 해제</h2>


  <p>이번 주에는 보안에서 Azure Arc 및 Azure Stack HCI의 최신 기능과 혁신을 공유하고<a href="https://myignite.microsoft.com/sessions/27b4aeb9-ba89-403c-9cdf-4c629eb538c1?source=sessions" target="_blank">, Microsoft Azure 세션을 통해 하이브리드 및 다중 클라우드에서 개발 및 혁신</a>하고, 전체 Azure 하이브리드 포트폴리오에 대해 알아보고 최신 상태를 유지하는 <a href="https://aka.ms/arcskilling" target="_blank">단일 리소스</a>를 제공했습니다.</p>


  <p>또한 더 많은 에지 시나리오를 지원하기 위해 IoT 기능을 계속 확장합니다. <a href="https://techcommunity.microsoft.com/t5/internet-of-things/building-multi-tenant-solutions-with-azure-iot-central/ba-p/2617416" target="_blank">Azure IoT Central</a>은 조직에 대한 지원을 소개합니다. 요청이 많은 이 기능은 일반 채택을 위해 IoT를 간소화합니다. 이제 IoT 솔루션을 한 번 빌드하고 여러 테넌트를 온보딩하여&mdash; 비용을 절감하고 관리 오버헤드를 줄일 수 있습니다. 또한 <a href="https://techcommunity.microsoft.com/t5/internet-of-things/windows-server-iot-2022-now-generally-available/ba-p/2703521" target="_blank">Windows Server IoT 2022</a> 및 <a href="https://techcommunity.microsoft.com/t5/internet-of-things/windows-for-iot-now-goes-to-11-with-windows-11-iot-enterprise/ba-p/2850335" target="_blank">Windows 11 IoT Enterprise</a> 이제 일반 공급됩니다.&nbsp; Microsoft IoT Signals를 사용하여 에지 전략을 강화하려면 IoT 전략, 비즈니스 성장 및 지속 가능성 및 사이버 보안에 대한 고려 사항을 자세히 <a href="https://azure.microsoft.com/en-us/resources/iot-signals/" target="_blank">살펴봅니다</a>.</p>


  <h2>추가 리소스에 액세스하여 자세한 정보</h2>


  <p>이번 주에 Microsoft Ignite에 참여해 주신 모든 분과 나중에 주문형 세션을 시청해 주신 분들께 감사드립니다. <a href="https://myignite.microsoft.com/sessions/5fbb6a38-0535-4df0-8d86-7743745c7de0?source=sessions" target="_blank">Microsoft Into Focus: 인프라 세션</a>&nbsp; 및 <a href="https://aka.ms/ignite-book-of-news" target="_blank">Microsoft Ignite News의</a> 모든 공지 사항을 확인하세요. 컴퓨팅, 스토리지 및 네트워킹&mdash;&rsquo;에서 IaaS 솔루션에 대해 자세히 알아보려면 2021년 11월&nbsp; 17일에 <a href="https://info.microsoft.com/ww-landing-azure-iaas-day.html" target="_blank">무료 Azure IaaS Day</a> 디지털 이벤트를 놓치게 됩니다. <a href="https://info.microsoft.com/ww-landing-azure-iaas-day.html" target="_blank">지금 등록하세요</a>!</p>


  <hr>

  <p><em>Azure. 목적에 따라 발명.</em></p>
