### YamlMime:Yaml
ms.openlocfilehash: 3cdcefefff7ec3f0fc061e979856ec6f43eaee8e
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139911605"
Slug: power-your-business-applications-data-with-analytical-and-predictive-insights
Title: 분석 및 예측 인사이트를 사용하여 비즈니스 애플리케이션 데이터 활용
Summary: 지난 2년 동안 고객 피드백은 데이터 장벽이 해소되면 분석의 영향이 기하급수적으로 증가한다는 것을 분명히 했습니다. 오늘 Microsoft Dataverse용 Azure Synapse Link를 사용하여 비즈니스 애플리케이션과 분석 시스템 간의 장벽을 제거하여 데이터 인사이트를 모두 가져오는 다음 단계를 발표합니다.
Content: >-
  <p>디지털 변환에 성공하려면 불필요한 장벽을 제거해야 합니다. 이를 위해 2019년 11월에 <a href="https://azure.microsoft.com/services/synapse-analytics/" target="_blank">Azure Synapse Analytics</a> 를 발표하여 데이터 웨어하우징과 빅 데이터 분석 간의 장벽을 제거했습니다. 그리고 2020년에는 한 단계 더 나아가 Azure <a href="https://azure.microsoft.com/en-us/blog/azure-analytics-clarity-in-an-instant/" target="_blank">Cosmos DB용 Azure Synapse Link</a>를 발표하여 운영 데이터와 분석 시스템 간에 오랫동안 존재했던 장벽을 허비했습니다.</p>


  <p>지난 2년 동안 고객 피드백은 데이터 장벽이 해소되면 분석의 영향이 기하급수적으로 증가한다는 것을 분명히 했습니다. 오늘 Microsoft&rsquo; Dataverse용 Azure Synapse Link를 사용하여 비즈니스 애플리케이션과 분석 시스템 간의 장벽을 제거하여 데이터 인사이트를 모두 가져오는 다음 단계를 발표했습니다.</p>


  <h2>Dataverse용 Azure Synapse Link 소개</h2>


  <p>비즈니스 애플리케이션 데이터와 분석 시스템 간의 장벽은 가속화된 인사이트 시간을 방해하는 중요한 요소입니다. 개발자가 Microsoft Power Apps, Microsoft Power Automate 및 Microsoft Dynamics 365와 같은 플랫폼을 사용하여 비즈니스 애플리케이션을 만들고 관리함에 따라 이러한 애플리케이션에서 가져온 데이터는 엄청납니다. 오늘날 고객은 모든 Microsoft 비즈니스 애플리케이션 <a href="https://powerplatform.microsoft.com/en-us/dataverse/" target="_blank">에 대한 Dataversea</a>&mdash; 공통 저장소에 이 데이터를 저장하고 관리합니다. 그러나 고객이 Dataverse 내의 데이터에서 심층적인 인사이트를 검색하려는 경우 다양한 서비스를 함께 연결하거나 지속적으로 데이터를 앞뒤로 복사해야 하므로 데이터 팀의 지속적인 유지 관리와 더 바쁜 작업이 발생합니다.</p>


  <p>Dataverse 내의 데이터는 분석이 쉽게 표면화할 수 있는 잠재적 인사이트의 골드마인입니다. 이제 고객은 Dataverse용 Azure Synapse Link를 사용하여 비즈니스 애플리케이션으로 흐르는 데이터도 분석 솔루션으로 흐르는지 자동으로 확인할 수 있습니다. 이를 통해 고객은 별도의 작업 스트림이 아닌 비즈니스 애플리케이션&mdash;에서 데이터를 관리하는 것과 함께 고급 분석 작업을 수행할 수 있습니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/e7c61190-7058-424d-a3b2-653af7c059b3.gif"><img alt="Azure Synapse Link for Dataverse GIF" height="576" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/a7e04bbb-a0e9-4e05-a352-c5f2b6ab4e19.gif" style="display: inline;" title="" width="1024"></a></p>


  <h2>작동 원리</h2>


  <p>몇 번의 클릭만으로 Power Apps 또는 Dynamics 365에서 작업하는 개발자는 전체 Dataverse 환경을 Azure Synapse로 가져올 수 있습니다. 고객은 단추를 클릭하고 Azure Synapseworkspace&nbsp; 이름을 입력하기만 하면 됩니다. 원활한 환경을 위해 개발자&rsquo;는 Azure Synapse에 액세스하기 위해 Power Apps 또는 Dynamics 365 포털을 떠날 필요가 없습니다. <strong>Azure Synapse Analytics 작업 영역</strong><em></em>으로 이동을 클릭하고 엔드 투 엔드 분석 서비스를 사용하여 인사이트 검색을 시작할 수 있습니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/c0f5ae3c-3815-4976-b9bd-f297b142dc68.png"><img alt="Screenshot of developers working in Power App bringing their entire Dataverse environment to Azure Synapse. " border="0" height="937" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/36168fa8-713d-48a8-89e3-d2cd6f7ff898.png" style="border: 0px currentcolor; border-image: none; display: inline; background-image: none;" title="DataverseSynapseLink" width="1920"></a></p>


  <p>Dataverse용 Azure Synapse Link에 대해 자세히 알아보려면 <a href="https://aka.ms/synapse-dataverse-tech" target="_blank">Dataverse 및 Azure Synapse Analytics를 연결하여</a> 최신 블로그 게시물인 &quot; Time to Insight를 가속화하세요.&quot;</p>


  <h2>오늘 시작</h2>


  <ul>
      <li>오늘 <a href="https://azure.microsoft.com/en-us/free/synapse-analytics/" target="_blank">Azure Synapse Analytics</a> 를 무료로 시작하세요.</li>
      <li>Dataverse용 Azure Synapse Link에 대한 자세한 내용은 <a href="https://aka.ms/synapse-dataverse-docs" target="_blank">설명서를 확인하세요</a>.</li>
  </ul>


  <hr>

  <p><em>Azure. 목적에 따라 발명.</em></p>
