### YamlMime:Yaml
ms.openlocfilehash: e368f4b35cbef9e4f26d335e55cc91795c079046
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139912682"
Slug: preview-of-custom-content-in-azure-policy-guest-configuration
Title: Azure Policy 게스트 구성에서 사용자 지정 콘텐츠 미리 보기
Summary: 오늘 Azure Policy의 새로운 기능에 대한 미리 보기를 발표합니다. Linux 및 Windows VM(가상 머신) 내 설정을 감사하는 게스트 구성 기능은 이제 고객이 사용자 지정 콘텐츠를 작성하고 게시할 준비가 되었습니다.
Content: >-
  <p>오늘 Azure Policy의 새로운 기능 미리 보기를 발표합니다. Linux 및 Windows VM(가상 머신) 내 설정을 감사하는 게스트 구성 기능은 이제 고객이 사용자 지정 콘텐츠를 작성하고 게시할 준비가 되었습니다.</p>


  <p>게스트 구성 플랫폼은 일반적으로 Microsoft에서 제공하는 기본 제공 콘텐츠에 사용할 수 있습니다. 고객은 이 플랫폼을 사용하여 서버에 대한 액세스 권한이 있는 사용자, 설치된 애플리케이션, 인증서가 최신 상태인 경우, 서버가 네트워크 위치에 연결할 수 있는지 여부와 같은 일반적인 시나리오를 감사합니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/d2d0531c-4e01-48be-9e08-e26d6760c504.png"><img alt="An image of the Definitions page in Azure Policy." border="0" height="683" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/9a7b8abf-99f0-4aa6-9b62-30222d45fac6.png" style="border: 0px currentcolor; border-image: none; display: inline; background-image: none;" title="Azure Policy의 정의 페이지 이미지입니다." width="1024"></a></p>


  <p>오늘부터 고객은 PowerShell 갤러리에 게시된 새 도구를 사용하여 개발자 워크스테이션과 ci/CD 플랫폼(예: Azure DevOps)에서 자체 콘텐츠 패키지를 작성, 테스트 및 게시할 수 있습니다.</p>


  <p>예를 들어 조직에서 개발한 Azure 가상 머신에서 애플리케이션을 실행하는 경우 Azure에서 해당 애플리케이션의 구성을 감사하고 플릿의 VM 중 하나가 규정을 준수하지 않을 때 알림을 받을 수 있습니다.</p>


  <p>이는 구성 기준을 감사해야 하는 규정 준수 팀의 중요한 이정표이기도 합니다. Microsofts&rsquo; 권장 보안 구성 기준을 사용하여 Windows 머신을 감사하는 기본 제공 정책이 이미 있습니다.&nbsp; 사용자 지정 콘텐츠는 구성 세부 정보, 그룹 정책의 인기 있는 원본에서 콘텐츠로 시나리오를 확장합니다. 그룹 정책 형식에서 Azure Policy 게스트 구성에서 사용하는 원하는 상태 구성 구문으로 변환하는 <a href="https://docs.microsoft.com/en-us/powershell/dsc/quickstarts/gpo-quickstart">데 사용할 수 있는 도구</a> 가 있습니다. 그룹 정책은 규정 표준을 게시하는 조직에서 사용하는 일반적인 형식이며 엔터프라이즈 조직에서 개인 데이터 센터의 서버를 관리하는 데 널리 사용되는 도구입니다.</p>


  <p>마지막으로, 사용자 지정 콘텐츠 패키지를 게시하는 고객은 타사 도구를 포함할 수 있습니다. 많은 고객이 프로덕션으로 릴리스되기 전에 가상 머신 내에서 설정 감사를 수행하는 데 사용되는 기존 도구를 가지고 있습니다. 예를 들어 <a href="https://github.com/microsoft/gcinspec" target="_blank">gcInSpec</a> 모듈은 Microsoft 및 Chef의 유지 관리자가 있는 오픈 소스 프로젝트로 게시됩니다. 고객은 이 모듈을 콘텐츠 패키지에 포함하여 Chef InSpec에 대한 기존 투자를 사용하여 Windows 가상 머신을 감사할 수 있습니다.</p>


  <p>자세한 내용 및 Azure Policy 게스트 구성에서 사용자 지정 콘텐츠 사용을 시작하려면 설명서 페이지 &rdquo;<a href="https://docs.microsoft.com/en-us/azure/governance/policy/how-to/guest-configuration-create" target="_blank">게스트 구성 정책을 만드는 방법을</a> 참조하세요.&rdquo;</p>
