### YamlMime:Yaml
ms.openlocfilehash: bea61daa290e50098f419b70ef5879be3fbfad0f
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139911569"
Slug: protecting-windows-virtual-desktop-environments-with-azure-security-center
Title: Azure Security Center를 사용하여 Windows Virtual Desktop 환경 보호
Summary: 이제 대규모 인력이 원격으로 이동하면서 IT 관리자와 보안 전문가는 진화하는 위협에 대처하면서 모든 사람의 생산성과 연결 상태를 유지해야 한다는 압박을 받고 있습니다.
Content: >-
  <p>이제 대규모 인력이 원격으로 이동하면서 IT 관리자와 보안 전문가는 진화하는 위협에 대처하면서 모든 사람의 생산성과 연결 상태를 유지해야 한다는 압박을 받고 있습니다.</p>


  <p><a href="https://www.microsoft.com/en-us/microsoft-365/blog/2019/09/30/windows-virtual-desktop-generally-available-worldwide" target="_blank">Windows Virtual Desktop</a>은 Azure에서 실행되는 포괄적인 데스크톱 및 애플리케이션 가상화 서비스로, VDI(가상 데스크톱 인프라)에 대한 간소화된 관리를 제공합니다.</p>


  <p>조직은 이러한 변환을 거치면서 직원들이 생산성을 유지할 수 있도록 하는 반면, IT 및 보안 전문가는 Windows Virtual Desktop의 배포가 보안 모범 사례에 따라 수행되므로 비즈니스에 불필요한 위험을 추가하지 않도록&rsquo; 해야 합니다. 이 블로그에서는 <a href="https://azure.microsoft.com/en-us/services/security-center/" target="_blank">Azure Security Center</a>가 Windows Virtual Desktop 환경 구성 위생 및 규정 준수를 유지하고 위협으로부터 보호하는 방법을 살펴보겠습니다.</p>


  <h2>Windows Virtual Desktop 호스트 풀 아키텍처 개요</h2>


  <p>Windows Virtual Desktop 환경을 설정할 때 먼저 하나 이상의 동일한 VM(가상 머신)의 컬렉션인 호스트 풀을 만들어야 합니다. 원격 인력 사용 사례를 지원하기 위해 이러한 VM은 일반적으로 Windows 10 다중 세션 OS를 실행합니다. 아키텍처에 대한 개요는 다음과 같습니다.<br>

  <a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/2278be12-2c0f-4ecb-bc7a-6694a9b6eeb9.png"><img alt="Customer Windows Virtual Desktop host pool VNET graph " border="0" height="599" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/a4c9a083-142d-4492-991a-f56517b74619.png" style="border: 0px currentcolor; border-image: none; display: inline; background-image: none;" title="" width="551"></a>&nbsp;<br>

  호스트 풀 세부 정보를 확인하고 <strong>리소스 그룹</strong> 이름을 클릭하여 호스트 풀에서 실행 중인 VM을 찾을 수 있습니다.</p>


  <p>&nbsp;<a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/8a7b37c9-a18b-41d3-b8d9-295b66f0d01c.png"><img alt="Windows Virtual Desktop host pools blade." border="0" height="827" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/2cc511b5-c228-4027-9682-737d80d1e467.png" style="border: 0px currentcolor; border-image: none; display: inline; background-image: none;" title="" width="1428"></a></p>


  <p>그러면 리소스 그룹 세부 정보가 표시됩니다. <strong>Virtual Machine</strong>으로 필터링하면 VM 목록이 표시됩니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/0aa3cf83-6502-4981-8d67-36305ab2420a.png"><img alt="Resource Group Windows Virtual Desktop VMs list." border="0" height="829" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/8ca8069a-300d-410d-833e-c57242be1d6b.png" style="border: 0px currentcolor; border-image: none; display: inline; background-image: none;" title="" width="1430"></a></p>


  <h2>Azure Security Center를 사용하여 Windows Virtual Desktop 배포 보안</h2>


  <p>공유 책임 모델을 고려할 때 고객이 Windows Virtual Desktop 배포에서 담당하는 <a href="https://docs.microsoft.com/en-us/azure/virtual-desktop/security-guide#security-responsibilities" target="_blank">보안 요구</a> 사항은 다음과 같습니다.</p>


  <ul>
      <li>Network.</li>
      <li>배포 구성.</li>
      <li>세션 호스트 OS.</li>
      <li>애플리케이션 보안.</li>
      <li>ID.</li>
  </ul>


  <p>이러한 요구 사항은 보안 상태와 위협 방지의 컨텍스트에서 모두 검사해야 합니다. 다음은 예제입니다.</p>


  <ul>
      <li>VM 네트워크 계층을 잘못 구성하면 공격 노출 영역이 늘어나고 엔드포인트가 손상됩니다. 한 가지 확인하려는 것은 Windows Virtual Desktop 가상 머신에서 모든 관리 포트를 닫아야 한다는 것입니다.</li>
      <li>사용자가 Windows Virtual Desktop 세션에 연결되면 악의적인 사이트로 이동하거나 악성 머신에 연결하도록 조작될 수 있습니다. 컴퓨터에 맬웨어가 있는 경우에도 발생할 수 있습니다. 네트워크 트래픽을 분석하여 컴퓨터가 명령 및 제어 센터와 통신한 것을 감지하는 것은 또 다른 보호 계층입니다.</li>
  </ul>


  <p>Azure Security Center는 Windows Virtual Desktop VM에 대한 다음과 같은 보안 상태 관리 및 위협 방지 기능을 제공합니다.</p>


  <ul>
      <li>보안 구성 평가 및 보안 점수</li>
      <li>업계에서 테스트된 취약성 평가</li>
      <li>호스트 수준 감지</li>
      <li>에이전트 없는 클라우드 네트워크 마이크로 세분화 &amp; 감지</li>
      <li>파일 무결성 모니터링</li>
      <li>Just-In-Time VM 액세스.</li>
      <li>적응형 애플리케이션 제어</li>
  </ul>


  <p>다음은 Virtual Desktop 보안 요구 사항을 Windows Azure Security Center 보호 기능을 매핑하는 표입니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/a6e2dcdf-32bb-4ab3-a5a0-14bdd58404ac.png"><img alt="Mapping of Azure Security Center protection capabilities to Windows Virtual Desktop security needs." border="0" height="480" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/a0c8cea3-f7dd-4bae-9a67-9e03b6494585.png" style="border: 0px currentcolor; border-image: none; display: inline; background-image: none;" title="" width="596"></a></p>


  <p>다음 Azure Security Center 참조 가이드에서 권장 사항 및 경고의 전체 목록을 찾을 수 있습니다.</p>


  <ul>
      <li><a href="https://docs.microsoft.com/en-us/azure/security-center/recommendations-reference" target="_blank">보안 권장 사항</a>.</li>
      <li><a href="https://docs.microsoft.com/en-us/azure/security-center/alerts-reference" target="_blank">경고 목록입니다</a>.</li>
  </ul>


  <p>Azure Security Center 포털로 전환하면 <strong>컴퓨팅 &amp; 앱</strong> 아래의 Windows Virtual Desktop 호스트 풀 VM<strong>과 VM 및 서버</strong> 탭, 해당 보안 점수 및 상태를 확인할 수 있습니다.</p>


  <p>&nbsp;<a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/38f41dfc-406c-474a-905d-d4182a139fdb.png"><img alt="In Azure Security Center portal, we can see the Windows Virtual Desktop host pool VMs under Compute &amp; apps followed by the VMs and Servers tab, as well as their respective Secure Score and status." border="0" height="593" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/f4404364-27b3-4f6f-8381-5b985655f72e.png" style="border: 0px currentcolor; border-image: none; display: inline; background-image: none;" title="" width="1024"></a></p>


  <p>특정 VM으로 드릴다운하면 전체 권장 사항 목록과 심각도 수준이 표시됩니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/4a4f498c-70a0-44e4-a02d-360abfbdc88d.png"><img alt="Showing full recommendation list as well as Severity level of a specific VM." border="0" height="593" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/fbd5085b-e782-47c2-9b24-a5ba7371010e.png" style="border: 0px currentcolor; border-image: none; display: inline; background-image: none;" title="" width="1024"></a>&nbsp;</p>


  <p>또한 이러한 VM은 다양한 규정 요구 사항, 기본 제공 또는 사용자 지정 요구 사항을 준수하는지 평가되며 규정 <a href="https://docs.microsoft.com/en-us/azure/security-center/security-center-compliance-dashboard">준수 대시보드</a>에 규정 준수 문제가 플래그가 지정됩니다.</p>


  <p>또한 보안 경고는 <strong>위협 방지</strong> 아래에 표시되고 보안 경고는 다음과 <strong>같이 표시됩니다.</strong></p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/855d5cda-ce51-4df3-8892-a3ef8230df29.png"><img alt="Showing VM security findings under Threat Protection blade followed by Security Alerts." border="0" height="597" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/68170ad4-9d82-41cc-8c3d-144ed45cc536.png" style="border: 0px currentcolor; border-image: none; display: inline; background-image: none;" title="" width="1024"></a></p>


  <p>보안 경고 및 권장 사항은 Security Center 포털에서 사용 및 관리하거나 추가 분석 및 수정을 위해 다른 도구로 내보낼 수 있습니다. 한 가지 좋은 예는 <a href="https://techcommunity.microsoft.com/t5/azure-sentinel/monitoring-windows-virtual-desktop-environments-fall-2019/ba-p/1356632" target="_blank">Windows Virtual Desktop 환경을 모니터링하는 일환으로 Azure Security Center를 Azure Sentinel과 통합하는</a> 것입니다.</p>


  <h2>Windows Virtual Desktop 환경에 Azure Security Center 사용</h2>


  <p>Azure Security Center 무료 계층은 Windows Virtual Desktop 배포에 대한 보안 권장 사항 및 보안 점수를 제공합니다.</p>


  <p>모든 보호 기능을 사용하도록 설정하려면 다음 두 단계를 수행해야 합니다.</p>


  <ol>
      <li>아래와 같이 Azure Security Center 표준 계층이 있는지 확인합니다.</li>
      <li>Virtual Machines에 대한 위협 방지를 사용하도록 설정합니다.</li>
  </ol>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/101d04c2-7a1b-46cb-970a-9bf19aa3296b.png"><img alt="Enabling threat protection for Virtual Machines in Azure Security Center." border="0" height="593" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/0760c703-2c4d-425e-be0e-135734cf5de0.png" style="border: 0px currentcolor; border-image: none; display: inline; background-image: none;" title="" width="1024"></a></p>


  <p>그리고 마지막 팁 하나. Azure Devops CI/CD Pipelines Windows 10 Azure VM 이미지와 함께 Windows Virtual Desktop 솔루션의 지속적인 빌드 및 배포를 위한 솔루션&rsquo;으로 사용하는 경우 비밀 관리를 위해 Azure Key Vault를 사용할 가능성이 높습니다. 아직 사용하도록 설정하지 않은 경우 <a href="https://techcommunity.microsoft.com/t5/azure-security-center/validating-azure-key-vault-threat-detection-in-azure-security/ba-p/1220336" target="_blank">Azure Key Vault에 대한 위협 방지</a> 를 설정하는 것이 다음 중지가 되어야 합니다.</p>


  <p>Windows Virtual Desktop 환경을 어떻게 보호하나요? 우리는 거기에 더 많은 아이디어가 있다고 확신하고 우리는 지역 사회가 우리의 <a href="https://github.com/Azure/Azure-Security-Center" target="_blank">GitHub 리포지토리</a>에 제출보고 싶어요.</p>
