### YamlMime:Yaml
ms.openlocfilehash: 752d9fad5564002e66d57eeaf9a594a3969179dd
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139911582"
Slug: protecting-applications-and-data-on-azure-stack
Title: Azure Stack에서 애플리케이션 및 데이터 보호
Summary: Azure Stack은 클라우드 컴퓨팅에 투자하는 많은 회사에 상당한 전략 변화를 제공합니다. 이 게시물에서는 비즈니스 요구 사항을 충족하는 솔루션에 대해 생각할 수 있도록 다양한 애플리케이션 유형 및 복구 목표에 대한 보호 목표를 살펴보겠습니다.
Content: >-
  <p>Azure는 54개 이상의 지역에서 Microsoft Datacenters에서 실행되는 글로벌 규모 클라우드 컴퓨팅을 제공합니다. Azure Stack은 고객 또는 서비스 공급자 데이터 센터에서 실행되는 통합 시스템에서 핵심 서비스 집합을 실행할 수 있도록 하여 Azure의 가치를 더 광범위한 고객&rsquo; 및 시나리오로 확장합니다. 많은 회사와 서비스 공급자가 자세한 내용을 알아보기 위해 ASDK(Azure Stack Development Kit)를 평가하고 있습니다. 이러한 회사 중 상당수는 최신 앱 및 온-프레미스 클라우드 서비스를 위한 하이브리드 클라우드의 전략, 디자인 및 구현을 통해 평가와 생각을 넘어서고 있습니다. BC/DR(비즈니스 연속성 및 재해 복구) 계획은 포괄적인 전략의 중요한 부분입니다.</p>


  <p>비즈니스 연속성 및 재해 복구 계획은 회사가 예기치 못한 위험을 준비하는 데 사용하는 프로세스와 밀접하게 관련이 있습니다. 이 게시물&rsquo;에서는 다양한 애플리케이션 유형 및 복구 목표에 대한 보호 목표를 살펴보고 비즈니스 요구 사항을 충족하는 솔루션에 대해 생각할 수 있습니다. 이러한 목표는 선택한 BC/DR 전략에 직접적인 영향을 미칩니다.</p>


  <h2>Azure Stack BC/DR 영역</h2>


  <p>BC/DR 전략을 위해 고려해야 할 네 가지 주요 영역은 다음과 같습니다.</p>


  <ul>
   <li>IaaS 가상 머신, PaaS 서비스 및 테넌트 애플리케이션 및 데이터를 호스트하는 기본 인프라를 보호합니다.</li>
   <li>IaaS 기반 애플리케이션 및 데이터를 보호합니다.</li>
   <li>PaaS 기반 애플리케이션 및 데이터를 보호합니다.</li>
   <li>장기 보존을 위해 PaaS 데이터를 보관합니다.</li>
  </ul>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/189e1431-5877-4e52-a9a0-82eacda3423c.png"><img alt="azure-stack" border="0" height="257" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/cb4adbbb-1970-43a7-bb4f-c5069a93be7c.png" style="border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="azure-stackThis" width="414"></a> 블로그는 백업 및 복원을 위해 Microsoft 및 파트너 제품을 사용하여 IaaS 가상 머신 기반 애플리케이션 및 데이터 보호, 복제 및 장애 조치(failover)에 중점을 둡니다. Azure Stack 팀은 여러 파트너와 협력하여 해당 타사 솔루션이 Azure Stack에서 작동하는지 확인합니다.&nbsp;</p>


  <h2>IaaS 가상 머신 기반 애플리케이션 백업 및 복원</h2>


  <p>Azure Stack은 IaaS Azure Resource Manager 가상 머신으로 프로비전되는 가상 머신에 배포된 Windows 및 Linux 기반 애플리케이션을 지원합니다. OS(게스트 운영 체제)에 액세스할 수 있는 백업 제품은 가까운 줄 및 장기 보존을 위해 현재 사용하는 유사한 정책을 사용하여 파일, 폴더, OS 상태 및 애플리케이션 데이터를 쉽게 보호할 수 있습니다. Azure Backup 및 System Center Data Center Protection Manager와 같은 Microsoft 제품과 타사 제품을 사용하여 온-프레미스, 서비스 공급자 또는 Azure에 직접 데이터를 백업할 수 있습니다. 이 방법을 사용하면 익숙한 제품과 신뢰를 사용하여 애플리케이션 및 데이터를 보호하기 위해 유연하게 선택할 수 있습니다.</p>


  <h2>IaaS 가상 머신 기반 애플리케이션에 대한 복제 및 장애 조치(failover)</h2>


  <p>가동 중지 시간을 최소화하고 데이터 손실을 최소화해야 하는 애플리케이션에는 추가 보호가 필요합니다. 백업 및 복원은 장기간 애플리케이션 가동 중지 시간을 허용할 수 있는 고객에게 적합합니다. 그러나 가동 중지 시간을 최소화하려면 데이터를 보조 위치에 복제하고 재해 발생 시 애플리케이션의 장애 조치(failover)를 오케스트레이션해야 합니다. Azure Stack을 사용하면 Azure Site Recovery를 사용하여 데이터를 Azure에 직접 복제하고 애플리케이션을 Azure에서 실행하도록 장애 조치(failover)할 수 있습니다. 이 기능은 현재 기술 미리 보기에서 사용할 수 있습니다. Microsoft SQL 같은 네이티브 복제를 지원하는 Azure Stack에 배포된 애플리케이션은 애플리케이션이 실행 중인 다른 위치에 데이터를 복제할 수 있습니다. 타사 복제 및 오케스트레이션 제품을 사용하여 애플리케이션을 다른 위치로 장애 조치(failover)할 수도 있습니다. 백업 및 복원과 마찬가지로 이 접근 방식은 애플리케이션 및 데이터를 보호하기 위한 유연성과 선택을 제공합니다.</p>


  <h2>Azure Stack 파트너 및 배포 시나리오</h2>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/749cc111-f291-4440-aad5-8baa089f97d4.png"><img alt="IaaS-virtual-machines" border="0" height="453" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/6d4b013c-280d-45c1-93d0-2eafb662f1fc.png" style="border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="IaaS-virtual-machines" width="1024"></a></p>


  <h2>파트너의 추가 정보</h2>


  <p>지원되는 파트너의 전체 목록은 <a href="https://aka.ms/azurestackbcdrpartners" target="_blank">Azure Stack 데이터 센터 통합 파트너 에코시스템</a> 데이터시트에 나와 있습니다.</p>


  <h2>일반 공급에 대한 중요한 고려 사항</h2>


  <ul>
   <li>게스트 내 protectionAzure&mdash; Stack은 IaaS 가상 머신의 게스트 수준에서 보호 기술만 지원합니다. Azure Stack은 기본 인프라 서버에 에이전트 설치를 지원하지 않으며 하이퍼바이저 기반 기술에 의존하지 않습니다.</li>
   <li>Azure Site RecoveryAzure&mdash; Site Recovery 기술 미리 보기는 Azure로 장애 조치(failover)를 지원하고 Azure에서 장애 조치(failover)를 테스트합니다. Azure에서 Azure Stack으로 장애 복구하려면 IaaS 가상 머신을 종료하고, 데이터를 Azure Stack 인스턴스에 수동으로 복사한 다음, IaaS 가상 머신을 다시 만들어야 합니다. 이 시점에서 IaaS 가상 머신에 대한 보호를 새 인스턴스로 사용하도록 설정할 수 있습니다.</li>
   <li>두 Azure Stack 클라우드에서 사이트 간 protectionProtecting&mdash; IaaS VM 리소스는 파트너 중 하나의 제품을 사용하여 지원됩니다.&nbsp;</li>
  </ul>


  <h2>치명적인 데이터 손실로부터 복구</h2>


  <p>BC/DR 계획은 전체 Azure Stack 클라우드를 영구적으로 오프라인으로 전환하여 완전하고 복구할 수 없는 데이터 손실을 초래하는 재해로부터 복구할 수 있도록 회사를 준비해야 합니다. Azure Stack 클라우드를 배포하려면 하드웨어 공급업체에 문의해야 합니다. 보조 사이트가 있는 경우 새 클라우드가 배포될 때까지 기다릴 필요 없이 테넌트 애플리케이션 및 데이터를 복구할 수 있는 Azure Stack 인스턴스를 배포하는 것이 좋습니다.</p>


  <h2>다음 단계</h2>


  <p>오늘 ASDK를 다운로드하여 설치하고 하이브리드 클라우드에서 애플리케이션을 호스팅하는 방법을 알아봅니다. Azure Stack에 배포하려는 애플리케이션에 대한 인사이트를 얻으면 애플리케이션에 대한 복구 목표를 생각해 보세요. 적합한 다양한 보호 체계를 식별하고 이러한 목표를 달성하는 데 도움이 되는 기술 및 제품을 고려합니다.</p>


  <p>공급업체에 연락하여 Azure Stack에서 BC/DR 시나리오를 지원하는 방법을 논의합니다. ASDK에서 애플리케이션 및 데이터 보호 테스트를 시작합니다.&nbsp;</p>


  <p><strong>설명서</strong></p>


  <ul>
   <li>사용자 IaaS VM <ul style="list-style-type:circle;">
    <li><a href="https://docs.microsoft.com/azure-stack/user/azure-stack-manage-vm-protect">Azure Stack에 배포된 VM 보호</a></li>
    <li><a href="https://docs.microsoft.com/azure/backup/backup-mabs-install-azure-stack">Azure Stack에 Azure Backup Server 설치</a></li>
    <li><a href="https://docs.microsoft.com/azure/site-recovery/azure-stack-site-recovery">Azure에 Azure Stack VM 복제</a></li>
   </ul>
   </li>
   <li>인프라 <ul style="list-style-type:circle;">
    <li><a href="https://docs.microsoft.com/azure-stack/operator/azure-stack-backup-infrastructure-backup">인프라 백업 서비스를 사용하여 Azure Stack에서 데이터 복구</a></li>
    <li><a href="https://docs.microsoft.com/azure-stack/operator/azure-stack-backup-reference">인프라 백업 서비스 참조</a></li>
    <li><a href="https://docs.microsoft.com/azure-stack/operator/azure-stack-backup-enable-backup-console">관리자 포털에서 Azure Stack에 대한 백업 사용</a></li>
   </ul>
   </li>
  </ul>


  <h2>추가 정보</h2>


  <p>추가 지침은 <a href="https://aka.ms/azurestackbcdrconsiderationswp" target="_blank">비즈니스 연속성 및 재해 복구 백서에 대한 Azure Stack 고려 사항을</a> 참조하세요.</p>


  <ul>
   <li>Azure Stack용 BC/DR에 대한 업데이트된 정보는 IaaS VM 블로그 시리즈의 4부를 확인하세요. <ul style="list-style-type:circle;">
    <li><a href="https://azure.microsoft.com/blog/azure-stack-iaas-part-four/">4 &ndash; 부 물건 보호</a></li>
   </ul>
   </li>
  </ul>
