### YamlMime:Yaml
ms.openlocfilehash: 0ec43e81abda8d0c631bcd109e28bdaa0f4996e2
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139897197"
Slug: real-time-serverless-applications-with-the-signalr-service-bindings-in-azure-functions
Title: Azure Functions에서 SignalR Service 바인딩을 사용하는 실시간 서버리스 애플리케이션
Summary: 'Microsoft Ignite 2018의 공개 미리 보기 발표 이후 전 세계 수천 명의 개발자가 매달 Azure Functions용 Azure SignalR Service 바인딩을 활용하여 서버리스 애플리케이션에 실시간 기능을 추가했습니다. '
Content: >-
  <p>Microsoft Ignite 2018의 공개 미리 보기 발표 이후 전 세계 수천 명의 개발자가 매달 Azure Functions용 Azure SignalR Service 바인딩을 활용하여 서버리스 애플리케이션에 실시간 기능을 추가했습니다. 오늘 Azure SignalR Service를 사용할 수 있는 모든 <a href="https://azure.microsoft.com/en-us/global-infrastructure/services/?products=signalr-service&amp;regions=all" target="_blank">글로벌 지역에서</a> 이러한 바인딩의 일반 공급에 대해 발표하게 되어 기쁩니다.</p>


  <p>SignalR Service는 HTTP를 통해 애플리케이션에 실시간 웹 기능을 추가하는 프로세스를 간소화하는 완전히 관리되는 Azure 서비스입니다. 이 실시간 기능을 사용하면 서비스에서 WebSocket과 같은 기술을 사용하여 연결된 클라이언트에 메시지 및 콘텐츠 업데이트를 푸시할 수 있습니다. 결과적으로 클라이언트는 서버를 폴링하거나 업데이트를 위해 새 HTTP 요청을 제출하지 않고도 업데이트됩니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/fb574bf4-b92d-417f-a380-e23713366813.gif"><img alt="20190306-real-time-app-gif" border="0" height="453" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/691a8794-113e-4065-a402-7f78a3069288.gif" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="20190306-real-time-app-gif" width="867"></a></p>


  <p>Azure Functions는 가속 개발 및 이벤트 기반 애플리케이션의 서버리스 호스팅을 위한 트리거 및 바인딩을 기반으로 하는 생산적인 프로그래밍 모델을 제공합니다. 이를 통해 개발자는 로컬에서 빌드 및 디버깅에서 클라우드의 배포 및 모니터링에 이르는 엔드 투 엔드 개발자 환경을 통해 선택한 프로그래밍 언어 및 도구를 사용하여 앱을 빌드할 수 있습니다. 이러한 바인딩을 사용하여 Azure SignalR Service와 Azure Functions를 결합하면 몇 줄의 코드만으로 애플리케이션의 UI에 업데이트를 쉽게 푸시할 수 있습니다. 이러한 업데이트의 원본은 이벤트에 응답하는 스크립트 실행을 시작하는 Azure Functions에서 지원되는 트리거 덕분에 다른 Azure 서비스에서 오는 데이터 또는 HTTP를 통해 통신할 수 있는 모든 서비스일 수 있습니다.</p>


  <p>언급할 가치가 있는 일반적인 시나리오는 데이터베이스에서 수정한 내용에 따라 애플리케이션의 UI를 업데이트하는 것입니다. Cosmos DB 변경 피드, Azure Functions 및 SignalR Service의 조합을 사용하여 이러한 업데이트를 수신할 클라이언트를 등록하고 업데이트 자체를 푸시하기 위한 몇 줄의 코드만으로 이러한 UI 업데이트를 실시간으로 자동화할 수 있습니다. 이 완전 관리형 환경은 이벤트 기반 시나리오에 적합하며 실시간 기능을 사용하여 서버리스 백 엔드 및 애플리케이션을 생성하여 개발 시간과 작업 오버헤드를 줄일 수 있습니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/6426254d-271f-4fa6-bf8f-699f400851e4.png"><img alt="20190306-real-time-app-graphic" border="0" height="455" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/88842d74-05c7-418c-b3e7-5776efaf9d30.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="20190306-real-time-app-graphic" width="854"></a></p>


  <p>Azure Functions에 대한 Azure SignalR Service 바인딩을 사용하여 다음을 수행할 수 있습니다.</p>


  <ul>
   <li>완전히 관리되는 서버리스 환경을 위해 애플리케이션 서버에 종속되지 않고 SignalR Service를 사용합니다.</li>
   <li>일반적으로 사용 가능한 모든 Azure Functions 언어(JavaScript, C#, <a href="https://azure.microsoft.com/en-us/blog/announcing-the-general-availability-of-java-support-in-azure-functions/" target="_blank">Java</a>)를 사용하여 서버리스 실시간 애플리케이션을 빌드합니다.</li>
   <li>Azure Functions에서 지원하는 모든 이벤트 트리거와 SignalR Service 바인딩을 활용하여 실시간으로 연결된 클라이언트에 메시지를 푸시합니다.</li>
   <li>보안 향상 및 완전 관리형 인증을 위해 SignalR Service 및 Azure Functions에서 App Service 인증을 사용합니다.</li>
  </ul>


  <h2>다음 단계</h2>


  <ul>
   <li><a href="https://aka.ms/af-binding" target="_blank">Azure Functions 및 Azure SignalR Service를 사용하여 실시간 앱 빌드</a> 설명서를 확인하세요&ldquo;.&rdquo;</li>
   <li>빠른 시작 &ldquo; 에 따라 <a href="https://docs.microsoft.com/en-us/azure/azure-signalr/signalr-quickstart-azure-functions-javascript" target="_blank">JavaScript를 사용하여 Azure Functions 및 SignalR Service로 채팅방을 만들어</a> 시작 &rdquo; 합니다.</li>
   <li><a href="https://github.com/Azure-Samples/signalr-service-quickstart-serverless-chat" target="_blank">GitHub 리포지토리</a>에서 더 많은 코드 샘플을 확인하세요.</li>
   <li><a href="https://azure.microsoft.com/free/serverless" target="_blank">Azure 계정에</a> 무료로 등록합니다.</li>
  </ul>


  <p>귀하의 피드백과 의견에 대해 듣고 싶습니다&#39;. <a href="https://github.com/azure/azure-signalr/issues" target="_blank">GitHub 리포지토리</a> 또는 <a href="mailto:asrs@microsoft.com">이메일로</a> 제품 팀에 연결할 수 있습니다.&nbsp;</p>
