### YamlMime:Yaml
ms.openlocfilehash: 45d577b916e0f01176e2d764f3120b6229b465a7
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139912500"
Slug: required-practice-for-applications-integrating-with-azure-active-directory
Title: Azure Active Directory 통합하는 애플리케이션에 필요한 연습
Summary: 이 게시물은 인증서 롤오버를 Azure Active Directory 2016년 8월 15일 이전 발표의 후속 작업입니다. Azure Active Directory 글로벌 서명 키를 롤오버하는 빈도를 늘릴 것입니다.
Content: >-
  <p>이 게시물은 Azure Active Directory 인증서 롤오버에 대한 <a href="https://azure.microsoft.com/en-us/blog/upcoming-azure-active-directory-certificate-rollover-august-15-2016/">이전 발표</a>의 후속 작업입니다.</p>


  <p>고객&rsquo; 데이터를 보호하고 2016년 8월 15일 롤오버의 모멘텀을 바탕으로 지속적으로 Azure Active Directory <strong>글로벌 서명 키(이전에는 Azure Active Directory&rsquo;</strong> 인증서&rdquo;라고 함)를 롤오버하는 &ldquo;빈도를 늘릴 것입니다.</p>


  <h2>애플리케이션의 빈도 증가는 무엇을 의미하나요?</h2>


  <ul>
      <li><a href="https://azure.microsoft.com/en-us/documentation/articles/active-directory-signing-key-rollover/#how-to-assess-if-your-application-will-be-affected-and-what-to-do-about-it">자동 롤오버를 지원하는</a> 애플리케이션의 경우 이 빈도 증가는 애플리케이션에 영향을 주지 않습니다.</li>
      <li>자동 롤오버를 지원하지 않는 애플리케이션의 경우 키를 주기적으로 모니터링하고 수동 롤오버를 수행하는 <a href="https://azure.microsoft.com/en-us/documentation/articles/active-directory-signing-key-rollover/#how-to-perform-a-manual-rollover-if-you-application-does-not-support-automatic-rollover">프로세스를 설정</a> 해야 합니다.</li>
  </ul>


  <p>2016년 10월 10일에 시작될 예정인 다음 롤오버는 발표될 마지막 롤오버입니다.</p>


  <p>앞으로는 공지 사항이 없으며 메타데이터에서 새 키를 사용할 수 있도록 한 다음 해당 새 키를 사용하여 점진적으로 전환하는 일반적인 단계만 진행합니다. 위에서 설명한 것처럼 자동 롤오버를 지원하는 애플리케이션은 이를 원활하게 처리하고 모니터링 프로세스를 사용하는 애플리케이션은 새 키를 사용할 수 있을 때 수동 롤오버를 수행합니다.</p>


  <p>영향을 평가하기 위한 지침은 8월 롤오버와 동일하게 유지됩니다.</p>


  <h2>다음의 영향을 기대하지 않습니다.</h2>


  <ul>
      <li><a href="https://aka.ms/aadcertificaterollover">모범 사례</a>에 따라 자동 롤오버를 지원하는 애플리케이션</li>
      <li>클라이언트 애플리케이션</li>
      <li><a href="https://azure.microsoft.com/en-us/marketplace/active-directory/all/">Azure Active Directory 앱 갤러리</a>에서 추가된 애플리케이션(사용자 지정&rdquo; 포함&ldquo;)</li>
      <li>애플리케이션 프록시를 통해 게시된 온-프레미스 애플리케이션</li>
      <li>Azure Active Directory B2C 테넌트에 있는 애플리케이션</li>
  </ul>


  <p>간단히 말해서<strong> 애플리케이션이 8월 롤오버의 영향을 받지 않는 경우 10월 롤오버 또는 후속 롤오버의 영향을 받지 않습니다.</strong></p>


  <h2>애플리케이션 영향</h2>


  <p>애플리케이션은 서명 키에 종속되며 메타데이터에서 키를 자동으로 업데이트하도록 구성되지 않습니다. 아래 정보를 따라 애플리케이션에 대한 롤오버의 영향 및 필요한 경우 키 롤오버를 처리하도록 업데이트하는 방법을 평가합니다.</p>


  <ol>
      <li>관리자 계정을 사용하여 <a href="https://manage.windowsazure.com/">Azure 클래식 포털</a> 에 로그인합니다.</li>
      <li><strong>Active Directory</strong> 탭에서 디렉터리를 선택합니다.</li>
      <li><strong>드롭다운 표시</strong> 메뉴에서 <strong>회사가 소유한 애플리케이션</strong>을 선택한 다음 오른쪽의 확인 표시를 클릭하여 필터를 적용합니다.</li>
      <li>Azure Active Directory 설명서의 <a href="https://aka.ms/aadcertificaterollover">서명 키 롤오버</a>에 대한 지침을 사용하여 나열된 각 애플리케이션을 검토하고 필요한 경우 권장 사항을 변경합니다.</li>
  </ol>


  <p>비정상적인 동작이 발생하는 경우 <a href="https://azure.microsoft.com/en-us/support/options/">Azure 지원에</a> 문의하세요.</p>
