### YamlMime:Yaml
ms.openlocfilehash: 15a05fdecaa365e08199f098b927976fae0a13c9
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139912499"
Slug: research-shows-cloud-computing-reduces-time-and-money-spent-managing-security
Title: 연구에 따르면 클라우드 컴퓨팅은 보안 관리에 소요되는 시간과 비용을 줄입니다.
Summary: '보안은 종종 비즈니스에 대한 클라우드 컴퓨팅 채택의 주요 관심사 또는 장벽 중 하나로 보고됩니다. 이러한 인식을 해소하기 위해 Microsoft는 오늘날 중소기업이 클라우드를 사용하여 상당한 IT 보안 이점을 얻고 있음을 보여주는 연구를 발표했습니다. '
Content: >-
  <p>보안은 종종 비즈니스용 <a href="https://azure.microsoft.com/en-us/overview/what-is-cloud-computing">클라우드 컴퓨팅</a>&nbsp;의 주요 관심사 또는 장벽 중 하나로 보고됩니다. 이러한 인식을 해소하기 위해 Microsoft는 오늘날 SMB(중소기업)가 클라우드를 사용하여 상당한 IT 보안 이점을 얻고 있음을 보여주는<span style="background-color: #ffffff;"> research를 <a href="https://www.microsoft.com/en-us/news/Press/2012/May12/05-14SMBSecuritySurveyPR.aspx" target="_blank">발표</a></span>했습니다.</p>


  <p>Microsoft가 의뢰하고 리서치 회사 comScore가 실시한 이 연구는 미국, 싱가포르, 말레이시아, 인도 및 홍콩 시장의 SMB 회사를 대상으로 실시되었습니다.</p>


  <p>미국의 연구 결과는 다음 세 가지 주요 영역에서 이점을 보여줍니다.</p>


  <ul>
   <li>시간 절약: 미국 기업의 32%는 사이버 공격의 위협에 대해 걱정하는 데 시간을 덜 소비한다고 말합니다.</li>
   <li>비용 절감: 클라우드를 사용하는 SMB는 클라우드를 사용하지 않는 SMB보다 보안에 소요되는 총 금액을 거의 6배 더 줄일 가능성이 높습니다.</li>
   <li>보안 개선: 미국 기업의 35%가 클라우드로 이전한 이후 눈에 띄게 높은 수준의 보안을 경험했습니다.</li>
  </ul>


  <p>클라우드 서비스를 사용하기 전에 보안을 관리하는 데 소요된 시간과 돈은 비즈니스를 성장시키고 경쟁력을 높이기 위해 SMB에 의해 재투자되고 있습니다.</p>


  <p><a href="https://www.microsoft.com/en-us/news/Press/2012/May12/05-14SMBSecuritySurveyPR.aspx" target="_blank">Microsoft 뉴스 센터</a> 및 신뢰할 수 있는 컴퓨팅 블로그에 대한 연구에 대해 자세히 확인할 수 있습니다<span style="background-color: #ffffff;"><i>.</i>&nbsp;</span>&nbsp;</p>
