### YamlMime:Yaml
ms.openlocfilehash: 5d95126f68a4fb7f73da3e156cb772360ecd467a
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139912467"
Slug: revamped-solutions-in-azure-for-application-and-infrastructure-monitoring
Title: 앱 및 인프라용 Azure의 엔드 투 엔드 모니터링 솔루션
Summary: 오늘 플로리다에서 열린 Ignite 2017 컨퍼런스에서는 Azure Monitor의 통합 큐레이팅된 개요에서 애플리케이션 및 인프라 모니터링을 통합하는 Azure의 다양한 새로운 모니터링 및 분석 기능을 발표했습니다. 새로운 로그 분석, 메트릭 탐색, 애플리케이션 성능 모니터링 및 실패 조사를 통해 환경을 크게 최적화하고 있습니다. 또한 It Service Management 도구 및 컨테이너 모니터링을 위한 새로운 솔루션과 Azure 경고의 통합을 발표했습니다.
Content: >-
  <p>오늘 플로리다에서 열린 <a href="https://www.microsoft.com/ignite/default.aspx">Ignite 2017</a> 컨퍼런스에서는 Azure Monitor의 통합 큐레이팅된 개요에서 애플리케이션 및 인프라 모니터링을 통합하는 Azure의 다양한 새로운 모니터링 및 분석 기능을 발표했습니다. 새로운 로그 분석, 메트릭 탐색, 애플리케이션 성능 모니터링 및 실패 조사를 통해 환경을 크게 최적화하고 있습니다. 또한 It Service Management 도구 및 컨테이너 모니터링을 위한 새로운 솔루션과 Azure 경고의 통합을 발표했습니다.</p>


  <h2>Azure Monitor에서 모니터링 서비스 통합</h2>


  <p><a href="https://docs.microsoft.com/azure/monitoring-and-diagnostics/">이제 Azure Monitor</a>에서 가상 머신에서 애플리케이션, 애플리케이션의 개별 코드 줄에 이르기까지 모든 클라우드 리소스의 상태 및 성능에 대한 한눈에 보고할 수 있습니다. 이제 Azure Monitor는 공개 미리 보기에서 Azure의 다양한 모니터링 서비스에 대한 탐색 및 온보딩을 위한 시작점으로 <a href="https://docs.microsoft.com/azure/monitoring-and-diagnostics/monitoring-overview-azure-monitor">통합된 개요</a> 를 제공합니다. 고객은 애플리케이션 &amp; 인프라에서 주목할 만한 문제를 한 곳에서 보고 컨텍스트에서 탐색할 수 있습니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/accd990d-acdd-40ee-bf0a-55f4db73ed00.png"><img alt="Capture1" border="0" height="391" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/59a40abf-0dca-45a9-a99a-3701c373d638.png" style="border-width: 0px; display: inline;" title="Capture1" width="1024"></a></p>


  <p>이제 Azure Monitor는 Virtual Machines, 네트워킹, ServiceBus, EventHubs 등과 같은 Azure 서비스의 플랫폼 메트릭에 대한 공개 미리 보기에서 <a href="https://docs.microsoft.com/azure/monitoring-and-diagnostics/monitoring-near-real-time-metric-alerts">거의 실시간 경고를 </a>제공합니다. 거의 실시간 경고에서 지원하는 모든 리소스의 전체 목록은 <a href="https://docs.microsoft.com/en-us/azure/monitoring-and-diagnostics/monitoring-near-real-time-metric-alerts#what-resources-can-i-create-near-real-time-metric-alerts-for">설명서</a>에서 찾을 수 있습니다. 또한 Azure Monitor는 네트워킹, Storage, Traffic Manager, 네트워크 인터페이스, Express 경로, 부하 분산 장치, Data Lake Store, Data Lake Analytics 등과 같은 많은 서비스에서 새 메트릭과 로그를 표시할 수 있도록 합니다. Azure Monitor를 통해 사용할 수 있는 모든 리소스 및 메트릭의 전체 목록은 <a href="https://docs.microsoft.com/en-us/azure/monitoring-and-diagnostics/monitoring-supported-metrics">설명서</a>에서 찾을 수 있습니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/105d60f7-346f-4343-9992-33bc01987603.png"><img alt="NRTAlert" border="0" height="768" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/e2a891d3-56e1-4459-9815-2527974979fb.png" style="border: 0px currentColor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block;" title="Azure Monitor용으로 릴리스된 NRTAlertAlso" width="334"></a>는 다차원 및 기본 메트릭 모두에 대한 렌더링 차트를 지원하는 완전히 <a href="https://docs.microsoft.com/azure/monitoring-and-diagnostics/monitoring-metric-charts">수정된 메트릭 탐색</a> 환경의 공개 미리 보기입니다. 다양한 리소스의 차트 오버레이 메트릭을 그릴 수 있으며 동시에 여러 차트를 확인하여 메트릭 값의 추세, 급증 및 급락을 시각적으로 상호 연결할 수 있습니다. 다차원 메트릭(예: 애플리케이션 Insights 또는 Storage)을 지원하는 리소스의 경우 원하는 차원/값 조합에 필터를 적용하거나 그룹화하여 각 차원 값에 대한 줄을 볼 수 있습니다.</p>


  <p>&nbsp;<a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/6f7aef85-66c3-4988-b8db-5cccee19f5f9.png"><img alt="StorageAndAppInsights Metrics With Filter" border="0" height="557" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/62b6fb18-9033-461f-a6a3-2d043c345b1c.png" style="border-width: 0px; display: inline;" title="필터를 사용하는 StorageAndAppInsights 메트릭" width="1024"></a></p>


  <p>Azure Monitor는 작업 그룹의 새로운 ITSM 작업을 통해 선택한 ITSM(IT Service Management) 도구(System Center Service Manager, Service Now, Provance 또는 Cherwell)와 통합할 수 있습니다. ITSM 작업을 사용하면 사용자가 Azure 경고가 발생할 때 ITSM 도구에서 작업 항목(인시던트, 이벤트 또는 경고)을 자동으로 만들 수 있습니다. 이 ITSM 작업은 Azure Log Analytics의 <a href="https://docs.microsoft.com/en-us/azure/log-analytics/log-analytics-itsmc-overview">ITSM 커넥터 솔루션을</a> 기반으로 합니다. 고객은 솔루션을 통해 지원 센터 데이터(예: 인시던트 및 변경 요청)와 로그 데이터(예: 활동 및 진단 로그, 성능 및 구성 변경)의 기능을 결합하여 인시던트 문제를 신속하게 완화할 수 있습니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/2e418384-5dbd-4b33-acc8-be4355f7fe74.png"><img alt="ITSMAction" border="0" height="473" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/a612ca20-1892-4b3e-b632-875e84ac6ca6.png" style="border: 0px currentColor; border-image: none; display: inline;" title="ITSMAction" width="1024"></a></p>


  <h2>새 Log Analytics &amp; 컨테이너 모니터링 솔루션</h2>


  <p><a href="https://docs.microsoft.com/azure/application-insights">Azure Application Insights</a> 및 <a href="https://docs.microsoft.com/azure/log-analytics/">Azure Log Analytics</a>는 사용자가 <a href="https://aka.ms/appinsightscrossapp">여러 애플리케이션 Insights 애플리케이션 또는 여러</a> <a href="https://aka.ms/loganalyticscrossworkspace">Log Analytics 작업 영역에서</a> 쿼리할 수 있도록 리소스 간 쿼리의 공개 미리 보기를 제공합니다. 이렇게 하면 다중 계층 또는 지역 분산 애플리케이션뿐만 아니라 여러 논리 인프라 그룹에서 쿼리할 수 있습니다. 업그레이드 출시가 한 달 전에 시작된 새롭고 향상된 Log Analytics는 이제 새 쿼리 언어에 대한 <a href="https://dev.loganalytics.io/">REST API</a> 를 제공하고 있습니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/c491b639-52db-49c4-8f08-d7abae53f479.png"><img alt="Capture 3" border="0" height="525" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/ce4d41d0-135e-4584-bd3d-82fb036291b6.png" style="border: 0px currentColor; border-image: none; display: inline;" title="캡처 3" width="1024"></a></p>


  <p>컨테이너 <a href="https://docs.microsoft.com/azure/log-analytics/log-analytics-containers">모니터링 솔루션</a>은 성능, 로그, 이벤트 및 인벤토리뿐만 아니라 Kubernetes 이벤트에 대한 컨테이너 모니터링을 제공하는 Windows Kubernetes Environment에 지원됩니다. Kubernetes용으로 빌드된 소프트웨어를 지원, 공유 및 사용하는 패키지 관리자인 Helm은 솔루션을 통합하여 고객이 Linux Kubernetes 환경에 컨테이너 모니터링을 쉽게 찾고 배포할 수 있도록 합니다. <a href="https://docs.microsoft.com/azure/service-fabric/service-fabric-diagnostics-event-analysis-oms"> Linux에서 Service Fabric</a> GA를 컨테이너 오케스트레이터로 사용하면 Log Analytics는 Azure Monitoring Agent를 사용하여 컨테이너 모니터링 정보를 캡처합니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/37d1e83c-b2ae-40a3-b346-1617f69e0dd6.png"><img alt="ContainerSolution" border="0" height="472" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/5e342a9f-6de2-4059-8873-7878e6796fb2.png" style="border: 0px currentColor; border-image: none; display: inline;" title="ContainerSolution" width="1024"></a></p>


  <h2>Azure Application Insights 개선된 사용자 환경</h2>


  <p><a href="https://docs.microsoft.com/azure/application-insights/">애플리케이션 Insights</a> <a href="https://docs.microsoft.com/azure/application-insights/app-insights-tutorial-performance">성능 모니터링</a>&nbsp; 및 <a href="https://docs.microsoft.com/azure/application-insights/app-insights-tutorial-runtime-exceptions">실패 진단</a>(공개 미리 보기)에 대한 사용자 환경을 완전히 새로 고쳐 대화형 환경을 제공하고 상황에 맞는 인사이트를 표시했습니다. 이제 고객은 프로덕션 환경에서 속도가 느린 특정 최종 사용자 환경을 신속하게 심사하고 기간 분포를 시각화하여 좋은 사용자 환경과 나쁜 사용자 환경 모두에 대한 전체적인 통계 보기를 얻을 수 있습니다. 코드 수준 표시 유형(프로파일러)으로의 효과적인 전환 및 느린 종속성에 대한 진단 정보는 클릭 한 번만 가능합니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/9c950266-ab07-4585-8ff0-8fc63813817f.png"><img alt="Capture" border="0" height="511" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/d2f18939-8c49-4270-bf02-78d05681ea6b.png" style="border-width: 0px; display: inline;" title="캡처" width="1024"></a></p>


  <p>새로운 오류 조사 환경을 사용하면 주요 실패 작업, 예외 유형, 실패한 종속성을 신속하게 식별하고&nbsp; 수정할 수 있으며 최종 사용자에게 미치는 영향을 확인할 수 있습니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/efd490f8-2959-4c4e-a84c-c65ccd35ea34.png"><img alt="Capture2" border="0" height="509" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/ef967414-865e-4406-bcc4-42031d09e783.png" style="border: 0px currentColor; border-image: none; display: inline;" title="Capture2" width="1024"></a></p>


  <p><a href="https://docs.microsoft.com/mobile-center/">Visual Studio Mobile Center</a>는 이제 사용자가 <a href="https://docs.microsoft.com/mobile-center/analytics/export">애플리케이션 Insights 연결</a>하고 모든 사용량 원격 분석 이벤트의 복사본을 지속적으로 내보낼 수 있다고 발표했습니다. 여기에서 Application Insights 임시 쿼리, 필터링, 세분화 및 다양한 사용 현황 분석을 중심으로 제공하는 다양한 기능 집합을 사용하여 Mobile Center 데이터를 쿼리하고 분석할 수 있습니다.</p>


  <h2>오늘 시작</h2>


  <p>Azure 모니터링 및 분석 서비스를 사용하면 고급 데이터 분석 및 시각화를 통해 환경에 대한 가시성을 높이고 인사이트를 작업으로 쉽게 전환할 수 있습니다. <a href="https://azure.microsoft.com/solutions/monitoring/">모니터링 솔루션</a>의 기능과 하이브리드 클라우드 환경의 복잡성을 줄이는 방법에 대해 자세히 알아봅니다.</p>
