### YamlMime:Yaml
ms.openlocfilehash: d9082923987324e47eea5a481ea43a10247c758e
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139912465"
Slug: rewrite-http-headers-with-azure-application-gateway
Title: Azure Application Gateway를 사용하여 HTTP 헤더 다시 쓰기
Summary: Azure Application Gateway에서 HTTP 헤더를 다시 작성하는 기능을 공유하게 되어 기쁘게 생각합니다. 이를 통해 요청 및 응답 패킷이 클라이언트와 백 엔드 애플리케이션 간에 이동하는 동안 HTTP 요청 및 응답 헤더를 추가, 제거 또는 업데이트할 수 있습니다.
Content: >-
  <p>Azure Application Gateway에서 HTTP 헤더를 다시 작성하는 기능을 공유하게 되어 기쁘게 생각합니다. 이를 통해 요청 및 응답 패킷이 클라이언트와 백 엔드 애플리케이션 간에 이동하는 동안 HTTP 요청 및 응답 헤더를 추가, 제거 또는 업데이트할 수 있습니다. 조건을 추가하여 지정한 헤더가 조건이 충족되는 경우에만 다시 작성되도록 할 수도 있습니다. 또한 이 기능은 요청 및 응답에 대한 추가 정보를 저장하는 데 도움이 되는 여러 <a href="https://docs.microsoft.com/azure/application-gateway/rewrite-http-headers#server-variables">서버 변수</a> 를 지원하므로 강력한 다시 쓰기 규칙을 만들 수 있습니다.</p>


  <p align="center"><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/560ba068-75c3-4f45-aaa1-ae25b36fbd91.png"><img alt="A diagram showing how X-Forwarded_For affects  how the client interacts with the application gateway and backend application." border="0" height="214" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/168757e7-54d0-4155-8ec0-faea6819b90c.png" style="border: 0px currentcolor; border-image: none; display: inline; background-image: none;" title="그림-1A 다이어그램은 X-Forwarded_For 클라이언트가 애플리케이션 게이트웨이 및 백 엔드 애플리케이션과 상호 작용하는 방식에 미치는 영향을 보여 줍니다." width="1090"></a></p>


  <p align="center"><em>그림 1: Application Gateway가 요청의 X-Forwarded-For 헤더에서 포트 정보를 제거하고 응답에서 위치 헤더를 수정합니다.</em></p>


  <p>헤더를 다시 작성하면 몇 가지 중요한 시나리오를 수행할 수 있습니다. 일반적인 사용 사례 중 일부는 아래에 설명되어 있습니다.</p>


  <h2>X-Forwarded-For 헤더에서 포트 정보 제거</h2>


  <p>Application Gateway는 백 엔드에 요청을 전달하기 전에 모든 요청에 <em>X-Forwarded-For</em> 헤더를 삽입합니다. 이 헤더의 형식은 IP:Port의 쉼표로 구분된 목록입니다. 그러나 백 엔드 애플리케이션에 IP 주소만 포함하도록 헤더가 필요한 시나리오가 있을 수 있습니다. 이러한 시나리오 중 하나는 대부분의 CMS가 헤더의 추가 포트 정보를 구문 분석할 수 없기 때문에 백 엔드 애플리케이션이 CMS(콘텐츠 관리 시스템)인 경우입니다. 이러한 시나리오를 수행하려면 포트 정보 없이<em> X-Forwarded-For </em>클라이언트 요청 헤더를 포함하는 add_x_forwarded_for_proxy 서버 변수로 헤더를 설정할 수 있습니다.</p>


  <p align="center"><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/2df63651-7690-4e0b-aa7e-c9b780a06a09.png"><img alt="Image showing how to remove port information from the X-Forwarded-For heading." src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/ccf9953c-c18a-493a-97eb-a71170e7dc0d.png" style="border: 0px currentcolor; border-image: none; width: 546px; height: 377px; display: inline; background-image: none;" title="그림 2 X-Forwarded-For 제목에서 포트 정보를 제거하는 방법을 보여 주는 그림 2Image입니다."></a></p>


  <p align="center"><em>그림 2: X-Forwarded-For 헤더에서 포트 정보를 제거하기 위한 Application Gateway 구성입니다.</em></p>


  <h2>App Service 및 기타 다중 테넌트 백 엔드와의 통합 개선</h2>


  <p>백 엔드 애플리케이션이 리디렉션 응답을 보낼 때 백 엔드 애플리케이션에서 지정한 것과 다른 URL로 클라이언트를 리디렉션할 수 있습니다. 이러한 시나리오 중 하나는 App Service가 애플리케이션 게이트웨이 뒤에서 호스트되는 경우입니다.</p>


  <p>App Service는 다중 테넌트 서비스이므로 요청의 호스트 헤더를 사용하여 올바른 엔드포인트로 라우팅합니다. 앱 서비스에는 애플리케이션 게이트웨이&#39;도메인 이름( <tt>예: contoso.com</tt>)과 다른 *.azurewebsites.net( <tt>예: contoso.azurewebsites.net</tt>)의 기본 도메인 이름이 있습니다. 클라이언트의 원래 요청에는 애플리케이션 게이트웨이&#39;도메인 이름이 호스트 이름으로 <tt>contoso.com</tt> 있으므로 애플리케이션 게이트웨이는 호스트 이름을 <tt>contoso.azurewebsites.net</tt> 변경하여 백 엔드의 앱 서비스가 올바른 엔드포인트로 라우팅할 수 있도록 합니다. 그러나 앱 서비스가 리디렉션 응답을 보낼 때 애플리케이션 게이트웨이에서 수신하는 요청의 호스트 이름과 동일한 호스트 이름을 응답의 위치 헤더에 사용합니다. 따라서 앱 서비스가 상대 경로(<tt>/path1에서 /path2</tt>로 리디렉션)로 리디렉션을 수행하는 경우 클라이언트는 <tt></tt>애플리케이션 게이트웨이(contoso.com/path2)를 통과하는 대신 <tt>contoso.azurewebsites.net/path2</tt> 직접 요청을 수행<tt></tt>합니다. 이는 바람직하지 않은 애플리케이션 게이트웨이를 무시합니다.</p>


  <p>이 문제는 위치 헤더의 호스트 이름을 애플리케이션 게이트웨이&#39;도메인 이름으로 설정하여 해결할 수 있습니다. 이렇게 하려면 응답의 위치 헤더에 azurewebsites.net 포함되어 있는지 평가하고 애플리케이션 게이트웨이&#39;호스트 이름을 갖도록 위치 헤더를 다시 작성하는 작업을 수행하는 조건으로 다시 쓰기 규칙을 만들 수 있습니다.</p>


  <p align="center"><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/718adb6e-c3ba-4433-93ab-b169360b7cdc.png"><img alt="An image showing how to configure a gateway for modifying the location header." src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/89cbeaf1-559f-48de-a789-cc856f171602.png" style="border-image: none; width: 541px; height: 852px; display: inline; background-image: none;" title="fig 3 위치 헤더를 수정하기 위한 게이트웨이를 구성하는 방법을 보여 주는 이미지"></a></p>


  <p align="center"><em>그림 3: 위치 헤더를 수정하기 위한 Application Gateway 구성입니다.</em></p>


  <h2>보안 관련 HTTP 헤더를 구현하여 취약성 방지</h2>


  <p>애플리케이션 응답에서 필요한 헤더를 구현하여 몇 가지 보안 취약성을 해결할 수 있습니다. 이러한 보안 헤더 중 일부는 X-XSS-Protection, Strict-Transport-Security, Content-Security-Policy, X-Frame-Options 등입니다. Application Gateway를 사용하여 모든 응답에 대해 이러한 헤더를 설정할 수 있습니다.</p>


  <h2>시작</h2>


  <p><a href="https://docs.microsoft.com/azure/application-gateway/rewrite-http-headers">Application Gateway를 사용하여 HTTP 헤더 다시 쓰기</a>에 대해 자세히 알아보고  <a href="https://docs.microsoft.com/en-us/azure/application-gateway/rewrite-http-headers-portal">Application Gateway에서 HTTP 헤더 다시 쓰기</a>를 구성하는 방법에 대한 자세한 지침을 찾을 수 있습니다.</p>


  <h2>피드백을 보내주세요.</h2>


  <p>피드백을 제공하는 몇 가지 경로가 있습니다.</p>


  <ul>
   <li><strong>UserVoice:</strong>  Application Gateway에 대한 새 아이디어를  <a href="https://feedback.azure.com/forums/217313-networking?category_id=134448">MicrosoftUserVoice 페이지에 게시합니다</a>.</li>
   <li><strong>코호트에 조인: </strong> 새&rsquo; 고객이 코호트에 가입하여 새 기능에 조기에 액세스하고 앞으로 Application Gateway를 개선하는 데 도움이 되는 데 항상 관심이 있습니다. 코호트에 가입하려는 경우 <a href="https://aka.ms/ApplicationGatewayCohort">이 빠른 양식을 작성하기만</a> 하면 됩니다.</li>
  </ul>
