### YamlMime:Yaml
ms.openlocfilehash: aee0cfeb027a5f349a5943a0a848d2795c7fca37
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139912424"
Slug: run-remote-applications-anytime-anywhere-with-frame-for-azure-government
Title: Azure Government용 Frame을 사용하여 언제 어디서나 원격 애플리케이션 실행
Summary: '오늘 Microsoft Government 기술 서밋에서 Frame은 Azure Government에서 사용할 수 있다고 발표했습니다. 프레임을 사용하면 고객이 온-프레미스 VDI(Virtual Desktop Infrastructure)의 높은 비용 없이 보안 DaaS(Desktop-as-a-Service) 기능을 배포할 수 있습니다. '
Content: >-
  <p><em>이 블로그 게시물은 Azure Global의 수석 프로그램 관리자인 Steve Downs가 작성했습니다. </em></p>


  <p>오늘 Microsoft Government 기술 서밋에서 <a href="https://fra.me/">Frame</a> 은 Azure Government에서 사용할 수 있다고 발표했습니다. Frame을 사용하면 고객이 높은 온-프레미스 VDI(Virtual Desktop Infrastructure) 비용 없이 보안 DaaS(Desktop-as-a-Service) 기능을 배포할 수 있으며, Frame Government Edition은 정부 Microsoft Azure 보안 인증을 가장 많이 사용하여 정부 클라우드에 배포할 수 있는 기능을 향상시킵니다 &ndash; .</p>


  <p>프레임 고객은 Azure Government에서 호스트되고 NV 시리즈 가상 머신에서 지원되는 그래픽 집약적 애플리케이션을 활용하기 위해 웹 브라우저가 필요합니다. 비용이 많이 드는 고급 워크스테이션은 더 이상 필요하지 않습니다. 또한 고객은 앱 시작 관리자를 <a href="https://blog.fra.me/launch-apps-on-frame-directly-from-office-365-f53d0ce46c83">Office 365 사용자에게 Frame 애플리케이션을 추가하여 사용자&rsquo;</a> 환경을 간소화할 수 있습니다.</p>


  <p>Frame의 공공 부문 책임자인 Jason Holloway는<i> Frame Platform Government Edition이 클라우드에서 Windows 데스크톱 애플리케이션을 쉽게 마이그레이션하고 관리할 수 있는 엔터프라이즈 지원 가상화 솔루션을 제공한다고 말&quot;했습니다. Azure Government에서 Frame 플랫폼을 사용할 수 있게 하는 것은 시장</i><i>-</i> <i>출시 상업용 플랫폼을 공공 부문에 도입하기 위한 여정의 중요한 이정표입니다.&rdquo;</i></p>


  <p>자세한 내용은 <a href="https://fra.me/frame-azure-gov-GA">Frame&#39;공 </a>지 사항을 확인하고 액세스를 요청하는 방법을 알아보세요.</p>


  <p>또한 최근 보안 &amp; 솔루션 디렉터인 David Reber<a href="https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fchannel9.msdn.com%2Fblogs%2FAzure-Government%2FVDI-with-Frame-on-Azure-Government&amp;data=04%7C01%7Ctina.meek%40microsoft.com%7C65c230618689442119c208d57fc15081%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636555390641305455%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwifQ%3D%3D%7C-1&amp;sdata=ynYE4ttCALLUqqB2uXK7YUHTMtimzMkve829tfcGBcs%3D&amp;reserved=0">와의 인터뷰를 </a>시청하여 정부 사용자에게 관심 있는 데모와 함께 Frame&#39;제품에 대한 자세한 정보를 얻을 수 있습니다.</p>


  <h2>추가 정보</h2>


  <ul>
      <li><a href="https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmedium.com%2F%40jason.holloway%2F136157954bf4&amp;data=04%7C01%7Ctina.meek%40microsoft.com%7C65c230618689442119c208d57fc15081%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636555390641305455%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwifQ%3D%3D%7C-1&amp;sdata=G2S7wU7eNeKg025j4VYd2EUSAv9ilc%2Fh7EzQqDqbvJ4%3D&amp;reserved=0">공공 부문을 위한 맞춤형: 프레임은 Microsoft Azure 정부에서 일반 공급됩니다.</a></li>
      <li><a href="https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fchannel9.msdn.com%2Fblogs%2FAzure-Government%2FVDI-with-Frame-on-Azure-Government&amp;data=04%7C01%7Ctina.meek%40microsoft.com%7C65c230618689442119c208d57fc15081%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636555390641305455%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwifQ%3D%3D%7C-1&amp;sdata=ynYE4ttCALLUqqB2uXK7YUHTMtimzMkve829tfcGBcs%3D&amp;reserved=0">Azure Government 데모의 프레임</a></li>
  </ul>
