### YamlMime:Yaml
ms.openlocfilehash: 515e1a0eeb8ebfe87a8aa31a9345d508fcffb8de
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139912408"
Slug: run-your-lob-applications-with-postgresql-powered-by-the-plv8-extension
Title: plv8 확장으로 구동되는 PostgreSQL을 사용하여 LOB 애플리케이션 실행
Summary: 이제 PostgreSQL용 plv8 확장이 Azure Database for PostgreSQL 서비스의 모든 일반 공급 지역에서 사용하도록 설정되어 있음을 발표하게 되어 매우 기쁩니다. plv8 확장은 성장하는 고객 기반 및 PostgreSQL 커뮤니티의 요청이 높은 UserVoice 중 하나입니다.
Content: >-
  <p>PostgreSQL용 plv8 확장이 이제 Microsoft Azure Database for PostgreSQL의 모든 일반 공급 지역에서 사용하도록 설정되어 있음을 공유하게 되어 매우 기쁩니다. plv8 확장은 성장하는 고객 기반 및 PostgreSQL 커뮤니티의 <a href="https://feedback.azure.com/forums/597976-azure-database-for-postgresql" target="_blank">요청이 높은 UserVoice</a> 중 하나입니다. 새로운 시나리오와 가능성을 잠금 해제하는 인기 있는 커뮤니티 확장이며, 개발자가 SQL 호출할 수 있는 JavaScript로 함수를 작성할 수도 있습니다.</p>


  <p>PostgreSQL은 강력한 네이티브 JSON 기능을 갖춘 설정된 오픈 소스 데이터베이스이며 plv8 확장은 JavaScript v8 엔진을 SQL 통합하여 이를 더욱 향상시킵니다. <a href="https://jasperfx.github.io/marten/" target="_blank">Marten 라이브러리</a> 는 plv8 확장을 사용하여 개발자가 PostgreSQL을 NoSQL 문서 저장소 또는 이벤트 저장소로 활용할 수 있도록 하는 라이브러리 중 하나입니다. PostgreSQL을 문서 데이터베이스로 사용하면 소매 카트 애플리케이션, 마켓플레이스 솔루션, IoT 이벤트 처리 및 LOB 애플리케이션을 디자인하고 개발할 수 있는 새로운 가능성이 열립니다.</p>


  <p>엔터프라이즈, 중소기업 및 ISV는 이제 관리되는 Azure Database for PostgreSQL 서비스에서 LOB 애플리케이션의 개발 및 배포를 가속화할 수 있습니다. 이를 통해 출시 시간을 단축할 수 있습니다.</p>


  <p>Azure Database for PostgreSQL에서 plv8 확장을 사용하는 방법의 예를 살펴보겠습니다. 이 예제에서는 plv8 확장이 있는 PostgreSQL 데이터베이스에서 제공하는 오픈 소스 ERP + CRM 웹 애플리케이션인 <a href="https://xtuple.com/about" target="_blank">xTuple</a>을 사용합니다. 무료 PostBooks 버전이 있는 xTuple 플랫폼은 거의 모든 업계에서 비즈니스 소프트웨어를 위한 훌륭한 시작점을 제공합니다. 비즈니스의 경우 상용 버전의 기능을 확장하고 더 추가할 수 있습니다. <a href="https://github.com/xtuple/xtuple" target="_blank">Github</a>의 xTuples&rsquo; 솔루션은 위에서 작업할 전체 스택이며 송장, 통화, 작업, 연락처 등 이미 구현된 많은 비즈니스 개체를 사용할 수 있습니다.</p>


  <p>xTuple에는 xTuple PostBooks <a href="https://github.com/xtuple/qt-client" target="_blank">데스크톱 클라이언트</a>를 실행하기 위한 PostgreSQL 설치 및 구성에 대한 <a href="https://xtupleuniversity.xtuple.com/sites/default/files/prodguide/admin-guide/server-setup.html" target="_blank">광범위한 단계별 가이드</a>가 있습니다. 관리형 Azure Database for PostgreSQL 서비스를 사용하면 몇 분 안에 xTuple ERP + CRM 플랫폼을 시작하고 실행할 수 있습니다.</p>


  <h2>xTuple용 PostgreSQL 초기화</h2>


  <p>아직 익숙하지 않은 경우 빠른 시작 자습서를 사용하여 <a href="https://docs.microsoft.com/en-us/azure/postgresql/quickstart-create-server-database-portal" target="_blank">Azure Portal</a> 또는 <a href="https://docs.microsoft.com/azure/postgresql/quickstart-create-server-database-azure-cli" target="_blank">Azure CLI</a>를 사용하여 관리되는 PostgreSQL 서버를 프로비전합니다.&nbsp; 서버를 프로비전한 후 서버 관리자 사용자 역할로 pgadmin&rdquo; 또는 &ldquo;psql&rdquo;을 사용하여 &ldquo;서버에 연결하고 아래와 같이 xTuple 소프트웨어용 PostgreSQL을 초기화합니다.</p>


  <pre>

  CREATE ROLE xtrole WITH NOLOGIN;

  GRANT azure_pg_admin TO xtrole;

  CREATE ROLE admin WITH PASSWORD &#39;admin&#39;
                          NOSUPERUSER
                          CREATEDB
                          CREATEROLE
                          LOGIN
                          IN ROLE xtrole;</pre>

  <p>아래와 같이 서버 연결을 끊은 다음 위에서 만든 관리자 사용자를 사용하여 다시 연결하여 UTF8 인코딩을 사용하여 xTuple 애플리케이션에 대한 데이터베이스를 만듭니다.</p>


  <pre>

  CREATE DATABASE xtupledb
       WITH
       OWNER = admin
       ENCODING = &#39;UTF8&#39;
       LC_COLLATE = &#39;English_United States.1252&#39;
       LC_CTYPE = &#39;English_United States.1252&#39;
       CONNECTION LIMIT = -1;</pre>

  <h2>Azure Database for PostgreSQL에서 plv8 확장 사용</h2>


  <p>다음으로 데이터베이스에 대해 plv8 확장을 사용하도록 설정하고 아래와 같이<strong> plv8.start_proc</strong> 변수를 설정합니다.</p>


  <pre>

  CREATE EXTENSION plv8;

  ALTER DATABASE xtupledb  SET &quot;plv8.start_proc&quot; TO &quot;xt.js_init&quot;;</pre>


  <p>연결을 끊은 다음 다시 연결하여 관리 사용자를 사용하여 새 세션을 설정하여 <strong>plv8.start_proc</strong> 매개 변수의 값을 확인합니다. 지정된 값이 모든 후속 새 세션에 대해 설정되고 반영되므로 <a href="https://www.postgresql.org/docs/10/static/sql-alterdatabase.html" target="_blank">ALTER DATABASE SET</a>&rdquo; 명령을 사용하여 &ldquo; 매개 변수 값을 설정할 때 필요합니다.</p>


  <pre>

  SELECT plv8_version();

  Show plv8.start_proc;</pre>


  <p>이제 데이터베이스 xtupledb가 xTuple ERP 솔루션에 전원을 공급할 준비가 되었습니다. 가이드에 따라 <a href="https://xtuple.com/products/postbooks/installing-postbooks-database" target="_blank">PostBooks 데이터베이스를 설치할 수 있습니다</a>. 데이터베이스가 복원되면 xTuple 데스크톱 앱을 설치하고 찾아볼 준비가 된 것입니다.</p>


  <p>데이터베이스를 복원하는 동안 <a href="https://xtupleuniversity.xtuple.com/sites/default/files/prodguide/admin-guide/ch02s04.html" target="_blank">xTuple 설명서</a>에 설명된 대로 안전하게 무시될 수 있는 일부 오류 메시지 또는 경고가 표시될 수 있습니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/680a1c8f-3f7c-4bf5-b998-3d629cb8c753.png"><img alt="xTuple log in" border="0" height="387" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/5b737941-b165-48b6-a099-e8141e6157d1.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="xTuple 로그인" width="500"></a></p>


  <p>이제 완전히 관리되는 Azure Database for PostgreSQL에서 실행되는 오픈 소스 xTuple ERP 솔루션을 사용하여 비즈니스를 수행할 준비가 되었습니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/9a0ff0bb-7a14-4e47-966f-61596546d440.png"><img alt="Practice Database" border="0" height="1020" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/2ecf586b-eebd-4c1c-b965-15f757d3a238.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="연습 데이터베이스" width="1920"></a></p>


  <p>Azure Database for PostgreSQL의 plv8 확장을 시도하고 활용하여 PostgreSQL의 새로운 시나리오 및 NoSQL 기능을 잠금 해제하는 것이 좋습니다. 지금 <a href="https://aka.ms/CreateazurePostgreSQLDB" target="_blank">PostgreSQL</a> 서버를 시작하고 만듭니다!</p>


  <p><a href="https://docs.microsoft.com/azure/postgresql/overview" target="_blank">개요</a> 및 <a href="https://docs.microsoft.com/en-us/azure/postgresql/concepts-extensions" target="_blank">지원되는 확장</a>에서 Azure Database for PostgreSQL에 대해 자세히 알아봅니다.</p>


  <p>다음에 보려는 <a href="https://feedback.azure.com/forums/597976-azure-database-for-postgresql" target="_blank">기능과 기능에 대한 피드백을</a> 계속 제공하세요. 도움이 필요하거나 질문이 있는 경우 <a href="https://docs.microsoft.com/en-us/azure/postgresql/" target="_blank">Azure Database for PostgreSQL 설명서를</a> 확인하세요. 최신 뉴스 및 발표에 대한 트위터에 <a href="https://twitter.com/AzureDBPostgres" target="_blank">@AzureDBPostgreSQL</a> 우리를 따르십시오.</p>


  <h2>관련 참고 자료</h2>


  <ul>
   <li><a href="https://xtupleuniversity.xtuple.com/library/articles/compatibility-matrix" target="_blank">PG/xTuple 버전 호환성 매트릭스</a></li>
  </ul>


  <ul>
   <li><a href="https://xtupleuniversity.xtuple.com/library/videos/introduction-xtuple-dashboards" target="_blank">PostgreSQL의 plv8 확장으로 구동되는 대시보드 소개</a></li>
  </ul>


  <h2>감사의 글</h2>


  <p>xTuple의 네드 릴리와 페리 클라크뿐만 아니라 수닐 카마스, 레이첼 아지메그, 짐 톨랜드가 이 게시물에 기여한 것에 대해 특별한 감사를 표합니다.</p>
