### YamlMime:Yaml
ms.openlocfilehash: db66cbdd7076323878ca7990fcc2525ed67f4a11
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139912393"
Slug: running-critical-application-workloads-on-microsoft-azure-d-series-virtual-machines
Title: Microsoft Azure D 시리즈 Virtual Machines에서 중요한 애플리케이션 워크로드 실행
Summary: AzureCAT(Azure 고객 자문 팀)에서 D 시리즈라는 퍼블릭 클라우드에 도입된 최신 세대의 하드웨어 구성 요소의 성능을 테스트해 왔습니다.
Content: >-
  <p align="justify">AzureCAT(Azure 고객 자문 팀)에서 D 시리즈라는 퍼블릭 클라우드에 도입된 최신 세대의 하드웨어 구성 요소 중 하나의 성능을 테스트해 왔습니다. 특히 멋진 점은 이전 VM 시리즈에 비해 중요한 워크로드 애플리케이션의 성능을 크게 향상시키는 데 도움이 되는 방법입니다. 이는 <a href="https://msdn.microsoft.com/en-us/library/azure/dn248436.aspx">이전 백서</a>에서 설명한 대로 Microsoft SQL Server 기반으로 하는 솔루션에 매우 중요합니다. 우리의 새로운 사실 인정은 그 시험을 확장합니다.</p>

  <p align="justify">고객은 기존 데이터 센터에서 Microsoft Azure VM(가상 머신)으로 애플리케이션을 전환하는 간단한 방법을 원하지만 성능은 중요한 워크로드의 핵심이며 항상 이를 얻지는 못했다고 말했습니다.</p>

  <p align="justify">D 시리즈는 성능과 관련된 두 가지 주요 기능을 제공하며, 둘 다 특정 애플리케이션을 변경할 필요가 없습니다.</p>


  <ul>
      <li>
  <div align="justify">SSD(반도체 드라이브)를 기반으로 하는 로컬 스토리지(임시)</div></li>
      <li>
  <div align="justify">더 많은 수의 연결된 데이터 디스크(D14 VM의 경우 최대 32개)</div></li>

  </ul>

  <p align="justify">성능 테스트에서는 이러한 새로운 기능을 사용하여 애플리케이션을 조정하고 성능이 향상되었습니다. 예를 들면 다음과 같습니다.</p>


  <ul>
      <li>
  <div align="justify">TempDB 파일을 D13 VM<strong></strong>의 로컬 SSD 스토리지에 배치하면 <strong>연결된 데이터 디스크가 있는 A7 VM의 처리량이 동일한 SQL Server 생성된 IO 패턴에 대한 이전 대기 시간의 약 4.5배</strong>에 해당합니다.</div></li>
      <li>
  <div align="justify">32개의 연결된 디스크가 있는 D14 VM은 16개의 연결된 디스크가 있는 A7 VM에 비해 <strong>최대 85% 더 많은 쓰기 IOPS 및 대역폭</strong> 을 제공할 수 있습니다.</div></li>

  </ul>

  <p align="justify">D 시리즈가 Microsoft Azure <a href="https://www.microsoft.com/en-us/download/details.aspx?id=45328">Virtual Machine에서 중요한 애플리케이션 워크로드를 실행하는</a> 백서에서 고객에게 상당한 차이를 만드는 네 가지 시나리오를 문서화했습니다.</p>

  <p align="justify">다음을 설명합니다.</p>


  <ul>
      <li>
  <div align="justify">영구 디스크 대기 시간이 응용 프로그램 응답 시간에 직접적으로 영향을 줄 수 있는 방법.</div></li>
      <li>
  <div align="justify">SQL Server tempdb 사용이 중요할 경우 영구 디스크의 제한된 처리량이 응용 프로그램 성능에 영향을 줄 수 있는 방법.</div></li>
      <li>
  <div align="justify">애플리케이션 계층에서 SSD 기반 고속 스토리지를 사용하여 임시 파일 처리를 가속화하는 방법입니다.</div></li>
      <li>
  <div align="justify">D 시리즈 VM의 임시 드라이브에서 %temp% 폴더를 이동하여 대규모 ASP.NET 웹 애플리케이션의 컴파일 및 시작 시간을 줄이는 방법입니다.</div></li>

  </ul>

  <p align="justify">기본적으로 Azure의 새로운 D 시리즈 VM은 데이터 계층과 애플리케이션 계층 모두에서 성능에 중요한 워크로드를 실행하는 데 도움이 될 수 있으며, CPU, 스토리지 및 네트워킹에 대해 전반적으로 더 나은 성능을 제공하며 다른 VM 시리즈에 비해 가격 성능 비율을 높일 수 있습니다.</p>

  <p align="justify">OLTP 데이터베이스 서버와 같은 특정 애플리케이션 시나리오는 주로 버퍼 풀을 확장하고 임시 작업을 호스트하기 위한 로컬 SSD 기반 임시 스토리지의 이점을 누릴 수 있습니다. 애플리케이션 서버는 더 빠르고 짧은 대기 시간 로컬 스토리지와 이 새로운 세대의 VM에서 제공하는 향상된 CPU 성능의 이점을 누릴 수 있습니다.</p>

  <p align="justify">애플리케이션 성능 향상을 위한 세부 정보 및 제안에 대한 <a href="https://www.microsoft.com/en-us/download/details.aspx?id=45328">백서를</a> 다운로드합니다. 그리고 D 시리즈에 대한 <a href="https://azure.microsoft.com/blog/2014/10/06/d-series-performance-expectations/">성능 기대 문서를</a> 확인하세요.</p>
