### YamlMime:Yaml
ms.openlocfilehash: 5726e13a00a80cdc8da579b55a581c849e4e89ed
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139912374"
Slug: sampling-in-application-insights
Title: '애플리케이션 Insights 샘플링: 원격 분석 볼륨을 제어하는 방법'
Summary: '많은 사용자가 있는 최신 애플리케이션은 많은 원격 분석 데이터를 생성할 수 있습니다. 애플리케이션 원격 분석의 모든 부분을 절대적으로 수집해야 한다는 매우 일반적인(그리고 거의 항상 잘못된) 인식이지만, 이렇게 하면 높은 가격으로 발생할 수 있습니다. '
Content: >-
  <p>많은 사용자가 있는 최신 애플리케이션은 많은 원격 분석 데이터를 생성할 수 있습니다. 애플리케이션 원격 분석의 모든 부분을 절대적으로 수집해야 한다는 매우 일반적인(그리고 거의 항상 잘못된) 인식이지만, 이렇게 하면 높은 가격으로 발생할 수 있습니다. 애플리케이션 Insights 더 많은 데이터를 저장하는 비용 증가 외에도 애플리케이션의 네트워크 사용량이 증가하고 모니터링으로 인한 성능 영향이 높을 수 있습니다.</p>


  <p>또한 원격 분석 볼륨이 <a href="https://go.microsoft.com/fwlink/?LinkID=691451">제한 제한을</a> 초과하면 애플리케이션 Insights 데이터 삭제를 시작합니다. 이 경우 애플리케이션 원격 분석은 완전히 제어할 수 없습니다. 메트릭은 더 이상 정확한 값을 반영하지 않으며 찾고&#39;원격 분석 항목이 제한될 수 있으므로 진단 환경이 중단됩니다. 수집된 데이터의 볼륨을 제어하고 너무 많은 원격 분석을 생성하지 못하도록 보호하기 위해 최근 릴리스된 <a href="https://go.microsoft.com/fwlink/?LinkID=691452">Application Insights SDK 2 베타</a>에서는 <em>샘플링</em> 개념이 도입되었습니다.</p>


  <p>애플리케이션 관점에서 샘플링은 포털에서 애플리케이션 데이터의 통계적으로 올바른 분석을 유지하면서 감소된 원격 분석 집합을 수집하고 저장할 수 있는 SDK의 기능입니다. 현재 샘플링은 클라이언트와 서버 쪽의 ASP.NET 웹 애플리케이션과 함께 사용하거나 다른(.NET이 아닌) 서버 쪽 플랫폼으로 작성된 웹 애플리케이션의 경우 클라이언트 쪽에서만 사용할 수 있습니다.</p>


  <p>샘플링&nbsp;을 통해 애플리케이션 원격 분석 볼륨을 낮추고&nbsp; <a href="https://azure.microsoft.com/en-us/documentation/articles/app-insights-sampling/">여기서</a> 웹 애플리케이션을 사용하여 샘플링을 구성하는 방법을 자세히&nbsp; 알아봅니다.</p>
