### YamlMime:Yaml
ms.openlocfilehash: ca9db4d2225f56099d470a9a3bf3ef808b552284
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139900947"
Slug: sap-applications-certified-on-azure
Title: Azure에서 인증된 SAP 애플리케이션
Summary: Microsoft와 SAP 모두에서 전폭적인 지원을 제공하는 SAP Business Suite, SAP NetWeaver 및 SAP HANA Developer Edition용 SAP에서 Azure를 인증했다고 발표하게 된 것을 자랑스럽게 생각합니다.
Content: >-
  Microsoft와 SAP 모두에서 전폭적인 지원을 제공하는 SAP Business Suite, SAP NetWeaver 및 SAP HANA Developer Edition용 SAP에서 Azure를 인증했다고 발표하게 된 것을 자랑스럽게 생각합니다.


  오늘부터 SAP 라이선스가 있는 고객은 이를 사용하여 Microsoft Azure SAP 소프트웨어를 배포할 수 있습니다. 이를 통해 Microsoft 및 SAP 투자의 가치를 최대화하고 클라우드의 주문형 리소스를 활용할 수 있습니다. 고객은 변화하는 비즈니스 요구 사항을 신속하게 해결하고 간소화된 인프라 관리, 출시 시간 개선 및 비용 절감의 이점을 누릴 수 있습니다. 몇 분 만에 가상 머신을 배포하여 SAP 솔루션에 필요한 인프라를 만들 수 있습니다.


  이 파트너십은 고객이 Azure에서 비즈니스를 실행하는 데 사용하는 애플리케이션 및 서비스를 지원하고 클라우드의 기능을 활용하려는 고객을 위한 강력한 엔터프라이즈 지원 플랫폼을 제공하기 위한 Microsoft의 지속적인 노력을 나타냅니다. 표준 구매 모델, 가격 책정 및 약관은 기본 Azure 서비스에 적용되며 고객은 다른 배포와 마찬가지로 이러한 서비스를 사용하고 비용을 지불합니다.


  앞으로 몇 달 안에 더 많은 SAP 제품에 대한 지원을 발표할 예정입니다.  <a href="https://azure.microsoft.com/en-us/campaigns/sap">Azure 페이지의SAP</a>에서 인증에 대해 자세히 알아보고 시작하세요.


  <span style="text-decoration: underline;"> </span>
