### YamlMime:Yaml
ms.openlocfilehash: 39d4494c68eee085839ee25dab2c1a1f7546a22c
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139900933"
Slug: sap-on-azure-architecture-designing-for-security
Title: Azure 아키텍처의 SAP - 보안을 위한 디자인
Summary: Azure 아키텍처의 뛰어난 SAP는 보안, 성능 및 확장성, 가용성 및 복구 가능성, 효율성 및 운영의 핵심 요소에 기반을 두고 있습니다.
Content: >-
  <p><em>이 블로그 게시물은 Azure의 SAP 기술 전문가인 Chin Lai The에 의해 제공되었습니다</em>.</p>


  <p>이는 Azure 아키텍처에서 훌륭한 SAP를 설계하는 네 부분으로 구성된 블로그 시리즈의 첫 번째 시리즈이며 보안을 위한 설계에 중점을 집니다.</p>


  <p>Azure 아키텍처의 뛰어난 SAP는 보안, 성능 및 확장성, 가용성 및 복구 가능성, 효율성 및 운영의 핵심 요소에 기반을 두고 있습니다.</p>


  <h2>Azure Security에 대한 Microsoft 투자</h2>


  <p>Microsoft는 보안 연구 개발에 매년 10억 달러를 투자하고 있으며 회사 전체에 3,500명의 보안 전문가가 근무하고 있습니다. 고급 AI는 Microsoft 클라우드 플랫폼에서 6.5조 개의 글로벌 신호를 분석하고 위협을 감지하고 대응하는 데 활용됩니다. Enterprise 등급 보안 및 개인 정보 보호는 <a href="https://gallery.technet.microsoft.com/Cloud-Red-Teaming-b837392e" target="_blank">Red Team 연습</a>과 같은 실제 테스트에 의한 지속적이고 엄격한 유효성 검사를 포함하여 Azure 플랫폼에 기본 제공됩니다. 이러한 테스트를 통해 Microsoft는 위반 탐지 및 대응을 테스트하고 실제 공격의 준비 상태와 영향을 정확하게 측정할 수 있으며 Azure에 동급 최고의 보안을 제공하는 많은 운영 프로세스 중 하나에 불과합니다.</p>


  <p>Azure는 국가, 지역 및 보건, 금융, 정부 및 제조와 같은 특정 산업을 아우르는 <a href="https://www.microsoft.com/en-us/trustcenter/compliance/complianceofferings" target="_blank">90개의 규정 준수 인증</a> 을 갖춘 신뢰의 플랫폼입니다. 또한 <a href="https://azure.microsoft.com/en-au/services/blueprints/" target="_blank">Azure 보안 및 규정 준수 청사진을</a> 사용하여 규격 환경을 쉽게 만들고, 배포하고, 업데이트할 수 있습니다.</p>


  <h2>공동 책임 보안 &ndash;</h2>


  <p>&rsquo;고객과 Microsoft 간의 공동 책임 모델을 이해하는 것이 중요합니다. 책임 분할은 사용되는 클라우드 모델(SaaS, PaaS 또는 IaaS)에 따라 달라집니다. 고객은 선택한 클라우드 배포에 관계없이 데이터, 엔드포인트, 계정/액세스 관리를 항상 담당합니다.</p>


  <p>Azure의 SAP는 IaaS 클라우드 모델을 사용하여 제공됩니다. 즉, 물리적 데이터 센터, 물리적 네트워크 및 물리적 호스트에서 Microsoft에서 보안 보호가 서비스에 기본 제공됩니다. 그러나 Azure 하이퍼바이저 이외의 모든 영역(예: 운영 체제 및 애플리케이션)의 경우 고객은 엔터프라이즈 보안 제어가 구현되도록 해야 합니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/60d7bef4-2237-4103-a17c-28aa4a6fa1e3.jpg"><img alt="A diagram looking at the responsibilities of the customer versus the service they are using." border="0" height="480" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/7ae64021-b5bc-44f8-b4b5-eb615302eb4c.jpg" style="border: 0px currentcolor; margin-right: auto; margin-left: auto; display: block; background-image: none;" title="고객의 책임과 사용 중인 서비스를 살펴보는 다이어그램." width="900"></a></p>


  <h2>Azure에서 SAP를 배포하기 위한 주요 보안 고려 사항</h2>


  <h3>리소스 기반 액세스 제어 &amp; 리소스 잠금</h3>


  <p><a href="https://docs.microsoft.com/en-us/azure/role-based-access-control/overview" target="_blank">RBAC(역할 기반 액세스 제어)</a> 는 Azure 리소스 관리를 위해 세분화된 액세스를 제공하는 권한 부여 시스템입니다. RBAC를 사용하여 IT 운영 내의 다양한 팀에 대한 Azure 리소스에 대한 액세스 및 제어 권한을 제한할 수 있습니다.</p>


  <p>예를 들어 SAP 기본 팀 구성원은 VM(가상 머신)을 Azure VNet(가상 네트워크)에 배포할 수 있는 권한을 부여받을 수 있습니다. 그러나 SAP 기본 팀은 VNet을 만들거나 구성하는 것을 제한할 수 있습니다. 반대로 네트워킹 팀의 구성원은 VNet을 만들고 구성할 수 있지만 SAP 애플리케이션이 실행되는 VNet에서 VM을 배포하거나 구성하는 것은 금지됩니다.</p>


  <p>Azure 프로젝트에서 SAP의 수명 주기 동안 RBAC 디자인의 유효성을 검사하고 테스트하는 것이 좋습니다.</p>


  <p>또 다른 중요한 고려 사항은 VM 및 디스크와 같은 <a href="https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-lock-resources" target="_blank">Azure 리소스</a> 를 실수로 삭제하거나 수정하는 것을 방지하는 데 사용할 수 있는 Azure 리소스 잠금입니다.&nbsp; SAP 프로젝트를 시작할 때 필요한 Azure 리소스를 만드는 것이 좋습니다. 모든 추가 기능, 이동 및 변경이 완료되고 Azure의 SAP 배포가 작동하면 모든 리소스를 잠글 수 있습니다. 다음으로 슈퍼 관리자만 리소스의 잠금을 해제하고 리소스(예: VM)를 수정할 수 있습니다.</p>


  <h3>보안 인증</h3>


  <p>SSO(Single Sign-On)는 SAP 및 Microsoft 제품을 통합하기 위한 토대를 제공하며, 수년 동안 Microsoft Active Directory의 Kerberos 토큰은 타사 보안 제품과 결합된 경우 SAP GUI 및 웹 브라우저 기반 애플리케이션 모두에서 이 기능을 사용하도록 설정해 왔습니다.</p>


  <p>사용자가 워크스테이션에 로그온하고 Microsoft Active Directory에 대해 성공적으로 인증하면 Kerberos 토큰이 발급됩니다. 그런 다음, 사용자가 다시 인증하지 않고도 타사 보안 제품에서 Kerberos 토큰을 사용하여 SAP 애플리케이션에 대한 인증을 처리할 수 있습니다. 또한 사용자 프런트 엔드에서 SAP 애플리케이션으로 전송 중인 데이터는 보안 제품을 DIAG(SAP GUI), RFC 및 HTTPS용 SPNEGO용 SNC(보안 네트워크 통신)와 통합하여 암호화할 수도 있습니다.</p>


  <p>SAML 2.0을 사용하는 Azure AD(Azure Active Directory)를 사용하여 SAP NetWeaver, SAP HANA 및 SAP Cloud Platform과 같은 다양한 SAP 애플리케이션 및 플랫폼에 SSO를 제공할 수도 있습니다.</p>


  <p>이 <a href="https://www.youtube.com/watch?v=AGCZA8CCIYo" target="_blank">비디오에서</a>는 <a href="https://docs.microsoft.com/en-us/azure/active-directory/saas-apps/sap-netweaver-tutorial#configure-and-test-azure-ad-single-sign-on-for-sap-netweaver" target="_blank">Azure AD와 SAP NetWeaver 간에 SSO</a>를 엔드투엔드로 사용하도록 설정하는 방법을 보여 줍니다.</p>


  <h3>네트워크 취약성으로부터 애플리케이션 및 데이터 보호</h3>


  <p>NSG(네트워크 보안 그룹)에는 Azure VNet 내의 리소스에 대한 네트워크 트래픽을 허용하거나 거부하는 보안 규칙 목록이 포함되어 있습니다. NSG는 서브넷 또는 VM에 연결된 개별 네트워크 인터페이스에 연결할 수 있습니다. 원본/대상, 포트 및 프로토콜에 따라 보안 규칙을 구성할 수 있습니다.<br>

  NSG&rsquo;는 SAP 시스템의 네트워크 트래픽에 영향을 줍니다. 아래 다이어그램에서는 세 개의 서브넷이 구현되며, 각각 NSG(FE(프런트 엔드), 앱 및 DB가 할당됩니다.</p>


  <ol>
      <li>공용 인터넷 사용자는 포트 443을 통해 SAP Web-Dispatcher 연결할 수 있습니다.</li>
      <li>SAP Web-Dispatcher 포트 443을 통해 SAP 애플리케이션 서버에 연결할 수 있습니다.</li>
      <li>앱 서브넷은 10.0.0.0/24에서 포트 443의 트래픽을 허용합니다.</li>
      <li>SAP 애플리케이션 서버는 포트 30015의 트래픽을 SAP DB 서버로 보냅니다.</li>
      <li>DB 서브넷은 포트 30015에서 10.0.1.0/24의 트래픽을 허용합니다.</li>
      <li>공용 인터넷 액세스는 앱 서브넷과 DB 서브넷 모두에서 차단됩니다.</li>
  </ol>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/057224a5-7281-4cb7-9794-2488ec92a815.png"><img alt="A diagram showing three subnets with NSGs influencing network traffic." height="531" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/95f118f5-8c72-42da-9ca9-4f5fb95a66cd.png" style="border-width: 0px; border-style: solid; border-image: none; width: 1024px; height: 604px; margin-right: auto; margin-left: auto; display: block; background-image: none;" title="740 블로그" width="900"></a></p>


  <p><a href="https://docs.microsoft.com/en-us/azure/architecture/vdc/networking-virtual-datacenter" target="_blank">Azure 가상 Ddatacenter</a> 아키텍처를 사용하는 SAP 배포는 허브 및 스포크 모델을 사용하여 구현됩니다. 허브 VNet은 SAP 애플리케이션이 상주하는 스포크 VNet에 대한 트래픽 라우팅을 검사하고 제어하기 위해 <a href="https://docs.microsoft.com/en-us/azure/firewall/overview" target="_blank">Azure Firewall</a> 또는 다른 유형의 NVA( <a href="https://azure.microsoft.com/en-us/solutions/network-appliances/" target="_blank">네트워크 가상 어플라</a> 이언스)가 구현되는 연결의 중심 지점입니다.</p>


  <p>Azure의 SAP 프로젝트 내에서 검사 디바이스 및 NSG 보안 규칙이 원하는 대로 작동하는지 확인하는 것이 좋습니다. 이렇게 하면 SAP 리소스가 네트워크 취약성으로부터 적절하게 보호됩니다.</p>


  <h3>암호화 방법을 통해 데이터 무결성 유지 관리</h3>


  <p><a href="https://docs.microsoft.com/en-us/azure/storage/common/storage-service-encryption" target="_blank">Azure Storage 서비스 암호화</a>는 사용하지 않도록 설정할 수 없는 Azure Storage 계정에서 기본적으로 사용하도록 설정됩니다. 따라서 Azure Storage 미사용 고객 데이터는 기본적으로 256비트 AES를 사용하여 데이터를 암호화/암호 해독하는 보안이 유지됩니다. 암호화/암호 해독 프로세스는 Azure Storage 성능에 영향을 주지 않으며 비용 부담이 없습니다.&nbsp; 암호화 키를 관리하는 Microsoft 옵션이 있거나 <a href="https://docs.microsoft.com/en-gb/azure/key-vault/key-vault-overview" target="_blank">Azure Key Vault</a>를 사용하여 사용자 고유의 키를 관리할 수 있습니다. Azure Key Vault를 사용하여 SAP 시스템 내에서 인터페이스 및 내부 통신을 보호하는 데 사용되는 SSL/TLS 인증서를 관리할 수 있습니다.</p>


  <p>또한 Azure는 Windows BitLocker를 사용하여 가상 머신 <a href="https://docs.microsoft.com/en-us/azure/security/fundamentals/azure-disk-encryption-vms-vmss" target="_blank">디스크 암호화</a>를 제공하고 Linux용 DM-Crypt 가상 머신 운영 체제 및 데이터 디스크에 대한 볼륨 암호화를 제공합니다.&nbsp;</p>


  <p>미사용 SAP 데이터를 암호화하는 권장 방법은 다음과 같습니다.</p>


  <ul>
      <li>SAP 데이터베이스 서버 - DBMS 공급자가 제공하는 네이티브 암호화 기술을 활용하여 데이터 및 로그 파일을 보호하고 백업도 암호화되도록 합니다.</li>
      <li>Linux 가상 머신 디스크를 암호화하려면 <a href="https://docs.microsoft.com/en-us/azure/virtual-machines/disk-encryption-overview" target="_blank">디스크 암호화 개요</a>에 설명된 대로 다양한 옵션이 있습니다.&nbsp;</li>
      <li>특정 Linux 배포판/버전/이미지에서 Azure Disk Encryption을 지원하려면 <a href="https://docs.microsoft.com/en-us/azure/virtual-machines/linux/disk-encryption-overview" target="_blank">Linux VM용 Azure Disk Encryption</a> 문서를 확인하세요.</li>
  </ul>


  <h3>운영 체제 강화</h3>


  <p>보안은 고객별 보안 컨트롤을 운영 체제, 데이터베이스 및 SAP 애플리케이션 계층에 적용해야 하는 고객으로서 Microsoft와 사용자 간의 공동 책임입니다. 예를 들어 SAP 데이터베이스에 대한 공격으로 이어질 수 있는 취약성을 근절하기 위해 운영 체제가 강화되었는지 확인해야 합니다.</p>


  <p>Windows, SUSE Linux, RedHat Linux 등은 Azure에서 SAP 애플리케이션을 실행하는 데 지원되며 이러한 운영 체제의 다양한 이미지를 Azure Marketplace 내에서 사용할 수 있습니다. 엔터프라이즈의 보안 정책을 준수하고 <a href="https://docs.microsoft.com/en-us/azure/security/azure-security-disk-encryption-overview" target="_blank">CIS(인터넷 보안 센터) Microsoft Azure 기초 벤치마크의</a> 지침 내에서 이러한 이미지를 더욱 강화할 수 있습니다.</p>


  <p>기업은 일반적으로 운영 체제를 포함하여 IT 소프트웨어를 업데이트하고 패치하기 위한 운영 프로세스를 갖추고 있습니다. 운영 체제 취약성이 노출되면 보안 권고에 게시되고 일반적으로 신속하게 수정됩니다. 운영 체제 공급업체는 정기적으로 보안 업데이트 및 패치를 제공합니다. Azure Automation의 <a href="https://docs.microsoft.com/en-us/azure/automation/automation-update-management" target="_blank">업데이트 관리 솔루션을</a> 사용하여 Azure에서 Windows 및 Linux VM에 대한 운영 체제 업데이트를 관리할 수 있습니다. 모범 사례 방법은 정기적인 주기로 운영 체제에 대한 보안 업데이트를 선택적으로 설치하고 유지 관리 기간 동안 새 기능과 같은 다른 업데이트를 설치하는 것입니다.</p>


  <h2>자세한 정보</h2>


  <p>이 블로그에서는 Azure에 SAP를 배포하는 것과 관련된 다양한 보안 항목에 대해 알아봅니다. 견고한 보안 사례를 통합하면 Azure에서 보안 SAP 배포가 수행됩니다.</p>


  <p><a href="https://azure.microsoft.com/en-us/services/security-center/" target="_blank">Azure Security Center는 Azure</a> 배포를 보호 및 모니터링하기 위한 모범 사례에 대해 알아볼 수 있는 곳입니다. 또한 <a href="https://azure.microsoft.com/en-us/services/azure-sentinel/" target="_blank">Azure Sentinel</a>과 함께 <a href="https://docs.microsoft.com/en-us/azure/security-center/security-center-intro" target="_blank">Azure Security Center 기술 설명서를</a> 읽어 취약성을 감지하고, 악용이 발생했을 때 경고를 생성하고, <a href="https://docs.microsoft.com/en-us/azure/security-center/security-center-recommendations" target="_blank">수정</a>에 대한 지침을 제공하는 방법을 이해하세요.</p>


  <p>이 시리즈의 블로그 2번에서는 성능 및 확장성을 위한 디자인을 다룹니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/4f60791e-7113-4e08-868f-1c4a3a734b2c.png"><img alt="An image of the Security Center Overview page." border="0" height="536" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/7be3fbfc-f9ec-460a-818d-ce587feaba4e.png" style="border: 0px currentcolor; margin-right: auto; margin-left: auto; display: block; background-image: none;" title="Security Center 개요 페이지의 이미지입니다." width="1024"></a></p>
