### YamlMime:Yaml
ms.openlocfilehash: a21bcffa497e1c091c7b467882bef3f68f28175e
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139900897"
Slug: scale-your-critical-applications-cost-effectively-with-azure-disk-storage
Title: Azure Disk Storage 사용하여 중요한 애플리케이션을 비용 효율적으로 확장
Summary: '비즈니스 연속성 보장 및 감소된 현금 흐름 관리와 같은 오늘날의 과제를 해결하기 위해 조직은 클라우드로의 마이그레이션을 가속화하고 있습니다. 광범위한 워크로드가 클라우드로 마이그레이션되므로 비용을 제어하면서 이러한 워크로드의 고유한 규모 요구를 충족하는 것이 중요합니다. '
Content: >-
  <p>비즈니스 연속성 보장 및 감소된 현금 흐름 관리와 같은 오늘날의&rsquo; 과제를 해결하기 위해 조직은 클라우드로의 마이그레이션을 가속화하고 있습니다. 광범위한 워크로드가 클라우드로 마이그레이션되므로 비용을 제어하면서 이러한 워크로드의 고유한 규모 요구를 충족하는 것이 중요합니다. 현재 <a href="https://azure.microsoft.com/en-us/services/storage/disks/" target="_blank">Azure Disk Storage</a> 새로운 기능을 공유하고 있으며, 이를 통해 비용 효율적으로&mdash; 성능을 확장하여 주문형 워크로드 요구 사항을 충족하고 필요한 비용만 지불할 수 있습니다.</p>


  <h2>Premium SSD에서 새 디스크 버스팅 환경을 사용하여 주문형 디스크 성능 향상</h2>


  <p>2020년 4월에는 <a href="https://azure.microsoft.com/en-us/blog/general-availability-of-new-azure-disk-sizes-and-bursting/#:~:text=Azure%20Premium%20SSD%20Managed%20Disks%20%20%20Burst,%2032%20GiB%20%204%20more%20rows%20" target="_blank">더 작은 프리미엄 SSD 디스크 크기(512GiB 이하)에서 디스크 버스팅의 일반 공급이 발표되었습니다.</a> 현재 새로운 주문형 환경을 통해 디스크 버스팅 지원(미리 보기)을 더 큰 프리미엄 SSD 디스크 크기(512GiB 이상)로 확장하고 있습니다. 크레딧을 누적한 경우에만 버스트할 수 있는 크레딧 기반 시스템과 달리, 새로운 주문형 버스팅 기능을 사용하면 필요할 때마다 프로비전된 금액의 최대 6회(최대 30,000 IOPS 및 1,000MB의 처리량)를 버스트할 수 있습니다. 이를 통해 수요를 충족하고 비용을 최적화할 수 있도록 성능을 유연하게 확장할 수 있습니다.</p>


  <p>디스크 버스팅은 예기치 않은 수요 급증에도 성능 저하를 허용할 수 없는 중요 업무용 워크로드에 가장 적합합니다. OLTP(온라인 트랜잭션 처리) 시스템을 호스팅하는 경우 수요 증가로 인해 주문 요청이 급격히 급증할 수 있습니다. 스토리지 시스템이 백 엔드 데이터베이스에 대한 증가된 부하를 처리하여 고객에게 일관된 환경을 제공할 수 있는지 확인하려고 합니다.</p>


  <p>지원되는 Premium SSD 디스크에서 사용하도록 설정하여 이 새로운 주문형 버스팅 기능을 쉽게 활용할 수 있습니다. 버스트 사용 요금이 있으며 프로비전된 대상에 대한 추가 트랜잭션은 별도로 청구됩니다. 미리 보기 범위, 사용 단계 및 가격 책정 모델에 대해 <a href="https://aka.ms/diskburstingP30" target="_blank">자세히 알아봅니</a>다.</p>


  <p>기존 크레딧 기반 버스팅을 이미 채택한 경우 최근에 새로운 디스크 버스팅 메트릭을 도입했습니다. 이러한 메트릭은 누적 버스트 크레딧에 대한 가시성을 제공하고 버스트 기능을 더 잘 예측하는 데 도움이 됩니다. 기준 및 버스트 성능 목표와 사용되지 않는 버스트 크레딧을 쉽게 볼 수 있습니다. 새 디스크 메트릭을 사용하여 디스크 버스팅을 모니터링하는 방법에 대해 <a href="https://docs.microsoft.com/en-us/azure/virtual-machines/disks-metrics" target="_blank">자세히 알아봅니</a>다.</p>


  <h2>프리미엄 SSD에 대한 성능 계층을 사용하여 지속적으로 더 높은 성능 달성</h2>


  <p>계절별 판매 프로모션 또는 교육 환경 실행과 같은 계획된 이벤트의 경우 몇 시간 또는 며칠 동안 지속적으로 더 높은 성능을 달성한 다음 정상 성능 수준으로 돌아가야 합니다. 프리미엄 SSD의 <a href="https://docs.microsoft.com/en-us/azure/virtual-machines/disks-change-performance?toc=/azure/virtual-machines/linux/toc.json&amp;bc=/azure/virtual-machines/linux/breadcrumb/toc.json" target="_blank">성능 계층</a> (11월에 <a href="https://azure.microsoft.com/en-us/updates/performance-tiers-for-premium-ssds-is-now-generally-available/" target="_blank">발표된</a> 일반 공급)을 사용하면 더 높은 성능 계층을 선택하여 디스크 크기를 늘리지 않고도 디스크 성능을 유연하게 확장할 수 있습니다. 언제든지 계층을 변경하거나 기준 성능 계층으로 다시 가져와서 더 높은 성능과 비용 절감을 달성할 수 있습니다.</p>


  <p>기준 성능 계층은 프로비전된 디스크 크기에 따라 설정됩니다. 크기를 늘리지 않고 더 높은 수요를 충족하기 위해 애플리케이션에 필요한 경우 더 높은 성능 계층을 설정할 수 있습니다. 예를 들어 P10 디스크(128GiB)를 프로비전하는 경우 기준 성능 계층은 P10(500 IOPS 및 100MB)으로 설정됩니다. P50(7500 IOPS 및 250MB)의 성능과 일치하도록 계층을 업데이트하고 더 높은 성능이 더 이상 필요하지 않은 경우 P10으로 돌아갈 수 있습니다. 디스크 성능 계층을 변경하는 방법에 대해 <a href="https://docs.microsoft.com/en-us/azure/virtual-machines/disks-performance-tiers-portal?toc=/azure/virtual-machines/linux/toc.json&amp;bc=/azure/virtual-machines/linux/breadcrumb/toc.json" target="_blank">자세히 알아봅니</a>다.</p>


  <h2>워크로드에 대해 동적으로 성능을 조정하는 최적의 옵션 선택</h2>


  <p>성능 계층 및 주문형 디스크 버스팅을 사용하면 이제 디스크 성능을 스케일링하는 두 가지 옵션이 제공됩니다. 워크로드에 가장 적합한 옵션을 평가할 때 다음 조건을 고려하는 것이 좋습니다.</p>


  <ul>
      <li><strong>계획된 성능과 계획되지 않은 성능 크기 조정:</strong>&nbsp; 디스크 성능이 지속적으로 향상되어야 하는 계획된 이벤트(예: 연말연시)가 있는 경우 성능 계층이 더 적합한 옵션입니다. 증가된 부하를 더 잘 수용하고 언제든지 원래 계층으로 다시 가져오기 위해 디스크 계층을 더 높은 성능 계층으로 설정할 수 있습니다. 그러나 미리 계획하거나 워크로드의 성능 패턴을 정확하게 예측할 수 없는 경우 프로비전된 대상을 초과하는 더 높은 허용량을 제공하므로 디스크 버스팅이 더 나은 선택입니다.</li>
      <li><strong>기간:&nbsp;</strong> 성능 수요 기간에 따라 두 옵션의 비용 효율성이 다를 수 있습니다. IO 예약의 짧은 실행 작업 또는 지터로 인해 수요가 많은 시나리오의 경우 버스트 트랜잭션에 대해서만 비용을 지불하므로 주문형 디스크 버스팅이 비용 효율적입니다. 워크로드가 프로비전된 대상을 초과하지 않는 경우 디스크 비용의 극히 일부인 버스트 사용 요금만 지불합니다. 반면, 워크로드가 며칠 이상 버스트될 것으로 예상되는 경우 성능 계층이 더 나은 옵션입니다. 예를 들어 세금 보고 솔루션을 호스트하는 경우 보고 시즌의 마지막 달 동안 크게 증가할 것으로 예상&nbsp;할 수 있습니다. 더 높은 성능 계층을 선택하여 성능을 스케일링하는 것이 이 상황에서 더 비용 효율적입니다.</li>
  </ul>


  <p>워크로드&rsquo; 요구 사항에 가장 적합한 옵션을 평가하려면 <a href="https://azure.microsoft.com/en-us/pricing/calculator/" target="_blank">Azure 가격 계산기를</a> 참조하는 것이 좋습니다.</p>


  <h2>시작</h2>


  <p>새로운 성능 크기 조정 기능을 시작하려면 <a href="https://aka.ms/diskburstingP30" target="_blank">주문형 디스크 버스팅</a> 및 <a href="https://docs.microsoft.com/en-us/azure/virtual-machines/disks-change-performance" target="_blank">성능 계층</a>에 대한 지침을 참조하세요. 또한 Azure Disk Storage <a href="https://docs.microsoft.com/en-us/azure/virtual-machines/disks-shared?toc=/azure/virtual-machines/linux/toc.json&amp;bc=/azure/virtual-machines/linux/breadcrumb/toc.json" target="_blank">공유 디스크</a>와 같은 다른 고유한 기능&mdash;, <a href="https://docs.microsoft.com/en-us/azure/virtual-machines/disks-enable-ultra-ssd?toc=%2Fazure%2Fvirtual-machines%2Flinux%2Ftoc.json&amp;bc=%2Fazure%2Fvirtual-machines%2Flinux%2Fbreadcrumb%2Ftoc.json&amp;tabs=azure-portal" target="_blank">Azure 울트라 디스크의 동적 크기 조정</a> 및 <a href="https://docs.microsoft.com/en-us/azure/virtual-machines/disk-bursting?toc=/azure/virtual-machines/linux/toc.json&amp;bc=/azure/virtual-machines/linux/breadcrumb/toc.json" target="_blank">더 작은 프리미엄 SSD 디스크 크기</a>&mdash; 조정을 통해 비즈니스에 중요한 애플리케이션을 비용 효율적으로 확장하고 실행할 수 있습니다.</p>


  <p>모든 디스크 작업에 대한 자세한 지침은 <a href="https://aka.ms/azuredisksdocs" target="_blank">Azure Disk Storage</a> 설명서를 참조하세요. AzureDisks@microsoft.com 의견을 공유하거나 <a href="https://feedback.azure.com/forums/217298-storage" target="_blank">Azure Storage 피드백 포럼</a>에 의견을 남겨 주시기 바랍니다.</p>
