### YamlMime:Yaml
ms.openlocfilehash: bf5b56d93e5edcd1e18a53990d6dfdea8664d0fd
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139900859"
Slug: seamlessly-migrate-your-application-from-aws-to-azure-in-4-simple-steps
Title: 네 가지 간단한 단계로 AWS에서 Azure로 애플리케이션 원활하게 마이그레이션
Summary: 네 가지 간단한 단계로 Amazon 웹 서비스에서 Azure로 애플리케이션을 원활하게 마이그레이션하는 방법을 알아봅니다.
Content: >-
  <p>Microsoft는 IaaS(Infrastructure-as-a-Service), PaaS(Platform-as-a-Service), 온-프레미스 데이터 센터 및 Windows 및 Linux를 모두 지원하는 하이브리드 환경을 아우르는 포괄적인 통합 솔루션 집합을 제공합니다. Azure Site Recovery의 강력한 마이그레이션 기능으로 이 플랫폼을 활용하는 것이 더 쉬워졌습니다.</p>


  <p>Azure는 현재 <a href="https://aka.ms/aws-vs-azure-campaign">온-프레미스 데이터 센터를 클라우드에 원활하게 연결하는 유일한 퍼블릭 클라우드</a>입니다. Azures&rsquo;의 강력한 기능, 일류 서비스 및 통합 도구는 새로운 수준의 규모와 탄력성을 달성하는 데 도움이 됩니다. Azure에는 가파른 학습 곡선이 없으므로 이미 알고 있는 것을 사용하기만 하면 조직이 첫날부터 생산성을 높일 수 있습니다. 기존 온-프레미스 자산과 Azure의 강력한 기능 간에 원활한 통합을 통해 진정한 하이브리드 클라우드 플랫폼을 달성하고 싶지만 AWS와 같은 다른 퍼블릭 클라우드에 갇혀 있다고 느끼려면 최근에 <a href="https://aka.ms/expanding_hybrid_cloud">발표된 마이그레이션 기능을</a> <a href="https://aka.ms/azure_site_recovery">&#39;Azure Site Recovery</a>를 활용하세요. Site Recovery는 Microsoft OMS( <a href="https://aka.ms/operations_management_suite">Operations Management Suite</a> )의 일부로도 사용할 수 있으며 <a href="https://aka.ms/azure_site_recovery_pricing">처음 31일 동안 마이그레이션을 체험하거나 활용할</a> 수 있습니다.</p>


  <p>다음 비디오에서는 AWS에서 Azure로 몇 시간 만에 간단한 애플리케이션을 마이그레이션하는 방법을 보여 줍니다.<br />

  &nbsp;</p>


  <p><iframe allowfullscreen="" frameborder="0" height="315" src="https://www.youtube.com/embed/Bn8o6KfvshY" width="560"></iframe></p>


  <p><br />

  videoillustrates&nbsp;는&nbsp; AWS에서 Azure로 애플리케이션을 마이그레이션하는 데 필요한 간단한 단계를 설명합니다. 핵심 원리는 다음과 같습니다.</p>


  <ol>
      <li>
      <h3>Azure 리소스 준비</h3>
  애플리케이션을 Azure로 마이그레이션할 준비를 하려면 Azure에서 인프라 구성 요소를 설정해야 합니다. &rsquo;모든 ASR 환경의 시작점이 되므로 Site Recovery 자격 증명 모음으로 시작합니다. 빠른 시작 마법사의&nbsp; 도입에 따라 Azure에 두 개의 IaaS VM viz., 구성 서버 및 마스터 대상 서버를 배포합니다. 온-프레미스 물리적 서버와 Azure 간에 보호를 설정하는 방법에 대한 지침에 따라 이러한 구성 요소를 Azure에 배포할 수 있습니다.</li>
      <li>
      <h3>AWS 리소스 준비</h3>
  프로세스 서버 구성 요소를 실행하는 EC2 인스턴스를 배포해야 합니다. 프로세스 서버를 배포할 때 프로세스 서버의 크기 조정에 대한 지침을 염두에 두어야 합니다. 프로세스 서버는 AWS에서 애플리케이션을 실행하는 VM에 액세스해야 하므로 프로세스 서버가&nbsp;&rsquo; 마이그레이션 중인 VM과 동일한 서브넷에 있는 것이 좋습니다. 마이그레이션하는 VM에는 TCP 및 UDP 포트 135-139, 445 및 1024-65535에서 인바운드 연결을 허용하는 보안 그룹 구성이 있어야 프로세스 서버와 통신할 수 있습니다. &rsquo;이 단계를 완료하고 구성 서버에 프로세스 서버를 등록하면 다음 단계로 이동할 준비가 된 것입니다.</li>
      <li>
      <h3>Azure에서 AWS VM 검색 및 &ldquo;보호&rdquo;</h3>
  이 시점에서 AWS에서 VM 검색을 시작할 수 있습니다. 먼저 보호 그룹을 만들고 물리적 머신&rdquo; 추가 워크플로를 사용하여 &ldquo;Azure로 마이그레이션하려는 모든 EC2 인스턴스를 식별합니다. EC2 인스턴스의 개인 IP 주소를 사용하여 검색할 수 있으며 나중에 참조할 수 있는 친숙한 이름을 사용할 수도 있습니다. 이 단계가 완료되면 이전 단계에서 식별한 모든 VM이 Azure에 복제되기 시작합니다. 가상 머신의 크기, 네트워크 용량 및 프로세스 서버의 크기에 따라 장기 실행 작업이 될 수 있습니다. 이 초기 복제가 성공하면 마이그레이션할 준비가 된 것입니다.</li>
      <li>
      <h3>한 번의 클릭으로 애플리케이션을 마이그레이션합니다!</h3>
  이 시점에서 한 번의 클릭으로 장애 조치(failover) 작업을 수행하고 애플리케이션을 Azure로 마이그레이션합니다. 이러한 리소스가 더 이상 필요하지 않으므로 EC2 인스턴스를 삭제하고 ASR에서 보호를 사용하지 않도록 설정해야 합니다.</li>

  </ol>


  <p>이제 애플리케이션을 마이그레이션하는 것이 얼마나 쉬운지 알아보았을&#39;, 직접 시도하고 Azure인 진정한 하이브리드 하이퍼스케일 퍼블릭 클라우드를 활용하세요. <a href="https://aka.ms/azure_site_recovery">Azure Site Recovery</a>를 시작하는 것은 쉽고 앞에서 설명한 대로 처음 31일 동안<a href="https://aka.ms/azure_site_recovery_pricing">의 마이그레이션에 대한 무료&nbsp; 토레버지</a>입니다. <span itemprop="headline"><a href="https://aka.ms/aws_to_azure_migration_documentation">AWS(Amazon Web Services)에서 Azure로 Windows 가상 머신 마이그레이션에 대한 Azure</a> 설명서를 통해 이 간단한 프로세스를 안내할 수 있습니다.</span></p>
