### YamlMime:Yaml
ms.openlocfilehash: 7637afbce72eedb0c15c81152ed8669d7bb31d33
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139900763"
Slug: september-update-web-apps-and-app-service-environments
Title: Web Apps 및 App Service Environment에 대한 9월 업데이트
Summary: '이 블로그 게시물은 약간 기한이 지났지만 제공된 기능 및 개선 사항을 만회하고 있습니다. '
Content: >-
  <p>이 블로그 게시물은 약간 기한이 지났지만 제공된 기능 및 개선 사항으로 이를 만회하고 있습니다.</p>


  <h2>.Net Framework 4.6 지원</h2>


  <p>이제 .Net Framework 4.6을 사용하도록 앱을 구성할 수 있습니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/71008f04-2cac-4212-a8c8-7595c06faea8.png"><img alt="image" border="0" height="576" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/06907213-39b2-4975-8c26-97065b7750b8.png" style="border-left-width: 0px; border-right-width: 0px; background-image: none; border-bottom-width: 0px; padding-top: 0px; padding-left: 0px; display: inline; padding-right: 0px; border-top-width: 0px" title="이미지" width="1024"></a></p>


  <h2>Process Explorer</h2>


  <p><strong>프로세스 탐색기는</strong> 웹 사이트 프로세스, 사이트 확장, 웹 작업 및 kudu 프로세스를 보다 쉽게 구분할 수 있도록 프로세스 아이콘을 포함하는 몇 가지 안정성 수정 사항과 페이스리프트를 얻었습니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/56623a2d-742c-40d9-8d40-6cdd19bb1fca.png"><img alt="clip_image002" border="0" height="576" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/04a9a342-c574-4d77-8bbe-2e55f969c15b.png" style="border-left-width: 0px; border-right-width: 0px; background-image: none; border-bottom-width: 0px; padding-top: 0px; padding-left: 0px; display: inline; padding-right: 0px; border-top-width: 0px" title="clip_image002" width="1024"></a></p>


  <h2>인증/권한 부여</h2>


  <p>큰 디렉터리를 더 잘 처리할 수 있도록 몇 가지 개선 사항이 적용되어 UI의 응답성이 훨씬 향상되었습니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/26922c2b-f5b3-4590-bdb1-c2d188ccd07a.png"><img alt="clip_image003" border="0" height="576" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/e0abf0e5-c8ae-49aa-9bd7-13da0dc7ee1e.png" style="border-left-width: 0px; border-right-width: 0px; background-image: none; border-bottom-width: 0px; padding-top: 0px; padding-left: 0px; display: inline; padding-right: 0px; border-top-width: 0px" title="clip_image003" width="1024"></a></p>


  <h2>새 CI 공급자: OneDrive</h2>


  <p>이제 연속 배포를 위해 OneDrive 폴더를 설정할 수 있습니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/601f1c80-30ac-4b4c-a37c-5be6495d1e10.png"><img alt="clip_image004" border="0" height="576" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/eb926266-2de7-41ca-835f-b54ea6990de1.png" style="border-left-width: 0px; border-right-width: 0px; background-image: none; border-bottom-width: 0px; padding-top: 0px; padding-left: 0px; display: inline; padding-right: 0px; border-top-width: 0px" title="clip_image004" width="1024"></a></p>


  <h2>App Service 계획 필수 사항</h2>


  <p>App <strong>Service 계획</strong> 필수 기능은 이제 웹/모바일 및 슬롯에서 앱 수를 제공합니다. <strong>찾아보기</strong> 에서는 통합 목록의 모든 형식도 포함합니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/e5eba08e-b568-4692-8a79-cf1618e312d0.png"><img alt="clip_image005" border="0" height="576" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/0461eb50-3e3d-48b2-bd94-0e23e181d77c.png" style="border-left-width: 0px; border-right-width: 0px; background-image: none; border-bottom-width: 0px; padding-top: 0px; padding-left: 0px; display: inline; padding-right: 0px; border-top-width: 0px" title="clip_image005" width="1024"></a></p>


  <h2>도구 메뉴</h2>


  <p>도구 메뉴에 <strong>이벤트</strong> 및 <strong>경고를</strong> 포함했습니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/86d5975f-a8b5-4e17-a4ad-99a36ef0d925.png"><img alt="clip_image006" border="0" height="576" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/4d67ba69-cdd0-49e7-a7b6-9f0a0d9d7339.png" style="border-left-width: 0px; border-right-width: 0px; background-image: none; border-bottom-width: 0px; padding-top: 0px; padding-left: 0px; display: inline; padding-right: 0px; border-top-width: 0px" title="clip_image006" width="1024"></a></p>


  <h2>App Service Environment 업데이트</h2>


  <h3>새 ASE 만들기 환경</h3>


  <p>웹앱 만들기 환경의 다시 vamp에서 모든 학습을 가져와<strong> App Service Environment</strong> 생성에 적용했습니다. 결과적으로 훨씬 더 간소화된 환경이 생성되어 모든 &ldquo;잠금이&rdquo; 제거되고 최소한의 입력이 요구됩니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/b9097714-33bd-422a-8050-a75060224a01.png"><img alt="clip_image007" border="0" height="576" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/85e86598-0cd4-499d-a7ae-2b913809f4ca.png" style="border-left-width: 0px; border-right-width: 0px; background-image: none; border-bottom-width: 0px; padding-top: 0px; padding-left: 0px; display: inline; padding-right: 0px; border-top-width: 0px" title="clip_image007" width="1024"></a></p>


  <h3>ASE 자동 크기 조정 지원</h3>


  <p>이제 App Service Environment Worker 풀 및 프런트 엔드에서 메트릭 및 일정 기반 자동 크기 조정을 수행할 수 있습니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/eca91eaa-c173-42b8-b895-efbb571a72f0.png"><img alt="clip_image008" border="0" height="576" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/a1921360-2f93-47b6-a24a-1f893a5735f2.png" style="border-left-width: 0px; border-right-width: 0px; background-image: none; border-bottom-width: 0px; padding-top: 0px; padding-left: 0px; display: inline; padding-right: 0px; border-top-width: 0px" title="clip_image008" width="1024"></a></p>


  <h3>작업자 풀 및 프런트 엔드에 대한 전체 리소스 블레이드</h3>


  <p>이제 프런트 엔드 및 작업자 풀을 개별 리소스로 관리할 수 있습니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/92a2f1f2-b402-4b5b-a3dc-37415cd59e18.png"><img alt="clip_image009" border="0" height="576" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/15b4cc58-2842-42ef-bb61-5bd291f4c996.png" style="border-left-width: 0px; border-right-width: 0px; background-image: none; border-bottom-width: 0px; padding-top: 0px; padding-left: 0px; display: inline; padding-right: 0px; border-top-width: 0px" title="clip_image009" width="1024"></a></p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/d0052f38-04f1-41ee-aadd-4505a89cda5a.png"><img alt="clip_image010" border="0" height="576" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/2963ec8e-f16e-443e-be00-9487cf567469.png" style="border-left-width: 0px; border-right-width: 0px; background-image: none; border-bottom-width: 0px; padding-top: 0px; padding-left: 0px; display: inline; padding-right: 0px; border-top-width: 0px" title="clip_image010" width="1024"></a></p>


  <h3>IP 주소 관리 환경</h3>


  <p>새 <strong>App Service Environment</strong> IP 관리 환경으로, IP 주소의 크기를 조정하고 <strong>App Service Environment</strong>에서 호스트되는 앱에서 사용할 수 있습니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/c1ba1f3b-7698-4f49-b4c1-8dd94876c9d8.png"><img alt="clip_image011" border="0" height="576" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/b9a016cf-5341-4a61-987c-05a5e6c2ece3.png" style="border-left-width: 0px; border-right-width: 0px; background-image: none; border-bottom-width: 0px; padding-top: 0px; padding-left: 0px; display: inline; padding-right: 0px; border-top-width: 0px" title="clip_image011" width="1024"></a></p>


  <h3>모든 App Service Environment 리소스 종류에 대한 경고 지원</h3>


  <p>이제 <strong>App Service Environment</strong>, 작업자 풀 및 프런트 엔드에서 메트릭 기반 경고를 설정하여 이메일 알림을 받거나 새 웹 후크 기능을 트리거할 수 있습니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/9adeff62-6e21-4666-9689-1e729719f0f6.png"><img alt="clip_image012" border="0" height="576" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/38de8a3c-96ae-4dfb-b110-685aa5a4ae65.png" style="border-left-width: 0px; border-right-width: 0px; background-image: none; border-bottom-width: 0px; padding-top: 0px; padding-left: 0px; display: inline; padding-right: 0px; border-top-width: 0px" title="clip_image012" width="1024"></a></p>


  <h2>ClearDB 클러스터 지원</h2>


  <p>또한 ClearDB에 대한 새로운 Hi-Performance MySQL SKU를 제공했습니다. 여기에는 중요 업무용 데이터베이스에 대한 지원과 웹앱 만들기 환경 다시 vamp의 학습에 기반한 구체화된 만들기 환경이 포함됩니다.</p>


  <p><a href="https://azure.microsoft.com/en-us/blog/announcing-new-mysql-premium-tiers-from-cleardb/">여기에서</a> ClearDB MySQL Premium 계층 공지 사항을 읽어보세요.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/2ded2993-009d-41bb-855d-4f9cab44b3be.png"><img alt="clip_image001[5]" border="0" height="576" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/5faf1032-793f-4c95-8108-4cd7232b6145.png" style="border-left-width: 0px; border-right-width: 0px; background-image: none; border-bottom-width: 0px; padding-top: 0px; padding-left: 0px; display: inline; padding-right: 0px; border-top-width: 0px" title="clip_image001[5]" width="1024"></a></p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/9f7c0dc5-0d85-4e21-9323-a31b5d68aaf5.png"><img alt="image" border="0" height="576" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/6e4e71cd-e3e6-4578-8514-67442e3eebcf.png" style="border-left-width: 0px; border-right-width: 0px; background-image: none; border-bottom-width: 0px; padding-top: 0px; padding-left: 0px; display: inline; padding-right: 0px; border-top-width: 0px" title="이미지" width="1024"></a></p>


  <p>&nbsp;</p>


  <h4>아래의 의견 섹션이나 <a href="https://feedback.azure.com/forums/169385-web-apps-formerly-websites" target="_blank">사용자 의견</a> 사이트를 통해 귀하의 생각, 질문 및 아이디어를 알려주세요.</h4>
