### YamlMime:Yaml
ms.openlocfilehash: 9366e0e88d9404c8a1a89805e0956b1b245f397b
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139900701"
Slug: sharepoint-server-2013-dev-test-environments
Title: SharePoint Server 2013 개발/테스트 환경
Summary: SharePoint Server 2013 개발/테스트 또는 개념 증명 환경을 신속하게 빌드합니다.
Content: >-
  SharePoint Server 2013 개발/테스트 또는 개념 증명 환경이 필요한가요? 다음 네 가지 옵션을 확인하세요.

  <ul>
   <li>인터넷 연결 팜에 대한 기본 구성(3개 서버)</li>
   <li>인터넷 연결 팜에 대한 고가용성 구성(9개 서버)</li>
   <li>인트라넷 팜(5개 서버)을 에뮬레이트하는 3계층 구성 SharePoint</li>
   <li>하이브리드 클라우드에서 인트라넷 팜 SharePoint(6개 서버)</li>
  </ul>

  <h2>인터넷 연결 팜에 대한 기본 구성</h2>

  기본 인터넷 연결 팜은 다음과 같습니다.


  <a href="https://acom.azurecomcdn.net/80C57D/blogmedia/blogmedia/2015/06/08/TCP80.jpg"><img style="background-image: none; padding-top: 0px; padding-left: 0px; display: inline; padding-right: 0px; border: 0px;" title="TCP80" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/TCP80_thumb.jpg" alt="TCP80" width="698" height="406" border="0" /></a>


  &nbsp;


  클라우드 전용 Azure 가상 네트워크를 사용하여 인터넷 연결 테스트 팜으로 이 구성을 사용합니다. 이 팜은 사이트-사이트 VPN 연결을 통해 조직 네트워크에 다시 연결되지 않습니다.


  다음 두 가지 방법으로 배포할 수 있습니다.

  <ul>
   <li>Azure Resource Manager 배포의 경우 <a href="https://azure.microsoft.com/documentation/templates/sharepoint-three-vm/">3개 VM 만들기 SharePoint Deployment</a> Resource Manager 템플릿을 사용합니다.</li>
   <li>Azure 서비스 관리 배포의 경우 Azure <a href="https://azure.microsoft.com/en-us/documentation/articles/virtual-machines-sharepoint-farm-azure-preview/">Preview 포털에서 SharePoint Server 팜을</a> 사용합니다.</li>
  </ul>

  두 경우 모두 구성 설정을 거의 지정하지 않으며 템플릿 또는 미리 보기 포털에서 컴퓨터 및 팜 구성을 수행할 수 있습니다.


  새 Azure Resource Manager에 대한 자세한 내용은 Azure Resource Manager<a href="https://azure.microsoft.com/en-us/documentation/articles/virtual-machines-azurerm-versus-azuresm/">에서 Azure Compute, 네트워크 &amp; Storage 공급자를</a> 참조하세요.

  <h2>인터넷 연결 팜에 대한 고가용성 구성</h2>

  고가용성 인터넷 연결 팜은 다음과 같습니다.


  <a href="https://acom.azurecomcdn.net/80C57D/blogmedia/blogmedia/2015/06/08/Web1.jpg"><img style="background-image: none; padding-top: 0px; padding-left: 0px; display: inline; padding-right: 0px; border: 0px;" title="Web1" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/Web1_thumb.jpg" alt="Web1" width="1029" height="500" border="0" /></a>


  &nbsp;


  위의 기본 구성과 마찬가지로 이 구성은 클라우드 전용 Azure 가상 네트워크를 사용하는 인터넷 연결 테스트 팜용입니다. 이 팜은 사이트-사이트 VPN 연결을 통해 조직 네트워크에 다시 연결되지 않습니다.

  <ul>
   <li>Azure Resource Manager 배포의 경우 <a href="https://azure.microsoft.com/documentation/templates/sharepoint-server-farm-ha/">새 HA SharePoint 팜</a> Resource Manager 템플릿 만들기를 사용합니다.</li>
   <li>Azure 서비스 관리 배포의 경우 Azure <a href="https://azure.microsoft.com/en-us/documentation/articles/virtual-machines-sharepoint-farm-azure-preview/">Preview 포털에서 SharePoint Server 팜을</a> 사용합니다.</li>
  </ul>

  이러한 방법을 사용하면 많은 구성 시간을 절약할 수 있지만 9개의 서버와 19개의 코어를 지원하는 Azure 구독이 필요합니다.

  <h2>인트라넷 팜을 에뮬레이트하는 3계층 구성 SharePoint</h2>

  Azure TLG(테스트 랩 가이드)<a href="https://download.microsoft.com/download/B/C/C/BCCE7D96-65AA-48E6-9549-02A3768D0ED4/AzureSP2013ThreeTierFarm.docx">의 SharePoint 3계층 팜</a>을 사용하면 클라이언트 컴퓨터가 포함된 간단한 3계층 팜을 빌드할 수 있습니다. 온-프레미스 컴퓨터 또는 가상 머신을 사용하여 SharePoint 테스트 랩을 빌드하는 대신 Azure 기반의 대안입니다.


  <a href="https://acom.azurecomcdn.net/80C57D/blogmedia/blogmedia/2015/06/08/Cloud-Service.jpg"><img style="background-image: none; padding-top: 0px; padding-left: 0px; display: inline; padding-right: 0px; border: 0px;" title="클라우드 서비스" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/Cloud-Service_thumb.jpg" alt="Cloud Service" width="637" height="387" border="0" /></a>


  &nbsp;


  클라우드 전용 Azure 가상 네트워크를 사용하여 인트라넷 테스트 팜으로 이 구성을 사용합니다. 조직 인트라넷이 아닌 CLIENT1 컴퓨터를 기준으로 인트라넷 팜을 에뮬레이트합니다. 앞에서 설명한 SharePoint 서버 팜 구성과 달리 SharePoint 팜의 리소스에 대한 인터넷 액세스 권한은 없습니다.


  이 구성의 장점은 기존 SharePoint TLL 집합을 사용하여 권한, 인증, 프로필 동기화 및 소셜 네트워킹을 구성할 수 있다는 것입니다. 자세한 내용은 <a href="https://social.technet.microsoft.com/wiki/contents/articles/24064.sharepoint-server-2013-test-lab-in-azure.aspx">Azure의 SharePoint Server 2013 테스트 랩을 참조하세요</a>.

  <h2>하이브리드 클라우드의 SharePoint 인트라넷 팜</h2>

  <a href="https://azure.microsoft.com/en-us/documentation/articles/virtual-networks-setup-sharepoint-hybrid-cloud-testing/">하이브리드 클라우드에서 SharePoint 인트라넷 팜</a>을 사용하면 도메인 컨트롤러 및 클라이언트 컴퓨터가 포함된 간소화된 온-프레미스 조직 네트워크를 갖춘 간단한 2계층 팜을 빌드할 수 있습니다.


  <a href="https://acom.azurecomcdn.net/80C57D/blogmedia/blogmedia/2015/06/08/DC1.jpg"><img style="background-image: none; padding-top: 0px; padding-left: 0px; display: inline; padding-right: 0px; border: 0px;" title="DC1" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/DC1_thumb.jpg" alt="DC1" width="779" height="418" border="0" /></a>


  이 구성은 크로스-프레미스 Azure 가상 네트워크를 사용하여 인트라넷 테스트 팜으로 사용합니다. 간소화된 온-프레미스 네트워크의 CLIENT1 컴퓨터를 기준으로 인트라넷 팜을 에뮬레이트합니다. SharePoint 팜에는 인터넷에 액세스할 수 없습니다.


  이 구성의 장점은 사이트 간 VPN 연결을 포함하며 인터넷에서 사용자의 위치를 기준으로 에뮬레이트된 인트라넷 SharePoint 팜의 성능 및 관리를 경험할 수 있다는 점입니다.


  <a href="https://azure.microsoft.com/en-us/documentation/articles/virtual-networks-setup-simulated-hybrid-cloud-environment-testing/">시뮬레이션된 하이브리드 클라우드</a>를 사용하여 빌드할 수도 있습니다. 결과는 다음과 같습니다.


  <a href="https://acom.azurecomcdn.net/80C57D/blogmedia/blogmedia/2015/06/08/Hybrid.jpg"><img style="background-image: none; padding-top: 0px; padding-left: 0px; display: inline; padding-right: 0px; border: 0px;" title="하이브리드" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/Hybrid_thumb.jpg" alt="Hybrid" width="932" height="645" border="0" /></a>


  &nbsp;


  보고 싶은 다른 SharePoint Server 2013 개발/테스트 구성을 생각할 수 있는 경우 이 블로그 게시물 또는 위에 연결된 문서의 Disqus 주석에 댓글을 달 수 있습니다.


  감사합니다.
