### YamlMime:Yaml
ms.openlocfilehash: 4717ff2149a53ca74cc85624363ce1d1d211de44
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139900615"
Slug: simulated-hybrid-cloud-test-environment
Title: 새로운 시뮬레이션된 하이브리드 클라우드 테스트 환경 토픽
Summary: Azure 구독만 사용하면 간소화된 인트라넷과 다른 Azure 가상 네트워크에 대한 VNet 간 연결로 완성된 하이브리드 클라우드를 시뮬레이션할 수 있습니다.
Content: >-
  <p>실제 하이브리드 클라우드 테스트 환경을 설정하려면 역할에 따라 다음 두 가지가 필요합니다.</p>


  <ul>
   <li>시뮬레이션된 온-프레미스 네트워크의 컴퓨터를 호스트&nbsp;할 수 있는 예비 Hyper-V 서버</li>
   <li>여분의 공용 IP 주소</li>
  </ul>


  <p>따라서 이러한 항목(특히 공용 IP 주소)&nbsp;이 상대적으로 부족하기 때문에 <a href="https://azure.microsoft.com/documentation/articles/virtual-machines-windows-ps-hybrid-cloud-test-env-sim/">테스트를 위해 시뮬레이션된 하이브리드 클라우드 환경을 설정</a>하여 Azure 가상 네트워크에서 간소화&nbsp;된 온-프레미스 네트워크를&nbsp; 만들고&nbsp; 복제본 도메인 컨트롤러가 포함된 추가 Azure 가상 네트워크를 만든 다음 두 가상 네트워크를 VNet 간 연결에 연결할 수 있습니다&nbsp;. 결과 구성은 다음과 같습니다.</p>


  <p><img src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/240fe89b-25c1-42a8-bfd9-ee62c2b8a547.png"></p>


  <p>인터넷의 실제 위치에서 작동하는 것을 볼 수 있는 이점을 얻을&#39;없습니다. 그러나 이 환경을 사용하여 Azure를 실험하고 프레미스 간 Azure 가상 네트워크에서 IT 워크로드를 실행하는 많은 측면을 경험할 수 있으며 유일한 요구 사항은 Azure 구독입니다.</p>


  <p>&nbsp;</p>
