### YamlMime:Yaml
ms.openlocfilehash: 1d3b46286c8ddcd4d1306557e1fffae51a6ca233
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139900525"
Slug: spot-every-spring-boot-application-issue-on-the-spot-using-appdynamics
Title: AppDynamics를 사용하여 해당 지점에서 모든 Spring Boot 애플리케이션 문제 발견
Summary: 이제 전체 IT 스택에서 애플리케이션을 관찰하고 인프라, 네트워크 및 보안과 상호 연결하는 기능은 디지털로 변환된 환경에서 필수적입니다. Azure Spring Cloud에서 AppDynamics를 통합하면 Spring Boot 애플리케이션을 쉽게 계측할 수 있습니다.
Content: >-
  <p>오늘 전체 스택 관찰을 위해 Azure Spring Cloud에서 <a href="https://aka.ms/Start-AppDynamics" target="_blank">AppDynamics</a> 의 통합을 발표하게 되어 기쁩니다.</p>


  <p>지난 20개월 동안 많은 엔터프라이즈 고객과 협력하여 직면한 시나리오에 대해 알아봅니다. 이러한 고객 중 상당수는 온-프레미스 데이터 센터에서 수천 개의 Spring Boot 애플리케이션을 실행하고 있습니다. 이러한 애플리케이션을 클라우드로 마이그레이션할 때 개발자가 익숙하고 수년 동안 사용해 온 솔루션을 사용하여 APM(애플리케이션 성능 모니터링)을 위해 계측해야 합니다. 또한 AppDynamics와 같은 에이전트를 사용하여 엔드 투 엔드 모니터링을 위해 이미 미리 계측된 데스크톱 및 모바일 애플리케이션의 연속성을 보장해야 합니다. 이 애플리케이션은 동적 하이브리드, 다중 클라우드 환경의 모든 종속성뿐만 아니라 모든 애플리케이션, 마이크로 서비스 및 인프라를 자동으로 검색하고 매핑합니다. Azure Spring Cloud의 AppDynamics 통합을 통해 경험을 계속하고 AppDynamics를 사용하여 Spring Boot 애플리케이션을 쉽게 계측할 수 있습니다.</p>


  <p style="margin-left: 40px;"><em>&quot;Azure Spring Cloud의 배포는 훨씬 더 광범위한 다중 지역 다중 클라우드 아키텍처의 한 구성 요소일 뿐입니다. Weve&rsquo;는 몇 년 동안 Digital Realty에서 AppDynamics를 사용했으며 성능 메트릭을 캡처하고 전체 스택에서 가용성을 모니터링하기 위해 이 단일 창을 갖고자 했습니다. 뿐만 아니라 AppDynamics는 이벤트 기반 아키텍처를 채택하는 한 가지 구성 요소인 강력한 APM 도구입니다. 우리는 자기 치유와 AIOps를 실험하고 있으며, 지금 할 수있는이 영역에서 우리의 기능을 확장해야합니다.</em>&quot;&mdash; 데본 요스트, Enterprise 설계자, <a href="https://www.digitalrealty.com/" target="_blank">디지털 부동산 신탁</a></p>


  <p style="margin-left: 40px;">&quot;<em>고객이 애플리케이션을 현대화하고 Azure Spring Cloud와 같은 클라우드 플랫폼의 사용 편의성 및 크기 조정을 활용하려고 함에 따라 전체 스택 관찰성에 대한 필요성이 그 어느 때보다 중요해졌습니다. 많은 Presidios&rsquo; 고객은 AppDynamics의 계측 기능을 활용하여 비즈니스에서 요구하는 고성능, 비용 효율 및 고가용성 방식으로 Spring Boot 애플리케이션을 실행합니다. Azure 및 Azure Spring Cloud Platform으로의 마이그레이션을 계획할 때 애플리케이션에 대한 통찰력과 가시성의 일관성이 그 어느 때보다 필요합니다. AppDynamics에 대한 Azure Spring Cloud 지원은 두 플랫폼을 통합하고 Presidio와 고객에게 명확한 경로를 제공합니다.&quot;&mdash;</em> Rich Gondek, 선임 기술 이사, 디지털 비즈니스 솔루션 및 서비스, <a href="https://www.presidio.com/" target="_blank">Presidio</a>.</p>


  <p style="margin-left: 40px;">&ldquo;<em>Im&rsquo;은 Microsoft와의 지속적인 파트너십을 통해 기쁘게 생각합니다. AppDynamics는 Azure Spring Cloud 내에서 작업하는 개발자에게 성능 문제의 근본 원인을 격리하고 비즈니스 영향에 대한 컨텍스트를 사용하여 마이크로 서비스를 최적화할 수 있는 상관 관계 인사이트를 통해 실시간 가시성을 제공합니다.</em>&rdquo;&mdash; 그레그 오스트로프스키, AppDynamics의 경영진 CTO</p>


  <p style="margin-left: 40px;">&ldquo;<em>Microsoft는 Spring 개발자가 Azure에서 대규모로 앱을 더 쉽게 실행할 수 있도록 하기 위해 최선을 다하고 있습니다. AppDynamics는 많은 고객에게 전체 스택 관찰의 중요한 부분이며, 파트너 관계를 통해 이 기능을 Azure Spring Cloud에 통합할 수 있습니다. 개발자&mdash;와 같은 AppDynamicsminimize&mdash;를 위해 선택한 APM 도구를 지원하면 새로운 기능을 제공하는 데 집중할 수 있도록 변경 내용이 적용됩니다.</em>&rdquo;&mdash; Julia Liuson, Microsoft 개발자 부문 부사장</p>


  <p style="margin-left: 40px;"><strong><a href="https://www.youtube.com/watch?v=4dZuRX5bNAs&amp;ab_channel=JavaonAzure" target="_blank"><img alt="Click here to watch the video" border="0" height="563" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/7534f7c0-dff1-4835-820b-114869c90d0a.png" style="border: 0px currentcolor; border-image: none; display: inline; background-image: none;" title="AppDynamics 비디오의 클릭 가능한 이미지입니다. 비디오를 시청하려면 이미지를 클릭합니다." width="1024"></a></strong></p>


  <p style="margin-left: 40px;"><em>AppDynamics를 사용하여 Spring Bootapplications&nbsp;를 모니터링하는 방법에 대해&nbsp; 알아보려면 위의 비디오를 시청하세요.</em></p>


  <p>이제 전체 IT 스택에서 애플리케이션을 관찰하고 인프라, 네트워크 및 보안과 상호 연결하는 기능은 디지털로 변환된 환경에서 필수적입니다. 기술자들은 고객과 비즈니스에 영향을 미치기 전에 문제를 예측할 수 있도록 전체 스택 관찰성을 요구합니다. 동시에 개발자는 Azure Spring Cloud와 같은 최신의 가장 민첩한 클라우드 플랫폼을 채택하여 빠르고 쉽게 대규모로 애플리케이션을 배포하고 실행함으로써 IT 스택을 지속적으로 혁신하고 발전시키고 있습니다. 마찬가지로, 사일로 데이터를 IT 팀에 공유 컨텍스트를 제공하는 실행 가능한 인사이트로 변환하는 전체 스택 가시성, 인사이트 및 작업으로 신속하게 이동하여 뛰어난 디지털 환경을 제공하고 비용 및 성능을 최적화하며 디지털 비즈니스 수익을 극대화할 수 있어야 합니다.</p>


  <p>AppDynamics와 Microsoft는 Azure 고객이 Azure에서 클라우드 네이티브 애플리케이션을 사용하여 해당 수준의 비즈니스 관찰성을 유지할 수 있도록 계속해서 협력합니다. 이제 고객은 코드 변경 없이 AppDynamics&mdash;를 사용하여 Azure Spring Cloud에 배포된 서비스 및 워크로드에서 가장 중요한 사항을 관찰할 수 있습니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/c384f218-e284-4f15-b059-bb27d289b36c.jpg"><img alt="Banner image" border="0" height="134" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/3c59bf84-4756-45a7-8fc0-1c9ac1918e4f.jpg" style="border: 0px currentcolor; border-image: none; display: inline; background-image: none;" title="다른 작업 공간 설정에서 애플리케이션 모니터링 소프트웨어를 사용하는 사람들을 보여주는 일련의 이미지가 있는 배너입니다." width="1666"></a></p>


  <p>Azure Spring Cloud 배포에서 AppDynamics 에이전트를 활성화하는 것은 Azure CLI를 통해 서비스를 배포할 때 JVM 옵션 및 환경 변수를 구성하는 것만큼 간단합니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/1a1ab230-a5b9-48ce-ab4c-d8c4c9ca03c1.jpg"><img alt="Shows Azure CLI command to activate AppDynamics as part a deployment" border="0" height="416" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/8c8106b4-a900-4de4-94ae-f5bb3b4d267b.jpg" style="border: 0px currentcolor; border-image: none; display: inline; background-image: none;" title="그림 1" width="1024"></a></p>


  <p><em><strong>그림 1:</strong> 배포의 일부로 AppDynamics를 활성화하는 Azure CLI 명령을 표시합니다.</em></p>


  <p>AppDynamics 에이전트는 ARM(Azure Resource Manager) 템플릿, Bicep 템플릿 또는 Terraform을 통해 Azure Portal을 통해 Azure Spring Cloud 내에서 활성화할 수도 있습니다.</p>


  <p>활성화되면 AppDynamics 포털을 열어 모니터링을 시작합니다. 아래 보기에서 AppDynamics는 Azure Spring Cloud의 모든 Spring Boot 애플리케이션을 보여 줍니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/db200205-1788-47ab-832c-e73a05c7ee5d.jpg"><img alt="Shows all the Spring Boot applications running in a production workload" border="0" height="444" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/5d628960-40d6-4c1b-8cad-24f5fe7d7bb8.jpg" style="border: 0px currentcolor; border-image: none; display: inline; background-image: none;" title="그림 2" width="1024"></a></p>


  <p><em><strong>그림 2:</strong> 프로덕션 워크로드에서 실행되는 모든 Spring Boot 애플리케이션 표시</em></p>


  <p>또한 애플리케이션을 통한 데이터 흐름을 보여 주는 자동화된 흐름 맵을 볼 수 있으며, Spring Boot 앱과 해당 종속성 및 비즈니스 영향을 완화하기 위해 해결해야 할 문제의 정확한 위치를 확인할 수 있습니다. 아래 보기에서 자동화된 흐름 맵은 추가 구성이 필요한 경우&mdash; 자동으로 사용할 수 있습니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/c01dc0db-7304-4d68-b871-d7eec6576e85.jpg"><img alt="Shows automated app flow maps for Spring Boot applications and their dependencies" border="0" height="590" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/8c77807b-6b6b-4be8-9137-f7f80e3b913d.jpg" style="border: 0px currentcolor; border-image: none; display: inline; background-image: none;" title="그림 3" width="1024"></a></p>


  <p><em><strong>그림 3:</strong> Spring Boot 애플리케이션 및 해당 종속성에 대한 자동화된 앱 흐름 맵 표시</em></p>


  <p>AppDynamics는 프로덕션 애플리케이션 동작에 따라 주요 비즈니스 트랜잭션을 추적합니다. 동적으로 성능을 기준하고 <em>정상</em>을 자동으로 검색하므로 고객과 개발자는 임계값을 초과하는 경우에만 경고를 받습니다. 아래 보기에서는 <em>api-gateway 앱에서 customers-services 앱으로</em> , 그리고 MySQL 데이터베이스로의 데이터 흐름을 보여 줍니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/0aa974e2-b7fb-4e2e-a374-c3b8d6db6056.jpg"><img alt="Shows flow of data from one Spring Boot app to another Spring Boot app, and then to a MySQL database" border="0" height="587" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/514c1a8c-feb1-46ee-9b4c-da7ca280db06.jpg" style="border: 0px currentcolor; border-image: none; display: inline; background-image: none;" title="그림 4" width="1024"></a></p>


  <p><em><strong>그림 4:</strong> 한 Spring Boot 앱에서 다른 Spring Boot 앱으로, 그리고 MySQL 데이터베이스로의 데이터 흐름을 표시합니다.</em></p>


  <p>전체 호출 스택, 세분화된 메서드 수준 코드 세부 정보 및 데이터베이스 쿼리와 같은 심층 진단을 얻을 수도 있습니다. AppDynamics가 수집하는 데이터에 대한 특정 기본 제한이 해제되어 애플리케이션 활동에 대한 추가 가시성을 제공하는 가끔 문제 해결을 위해 <em><a href="https://docs.appdynamics.com/21.9/en/application-monitoring/development-level-monitoring" target="_blank">개발 모드</a></em> 를 설정할 수 있습니다. 아래 표시된 보기에서는 모든 데이터베이스 호출을 확대하고 있으며, 지난 몇 시간 동안 응답 시간이 좋은 약 5백만 건의 호출이 있었습니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/15b4bc37-410e-4797-b7ca-004a5f6d9038.jpg"><img alt="Zooms into all the database calls from a Spring Boot application" border="0" height="590" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/fcddd350-ef5b-49c9-95d1-079e859a124e.jpg" style="border: 0px currentcolor; border-image: none; display: inline; background-image: none;" title="그림 5" width="1024"></a></p>


  <p><em><strong>그림 5:</strong> Spring Boot 애플리케이션에서 모든 데이터베이스 호출을 확대합니다.</em></p>


  <p>가장 느린 데이터베이스 호출을 찾을 수 있습니다. <em>고객 서비스</em> 앱에 대한 아래 보기에서 이러한 호출은 가장 느린 데이터베이스 호출&mdash;이며 연결 설정에 많은 시간이 소요됩니다. 언제나처럼 개선의 여지가 있습니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/ffdd0f64-d645-47a7-8755-46c31250d35d.jpg"><img alt="Shows slowest database calls from a Spring Boot application" border="0" height="302" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/1dbd5a9f-5492-4631-ac05-2adc48ef4661.jpg" style="border: 0px currentcolor; border-image: none; display: inline; background-image: none;" title="그림 6" width="1024"></a></p>


  <p><em><strong>그림 6:</strong> Spring Boot 애플리케이션에서 가장 느린 데이터베이스 호출 표시</em></p>


  <p>AppDynamics에는 시간이 지남에 따라 JVM 메트릭을 볼 수 있는 좋은 JVM 메트릭 브라우저도 있습니다. 아래 보기에서 <em>JVM 스레드 수와 JVM</em> <em>CPU 사용량을</em> 확인할 수 있습니다. 물론 메트릭 브라우저를 통해 더 많은 인사이트를 얻을 수 있습니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/575fceb8-52c6-46de-a822-5fcfbe42627f.jpg"><img alt="Shows JVM Metrics across time in AppDynamics Metric Browser" border="0" height="588" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/31e12782-ea1e-4dc0-b2a7-aa5a25f3c168.jpg" style="border: 0px currentcolor; border-image: none; display: inline; background-image: none;" title="그림 7" width="1024"></a></p>


  <p><em><strong>그림 7:</strong> AppDynamics 메트릭 브라우저에서 시간 간 JVM 메트릭 표시</em></p>


  <p>AppDynamics를 사용하면 개발자, 운영자 및 비즈니스 팀 간에 원활한 공동 작업을 수행할 수 있습니다. 통합 모니터링 및 실시간 인사이트는 이러한 팀을 하나로 모아 애플리케이션 성능, 사용자 환경 및 비즈니스 성능을 유지합니다.</p>


  <h2>솔루션을 빌드하고 지금 모니터링</h2>


  <p>Azure Spring Cloud는 Microsoft 및 VMware에서 공동으로 빌드, 운영 및 지원됩니다. 인프라 및 Spring Cloud 미들웨어 관리의 복잡성을 추상화하여 Azure에서 동적 크기 조정, 패치, 보안, 규정 준수 및 고가용성을 처리할 수 있도록 하는 Spring Boot 애플리케이션용 완전 관리형 서비스입니다. 몇 단계를 통해 Azure Spring Cloud를 프로비전하고, 애플리케이션을 만들고, Spring Boot 애플리케이션을 배포 및 확장하고, 몇 분 안에 모니터링을 시작할 수 있습니다. Azure Spring Cloud에 더 많은 개발자 친화적이고 엔터프라이즈 지원 기능을 계속 도입할 예정입니다. Azure Spring Cloud를 사용하여 영향력 있는 솔루션을 빌드하는 방법을 듣고 싶습니다.</p>


  <p>AppDynamics<a href="https://aka.ms/Start-AppDynamics" target="_blank">를 사용하여</a> Spring Boot 애플리케이션 모니터링을 시작합니다! <a href="https://www.appdynamics.com/blog/news/appdynamics-microsoft-azure-spring-cloud" target="_blank">AppDynamics</a>에서 이 공지 사항에 대해 자세히 알아보세요.</p>


  <h2>리소스</h2>


  <ul>
      <li><a href="https://docs.microsoft.com/en-us/learn/modules/azure-spring-cloud-workshop/" target="_blank">GitHub MS Learn 모듈</a> 또는 <a href="https://github.com/microsoft/azure-spring-cloud-training" target="_blank">자가 진행 워크샵</a>을 사용하는 방법을 알아봅니다.</li>
      <li>Azure Spring Cloud에서 솔루션 구현에 대해 <a href="https://docs.microsoft.com/en-us/azure/spring-cloud/" target="_blank">자세히 알아보기</a></li>
      <li>AppDynamics <a href="https://docs.appdynamics.com/21.9/en/application-monitoring/install-app-server-agents/java-agent/install-the-java-agent/monitor-azure-spring-cloud-with-java-agent" target="_blank">에서 게시한 관련 문서</a> 보기</li>
      <li><a href="https://github.com/Azure-Samples/spring-petclinic-microservices" target="_blank">Spring Petclinic 애플리케이션</a>의 분산 버전 배포</li>
      <li>엔터프라이즈 모범 사례를 활용하여 Spring Boot 애플리케이션 배포Azure&mdash; <a href="https://docs.microsoft.com/en-us/azure/spring-cloud/reference-architecture" target="_blank">Spring Cloud 참조 아키텍처</a></li>
      <li><a href="https://docs.microsoft.com/en-us/azure/developer/java/migration/migrate-spring-boot-to-azure-spring-cloud" target="_blank">Spring Boot</a>, <a href="https://docs.microsoft.com/en-us/azure/developer/java/migration/migrate-spring-cloud-to-azure-spring-cloud" target="_blank">Spring Cloud</a> 및 <a href="https://aka.ms/migrate-tomcat-to-azure-spring-cloud-service" target="_blank">Tomcat</a> 애플리케이션을 Azure Spring Cloud로 마이그레이션</li>
      <li><a href="https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/" target="_blank">Azure 서비스와 상호 작용하는</a> Wire Spring 애플리케이션</li>
      <li>피드백 및 질문은 <a href="mailto:mailto:AzureSpringCloud-Talk@service.microsoft.com" target="_blank">전자 메일로</a> 보내주세요.</li>
  </ul>
