### YamlMime:Yaml
ms.openlocfilehash: ee8b6e0f5819e968a69044bf0c47ed896a5c2a86
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139900485"
Slug: sql-azure-connection-security
Title: SQL Azure 연결 보안
Summary: '[이 문서는 SQL Azure 팀에서 제공했습니다.] Selcin Turkarslan은 SQL Azure 사용할 때 연결 보안 고려 사항에 대한 심층적인 TechNet 위키 문서를 작성했습니다. 문서는...'
Content: <p>[이 문서는 SQL Azure 팀에서 제공했습니다.]</p><p>Selcin Turkarslan은 SQL Azure 사용할 때 연결 보안 고려 사항에 대한 심층적인 TechNet 위키 문서를 작성했습니다. 이 문서는 주로 SQL Azure Database에 대한 보안 연결 문자열 작성과 관련이 있습니다. Id&rsquo;는 SQL Azure 연결할 때 좋은 절차와 모범 사례를 자세히 설명하므로 읽는 것이 좋습니다. </p>  <p><a href="https://social.technet.microsoft.com/wiki/contents/articles/sql-azure-connection-security.aspx">"SQL Azure 연결 보안"을 읽으려면 여기를 클릭하십시오.</a></p>  <p>SQL Azure 내의 연결 보안에 대한 질문이 있는 경우 의견을 남겨주세요.  당신이 질문이있는 경우 Wed&rsquo;는 당신을 도울 수 있기를 좋아합니다.</p>  <p>-Steve</p>
