### YamlMime:Yaml
ms.openlocfilehash: c39f77fc7c0e10c8a356e082e846e1d4ccb43baf
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139900175"
Slug: taking-advantage-of-the-new-azure-application-gateway-v2
Title: 새 Azure Application Gateway V2 활용
Summary: 최근에 Azure Application Gateway V2 또는 SKU(자동 크기 조정 버전) 및 WAF(웹 애플리케이션 방화벽)를 릴리스했습니다. 이러한 SKU는 각각 Standard_v2 및 WAF_v2 99.95% SLA에서 완벽하게 지원됩니다.
Content: >-
  <p>최근에 <a href="https://azure.microsoft.com/en-us/updates/azure-application-gateway-standardv2-wafv2-skus-generally-available/" target="_blank">Azure Application Gateway V2 및 WAF(웹 애플리케이션 방화벽) V2</a>를 릴리스했습니다. 이러한 SKU는 각각 Standard_v2 및 WAF_v2 이름이 지정되며 99.95% SLA에서 완벽하게 지원됩니다. 새로운 SKU는 고객에게 상당한 개선 및 추가 기능을 제공합니다.</p>


  <ul>
   <li>자동 크기 조정은 애플리케이션 트래픽 패턴에 따라 필요에 따라 애플리케이션 게이트웨이의 크기를 조정하여 애플리케이션&rsquo;에 대한 탄력성을 허용합니다. 프로비전된 최대 용량에서 애플리케이션 게이트웨이를 더 이상 실행할 필요가 없으므로 비용을 크게 절감할 수 있습니다.</li>
   <li>영역 중복성을 사용하면 애플리케이션 게이트웨이가 영역 오류에서 살아남을 수 있으므로 애플리케이션에 대한 복원력이 향상됩니다.</li>
   <li>정적 VIP 기능을 사용하면 엔드포인트 주소가 수명 주기 동안 변경되지 않습니다.</li>
   <li>헤더 다시 쓰기를 사용하면 애플리케이션 게이트웨이에서 HTTP 요청 및 응답 헤더를 추가, 제거 또는 업데이트할 수 있으므로 애플리케이션 코드를 터치할 필요 없이 HSTS 지원, 쿠키 보안, 캐시 컨트롤 변경 등과 같은 다양한 시나리오를 사용할 수 있습니다.</li>
   <li>더 빠른 프로비전 및 구성 업데이트 시간</li>
   <li>애플리케이션 게이트웨이에 대한 성능 향상은 전체 비용을 줄이는 데 도움이 됩니다.</li>
  </ul>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/7d2c7d22-a6e7-4e25-bffd-2cad72451abf.png"><img alt="Diagram showing improved capabilities in V2" border="0" height="456" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/5effa721-8032-40d3-9864-43e514caaa2a.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="V2의 향상된 기능을 보여 주는 다이어그램" width="640"></a></p>


  <p>고객은 새 애플리케이션/워크로드에 대해 V1 SKU 대신 V2 SKU를 사용하는 것이 좋습니다.</p>


  <p>Application Gateway/WAF의 V1 SKU 뒤에 기존 애플리케이션이 있는 고객은 나중에 V2 SKU로 마이그레이션하는 것도 고려해야 합니다. 이러한 이유 중 일부는 다음과 같습니다.</p>


  <ul>
   <li><strong>기능 및 개선</strong> 사항: 위에서 언급한 향상된 기능과 기능을 활용하고 출시될 때 로드맵의 새로운 기능을 계속 활용할 수 있습니다. 앞으로 로드맵의 새로운 기능 대부분은 V2 SKU에서만 릴리스됩니다.</li>
   <li><strong>비용</strong>: V2 SKU는 V1 SKU에 비해 전반적으로 저렴할 수 있습니다. V2 SKU 비용에 대한 자세한 내용은 <a href="https://docs.microsoft.com/en-us/azure/application-gateway/application-gateway-autoscaling-zone-redundant#pricing" target="_blank">가격 책정 페이지를</a> 참조하세요.</li>
   <li><strong>향후 플랫폼 지원</strong>: 향후 V1 SKU에서 새 게이트웨이 만들기를 사용하지 않도록 설정합니다. 고객이 마이그레이션할 충분한 시간을 가질 수 있도록 사전 알림이 제공됩니다. 게이트웨이를 V2 SKU로 더 빨리 마이그레이션하면 더 많은 엔지니어링 및 지원 리소스를 V2 SKU에 더 빨리 할당할 수 있습니다.&nbsp; 도와주세요!</li>
  </ul>


  <h2>V2 SKU 게이트웨이로 마이그레이션 구성 복제 안내 &ndash;</h2>


  <p>고객은 V1 게이트웨이와 동일한 구성을 사용하여 새 V2 게이트웨이를 수동으로 구성하여 자체적으로 마이그레이션을 수행할 수 있지만, 실제로 많은 고객에게는 관련될 수 있는 구성 터치포인트의 수로 인해 매우 복잡하고 오류가 발생하기 쉽습니다. 이를 돕기 위해 최근에 <a href="https://aka.ms/appgwmigrationdoc" target="_blank">V1 게이트웨이의 구성을 새 V2 게이트웨이로 복제</a>하는 데 도움이 되는 설명서와 함께 PowerShell 스크립트를 게시했습니다.</p>


  <p>PowerShell 스크립트에는 몇 가지 입력이 필요하며 지정된 V1 게이트웨이에서 새 V2 게이트웨이로 구성을 원활하게 복사합니다. V2 게이트웨이가 자동으로 만들어집니다.) 몇 가지 <a href="https://docs.microsoft.com/en-us/azure/application-gateway/migrate-v1-v2#caveatslimitations" target="_blank">제한 사항이</a> 있으므로 스크립트를 사용하기 전에 이러한 제한 사항을 살펴보고 <a href="https://docs.microsoft.com/en-us/azure/application-gateway/migrate-v1-v2#common-questions" target="_blank">미니 FAQ</a> 를 방문하여 추가 지침을 확인하세요.</p>


  <h2>트래픽을 새 V2 엔드포인트로 전환</h2>


  <p>애플리케이션 게이트웨이를 통한 트래픽 흐름이 설계되는 방식의 세부 사항은 애플리케이션마다, 고객마다 다르므로 이는 고객에게 전적으로 달려 있습니다. 그러나 <a href="https://docs.microsoft.com/en-us/azure/application-gateway/migrate-v1-v2#migrate-client-traffic" target="_blank">트래픽 흐름의 일부 시나리오에 대한 지침을</a> 제공했습니다. 특히 Azure DNS 또는 Azure Traffic Manager 사용하여 애플리케이션 게이트웨이로 트래픽을 전송하는 고객을 위해 이 단계를 사용하는 고객을 돕기 위한 향후 도구를 고려할 것입니다.</p>


  <h2>피드백</h2>


  <p>언제나처럼, 우리는 당신의 귀중한 피드백을 듣고에 관심이 있습니다. V2 SKU로의 마이그레이션에 대한 특정 피드백은 다음으로 <a href="mailto:appgwmigrationsup@microsoft.com">appgwmigrationsup@microsoft.com</a>이메일을 보내 드립니다. Application Gateway에 대한 일반적인 피드백은 <a href="https://feedback.azure.com/forums/217313-networking?category_id=134448" target="_blank">Azure 피드백 페이지를</a> 사용하세요.</p>
