### YamlMime:Yaml
ms.openlocfilehash: d43ed7aac300a73d44e01eeb1959ffe1c0f067ee
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139908741"
Slug: the-3-ways-azure-improves-your-security
Title: Azure에서 보안을 개선하는 3가지 방법
Summary: 오늘 우리는 RSA에 있으며, 보안을 중심으로 한 이 업계 행사를 후원하고 참여하게 되어 기쁩니다. 클라우드 보안에 대한 우리의 관점을 공유할 수 있는 기회를 얻게 될 거라고 생각했습니다.
Content: >-
  <p><em>이 블로그는 Microsoft Azure 안전한 기반을 제공하는 방법에 대한 4부로 구성된 <a href="https://azure.microsoft.com/en-us/blog/tag/azure-security/">블로그 게시물 시리즈의</a> 두 번째 블로그입니다.</em></p>


  <p>오늘 우리는 RSA에서 were&rsquo;, 우리는 후원하고 보안을 중심으로이 산업 이벤트에 참여하게 되어 기쁘게 생각합니다. Id&rsquo;는 클라우드 보안에 대한 우리의 관점을 Azure와 공유할 수 있는 기회를 얻게 될 것이라고 생각했습니다.</p>


  <p>우리 모두가 알다시피, 전 세계 기업들은 진화하는 보안 위협의 지속적인 볼륨과 이러한 위협에 대응하기 위해 자격을 갖춘 보안 인재를 유지하는 데 어려움을 겪고 있습니다. 실제로 평균 대규모 조직은 매주 17,000건의 보안 경고를 받으며, 이로 인해 보안 위반을 검색하는 데 평균 99일이 발생합니다. 이는 보안 위반이 손상된 한 시스템에서 훨씬 더 광범위한 문제로 증가하는 데 걸리는 48시간 미만과는 대조적입니다.</p>


  <p>이러한 문제를 해결하기 위한 솔루션을 찾을 때 Azure는 비용과 복잡성을 줄이면서 보안 태세를 강화하는 데 도움이 될 수 있습니다. TD Bank, First Tech Credit Union, Geico, 3M, <a href="https://customers.microsoft.com/en-us/story/rollsroycestory" target="_blank">롤스로이스</a>, 하와이 주, 머슨 시, 하이네켄 등 전 세계의 수천 개의 기업과 정부가 Azure를 신뢰할 수 있는 클라우드로 선택했습니다. Azure는 Microsoft에서 제공하는 보안 기반, 전체 스택에서 보안을 신속하게 구성하는 데 도움이 되는 기본 제공 보안 컨트롤 및 데이터를 보호하고 실시간으로 위협에 대응할 수 있도록 클라우드 규모의 고유한 인텔리전스를 제공하는 세 가지 주요 영역에 &ndash; 가치를 제공합니다.</p>


  <h3>1. Azures&rsquo; 보안 기반</h3>


  <p>Microsoft는 Azure 플랫폼을 포함하여 사이버 보안에 매년 10억 달러 이상을 투자하므로 IT 예산 및 리소스를 다른 중요 비즈니스용 이니셔티브에 할당할 수 있습니다.</p>


  <p>사이버 방어 운영 센터, 디지털 범죄 단위 및 기타 팀에서 협력하는 3,500명의 전담 사이버 보안 전문가를 활용하여 실시간으로 위협을 보호, 감지 및 대응할 수 있습니다.</p>


  <p><a href="https://azure.microsoft.com/en-us/blog/azure-layered-approach-to-physical-security/" target="_blank">물리적 보안을</a> 위해 Azure에는 50개 지역에 수백 개의 데이터 센터가 있으며, 권한이 없는 사용자가 고객 데이터에 물리적으로 액세스할 수 없도록 광범위한 다중 계층 보호 기능이 있습니다.</p>


  <p>클라우드 보안에는 사이버 보안 전문가 및 물리적 제어보다 훨씬 더 많은 것이 포함됩니다. Azure용 컴퓨팅 인프라는 비밀 관리 및 점점 더 많은 하드웨어 기반 enclave 기술을 포함하여 하드웨어 및 펌웨어 구성 요소에 통합된 보안 제어를 사용하여 사용자 지정된 하드웨어를 기반으로 합니다.</p>


  <p>광범위한 네트워크 인프라에는 볼륨 또는 프로토콜 계층 공격으로부터 리소스를 보호하기 위해 DDoS에 대한 기본 제공 보호 기능이 있습니다. Azure DDoS Protection에는 최대 워크로드로 보호를 확장하고 Xbox 및 O365와 같은 Microsoft 서비스 보호하는 환경을 위한 운영 용량이 있습니다.</p>


  <p>보안은 끊임없이 진화하는 상태이므로 시간을 절약하기 위해 Azure를 실행하는 서버가 패치되도록 하는 등의 기본 사항을 관리합니다. 우리는 지속적인 테스트 및 모니터링을 통해 취약성을 식별하기 위해 적극적으로 노력하고 레드 팀 대 블루 팀 사이버 침투 테스트와 같은 연습을 실행합니다.</p>


  <p>고객이 Azure를 선택한 이유 중 하나는 핵심 가치를 제공하는 데 더 많은 리소스를 투입할 수 있는 보안 기반이라는 것을 <a href="https://customers.microsoft.com/en-us/story/core-banking-software-provider-moves-flagship-offering" target="_blank">고객</a> 으로부터 정기적으로 듣습니다.</p>


  <h3>2. Azure&rsquo; 기본 제공 보안 컨트롤</h3>


  <p>Azure에서 제공하는 보안 기반이 있더라도 보안은 궁극적으로 Microsoft와 고객 간의 공동 책임입니다. Azure에 워크로드 및 데이터를 배치하는 경우 보안 모범 사례를 따르는 것이 좋습니다. Azure에는 보안 관리 및 위협 방지에 도움이 되는 ID, 네트워크, 데이터 및 도구를 통해 더 빠르게 보호할 수 있는 기본 제공 보안 컨트롤이 있습니다.</p>


  <p><strong>ID 및 액세스 관리: </strong><a href="https://azure.microsoft.com/en-us/services/active-directory/" target="_blank">Azure Active Directory</a> Azure, Office 365 및 수백 개의 인기 있는 SaaS 및 PaaS 클라우드 서비스와 온-프레미스를 포함한 모든 클라우드 서비스에서 액세스를 관리하기 위한 중앙 시스템입니다. Active Directory는 세계에서 가장 사용되는 디렉터리 서비스입니다. <a href="https://azure.microsoft.com/en-us/services/multi-factor-authentication/" target="_blank">Azure Multi-Factor Authentication</a>을 사용하여 액세스를 보호하는 것이 좋습니다. 또한 Azure에서 내부적으로 수행하는 것과 동일한 접근 방식을 따르고 <a href="https://docs.microsoft.com/en-us/azure/active-directory/role-based-access-control-configure" target="_blank">역할 기반</a> 액세스를 사용하여 작업별로 필요한 사용자로만 액세스를 제한하는 것이 좋습니다.</p>


  <p><strong>네트워크 보안:</strong> Azure VNet(가상 네트워크)을 통해 보안 네트워크를 빌드하고 유지 관리하는 작업은 일반적으로 서브넷을 분할하고 <a href="https://docs.microsoft.com/en-us/azure/virtual-network/virtual-networks-nsg" target="_blank">네트워크</a> 및 <a href="https://azure.microsoft.com/en-us/blog/applicationsecuritygroups/" target="_blank">애플리케이션</a> 보안 그룹을 사용하여 액세스 규칙을 구성하는 것부터 시작합니다. 보안 사이트-사이트 VPN 또는 전용 <a href="https://azure.microsoft.com/en-us/services/expressroute/" target="_blank">Azure ExpressRoute</a> 연결을 사용하여 온-프레미스 네트워크를 클라우드로 확장합니다. 기본 제공 웹 애플리케이션 <a href="https://docs.microsoft.com/en-us/azure/application-gateway/application-gateway-web-application-firewall-overview" target="_blank">방화벽을 사용하여 웹 애플리케이션을</a> 보호합니다. 이번 주 RSA에서 발표하는 <a href="https://azure.microsoft.com/en-us/services/ddos-protection/" target="_blank">Azure DDoS Protection 표준</a> 은 턴키 보호, 원격 분석 및 경고를 사용하여 가상 네트워크에 대한 DDoS 보호에 대한 더 많은 제어를 제공합니다.</p>


  <p><strong>데이터 보호 및 비밀 관리:</strong> Azure는 전송 중&rsquo;, 미사용 상태 또는 사용되는 동안&rsquo;에도 데이터를 보호할 수 있습니다. Azure는 업계 표준 프로토콜을 사용하여 디바이스와 Microsoft 데이터 센터 간에 이동할 때 전송 중인 데이터를 암호화합니다. 데이터가 <a href="https://docs.microsoft.com/en-us/azure/storage/storage-security-guide?toc=%2fazure%2fsecurity%2ftoc.json" target="_blank">Azure Storage</a> 유지되면 기본 제공 데이터 암호화를 사용하여 데이터를 보호할 수 있습니다. <a href="https://azure.microsoft.com/en-us/services/key-vault/" target="_blank">Azure Key Vault</a> 를 사용하면 클라우드 앱 및 서비스에서 사용하는 암호화 키 및 기타 비밀을 보호하고 제어할 수 있습니다. 데이터 암호화 컨트롤은 가상 머신에서 CosmosDB 및 Azure Data Lake로 SQL 서비스에 기본 제공됩니다. 최근에 발표된 <a href="https://azure.microsoft.com/en-us/blog/safeguarding-your-cloud-resources-with-azure-security-services/" target="_blank">Azure 기밀 컴퓨팅</a>에서 데이터를 사용하는 동안&rsquo;에도 데이터를 보호할 수 있습니다.</p>


  <p><strong>위협을 방지하고 검색하는 데 도움이 되는 통합 보안 관리:</strong> Azure Security Center는 Azure 워크로드의 보안 문제에 대한 인사이트를 제공하고 수정할 사항에 대한 명확한 제안을 제공합니다. Azure Security Center는 에이전트를 사용하여 가상 머신 및 클라우드 리소스 내에서 중요한 보안 문제를 검색하기 위해 다른 클라우드에 있는 에이전트 없는 대안의 기능을 넘어갑니다. Azure Security Center를 확장하여 온-프레미스 워크로드를 관리할 수도 있습니다.</p>


  <p>Azure Security Center <a href="https://azure.microsoft.com/en-us/blog/just-in-time-vm-access-is-generally-available/" target="_blank">Just-In-Time VM 액세스를</a> 사용하여 무차별 암호 대입 공격으로부터 가상 머신 관리 포트를 보호할 수 있습니다. 이번 주 RSA에서는 WINDOWS DEFENDER ATP 통합을 통해 서버에 대한 향상된 보호, 여러 구독에서 규정 준수를 평가하고 가상 머신 환경의 컨텍스트 내에서 쉽게 보안을 구성하는 데 도움이 되는 향상된 관리 대시보드 환경을 포함하여 Azure Security Center에 대한 많은 <a href="https://aka.ms/czyvn4" target="_blank">새로운 기능을</a> 발표합니다.</p>


  <p>ID, 네트워킹, 데이터, 위협 방지 및 보안 관리 전반에 걸친 Azure&rsquo;의 다양한 기본 제공 보안 서비스를 사용하면 보안 태세를 간단하게 개선할 수 있습니다. Barracuda, Palo Alto 및 Check Point와 같은 회사에서 <a href="https://azuremarketplace.microsoft.com/en-us/marketplace/apps/category/security-identity?page=1" target="_blank">Azure Marketplace에서 사용할 수 있는 많은 파트너 보안 솔루션을</a> 사용하여 기존 투자를 Azure로 확장할 수도 있습니다.</p>


  <h3>3. Azures&rsquo; 고유 인텔리전스</h3>


  <p>진화하는 위협 환경에서 위협 데이터 세트의 크기는 크고 지속적으로 변화하고 있습니다. 우리는 모두 사이버 공격에 대처하기 위해 함께 노력하고 있기 때문에 위협에 보조를 맞추기 위해 집단 인텔리전스를 활용해야 합니다. Microsoft Intelligence Security Graph 매월 4,500억 개의 인증, 40억 개의 이메일 및 10&mdash;억 디바이스의 데이터를 포함하여 대규모로 사용되는 많은 Microsoft 제품의 신호를 결합하여 진화하는 위협으로부터 보호하는 데 필요한 인텔리전스를 제공합니다. RSA에서는 그래프의 풍부한 정보를 더 많이 늘리고 접근성을 높이기 <a href="https://aka.ms/graphsecurityapi" target="_blank">위해 Microsoft Intelligence Security Graph API</a>의 미리 보기를 발표합니다.</p>


  <p><a href="https://azure.microsoft.com/en-us/services/security-center/" target="_blank">Azure Security Centers&rsquo;</a> 위협 방지를 사용하면 Microsoft Intelligence Security Graph 기계 학습 및 시각화와 결합하여 가장 중요한 문제를 이해하고 완전한 공격 체인을 빠르게 시각화하여 보안 경고 대시보드에서 위협을 감지하고 완화할 수 있습니다. 모든 엔터프라이즈 고객이 이 기능을 켜는 것이 좋습니다.</p>


  <p>보안 태세를 강화하기 위해 Azure가 보안 기반에서 제공하는 보안 기능, 기본 제공 컨트롤 및 고유한 인텔리전스에 대해 고려하는 것이 좋습니다. 자세히 알아보려면 새 <a href="https://youtu.be/OTGMi0ksjXY" target="_blank">Azure Essentials 비디오를</a> 시청하고 <a href="https://azure.microsoft.com/en-us/overview/security/" target="_blank">웹 페이지를 방문하세요</a>.</p>


  <h2>RSA 2018의 Azure Security</h2>


  <p>이번 주 샌프란시스코에서 열리는 RSA 컨퍼런스에 참석하는 경우 <strong>3501 부스</strong> 를 방문하여 Azure Security에 대해 자세히 알아보세요. 우리는 당신과 연결 기다릴 수 없어!</p>


  <p>&nbsp;</p>


  <hr>

  <p><sup>1</sup>&rdquo; 전체적인 보안 전략에 대한 7단계,&rdquo; 2017, Microsoft.<br>

  <sup>2개</sup>&rdquo; M-Trends 2016,&rdquo; 2016, Mandiant Consulting.<br>

  <sup>3</sup>&rdquo; 위반의 해부학,&rdquo; 2016, 마이크로 소프트.</p>
