### YamlMime:Yaml
ms.openlocfilehash: 56ee6b9b7c98ef3bfce7c3186fb624a2d5d3ebcf
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139905771"
Slug: tracking-configuration-changes-for-your-azure-vm
Title: Azure VM에 대한 구성 변경 내용 추적
Summary: 이 블로그 게시물에서는 변경 내용 추적 솔루션을 사용하여 Azure VM에서 게스트 내 변경 내용을 검색하는 방법에 대해 설명합니다. Azure VM 내에서 시스템 전체에서 발생한 변경 내용의 세부 정보를 신속하게 평가할 수 있습니다. 현재 소프트웨어, 파일, Windows 레지스트리, Windows 서비스 및 Linux 디먼 추적을 지원합니다.
Content: >-
  <p>이 블로그 게시물에서는 변경 내용 추적 솔루션을 사용하여 Azure VM에서 게스트 내 변경 내용을 검색하는 방법에 대해 설명합니다. Azure VM 내에서 시스템 전체에서 발생한 변경 내용의 세부 정보를 신속하게 평가할 수 있습니다. 현재 소프트웨어, 파일, Windows 레지스트리, Windows 서비스 및 Linux 디먼 추적을 지원합니다.</p>


  <p>이 기능은 현재 <strong>프라이빗 미리 보기</strong>로 제공됩니다. &rsquo;당신이 그것을 시도에 관심이 있다면, <a href="https://aka.ms/automationconfigforvm">여기에 가입</a>하시기 바랍니다!</p>


  <h2>변경 내용 추적 사용</h2>


  <p>VM에서 <strong>Automation + Control</strong> 아래의 가상 머신 블레이드에서 <strong>변경 내용</strong>&rdquo; 추적을 선택할 &ldquo; 수 있습니다. 이 VM을 선택한 후 이 VM에 대해 변경 내용 추적 솔루션을 사용할 수 있는지 확인하기 위해 유효성 검사가 수행됩니다. 사용하도록 설정되지 않은 경우 솔루션을 사용하도록 설정하는 옵션이 있습니다.</p>


  <p>솔루션 사용 프로세스는 일반적으로 몇 분밖에 걸리지 않지만 최대 15분이 걸릴 수 있습니다. 이 시간 동안 브라우저 창을 닫으면 안 됩니다. 솔루션을 사용하도록 설정하고 로그 데이터가 작업 영역으로 흐르기 시작하면 다음 섹션에 설명된 대시보드에서 데이터를 분석하는 데 30분 이상 걸릴 수 있습니다. 향후 이 시기가 크게 개선될 것으로 예상됩니다.</p>


  <h2>VM의 변경 내용 시각화</h2>


  <p>변경 내용 추적 대시보드에서 VM에서 발생한 변경 내용을 볼 수 있습니다. 기본 그래프 집합은 시간 및 변경 유형별로 구성 변경 내용을 표시합니다. 아래 대화형 표에는 지정된 시간 범위 동안 발생한 변경 내용이 표시됩니다. 테이블 행을 클릭하면 각 변경 내용의 세부 정보를 볼 수 있습니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/4e25da92-48e5-45d1-a594-4d17afe8f73f.png"><img alt="image" border="0" height="380" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/59657b1a-3cdc-4693-b35f-194f3c7ac3cf.png" style="border: 0px currentColor; border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="이미지" width="800"></a></p>


  <p>볼 수 있는 기간을 변경하려면 <strong>필터</strong>&rdquo;를 &ldquo; 클릭합니다. 기본 시간 범위는 지난 24시간이지만 지난 30분, 지난 1시간, 지난 6시간, 지난 7일, 지난 30일 또는 사용자 지정 시간 범위로 시간 범위를 설정할 수도 있습니다. 변경 내용 추적 솔루션은 모든 Windows 서비스, 모든 Linux 디먼, 모든 소프트웨어 및 일부 Linux 파일(/etc/*.conf)을 기본적으로 추적합니다. 그러나 컴퓨터에서 추가 파일 및 Windows 레지스트리 변경 내용을 수집하려는 경우 <strong>구성</strong>&rdquo;을 &ldquo; 클릭하여 솔루션&rsquo; 컬렉션 설정에 추가할 수 있습니다. 참고: 구성 설정은 해당 작업 영역 아래의 모든 컴퓨터에서 범용입니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/c5a1dbbf-a474-4576-8aaa-03b4c49cd7fb.png"><img alt="image" border="0" height="361" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/94052b69-b2ef-4c87-847a-64f9a2b04874.png" style="border: 0px currentColor; border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="이미지" width="640"></a></p>


  <p>컬렉션 설정에서 페이지 맨 위에 있는 탭을 통해 수정하려는 변경 유형으로 이동하면 됩니다. 더하기(+) 아이콘을 클릭하여 지정된 변경 유형에 대한 새 컬렉션 설정을 추가하거나 기존 설정을 클릭하여 속성을 편집할 수 있습니다.</p>


  <h2>VM에 대한 Azure 활동 로그 이벤트 상관 관계 지정</h2>


  <p>OMS 작업 영역으로 데이터를 유입하는 Azure 활동 로그 솔루션이 있는 경우 Azure 활동 상관 관계 선 그래프를 사용하도록 설정하여 변경 내용 추적 기간 내에 발생한 VM에 대한 활동 로그 이벤트의 추세를 확인할 수 있습니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/45fb26ac-37a8-403d-9432-b1c9733908af.png"><img alt="image" border="0" height="193" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/9350e2c9-aed3-4888-a8cf-f0eed88622be.png" style="border: 0px currentColor; border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="이미지" width="640"></a></p>


  <p>OMS 작업 영역에서 Azure 활동 로그를 받으려면 아래 단계를 수행합니다(원본 <a href=""></a>).</p>


  <ol>
   <li>OMS에서 Azure 활동 Log Analytics 솔루션 추가</li>
   <li>Azure의 작업 영역으로 이동하여 작업 영역 데이터 원본 아래의 Azure 활동 로그&quot;를 클릭합니다&quot;.</li>
   <li>선택한 구독에 대한 연결 사용</li>
   <li>데이터 수집을 시작해야 합니다.</li>
  </ol>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/f7610aab-06c0-43eb-83ae-fc74b091f9e3.png"><img alt="image" border="0" height="306" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/bc75eb04-0b17-4b21-a3cd-d5dd91cb635a.png" style="border: 0px currentColor; border-image: none; padding-top: 0px; padding-right: 0px; padding-left: 0px; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="이미지" width="640"></a></p>


  <p>활동 로그 그래프 지점을 클릭하여 해당 시간 동안 발생한 활동 로그 이벤트를 확인할 수 있습니다. 결과는 로그 검색에서 열립니다.</p>


  <h2>OS 지원</h2>


  <p>OMS 에이전트 요구 사항을 충족하는 모든 운영 체제를 지원합니다. x86 및 x64 버전은 모두 다양한 배포에서 공식적으로 지원됩니다. 그러나 OMS 에이전트는 나열되지 않은 다른 배포판에서도 실행될 수 있습니다.</p>


  <ul>
   <li>Windows
   <ul>
    <li>Windows Server 2008 SP 1 이상</li>
    <li>Windows 7 SP1 이상</li>
   </ul>
   </li>
   <li>Linux
   <ul>
    <li>Amazon Linux 2012.09~2015.09</li>
    <li>CentOS Linux 5, 6 및 7</li>
    <li>Oracle Linus 5, 6 및 7</li>
    <li>Red Hat Enterprise Linux Server 5, 6 및 7</li>
    <li>Debian GNU/Linux 6, 7, 8</li>
    <li>Ubuntu 12.04 LTS, 14.04 LTS, 15.04 및 15.10</li>
    <li>SUSE Linux Enterprise Server 11 및 12</li>
   </ul>
   </li>
  </ul>


  <h2>OMS 변경 내용 추적의 새로운 기능</h2>


  <p>OMS 변경 내용 추적을 익숙하지 않은 경우 <a href="https://docs.microsoft.com/en-us/azure/log-analytics/log-analytics-change-tracking">설명서</a>에서 Windows 및 Linux 컴퓨터 모두에서 변경 검색을 포함하는 현재 기능을 볼 수 있습니다.</p>
