### YamlMime:Yaml
ms.openlocfilehash: b2887a9fb2e66a39ecea73ec095744718a0091d9
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139898239"
Slug: train-an-iot-equipped-drone-and-compete-to-win-at-microsoft-build
Title: IoT가 장착된 드론을 학습시키고 Microsoft Build에서 승리하기 위해 경쟁합니다.
Summary: Microsoft의 궁극적인 개발자 이벤트에 대한 준비가 되셨나요? 워싱턴 주 시애틀에서 5월 7~9일에 열리는 Microsoft Build를 이미 알고 있다면 전문가와 연결해야 합니다...
Content: >-
  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/07e079d6-c34d-4e03-a115-e4a92080d0f0.png"><img alt="Build-Drone-Contest-Banner%202%202000x590%20" border="0" height="590" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/b9e56a74-5964-472d-9dad-ed83d7eb026f.png" style="border: 0px currentcolor; border-image: none; display: inline; background-image: none;" title="Build-Drone-Contest-Banner%202%202000x590%20" width="2000"></a></p>


  <p>Microsofts&rsquo; 궁극의 개발자 이벤트에 대한 준비가 되셨나요? 5월 79&ndash;일 워싱턴 주 시애틀에서 열리는 <a href="https://www.microsoft.com/en-us/build/?icid=azure_blog_drone_copy1" target="_blank">Microsoft Build</a>를 이미 알고 있다면 전문가와 연결하고, 새로운 도구를 검색하고, 클라우드 기술, AI, 혼합 현실 등에 대한 기술을 향상시켜야 합니다.</p>


  <p>물론, 훌륭한 스피커와 기술 세션이&mdash; 있을 것입니다 풍부한 당신은 당신이 무인 항공기를 이길 수 알고 있었습니까?</p>


  <p>그건&rsquo; 바로, 무인 항공기 대회를 가지고 were&rsquo;. 참가자들은 드론이 Microsoft Build용으로 특별히 설계된 야외 수색 및 구조 과정을 완료할 수 있는 동료 컨퍼런스 참석자와 경쟁하게 됩니다. Microsofts&rsquo;&rsquo; 인텔리전트 클라우드 플랫폼, Azure IoT Edge에서 실습, 엔드투엔드 환경을 제공하고 DJI Mavic Air 드론을 획득할 수 있습니다.</p>


  <p>얼마나 멋진가요?</p>


  <h2>작동 방식의 이단&rsquo;</h2>


  <p>참가자는 오픈 소스 항공 정보학 및 로봇 시뮬레이션 플랫폼인 AirSim을 사용하여 학습 이미지를 만듭니다. 그런 다음 참가자는 Custom Vision을 사용하여 클라우드에서 현실적인 AI 드론 모델을 빌드하고 학습한 다음, <a href="https://www.microsoft.com/en-us/internet-of-things/intelligentedge" target="_blank">IoT Edge를 Microsoft Azure</a> AI 배포용 컨테이너를 만듭니다. 이 지능형 클라우드 플랫폼을 사용하면 클라우드 가장자리에서 인공 지능을 실행하고, 분석을 수행하고, 클라우드에서 에지 지원 디바이스로 IoT 솔루션을 배포하고, 클라우드에서 중앙에서 관리할 수 있습니다.</p>


  <p>컨퍼런스 중에 <a href="https://aischool.microsoft.com/learning-paths" target="_blank">AI School</a>에서 Azure IoT Edge 개발자 도구 키트를 다운로드하고, 2018년 5월 9일 수요일 오전 11시 태평양 표준시 이전에 드론 부스에서 콘테스트에 모델을 입력할 수 있습니다. 정오에, 웰&rsquo;은 무작위로 그 날 저녁 라이브 드론에 자신의 모델을 테스트하기 위해 10 행운의 참가자를 그립니다. &rsquo;그리고 모든 사람이 작업을 엿볼 수 있도록 Microsoft Build 닫기 축하 행사 기간 동안 대회를 라이브 스트리밍할 수 있습니다.</p>


  <p>우승자는 DJI Mavic Air 드론을 받게 됩니다. 2위와 3위 우승자는 DJI Spark 드론을 집으로 가져갔습니다. 모든 결선 진출자는 독점 스웨그로 가득 찬 구디 백을 받게 됩니다. 자세한 내용 및 전체 콘테스트 규칙은 <a href="https://www.microsoft.com/en-us/build" target="_blank">Microsoft Build 웹 사이트를</a> 방문하세요.</p>


  <h2>대회 이후</h2>


  <p>콘테스트에 참가하든 Microsoft Build 환경을 다른 활동으로 채우든, 엑스포의 AI 영역에서 드론 부스를 확인하세요. 웰&rsquo;은 또한 무인 항공기 박물관, 자신의 특별한 케이지에서 비행 라이브 미니 드론, 경쟁 비디오 등이 있습니다.</p>


  <p><a href="https://www.microsoft.com/en-us/build/sessions" target="_blank">350개가 넘는 놀라운 기술 세션과 대화형 워크샵</a> 중에서 선택할 수 있으며 <a href="https://www.microsoft.com/en-us/build/speakers" target="_blank">수십 개의 영감을 주는 스피커</a>를 통해&rsquo; Microsoft Build에서 기술이 어디로 향하고 있는지, 어떻게 변환의 일부가 될 수 있는지를 더 깊이 이해하고 있습니다.</p>


  <p>이 모든 것과 드론도? 개발자 천국처럼 들립니다. 하지만 <a href="https://www.microsoft.com/en-us/build/?icid=azure_blog_drone_copy1" target="_blank">지금 Microsoft Build에 등록하는</a> 경우에만!</p>
