### YamlMime:Yaml
ms.openlocfilehash: f7075573cc67aa9ab3d8ee3ae9ef86f4e793b8f8
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139899581"
Slug: transparent-data-encryption-with-azure-key-vault-configuration-checklist
Title: '미리 보기: Azure Key Vault 구성 검사 목록을 사용하여 SQL Database 투명한 데이터 암호화'
Summary: Azure SQL Database 및 Data Warehouse는 데이터베이스, 로그 파일 및 백업을 포함하여 디스크에 기록된 모든 데이터에 대한 TDE(투명한 데이터 암호화)를 제공하여 미사용 암호화를 제공합니다.
Content: >-
  <p>Azure SQL Database 및 Data Warehouse는 데이터베이스, 로그 파일 및 백업을 포함하여 디스크에 기록된 모든 데이터에 대한 TDE(투명한 데이터 암호화)를 제공하여 미사용 암호화를 제공합니다. 이렇게 하면 하드웨어에 무단으로 액세스하는 경우 데이터를 보호합니다. TDE는 데이터를 암호화하는 데 사용되는 DEK(데이터베이스 암호화 키)를 암호화하는 데 사용되는 TDE 보호기를 제공합니다. TDE 보호기는 기본적으로 완전히 투명한 방식으로 서비스에서 관리되며, 90일마다 회전하며 백업에 액세스할 수 있도록 보관에 유지 관리됩니다. 필요에 따라 더 많은 제어가 필요한 경우 고객이 TDE 보호기를 관리할 수 있습니다. 이렇게 하려면 TDE 보호기를 고객 소유의 Azure Key Vault에 저장해야 합니다. 이 옵션을 선택하는 경우 모든 TDE 의미를 완전히 이해하고 진행 중인 키 관리를 신중하게 계획하는 것이 중요합니다.</p>


  <h2>고객 관리형 키 및 Azure Key Vault 통합을 이용한 TDE 개요:</h2>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/e027e31d-57fc-45ed-bb74-b34a7e013c56.png"><img width="624" height="247" title="이미지" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" alt="image" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/f55a7b0e-5bed-4989-8e90-53c5d2d68317.png" border="0"></a></p>


  <p>이 시나리오에서 고객은 Azure Key Vault를 유지하고, Azure Key Vault에 대한 SQL Database 권한을 제어하고, 모든 TDE 보호기에 대한 액세스를 유지 관리하여 데이터베이스 또는 백업을 열거나 복원하고, TDE 보호기에 대한 데이터베이스 액세스가 필요한 다른 모든 작업을 사용하도록 설정해야 합니다. 다음 검사 목록은 Azure Key Vault의 모든 키 관리 관련 업무를 체계적으로 계획하는 데 도움이 됩니다. 또한 Azure Key Vault에서 고객 관리형 키를 사용하여 TDE를 구성하기 위해 따라야 하는 가장 중요한 설정 고려 사항 및 구성 요구 사항을 나열합니다.</p>


  <h2>일반 지침:</h2>


  <ul>
   <li>Azure Key Vault와 Azure SQL Database는 동일한 테넌트에 있어야 합니다. 교차 테넌트 키 자격 증명 모음 및 서버 상호 작용은 지원되지 않습니다.</li>
   <li>필요한 리소스에 사용할 구독을 결정합니다. 나중에 구독 간에 서버를 이동하려면 BYOK를 사용하여 TDE를 새로 설정해야 합니다.</li>
   <li>BYOK 기반 TDE를 구성하는 경우 반복되는 래핑/래핑 해제 작업을 통해 자격 증명 모음에 배치되는 로드를 고려해야 합니다. 예를 들어 논리 서버와 연결된 모든 데이터베이스에서 동일한 TDE 보호기를 사용하므로 해당 서버의 장애 조치는 서버에 있는 데이터베이스만큼 자격 증명 모음에 대한 많은 키 작업을 트리거합니다. 우리가 경험한 내용과 <a href="https://docs.microsoft.com/en-us/azure/key-vault/key-vault-service-limits" target="_blank">키 자격 증명 모음 서비스 제한</a>에 설명된 내용에 따라, 자격 증명 모음의 TDE 보호기에 액세스할 때 일관적으로 고가용성을 보장할 수 있도록 단일 구독의 Azure Key Vault 하나에 표준 데이터베이스는 최대 500개, 프리미엄 데이터베이스는 최대 200개까지만 연결하는 것이 좋습니다.</li>
   <li>권장 사항: 온-프레미스에 TDE 보호기 복사본을 유지합니다. 이렇게 하려면 HSM 디바이스가 TDE 보호기를 로컬로 만들고 키 에스크로 시스템을 만들어 TDE 보호기의 로컬 복사본을 저장해야 합니다.</li>
  </ul>


  <h2>Azure Key Vault를 구성하기 위한 지침:</h2>


  <ul>
   <li><a href="https://docs.microsoft.com/azure/key-vault/key-vault-ovw-soft-delete" target="_blank">일시 삭제</a>를 사용하도록 설정된 키 자격 증명 모음(필수)을 사용하여 실수로 키 또는 키 자격 증명 모음을 삭제하는 시나리오의 경우 데이터 손실로부터 보호합니다.</li><ul><li>
  일시 삭제된 리소스는 복구되거나 제거되지 않는 한 90일 동안 보존됩니다.<br>
   </li><li>복구 및 제거 작업에는 키 자격 증명 모음 액세스 정책과 연결된 고유 권한이 있습니다.</li></ul>
   <li>Azure Active Directory(Azure AD) ID를 사용하여 SQL 서버에 키 자격 증명 모음에 대한 액세스 권한을 부여합니다. 포털 UI를 사용하는 경우 Azure AD ID가 자동으로 생성되고 키 자격 증명 모음 액세스 권한이 서버에 부여됩니다. PowerShell을 사용하여 이러한 단계를 올바른 순서로 개별적으로 완료해야 하며 확인해야 합니다. PowerShell을 사용하는 경우 자세한 단계별 지침은 <a href="https://docs.microsoft.com/en-us/sql/relational-databases/security/encryption/transparent-data-encryption-byok-azure-sql-configure" target="_blank">BYOK 기반 TDE 구성</a>을 참조하세요. 참고: Azure AD ID가 실수로 삭제되거나 키 자격 증명 모음의 액세스 정책을 사용하여 서버의 권한이 해지되면 서버는 키 자격 증명 모음에 대한 액세스 권한을 잃게 됩니다.</li>
   <li>모든 암호화 키에서 Azure Key Vault에서 감사 및 보고 사용: Key Vault는 다른 SIEM(보안 정보 및 이벤트 관리) 도구에 쉽게 삽입할 수 있는 로그를 제공합니다. OMS(Operations Management Suite) <a href="https://docs.microsoft.com/azure/log-analytics/log-analytics-azure-key-vault" target="_blank">Log Analytics</a>는 이미 통합된 서비스의 한 예입니다.</li>
   <li>암호화된 데이터베이스의 고가용성을 보장하려면 다른 지역에 두 개의 Azure Key Vault가 있는 하나의 논리 서버를 구성합니다.</li>
   <li>단일 SQL 데이터베이스의 고가용성을 위해 두 개의 키 자격 증명 모음을 구성하는 것이 좋습니다.</li></ul><p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/3d3eede2-dbe4-4512-87fa-9c665fefd15c.png"><img width="527" height="401" title="이미지" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" alt="image" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/0e7a26d6-a358-41c5-952d-5469da6c9436.png" border="0"></a></p><ul>
   <li>Backup-AzureKeyVaultKey cmdlet을 사용하여 암호화된 형식으로 키를 검색한 다음, Restore-AzureKeyVaultKey cmdlet을 사용하고 두 번째 지역에서 키 자격 증명 모음을 지정합니다.</li>
   <li>지역에서 복제된 데이터베이스의 경우 다음 AKV 구성이 필요합니다.
  </li></ul><p>&nbsp;<a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/7287e61e-3689-492f-9b3f-64ff6e4925c4.png"><img width="826" height="454" title="geo_DR_new_config" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" alt="geo_DR_new_config" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/257d2815-2bed-4fd8-9d42-14b67cea1264.png" border="0"></a></p><ul>
    <ul><li>지역에 하나의 키 자격 증명 모음이 있는 주 데이터베이스 및 지역에 하나의 키 자격 증명 모음이 있는 하나의 보조 데이터베이스가 있습니다.</li></ul>
    <ul><li>하나의 보조 데이터베이스가 필요하며 최대 4개의 보조 데이터베이스가 지원됩니다.</li></ul>
    <ul><li>보조 복제본(체인)은 지원되지 않습니다.</li></ul>
   </ul><p>
   </p><ul>
   <li>참고: 서버 ID를 할당할 때 보조 ID를 먼저 할당하고 기본 두 번째에 대한 ID를 할당합니다.</li></ul><h2>Azure Key Vault에 저장된 TDE 보호기(비대칭 키)를 구성하기 위한 지침:</h2>

  <ul>
   <li>로컬 HSM 디바이스에 암호화 키를 로컬로 만듭니다. Azure Key Vault에 저장할 수 있도록 비대칭 RSA 2048 키인지 확인합니다. 더 큰 키 크기는 현재 Azure SQL Database 지원되지 않습니다.</li>
   <li>키 에스크로 시스템에서 키를 에스크로합니다. </li>
   <li>암호화 키 파일(.pfx, .byok 또는 .backup)을 Azure Key Vault로 가져옵니다.
   <ul>
    <li>(참고: 테스트를 위해 Azure Key Vault를 사용하여 키를 만들 수 있지만 프라이빗 키는 키 자격 증명 모음을 떠날 수 없으므로 이 키를 에스크로할 수 없습니다. 키 손실(키 자격 증명 모음에서 실수로 삭제, 만료 등)으로 인해 데이터가 영구적으로 손실되므로 프로덕션 데이터를 암호화하는 데 사용되는 키는 항상 에스크로깅되어야 합니다.</li>
   </ul>
   </li>
   <li>만료 날짜가 없는 키를 사용하고 이미 사용 중인 키에 만료 날짜를 설정하지 마세요. 키가 만료되면 암호화된 데이터베이스는 TDE 보호기 액세스 권한을 잃게 되며 24시간 이내에 삭제됩니다.</li>
   <li>키를 사용하도록 설정되어 있고 가져오기, 키 래핑 및 키 래핑 해제 작업을 수행할 수 있는 권한이 있는지 확인합니다.</li>
   <li>Azure Key Vault에서 처음으로 키를 사용하기 전에 Azure Key Vault 키 백업을 만듭니다. <a href="https://docs.microsoft.com/en-us/powershell/module/azurerm.keyvault/backup-azurekeyvaultkey?view=azurermps-5.1.1" target="_blank">Backup-AzureKeyVaultKey</a> 명령에 대해 자세히 알아보세요.</li>
   <li>키가 변경될 때마다(예: ACL 추가, 태그 추가, 키 특성 추가) 새 백업을 만듭니다.</li>
   <li>데이터베이스가 원래 키로 계속 암호화되는 가상 로그 파일에 계속 액세스할 수 있도록 키를 회전할 때 키 자격 증명 모음에 이전 버전의 키를 유지합니다. 또한 데이터베이스에 대해 TDE 보호기가 변경되면 데이터베이스의 이전 백업이 최신 TDE 보호기를 사용하도록 업데이트되지 않습니다. 키 회전은 <a href="https://docs.microsoft.com/en-us/sql/relational-databases/security/encryption/transparent-data-encryption-byok-azure-sql-key-rotation" target="_blank">PowerShell을 사용하여 투명한 데이터 암호화 방지 프로그램 회전</a>에 나와 있는 지침에 따라 수행할 수 있습니다.</li>
   <li>서비스 관리 키로 다시 변경한 후에는 이전에 사용한 모든 키를 Azure Key Vault에 유지합니다. 이렇게 하면 Azure Key Vault에 저장된 TDE 보호기를 사용하여 데이터베이스 백업을 복원할 수 있습니다. 서비스 관리형 키를 사용하는 동안 필요한 모든 백업이 만들어질 때까지 TDE 보호기는 Azure Key Vault에서 유지 관리되어야 합니다. </li>
   <li><a href="https://docs.microsoft.com/en-us/powershell/module/azurerm.keyvault/backup-azurekeyvaultkey?view=azurermps-5.1.1" target="_blank">Backup-AzureKeyVaultKey</a>를 사용하여 이러한 키의 복구 가능한 백업 복사본을 만듭니다.</li>
   <li>데이터가 손실될 위험 없이 보안 인시던트 중에 잠재적으로 손상될 수 있는 키를 제거하려면 <a href="https://docs.microsoft.com/en-us/sql/relational-databases/security/encryption/transparent-data-encryption-byok-azure-sql-remove-tde-protector" target="_blank">잠재적으로 손상될 수 있는 키 제거</a>의 단계를 따릅니다.</li>
  </ul>


  <h2>요약</h2>


  <p>위의 검사 목록은 Azure Key Vault에서 고객 관리형 키로 Azure SQL Database TDE를 설정하기 전에 신중하게 고려하고 계획해야 하는 요구 사항을 지정합니다. 업데이트된 버전의 개요에서는 <a href="https://docs.microsoft.com/en-us/sql/relational-databases/security/encryption/transparent-data-encryption-byok-azure-sql" target="_blank">Azure Key Vault 설정 및 Azure Key Vault에 저장된 TDE 보호기 관리에 대한 권장 사항을</a> 공유합니다.</p>
