### YamlMime:Yaml
ms.openlocfilehash: b279a0969ee3b3e11089190ef438b2122eb1fe15
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139900153"
Slug: transitioning-mobile-apps-from-application-insights-to-hockeyapp
Title: Mobile Apps를 애플리케이션 Insights HockeyApp으로 전환
Summary: '오늘 모바일 및 데스크톱 앱 고객을 위한 업데이트를 발표합니다. 몇 가지 중요한 예정된 변경 내용과 변경이 발생하는 시기에 대해 알아봅니다. '
Content: >-
  <p>지난 11월 커넥트()에서 HockeyApp의 모바일 및 데스크톱 앱 개발자를 위한 노력을 집중할 것이라고 <a href="https://azure.microsoft.com/en-us/blog/deep-diagnostics-for-web-apps-with-application-insights/">발표</a>&rsquo;했습니다. <a href="https://hockeyapp.net/features/">HockeyApp</a>은 iOS, Android, OS X, Windows, Xamarin, Cordova 및 Unity와 같은 플랫폼에서 앱을 빌드하기 위한 모바일 DevOps 솔루션의 핵심 구성 요소입니다. <a href="https://azure.microsoft.com/en-us/services/application-insights/">Visual Studio Application Insights</a> 대화형 분석 및 기본 제공 인사이트를 사용하여 웹앱 및 서비스에 대한 시나리오를 검색, 심사 및 진단하는 데 계속 집중하고 있습니다.</p>


  <h2>HockeyApp으로 전환</h2>


  <p>오늘 모바일 및 데스크톱 앱 고객을 위한 업데이트를 발표합니다. HockeyApp에 대한 투자와 HockeyApp 고객으로부터의 긍정적인 피드백&rsquo;의 일환으로, 다음 목표 날짜로 애플리케이션 Insights 모바일 환경을 종료하기로 결정했습니다.</p>


  <ul>
      <li><strong>2016년 4월 15일:</strong> 애플리케이션 Insights iOS, Android, Windows Store 및 Windows Phone 대한 <u>새 앱 수락을 중지</u>합니다. 기존 앱은 Azure Portal에 계속 표시됩니다. 이 날짜가 되면 계측 키를 HockeyApp으로 전환하는 옵션을 제공합니다.</li>
      <li><strong>2016년 6월 15일:</strong> 애플리케이션 Insights iOS, Android, Windows Store 및 Windows Phone 앱에 대한 <u>데이터 표시를 중지</u>합니다. 대신 HockeyApp을 통해 이 데이터에 액세스할 수 있습니다. 이 날짜 이전에 계측 키를 HockeyApp으로 전환하지 않은 경우 HockeyApp 지원 팀과 함께 지원 요청을 열어야 합니다.</li>
  </ul>


  <p>모바일 앱용 현재 애플리케이션 Insights SDK의 사용자, 세션 및 사용자 지정 이벤트 데이터는 HockeyApp SDK와 호환되므로 2016년 6월 15일 이후에 계속 처리되므로 이전 버전의 앱에서 데이터가 손실되지 않습니다. 계측 키를 요약된 시간 범위에서 전환해야 합니다. 그렇지 않으면 최종 전환 날짜 이후에 HockeyApp에서 데이터를 볼 수&#39;없습니다.</p>


  <h2>HockeyApp으로 무엇을 얻을 수 있나요?</h2>


  <p>HockeyApp은 모바일 개발자를 위한 최고의 솔루션입니다. 빠른 무선 배포를 통해 모바일 앱을 배포할 수 있으며 Mobile DevOps 워크플로에 완벽하게 통합됩니다. Visual Studio Team Services 함께 모바일 앱의 개발, 관리 및 배달을 간소화할 수 있습니다.</p>


  <p>HockeyApp은 또한 피드백 기능을 통해 동급 최고의 충돌 보고 및 직접 사용자 참여를 제공합니다. 이제 새로운 <a href="https://hockeyapp.net/preseason/">HockeyApp 프리 시즌 프로그램을</a> 사용하여 사용자 및 세션 메트릭을 수집하고, 개발자 및 테스트 팀을 <a href="https://hockeyapp.net/blog/2016/02/25/azure-active-directory.html">Azure Active Directory</a> 연결하고, HockeySDK를 <a href="https://hockeyapp.net/blog/2016/02/15/hockeysdk-for-uwp-apps.html">UWP 앱</a>에 통합할 수 있습니다.</p>


  <p><iframe allowfullscreen="" frameborder="0" height="315" src="https://www.youtube.com/embed/gVEpupXd3W8" width="560"></iframe></p>


  <p>HockeyApp은 무료 제품을 제공하지만 Microsoft Azure 구독(Enterprise 계약 포함)을 사용하여 Visual Studio <a href="https://marketplace.visualstudio.com/subscriptions">Marketplace</a>를 통해 구매하는 것이 그 어느 때보다 쉬워졌습니다. 오늘 <a href="https://hockeyapp.net/pricing/">무료 HockeyApp을 시작하는</a> 것이 좋습니다!</p>


  <h2>결론</h2>


  <p>이러한 전환은 이전 전략의 전환점이며 몇 가지 추가 작업이 발생할 수 있습니다. 이러한 변화의 목표는 모바일 앱을 배포, 테스트, 모니터링 및 관리할 수 있는 최상의 환경을 제공하는 것입니다. HockeyApp은 이 환경을 제공하는 솔루션입니다.</p>


  <p>애플리케이션 Insights 및 HockeyApp 지원 팀은 최대한 원활하게 전환할 준비가 되었습니다. 추가 질문이나 문제가 있는 경우 <a href="https://support.hockeyapp.net/">문의하세요</a>. 우리는이 전환을 통해 당신을 지원하기를 기대합니다.</p>


  <p><strong>업데이트:</strong> Application Insights Mobile Apps에서 HockeyApp으로의 전환 계획을 발표한 이후, 애플리케이션 Insights 있지만 현재 HockeyApp에서 사용할 수 없는 기능에 대한 우려를 표명하는 고객의 피드백을 받았습니다. 피드백을 고려한 후 계획을 변경하기로 결정했습니다. HockeyApp은 모바일 앱에 대한 주요 제품이 될 것이지만, 고객이 디바이스 원격 분석에서 심층 분석을 액세스하고 수행할 수 있도록 하는 애플리케이션 Insights 중요한 기능을 제공할 것입니다. 이 Azure 블로그 <a href="https://azure.microsoft.com/en-us/blog/update-on-transitioning-mobile-apps-from-application-insights-to-hockeyapp/">게시물</a>의 세부 정보를 읽을 수 있습니다.</p>
