### YamlMime:Yaml
ms.openlocfilehash: 5e2ee416bbc984332c622c936209dd0784ec9e57
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139912344"
Slug: transforming-your-vmware-environment-with-microsoft-azure
Title: Microsoft Azure 사용하여 VMware 환경 변환
Summary: 오늘 Azure로 VMWare 마이그레이션의 모든 단계에서 도움이 되는 새로운 서비스를 발표합니다.
Content: >-
  <p><em>업데이트된 12/19: Azure의 VMware 가상화에 대한 이전 정보가 아래에서 제거되어 <a href="https://azure.microsoft.com/en-us/blog/vmware-virtualization-on-azure/">이 새 게시물</a>로 이동되었습니다.</em></p>


  <p>각 조직이 고유하듯이 각 조직은 클라우드에 대한 고유한 경로를 사용합니다. 데이터를 전송하거나, 인프라를 마이그레이션하거나, 애플리케이션을 현대화하거나, 새 앱을 빌드하는 경우 Azure를 사용하면 필요에 가장 적합한 방식으로 클라우드로 이동할 수 있습니다.</p>


  <p>이 과정의 일환으로 자주 듣는 한 가지 요청은 기존 온-프레미스 VMware 워크로드를 Azure로 이동하려는 것입니다. 여기에는 VMware 기반 애플리케이션을 Azure로 마이그레이션하고 Azure와 통합하는 것이 포함됩니다.&nbsp;</p>


  <h2>VMware 환경을 위한 Azure에 대한 마찰 없는 경로</h2>


  <p>오늘 Azure로 VMware 마이그레이션의 모든 단계에서 도움이 되는 새로운 서비스를 발표합니다.</p>


  <ul>
   <li><strong>Azure Migrate를 사용하여 애플리케이션을 마이그레이션합니다.</strong> <em>11월 27일에는 무료 서비스인 Azure Migrate가 모든 Azure 고객에게 광범위하게 제공됩니다.</em> 대부분의 클라우드 공급업체는 단일 서버 마이그레이션 기능을 제공하지만 Azure Migrate는 다음 단계에서 전체 다중 서버 애플리케이션을 마이그레이션하는 과정을 안내합니다.&nbsp;</li>
  </ul>


  <p style="margin-left: 40px;"><em>검색 및 평가.</em> <a href="https://aka.ms/azuremigrateproductpage" target="_blank">Azure Migrate</a> 는 VMware 환경을 변경하지 않고도 온-프레미스 VMware 기반 애플리케이션을 검색할 수 있습니다. Azure Migrate는 다중 VM 애플리케이션에서 그룹 수준 종속성을 시각화하는 고유한 기능을 제공하므로 마이그레이션을 위해 전체 애플리케이션을 논리적으로 그룹화하고 우선 순위를 지정할 수 있습니다. CPU, 메모리, 디스크 및 네트워크의 사용률 검색을 통해 Azure Migrate는 크기 및 비용 지침을 제공하기 위한 기본 제공 권한도 제공하므로 마이그레이션할 때 비용을 절감할 수 있습니다.</p>


  <p><img alt="VMWare" border="0" height="508" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/cb828f68-53fd-46af-b1e4-4161745b0389.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="VMWare" width="1024"></p>


  <p align="center"><em>Azure Migrate를 사용하여 전체 애플리케이션 종속성을 고유하게 시각화</em></p>


  <p style="margin-left: 40px;"><em>마이그레이션</em> 검색이 완료되면 몇 번의 클릭만으로 온-프레미스 애플리케이션을 Azure로 마이그레이션할 수 있습니다. ASR(Azure Site Recovery)을 사용하면 고객이 가동 중지 시간을 최소화하면서 VMware 가상화된 Windows Server 및 Linux 워크로드를 <a href="https://docs.microsoft.com/en-us/azure/site-recovery/tutorial-migrate-on-premises-to-azure" target="_blank">마이그레이션</a>할 수 있습니다. ASR은 애플리케이션 중심 마이그레이션을 제공하므로 마이그레이션할 때 애플리케이션 서버를 시퀀싱할 수 있습니다. 다른 클라우드 공급자는 이 기본 제공 다중 계층 시퀀싱을 제공하지 않습니다. 또한 Azure Database Migration Service를 사용하면 고객이 SQL Server 및 Oracle 데이터베이스를 완전히 관리되는 Azure SQL Database 직접 마이그레이션할 수 있습니다. 대용량 스토리지 마이그레이션이 필요한 고객을 위해 최근에 Azure로의 데이터 이동을 간소화하도록 설계된 어플라이언스인 Azure <a href="https://azure.microsoft.com/en-us/services/storage/databox/" target="_blank">Data Box</a>를 발표했습니다.</p>


  <p style="margin-left: 40px;"><em>리소스 &amp; 비용 최적화.</em> Azure에 배포된 후 무료 <a href="https://azure.microsoft.com/en-us/services/cost-management/" target="_blank">Azure Cost Management</a> 서비스(이전의 Cloudyn)를 사용하여 지출을 쉽게 예측, 추적 및 최적화할 수 있습니다. 계산은 특정 온-프레미스 VMware에서 Azure로의 마이그레이션 시나리오에 대해 최대 84%의 TCO 절감액을 표시합니다. 이 <a href="https://aka.ms/vmwazuretco" target="_blank">VMware를 Azure TCO 가이드에</a> 참조하여 자세히 알아보고 <a href="https://tco.microsoft.com/" target="_blank">TCO 계산을</a> 직접 실행할 수도 있습니다. 예를 들어, <a href="https://customers.microsoft.com/en-us/story/capstone-mining" target="_blank">Capstone Mining</a> 은 이 여정을 거쳤으며 이미 $6M의 자본 및 운영 비용을 절감했습니다.</p>


  <ul>
   <li><strong>Azure 서비스와 VMware 워크로드를 통합합니다.</strong> 마이그레이션 또는 배포 없이 VMware 워크로드와 함께 사용할 수 있는 많은 Azure 서비스가 있으므로 클라우드 및 온-프레미스에서 전체 환경을 안전하고 잘 관리할 수 있습니다. 여기에는 Azure Backup, Azure Site Recovery(재해 복구용), 업데이트/구성 관리, Azure Security Center 및 Azure Log Analytics를 사용하는 운영 인텔리전스가 포함됩니다. VMware vRealize Automation 콘솔을 사용하여 퍼블릭 클라우드에서 Azure 리소스를 관리할 수도 있습니다. <a href="https://customers.microsoft.com/en-us/story/somerset-county-council-local-government" target="_blank">서머셋 카운티 위원회</a> 및 <a href="https://customers.microsoft.com/en-us/story/russell-reynolds-and-attunix" target="_blank">러셀 레이놀즈 어소시에이츠는</a> Azure 서비스를 VMware VM과 통합한 예제 고객입니다.&nbsp;</li>
  </ul>


  <p>Azure로 마이그레이션하는 데 도움이 되는 몇 가지 리소스는 다음과 같습니다.</p>


  <ul>
   <li>VMware에서 Azure로 이동하기 위한 잠재적 절감액을 간략하게 설명하는 <a href="https://aka.ms/vmwazuretco" target="_blank">TCO 문서</a></li>
   <li><a href="https://turbonomic.com/solutions/technologies/azure-cloud/" target="_blank">Turbonomic</a>, <a href="https://www.movere.io/product/" target="_blank">Movere</a> 및 <a href="https://www.cloudamize.com/" target="_blank">Cloudamize</a>와 같은 도구, 지침 및 권장 마이그레이션 기술 파트너가 포함된 <a href="https://azure.microsoft.com/migrate/" target="_blank">Azure Migration Center</a></li>
   <li><a href="https://azure.microsoft.com/campaigns/vmw-to-azure/" target="_blank">VMware에서 Azure로 마이그레이션 시나리오에</a> 대한 추가 정보&nbsp;</li>
   <li><a href="https://www.pluralsight.com/courses/microsoft-azure-vms-vmware-vsphere-admins" target="_blank">VMware vSphere 관리자 과정용</a> 무료 온라인 Azure</li>
   <li>11월 28일 오전 10시 PST에서 <a href="https://info.microsoft.com/Running-VMWare-on-Azure-Webinar.html" target="_blank">웹캐스트</a>를 통해 오늘&rsquo; 공지 사항에 대한 자세한 정보를 공유합니다.</li>
  </ul>


  <h2>마이그레이션 외</h2>


  <p>많은 사용자가 비즈니스가 더 빠르게 이동할 수 있도록 클라우드로 이동하려고 합니다. Azure는 애플리케이션을 제공하고 크기를 조정하는 데 도움이 되는 보안, 안정성 및 글로벌 규모를 제공합니다. 동시에 클라우드에서 전체 비즈니스를 실행하지 못할 수도 있음을 이해합니다. 일부 애플리케이션을 하이브리드 방식으로 온-프레미스에서 실행해야 하는 대기 시간, 규정 또는 규정 준수 요구 사항이 낮을 수 있습니다. 실제로 클라우드에서 VMware 가상화 스택을 실행해도 하이브리드 요구 사항이 해결되지 않습니다.&nbsp; 이를 위해서는 연결 및 가상화뿐만 아니라 클라우드 및 온-프레미스 환경에서 진정한 일관성을 제공하는 광범위한 하이브리드 서비스 및 솔루션 집합이 필요합니다.&nbsp;&nbsp;</p>


  <p>Azure는 애플리케이션 개발, 관리, 보안, 데이터 및 ID에서 일관성을 유지하는 유일한 진정한 <a href="https://azure.microsoft.com/en-us/overview/hybrid-cloud/?wt.mc_id=AID601064_QSG_BNR_156079" target="_blank">하이브리드 클라우드</a> 입니다. 클라우드 및 온-프레미스 서버의 패치, 구성 및 모니터링을 통해 Azure Stack, Azure Backup, Azure Site Recovery, Azure Security Center, SQL Server Stretch DB, Azure Active Directory 및 하이브리드 관리와 같은 다양한 제품 집합을 사용할 수 있습니다. 다른 클라우드는 이러한 수준의 포괄적인 하이브리드 기능을 제공하지 않습니다.</p>


  <p>Microsoft는 사용자의 요구 사항과 클라우드 여정에 상관없이 Azure를 간단하게 만드는 도구, 솔루션 및 서비스에 투자하기 위해 최선을 다하고 있습니다. 클라우드 스토리에 대한 자세한 내용을 듣기 위해 기다릴 수&rsquo; 없어.</p>


  <p>감사합니다,</p>


  <p>코리 샌더스</p>
