### YamlMime:Yaml
ms.openlocfilehash: 8378a56e4fe7526eac93861e3d63e9121e404a74
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139908009"
Slug: troubleshooting-common-configuration-issues-with-azure-backup
Title: Azure Backup의 일반적인 구성 문제 해결
Summary: 이 블로그 게시물은 Microsoft Cloud Backup 솔루션인 Azure Backup과 관련된 일반적인 구성 문제를 해결하는 데 도움이 됩니다. 고객은 일반적으로 Azure Backup 설치 또는 등록 시 해당 고객이 발생합니다.
Content: >-
  이 블로그 게시물은 Microsoft Cloud Backup 솔루션인 Azure Backup과 관련된 일반적인 구성 문제를 해결하는 데 도움이 됩니다. 고객은 일반적으로 Azure Backup 설치 또는 등록 시 해당 고객이 발생합니다. 다음은 문제를 진단하고 해결하는 방법에 대한 제안입니다.


  <strong> </strong>

  <h3>"선택한 설치 폴더에 잘못된 특성이 지정됨"으로 Azure Backup 설치가 실패합니다.</h3>

  'System, Hidden, Compressed 또는 Encrypted' 특성이 설정된 폴더에 Azure Backup 에이전트를 설치하려고 하면 "선택한 설치 폴더에 잘못된 특성이 지정됨" 메시지가 표시됩니다.

  설치 폴더에서 시스템 또는 숨김 또는 압축 또는 암호화 특성을 제거하세요. 다음은 폴더의 속성을 제거하는 방법에 대한 단계별 가이드입니다.

  <ol>
   <li> 암호화 특성을 제거하려면 Windows" href="https://support.microsoft.com/kb/308993"> Windows 파일 및 폴더 암호화에서 </a>KB 문서 <a title="제거 파일 및 폴더 암호화를 참조하세요. 이 단계는 서버에도 적용할 수 있습니다.</li>
   <li>폴더의 압축된 특성을 제거하는 압축 해제 폴더에서 TechNet 설명서, <a title="폴더 및 파일" href="https://technet.microsoft.com/en-us/library/cc976811.aspx"> 압축 해제 및 압축 해제 폴더 및 파일 </a>압축 해제를 참조하세요.</li>
   <li>TechNet 설명서인 <a title="Attributes VolumeAttributes" href="https://technet.microsoft.com/en-us/library/gg252643.aspx"> Volume</a>을 참조하여 폴더에서 숨겨진/읽기 전용 특성을 제거하세요.</li>
   <li>Azure Backup 설치 폴더 위치에 시스템 특성이 있는 경우 새 폴더를 만들고 새 폴더 위치에 Azure 백업을 설치하세요.</li>
  </ol>

  <strong>

  </strong>

  <h3>"잘못된 자격 증명 모음 자격 증명이 제공됨"으로 Azure Backup 등록이 실패합니다. 파일이 손상되었거나 복구 서비스와 연결된 최신 자격 증명이 없습니다."</h3>

  잘못된 시간 설정으로 서버를 등록하려고 하면 아래 오류 메시지가 표시될 수 있습니다.


  <img alt="Invalid vault credentials provided. The file is either corrupted or does not have the latest credentials associated with recovery service. (ID: 34513) We recommend you download a new vault credentials file from the portal and use it within 2 days." src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/RegistrationError.png" width="519" height="188" />


  "날짜 및 시간 설정 변경..."을 사용하여 시간을 다시 설정하세요. 서버를 다시 시작합니다.다음은 문제를 해결하기 위한 자세한 지침입니다.

  <ol>
   <li>시계" href="https://windows.microsoft.com/en-us/windows/set-clock#1TC=windows-7"> 집합 설정 아티클</a>을 참조하여 <a title="날짜 및 시간 설정을 업데이트하세요.</li>
   <li>현지 표준 시간대 및 옷장 시간 설정과 일치하는지 확인하세요.</li>
   <li>서버를 다시 시작하여 서버의 등록 상태를 새로 고칩니다. <strong>서버를 다시 시작해야 합니다. 이는 놓칠 수 있는 일반적인 단계입니다</strong>.</li>
   <li>Azure Backup 서비스에 서버를 등록합니다.</li>
  </ol>

  &nbsp;

  <h3>"인증 서비스와 통신할 수 없습니다."라는 오류 메시지와 함께 Azure Backup 작업이 실패합니다.</h3>

  프록시 뒤에 있는 서버를 작동하려고 하면 "인증 서비스와 통신할 수 없음"이 발생할 수 있습니다.

  올바른 프록시 주소를 설정해야 합니다. 또한 프록시가 인증된 프록시인 경우 사용자 이름 및 암호를 지정합니다. 다음은 Azure Backup에 대한 프록시 서버 주소를 설정하는 방법에 대한 단계별 지침입니다.

  <ol>
   <li>Windows Azure Backup 에이전트 UI를 엽니다.<img alt="Azure Backup UI with Change Properties link on the right hand side." src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/AzureBackupUI-636x356.png" width="636" height="356" /></li>
   <li>작업 탭에서 "속성 변경" 링크를 클릭합니다.                                         <img alt="Azure Backup Proxy Configuration" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/AzureBackupProxySettings-380x369.png" width="380" height="369" /></li>
   <li>프록시 주소 및 포트를 제공합니다. 인증된 프록시인 경우 사용자 이름 및 암호를 지정합니다.                                                                                                                                            <img alt="Azure Backup Proxy Setting Username" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/AzureBackupProxyUserName.png" width="373" height="217" /></li>
   <li>"확인"을 클릭합니다. 이제 서버는 지정된 프록시 세부 정보를 사용하여 Azure Backup 서비스와 통신할 수 있습니다.</li>
  </ol>

  &nbsp;


  &nbsp;


  Azure Backup과 관련된 일반적인 문제를 해결하는 데 도움이 되기를 바랍니다. Azure Backup에 대한 자세한 도움말을 보려면 Azure Backup 지원 옵션이 여기에 설명되어 있습니다. <a href="https://azure.microsoft.com/en-us/support/options/">https://azure.microsoft.com/en-us/support/options/</a>

  <ul>
   <li><a title="Azure Backup 기술 및 청구 지원" href="https://manage.windowsazure.com/?getsupport=true">  기술 및 청구 지원</a></li>
   <li><a title="Azure Backup 지원 LinkForum" href="https://social.msdn.microsoft.com/Forums/windowsazure/en-US/home?forum=windowsazureonlinebackup&amp;filter=alltypes&amp;sort=lastpostdesc">  지원</a></li>
  </ul>

  &nbsp;


  &nbsp;


  &nbsp;


  &nbsp;
