### YamlMime:Yaml
ms.openlocfilehash: f6b3ac2ce08b749d12d462fc40ee95d02f7c5af8
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139900130"
Slug: understand-your-sharepoint-usage-with-application-insights-2
Title: 애플리케이션 Insights SharePoint 사용량 이해
Summary: 이제 Application Insights 사용하면 SharePoint 사이트의 사용 및 성능에 대한 빠르고 강력한 인사이트를 쉽게 얻을 수 있습니다.
Content: >-
  SharePoint 기반 사이트 및 웹 애플리케이션은 Enterprise 수준에서 매우 인기가 있습니다.이제 <a href="https://azure.microsoft.com/en-us/services/application-insights/">Application Insights</a> 사용하면 SharePoint 사이트의 사용 및 성능에 대한 빠르고 강력한 인사이트를 쉽게 얻을 수 있습니다. <a href="https://azure.microsoft.com/en-us/services/application-insights/">애플리케이션 Insights</a> Azure <a href="https://portal.azure.com/">Portal</a>에 원격 분석을 보내는 웹 페이지의 앱 또는 클라이언트 쪽 Java 스크립트 코드에 SDK를 추가하여 작동합니다. 지원되는 플랫폼, 언어 및 IDE의 여러 조합에 대해 서로 다른 <a href="https://github.com/Microsoft/AppInsights-Home">SDK</a> 가 있습니다.

  <h2>시작</h2>

  먼저 <a href="https://azure.com/">Microsoft Azure</a> 계정이 필요합니다. 이미 조직을 통해 그룹 계정에 액세스할 수 있거나 종량제 계정을 가져올 수 있습니다. (Application Insights 미리 보기 상태이지만 무료입니다.)

  <h3>Microsoft Azure 애플리케이션 Insights 리소스 가져오기</h3>

  <ul>
   <li><a href="https://azure.com/">Microsoft Azure</a> 등록하고 <a href="https://portal.azure.com/">미리 보기 포털</a>로 이동하여 애플리케이션 Insights ASP.NET 리소스를 추가합니다.</li>
   <li>SharePoint 페이지에 추가할 애플리케이션 Insights 웹 클라이언트 코드 가져오기</li>
  </ul>

  &nbsp;


  <a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/GetStarted.png"><img class="alignnone size-full wp-image-276841" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/GetStarted.png" alt="GetStarted" width="924" height="500" /></a> <a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/GetAppInsightsCode.png"><img class="alignnone size-full wp-image-276851" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/GetAppInsightsCode.png" alt="GetAppInsightsCode" width="574" height="471" /></a>

  <h2>SharePoint 페이지에 애플리케이션 Insights 클라이언트 코드 추가</h2>

  클라이언트 코드에 쉽게 추가할 수 있는 두 가지 방법이 있습니다.


  1) 마스터 페이지에 액세스할 수 있는 경우 이 방법을 사용하는 것이 좋습니다. 그러면 기본적으로 모든 페이지에 대한 원격 분석이 표시됩니다.

  <ul>
   <li>시애틀에 코드를 추가합니다. 마스터 페이지</li>
   <li>SharePoint Designer 또는 원하는 다른 편집기를 사용하여 마스터 페이지를 체크 아웃합니다.</li>
   <li>첫 번째 단계에서 복사한 코드 조각을 닫 &lt;는 /head&gt; 태그 앞에 삽입합니다.</li>
  </ul>

  &nbsp;


  <a href="https://acom.azurecomcdn.net/80C57D/blogmedia/blogmedia/2015/04/16/SharepointMasterPage.png"><img class="alignnone size-large wp-image-276891" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/SharepointMasterPage-340x369.png" alt="SharepointMasterPage" width="340" height="369" /></a><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/AddAppInsightsCode.png"><img class="alignnone size-full wp-image-276881" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/AddAppInsightsCode.png" alt="AddAppInsightsCode" width="785" height="367" /></a>


  2)  웹 파트를 삽입하고 코드 조각을 포함하면 애플리케이션 Insights 코드 조각을 개별 페이지에 추가할 수 있습니다(마스터 페이지에 대한 액세스 권한이 없는 경우).


  <a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/EmbedAppInsightsCode.png"><img class="alignnone size-full wp-image-276871" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/EmbedAppInsightsCode.png" alt="EmbedAppInsightsCode" width="513" height="647" /></a>


  이제 SharePoint 사이트에 대한 강력한 인사이트를 볼 준비가 되었습니다!

  <h2>애플리케이션 Insights 사용하여 SharePoint 사용 현황 보기</h2>

  SharePoint 사용량을 검토할 준비가 되면 <a href="https://portal.azure.com/">미리 보기 포털</a>로 이동하여 첫 번째 단계에서 만든 애플리케이션 Insights 리소스로 이동합니다. 애플리케이션 Insights 사용 현황 분석은 사용자, 세션 및 페이지 보기의 빠른 스냅샷을 제공합니다.


  <a href="https://acom.azurecomcdn.net/80C57D/blogmedia/blogmedia/2015/04/16/Users1.png"><img class="alignnone size-medium wp-image-276911" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/Users1-338x369.png" alt="Users1" width="338" height="369" /></a> <a href="https://acom.azurecomcdn.net/80C57D/blogmedia/blogmedia/2015/04/16/PageViews1.png"><img class="alignnone size-medium wp-image-276921" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/PageViews1-264x369.png" alt="PageViews1" width="264" height="369" /></a>


  애플리케이션 Insights 진단 검색을 사용하면 페이지 보기에 대한 원시 데이터를 가져올 수 있습니다.


  <img class="alignnone size-medium wp-image-276901" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/Search1-584x369.png" alt="Search1" width="584" height="369" />

  <h2>요약</h2>

  애플리케이션 Insights 사용하면 다양한 차원으로 메트릭을 조각화하고 받아쓰기하여 <a href="https://blogs.msdn.com/b/visualstudioalm/archive/2014/12/15/application-insights-metric-explorer-me-part-2.aspx">고유한 인사이트를 만들</a> 수 있으며 마스터 페이지에 간단한 코드 조각을 삽입하기만 하면 됩니다.


  이제 애플리케이션 Insights <a href="https://azure.microsoft.com/en-us/documentation/articles/app-insights-get-started/">시작하여</a> SharePoint 사이트/애플리케이션 성능, 사용량 및 가용성을 분석합니다.
