### YamlMime:Yaml
ms.openlocfilehash: 9fe96e1af5d8c3fa7fd67abf28f6f3196369de2c
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139897156"
Slug: unified-proactive-diagnostics-in-application-insights
Title: Application Insights 통합 사전 진단
Summary: 다양한 유형의 자동 관리 검색 경고에 대한 사용자 환경을 통합하고 있습니다.
Content: >-
  <p>다양한 유형의 자동 관리 검색 경고에 대한 사용자 환경을 통합하고 있습니다. 지금까지 애플리케이션 Insights Visual Studio 이러한 전자 메일에 익숙할 것입니다. 오류율의 급격한 인상, 요청 성능의 이상 또는 페이지 로드 시간과 같은 애플리케이션의 문제에 대해 자동으로 가져옵니다. 실제로 몇 가지 유형의 사전 예방적 검색이 있습니다. 그러나 이제&rsquo;는 단순화된 것들을 소비하는 다양한 방법을 기억할 필요가 없습니다&rsquo;.</p>


  <h1>전자 메일 모양</h1>


  <p>이제 모든 자동 관리 경고 알림의 모양이 비슷합니다. 그들은 문제가 무엇인지뿐만 아니라 그것을 일으킬 수있는 것에 대한 몇 가지 관련 정보를 제공합니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/6acc6c09-ec80-4e7e-8f21-ed3a2219f115.png"><img alt="" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/4f35e305-4883-46c2-aa69-ed6e8e6662ba.png" style="border-width: 0px; padding-top: 0px; padding-left: 0px; margin-left: auto; display: block; padding-right: 0px; margin-right: auto; width: 425px; height: 390px; background-image: none;" title=""></a></p>


  <h1>검색 검토</h1>


  <p>선택한 기간 내에 모든 자동 관리 검색을 검토하기 위해 포털에서&rsquo; 단일 보기인 자동 관리 검색 블레이드가 표시됩니다. 애플리케이션 Insights 개요 블레이드-&gt;자동 관리 검색 타일 또는 전자 메일 알림-&gt; 파란색 단추에서 블레이드에 액세스하여 문제를 추가로 조사할 수 있습니다. 자동 관리 검색 블레이드에 나열된 각 검색에서 특정 검색 세부 정보로 드릴다운하고 조사를 시작할 수 있습니다.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<br>

  &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/fb032be4-0748-44eb-bc54-a79b658b6759.png"><img alt="" border="0" height="962" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/dfdf17b9-1d7e-4cac-a2d7-5516b7f727ea.png" style="border-left-width: 0px; border-right-width: 0px; background-image: none; border-bottom-width: 0px; float: none; padding-top: 0px; padding-left: 0px; margin-left: auto; display: block; padding-right: 0px; border-top-width: 0px; margin-right: auto" title="" width="750"></a></p>


  <p>이렇게 하면 애플리케이션에서 사전에 식별된 문제에 대한 전체적인 보기를 수신하고, 심사하고, 근본 원인을 식별하고, 검색된 문제에 접근하는 방법에 대한 결정을 지원하기 위해 더 많은 데이터를 제공할 수 있습니다.</p>


  <h1>자동 관리 검색 유형</h1>


  <p>세 가지 유형의 사전 예방적 검색이 있습니다.</p>


  <h2>1. 비정상적인 동작</h2>


  <p>위치, 브라우저, 클라이언트 OS, 서버 인스턴스, 하루 중 시간 등의 속성과 이러한 문제를 상호 연결하여 매일 비정상적인 패턴을 검색하여 다음 사항에 초점을 맞춘 검색을 제공합니다.<br>

  &bull;&nbsp;&nbsp;&nbsp; HTTP 요청의 느린 응답<br>

  &bull;&nbsp;&nbsp;&nbsp; 앱에서 수행한 호출에 대한 종속성의 느린 응답<br>

  &bull;&nbsp;&nbsp;&nbsp; 느린 페이지 로드<br>

  &bull;&nbsp;&nbsp;&nbsp; 높은 실패한 요청 속도</p>


  <p><a href="https://azure.microsoft.com/en-us/documentation/articles/app-insights-proactive-detection/">자세한 정보</a></p>


  <h2>2. 근 실시간 오류 경고</h2>


  <p>기계 학습을 사용하여 앱에 대해 실패한 요청의 예상 비율을 설정하고 로드 및 다른 요소와 상관 관계를 지정합니다. 실패율이 예상된 범위를 벗어나는 경우 경고를 보냅니다.<br>

  &bull;&nbsp;&nbsp;&nbsp; 요청 실패율이 비정상적으로 증가합니다.</p>


  <p><a href="https://azure.microsoft.com/en-us/documentation/articles/app-insights-nrt-proactive-diagnostics/">자세한 정보</a></p>


  <h2>3. Azure 클라우드 서비스 검색</h2>


  <p><a href="https://azure.microsoft.com/en-us/documentation/articles/app-insights-cloudservices/">Azure 클라우드 서비스에 애플리케이션 Insights 적용하면 이러한 항목이 표시됩니다</a>.<br>

  &bull;&nbsp;&nbsp;&nbsp; 역할 인스턴스 시작 실패 및 중단<br>

  &bull;&nbsp;&nbsp;&nbsp; 역할 인스턴스 자주 재활용<br>

  &bull;&nbsp;&nbsp;&nbsp; 역할 인스턴스 런타임 충돌</p>


  <p><a href="https://azure.microsoft.com/en-us/blog/proactive-notifications-on-cloud-service-issues-with-azure-diagnostics-and-application-insights/">자세한 정보</a></p>


  <h2>4. 향후 도입될 추가 자동 관리 검색 유형&hellip;</h2>


  <h2>&nbsp;</h2>


  <h3>출시 예정: 통합 구성 환경이므로 계속 지켜봐 주시기 바랍니다.&hellip;</h3>


  <p>&nbsp;</p>


  <p><u>다음을 알려주세요.</u></p>


  <p>질문이나 피드백은 <a href="https://social.msdn.microsoft.com/Forums/en-US/home?forum=ApplicationInsights">애플리케이션 Insights 포럼</a>을 방문하세요.<br>

  모든 기능 요청은 <a href="https://visualstudio.uservoice.com/forums/357324">사용자 의견 사이트를</a> 방문하세요.</p>


  <p>&nbsp;</p>
