### YamlMime:Yaml
ms.openlocfilehash: 6282165fc60f6b9b6b390dd05df5a0155d8acb37
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139897104"
Slug: update-on-transitioning-mobile-apps-from-application-insights-to-hockeyapp
Title: 애플리케이션 Insights HockeyApp으로 Mobile Apps 전환 업데이트
Summary: 'Visual Studio 애플리케이션 Insights Mobile Apps에서 HockeyApp으로의 전환 계획을 발표한 이후, Hockey 앱에서 누락된 기능에 대한 우려를 표명하는 고객의 피드백을 받았습니다. '
Content: >-
  <p><a href="https://azure.microsoft.com/services/application-insights/">Visual Studio 애플리케이션 Insights</a> Mobile Apps에서 <a href="https://www.hockeyapp.net/features/">HockeyApp</a>으로<a href="https://azure.microsoft.com/blog/transitioning-mobile-apps-from-application-insights-to-hockeyapp/">의 전환 계획을</a> 발표한 이후, 애플리케이션 Insights 있지만 현재 HockeyApp에서 사용할 수 없는 기능에 대한 우려를 표명하는 고객의 피드백을 받았습니다. 피드백을 고려한 후 계획을 변경하기로 결정했습니다. HockeyApp은 모바일 앱에 대한 주요 제품이 될 것이지만, Microsoft는 Application Insights 중요한 기능을 제공하며, 이를 통해 사용자는 심층 분석 온&nbsp;데빅 원격 분석에 액세스하고 수행할 수&nbsp; 있습니다. 이는 서비스 및 디바이스 원격 분석 데이터&nbsp; 인 애플리케이션 &ndash; Insights 상관 관계 및 분석을 통해 솔루션 전체에서 분석할 수 있도록 하는 목표를&nbsp; 향한 초기 단계입니다.</p>


  <p>특히 변경 내용은 다음과 같습니다.</p>


  <ul>
      <li>애플리케이션 Insights iOS, Android 및 모든 Windows&nbsp; 적용에 대한 디바이스 유형&rdquo; 애플리케이션을 계속 지원&ldquo;합니다. 기존 모바일 앱에 애플리케이션 Insights 계속 사용할 수 있으며 곧 새 앱을 만들 수 있습니다. <a href="https://blogs.msdn.microsoft.com/bharry/2016/03/28/introducing-application-analytics/">분석 </a>및 &ldquo;<a href="https://azure.microsoft.com/en-us/documentation/articles/app-insights-export-telemetry/">연속 내보내기</a>&quot; 기능은 애플리케이션 Insights 디바이스 유형&rdquo; 앱에 대해 지원&ldquo;됩니다. 애플리케이션 Insights 디바이스 유형&quot; 애플리케이션에 대해 현재 사용하지 않도록 설정된 &quot;분석 기능은 곧&nbsp; 이러한 앱에 대해 사용하도록 설정될 예정입니다.</li>
      <li><a href="https://blogs.msdn.microsoft.com/bharry/2016/03/28/introducing-application-analytics/">Analytics를</a> 사용하면 HockeySDK에서 공급되는 디바이스 원격 분석에 대해 심층 분석을 수행할 수 있습니다. 애플리케이션 Insights SDK도 제한된 시간 동안 계속 지원됩니다. 호환되는 버전을 사용할 수 있게 되면 HockeySDK로 전환하는 것이 좋습니다. 이러한 새 버전은 가용성 날짜에 가깝게 발표될 예정입니다.</li>
      <li>검색, 드릴다운, 사용자 지정 차트, 대시보드 등 분석 및 연속 내보내기 이외의 Azure Portal 환경의 다른 모든 현재 기능은 더 이상 사용할 수 없습니다. 크래시 분석은 HockeyApp에서만 사용할 수 있습니다.</li>
      <li>나중에 분석에 추가된 새로운 기능(예: 대시보드, 모바일 및 웹앱에서 데이터 조인 등)은 디바이스 유형&rdquo; 앱에 &ldquo;사용할 수 있어야 합니다.</li>
      <li>애플리케이션 Insights HockeyApp에 &ldquo;디바이스 유형&quot; 앱을 연결하는 &quot;&rdquo; 기능을 곧 사용하도록 설정할 예정입니다. 이는 현재 제공된 HockeyApp&rdquo;으로의 전송 함수를 대체&ldquo;합니다. 앱을 연결&rdquo;하면 &ldquo;HockeyApp에 동급 최고의 크래시 보고 및 피드백 기능을 통해 직접 사용자 참여와 같은 HockeyApp 기능을 활용할 수 있는 앱이 있습니다.</li>
      <li>기한을 연장했으며 기존 모바일 앱은 현재 애플리케이션 Insights 7월 15<sup>일까지</sup> 계속 작동합니다. 7월 15<sup>일</sup> 이후에는 애플리케이션 Insights 이러한 앱에 대해 앞에서 언급한 기능만 사용하도록 설정됩니다.</li>
  </ul>


  <p>향후 몇 주 안에 자세한 내용을 발표할 예정입니다. 그 동안 애플리케이션 Insights 모바일 앱을 계속 사용하세요. 이제 HockeyApp 및 애플리케이션 Insights 최대한 활용할 수 있습니다.</p>
