### YamlMime:Yaml
ms.openlocfilehash: 86854fd8e5f21aa8b886fe9261ed59476608b7c1
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139906391"
Slug: use-new-relic-one-to-effortlessly-monitor-applications-in-azure-spring-cloud
Title: New Relic One을 사용하여 Azure Spring Cloud에서 애플리케이션을 손쉽게 모니터링
Summary: 오늘 Azure Spring Cloud에서 New Relic One 성능 모니터링의 통합을 발표합니다. 지난 18개월 동안 많은 엔터프라이즈 고객과 협력하여 시나리오에 대해 알아봅니다. 이러한 고객 중 상당수는 온-프레미스 데이터 센터에서 수천 개의 Spring Boot 애플리케이션을 실행하고 있습니다. 이러한 애플리케이션을 클라우드로 마이그레이션할 때 개발자가 잘 알고 있는 도구를 사용하여 APM(애플리케이션 성능 모니터링)을 위해 계측해야 합니다. 이제 Azure Spring Cloud에서 New Relic One이 통합되어 경험을 계속하고 Spring Boot 애플리케이션을 쉽게 계측할 수 있습니다.
Content: >-
  <p>오늘 Azure <a href="https://azure.microsoft.com/en-us/services/spring-cloud/" target="_blank">Spring Cloud</a>에서 New Relic One 성능 모니터링의 통합을 발표합니다.</p>


  <p>지난 18개월 동안 많은 엔터프라이즈 고객과 협력하여 시나리오에 대해 알아봅니다. 이러한 고객 중 상당수는 온-프레미스 데이터 센터에서 수천 개의 Spring Boot 애플리케이션을 실행하고 있습니다. 이러한 애플리케이션을 클라우드로 마이그레이션할 때 개발자가 익숙하고 수년 동안 사용해 온 도구를 사용하여 APM(애플리케이션 성능 모니터링)을 위해 계측해야 하며, <a href="https://docs.newrelic.com/" target="_blank">New Relic One</a>과 같은 에이전트를 사용하여 엔드 투 엔드 모니터링을 위해 이미 미리 계측된 데스크톱 및 모바일 애플리케이션의 연속성을 보장해야 합니다. Azure Spring Cloud에서 New Relic One의 통합을 통해 경험을 계속하고 New Relic One을 사용하여 <a href="https://docs.microsoft.com/en-us/azure/developer/java/migration/migrate-spring-boot-to-azure-spring-cloud" target="_blank">Spring Boot</a> 애플리케이션을 쉽게 계측할 수 있습니다.</p>


  <p>현재 Spring Boot 애플리케이션을 배포하는 대부분의 조직에서는 자동화 및 애플리케이션 성능 모니터링을 사용하여 거의 모든 규모에서 Spring Boot 애플리케이션을 실행하는 이점을 최대화하는 비슷한 목표를 공유합니다. Azure Spring Cloud는 컨테이너화된 워크로드 관리와 관련된 많은 수고를 추상화하는 데 탁월하지만, 조직에서 이러한 애플리케이션을 대규모로 배포할 때 이러한 애플리케이션의 성능 및 상태를 모니터링 및 유지 관리하거나 문제가 발생할&mdash; 경우 문제를 해결하는 데 어려움을 줍니다. New Relic One 여정을 성공하고 계속할 수 있도록 Azure Spring Cloud 인스턴스에서 New Relic One을 사용하여 계측, 모니터링 및 가시성을 제공하는 기능을 통합하고 업그레이드했습니다. 이는 계측을 빠르고 쉽게 설정하는 것으로 시작합니다. 그런 다음, 애플리케이션, JVM(Java Virtual Machines), 트랜잭션 등의 성능 및 상태를 분석하여 성능 문제를 식별하고 해결할 수 있습니다.</p>


  <h2>Spring Boot 애플리케이션 계측</h2>


  <p>&quot;Terraform 또는 ARM 템플릿을 만들고 배포&mdash;하는&quot; 새 애플리케이션을 계측하고 모니터링하기 위한 완전한 실습 환경을 위해 프로비저닝 자동화를 실행합니다. 또는 Azure CLI를 사용하여 주문형으로 실행하여 유연성과 제어를 강화할 수 있습니다.</p>


  <pre style="background: rgb(238, 238, 238); padding: 5px 10px; border: 1px solid rgb(204, 204, 204); border-image: none;">

  az spring-cloud app update --name customers-service \
      --jvm-options=&quot;-javaagent:/opt/agents/newrelic/java/newrelic-agent.jar&quot; \
      --env NEW_RELIC_APP_NAME=customers-service NEW_RELIC_LICENSE_KEY=&lt;key&gt;
  </pre>


  <h2>Spring Boot 애플리케이션 성능 살펴보기</h2>


  <p>계측 후 New Relic One 포털을 통해 Spring Boot 애플리케이션 성능을 탐색할 수 있습니다. 서비스 지도 통해 작동 중인 애플리케이션을 볼 수 있습니다. 예를 들어 아래 스크린샷은 인기 있는 Petclinic 프로젝트의 모든 애플리케이션을 보여 줍니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/0a46f26c-d26e-4e9b-965c-edde1cff1ba8.jpg"><img alt="Screenshot 1—shows all the applications in the popular Petclinic project." border="0" height="1888" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/1369468a-0f0b-4317-a7f6-45298a98f0e5.jpg" style="border: 0px currentcolor; border-image: none; display: inline; background-image: none;" title="2-Service-maps" width="3360"></a></p>


  <p><em>그림 1: 인기 있는 Petclinic 프로젝트의 모든 애플리케이션을 보여 줍니다.</em></p>


  <p>New Relic One 포털에서 애플리케이션&rsquo;별 탐색을 통해 애플리케이션 성능을 관찰할 수 있습니다. 예를 들어 아래 스크린샷은 customers-service에서 처리한 트랜잭션, 처리량 및 오류 비율을 보여 줍니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/dbc688e1-5531-485e-b3b3-e258c75bde8d.jpg"><img alt="Screenshot 2—shows transactions processed by customers-service, its throughput and error rate." border="0" height="1884" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/62813a9e-1d03-4fd2-8737-3c84ee34a26c.jpg" style="border: 0px currentcolor; border-image: none; display: inline; background-image: none;" title="2-customers-service-summary" width="3360"></a></p>


  <p><em>그림 2: customers-service에서 처리한 트랜잭션, 처리량 및 오류 비율을 보여 줍니다.</em></p>


  <p>New Relic One 포털에서 JVM&rdquo; 블레이드로 이동하여 &ldquo;기본 Java Virtual Machines를 자세히 살펴볼 수 있습니다. 예를 들어 아래 스크린샷은 모든 고객 서비스 애플리케이션 인스턴스에 대한 Java Virtual Machines 수를 보여 줍니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/e70f8bc5-4ad6-437c-adde-222c64b5934c.jpg"><img alt="Screenshot 3—shows how many JVMs for all the customers-service application instances." border="0" height="942" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/299a6ba4-b44c-4098-8222-25f19e2b8d7d.jpg" style="border: 0px currentcolor; border-image: none; display: inline; background-image: none;" title="2-customers-service-jvms" width="1680"></a></p>


  <p><em>그림 3:</em><em> 모든 고객 서비스 애플리케이션 인스턴스에 대한 Java Virtual Machines 수를 보여 줍니다.</em></p>


  <p>New Relic One 포털에서 데이터베이스 블레이드로 이동하여 데이터베이스 트랜잭션을 비롯한 애플리케이션 종속성을 분석할 &ldquo;&rdquo; 수 있습니다. 예를 들어 아래 스크린샷은 customers-service에 대한 모든 데이터베이스 트랜잭션을 보여 줍니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/3999145c-cc59-485e-856b-deee960adab6.jpg"><img alt="Screenshot 4—shows all the database transactions for customers-service." border="0" height="1888" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/036ff74f-bdc8-4363-ae5f-58aa03c2852a.jpg" style="border: 0px currentcolor; border-image: none; display: inline; background-image: none;" title="2-customers-service-databases" width="3360"></a></p>


  <p><em>그림 4: customers-service에 대한 모든 데이터베이스 트랜잭션을 보여 줍니다.</em></p>


  <p>New Relic One 스레드 프로파일러를 통해 각 스레드의 스택 추적을 살펴보고 Java 메서드에서 사용되는 시간을 이해할 수 있습니다. 이렇게 하면 대부분의 시간이 소요되는 애플리케이션의 핫&quot; 함수에 대한 인사이트를 &quot;얻을 수 있습니다. 예를 들어 아래 스크린샷은 customers-service 애플리케이션에서 스레드의 스택 추적을 보여줍니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/47a9bb59-1274-490e-9997-57351962260e.jpg"><img alt="Screenshot 5—shows a stack trace of a thread in the customers-service." border="0" height="1884" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/43fdb0eb-513b-4adb-a5a0-e40f94fbecc0.jpg" style="border: 0px currentcolor; border-image: none; display: inline; background-image: none;" title="2-customers-service-thread-profiler" width="3360"></a></p>


  <p><em>그림 5: customers-service의 스레드 스택 추적을 보여줍니다.</em></p>


  <h3>최종 사용자에게 값 제공</h3>


  <p>계측되면 여러 Spring Boot 애플리케이션 인스턴스로 확장할 때 모든 새 애플리케이션 인스턴스가 자동으로 모니터링됩니다. 에이전트 설치 및 유지 관리를 관리하는 시간을 줄이고 인시던트 식별 및 해결에 더 많은 에너지를 소비합니다. Azure Spring Cloud 서비스는 에이전트를 주기적으로 업데이트하기 위한 온포인트입니다.</p>


  <h3>Spring Boot 애플리케이션 인스턴스 보기</h3>


  <p>New Relic One Navigator는 애플리케이션 인스턴스의 작동 상태를 한눈에 볼 수 있습니다. 부동산의 이 조감도&#39;자동으로 사용할 수 있으며 구성이 필요하지 않습니다. 탐색기를 사용하면 정의한 경고에 따라 신호등 색이 있는 조밀한 허니콤 보기에 인스턴스를 직관적으로 표시하므로 많은 수의 인스턴스를 쉽게 탐색할 수 있습니다. 영향을 받을 수 있는 종속 시스템을 확인하는 것 외에도 경고 인스턴스를 신속하게 식별하고 근본 원인을 파악합니다.</p>


  <p>다음 탐색기 보기는 Azure Spring Cloud 인스턴스에서 인스턴스를 그룹화하여 다중 지역 배포에서 작업을 신속하게 비교할 수 있도록 합니다. 인스턴스를 그룹화하고 필터링하여 문제에 대해 신속하게 0으로 설정할 수 있습니다. 또한 모든 인스턴스로 드릴다운하여 해당 작업의 요약과 사용자 지정 특성을 포함한 주요 메트릭 및 메타데이터와 함께 위반 사항을 확인할 수 있습니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/7081ddde-755e-4f56-804c-ae1924da4710.jpg"><img alt="Screenshot 6—show how Navigator view groups your instances across Azure Spring Cloud instances." border="0" height="699" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/d0c05e18-0ffa-4b3f-bf40-42cc1de33146.jpg" style="border: 0px currentcolor; border-image: none; display: inline; background-image: none;" title="스크린샷 6" width="1650"></a></p>


  <p><em>그림 6: 탐색기 보기가 Azure Spring Cloud 인스턴스에서 인스턴스를 그룹화하는 방법을 보여 줍니다.</em></p>


  <h3>Spring Boot 애플리케이션 인스턴스에서 변칙 검색</h3>


  <p>New Relic Lookout은 최근 신호 변경의 심각도를 나타내는 색과 메트릭 신호의 크기에 비례하여 크기가 조정된 원 시각화를 사용하여 일반적인 동작에서 벗어나는 인스턴스의 직관적인 보기를 제공합니다. Lookout은 지난 5분 내의 신호를 이전 시간에 대해 자동으로 비교합니다.</p>


  <p><strong>마찬가지로 New Relic One을 사용하여 <a href="https://docs.newrelic.com/docs/agents/java-agent/additional-installation/install-new-relic-java-agent-docker/" target="_blank">Azure Kubernetes Service</a> 및 <a href="https://docs.newrelic.com/docs/agents/java-agent/installation/install-java-agent/" target="_blank">Virtual Machines</a>와 같은 Azure 서비스에서 Java 애플리케이션을 모니터링할 수 있습니다.</strong></p>


  <h2>솔루션을 빌드하고 지금 모니터링</h2>


  <p>Azure Spring Cloud는 Microsoft 및 VMware에서 공동으로 빌드, 운영 및 지원됩니다. 인프라 및 Spring Cloud 미들웨어 관리의 복잡성을 추상화하여 비즈니스 논리를 빌드하는 데 집중하고 Azure에서 동적 크기 조정, 패치, 보안, 규정 준수 및 고가용성을 처리할 수 있도록 하는 Spring Boot 애플리케이션용 완전 관리형 서비스입니다. 몇 단계를 통해 Azure Spring Cloud를 프로비전하고, 애플리케이션을 만들고, Spring Boot 애플리케이션을 배포 및 확장하고, 몇 분 안에 모니터링을 시작할 수 있습니다. 계속해서 개발자 친화적이고 엔터프라이즈급 기능을 Azure Spring Cloud에 도입할 예정입니다.</p>


  <p>Azure Spring Cloud를 사용하여 영향력 있는 솔루션을 빌드하는 방법을 듣고 싶습니다. 빠른 시작을 사용하여 오늘&mdash; Spring 애플리케이션을 <a href="https://aka.ms/get-started-with-azure-spring-cloud" target="_blank">Azure Spring Cloud에</a> 배포합니다.</p>


  <h3>리소스</h3>


  <ul>
      <li><a href="https://aka.ms/new-relic-spring-cloud-blog-june2021" target="_blank">New Relic에서 도우미 공지 블로그를</a> 읽어보세요.&nbsp;</li>
      <li><a href="https://docs.microsoft.com/en-us/learn/modules/azure-spring-cloud-workshop/" target="_blank">GitHub Microsoft Learn 모듈</a> 또는 <a href="https://github.com/microsoft/azure-spring-cloud-training" target="_blank">자가 진행 워크샵</a>을 사용하는 방법을 알아봅니다.</li>
      <li><a href="https://docs.microsoft.com/en-us/azure/spring-cloud/" target="_blank">Azure Spring Cloud에서 솔루션을 구현하는 방법에</a> 대해 자세히 알아봅니다.</li>
      <li>Azure Spring Cloud의 <a href="https://docs.microsoft.com/en-us/azure/spring-cloud/how-to-new-relic-monitor" target="_blank">New Relic Java 에이전트</a> 에 대해 자세히 알아봅니다.</li>
      <li>Spring Cloud를 사용하여 빌드된 배포된 버전의 Spring Petclinic을 <a href="https://github.com/Azure-Samples/spring-petclinic-microservices" target="_blank">배포</a>합니다.</li>
      <li>엔터프라이즈 모범 사례<a href="https://docs.microsoft.com/en-us/azure/spring-cloud/reference-architecture" target="_blank">Azure Spring Cloud 참조 아키텍처</a>를 활용하여 Spring Boot 애플리케이션을 배포합니다&mdash;.</li>
      <li><a href="https://docs.microsoft.com/en-us/azure/developer/java/migration/migrate-spring-boot-to-azure-spring-cloud" target="_blank">Spring Boot</a>, <a href="https://docs.microsoft.com/en-us/azure/developer/java/migration/migrate-spring-cloud-to-azure-spring-cloud" target="_blank">Spring Cloud</a> 및 <a href="https://aka.ms/migrate-tomcat-to-azure-spring-cloud-service" target="_blank">Tomcat</a> 애플리케이션을 Azure Spring Cloud로 마이그레이션합니다.</li>
      <li><a href="https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/" target="_blank">Azure 서비스와 상호 작용하는</a> Wire Spring 애플리케이션</li>
      <li>피드백 및 질문은 <a href="mailto:AzureSpringCloud-Talk@service.microsoft.com" target="_blank">이메일을 보내</a>주세요.</li>
  </ul>
