### YamlMime:Yaml
ms.openlocfilehash: 838b5906fee13b55e783641bbf7aa672a68c1fc3
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139906358"
Slug: video-new-business-and-application-models-with-microsoft-sql-azure
Title: '비디오: Microsoft SQL Azure 사용하는 새로운 비즈니스 및 애플리케이션 모델'
Summary: '[이 문서는 SQL Azure 팀에서 제공했습니다.] SQL Azure 통해 기업은 수익성을 높이고, 새로운 수익원을 실현하고, 세그먼트 범위를 확장할 수 있습니다. 이 비디오에서 수디르 하스베는 이야기 ...'
Content: '<p>[이 문서는 SQL Azure 팀에서 제공했습니다.]</p><p>SQL Azure 통해 기업은 수익성을 높이고, 새로운 수익원을 실현하고, 세그먼트 범위를 확장할 수 있습니다. 이 비디오에서 Sudhir Hasbe는 SQL Azure 빌드하고 시장에 배포하는 데 필요한 시간을 줄여 첫 번째 이동기 이점을 가능하게 하는 방법에 대해 설명합니다. 탄력적 확장성, 동적 소비 모델, 비즈니스 준비 서비스 수준, 웹 기반 접근성 및 유연성을 제공하는 SQL Azure 제공하는 판도를 바꾸는 기회에 대해 알아봅니다.</p>  <p>비디오: 보기</p>'
