### YamlMime:Yaml
ms.openlocfilehash: 2a24e9db1f3508b9cc84a3c15082b795913548d5
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139899569"
Slug: video-use-sql-azure-to-build-a-cloud-application-with-data-access
Title: '비디오: SQL Azure 사용하여 데이터 액세스로 클라우드 애플리케이션 빌드'
Summary: '[이 문서는 SQL Azure 팀에서 제공했습니다.] Microsoft SQL Azure 훌륭한 관계형 데이터베이스-클라우드 기능 제품군을 제공합니다. 이 비디오에서는 모스의 호스트인 힐튼 기제나우에 참여하세요...'
Content: <p>[이 문서는 SQL Azure 팀에서 제공했습니다.]</p><p>Microsoft SQL Azure 훌륭한 관계형 데이터베이스-클라우드 기능 제품군을 제공합니다. 이 비디오에서는 더 모스 쇼 SharePoint 팟캐스트의 호스트인 힐튼 기제나우(Hilton Giesenow)와 함께 등록하고 Microsoft SQL Azure 데이터베이스 만들기를 시작하는 방법을 살펴봅니다. 이 비디오에서는 R2(Microsoft SQL Server Management Studio Express)의 최신 릴리스를 사용하여 SQL Azure 데이터베이스에 연결하는 방법과 SQL Azure 말하도록 기존 온-프레미스 ASP.NET 애플리케이션을 구성하는 방법도 살펴봅니다.</p>  <p>여기에서 비디오를 봅니 <a href="https://msdn.microsoft.com/en-us/ff728568.aspx">다</a>.</p>
