### YamlMime:Yaml
ms.openlocfilehash: 08ca00ab95ac4c0a7451a8831f4e27bc415ede8c
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139901531"
Slug: video-teched-2010-migrating-applications-to-microsoft-sql-azure
Title: '비디오: TechEd 2010 - Microsoft SQL Azure 애플리케이션 마이그레이션'
Summary: '[이 문서는 SQL Azure 팀에서 제공했습니다.] 온-프레미스 애플리케이션 및 데이터베이스를 MySql 또는 다른 RDBM에서 SQL Azure 마이그레이션하시겠습니까? 아니면 단순히 에 초점을 맞추고 있습니다 ...'
Content: <p>[이 문서는 SQL Azure 팀에서 제공했습니다.]</p><p>온-프레미스 애플리케이션 및 데이터베이스를 MySql 또는 다른 RDBM에서 SQL Azure 마이그레이션하시겠습니까? 또는 SQL Server 데이터베이스를 SQL Azure 수 있는 가장 쉬운 방법에만 집중하고 있나요? 그런 다음이 비디오는 당신을위한 것입니다. Cihan Biyikoglu는 이 세션의 두 가지 기본 영역인 애플리케이션 데이터 액세스 계층과 데이터베이스 스키마+데이터를 다룹니다. 1부에서는 클라우드 및 SQL Azure 데이터 액세스 계층의 복원력을 높이는 데 도움이 되는 모범 사례뿐만 아니라 일반적인 마이그레이션 문제를 다루는 애플리케이션 데이터 액세스 계층에 대해 자세히 설명합니다. 2부에서는 데이터베이스 마이그레이션에 중점을  두고 있습니다. 스키마 및 데이터 마이그레이션을 진행하면서 Management Studio 및 DAC(Data-Tier Application)를 통해 스키마를 효율적으로 전송하기 위한 도구와 기술을 살펴봅니다. 그런 다음 SSIS 및 BCP와 같은 도구를 통해 크고 작은 데이터를 SQL Azure 이동하는 효율적인 방법을 발견합니다. 그는 애플리케이션을 SQL Azure 마이그레이션을 완화하기 위해 향후 매장에 무엇이 있는지 엿볼 수 있는 비디오를 닫습니다.</p>  <p>여기에서 비디오 보기</p>  <h2>요약</h2>  <p>비디오에서 설명하는 정보에 대한 질문, 우려 사항, 의견이 있나요? 아래에 게시하고 우리는 그들을 해결하기 위해 노력할 것입니다.</p>
