### YamlMime:Yaml
ms.openlocfilehash: 6dc976602d0365fd1b327eaedb04518768df7574
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139898827"
Slug: video-building-a-multi-tenant-saas-application-with-sql-azure-and-appfabric
Title: '비디오: SQL Azure 및 AppFabric을 사용하여 다중 테넌트 SaaS 애플리케이션 빌드'
Summary: '[이 문서는 SQL Azure 팀에서 제공했습니다.] 이 비디오에서 Niraj Nagrani와 Rick Negrin은 SQL Azure, AppFabric 및 Windows Azure 플랫폼을 통해 어떻게 성장시킬 수 있는지를 설명합니다.'
Content: '<p>[이 문서는 SQL Azure 팀에서 제공했습니다.]</p><p>이 비디오에서 Niraj Nagrani와 Rick Negrin은 SQL Azure, AppFabric 및 Windows Azure 플랫폼을 통해 수익을 늘리고 시장 진출을 늘릴 수 있는 방법을 설명합니다. 고가용성 셀프 서비스 플랫폼을 사용하여 비용을 절감하고 출시 시간을 단축하는 탄력적 애플리케이션을 빌드하는 방법을 알아봅니다. 이러한 앱은 클라우드에서 엔터프라이즈까지 쉽게 확장할 수 있습니다. 클라우드로 이동하려는 기존 ISV 또는 더 많은 기능과 더 큰 지리적 존재를 얻고자 하는 SaaS ISV인 경우 이 세션은 방법을 보여 주는 세션입니다.</p>  <p>비디오: 보기</p>'
