### YamlMime:Yaml
ms.openlocfilehash: 6b2fb1d0f31450fb6d5fd183ca28a8f82259ef40
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139902432"
Slug: video-how-do-i-configure-sql-azure-security
Title: '비디오: 어떻게 해야 하나요? SQL Azure 보안 구성'
Summary: '[이 문서는 SQL Azure 팀에서 제공했습니다.] 이 비디오에서 Max Adams는 SQL Azure 내의 보안을 소개합니다. 로그인, 데이터베이스 및 사용자 만들기에 대해 설명하고 설명합니다. Tthe...'
Content: <p>[이 문서는 SQL Azure 팀에서 제공했습니다.]</p><p>이 비디오에서 Max Adams는 SQL Azure 내의 보안을 소개합니다. 로그인, 데이터베이스 및 사용자 만들기에 대해 설명하고 설명합니다. master 데이터베이스에서 로그인 및 데이터베이스를 표시할 수 있는 뷰 sys.sql_logins 및 sys.databases도 설명합니다.</p>  <p>여기에서 비디오를 봅니 <a href="https://technet.microsoft.com/en-us/ff772115.aspx">다</a>.</p>
