### YamlMime:Yaml
ms.openlocfilehash: ad239100426d90706079d07e03b3883ef9609ad6
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139899562"
Slug: view-chooses-microsoft-azure-iot-to-accelerate-development-of-smart-building-applications
Title: 보기에서 스마트 빌딩 애플리케이션 개발을 가속화하는 Microsoft Azure IoT 선택
Summary: 최근 몇 년 동안 클라우드, AI 및 IoT의 민주화로 인해 스마트 빌딩의 혁신이 증가하고 있습니다. 최근 Azure Digital Twins 공지 사항은 IoT 혁신에 대한 Microsoft의 노력을 강조합니다.
Content: >-
  <p>최근 몇 년 동안 클라우드, AI 및 IoT의 민주화로 인해 스마트 빌딩의 혁신이 증가하고 있습니다. 최근 <a href="https://azure.microsoft.com/en-us/services/digital-twins/" target="_blank">Azure Digital Twins</a> 공지 사항은 IoT 혁신에 대한 Microsofts&rsquo;의 노력을 강조합니다. 조직은 실제 환경을 가상으로 표현하여 스마트 빌딩을 비롯한 다양한 IoT 시나리오를 제공할 수 있습니다. 조직은 다양한 센서 및 디바이스에서 데이터를 수집하여 공간을 보다 정확하게 이해하고 최적화하고 사람들의&rsquo; 요구에 가장 잘 부합하도록 변경할 수 있습니다. 컴퓨팅 성능이 사람들이 사용하는 모든 물리적 환경에 전파됨에 따라 건물은 효율성 향상 및 점유자 만족도를 창출할 수 있는 잠재력에서 최우선 순위가 되었습니다. 크기나 배경에 관계없이 모든 고객이 IoT에 액세스할 수 있도록 하는 것은 파트너&rsquo; 의 창의성과 고유한 도메인 전문 지식에 크게 의존합니다. 새로운 혁신적인 디바이스를 사용하면 더 풍부하고 의미 있는 데이터를 캡처하고 획기적인 스마트 빌딩 애플리케이션을 만들 수 있습니다. Were&rsquo;는 수세기 &ndash; 동안 변하지 않은&rsquo; 무언가를 재창조한 회사인 View와 함께 하고 있는 작업 중 일부를 공유하게 되어 기쁩니다.</p>


  <h2>보기는 유쾌한 인간 환경을 만드는 임무에</h2>


  <p><a href="https://viewglass.com/" target="_blank">뷰</a> 는 인간의 건강과 웰빙이 스마트 건물의 중심이 되어야 한다고 믿습니다. 그래서&rsquo; 그들은 동적 유리를 사용하여 그 어느 때보 다 지능적이고, 더 연결되고, 개인화함으로써 건물에서 인간의 경험을 개선하는 임무를 맡고 있습니다. 동적 유리 창을 통해&rsquo; 보기를 유지하면서 최적의 자연 채광을 구현하여 건물 거주자의 웰빙을 크게 개선하는 동시에 건물 에너지 사용량을 줄입니다. <a href="https://hbr.org/2018/09/the-1-office-perk-natural-light?utm_medium=email&amp;utm_source=newsletter_weekly&amp;utm_campaign=weeklyhotlist_not_activesubs&amp;referral=00202&amp;deliveryName=DM13857" target="_blank">하버드 비즈니스 리뷰</a> 는 자연광을 #1 원하는 사무실 특전으로 식별하는 연구를 발표했습니다. 또 다른 최근 연구는 일반 창을 통해 <a href="https://viewglass.com/assets/pdfs/daylight-research.pdf" target="_blank">보기 동적 유리와 관련 된 중요 한 건강 혜택을</a> 발견, 포함 하 여 이상 50 눈 긴장에 % 감소, 두통, 그리고 졸음 &ndash; 모든 향상 된 직원 건강과 생산성에 기여.</p>


  <p>뷰는 데이터를 생성하고 컨텍스트를 적용함으로써 조직이 건물 공간을 사용하는 방법을 더 잘 분석하고 직원 건강 및 생산성에서 에너지 효율성, 상황별 개인 설정에 이르기까지 모든 수준에서 &mdash; 필요한 사람들에게&rsquo; 서비스를 제공하도록 최적화할 수 있다는 Microsofts&rsquo; 비전을 &ndash; 공유합니다.</p>


  <h2>새로운 파트너십</h2>


  <p>오늘 우리는 View와의 새로운 파트너십을 발표하게 되어 기쁘고 스마트 빌딩을 위한 혁신적인 애플리케이션을 개발하기 위해 함께 일할 수 있게 되어 기쁩니다. 이 파트너십의 일환으로 View는 스마트 빌딩에 대한 전문 지식을 활용하고 Azure IoT 플랫폼의 여러 측면을 활용하여 솔루션 개발을 가속화할 것입니다. 예를 들어 View는 액세스 제어 및 기타 스마트 빌딩 애플리케이션뿐만 아니라 창 및 바닥 컨트롤러 디바이스에 대한 Azure IoT Edge 및 Azure Sphere에 Azure Digital Twins를 활용합니다.</p>


  <p>첫 번째 솔루션인 <a href="https://view.com/assets/pdfs/microsoft-view-announcement.pdf" target="_blank">View SmartProtect</a>는 오늘 발표됩니다. View SmartProtect는 유리 파손을 자동으로 즉시 감지하는 스마트 창 기반 빌드 보안 솔루션입니다. 건물의 모든 창에서 유리가 손상되는 즉시 Azure IoT 통해 고객에게 유리 중단 이벤트가 발생한 건물 내의 특정 시간, 창 및 위치를 알리는 SmartProtect 애플리케이션 보기&rsquo;로 신호가 전송됩니다.</p>


  <p>View SmartProtect는 Azure IoT 플랫폼을 활용하는 애플리케이션을 통해 건물을 더 건강하고 스마트하며 생산성을 높이는 것을 목표로 하는 View의 여러 IoT 솔루션 중 첫 번째 솔루션입니다. 이는 공간 구축에 대한 다음 수준의 인텔리전스 및 개인화를 가져오는 첫 번째 단계일 뿐입니다. 이 파트너 관계를 통해 View 고객은 향후 요구 사항을 충족하기 위해 강력하고 안전하며 확장 가능한 최고의 생산성 솔루션을 활용할 수 있습니다.</p>


  <h2>무한한 가능성</h2>


  <p>여행의 다음 단계는 매우 자동화되고 손쉽게 각 개인이 건강과 생산성을 최대화할 수 있도록 건물 공간을 최적화하는 데이터 중심 접근 방식을 취합니다. 보기는 대화형 유리 디스플레이와 카메라, 마이크, 공기 품질 센서 등이 있는 센서 배열을 창 프레임에 포함하는 지능형 에지를 만듭니다.</p>


  <p>Azure IoT,&rdquo; Office 365, Cortana 및 Dynamics 365와 통합된 이 &ldquo;스마트 창은 공간을 통해 거주자에게 더 나은 서비스를 제공하고 사람들이 새로운 방식으로 환경과 상호 작용할 수 있도록 합니다. 인텔리전트 클라우드와 인텔리전트 에지가 작동하는 예제입니다. 퍼블릭 클라우드에서 사용할 수 있는 유비쿼터스 분산 컴퓨팅과 건물의 &ndash; 창문과 벽을 포함하여 연결된 시스템 및 디바이스 &ndash; 집합을 지속적으로 확장함으로써 훨씬 더 다양한 방식으로 주변 환경과 지속적으로 상호 작용할 것입니다. 뷰는 항상 연결된 고밀도 플랫폼을 제공하여 여러 변환 애플리케이션을 사용하도록 설정합니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/2dbf0532-b0e2-49ae-a143-440ca84214cc.png"><img alt="Charlotte, NC airport terminal " src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/804d88d3-01f1-45d2-bab8-3476f71bbc1f.png" style="border: 0px; border-image: none; width: 1043px; height: 588px; background-image: none; display: inline;" title="CLT"></a></p>


  <p>예를 들어, 거주자가 스마트 빌딩에 들어가면 건물은 사람들이 처음으로 공간에 들어가는 것을 인식하고 이를 알 &ldquo;수 있습니다. 이 공간은 음성 명령으로 제어할 수 있습니다. 너무 춥거나 너무 뜨겁고 Ill&rsquo;이 환경을 기본 설정으로 조정하면 됩니다.&rdquo; 이 음성 상호 작용은 창의 색조, HVAC 수준 및 조명 조건을 자동으로 조정하여 최적의 환경을 만들 수 있습니다.</p>


  <p>이&rsquo; 파트너십의 가능성에 흥분하고 Azure Digital Twins가 뷰가 거주자의 건강과 웰빙을 개선하는 솔루션을 제공하는 데 어떻게 힘을 실어줄지 기대합니다&rsquo; . 뷰&rsquo; 혁신은 무한한 스마트 빌딩 혁신을 위한 새로운 토대를 제공합니다. 나는 다음에 무엇을&rsquo;보고 기다릴 수&rsquo; 없어!</p>


  <h2>자세한 정보</h2>


  <p><a href="https://azure.microsoft.com/services/digital-twins/" target="_blank">Azure Digital Twins</a> 및 <a href="https://viewglass.com/" target="_blank">보기</a>에 대해 자세히 알아봅니다. 스마트 시티 엑스포 Word 의회에 오는 경우&rsquo;, 보기 미리 보기 SmartProtect, 업계&#39;최초의 스마트 창 기반 유리 브레이크 감지 솔루션을 볼 수있는 마이크로 소프트 부스에 들러해야합니다.</p>
