### YamlMime:Yaml
ms.openlocfilehash: 1bf5ed1cfc358acfcd2a1131c53ec86d5420a206
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139907983"
Slug: wcf-monitoring-with-application-insights
Title: 애플리케이션 Insights 사용하여 WCF 모니터링
Summary: 특히 WCF 애플리케이션을 모니터링하기 위한 새 Application Insights Labs SDK를 출시했습니다. .NET 웹 애플리케이션용 애플리케이션 Insights SDK는 이미 HTTP 기반 WCF 애플리케이션을 지원하지만 WCF 관련 용도로 최적화된 적이 없습니다.
Content: >-
  <p>특히 WCF 애플리케이션을 모니터링하기 위한 새 <a href="https://www.myget.org/gallery/applicationinsights-sdk-labs">Application Insights Labs</a> SDK를 출시했습니다. <a href="https://azure.microsoft.com/documentation/articles/app-insights-asp-net/">.NET 웹 애플리케이션용 애플리케이션 Insights SDK</a>는 이미 HTTP 기반 WCF 애플리케이션을 지원하지만 WCF 관련 사항에 최적화된 적이 없습니다. 애플리케이션 Insights WCF SDK는 이러한 애플리케이션을 모니터링하는 데 유용한 환경을 제공합니다. 모든 일반적인 WCF 바인딩을 모니터링하고 예외 모니터링, 명확한 작업 식별 및 선택적 모니터링을 제공합니다.</p>


  <h2>동기</h2>


  <p>모니터링 도구를 작성하면 항상 원격 분석을 수집할 수 있는 여러 계층을 선택할 수 있습니다. 많은 IIS 기반 애플리케이션에 대한 공통 분모는 HTTP 모듈 계층입니다. HTTP 모듈은 이 요청 ASP.NET, MVC, Web API 또는 WCF를 처리하는 데 사용되는 기술에 관계없이 모든 HTTP 요청에 &ndash; 대한 알림을 받습니다. <a href="https://www.iis.net/learn/application-frameworks/building-and-running-aspnet-applications/how-to-take-advantage-of-the-iis-integrated-pipeline">non-.NET 애플리케이션</a>을 모니터링할 수도 있습니다.</p>


  <p>일반적인 접근 방식이 WCF 애플리케이션에서 잘 작동하지 않는다는 피드백을 많이 들었습니다. 이 피드백은 너무 강해서 Application Insights 팬이자 큰 후원자 중 하나인 <a href="https://github.com/tomasr">Tomas Restrepo</a>가 자신에 대한 WCF 모니터링 지원을 빌드하기로 결정했습니다. 그는 웹 SDK에서 지원되지 않는 몇 가지 경험을 놓쳤으며 몇 가지 제한 사항도 제거하고 싶었습니다.</p>


  <p>이제 Tomass&rsquo; 작업의 결과를 공유하고 <a href="https://github.com/Microsoft/ApplicationInsights-SDK-Labs/blob/master/WCF/readme.md">있습니다. WCF 애플리케이션용 애플리케이션 Insights SDK.</a></p>


  <h2>기능</h2>


  <p>WCF 애플리케이션용 애플리케이션 Insights SDK는 흥미로운 기능 목록을 제공합니다.</p>


  <h4>일반적인 WCF 바인딩을 사용하는 계측</h4>


  <p>이제 WCF 원격 분석용 Application Insights SDK를 사용하여 HTTP 바인딩만 제한됩니다. 이제 HTTP 기반의 일반적인 WCF 바인딩을 사용할 수 있습니다.</p>


  <h4>매핑 작업</h4>


  <p>이제 사용자 지정 코드 없이 특정 서비스 작업에 대한 요청을 구분할 수 있습니다. 제네릭 URL 경로 대신 요청 원격 분석에 대한 작업 이름은 <b>Contract&gt; 형식&lt;입니다.&lt; 작업을&gt;</b> 코드에 더 쉽게 매핑할 수 있습니다.</p>


  <h4>IErrorHandler 확장성 지점</h4>


  <p>IErrorHandler 구현을 사용하면 대부분의 시나리오에서 서비스에서 throw된 예외 또는 오류를 자동으로 추적할 수 있습니다.</p>


  <h4>선택적 모니터링</h4>


  <p>기본적으로 WCF 서비스에 대한 호출은 요청 이벤트를 Application Insights 보냅니다.</p>


  <p>모니터링할 서비스를 선택하려면 <a href="https://github.com/Microsoft/ApplicationInsights-SDK-Labs/blob/master/WCF/readme.md#controlling-operation-telemetry">[OperationTelemetry]</a> 메서드 특성을 모니터링하려는 서비스의 계약 또는 구현에 연결합니다. 앱에서 이 특성을 사용하는 경우 특성이 없는&rsquo; 서비스는 모니터링되지 않습니다.</p>


  <h2>설치</h2>


  <p>WCF 프로젝트에 Application Insights SDK Labs 패키지 원본의 시험판 Microsoft.ApplicationInsights.Wcf 패키지를 추가합니다.</p>


  <p>명령줄 <b>NuGet 패키지 관리자</b><b>를 사용하는 경우&rsquo;</b>:</p>


  <pre class="prettyprint">

  &gt; Install-Package &quot;Microsoft.ApplicationInsights.Wcf&quot; &ndash;Source &quot;https://www.myget.org/F/applicationinsights-sdk-labs/&quot; -Pre </pre>


  <p><b>Visual Studio 사용하는 경우&rsquo;:</b></p>


  <p>솔루션 탐색기에서 프로젝트를 마우스 오른쪽 단추로 클릭하고 <b>NuGet 패키지 관리를</b> 선택합니다. 그런 다음 패키지 원본 목록에 추가 <a href="https://www.myget.org/F/applicationinsights-sdk-labs/">https://www.myget.org/F/applicationinsights-sdk-labs/</a> 합니다.</p>


  <p><img alt="wcf_thumb1" border="0" height="367" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/5d030f4d-6b05-46d0-867d-7eab394779e1.png" style="border-left-width: 0px; border-right-width: 0px; background-image: none; border-bottom-width: 0px; padding-top: 0px; padding-left: 0px; display: inline; padding-right: 0px; border-top-width: 0px" title="wcf_thumb1" width="610"></p>


  <p>패키지 원본을 설정하고 <b>, 시험판 포함</b> 을 선택하고, Microsoft.ApplicationInsights.Wcf를 설치합니다.</p>


  <p><img alt="wcf2_thumb1" border="0" height="201" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/9c7e8f19-0b14-4e0d-8078-d428b67b6641.png" style="border-left-width: 0px; border-right-width: 0px; background-image: none; border-bottom-width: 0px; padding-top: 0px; padding-left: 0px; display: inline; padding-right: 0px; border-top-width: 0px" title="wcf2_thumb1" width="610"></p>


  <p><b>계측 키 설정</b></p>


  <p><a href="https://azure.microsoft.com/documentation/articles/app-insights-create-new-resource/">애플리케이션 Insights 리소스의 계측 키를</a> ApplicationInsights.config 파일에 추가합니다. <a href="https://azure.microsoft.com/documentation/articles/app-insights-api-custom-events-metrics/#ikey">코드 또는 웹 구성을 통해</a> 계측 키를 제공할 수도 있습니다. 즉&rsquo;, 그것을!</p>


  <h2>특별 감사</h2>


  <p>WCF 애플리케이션용 Application Insights SDK를 Microsoft 및 커뮤니티와 공유해 주신 Tomas Restrepo에 감사드립니다.</p>


  <h2>알려주세요.&hellip;</h2>


  <p>문제 또는 기능 요청은 WCF 원격 분석 <a href="https://github.com/Microsoft/ApplicationInsights-SDK-Labs/tree/master/WCF">리포지토리</a>용 Application Insights SDK를 방문하세요.</p>


  <p>WCF 관련 SDK와 일반 웹 SDK를 비교하는 여러분의 생각과 의견을 듣고 싶습니다. 애플리케이션 Insights 팀은 개발자를 위한 고품질 도구를 제공하기 위해 최선을 다하고 있습니다. <a href="https://aka.ms/aiuservoice">피드백이나 새로운 기능 권장 사항에</a> 감사드립니다.</p>
