### YamlMime:Yaml
ms.openlocfilehash: a41eb77b03888919872a30ae74aa4aa274704611
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139898232"
Slug: web-application-firewall-at-azure-front-door-service
Title: Azure Front Door 서비스의 웹 애플리케이션 방화벽
Summary: 많은 사용자로부터 웹 애플리케이션을 클라우드로 이동할 때 보안이 최우선이라는 소식을 들었습니다. 오늘 Azure Front Door 서비스에 대한 WAF(웹 애플리케이션 방화벽)의 공개 미리 보기를 발표하게 되어 매우 기쁩니다.  글로벌 애플리케이션 및 콘텐츠 배달 네트워크를 고유하게 통합된 WAF 엔진과 결합하여 이제 웹 애플리케이션을 안전하고 빠르게 전 세계에 제공할 수 있는 고가용성 플랫폼을 갖게 되었습니다.
Content: >-
  <p>당신은 훌륭한 웹 애플리케이션을 가지고 있으며, 전 세계의 사용자는 그것을 사랑해요. 악의적인 공격자도 마찬가지입니다. 사이버 공격은 매년 빈도와 정교함에서 증가하고 있으며, 이에 대한 보호를 받지 않으면 서비스 중단, 데이터 손실 및 손상된 평판의 위험에 노출됩니다.</p>


  <p>많은 사용자로부터 웹 애플리케이션을 클라우드로 이동할 때 보안이 최우선이라는 소식을 들었습니다. 오늘 Azure Front Door 서비스에 대한 WAF(웹 애플리케이션 방화벽)의 공개 미리 보기를 발표하게 되어 매우 기쁩니다.&nbsp; 글로벌 애플리케이션 및 콘텐츠 배달 네트워크를 고유하게 통합된 WAF 엔진과 결합하여 이제 웹 애플리케이션을 안전하고 빠르게 전 세계에 제공하는 데 도움이 되는 고가용성 플랫폼을 제공합니다.</p>


  <p>Front Door 서비스를 사용하는 WAF는 Azure Edge에서 수행한 규모와 심층 보안 투자를 활용하며, 주입 유형 공격 및 대량 DoS 공격과 같은 여러 공격 벡터로부터 보호하도록 설계되었습니다. Azures&rsquo; 네트워크 에지에서 들어오는 각 요청을 검사하고, 백 엔드 서버에 들어가기 전에 원치 않는 트래픽을 중지하며, 성능을 저하시키지 않고 대규모로 보호를 제공합니다. Front Door용 WAF를 사용하면 정의하는 사용자 지정 규칙을 사용하여 웹 애플리케이션에 대한 액세스를 미세 조정할 수 있을 뿐만 아니라 관리되는 규칙 집합으로 패키지된 일반적인 웹 애플리케이션 취약성에 대한 보안 규칙 컬렉션을 사용하도록 설정할 수 있습니다. 또한 Front Door에서 WAF를 사용하는 경우 보안 정책 관리가 중앙 집중화되고 변경한 내용이 즉시 모든 Front Door 에지에 전파됩니다.</p>


  <p>WAF 정책은 웹 애플리케이션의 보안 상태를 정의하는 WAF의 구성 단위입니다. 두 가지 유형의 보안 규칙, 즉 사용자 지정 규칙과 관리되는 규칙 집합이라고 하는 미리 구성된 규칙 그룹 집합이 있을 수 있습니다. Azure 관리형 기본 규칙 집합은 새 공격 서명에 맞게 필요에 따라 Azure에서 업데이트됩니다. Azure PaaS 플랫폼에서 호스트되는 웹앱과 같은 클라우드 네이티브 인터넷 연결 웹 애플리케이션이 있는 경우 기본 WAF 정책을 사용하여 Front Door를 추가하는 것은 매우 간단합니다. 몇 번의 클릭만으로 웹 애플리케이션은 일반적인 OWASP TOP 10 악용 및 Front Door 서비스에서 제공하는 대기 시간 최적화로부터 보호됩니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/5fdc3b91-dd54-4e49-b2f1-5745baa2f53a.png"><img alt="Diagram of Web Application Firewall protecting Contoso's Web App" border="0" height="196" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/f44ea369-486f-4b7f-a27e-287da2d5a179.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="Contoso의 웹앱을 보호하는 웹 애플리케이션 방화벽 다이어그램" width="607"></a></p>


  <p align="center"><em>그림 1 Front Door에서 WAF를 사용하여 웹앱 보호</em></p>


  <p><br>

  중요 비즈니스용 애플리케이션에 대한 규정 준수 및 BCDR 요구 사항이 있는 많은 고객과 마찬가지로 웹 애플리케이션이 여러 지역에서 호스트될 수 있습니다. Front Door가 있는 WAF는 백 엔드에 대한 많은 라우팅 옵션을 지원하는 중앙 집중식 정책 관리 및 글로벌 부하 분산을 제공합니다.</p>


  <p><a href="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/8e59b740-6b05-4b31-afeb-cade2840b503.png"><img alt="Diagram of Web Application Firewall (WAF) protecting your Web Apps within your organization with multiple regions" border="0" height="329" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/005f261c-919a-4b9f-ab5e-95f27f842bb5.png" style="border: 0px currentcolor; border-image: none; margin-right: auto; margin-left: auto; float: none; display: block; background-image: none;" title="여러 지역을 사용하여 조직 내에서 Web Apps를 보호하는 WAF(웹 애플리케이션 방화벽) 다이어그램" width="590"></a></p>


  <p align="center"><em>그림 2 Front Door에서 WAF를 사용하여 다중 지역 웹 애플리케이션 보호</em></p>


  <p>Front Door를 사용하는 WAF는 Azure에서 호스트되는 백 엔드와 다른 클라우드 또는 온-프레미스에서 호스트되는 백 엔드를 보호할 수 있습니다. Front Door의 트래픽만 허용하고 인터넷에서 직접 액세스를 거부하도록 백 엔드를 추가로 잠글 수 있습니다. Front Door의 WAF는 사용자 지정 규칙을 통해 세분화된 액세스 및 속도 제어를 허용합니다. 다음 차원에 따라 사용자 지정 규칙을 만들 수 있습니다.</p>


  <ul>
   <li><strong>IP 허용 목록 및 차단 목록</strong>: 클라이언트 IP 주소 또는 IP 주소 범위 목록에 따라 웹 애플리케이션에 대한 액세스를 제어합니다. IPv4 및 IPv6 모두 지원됩니다.</li>
   <li><strong>지리적 기반 액세스 제어</strong>: 클라이언트&rsquo; 국가 코드에 따라 웹 애플리케이션에 대한 액세스를 제어합니다.</li>
   <li><strong>HTTP 매개 변수 기반 액세스 제어</strong>: 쿼리 문자열, 게시 인수, 요청 Uri, 요청 헤더 및 요청 본문과 같은 HTTP(S) 요청 매개 변수의 문자열 일치를 기반으로 웹 애플리케이션에 대한 액세스를 제어합니다.</li>
   <li><strong>요청 메서드 기반 액세스 제어</strong>: Get, Put 및 Head와 같은 HTTP 요청 방법을 기반으로 웹 애플리케이션에 대한 액세스를 제어합니다.</li>
   <li><strong>크기 제약 조건</strong>: 쿼리 문자열, URI 또는 요청 본문과 같은 요청의 특정 부분 길이에 따라 웹 애플리케이션에 대한 액세스를 제어합니다.</li>
   <li><strong>속도 제한 규칙</strong>: 속도 제어 규칙은 모든 클라이언트 IP에서 비정상적인 높은 트래픽을 제한하는 것입니다. 1분 동안 클라이언트 IP에서 허용하는 웹 요청 수에 대한 임계값을 설정할 수 있습니다. 속도는 특정 Uri 경로에 대한 속도 제한 액세스와 같은 일치 조건과 결합될 수 있습니다.</li>
  </ul>


  <p>WAF는 사용자가 만든 WAF 정책 및 규칙 수, 선택한 관리되는 규칙 집합 유형 및 수신하는 웹 요청 수에 따라 요금이 청구됩니다. 공개 미리 보기 기간 동안 Front Door의 WAF는 무료입니다.</p>


  <p>Azure WAF 제품을 계속 향상시키면서 여러분의 의견을 듣고 싶습니다. 포털, ARM 템플릿 또는 PowerShell을 사용하여 현재 Front Door에서 웹 애플리케이션 방화벽을 사용해 볼 수 있습니다. 자세한 내용은 <a href="https://docs.microsoft.com/en-us/azure/frontdoor/waf-overview">Azure Front Door 서비스에 대한 WAF(웹 애플리케이션 방화벽)에 대한</a> 자세한 설명서를 참조하세요.</p>
