### YamlMime:Yaml
ms.openlocfilehash: 9f01b1f53334a724fa34c94bea1722d299ec5f3e
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139912288"
Slug: what-you-need-to-know-when-writing-hybrid-applications
Title: 하이브리드 애플리케이션을 작성할 때 알아야 할 사항
Summary: 현재 Azure는 Azure Stack을 통해 고객의 데이터 센터뿐만 아니라 54개 지역, 여러 소버린 클라우드에 있습니다. 일관성은 애플리케이션을 배포하는 지역과 관계없이 스크립트와 템플릿을 작성하는 방식이 동일한 Azure의 기본 핵심 요소입니다.
Content: >-
  <p>현재 Azure는 Azure Stack을 통해 고객&rsquo; 데이터 센터뿐만 아니라 <a href="https://azure.microsoft.com/en-us/global-infrastructure/regions/" target="_blank">54개 지역</a>, 여러 소버린 클라우드에 있습니다. 일관성은 애플리케이션을 배포하는 지역과 관계없이 스크립트와 템플릿을 작성하는 방식이 동일한 Azure의 기본 핵심 요소입니다.</p>


  <p>일관성은 지식과 아티팩트 다시 사용할 수 있기 때문에 좋습니다. 이 게시물은 다양한 Azure 클라우드를 대상으로 하는 애플리케이션을 작성할 때 알아야 할 주요 사항을 제공합니다.</p>


  <ul>
      <li>리소스 종류 가용성 및 버전은 여러 지역 및 클라우드에 따라 달라집니다.</li>
      <li>사용 가능한 이미지, VM(가상 머신) 크기 및 확장은 클라우드마다 다를 수 있습니다.</li>
      <li>ARM(Azure Resource Manager) 및 스토리지 엔드포인트도 다를 수 있습니다.</li>
  </ul>


  <p>즉,&rsquo; 위의 항목에 대한 매개 변수를 허용하도록 코드 및 템플릿을 디자인하는 것이 중요합니다. 이렇게 하면 다양한 클라우드에 리소스를 쉽게 배포할 수 있습니다. 매개 변수화 외에도 솔루션을 다른 클라우드에 배포할 수 있는 더 작은 청크로 분해할 수 있는 <a href="https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-linked-templates" target="_blank">중첩된 템플릿</a> 을 활용하는 것도 고려해야 합니다. 자세한 내용은 <a href="https://aka.ms/consistency" target="_blank">클라우드 일관성을 위한 Azure Resource Manager 템플릿 개발</a> 문서를 &quot; 참조하세요.&quot;</p>


  <p>또한 고객이 Azure Stack을 배포할 수 있도록 돕는 데 중점을 둔 AzureCAT 팀의 훌륭한 지침도 있습니다. 자세한 인사이트와 지침은 블로그 게시물, &quot; 하이브리드 애플리케이션&quot;<a href="https://blogs.msdn.microsoft.com/azurecat/2018/09/23/design-considerations-for-hybrid-applications-summary-learn-more/" target="_blank">에 대한 디자인 고려 사항을</a> 확인하세요. Microsoft Ignite 2018에서도 훌륭한 세션이 진행되었으며, 이 모든 세션에는 재사용할 수 있는 귀중한 리소스가 있습니다. 권장되는 몇 가지 세션은 다음과 같습니다.</p>


  <ul>
      <li>Compute 및 ASDK용 프로그램 관리자인 <a href="https://twitter.com/Kirtana_MSFT" target="_blank">Kirtana Venkatraman</a> 및 <a href="https://twitter.com/MichelaSaina" target="_blank">Michela Sainato</a>는 <a href="https://youtu.be/71kd2Uue1qI?t=279" target="_blank">엔드포인트</a>, <a href="https://youtu.be/71kd2Uue1qI?t=1324" target="_blank">도구</a>, <a href="https://youtu.be/71kd2Uue1qI?t=1451" target="_blank">powershell 및 CLI</a>, <a href="https://youtu.be/71kd2Uue1qI?t=2179" target="_blank">Azure Stack 개발자 키트</a>와 같은 개발자를 위한 여러 관심 영역을 안내합니다.</li>
      <li>개발자 도구 및 SDK용 프로그램 관리자인 <a href="https://www.linkedin.com/in/siddique-juman/" target="_blank">Siddique Juman</a>은 <a href="https://youtu.be/zfHcldL3Pnc?t=610" target="_blank">Visual Studio를 사용하여 일관된 앱 개발에</a> 대한 훌륭한 개요를 제공합니다.</li>
      <li>Azure Stack의 Azure 서비스 프로그램 관리자인 <a href="https://twitter.com/shriramnat" target="_blank">Shriram Natarajan</a>은 <a href="https://youtu.be/zfHcldL3Pnc?t=2503" target="_blank">API 프로필</a>과 Azure SDK 데모를 안내합니다. 이 세션은 Ignite에서 가장 높은 등급의 세션이었습니다!</li>
  </ul>


  <p>마지막으로, 위의 링크에 설명된 많은 기능과 기능에서 Id&rsquo;는 Azure의 하이브리드 기능 및 일관성을 효과적으로 활용하는 코드를 작성할 수 있도록 기능의 핵심인&rsquo; <a href="https://docs.microsoft.com/en-us/azure/azure-stack/user/azure-stack-version-profiles#summary-of-api-profiles" target="_blank">API 프로필을</a> 소개하는 것을 좋아합니다. API 프로필은 여러 Azure Cloud Services를 대상으로 하는 Azure 리소스 공급자 및 해당 API 버전 집합을 나타냅니다. 다음은 다양한 유형의 API 프로필입니다.</p>


  <ul>
      <li><strong>최신</strong></li>
  </ul>


  <p>여기에는 글로벌 Azure에서 릴리스된 최신 API 버전이 포함됩니다.</p>


  <ul>
      <li><strong>yyyy-mm-dd-hybrid</strong></li>
  </ul>


  <p>격년 주기로 릴리스된 이 릴리스는 여러 클라우드의 일관성과 안정성에 중점을 둡니다. 이 프로필은 최적의 Azure Stack 호환성을 대상으로 합니다.</p>


  <ul>
      <li><strong>yyyy-mm-dd-profile</strong></li>
  </ul>


  <p>이 기능은 최적의 안정성과 최신 기능 사이에 있습니다.</p>


  <p>이 게시물의 정보가 유용하기를 바랍니다! 하이브리드 애플리케이션 개발에 관한 새로운 주제에 대해 계속 지켜봐 주시기 바랍니다. Twitter에서 저와 제 팀을 자유롭게 <a href="https://www.twitter.com/rlfmendes" target="_blank">팔로우</a> 하세요.</p>


  <p><em>하이브리드 애플리케이션 개발에 대해 자세히 알아보려면 이전 게시물인<em> &quot;<a href="https://azure.microsoft.com/en-us/blog/developing-hybrid-applications-with-azure-stack/" target="_blank">Azure Stack을 사용하여 하이브리드 애플리케이션을 개발하는 방법을</a> 읽어보세요.&quot; </em></em></p>
