### YamlMime:Yaml
ms.openlocfilehash: 7092c16e5f0ba3243649203f93248da7e680573c
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139905712"
Slug: windows-azure-web-sites-how-application-strings-and-connection-strings-work
Title: 'azure 웹 사이트 Windows: 애플리케이션 문자열 및 연결 문자열의 작동 방식'
Summary: Windows Azure 웹 사이트에는 개발자가 웹 사이트와 연결된 구성 정보의 일부로 Azure에 키-값 문자열 쌍을 저장할 수 있는 편리한 기능이 있습니다.런타임에 Windows...
Content: >-
  Windows Azure 웹 사이트에는 개발자가 웹 사이트와 연결된 구성 정보의 일부로 Azure에 키-값 문자열 쌍을 저장할 수 있는 편리한 기능이 있습니다.런타임에 Windows Azure 웹 사이트는 자동으로 이러한 값을 검색하고 웹 사이트에서 실행되는 코드에 사용할 수 있도록 합니다.개발자는 연결 문자열로 사용할 키-값 쌍뿐만 아니라 일반 바닐라 키-값 쌍을 저장할 수 있습니다.


  키-값 쌍은 Windows Azure 웹 사이트 구성 저장소의 백그라운드에서 저장되므로 키-값 쌍을 웹 애플리케이션의 파일 콘텐츠에 저장할 필요가 없습니다.보안 관점에서 보면 암호가 있는 Sql 연결 문자열과 같은 중요한 정보가 web.config 또는 php.ini 파일에 일반 텍스트로 표시되지 않으므로 좋은 측면 이점이 있습니다.


  Azure Portal의 웹 사이트에 대한 "구성" 탭에서 키-값 쌍을 입력할 수 있습니다.아래 스크린샷은 키와 연결된 값을 입력할 수 있는 이 탭의 두 위치를 보여 줍니다.


  <img alt="" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/2275.app-1.png" border="0" />


  키-값 쌍을 "앱 설정" 또는 "연결 문자열"로 입력할 수 있습니다.유일한 차이점은 연결 문자열에 문자열 값이 데이터베이스 연결 문자열임을 Windows Azure Web Sites에 알리는 약간의 추가 메타데이터가 포함되어 있다는 것입니다.이는 웹 사이트에서 실행되는 다운스트림 코드에서 특수한 경우 연결 문자열에 대한 일부 동작에 유용할 수 있습니다.

  <h4>환경 변수로 Key-Value 쌍 검색</h4>

  개발자가 웹 사이트에 대한 키-값 쌍을 입력하면 웹 사이트 내에서 실행되는 코드로 런타임에 데이터를 검색할 수 있습니다.


  Azure 웹 사이트를 Windows 실행 중인 웹 사이트에 이러한 값을 제공하는 가장 일반적인 방법은 환경 변수를 사용하는 것입니다.예를 들어 이전 스크린샷에 표시된 데이터를 사용하여 환경 변수를 사용하여 데이터를 덤프하는 ASP.NET 코드 조각은 다음과 같습니다.


  <img alt="" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/2605.Screen-Shot-2013_2D00_07_2D00_17-at-10.12.22-AM.png" border="0" />


  이전 코드 조각의 예제 페이지 출력은 다음과 같습니다.


  <img alt="" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/4101.Screen-Shot-2013_2D00_07_2D00_17-at-10.13.06-AM.png" border="0" />


  [참고: Sql 연결 문자열의 흥미로운 부분은 별표가 있는 이 게시물에서 의도적으로 비워집니다.그러나 런타임에 서버 이름, 데이터베이스 이름, 사용자 이름 및 암호를 포함한 전체 연결 문자열을 검색할 수 있습니다.]


  "앱 설정" 및 "연결 문자열"에 대한 키-값 쌍은 환경 변수에 저장되므로 개발자는 Windows Azure 웹 사이트에서 지원되는 웹 애플리케이션 프레임워크에서 이러한 값을 쉽게 검색할 수 있습니다.예를 들어 다음은 php를 사용하여 동일한 설정을 검색하는 방법을 보여 주는 코드 조각입니다.


  <img alt="" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/4314.Screen-Shot-2013_2D00_07_2D00_17-at-10.45.32-AM.png" border="0" />


  이전 예제에서는 개별 키를 참조하는 명명 패턴을 발견했습니다."앱 설정"의 경우 해당 환경 변수의 이름 앞에 "APPSETTING_"이 추가됩니다.


  "연결 문자열"의 경우 데이터베이스 드롭다운에서 선택한 데이터베이스의 유형에 따라 환경 변수를 앞에 추가하는 데 사용되는 명명 규칙이 있습니다.구성된 연결 문자열이 드롭다운에서 "Sql Databases"를 선택했기 때문에 샘플 코드는 "SQLAZURECONNSTR_"를 사용합니다.


  데이터베이스 연결 문자열 형식의 전체 목록과 환경 변수 이름 지정에 사용되는 앞에 추가된 문자열은 다음과 같습니다.

  <p style="padding-left: 30px">"Sql Databases"를 선택하면 앞에 추가된 문자열은 "SQLAZURECONNSTR_"입니다.</p>

  <p style="padding-left: 30px">"SQL Server"을 선택하면 앞에 추가된 문자열이 "SQLCONNSTR_"입니다.</p>

  <p style="padding-left: 30px">"MySQL"을 선택하면 앞에 추가된 문자열이 "MYSQLCONNSTR_"입니다.</p>

  <p style="padding-left: 30px">"사용자 지정"을 선택하면 앞에 추가된 문자열이 "CUSTOMCONNSTR_"입니다.</p>


  <h4>ASP.NET Key-Value 쌍 검색</h4>

  지금까지 포털에 입력된 키-값 쌍이 환경 변수를 통해 웹 애플리케이션으로 이동하는 방법을 보여 줍니다.ASP.NET 웹 애플리케이션의 경우 .NET 4.5 프레임워크를 사용할 때도 사용할 수 있는 몇 가지 추가 런타임 매직이 있습니다(참고: .NET 4.5에만 존재하는 기능을 사용하므로 .NET 3.5를 선택하면 이 매직을 사용할 수 없습니다).다양한 키-값 형식의 이름을 살펴보면 의도적인 .NET 개발자에게 익숙한 것처럼 보입니다."앱 설정"은 .NET Framework <em>appSettings</em> 구성에 깔끔하게 매핑됩니다.마찬가지로 "연결 문자열"은 .NET Framework <em>connectionStrings 컬렉션에 해당합니다</em>.


  다음은 <em>System.Configuration</em> 형식을 사용하여 앱 설정을 참조하는 방법을 보여주는 또 다른 ASP.NET 코드 조각입니다.


  <img alt="" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/4276.Screen-Shot-2013_2D00_07_2D00_17-at-10.38.42-AM.png" border="0" />


  이전에 포털에 입력한 값이 <em>AppSettings</em> 컬렉션의 일부로 자동으로 표시되는지 확인합니다.애플리케이션 설정이 web.config 파일에 이미 있는 경우 Windows Azure 웹 사이트는 웹 사이트와 연결된 값을 사용하여 런타임에 자동으로 재정의합니다.


  연결 문자열은 비슷한 방식으로 작동하며, 약간의 추가 요구 사항이 있습니다.앞에서 웹 사이트와 연결된 "example-config_db"라는 연결 문자열이 있음을 기억하세요.웹 사이트의 web.config 파일이 connectionStrings/&gt;configuration 섹션에서 동일한 연결 문자열&lt;을 참조하는 경우 Windows Azure Web Sites는 포털에 표시된 값을 사용하여 런타임에 연결 문자열을 자동으로 업데이트합니다.


  그러나 Windows Azure 웹 사이트에서 web.config 이름이 일치하는 연결 문자열을 찾을 수 없는 경우 포털에 입력된 연결 문자열은 앞에서 설명한 것처럼 환경 변수로만 사용할 수 있습니다.


  예를 들어 다음과 같이 web.config 항목을 가정합니다.


  <img alt="" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/5342.Screen-Shot-2013_2D00_07_2D00_17-at-10.13.56-AM.png" border="0" />


  웹 사이트는 다음 코드 조각을 사용하여 환경에 구애받지 않은 방식으로 이 연결 문자열을 참조할 수 있습니다.


  <img alt="" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/4666.Screen-Shot-2013_2D00_07_2D00_17-at-10.23.32-AM.png" border="0" />


  이 코드가 개발자의 로컬 컴퓨터에서 실행되면 반환되는 값은 web.config 파일의 값이 됩니다.그러나 이 코드가 Windows Azure 웹 사이트에서 실행되면 반환되는 값이 포털에 입력된 값으로 재정의됩니다.


  <img alt="" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/0434.Screen-Shot-2013_2D00_07_2D00_17-at-10.24.35-AM.png" border="0" />


  애플리케이션이 배포된 위치에 관계없이 애플리케이션에서 올바른 연결 문자열 정보를 사용하는지 확인하는 오래된 개발자 문제를 깔끔하게 해결하기 때문에 이 기능은 정말 유용한 기능입니다.

  <h4>명령줄에서 Key-Value 쌍 구성</h4>

  포털에서 앱 설정 및 연결 문자열을 유지 관리하는 대신 개발자는 PowerShell cmdlet 또는 플랫폼 간 명령줄 도구를 사용하여 두 가지 유형의 키-값 쌍을 검색하고 수정할 수도 있습니다.


  예를 들어 다음 PowerShell 명령은 여러 앱 설정의 해시 테이블을 정의한 다음 <em>Set-AzureWebsite</em> cmdlet을 사용하여 Azure에 저장하여 "example-config"라는 웹 사이트와 연결합니다.


  <img alt="" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/3465.Screen-Shot-2013_2D00_07_2D00_17-at-10.39.44-AM.png" border="0" />


  ASP.NET 다음 코드 조각을 실행하면 원래 앱 설정("some-key-here")에 대한 값이 업데이트되었으며 두 번째 키-값 쌍("some-other-key")도 추가되었음을 알 수 있습니다.


  <img alt="" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/8737.Screen-Shot-2013_2D00_07_2D00_17-at-10.26.07-AM.png" border="0" />


  적용되는 변경 내용을 보여 주는 샘플 HTML 출력:

  <p style="padding-left: 30px">some-other-key &lt;&gt;--a-different-value some-key-here &lt;--&gt; changed-this-value</p>

  연결 문자열 업데이트는 비슷한 방식으로 작동하지만, 내부적으로 PowerShell cmdlet은 연결 문자열을 <em>ConnStringInfo</em> <em>개체 목록(Microsoft.WindowsAzure.Management.Utilities.Websites.Services.WebEntities.ConnStringInfo)으로&lt;&gt;</em> 처리하므로 구문은 약간 다릅니다.<em></em>


  다음 PowerShell 명령은 새 연결 문자열을 정의하고 웹 사이트와 연결된 연결 문자열 목록에 추가한 다음 모든 연결 문자열을 Azure에 다시 저장하는 방법을 보여 줍니다.


  <img alt="" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/5340.Screen-Shot-2013_2D00_07_2D00_17-at-10.26.48-AM.png" border="0" />


  속성의 <em>경우 $cs. 형식</em>: "Custom", "SQLAzure", "SQLServer" 및 "MySql" 형식을 정의하려면 다음 문자열을 사용할 수 있습니다.


  ASP.NET 다음 코드 조각을 실행하면 웹 사이트의 모든 연결 문자열이 나열됩니다.


  <img alt="" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/2018.Screen-Shot-2013_2D00_07_2D00_17-at-10.26.07-AM.png" border="0" />


  Windows Azure 웹 사이트에서 연결 문자열을 재정의하고 .NET Framework 연결 문자열 구성 컬렉션에서 구체화하려면 연결 문자열이 이미 web.config 정의되어 있어야 합니다.  이 예제 웹 사이트의 경우 아래와 같이 web.config 업데이트되었습니다.


  <img alt="" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/7418.Screen-Shot-2013_2D00_07_2D00_17-at-10.28.21-AM.png" border="0" />


  이제 ASP.NET 페이지가 실행되면 PowerShell을 통해 저장된 값을 사용하여 두 연결 문자열 값이 오버라이드되었음을 보여 줍니다(첫 번째 연결 문자열의 중요한 부분은 별표로 의도적으로 비워집니다.)


  <img alt="" src="https://azurecomcdn.azureedge.net/mediahandler/acomblog/media/Default/blog/5488.Screen-Shot-2013_2D00_07_2D00_17-at-10.28.27-AM.png" border="0" />

  <h4>요약</h4>

  이 게시물에서는 간단한 키-값 쌍의 구성 데이터를 웹 사이트와 쉽게 연결하고 런타임에 환경 변수로 검색하는 방법을 살펴보셨습니다.이 기능을 사용하면 웹 개발자는 이 데이터가 웹 사이트 구성 파일에 명확한 텍스트로 표시되지 않고도 구성 데이터를 안전하고 안전하게 저장할 수 있습니다. 또한 ASP.NET 사용하는 경우 .NET <em>AppSettings</em> 및 <em>ConnectionStrings</em> 구성 컬렉션의 값으로 값을 자동으로 구체화하는 약간의 추가 구성 "매직"이 있습니다.


  즐겨보세요!
