### YamlMime:Yaml
ms.openlocfilehash: 92c4991208ba7f1996222e4c41c95b3b3c9dd6d7
ms.sourcegitcommit: d03bdc7fe5447adb6530886aab848b75fe8fa8ee
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 03/11/2022
ms.locfileid: "139905695"
Slug: world-cities-day-2020-committing-to-sustainable-urban-environments
Title: '세계 도시의 날 2020: 지속 가능한 도시 환경에 전념'
Summary: 'Microsoft는 지속 가능성과 관련된 중요한 문제에 대한 집중과 헌신을 지속적으로 늘려가고 있습니다. 우리는 지속 가능성이 앞으로 여러 세대에 걸친 번성하는 미래를 보장하는 가장 중요한 방법 중 하나라는 것을 알고 있습니다. '
Content: >-
  <p>10월 31일은 관심 문제에 대해 대중을 교육하고, 정치적 의지와 자원을 동원하여 글로벌 문제를 해결하고 인류의 업적을 축하하고 강화하기 위해 설립된 세계 도시의 날입니다. 올해&rsquo; 테마 &lsquo;더 나은 도시, 더 나은 삶: 지역 사회와 도시를&rsquo; 소중히 여기는 것은 세계 도시화에 대한 국제 사회의&rsquo; 관심을 크게 촉진하고, 기회를 충족시키고, 도시화의 과제를 해결하고,&nbsp; 전 세계의 지속 가능한 도시 개발에 기여할 것으로 예상됩니다. 이것은 전 세계 사람들이 사회에 대한 이러한 긴급한 문제에 함께 모이는 중요한 순간입니다.</p>


  <p>Microsoft는 지속 가능성과 관련된 중요한 문제에 대한 집중과 헌신을 지속적으로 늘려가고 있습니다. 우리는 지속 가능성이 앞으로 여러 세대에 걸친 번성하는 미래를 보장하는 가장 중요한 방법 중 하나라는 것을 알고 있습니다. 그리고 지속 가능한 개발에는 경제 및 사회 발전과 함께 환경 문제를 해결하는 통합된 접근 방식이 필요하다는 것을 알고 있습니다.</p>


  <p>올해 세계 도시의 날을 맞아 기후 행동에 영향을 미치는 기술 파트너의 수를 축하합니다. 이는 또한 유엔&rsquo; 지속 <a href="https://www.un.org/sustainabledevelopment/sustainable-development-goals/" target="_blank">가능한 개발 목표</a>(SDG)에 부합하는 기회와 긍정적인 비즈니스 결과를 창출함으로써 보다 포용적인 경제를 가능하게 하는 솔루션을 강조한 <a href="https://aka.ms/partners/buildfor2030" target="_blank">BuildFor2030 캠페인의 초점#</a>이기도 합니다.</p>


  <h2>Microsoft 파트너: 도시를 위한 혁신적인 솔루션 구축 지원</h2>


  <p>Microsoft는 탄소 음수, 물 양성, 제로 폐기물 회사가 되기 위해 <a href="https://www.microsoft.com/en-us/sustainability/approach?activetab=pivot1%3aprimaryr4" target="_blank">최선을 다하고</a> 있습니다. 우리는 2025년까지 사용하는 것보다 더 많은 토지를 보호할 계획이며, 공기, 물 및 토지 관리에 대한 현명한 결정을 알리는 데 도움이 되는 행성 컴퓨터를 구축하고 있습니다. 이러한 목표를&rsquo; 달성하려면 우리와 함께 일하는 파트너의 지원이 필요합니다.</p>


  <p>Microsoft 파트너는 비즈니스와 도시에 고유한 아이디어를 제공하고 우리의 야망을 실현하고 비즈니스를 혁신하는 데 도움이 되는 대담한 계획을 실행하고 있습니다.</p>


  <p>Redmond Campuswhich&mdash;에서 더 적은 에너지를 사용하기 위해 스마트 시티 솔루션을 만들기 위해 파트너와 협력한 소규모 도시&mdash;입니다. 이 솔루션은 클라우드 서비스를 사용하여 매일 5억 개의 트랜잭션을 생성하는 2백만 개 이상의 데이터 요소를 연결하여 18개월 이내에 구현 회수를 통해 610 &ndash; %&nbsp;의 에너지 절감을 달성할 수 있도록 지원합니다.<sup> 1</sup></p>


  <p>파트너 솔루션은 지속 가능한 미래 구축을 지원합니다. 한 가지 예는 배출을 줄이기 위해 유틸리티 공급을 모니터링하여 도시&rsquo; 인프라를 지원하는 것입니다. 다른 솔루션으로는 대기 질 모니터링 및 개선, 재활용 관리, 태양열, 풍력 및 기타 재생 가능 에너지 사용을 최적화하는 데 도움이 됩니다. 마지막으로, 파트너는 물과 에너지 소비를 최소화하면서 주민의&rsquo; 편안함을 극대화하는 데 도움이 되는 스마트 빌딩 솔루션을 지원합니다. 파트너는 시민을 참여시키고 도시 전체의 지속 가능성 이니셔티브에 대한 참여를 측정하는 데 도움을 줄 수도 있습니다.</p>


  <p>Microsoft 파트너 솔루션은 지속 가능하고 안전하며 살기 좋은 도시를 지원합니다. BuildFor2030 캠페인, Microsoft <a href="https://aka.ms/appsource" target="_blank">AppSource</a> 및&nbsp;<a href="https://aka.ms/azuremarketplace" target="_blank">Azure Marketplace</a>에 등장하는 <a href="https://aka.ms/partners/buildfor2030" target="_blank">#</a> 더 많은 Microsoft 파트너 솔루션을 살펴보세요.</p>


  <hr>

  <p>1.<a href="https://www.microsoft.com/en-us/stories/88acres/88-acres-how-microsoft-quietly-built-the-city-of-the-future-chapter-4.aspx" target="_blank">Microsoft가 미래의 도시를 어떻게 조용히 건설했는지에</a> 대한 추가 세부 정보를 읽어 보십시오.</p>
